### ISSUE TITLE
PullRequest Merge 

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#1]
Pull request merge is untested

**Comment by k0shk0sh** [comment]
PullRequest Merge is currently hidden until I test it out.

**Comment by dhollinger** [comment]
Do you have a timeline on when this may make it into a release?

**Comment by k0shk0sh** [comment]
probably after 1.0.5 maybe another week. I will see if I can make in next release. it all depends on this coming weekend.

**Comment by k0shk0sh** [comment]
@dhollinger  this will be in tomorrow's release.
