### ISSUE TITLE
Unable to view commits from branches other than master

### ISSUE THREAD

**Issue by silverAndroid** [k0shk0sh/FastHub#100]
I noticed that even though I can view the files for a different branch, I can only view the commits for the branch on master

**Comment by k0shk0sh** [comment]
strange tho, as if I switched to another branch I could see that files changed, maybe a Github api problem or FastHub bug, can't be sure. could you point me to that repo so at least I could try it.

**Comment by silverAndroid** [comment]
I found it while browsing through the [flutter](https://github.com/flutter/flutter) repo, it defaults to the alpha branch but when I switched tabs to Commits, I noticed later, it was showing the master branch

**Comment by k0shk0sh** [comment]
Owh, now I got you, it has been fixed in #67 . this weekend will be shipped in 1.0.7

**Comment by silverAndroid** [comment]
Ohh ok, awesome!

**Comment by k0shk0sh** [comment]
Oops, I think got this wrong which now I only got it. it will be in 1.0.7 once i made the fix, I will reference it.
