### ISSUE TITLE
Multiple .gif images not showing properly

### ISSUE THREAD

**Issue by lil5** [k0shk0sh/FastHub#1000]
**FastHub Version: 4.3.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Wileyfox  
- **Brand:** Wileyfox  
- **Model:** Swift  
---

In an issue someone posted many `.gif`  images.
<https://github.com/sindresorhus/eslint-config-xo/issues/29>
In a normal web browser all seems normal.

The `.gif`s look like the frames have been mixed together.

**Comment by k0shk0sh** [comment]
congrats on opening the 1000 issue in FastHub :) .. I'll reply to your issue later ;)

**Comment by k0shk0sh** [comment]
They work fine, can you please update to 4.4.1 and let me know?

**Comment by lil5** [comment]
@k0shk0sh 

https://youtu.be/wYLaFn9EfZo

This may be an Android or Lineage bug, will update and see if it's the case...
