### ISSUE TITLE
Annoying and blocking "Too many changes to show" 

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1002]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

It seems that you added a threshold in a new version and don't show a diff in PR if file contains many changes. This is a horrible decision that significantly decrease the usability. First of all this threshold seems to be very small as most of changes are not being displayed more. Another point is that PR review feature is affected. You sell a PRO feature to perform a code review via app, however how could it be possible to left a comment if diff isn't displayed? Now I'm able to left comments to a few files in only, while for rest I should use the browser.

I'm very disappointed by this bug :pensive: For me it's about the current approach in general - in each version you introduce some new "features", that later create the usability issues (minor or major) :cry: It's a bit annoying as I feel like a beta tester.. Of course, you quickly fix them, but for couple of weeks we should live with them :( Could you please consider adding an advanced configuration for such things, so we could quickly disable/tune new features if there issues with them? For instance, it would be enough to tune the threshold value to work around the current issue, rather than be unable to perform a code review for a few weeks..

Thank you for your time and work on this project!

**Comment by k0shk0sh** [comment]
Will release it today 😅

**Comment by k0shk0sh** [comment]
there will be no need for threshold, there will be three scenarios,
1- max 100 changes 
2- if 1 is hit, I'll try and open it in full screen.
3- if 2 failed due to Android transaction is too large, open it in browser. 

that's what I can do!

**Comment by zvirja** [comment]
@k0shk0sh Thanks for looking into this. Sounds like a plan. Hope, I'll not meet that "hard limit" with transaction with regular PRs..

**Comment by yakov116** [comment]
@k0shk0sh what changed?
Side note: this hard limit is killing me! :triumph:
