### ISSUE TITLE
Change the Floating Action Button behavior

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#1005]
**FastHub Version: 4.3.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

Changing FAB behavior would make the section more clear, adapting all items to the same design  lines, and in this way you don't have to dismiss the bottom bar for showing the fab. The animation can be customized in Settings.
For the last updated checkbox, you can make the text to be changed dynamically basing on preferences

![](https://i.imgur.com/bZuOYvA.png)

**Comment by k0shk0sh** [comment]
sorry, but no customization for that as I'm not interested to do complicte things any further in there.

now for the dynamic checkbox, this won't happen either, you go search/filter issues use it which has more functionality to do what it intended to do.
