### ISSUE TITLE
Code search doesn't work

### ISSUE THREAD

**Issue by adamkay** [k0shk0sh/FastHub#1006]
**FastHub Version: 4.3.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** Huawei  
- **Model:** G620S-L01  
---

I've tried to search in code several times and it doesn't seem to work. It shows the number of search results, but the list is empty. 

Screenshot:
https://postimg.org/image/lclwx60g5/

**Comment by k0shk0sh** [comment]
Search results has an API limit, therefore the response never returned any results, try to be more specific for the results to lesser.

**Comment by yakov116** [comment]
@adamkay to explain a bit more what @k0shk0sh said. If the search returns too many matches nothing is shown

**Comment by yakov116** [comment]
@k0shk0sh Maybe we should display "Too many results, please refine your search and try again."
