### ISSUE TITLE
Reply to comments 

### ISSUE THREAD

**Issue by EvilOne** [k0shk0sh/FastHub#1009]
**FastHub Version: 4.3.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

I tap on comment under a comment I want to reply to. Type my message, hit send. I see a blue activity indicator, then screen comes back to the message I typed. I have to cancel it because it just keeps doing the same thing again.

**Comment by yakov116** [comment]
@EvilOne your talking about the quick comment? (The one on the bottom)

**Comment by k0shk0sh** [comment]
could you elaborate more? because I didn't get you!

**Comment by k0shk0sh** [comment]
do you mean in PR reviews?
