### ISSUE TITLE
Line breaks in ordered list

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1012]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

Markdown renderer adds invalid line breaks in ordered list. See the following comment (3rd comment from start): https://github.com/AutoFixture/AutoFixture/issues/842#issuecomment-332236665. If you open comment in the browser, you'll see that everything looks fine. :disappointed:

**Comment by k0shk0sh** [comment]
According to the response from github, look at it by yourself and tell me its FastHub fault? :D 

```
<ol>\n<li>\n<p>In fact, AutoFixture is not the best place for this interface, as it should \"know nothing\" about the potential glue libraries. While we introduce this interface there, the library itself will not use it - those are glue libraries, which are the main clients of this interface. Therefore, it's a bit \"dirty\" approach. From architectural perspective, we should create a standalone package with that single interface and later reference that package on our glue libraries.</p>\n</li>\n<li>\n<p>Suppose, we create \"active\" customization attribute in AutoMoq package, like <code>FrozenMock</code>. Later user installs the AutoMoq library. While this attribute is available to the user, he can use it only if he installs xUnit or NUnit integration libraries. What looks weird, that you should install some other package which is not directly referenced to be able to use some particular feature.</p>\n</li>\n</ol>\n
```

**Comment by yakov116** [comment]
@k0shk0sh time to move to GraphQL :stuck_out_tongue_winking_eye:

**Comment by zvirja** [comment]
@k0shk0sh It's hard for me too see what's wrong is with markup as I don't have a laptop with me to test the browser behavior. Do you want to say that the `<p>`  tag inside the `<li>`  tag should cause the line break? In this case, why does the browser render the content correctly? :confused:

**Comment by k0shk0sh** [comment]
not `p` but `\n` is a line break !

**Comment by zvirja** [comment]
For me that isn't too obvious, as whitespace characters are usually ignored in html..

**Comment by k0shk0sh** [comment]
they are ignored in html but who told you we use html? do you know how much efforts for making the whole html tags to be rendered in Android textview?  and java pretty much understands newlines.

**Comment by zvirja** [comment]
> do you know how much efforts for making the whole html tags to be rendered in Android textview?

No, I don't - thought that you use some lib for that.. :blush:

**Comment by k0shk0sh** [comment]
I did, but I had to write most of them manually

![](https://i.imgur.com/OynEHhZ.jpg)

**Comment by k0shk0sh** [comment]
1.  one
2. two
3. three
4. four

**Comment by k0shk0sh** [comment]
could you elaborate on why this work fine but not in the issue u linked?

![](https://i.imgur.com/qwyihE3.jpg)

**Comment by k0shk0sh** [comment]
1. Hdhd
1. Hdhdh
1. Hshs
