### ISSUE TITLE
Jump to the comment for the comment link

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1013]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

Currently when you have a link to the comment, FastHub opens the thread only, however doesn't jump to the comment itself. Consider this link as example: https://github.com/AutoFixture/AutoFixture/issues/842#issuecomment-332236665. While the thread is opened, you have no clue which particular comment is referenced. 

If you open this link in a browser, it will jump and highlight the comment.

This is very important feature and I feel the pain of its absence almost every day. :cry:

The overall experience becomes even worse, because FastHub application intercept links to the github. Therefore, when I receive an email from GitHub and want to jump to the comment, link is opened in the app, rather than in the browser and I should find the comment manually.

Please please please add this feature :) Also don't forget about paging and highlighting of the comment, so you clearly see which exact one has been pointed.

Thank you! :raised_hands:

**Comment by zvirja** [comment]
Link to the duplicated link please :blush:

**Comment by k0shk0sh** [comment]
could u search for it? my internet is shitty

**Comment by zvirja** [comment]
I've reviewed opened issues for 3 times, but cannot see it. Pleae post a link when your Internet is OK back..

**Comment by k0shk0sh** [comment]
and please Alex, search for the issue before opening new one, as much as I appreciate your efforts, but I want you to make an extra step in your effort to search ?

**Comment by yakov116** [comment]
@k0shk0sh @zvirja #988 is the one I found

**Comment by k0shk0sh** [comment]
there are more, closed ones.

**Comment by zvirja** [comment]
@yakov116 This one is closed.

> and please Alex, search for the issue before opening new one

While I may admit that sometimes I post duplicates, this time I'm unable to see the _opened_ issues about this feature. Therefore, I honestly searched through the list of opened issues, found nothing and registered this one. Probably, I missed something. 

In any case, next time will try to search more thoroughly before opening the issue.

**Comment by k0shk0sh** [comment]
thanks man and sorry if I'm asking for too much, they are closed matter of fact because I remembered last time I wasn't gonna implement it. I'll look for the first one and reopen tomorrow.

**Comment by zvirja** [comment]
@k0shk0sh Have you reopened any issue? Just want to ensure that we haven't forgot about the issue..

**Comment by zvirja** [comment]
@k0shk0sh Are you here? 😉 Just want to ensure that we don't miss the feature and it's in backlog..

**Comment by yakov116** [comment]
@k0shk0sh no he is in another world 💤

**Comment by k0shk0sh** [comment]
ignore: 

https://github.com/jashkenas/underscore/issues/1805#issuecomment-53622925


second page: https://github.com/jashkenas/underscore/issues/1805#issuecomment-53972612

**Comment by yakov116** [comment]
@k0shk0sh can we highlight the comment like you do when going to a specific 
Iine in code?
