### ISSUE TITLE
Commenting on a commit under certain repos fails

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#1014]
**FastHub Version: 4.3.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** oneplus  
- **Model:** OnePlus One  
---

Similarly to issue 952, when I try to post a comment (using the quick comment  box) to a commit that was pushed in the lawnchair repo it won't let me, but it works fine from the mobile web. Back to FastHub app, I tried the same steps to comment here (FastHub repo) on a commit and it worked as well.

This time around I think it's the authorization/access thingy ?

**Comment by yakov116** [comment]
@Younes-L using the regular comment works?

**Comment by Younes-L** [comment]
@yakov116 how do I do that ? 
And btw it says "not found" in a red toast

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/30883021-e5546b28-a2d8-11e7-87d5-986e377cd6c4.png)

**Comment by k0shk0sh** [comment]
are they org repos??? 
why did you assume its FastHub fault? if you could comment on some and some not???

**Comment by Younes-L** [comment]
@yakov116  from what I can see that is the same quick add box I used, the expand button only makes the box full screen but when sending it reverts to the small one i can submit the comment

**Comment by Younes-L** [comment]
@k0shk0sh sorry my description was all over the place ^^

I posted a comment using mobile github and it worked, that's why I assumed it was a FastHub issue.

**Comment by yakov116** [comment]
@Younes-L what?

**Comment by Younes-L** [comment]
@yakov116 here's the screen I'm trying to get into when replying, to see if it makes a difference

![](https://i.imgur.com/vNc2rxD.jpg)

If I go to an issue and hit the reply button, this screen shows up

But if I do the same on a commit, it just focuses the quick comment box instead , and even when expanded it's different (doesn't send while expanded, doesn't show previous replay)

**Comment by k0shk0sh** [comment]
ddc41e36a79028e52ea3eb190a47396e62dc12a0

**Comment by Younes-L** [comment]
Sorry for bugging you again guys, but it's happening to me on v4.5.2 ~ 4.5.5

Can you check if commenting on commits works ?
It fails for me on this commit https://github.com/Deletescape-Media/Lawnchair/commit/22a275186afb2c3b2dab0f9512fb8f3d8d3eed6b

@k0shk0sh @yakov116

**Comment by k0shk0sh** [comment]
It worked on my side but not on that repo.
