### ISSUE TITLE
Issues don't show the title on project page

### ISSUE THREAD

**Issue by Aphlax** [k0shk0sh/FastHub#1016]
**FastHub Version: 4.3.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

Issues in project columns show up as
User/repo/issueId, e.g. Aphlax/Test/47

**Comment by yakov116** [comment]
@Aphlax Can you provide a link please?

Thanks for your feedback

**Comment by k0shk0sh** [comment]
yep I'm aware of that and it's GitHub limitations so can't do anything until they fix their graphql api!!

**Comment by yakov116** [comment]
@k0shk0sh Lets leave it open so we don't have people opening new issues
