### ISSUE TITLE
Invalid indentation for quotation and header

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1017]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

Markdown renderer doesn't render the correct indentation for quotation and headers. See a sample below.

If you open this issue in a browser, you'll see the correct indentation.

As I mentioned in other issue, it's important for this app to have valid markdown rendering, as otherwise I'd need to see how it looks in browser when I update something important (e.g. `Readme`). Also it's annoying when you compose a comment and add unnecessary line breaks because your text looks shitty, and later it appears that markdown is fine and the issue is with the app instead.. :disappointed:

Thank you for your time! :smile_cat:

-------

Here is some text.
> This quotation is expected to have indent between the previous line - same as between the line below. 

Some reply to the quote.

Here is some text.
### This header is expected to have indent between the previous line.

**Comment by k0shk0sh** [comment]
# This header is expected to have indent between the previous line.

> This quotation is expected to have indent between the previous line - same as between the line below.

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/8WkC08J.png)

**Comment by zvirja** [comment]
@k0shk0sh Have I spotted it wrongly, or now there is an extra indent before the "Some reply to the quote" text (the first screenshot)? :sweat:
