### ISSUE TITLE
Diagonal scroll momentum is wierd when viewing code

### ISSUE THREAD

**Issue by aaronduino** [k0shk0sh/FastHub#1018]
**FastHub Version: 4.3.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5  
---

Vertically and horizontally, the momentum (the thing that makes the screen keep on scrolling for a little bit after you stop swiping) is great.

When you swipe diagonally, though, the momentum is wierd. Instead of scrolling diagonal (vertically and horizontally at the same time), either vertical or horizontal momentum seems to be applied first, and the other direction's movement happens after the first one's movement is complete.

Btw, thanks for the app-- it's super helpful.

**Comment by yakov116** [comment]
@aaronduinoyour talking about where? Code? Markdown?

Thanks for your feedback

**Comment by aaronduino** [comment]
@yakov116 no problem

**Comment by aaronduino** [comment]
btw, after looking at it further, I think this may be caused by the title bar going up/down when you change scrolling direction
