### ISSUE TITLE
Start screen 

### ISSUE THREAD

**Issue by branoholy** [k0shk0sh/FastHub#1019]
**FastHub Version: 4.3.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

Everything's fine so far but it would be great to be able to set some different screen as the start screen. I would rather see the pinned repositories screen than the feed screen when I open the app.

**Comment by yakov116** [comment]
@branoholy please search before opening an issue 

Thanks for your feedback

**Comment by k0shk0sh** [comment]
use app shortcuts!!!!

**Comment by branoholy** [comment]
Do app shortcuts allow me to start the pinned repositories? I don't see that option. I see only Profile, Pull Request, Issues, and Feeds.

**Comment by k0shk0sh** [comment]
I guess it's due to limitation in number of shortcuts, will remove feeds in next release

**Comment by branoholy** [comment]
Cool, thanks!
