### ISSUE TITLE
Weird bug when posting new issue comment

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#102]
![screenshot_20170308-192828](https://cloud.githubusercontent.com/assets/5065698/23717863/c422939a-0435-11e7-99d2-e9f3630cfa15.png)
See the margin between the last and second last comment. This is there when you post a comment. It goes away when you refresh the list

**Comment by k0shk0sh** [comment]
welcome to recyclerview when calling notifyItemInserted(index) does not work & adding on top of it notifyItemRangeInserted(index, total) does not fix it. I guess will just notify the whole adapter and  that would fix it.

**Comment by HeinrichReimer** [comment]
Don't do that. Using `RecyclerView`'s `notifyItem...()`methods are the way to go. You should probably check your item animator.
