### ISSUE TITLE
Use standard Android loading spinner

### ISSUE THREAD

**Issue by seaneking** [k0shk0sh/FastHub#1020]
**FastHub Version: 4.3.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

I don't know if its just me, but I find the bouncing blue ball spinner really jarring and, to be honest, an unpolished and nasty edge of an otherwise smooth app.

Moreover though should stick with standard material design conventions in an Android app, especially since other loading states in the app (eg: pull to refresh) _do_ use standard spinners, makes it all a bit of a jumble. I'd consider the bouncing ball a UI regression.

**Comment by seaneking** [comment]
Marginally related to #998

**Comment by k0shk0sh** [comment]
well, most feedbacks, people like it, I'm really over listing to individual opinion about something, because when I do tbat I make thousands mad. so this gonna remain the same until majority says otherwise.

thanks sean.
