### ISSUE TITLE
Unable to check checkboxes in comments

### ISSUE THREAD

**Issue by seaneking** [k0shk0sh/FastHub#1021]
**FastHub Version: 4.3.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

Bug
Not able to mark/unmark checkboxes in comments, ie:

- [ ] Try and check me in FastHub

**Comment by yakov116** [comment]
@seanekingots not possible due to text view. Edit the post and add an 'X'
