### ISSUE TITLE
Fix some Spanish strings

### ISSUE THREAD

**Issue by Dahnark** [k0shk0sh/FastHub#1023]
**FastHub Version: 4.3.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

Hello, I have seen a few errors in the Spanish strings. Is there any place to fix it?

**Comment by yakov116** [comment]
@Dahnark Sure make a pull request
