### ISSUE TITLE
Make selected text a link

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1024]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

If you select any text and press for example the `bold`  button, the selected text will be surrounded by the underscores. However, if you select any text and press the `link` button, the selected text will not be transformed to a link. 

What I expect:
1. You write the "text" text, select it and press the `link` button.
1. Dialog appears. The link text field contains the "text" text and focus is set in the `link` input.
1. You fill the link and press the `insert` button.
1. Link is inserted instead of the selected text.

This behavior will be logical and cool, as I often decide to transform parts of existing comment to links.

Thanks :angel:

**Comment by yakov116** [comment]
@zvirja Good idea! I agree

**Comment by zvirja** [comment]
@k0shk0sh Could you please reopen this issue? It seems that I wasn't clear and confused you. I expected that you will substitute the selected text to the "Link text" field. Usually I want keep the text and simply make it a link.

With current implementation it's non-usable, unfortunately. Moreover, it does opposite to what I expect.. 

Sorry again if I wasn't clear enough :cry:

**Comment by k0shk0sh** [comment]
done.
