### ISSUE TITLE
Preview resets the cursor position

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1025]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

When you write a comment, switch to the preview mode and return back, the cursor is set at then end of the comment. Could you please preserve the cursor position before the preview?

**Comment by k0shk0sh** [comment]
simply press back instead of the check button, basically when u press the check button means that its treated as new so, I can't do much in here. its more like a user fault that the app fault.

**Comment by zvirja** [comment]
@k0shk0sh Not sure I got your idea. Please review the scenario again:
1. Enter the full screen editor mode and type some text
1. Put cursor at the the middle
1. Press the `preview`  button
1. Press the `preview`  button again to return to the edit mode.

Now the cursor is at the end. Where is the "user's fault here"? :disappointed:

I cannot press the `back` button, as app exists the comment and asks me whether I want to discard the change.

Also it doest look like a new view is created..

**Comment by k0shk0sh** [comment]
damn, I should really go and sleep, I'm still hangover, I literally misunderstood the issue 😫

**Comment by k0shk0sh** [comment]
ddc41e36a79028e52ea3eb190a47396e62dc12a0
