### ISSUE TITLE
Crash on tap the picture

### ISSUE THREAD

**Issue by woeijiunn88** [k0shk0sh/FastHub#1026]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone3  
---

Just like the title say.
Fasthub crashed after open the image in comment section, but the picture can shown in browser, but the Fasthub app crashed.:fearful:

**Comment by woeijiunn88** [comment]
May refer to issue #1012 in this repo.

**Comment by yakov116** [comment]
@woeijiunn88 do you have chrome installed?

**Comment by woeijiunn88** [comment]
Yes, chrome installed.
Lol another thing also weird,
I tap on this issue #1012 also can crashed:joy:

**Comment by k0shk0sh** [comment]
I think its phone related stuff, for example you were able to open it and now you can't? that's weird. 
according to crashlog it seems that your phone textView has a bug!!!

**Comment by woeijiunn88** [comment]
I also think maybe my phone problem after I reinstall :sweat:
I've forgot previously got this issue or not (previously I rarely access to this app:joy:), and found this issue just now only...

I didn't know through about what is textview LOL:joy:

**Comment by k0shk0sh** [comment]
Its more like an OS bug, that's what OEMs do with Android, they fuck it up and make users blame Android 🤷‍♂️

**Comment by woeijiunn88** [comment]
Ok, i see😏
