### ISSUE TITLE
CLI in-app

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1030]
**FastHub Version:*4.3.0*    <>
**Android Version:*5.0.1 (sdk21)*  
**Device Information:**  
- MANUFACTURER: lge  
- BRAND: lge  
- MODEL: lg g3 cat.6  
---
git cli looking in app
for folders in local, `git init` then does the git work for the user
has commands such as `git commit`, `git branch` etc
If you need more explaination, i will do it later

**Comment by k0shk0sh** [comment]
Thanks @cozyplanes but this isn't in any of my plans :)
