### ISSUE TITLE
Gist saving doesn' t work correctl

### ISSUE THREAD

**Issue by rhalff** [k0shk0sh/FastHub#1031]
**FastHub Version: 4.3.0**  
**Android Version: 5.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** Archos  
- **Brand:** archos  
- **Model:** 55 Cobalt Plus  
---

Hi.

I've lost edits several times when editing gists, when I leave a gist I want it to be saved. Right now you first go back and then have to save and even that doesn't work correctly.

Made my todo list two times and lost it two times which is rather counter productive :)

Greetings,
Rob Halff

**Comment by k0shk0sh** [comment]
hello Rob Halff,

you'll have to press save in order for it to be submitted to GitHub.

**Comment by k0shk0sh** [comment]
there is a submit button in top, you'll need to hit it once you done with your editing :). 

do let me know if you encountered any other issues
