### ISSUE TITLE
Enhancement: Comment views could be cleaner

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [k0shk0sh/FastHub#1032]
**FastHub Version:**   4.3.0
**Android Version:**  8.0
---

Comment items in lists (and elsewhere in the app) currently use overflow menus, like this:
![screenshot_20170929-215046](https://user-images.githubusercontent.com/6058082/31033454-680d9cd6-a560-11e7-99fe-06ffa10af7c9.png)

Instead, they could be collapsed until pressed, like this:
![screenshot from 2017-09-29 21-54-05](https://user-images.githubusercontent.com/6058082/31033577-ec6c3a8c-a560-11e7-9515-2f5ca1e4bb04.png)

Once they are pressed, they could transition (with animation) into their expanded state, like this:
![screenshot from 2017-09-29 21-53-26](https://user-images.githubusercontent.com/6058082/31033661-3664fd0e-a561-11e7-91d9-d674d3022ac6.png)

Both of these sample pictures were taken from [Nick Butcher's "Material Improvements" I/O 2016 talk](https://youtu.be/EjTJIDKT72M?t=335), where it is very clearly explained how this design pattern is achieved.

**Comment by k0shk0sh** [comment]
I'm aware of that, this will work perfectly if the menu is short with just two items or three as max plus the comment is short, but as you know, comments in GitHub aren't really comments.

I really could use good design for the comments but currently I'm tackling more important issues and can't do everything alone while having full time job.
but I promise you soon hopefully I'll change that design.

P.S: if you have some design ideas, you could join our slack and message me directly, I'll be happy to talk more about it :)

**Comment by aleksandar-stefanovic** [comment]
I'm sorry, I just wanted your opinion on it, I wanted to implement it myself, but wanted to check with you first  (to see whether you'd accept a change like that).

**Comment by k0shk0sh** [comment]
I would love that, but we could work on a similar approach together and you could take it over :)
