### ISSUE TITLE
[FR]Remember language selected in trending

### ISSUE THREAD

**Issue by maple3142** [k0shk0sh/FastHub#1035]
**FastHub Version: 4.3.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

As title

**Comment by k0shk0sh** [comment]
as title? please could you put some efforts on writing good description of what you want?

**Comment by maple3142** [comment]
for example:
In "trending" page,I use "javascript" filter.
Next time I enter "trending" page will auto select "javascript" filter
