### ISSUE TITLE
See labels from list

### ISSUE THREAD

**Issue by Nxt3** [k0shk0sh/FastHub#1037]
**FastHub Version: 4.3.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

Right now to see labels for an issue, you have to long press on an issue. If I click on an issue normally, I have to scroll down to wherever the issues were assigned labels--they don't appear at the top or anything.

**Comment by k0shk0sh** [comment]
as you said, you either scroll or long press. its annoying I know, but as you know, labels are added dynamically and therefore there is no reason for me to duplicate them in the issue.

**Comment by Nxt3** [comment]
That is annoying. It's only available in one view. why not make it so when I click an issue it pops-up as if I long pressed then? I'd rather do that.

**Comment by Nxt3** [comment]
Why not consolidate the views? It's just bad UX

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/zcCrNWt.png)

**Comment by Nxt3** [comment]
thank you!
