### ISSUE TITLE
Project Card title showing link if converted to issue

### ISSUE THREAD

**Issue by Oisins** [k0shk0sh/FastHub#1038]
**FastHub Version: 4.3.0**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** Huawei  
- **Model:** P8 Lite  
---

If a project Card has been converted to a issue it shows the link to the issue, not the title.

**Comment by Oisins** [comment]
Sorry, accidentally only searched open issues

**Comment by k0shk0sh** [comment]
@Oisins now prob mate :)
