### ISSUE TITLE
Support For GitHub showcase

### ISSUE THREAD

**Issue by Shriram-Balaji** [k0shk0sh/FastHub#1039]
**FastHub Version: 4.3.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LYF  
- **Brand:** LYF  
- **Model:** LS-5201  
---
**Git Showcase Support** 

Git has a special listing which it calls "showcases". These are categorized listings of the top repos in a specific category . Please add support for that.
 https://github.com/showcases/

**Comment by k0shk0sh** [comment]
thanks for the suggestion, but I'm not interested in this as this will require alot of scrapping. 

for trending language names are saved locally and therefore less scrapping is done and less complicity is going on. 
if ever GitHub did an api for that, please do reopen it, which I doubt.
