### ISSUE TITLE
Issue description is deleted when navigating back from the editor

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#104]
If you type an issue description in the markdown editor and go back using either the up arrow in the toolbar or the back arrow in the navigation bar, the text you typed is not saved like when you click the check icon.
My suggestion for every action:

- Back (in system navigation bar): Save progress and go back
- Check mark: Same as back
- Up icon (in toolbar): Replace with cancel icon (**×**) and when user clicks it discard changes and go back but let users confirm that with a dialog or provide an undo snack bar
- Send icon (not currently implemented): Use a send icon on the right side of the toolbar to immediately save changes and send the issue

**Comment by k0shk0sh** [comment]
mistakenly closed this instead of provide description.
