### ISSUE TITLE
FAQ looking weird

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1040]
**FastHub Version: 4.4.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

Again me, the typo finder master.
At the last, student something, rate fasthub in play store seems to be incorrect. I dont know what kosh wanted to do so i will not send a pr.

**Comment by k0shk0sh** [comment]
hmmm Ian,  rate in fh in play store = open up play store, search fasthub & rate it 5 stars. 

what's incorrect about it?

**Comment by cozyplanes** [comment]
i cant click in my phone. and you covered with the tag `<li>` which doesnt seem to be a link

**Comment by cozyplanes** [comment]
and there is no new line

**Comment by cozyplanes** [comment]
![](https://i.imgur.com/J8KWMAH.png)

**Comment by cozyplanes** [comment]
any ideas?

**Comment by cozyplanes** [comment]
waiting for an answer regarding 
`Rate FastHub in the Play Store`
Is this a link or what?

**Comment by cozyplanes** [comment]
@k0shk0sh

**Comment by yakov116** [comment]
@cozyplanes he is still :zzz:

**Comment by cozyplanes** [comment]
@yakov116 he is alive, he replied to my PR

**Comment by k0shk0sh** [comment]
it's not a link

**Comment by cozyplanes** [comment]
so why did you put there?
if you just want to put that in there, i think there should be a new line

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/JfQmyuX.png)

**Comment by cozyplanes** [comment]
@k0shk0sh well it looks strange in my phone
i am not an html expert, so what does the tag `<p>` and `<li>` each mean?

**Comment by cozyplanes** [comment]
um why? in my phone there isnt • in front of rate, write etc. look pic above. it may be because my phone is quite old... can you check with other sdk(phones)? 
(...android fragmentation)

**Comment by k0shk0sh** [comment]
that's the thing, I ain't gonna do specific phone fixes, fix it for you, break on the other million phones lol.

**Comment by cozyplanes** [comment]
(lost words by such a powerful statement)
