### ISSUE TITLE
Expanding view of changes made to a file in a commit not possible

### ISSUE THREAD

**Issue by d-Rickyy-b** [k0shk0sh/FastHub#1042]
**FastHub Version:**  4.4.0
**Android Version:**  7.1.1
**Device Information:**  
- MANUFACTURER: OnePlus Science & Technology Co., Ltd.
- BRAND: OnePlus
- MODEL: OnePlus 3  
---
### Description
Sometimes (mostly after rotating the phone to landscape) it's not possible to expand the changes made to a file in a commit.

### Steps to reproduce
1) Open a repository
2) Open tab "Commits"
3) Check if expanding the card for a changed file works
4) If yes, rotate the phone to landscape mode

### Expected behaviour
The card for the file expands, showing the changes made to that file

### Actual behaviour
Expanding of the changes made to a file is not possible anymore. The arrow icon is animated, but expanding doesn't work

![telegram_2017-10-01_14-39-17](https://user-images.githubusercontent.com/5798157/31054624-c2e32e44-a6b6-11e7-918b-0351e0657a44.png)

**Comment by k0shk0sh** [comment]
thanks for the descriptive & well organized issue.

**Comment by yakov116** [comment]
@k0shk0sh any update?
