### ISSUE TITLE
Erm... How would I edit a file? I really like coding on my phone

### ISSUE THREAD

**Issue by toastflaming** [k0shk0sh/FastHub#1047]
**FastHub Version: 4.4.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

**Comment by yakov116** [comment]
@toastflaming go to files click  the three dots and click edit.

@k0shk0sh I think we need to make an in app FAQ with pictures

**Comment by k0shk0sh** [comment]
Hmmm, I don't think for such functionality we need to do something like that, its basics of android and every android user should know about it :p but I definitely agree that there are 100s of features users are not aware of :D

**Comment by yakov116** [comment]
@k0shk0sh if you make a template I can work on it

**Comment by k0shk0sh** [comment]
maybe you could make screenshots using phone, I could later work on making a complete guide of whole features. 

make sure the screenshots are taken under FH repo :p

**Comment by yakov116** [comment]
@k0shk0sh tablet OK?


_Sent from my Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_ :grinning:

**Comment by k0shk0sh** [comment]
noooo :p phone UI is better :p and smaller :p

**Comment by yakov116** [comment]
@k0shk0sh have an idea. I'll do tablet and then we will change to phone pictures.



_Sent from my Nexus 9 :stuck_out_tongue_winking_eye: using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
no yanki, phoneeeeeeee, because UI look better in there. 

don't waste time on tablet because I'll never do it :p

**Comment by yakov116** [comment]
@k0shk0sh OK what pictures do u need? Or do you want me to make a list?

**Comment by k0shk0sh** [comment]
of all features, like for example long press issue/pr, stars and forks etc. 
the things that you think aren't visible or easy to find

**Comment by yakov116** [comment]
@k0shk0shsome things may need gifs

**Comment by cozyplanes** [comment]
(takes 10 yrs to finish)

**Comment by yakov116** [comment]
@cozyplanes I sure hope not
