### ISSUE TITLE
Support for image attachments when posting an issue or issue comment in Markdown editor.

### ISSUE THREAD

**Issue by heinrichreimer** [k0shk0sh/FastHub#105]

**Comment by GeorgeWL** [comment]
Sorry,  the title isn't as clearly worded.

**Comment by k0shk0sh** [comment]
Renamed the issue to have more specific meaning, removed support to attach file since GitHub API doesn't have this feature.

**Comment by GeorgeWL** [comment]
@k0shk0sh a solution I've seen many do is to instead use the imgur API, and then use the github API to format the link that imgur provides.

**Comment by k0shk0sh** [comment]
@GeorgeWL the solution I provided is actually to use the imgur API to upload the image & then append it as `![name](url)` inserting the URLS now is much easier as now you could type the title & link is a dialog and FastHub will append it.

**Comment by GeorgeWL** [comment]
Oops I accidentally tapped delete instead of edit.

**Comment by k0shk0sh** [comment]
@GeorgeWL old comment ( a solution I've seen many do is to instead use the imgur API, and then use the github API to format the link that imgur provides.)

**Comment by zanona** [comment]
Is there any solution for addijg images to issues right now? I believe I am missing something because I can't see any way to upload it through the app in the new issue view?

**Comment by GeorgeWL** [comment]
Press the picture of an image ![](https://i.imgur.com/6Hs4kWz.png)

Then select, then insert.

**Comment by GeorgeWL** [comment]
@zanona

**Comment by zanona** [comment]
@GeorgeWL thanks so much. I didn't know I could scroll that toolbar as well. Wasn't seeing the image icon before :astonished:

**Comment by GeorgeWL** [comment]
We could possibly add a slight edge-shadow to it to let folks know it's scrollable @k0shk0sh ?
