### ISSUE TITLE
quangtho92

### ISSUE THREAD

**Issue by thokaka92** [k0shk0sh/FastHub#1051]
**FastHub Version: 4.4.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P10  
---

_Sent from my P10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@thokaka92 What?
