### ISSUE TITLE
[FR]. Allow adding lables and milestone when opening an issue

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#1052]
**FastHub Version: 4.4.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** HTC  
- **Model:** Nexus 9  
---

Right not you can only do it after opening an issue.

Would be nice to be able to close and comment too when replying.

Side note: when replying the reply is missing a space after the user name

**Comment by k0shk0sh** [comment]
the irony, we tell people to search before posting new issue but we don't 😂😂😂😂😂😂😂😂😂😂

**Comment by k0shk0sh** [comment]
#657

**Comment by yakov116** [comment]
@k0shk0sh um... I open it for another reason! And by the way there is no open issue. 

Opened so that we can keep track of what we wanted added

**Comment by k0shk0sh** [comment]
have you seen the issue I linked?

**Comment by yakov116** [comment]
@k0shk0sh now I did. I opened for comment and close but on the way I threw in some other stuff

**Comment by k0shk0sh** [comment]
I know that's why I was surprised 🤣

**Comment by yakov116** [comment]
@k0shk0sh lol!
