### ISSUE TITLE
Cannot render emojis in changelog

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#1053]
**FastHub Version: 4.4.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

When displaying the updated changelog the parser doesn't converts the emoji string to an effective emoji

![](https://i.imgur.com/sbhFZgO.png)

**Comment by yakov116** [comment]
@k0shk0sh it's only in the pop up change log... not in releases
