### ISSUE TITLE
[Feature request] Tabbed markdown editor

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#1054]
**FastHub Version: 4.4.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

## Current view problem
The current view is very compact but to switch between normal and preview mode you need to activate a button, it's not the best idea

## New view
The new Markdown editor view should be a tabbed activity. It will be useful because:
- It will remove the button from the sticky menu and you can have more scroll space
- It's a more intuitive and good-looking feature
- it will optimize the user experience and the user interface of Markdown editor
- It's more similar to GitHub Edit&View feature

## Features 
- Expanded and compact mode, to be a tabbed activity on large devices and a spinner on normal or small devices (Directly implemented in the toolbar)
- Ability to enable or disable that view in settings

## Why introduce that
- A lot of users will like the brand new design, and if somebody don't he can change it manually
- It will make better every aspect of the Markdown editor
- Users can customize that Activity, and at the end it's the most used and important thing because user will interact with GitHub via comments and file edits, so it's perfect

**Comment by yakov116** [comment]
@AndreaCioccarelli wow I wish all issues were as detailed! 

Thanks for your feedback!

**Comment by k0shk0sh** [comment]
hey Andrea, thanks for the suggestion but I won't be implementing that.
