### ISSUE TITLE
Pressing wiki change items in feed should go to wiki page

### ISSUE THREAD

**Issue by gdevenyi** [k0shk0sh/FastHub#1062]
**FastHub Version: 4.4.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 3  
---

**Comment by k0shk0sh** [comment]
the problem with this is that I can't find a way to make this scenario with new github feed content where they took of everything.

**Comment by gdevenyi** [comment]
Hrm, so the API based feed doesn't have a link? The web one does.

**Comment by k0shk0sh** [comment]
No, but as you can see, the feeds doesn't exist anymore? i mean only starred, forks and pushes evens now happen other than that nothing is showing in the new github feed

**Comment by gdevenyi** [comment]
Not sure what you mean, on my github.com main feed, I see updates for wiki, with a link to the page, and to the diff.

![image](https://user-images.githubusercontent.com/3001850/32227357-8ab9596c-be21-11e7-96fd-43944925819a.png)

**Comment by k0shk0sh** [comment]
Can u share the api response?

**Comment by yakov116** [comment]
@k0shk0sh edit a wiki page and I will try

**Comment by k0shk0sh** [comment]
@yakov116 done

**Comment by yakov116** [comment]
@k0shk0sh 
``` json
{
"id": "6790033878",
"type": "GollumEvent",
"actor": {
"id": 960767,
"login": "k0shk0sh",
"display_login": "k0shk0sh",
"gravatar_id": "",
"url": "https://api.github.com/users/k0shk0sh",
"avatar_url": "https://avatars.githubusercontent.com/u/960767?"
},
"repo": {
"id": 91719760,
"name": "yakov116/My-Issues",
"url": "https://api.github.com/repos/yakov116/My-Issues"
},
"payload": {
"pages": [
{
"page_name": "Home",
"title": "Home",
"summary": null,
"action": "edited",
"sha": "d6e67b9bbecb985b17a7179529a2120dd2d8e5b2",
"html_url": "https://github.com/yakov116/My-Issues/wiki/Home"
}
]
},
"public": false,
"created_at": "2017-10-31T15:15:35Z"
}
```

**Comment by gdevenyi** [comment]
Hurrah thanks!

**Comment by yakov116** [comment]
@k0shk0sh you can detect if its public. If not display an error.

``` json
{
"page_name": "Home",
"title": "Home",
"summary": null,
"action": "edited",
"sha": "d6e67b9bbecb985b17a7179529a2120dd2d8e5b2",
"html_url": "yakov116/My-Issues/wiki/Home"
}
]
},
**"public": false,** --Here
"created_at": "2017-10-31T15:15:35Z"
}
```
