### ISSUE TITLE
Unable to scroll in low power mode 

### ISSUE THREAD

**Issue by hkyq** [k0shk0sh/FastHub#1064]
**FastHub Version: 4.4.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

When trying to scroll (in a repo) in lower power mode, I'm unable to, I'm just put back to my previous scroll location if you know what I mean.

**Comment by yakov116** [comment]
@hkyq I'm going to wait for @k0shk0sh to chime in. I wonder if this has to do with Android 8.0.
Thanks for your feedback

**Comment by k0shk0sh** [comment]
i don't know what you mean!. and I don't do per phone / mode customization
