### ISSUE TITLE
the problem of usage

### ISSUE THREAD

**Issue by nihaocun** [k0shk0sh/FastHub#1065]
**FastHub Version: 4.4.0**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** 360  
- **Brand:** 360  
- **Model:** 1501-M02  
---

I am in China，why is it possible to access the App only by using a Vpn?

**Comment by k0shk0sh** [comment]
because china blocked GitHub?

**Comment by nihaocun** [comment]
@k0shk0sh
No,I can visit www.github.com

**Comment by k0shk0sh** [comment]
really?

can you visit api.github.com ? also does Google playservice works in chin

**Comment by nihaocun** [comment]
@k0shk0sh
yes
