### ISSUE TITLE
Can't comment on a pull request review

### ISSUE THREAD

**Issue by GoryMoon** [k0shk0sh/FastHub#1066]
**FastHub Version: 4.4.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

When writing a comment on a review that is made on a pull request and pressing the send button on the text edit page it loads a little and then a red error pops up saying "Not found".

**Comment by k0shk0sh** [comment]
tested and working fine, perhaps the review was removed. could you please confirm that!

**Comment by GoryMoon** [comment]
Tested on the same review and I can't comment on it and it still exists.
Created a test pull request and made a review on it and could comment on that.

This case that I can't comment is on a repository that I don't have commit access (hens the pull request) and the review is made by someone else then me.

**Comment by k0shk0sh** [comment]
could you point me to your test pr to try and comment on to verify your assumption?

**Comment by GoryMoon** [comment]
https://github.com/GoryMoon/Test/pull/1
I did a review on it myself and had a friend that made a review as well to try to reproduce as close as possible. Also the repository that I made my pull request and tried to comment on a review is owned by an organization.

**Comment by k0shk0sh** [comment]
Well then that explains everything. Please read the FAQ about organizations and also https://github.com/k0shk0sh/FastHub/issues/952 has more details and discussion.

**Comment by MartinZikmund** [comment]
Test
