### ISSUE TITLE
Insertion of emoji resets cursor position

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1067]
**FastHub Version: 4.4.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

If you insert an emoji, the cursor position is set to beginning of the comments :disappointed:

Do you have any kind of regression tests? It's pretty pity that after you fix one issue other one appears and it might never end :cry:

**Comment by k0shk0sh** [comment]
I actually never fixed it for the emoji ;)

**Comment by zvirja** [comment]
Well, in the previous release everything worked fine..
