### ISSUE TITLE
Add jupyter notebook preview

### ISSUE THREAD

**Issue by hell03end** [k0shk0sh/FastHub#1069]
**FastHub Version: 4.4.1**  
**Android Version: 6.0.1 (SDK: 23)**  

Please, add more convenient preview for ipython notebooks (.ipynb files) like GitHub does it (not just raw json).

**Comment by yakov116** [comment]
@hell03end Link to file...

Thanks for your feedback

**Comment by Dreamersoul** [comment]
Would it be okay if I tried to solve this?

**Comment by k0shk0sh** [comment]
Sure ;)
