### ISSUE TITLE
Checkbox in issues

### ISSUE THREAD

**Issue by Aozavyalov** [k0shk0sh/FastHub#1070]
**FastHub Version: 4.4.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3010  
---

Please, add a possibility to fill a checkbox in a task list in issues. It will help with working and planning.

**Comment by yakov116** [comment]
#1021
