### ISSUE TITLE
Followers tab should list in reverse chronological order

### ISSUE THREAD

**Issue by raisedadead** [k0shk0sh/FastHub#1071]
**FastHub Version: 4.4.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

Followers tab should list items in reverse chronological order, same as GitHub's convention.

**Comment by k0shk0sh** [comment]
I wish if that's possible :), please search before submit new issue it will help keep the repo tidy
