### ISSUE TITLE
Trending repo back button

### ISSUE THREAD

**Issue by pekosoG** [k0shk0sh/FastHub#1072]
**FastHub Version: 4.4.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

While browsing inside a repo from the trending list, if i want to go back that list and use the on-layout back button (top left corner) it took me to the initial screen and not the trending list.

Not sure if that happens everywhwere, but at least on trending is happening.

**Comment by k0shk0sh** [comment]
this is the right way to navigate, please use phone back button to return where you left.

**Comment by pekosoG** [comment]
thats kinda inconsistent with the rest of the app, if you go to gists, select one and the use the same "back" button, you go back to the gists list, not the "news feed" screen :sweat_smile:

**Comment by k0shk0sh** [comment]
then, please report another issue, it sounds like a bug for me :)
