### ISSUE TITLE
Javascript highlight "data" as keyword

### ISSUE THREAD

**Issue by maple3142** [k0shk0sh/FastHub#1080]
**FastHub Version: 4.4.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

as title

![](https://i.imgur.com/5XAlqfz.png)

*data is not a keyword

**Comment by k0shk0sh** [comment]
this is beyond my hands :)
