### ISSUE TITLE
Keys not rendered properly in MarkDown files with dark interface

### ISSUE THREAD

**Issue by timvisee** [k0shk0sh/FastHub#1081]
**FastHub Version: 4.4.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

FastHub had trouble rendering key bindings in MarkDown with the black interface. Using the white interface is fine, the others I haven't tried.

See the following Imgur album for an example:
https://imgur.com/gallery/Ufsvv

Repository that has the keybind in the README (behind xcape):
https://github.com/timvisee/dotfiles

It is probably easy to fix by slightly modifying the theme configurations.

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/MCXkDjC.png)
