### ISSUE TITLE
Validation fails if I don't set a milestone 

### ISSUE THREAD

**Issue by benleavett** [k0shk0sh/FastHub#1085]
**FastHub Version: 4.4.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus3T  
---

I should to be able to create an issue without setting a milestone but the validation seems to now require now (used to work fine).

**Comment by k0shk0sh** [comment]
dang, I guess I know what's going on, I'm sorry for that I'll make a release asap
