### ISSUE TITLE
Merging fails with "http method 405 not allowed"

### ISSUE THREAD

**Issue by mmoayyed** [k0shk0sh/FastHub#1087]
**FastHub Version: 4.4.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

Attempting to merge pull requests that are perfectly good to merge with all checks being green results in a 405 error displayed on the screen.

**Comment by k0shk0sh** [comment]
I did reply you in the playstore. with

You are probably merging in organization repo which mean you need to ask org to grant access to Fasthub, please notice that this error isn't coming from FastHub and therefore you should contact GitHub.

**Comment by mmoayyed** [comment]
thanks for the comment. the repo belongs to an organization of which I am an admin and have been merging pull requests for the past 8 years. this is not a GitHub issue (trying to test this with other clients shows that I can perfectly merge)

**Comment by k0shk0sh** [comment]
you probably grant them access. so grant access to Fasthub and it will work!!

**Comment by mmoayyed** [comment]
sure. would you mind describing how I might do that? is this a setting in the app? or as you hinted something I need to configure in GitHub?

**Comment by k0shk0sh** [comment]
please read the faq from the readme or open up the navigation menu and click on faq you'll find the description there

**Comment by k0shk0sh** [comment]
it is something that you need to do in GitHub, basically few years ago, GitHub has restricted access to orgs

**Comment by mmoayyed** [comment]
Thanks. 

This is a puzzler; here is the setting:

![image](https://user-images.githubusercontent.com/1205228/31282538-c38e9984-aabf-11e7-8b3e-972fbe2d7dd6.png)


The pull request I was going to merge was in this project:
https://github.com/apereo/cas

- I assume everything (status checks, etc) must be green before a merge is allowed?
- Does the app support "Use your admin rights to merge this even though something may be red" ?

It's possible that a status check was red for a PR and that's why it failed. I'll experiment with one that is 100% green/passed.

**Comment by k0shk0sh** [comment]
yep, all these could effect it but imho merge button wont appear if GitHub said that the pr isn't mergeable, so I definitely think its to do with grant access, plus you could login via access token where you could setup these permissions yourself to be able to do such things :)
