### ISSUE TITLE
[Critical] Markdown renders totally invalid table content

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1088]
**FastHub Version: 4.4.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

See [this](https://github.com/AutoFixture/AutoFixture/issues/404#issuecomment-334203815) comment. If you open it in the browser, you'll notice that its content **completely** differs from how it's rendered in the app:

![Img](https://i.imgur.com/ILA0d9o.png)

Likely, there is some issue with the table rendering.. :disappointed:

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/patuVny.png)
