### ISSUE TITLE
Markdown rendering issue

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1089]
**FastHub Version: 4.4.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

Consider the following comment: https://github.com/AutoFixture/AutoFixture/issues/858#issuecomment-334803093. In browser you'll see two quotations with an emoji between them, however in app it looks completely differently:

![Screenshot](https://i.imgur.com/wBapiia.png)

Thank you for the app :blush:

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/3Yb8BMC.png)

**Comment by k0shk0sh** [comment]
about the emoji thingy I'm not sure what is going and honestly this markdown thing is getting to my nerve. 

jfyi: don't expect every single thing on the web(browser) to be rendered exactly the same on phone.

**Comment by k0shk0sh** [comment]
> hshshshshshshhs hshshshshshshhshshshshshshshshhs

:relaxed:

> hshshshshshshhs hshshshshshshhshshshshshshshshhs

**Comment by k0shk0sh** [comment]
this is an emoji from GitHub that is rendered and it's not an Android emoji. 

so I'm unsure what is going now? maybe the emoji doesn't exists in your phone and my phone? and therefore it's not rendered?

**Comment by zvirja** [comment]
> jfyi: don't expect every single thing on the web(browser) to be rendered exactly the same on phone.

Well, it might differ, but here the semantic of reply is changed completely. The second part of text is quoted, but looks like it's posted. That completely changes understanding of the reply.

I do understand that you're probably tired of those issues as there a lot of them, but here the issue changes how the comment is read. :disappointed:

> so I'm unsure what is going now? maybe the emoji doesn't exists in your phone and my phone? and therefore it's not rendered?

I don't know neither :blush: I don't know too much about the rendering system here..

**Comment by zvirja** [comment]
> jfyi: don't expect every single thing on the web(browser) to be rendered exactly the same on phone.

Well, it might differ, but here the semantic of reply is changed completely. The second part of text is quoted, but looks like it's posted. That completely changes understanding of the reply.

I do understand that you're probably tired of those issues as there a lot of them, but here the issue changes how the comment is read. :disappointed:

> so I'm unsure what is going now? maybe the emoji doesn't exists in your phone and my phone? and therefore it's not rendered?

I don't know neither :blush: I don't know too much about the rendering system here..

**Comment by k0shk0sh** [comment]
Please update to 4.4.2 and let me know if the issue still exists! and if the emoji doesn't appear then as I said :)

**Comment by zvirja** [comment]
Will do when update becomes available to me.

Issue was not about emoji only - the second quotation was rendered incorrectly also.

**Comment by k0shk0sh** [comment]
but did you see the screenshot I attached here?

**Comment by zvirja** [comment]
Yep, I saw - it was rendered correctly there.

**Comment by zvirja** [comment]
Can confirm that quotation are displayed correctly. The emoji is still missing. If you could replace it with some dummy char indicating that emoji is unknown - it would be awesome.
