### ISSUE TITLE
[Xiaomi] Unable to upload image

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1090]
**FastHub Version: 4.4.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

I'm unable to upload image from my phone from the "insert media" dialog. On other devices everything works fine, but not here. Also I have the Imgur app installed and it works perfectly fine. I've tried to reinstall the app, but it does help. 

Could you please advice how we can troubleshoot this issue? For instance, you can provide with diagnostic app that will display error detail, so we can understand why that happens.. Issue is really annoying :triumph::confused:

**Comment by k0shk0sh** [comment]
I thought we have discussed this before? check your phone own permission implemention. 

P.S: I DO NOT DO SPECIFIC PHONE FIXES. 
 you mentioned it works everywhere but on that phone. 

I guess you have that phone and therefore you should know about their stupid permissions restriction?

**Comment by k0shk0sh** [comment]
P.S: I hate that phone.

**Comment by zvirja** [comment]
Everything is fine with permission. I'm able to pick the image from gallery, but later see this:

![Screenshot ](https://i.imgur.com/217nG7y.png)

At this point I want to understand what exactly happens, but the generic error message doesn't show that.

Is that possible to build a checked build with exception message? So we could see what exactly happens..

**Comment by zvirja** [comment]
Everything is fine with permission. I'm able to pick the image from gallery, but later see this:

![Screenshot ](https://i.imgur.com/217nG7y.png)

At this point I want to understand what exactly happens, but the generic error message doesn't show that.

Is that possible to build a checked build with exception message? So we could see what exactly happens..

**Comment by k0shk0sh** [comment]
this mean I couldn't retrieve the image, simply your phone OEM plays with Android default impl and therefore I'll need to find a hack for it and therefore the other 60k users will suffer that it's not working with them. 
I don't even have that phone to test it out!!!!!!!!

**Comment by maple3142** [comment]
@zvirja I think that is because MIUI has their own file manager instead of Android default file manager.
But MIUI file manager is disabled by default in MIUI 8(I don't know why)
You can try [this](http://en.miui.com/thread-353084-1-1.html) to enable it.

**Comment by zvirja** [comment]
Wow, that indeed helped :stuck_out_tongue_closed_eyes: Thanks a lot for the suggestion! :blush:
