### ISSUE TITLE
FastHub keeps showing logo, won't open.

### ISSUE THREAD

**Issue by tkosamja** [k0shk0sh/FastHub#1091]
Tried installing from the Play Store and downloading the .apk file, and I get the same error.
Basically when I open the App it just keeps showing the screen in the file attached and nothing happens.
I'm using Lineage OS. Already tried clearing cache and data but nothing changed.

**Comment by k0shk0sh** [comment]
search, there are tones of similar issues.

**Comment by tkosamja** [comment]
Yes, I did search but it's not easy to find the original issue in 849 issues.

**Comment by k0shk0sh** [comment]
you don't specifically search one by one, all you gotta do is search for the keyword.

**Comment by tkosamja** [comment]
Already did. "won't open" "freeze" "stuck". No results.

**Comment by k0shk0sh** [comment]
#780

![](https://i.imgur.com/2ctAhgn.png)

**Comment by tkosamja** [comment]
I guess that's it. Google Play Services right? 
No need to me mad.

**Comment by k0shk0sh** [comment]
I'm not mad at you, I'm mad at this whole thing, I hate this issue and you hate it too.  but with all I did I still can't suppress it :'(

**Comment by tkosamja** [comment]
Let me try install Google Play Services. I will update you.

**Comment by tkosamja** [comment]
Nop. Still not working

**Comment by k0shk0sh** [comment]
can you try and use appshortcut to go to app?

**Comment by tkosamja** [comment]
I'm in. It only works with appshortcut but it's something at least.

**Comment by tkosamja** [comment]
Never mind, it works. Problem solved. Thanks for your time.

**Comment by k0shk0sh** [comment]
could you tell me how it worked?

**Comment by tkosamja** [comment]
Sure. I clicked "Profile" with appshortcut and it opened the log in screen. I logged in and after that it started working.

**Comment by k0shk0sh** [comment]
hmmmm, that's weird! will investigate on this 😞

**Comment by tkosamja** [comment]
Hehe good luck

**Comment by shangshiyjn** [comment]
I met the same problem as you, and I opened the log-in screen as you, but I can't log in no matter which log-in method I choose. I believe my username and password is correct because I can log in with my browser.

**Comment by k0shk0sh** [comment]
I have fixed this and removed the check for purchases at all. Please wait for few days.

**Comment by shangshiyjn** [comment]
OK, thanks for your time
