### ISSUE TITLE
HTML code in markdown

### ISSUE THREAD

**Issue by Ni55aN** [k0shk0sh/FastHub#1093]
**FastHub Version: 4.4.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LENOVO  
- **Brand:** Lenovo  
- **Model:** Lenovo P2  
---

html code is not output as plain text, instead it is rendered

**Comment by yakov116** [comment]
@Ni55aN link?!

**Comment by Ni55aN** [comment]
@yakov116  https://github.com/Ni55aN/D3-Node-Editor/wiki/Nodes at the bottom of the page

**Comment by yakov116** [comment]
@Ni55aN duplicate of #935
