### ISSUE TITLE
Issues just display number

### ISSUE THREAD

**Issue by darwinfroese** [k0shk0sh/FastHub#1095]
**FastHub Version: 4.4.1**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

Issues only display number and it's difficult to see which one you want to look at without opening them all.

Not an issue, just a feature request.

**Comment by yakov116** [comment]
@darwinfroese um so what exactly do u want it to do?

Also if you hold down an issue it shows the info

**Comment by darwinfroese** [comment]
I realized that I didn't clarify well. In the projects page it says: `githubuser/project/issue#` .. I tried a long hold and don't see anything.

**Comment by k0shk0sh** [comment]
it won't work in projects because we don't have the issue object. waiting for GitHub to fix their api :)

**Comment by darwinfroese** [comment]
awesome. thanks!
