### ISSUE TITLE
Option to turn on, off in edit

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1101]
**FastHub Version: 4.4.1**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

Same as title
Option to turn on, off wrap in edit files.

**Comment by k0shk0sh** [comment]
this won't be fixable as i'm using TextView and not webview :)

**Comment by cozyplanes** [comment]
even if i make a wrappable textview lib or you use another lib?

**Comment by k0shk0sh** [comment]
point me to that lib ;)

**Comment by cozyplanes** [comment]
dunno

**Comment by cozyplanes** [comment]
i will try to make it after october (after my final project ends)
