### ISSUE TITLE
Impossible to press explanation button when title is >2 lines in issues.

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1105]
**FastHub Version: 4.4.2**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

~~~~ 
Just same as explanation too.

**Comment by k0shk0sh** [comment]
????????

**Comment by cozyplanes** [comment]
opening new issue. sorry
