### ISSUE TITLE
Unable to scroll when in low power mode

### ISSUE THREAD

**Issue by hkyq** [k0shk0sh/FastHub#1106]
**FastHub Version: 4.4.2**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

Title says all. When my phone is in low power mode, scrolling is very buggy on repositories and is constantly being me back to where I was.

**Comment by yakov116** [comment]
@hkyq please search before opening an issue.

Thanks for your feedback
