### ISSUE TITLE
Fix the spelling Error

### ISSUE THREAD

**Issue by Lulzx** [k0shk0sh/FastHub#1108]
**FastHub Version: 4.4.2**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G4 Play  
---

I found that there was a spelling mistake for ACCESS which was written as ACESS in the e-mail which I got from Google PlayStore. Kindly Check it out and fix that. 
Thanks! :blue_heart:

**Comment by k0shk0sh** [comment]
what are u talking about? if its email from playstore what FastHub has to do with it?

**Comment by Lulzx** [comment]
@k0shk0sh I was telling you about the email from PlayStore which I received after purchasing the PRO version. There was a spelling mistake there. :relieved:

**Comment by k0shk0sh** [comment]
Not mine lol, :D google write that, or you can also attach the text her so I can confirm
