### ISSUE TITLE
Markdown image caching is to aggressive

### ISSUE THREAD

**Issue by robojones** [k0shk0sh/FastHub#1109]
**FastHub Version: 4.4.2**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer&Brand:** HUAWEI  
- **Model:** Hi6210sft  
---

The markdown preview caches images forever. This destroys the purpose of badges in the readme.

**Comment by k0shk0sh** [comment]
aren't the images updated Everytime???

**Comment by robojones** [comment]
Doesn't seem to be the case at one of my repos. When I open it with FastHub, my bitHound badge shows: "Dependencies: outdated". In the browser and on the bitHound website it says: "Dependencies: all star".

**Comment by k0shk0sh** [comment]
🤷‍♂️  , i'll look into that later, could you also point me to your repo?

**Comment by robojones** [comment]
Here is the repo:
https://github.com/robojones/z1
