### ISSUE TITLE
notifications running crazy

### ISSUE THREAD

**Issue by emdete** [k0shk0sh/FastHub#1110]
fasthub creates lots of notifications, removing them itsself again, sometimes i had 10 or more notifications showing up, being removed just after creating them showing up again and so forth. sometimes it's only a single one, showing up, disapearing, showing up... not enough time to even read the thing if you drag down. this doesnt make much sense.

i have disabled to retrieve notices but fasthub did not stop to run in the backround and showing this behaviour. to get rid of it i had to deinstall the app. :(

**Comment by k0shk0sh** [comment]
you should have reported the issue from FastHub to save us time asking you what version are you using and other things!!!!!!!!!!!

**Comment by k0shk0sh** [comment]
its duplicated of issues reported like ages ago and it has never happened again, so can you please tell me, what version of FastHub are you using?

**Comment by emdete** [comment]
sorry, i forgot to tell that i use the version provided by f-droid. as i had to deinstall it to get my phone back i could not look into an about page or the like. f-droid tells it's 2.1.0. i will reinstall and check if i can reproduce the behaviour.

i looked for the issue but did not find any similar one. which one is this "ages ago" one? a number would be helpful.

**Comment by emdete** [comment]
after reinstall i applied my settings (i switch off "notification sound" and switch "sync interval" to "turn off". after that the effect immediatly started again).

this is some log during that, the second and third line repeated many times:

```
10-12 14:59:16.963 E/NotificationService( 3422): Package enqueue rate is 10.026949. Shedding events. package=com.fastaccess.github
10-12 14:59:16.980 W/Notification(21544): Use of stream types is deprecated for operations other than volume control
10-12 14:59:16.980 W/Notification(21544): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
10-12 14:59:16.989 W/Notification(21544): Use of stream types is deprecated for operations other than volume control
10-12 14:59:16.989 W/Notification(21544): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
10-12 14:59:17.031 W/StaticLayout( 5187): maxLineHeight should not be -1.  maxLines:1 lineCount:1
10-12 14:59:17.203 I/chatty  ( 5187): uid=10025(u0_a25) com.android.systemui identical 34 lines
10-12 14:59:17.203 W/StaticLayout( 5187): maxLineHeight should not be -1.  maxLines:1 lineCount:1
10-12 14:59:17.646 E/SQLiteLog(21544): (14) cannot open file at line 33378 of [8201f4e1c5]
10-12 14:59:17.646 E/SQLiteLog(21544): (14) os_unix.c:33378: (24) openDirectory(/data/user/0/com.fastaccess.github/databases) - 
```

i do not want any notifications at all from fasthub, maybe it would be good to be able to switch off any background activity?

**Comment by k0shk0sh** [comment]
you don't need to trouble yourself, Fasthub is in version 4.4.2 and you are using 2.1.0 thats like months away. 

my only advice, is that you install FastHub from releases page. 
I no longer support fdroid.

**Comment by emdete** [comment]
hm, that version doesnt even allow me to log in... stays in the login screen after i provided user&passwd.

**Comment by k0shk0sh** [comment]
you'll need to enable your Google Play service.

**Comment by k0shk0sh** [comment]
#245  #353
