### ISSUE TITLE
Search repo in Orgs & User

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#1111]

**Comment by the-cybersapien** [comment]
Hi Kosh, could you add a little explanation to this issue?
If I am correct, you want the ability to search the repos when an org or a user page is open. Am I right?

**Comment by k0shk0sh** [comment]
@the-cybersapien yep, that's correct, it will be really easy task. 

Matter of creating new activity, and locking the search to that specific repo or org and attach the SearchRepoFragment to it and that's it :D ..

**Comment by the-cybersapien** [comment]
Yep, Starting work on this right now. Please expect a PR by this time tomorrow :smile:

**Comment by k0shk0sh** [comment]
Any news about this? I'm planning to make a release today  :blush:

**Comment by the-cybersapien** [comment]
@k0shk0sh 
Done. Sorry I was a bit late, it's festive Season in India, Didn't get a lot of time :sweat_smile: 
Have a look at PR #1164
