### ISSUE TITLE
A new feature idea 

### ISSUE THREAD

**Issue by oguzkaganeren** [k0shk0sh/FastHub#1112]
**FastHub Version: 4.4.1**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G4  
---

Will be matches in searching result such as:most stars, most branches, most comments and may be trends.

**Comment by k0shk0sh** [comment]
there is an issue open with similar request where to filter search results. 

thanks for the issue :)
