### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by AdrianVovk** [k0shk0sh/FastHub#112]
Links in a table of contents of a library README don't work. For example, [here](https://github.com/afollestad/material-dialogs/releases/tag/0.9.4.1)

**Comment by k0shk0sh** [comment]
this should be fixed in #68 , #77 and #78 , it should be released in next version.

**Comment by AdrianVovk** [comment]
Still not fixed in latest update

**Comment by AdrianVovk** [comment]
Oh looking at the issues you linked I think you misunderstood the issue. many repositories have a list of links on their READMEs cooresponding to sections (so they have a section on how to download, how to build, how to use, etc. They would have a list of links at the top linking you to each of these sections). Now if you click one if these links it just opens the repository again, instead of linking you down to the correct section

**Comment by k0shk0sh** [comment]
I literally misunderstood this issue, well this issue, I guess won't be something that is easy to fix, however i'll re-open it until I confirm either that is something can be done or not.

**Comment by k0shk0sh** [comment]
I'll see either WebView can support hash-links. I'm sorry for misunderstanding your issue tho.

**Comment by AdrianVovk** [comment]
Thanks! Possible ETA for the next release?

**Comment by k0shk0sh** [comment]
Sunday as usual or Saturday. But maybe earlier, but can't promise you that. I had to some javascript stuff to make it work ✌️

**Comment by k0shk0sh** [comment]
Meantime, please keep reporting the bugs you find @AdrianVovk :)

**Comment by AdrianVovk** [comment]
@k0shk0sh Thanks!
