### ISSUE TITLE
GitHub urls ending in .git don't open correctly

### ISSUE THREAD

**Issue by lufinkey** [k0shk0sh/FastHub#1120]
**FastHub Version: 4.4.2**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

I get a "Not Found" error

**Comment by yakov116** [comment]
@lufinkey link please.......


Thanks for your feedback

**Comment by lufinkey** [comment]
Literally any repository URL ending in .git fails to open in fasthub

Example:
this URL works: https://github.com/lufinkey/kodi-openbox
this URL does not: https://github.com/lufinkey/kodi-openbox.git

**Comment by k0shk0sh** [comment]
yeah, because basically i'll parse that url to lufinkey as username & kodi-openbox.git

**Comment by lufinkey** [comment]
Right, but both should work, since both are valid github URLs pointing to the same repository

**Comment by k0shk0sh** [comment]
Then I'm not the one to blame since I'm not doing anything but requesting the api with these values, anyway I have fixed that.
