### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by Dil3mm4** [k0shk0sh/FastHub#1121]
**FastHub Version: 4.4.2**  
**Android Version: 5.0.2 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** LGE  
- **Model:** LG Prime  
---

Hello there, dunno if you've planned to support other languages.
If you have a transifex open (or anything else) I'd help translating FastHub in Italian.

Have a nice day.

**Comment by k0shk0sh** [comment]
there is Italian language already and other languages in settings screen, you are welcome to update the strings to latest via git, GitHub website or even FastHub app.
