### ISSUE TITLE
Show number of commits behind original repo

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1122]
**FastHub Version: 4.4.2**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

Can you consider implementing the feature as in title in forked repos?

**Comment by k0shk0sh** [comment]
could you please describe what you want exactly? I can't get your question. 

please, also be specific and more clear with your issues :'(

**Comment by cozyplanes-development** [comment]
so when you fork a repo, and after some days, you see in your forked repo something like 8 commits behind someone:master in the web version. i was asking if you could implement this

**Comment by k0shk0sh** [comment]
Can't find any API for that, if you can find one, please let me know and i'll reopen it.

**Comment by cozyplanes** [comment]
can't you do html scraping?
