### ISSUE TITLE
Issue 9

### ISSUE THREAD

**Issue by beiquotes** [k0shk0sh/FastHub#1125]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 4  
---

Ticket for support 9

**Comment by dedepete** [comment]
What do you mean by writing this? Please, do not use the Feedback form for this kind of "reports".
