### ISSUE TITLE
pinned repo gone

### ISSUE THREAD

**Issue by Yofri** [k0shk0sh/FastHub#1128]
**FastHub Version: 4.4.2**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7 Edge  
---

My pinned repo gone after change device

**Comment by k0shk0sh** [comment]
we don't have backend to store your pinned repos and backup across devices.
