### ISSUE TITLE
Nothing happen when click on link

### ISSUE THREAD

**Issue by maple3142** [k0shk0sh/FastHub#1130]
l**FastHub Version: 4.4.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

![](https://i.imgur.com/7TZPq9u.png)

When I click on `CLI` `Browser` `Server` `In-memory` nothing happen.

[https://github.com/typicode/lowdb](https://github.com/typicode/lowdb)

**Comment by k0shk0sh** [comment]
Simply because they are hashlinks and their id doesn't exist or the app never find them.

**Comment by maple3142** [comment]
@k0shk0sh try to open link in browser if link doesn't supported?
