### ISSUE TITLE
总是卡在起始页

### ISSUE THREAD

**Issue by forgiveboo** [k0shk0sh/FastHub#1131]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** honor  
- **Model:** Honor 8  
---

The software is always on the start page when it is open

**Comment by yakov116** [comment]
@forgiveboo What?

**Comment by k0shk0sh** [comment]
You need to have google Play service

**Comment by forgiveboo** [comment]
@k0shk0sh I've already installed Google play server

**Comment by forgiveboo** [comment]
@k0shk0sh I've already installed Google play service

**Comment by k0shk0sh** [comment]
Enabled??

**Comment by forgiveboo** [comment]
@k0shk0sh yes

**Comment by k0shk0sh** [comment]
Alright, can you search for other issues and read the solutions there?

**Comment by forgiveboo** [comment]
@k0shk0shyes
