### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by Pranav-Rastogi** [k0shk0sh/FastHub#1133]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LENOVO  
- **Brand:** Lenovo  
- **Model:** P2  
---

The images in a `.md` file are not displayed in the app.

**Comment by dedepete** [comment]
Please, provide a link to the affected `.md`.

**Comment by Pranav-Rastogi** [comment]
https://github.com/Pranav-Rastogi/Notes/Chemistry(Sem-3).md

**Comment by yakov116** [comment]
@Pranav-Rastogi working for me ![](https://i.imgur.com/MQY047r.png)

**Comment by Pranav-Rastogi** [comment]
@yakov116 This is what my app shows.
![whatsapp image 2017-10-16 at 4 53 52 pm](https://user-images.githubusercontent.com/20932153/31609697-d672545c-b292-11e7-8469-d0077db8e152.jpeg)

**Comment by Pranav-Rastogi** [comment]
Reinstalling the application solved the issue for me.

**Comment by k0shk0sh** [comment]
It's probably caching problem, its fixed locally and should be released very soon
