### ISSUE TITLE
[feature suggestion] possibility to select custom home page

### ISSUE THREAD

**Issue by lbusett** [k0shk0sh/FastHub#1139]
**FastHub Version: 4.4.2**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (3rd Gen)  
---

Hi. First of all,  thanks for a great app!

A suggestion for a possible improvement: would you consider introducing the possibility to allow selection of a different ​ home page, so that when opening the app I may,  for example,  see the list of my pinned repositories,  or my profile page,  instead than the "feeds" page?

**Comment by k0shk0sh** [comment]
You could use appshortcuts to open these and more :).

**Comment by lbusett** [comment]
Hi, 

   thanks for the reply. I don't know if I get your answer right: If you mean that I can access those by swiping right and select what I need, I was aware of the functionality. What I was asking is this: 

   - When I open the app, by  default I am taken to the "feeds" panel. I'd suggest to add the possibility to change this default behaviour, so that when I open the app I can be taken directly, for example, to the "my profile" page, or to the "notifications" panel, instead than seeing the "feeds" panel. 

I hope that now it is more clear. 

Lorenzo

**Comment by k0shk0sh** [comment]
Hi sorry if I was unclear I meant using Android app shortcut which FastHub has 

Profile, pinned, issues, prs

**Comment by lbusett** [comment]
Ah, now I got it. Didn't know about that. 

Am I wrong, or that is available only for Android > 7.1 ?

**Comment by k0shk0sh** [comment]
Yep its on 7.1 and above.  

I'm not really interested on making the home page customizable on pre 7.1 so I'm sorry about that:)

**Comment by lbusett** [comment]
No worries. I agree that it wouldn't make sense to develop a feature just for older Android versions. Sooner or later I'll update my phone... ;-) 

Thanks for your answers .

L.
