### ISSUE TITLE
Make contributing easier

### ISSUE THREAD

**Issue by passsy** [k0shk0sh/FastHub#114]
It could be much simplified with the following things:

- add debug keystore in repository with corresponding signing config
- add `google-services.json` at least a fake one for the debug build with debug keystore SHA-1
- quick link where to register the github oauth app and what to set for the `redirect_url` (`https://127.0.0.1` works perfect)

**Comment by k0shk0sh** [comment]
This should be a most to have. I'm busy with more bugs fixes. it would be cool if use yours as PullRequest, that had be awesome. If you don't have time to do it, let me know and I'll try and find time for it.
