### ISSUE TITLE
'Unauthorized user' toast popping up.

### ISSUE THREAD

**Issue by Gauti4417** [k0shk0sh/FastHub#1141]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5) Plus  
---

I was having some issues related to my profile, so i cleared all the data of app. After doing it and re-opening the app, the **'unauthorized user' toast**  popped up. And also when i logged in, all of the premium features were gone too(you unlocked premium features for me when I mailed you my id proof that i am a student). I have also mailed you about the same. Hoping for a solution as quick as possible.

**Comment by yakov116** [comment]
@Gauti4417 it maybe a github issue

**Comment by yakov116** [comment]
@k0shk0sh at the rate github is going down, I this we should add github status in the app

**Comment by k0shk0sh** [comment]
Will include next time auto enabling of pro features for those students.

**Comment by Gauti4417** [comment]
So how should i solve this? How can the feature be unlocked again?
