### ISSUE TITLE
Commiting to a pull request doesn't show the new CI result

### ISSUE THREAD

**Issue by Dreamersoul** [k0shk0sh/FastHub#1142]
**FastHub Version: 4.4.2**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

After I submitted a pull request and added a commit to it
The pull request screen showed 2 CI but both failing when infact the second one passes
Check my pull request [here](https://github.com/kennethreitz/pipenv/pull/922)

**Comment by yakov116** [comment]
@Dreamersoul
![](https://i.imgur.com/TdBJwsB.png)

**Comment by Dreamersoul** [comment]
that's weird! sorry for that

**Comment by k0shk0sh** [comment]
We don't do any handling or anything, I display whatever comes from GitHub. So it might just been that it was failing and it  rebuilt again or it was building by that time
