### ISSUE TITLE
Remove annoying "Press back again to exit" toast

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#115]
This is a bad practice as it blocks user navigation and breaks the overall navigation flow.

**Comment by k0shk0sh** [comment]
I guess, this could be disabled from settings screen.

**Comment by HeinrichReimer** [comment]
No, this should just be removed.

**Comment by Rainer-Lang** [comment]
Without it, you could accidently close the app.

**Comment by HeinrichReimer** [comment]
@Rainer-Lang Hahaha, following that logic every app should have such a message 😂
Google's Roman Nurik and Nick Butcher specifically stated this as an anti-pattern some years (!) ago.
Just remove it.
If you accidentally close the app, which is fairly uncommon anyway,  you can just re-open it from the recents screen (or your home screen) 😉

**Comment by k0shk0sh** [comment]
I do most of the time hit that back button. which is annoying to back where I was in the list. not all the rules are meant to be followed :p sometimes we just have to find away around them.

**Comment by kutsan** [comment]
@HeinrichReimer I agree with you. This is anti-pattern.

**Comment by HeinrichReimer** [comment]
@k0shk0sh Well if you hit the back button accidentally we should fight the reason for this instead of the symptoms.
Maybe the bottom nav is the problem here...

**Comment by k0shk0sh** [comment]
Not really, I do that everytime in Facebook app which does not have
bottomNavigation.

Anyway, this issue has been resolved and i'm doing testing while writing
this and going to commit it right away.

It will be there tho, but again, its user preference, and you could disable
it from settings screen.

*Thanks.*
*Best Regards,*
*Kosh*



<https://about.me/imkosh?promo=email_sig>
