### ISSUE TITLE
[FR] Add/View Collaborators to repo

### ISSUE THREAD

**Issue by Gauti4417** [k0shk0sh/FastHub#1150]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5) Plus  
---

We can only view contributer, but there is no option to add a collaborator or view a collaborator.

**Comment by yakov116** [comment]
@Gauti4417 Are you talking about adding a new collaborator  to a repo?
Thanks for your feedback.

**Comment by Gauti4417** [comment]
Yes.

**Comment by yakov116** [comment]
@Gauti4417 I will wait for @k0shk0sh to chime in.

**Comment by Gauti4417** [comment]
okay :)

**Comment by k0shk0sh** [comment]
You can view, adding collaborator should be done from the website.

**Comment by Gauti4417** [comment]
i am sorry but as far as i have explored the app, i can only see contributers in my repository, no collaborators.

**Comment by k0shk0sh** [comment]
Owh, yep contributors only.

**Comment by Gauti4417** [comment]
😅😅 yeah.... and btw, please do not forget my issue after clearing the data...all the activated premium features were lost :(. i did what you suggested(clear my data to make repositories show actual size instead of 0B) and yet it arose another issue :(.

**Comment by yakov116** [comment]
@Gauti4417 That was fixed already. Will be in the next build.

![image](https://user-images.githubusercontent.com/16872793/31774516-fd2f3416-b4b3-11e7-8b3a-cbb3a85ce2e6.png)

**Comment by k0shk0sh** [comment]
This isn't related @yakov116 restore purchases are actually for who actually bought pro or all features or anything.   

For the students part they don't need to do anything. It will automatically detect it.

Haven't implement that part it shouldn't take 5mins

**Comment by Gauti4417** [comment]
would really appreciate if the issue is solved. thank you.

**Comment by k0shk0sh** [comment]
It will, can we stop talking about it already?
