### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by zzSWG** [k0shk0sh/FastHub#1154]
**FastHub Version: 4.4.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 3  
---

开发者你好，很抱歉使用英文描述我的问题，希望不影响你的阅读体验。

我发现的问题是：当用fasthub来查看带有中文注释的代码时，会出现乱码问题，希望你们可以解决！

十分感谢！

**Comment by yakov116** [comment]
@zzSWG English please...



_Sent from my Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
