### ISSUE TITLE
[feature request] Show (svg) images

### ISSUE THREAD

**Issue by yungtravla** [k0shk0sh/FastHub#1155]
**FastHub Version: 4.4.2**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S5  
---

I can't see embedded svg images on my README.md

**Comment by yakov116** [comment]
@yungtravla link please

**Comment by yungtravla** [comment]
@yakov116 everything seems fine now. It just took a while to fetch. Closing this issue
