### ISSUE TITLE
Issue with comment highlighting in Java source

### ISSUE THREAD

**Issue by giosil** [k0shk0sh/FastHub#1157]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** HUAWEI P9 lite  
---

comments in the code will not be properly highlighted in some sources Java

**Comment by yakov116** [comment]
@giosil Link......................................

**Comment by giosil** [comment]
https://github.com/giosil/wcollections/blob/master/src/org/util/WUtil.java

Il 19 ott 2017 9:00 PM, "yakov116" <notifications@github.com> ha scritto:

@giosil <https://github.com/giosil> Link..........................
............

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/1157#issuecomment-338004912>,
or mute the thread

**Comment by yakov116** [comment]
@giosil Going to wait for @k0shk0sh but don't think there is much to do about it, SInce we are using a lib.

**Comment by k0shk0sh** [comment]
Can't do anything about it, I'm using highlight.js library to highlight the code so nothing really I can do.
