### ISSUE TITLE
Feature suggestion: add a milestones tab to the issues panel

### ISSUE THREAD

**Issue by lbusett** [k0shk0sh/FastHub#1158]
**FastHub Version: 4.4.2**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (3rd Gen)  
---

Hi. The title says it all: I think it could be nice to have an additional tab in the issues panel of a repo, allowing to quickly access its milestones list.

**Comment by k0shk0sh** [comment]
You could click on the pencil icon to access milestone you can even create new milestones from.there!

**Comment by lbusett** [comment]
Yes, I know I can do that after selectin a specific issue. What I was suggesting was to have an additional panel accessible by swiping right here: 

![image](https://user-images.githubusercontent.com/4480397/31815094-f31b6354-b58b-11e7-9f89-74c693d5f22d.png)

, containing the list of active milestones. 

Just a suggestion. 

L.

**Comment by k0shk0sh** [comment]
How about clicking search and you could see all the milestones and others also you can long press on an issue or pr to see its details faster with labels, milestones and others quickly

**Comment by lbusett** [comment]
That works too, thanks.
Maybe not "immediate" as I hoped, but once you know that it is there it does the trick neatly.!
