### ISSUE TITLE
Gist shows no files

### ISSUE THREAD

**Issue by nazavode** [k0shk0sh/FastHub#1161]
**FastHub Version: 4.4.2**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia X  
--

While opening [this](https://gist.github.com/8e22cbef33a09e15c1fd01fae441990e) gist the app shows no files.

**Comment by k0shk0sh** [comment]
Simply because the files to transfer to the Fragment size is `1.34332 megabytes` which Android can't take therefore I'm avoiding to crash the app if not you had see TTL exception.

**Comment by k0shk0sh** [comment]
Fallback to open it in the browser :sorry tho:
