### ISSUE TITLE
Fraudulent pro features description 

### ISSUE THREAD

**Issue by yliaho** [k0shk0sh/FastHub#1163]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

I bought the Pro features pack and despite it saying that I'd get the premium themes along with, I'm still being prompted to pay for them. Why? Scummy much?

**Comment by k0shk0sh** [comment]
That's strange, can you try again?????????????


P.S: stop being judgemental.
