### ISSUE TITLE
Unable to purchase

### ISSUE THREAD

**Issue by mashirozx** [k0shk0sh/FastHub#1166]
**FastHub Version: 4.4.2**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI NOTE LTE  
---

After click purchase button, the app just restarted again. Again and again. What's more details should I provide?

**Comment by k0shk0sh** [comment]
Google play services? Does your country support purchase from Playstore, how did you install the app?

**Comment by mashirozx** [comment]
@k0shk0sh I'm in China, but I use a VPN, my Google account is in Japan, I have purchased with Japan Yen successfully  before. 
I install this app from Google play, I have all Google service framework on my phone.
