### ISSUE TITLE
.ico file not shown properly

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1168]
**FastHub Version: 4.4.2**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

https://github.com/hdkesting/SudokuX/blob/master/SudokuX.UI/S%C5%ABdoku%20X.ico 

Refer this as example

**Comment by k0shk0sh** [comment]
And what it suppose to be? An image?

**Comment by cozyplanes-development** [comment]
it is an icon file, 
you can deal like pngs

**Comment by cozyplanes-development** [comment]
so will the image be viewed properly? 
Is it updated with the latest version?

**Comment by k0shk0sh** [comment]
Nope, didn't work, checked with GitHub and they don't show it either so fallback to browser

**Comment by cozyplanes** [comment]
by viewing raw, it works...
Then how is png shown? Hmmm

**Comment by k0shk0sh** [comment]
Png just a link and display it normal, tried to .icon Android didn't recognize it neither GitHub. So fallback to browser :)
