### ISSUE TITLE
Unable to view in-app purchases I've made. 

### ISSUE THREAD

**Issue by Ryonez** [k0shk0sh/FastHub#1169]
**FastHub Version: 4.5.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7 Edge  
---

I know I have purchased pro before to unlock the themes, but there is no acknowledgement of that in app, to the point I can even purchase pro again!
I seem to be able to apply themselves without issue, but this lack of acknowledgement is unsettling, especially when the store is actually letting me take steps to purchase it again.

Using the option to restore prior purchases makes a white box fly across the screen. Not sure what's happening there either.

Can you please make this clearer as to what is actually enabled and what I've payed for already? Thank you.

**Comment by k0shk0sh** [comment]
If you have purchased pro you would see a heart on your image inside the drawer menu. 
Restore purchases will unlock everything if you have installed the app somewhat or cleared app data.

**Comment by Ryonez** [comment]
Ah, so that's what that was for.
Thank you for telling me about that. I still think it would be helpful to have something that outright says that you have such and such purchased though, as the heart and the fact I can change themes are the only indicators I have Pro. It still feels a little alarming that I can purchase Pro again. 
As to the restore purchases option, I was to trying to find what Google thought I had. However it really didn't help :)

**Comment by yakov116** [comment]
@k0shk0sh I said this long ago lol

https://github.com/k0shk0sh/FastHub/issues/236#issuecomment-291037385
