### ISSUE TITLE
Use Material Design Spinner

### ISSUE THREAD

**Issue by Scrumplex** [k0shk0sh/FastHub#1170]
**FastHub Version: 4.5.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

After an update, the spinner was changed to that weird jumping ball. Can't there just be the Material Design spinner? This app looks so good, but that jumping ball destroys it's looks

**Comment by yakov116** [comment]
@Scrumplex side note: this change happened about 4 updates ago if not even more.....

**Comment by Scrumplex** [comment]
@yakov116 yeah I know, that it happened some updates ago, but I just had the motivation to open an issue.

**Comment by k0shk0sh** [comment]
Can't we have something different? ProgressDialog is deprecated in android O. 
I'll change it to something else.

**Comment by dedepete** [comment]
What do you think of this, guys?  
https://github.com/d-max/spots-dialog

**Comment by Scrumplex** [comment]
I think it would be better, just to trigger the spinner of the SwipeRefreshLayout. That would be user friendly and material design conform.

**Comment by k0shk0sh** [comment]
None of that will happen, I'll change the bouncing ball to something else, but still lottie. 


Don't bother to discuss it more 🤑

**Comment by dedepete** [comment]
If it's not a secret, what will replace the bouncing ball?  
IMO, a loading dialog makes the appearance being more serious. So does a material spinner.

**Comment by avently** [comment]
I like current implementation. it's really cool

**Comment by AdrianVovk** [comment]
It still looks quite odd. The colors also break the look of the app. Again, it'd be much better just to have the normal spinner. Not a dialog either, just the normal Material loading spinner.

**Comment by k0shk0sh** [comment]
@AdrianVovk hmmmmm, can I keep it please 😂. 

If your comment got 5 upvotes like the OP I'll remove it :p

**Comment by k0shk0sh** [comment]
@AdrianVovk i made it stock progress /shrug

**Comment by yakov116** [comment]
@k0shk0sh i actually liked the last one you did.

Make it an option :wink:

**Comment by avently** [comment]
@yakov116 I liked jumping animation. It was creative and cool

**Comment by k0shk0sh** [comment]
Loool, so :( I'm lost. Customization it is then

**Comment by Scrumplex** [comment]
I likw thos one :smile:
