### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by victor-iyiola** [k0shk0sh/FastHub#1171]
**FastHub Version: 4.5.0**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Infinix  
- **Brand:** Infinix  
- **Model:** Infinix HOT 4 Lite  
---

It doesn't process **Jupyter or IPython Notebook** the raw source codes are annoying to look at. It'll be great if this can be included in the next update. Thanks! Cool updates though :grinning:

**Comment by yakov116** [comment]
Please search before opening an issue

Thanks for your feedback

**Comment by k0shk0sh** [comment]
Could you point me to these files please!!!

**Comment by victor-iyiola** [comment]
@k0shk0sh 
Here's an example:

https://github.com/victor-iyiola/deep-convolutional-GAN/blob/master/generating-handwritten-digits.ipynb

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/1JKbRLq.png)


Can you tell me what is going on? Whats the issue here? The code is highlighted

**Comment by yakov116** [comment]
@k0shk0sh on desktop its formatted

![image](https://user-images.githubusercontent.com/16872793/31864257-7723917e-b728-11e7-8a0d-382b68eac10d.png)

**Comment by victor-iyiola** [comment]
The code highlighting is great but can it be formatted on phone also just like it is on desktop?
