### ISSUE TITLE
Avatar don't update

### ISSUE THREAD

**Issue by vlourme** [k0shk0sh/FastHub#1172]
**FastHub Version: 4.5.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy A3(2016)  
---

Avatar was changed on website but it stays old on app

**Comment by k0shk0sh** [comment]
Stays old until when? Did u at least restart the app?

**Comment by vlourme** [comment]
Oh sorry, after a second restart it changed

**Comment by k0shk0sh** [comment]
I'm requesting user profile on app start and it's not instant because I can't know :)
