### ISSUE TITLE
Unable to consecutively merge pull reqiests

### ISSUE THREAD

**Issue by edo9300** [k0shk0sh/FastHub#1175]
**FastHub Version: 4.5.0**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** nubia  
- **Brand:** nubia  
- **Model:** NX529J  
---

If I have multible merge able pull requests in my repo, and I merge 1 of them, when trying to merge others they all will say "some checks are pendings", and I'm forced to restart the app

**Comment by k0shk0sh** [comment]
When it says that, ignore it because GitHub is returning me that some checks are pending and you can ignore them.

**Comment by edo9300** [comment]
The problem is that I cannot merge from the app until a restart...

**Comment by yakov116** [comment]
@edo9300 Whats happens if you wait 30 seconds?

**Comment by edo9300** [comment]
Apparently after waiting a while it allows you to merge again. Even if sometimes that's a bit annoying 😞, and I remember sometimes I could merge some commits consecutively.

**Comment by yakov116** [comment]
@edo9300 its github not the app that is the issue
