### ISSUE TITLE
No end of list animation

### ISSUE THREAD

**Issue by EmmanuelMess** [k0shk0sh/FastHub#1176]
**FastHub Version: 4.5.0** 
**Android Version: 6.0**  
**Device Information:**  
- MANUFACTURER: Motorola
- BRAND: Motorola
- MODEL: Moto E2 4G>  
---
Go to "Issues" and scroll down to the first one (chronologically, last one in the list) and you won't see something like this to indicate the end of the list: 
![screenshot_20171023-184705](https://user-images.githubusercontent.com/10991116/31914935-120b65cc-b823-11e7-9551-b7fd3b3f2055.png)
I've tried turning on list animations, white and dark themes and restarting the app.
Here's what I see:
![screenshot_20171023-185259](https://user-images.githubusercontent.com/10991116/31915095-94a7be72-b823-11e7-9bd2-5d383539fbd8.png)

**Comment by k0shk0sh** [comment]
The list scrolling will end once you can't scroll anymore 🤷‍♂️
