### ISSUE TITLE
Organizations missing wiki error

### ISSUE THREAD

**Issue by SGospodinov** [k0shk0sh/FastHub#1177]
**FastHub Version: 4.5.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

When I try to open non- existing wiki page for organization repo I got a server error(toast) instead of no wiki activity.

**Comment by yakov116** [comment]
@SGospodinov please read them faq
