### ISSUE TITLE
Reporting an issue bug

### ISSUE THREAD

**Issue by SGospodinov** [k0shk0sh/FastHub#1178]
**FastHub Version: 4.5.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

Pasting (or trying to) in report an issue activity cause error that makes the application crash crash.

**Comment by k0shk0sh** [comment]
Could you be more specific? I didn't get you

**Comment by SGospodinov** [comment]
When I go to  'Report an issue' and try to paste something (long-press/hold) in the Title section the application just dies.

**Comment by k0shk0sh** [comment]
What were you trying to paste?? I can't produce it for real.

**Comment by k0shk0sh** [comment]
And I can't find it in crash reports ?

**Comment by SGospodinov** [comment]
I've sent crash reports. I'll try to send you record of my screen as well.

**Comment by k0shk0sh** [comment]
the weird thing is that I didn't see any crash report from nexus 5, all i see related crashes are coming from huawei phone.
