### ISSUE TITLE
Branches issues

### ISSUE THREAD

**Issue by shgaurav** [k0shk0sh/FastHub#118]
hey, will you be adding branches drop down for the commit screen? It will be extremely usefull on that screen. Also, When i look at my own repositories, my commits are not updated for some reason. They are not showing me the latest commits. I have made commits on one of the share repos but still.doesn't show up there. Hope this feedback helps! Fasthub is probably the most smooth gitbub client.

**Comment by k0shk0sh** [comment]
refer to #100
