### ISSUE TITLE
Adding a reaction duplicates the emoji strip

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1182]
**FastHub Version: 4.5.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

Navigate to any comment, press the "reaction" button and leave any reaction. As result, the duplicated reactions pane strip is inserted:
![](https://i.imgur.com/58ffVru.png)

After you refresh the comments, it will disappear.

**Comment by k0shk0sh** [comment]
Could you be more specific????

**Comment by k0shk0sh** [comment]
P.S: I'm against this, it was your idea to add the reactions to bottom. 

P.S: they behave exactly like the ones that appears when you click on the emojie icon. 


Despite the fact that I should show the one that only reacted to I was meh, show them all.

**Comment by zvirja** [comment]
Sure, let me describe. The issue is that you see 2 strips at the same time. If you later refresh the feed you will not be able to see that behavior more - strip will appear either above or below the comment.

The bug is that we shouldn't add the strip _below_ the comment _while_ the strip above is displayed.

> P.S: I'm against this, it was your idea to add the reactions to bottom.

Well, I imagined that in a bit different shape. I also don't like to see the _same_ strip as it contains a "empty" emoji also which is annoying. Rather, I expected that only emoji with count > 0 will be displayed. The click handler would be simply open dialog with people reacted. Also it had to be left-aligned.
