### ISSUE TITLE
App crashes when tapping on Issue's title to edit it.

### ISSUE THREAD

**Issue by christianv07** [k0shk0sh/FastHub#1184]
**FastHub Version: 4.5.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

It's happening 100% of the time. All I do is to try to edit the title of an already existing issue on any repository.

**Comment by k0shk0sh** [comment]
Aha, so it's yours.

Your device has a real bug in the whole textview framework alot of crashes just happen because of your phone and no other phones.

Its internal crash btw and not within FastHub so I can stop it from crashing.

**Comment by yakov116** [comment]
@christianv07 @k0shk0sh #1178 

I think this is an Android 8.0 bug...

**Comment by k0shk0sh** [comment]
It's nooot.

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/WVRjXWw.png)
