### ISSUE TITLE
Can't download private repository files.

### ISSUE THREAD

**Issue by abtExp** [k0shk0sh/FastHub#1185]
**FastHub Version: 4.5.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Brand:** motorola  
- **Model:** Moto G 2014  
---

Can't download the private repo files. All public repos are downloadable but none of my private repos can be downloaded.

**Comment by yakov116** [comment]
@abtExp do you get some kind of error message?

**Comment by k0shk0sh** [comment]
It's exactly like private wiki, which it will never be fixed because GitHub wants some tokens that only exists on their cookies.

**Comment by yakov116** [comment]
@k0shk0sh wow I never knew this

**Comment by k0shk0sh** [comment]
If we could download then we should display wiki 🤣, same goes to enterprise where I can't display user images because they require authonicate'd user token which only exists in browser cookies.

**Comment by abtExp** [comment]
Ohhkk.. got it.
