### ISSUE TITLE
Animated gifs don't play right on fasthub

### ISSUE THREAD

**Issue by Thatkookooguy** [k0shk0sh/FastHub#1191]
**FastHub Version: 4.5.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

Here's an example: https://github.com/janpaepke/ScrollMagic/issues/733

Open on mobile web browser and fasthub and see the difference

**Comment by KurtJacobson** [comment]
The gifs in the linked example animate just fine on my device.

**FastHub Version: 4.5.0**
**Android Version: 5.0.1**
**Device Information:**
  * **Manufacturer:** Samsung
  * **Model:** Galaxy S4
