### ISSUE TITLE
What about Bitbucket

### ISSUE THREAD

**Issue by yeboahnanaosei** [k0shk0sh/FastHub#1193]
**FastHub Version: 4.5.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy A5  
---

Guys do you have any similar app for Bitbucket? Perhaps you can even have one app with which we can sign into separate hosting platforms

I don't know if I'm clear.
You can reach me: yeboahnanaosei@gmail.com

**Comment by k0shk0sh** [comment]
No plans so far to make one for any other platforms than GitHub. 

sorry.
