### ISSUE TITLE
No actualiza commit's

### ISSUE THREAD

**Issue by Az-PhoenixLeo** [k0shk0sh/FastHub#1195]
**FastHub Version: 4.5.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone 3 Max (ZC520TL)  
---

En la ventana principal donde se muestran todos los commits, al llegar a un determinado número de commits ya no se muestra actualizado, a pesar de que existen mas commits en el repositorio.

**Comment by dedepete** [comment]
Please, use English when creating reports.
