### ISSUE TITLE
no project view 

### ISSUE THREAD

**Issue by kenoverse** [k0shk0sh/FastHub#1199]
**FastHub Version: 4.5.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 4c  
---

there is no project view in this mobile application while in browser it is available

**Comment by k0shk0sh** [comment]
There is an icon for that at the bottomNavigation last icon to be more specific.
