### ISSUE TITLE
Non-adaptive App shortcut icons

### ISSUE THREAD

**Issue by Wikiwix** [k0shk0sh/FastHub#1200]
**FastHub Version: 4.5.1**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
The app shortcuts don't have adaptive icons yet.

**Comment by k0shk0sh** [comment]
Care to open a PR? They are in svg format so they won't be hard to do?
