### ISSUE TITLE
Can not open repos without README

### ISSUE THREAD

**Issue by ramottamado** [k0shk0sh/FastHub#1202]
**FastHub Version: 4.5.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 3  
---

I cannot open repos without README in this app. It simply says 'not found' and then open the repo link in browser.

**Comment by k0shk0sh** [comment]
Oops, that's really gooood catch :'( .

**Comment by k0shk0sh** [comment]
this was fixed in latest release few days ago.
