### ISSUE TITLE
Display issue labels on issues list

### ISSUE THREAD

**Issue by HizkiFW** [k0shk0sh/FastHub#1203]
**FastHub Version: 4.5.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7 Edge  
---

Navigating through issues would be easier if the labels were displayed on the issue list too. Right now, I have to tap on the issue to see its labels.

**Comment by k0shk0sh** [comment]
Long press the issue to avoid heading inside of it.

**Comment by k0shk0sh** [comment]
Basically it will give you quick overview and you could even comment from there
