### ISSUE TITLE
Cannot view : username.github.io repo

### ISSUE THREAD

**Issue by shgysk8zer0** [k0shk0sh/FastHub#1207]
**FastHub Version: 4.5.1**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

Just says repo not found and takes me to mobile GitHub page.

I'm guessing this might be an issue with the "." in the repo name.

**Comment by k0shk0sh** [comment]
Link please

**Comment by k0shk0sh** [comment]
#1202 

Unfortunately its a bug

**Comment by shgysk8zer0** [comment]
https://github.com/shgysk8zer0/shgysk8zer0.github.io has a README. This is not a duplicate of #1202

**Comment by k0shk0sh** [comment]
It is related because all 404 will result to exiting the app

**Comment by k0shk0sh** [comment]
The way I did handle that was really rushy :'( I'll release new update tomorrow

**Comment by shgysk8zer0** [comment]
Really. This issue is not resolved. Just installed update and same thing keeps happening.

I've now done a search for ".github.io" and not a single one of the dozen results I've tried will open in app.

My repo in particular has no reason that I can think of to 404 on anything.

**Comment by k0shk0sh** [comment]
this is fixed, its due to me replacing .git from the repo name :D 

i'll be making new release right now :)
