### ISSUE TITLE
Last releases lack APK attachment

### ISSUE THREAD

**Issue by IzzySoft** [k0shk0sh/FastHub#1208]
Checking my logs I just noticed that the last 2 releases had no `.apk` file attached (so my repo couldn't update it). Just forgotten, or is this intentional? The promising black box on the README.md saying "Direct APK download" is currently misleading (going to "latest" where there is no `.apk`) :wink:

**Comment by yakov116** [comment]
@IzzySoft Yes.

You can get it from XDA

**Comment by k0shk0sh** [comment]
I'll try and upload it later.

**Comment by yakov116** [comment]
@IzzySoft done!

**Comment by IzzySoft** [comment]
@yakov116 XDA doesn't work with my auto-updater, sorry. But the newly attached file does work with it: update fetched, "upsync" started, [find it here](https://apt.izzysoft.de/fdroid/index/apk/com.fastaccess.github) in a few minutes :wink: Thanks!

**Comment by IzzySoft** [comment]
@yakov116 unfortunately, the latest releases miss the APK again. Could you please continue attaching it? Starting with the most recent one will suffice.

**Comment by yakov116** [comment]
@IzzySoft sure will do it in a few

**Comment by IzzySoft** [comment]
@yakov116 please add a small unit: hours would be fine, minutes superb – months or even years would be shocking :fearful:

**Comment by yakov116** [comment]
@IzzySoft sorry got very busy. Will do it later tonight

**Comment by yakov116** [comment]
@IzzySoft done

**Comment by k0shk0sh** [comment]
Honestly I shouldn't upload the apk anymore since its already in foss. 
Is there another reason that I should upload it?

**Comment by IzzySoft** [comment]
@k0shk0sh Thanks! Fetched & updated in the repo (currently syncing).

**Comment by k0shk0sh** [comment]
It was @yakov116 who uploaded it. The thanks should go to him ;),

**Comment by IzzySoft** [comment]
@k0shk0sh Yepp, just noticed: I've got the notification for @yakov116's post, and when writing the answer yours was the last – got me confuse (not really awake yet). So what do you mean by "its already in foss"? As I wrote, I just checked and it's on F-Droid Archive in an older version only. It's not in the main repo as far as I can see.

**Comment by IzzySoft** [comment]
Ahem, shall we keep this issue open? v4.6.0 lacks the `.apk` again :scream:

**Comment by IzzySoft** [comment]
@k0shk0sh v4.6.1 as well lacks the APK. Did you give up on it? Shall I remove it from my repo? We don't want the users to stick with old versions, do we?

**Comment by yakov116** [comment]
@IzzySoft apkmirror...

**Comment by IzzySoft** [comment]
@yakov116 if that's the final say, I'll have to remove [the app from my F-Droid repo](http://apt.qumran.org/fdroid/index/apk/com.fastaccess.github). Can't update it from there, sorry. So will you confirm? Or deny?

**Comment by yakov116** [comment]
@IzzySoft why it's the exact same apk!

**Comment by IzzySoft** [comment]
@yakov116 that might be. But it's a different server and structure. My auto-updater doesn't know how to handle it. And I don't have the time to program all possible structures to scrape the APK data out of different HTML structures.

My script can deal with Github releases, with the APK inside the repo, and with the APK having a "fixed URL" (e.g. `http://example.com/latest.apk`). Not with Playstore, APKMirror etc. Not with changing links on pages other than Github releases/repo (`http://example.com/app_v1.2.3.apk` which next time is `app_v1.2.5.apk`) where I don't know what to look for.

You say APKMirror, other projects say Dropbox, Mega, our CI Build server … Sorry, but I cannot effort to deal with all those. I do my best to provide some additional service – but I'm only a single person with limited resources. And I've got some other work to do for living (unfortunately). So I hope you can understand why I say "Can't update it from there". And if I can't update it, I can't provide it in my repo: users would rightfully blame me for outdated versions.

----

No bad feelings: you do that in your spare time as well, and you have to budget your time as I have – so we're sitting in "comparable boats" (not necessarily the same boat :wink:). So let's see where we can meet: Can you maintain your `.apk` here at Github, or provide it via a "fixed URL" some place? Then I can pick it and provide it via my repo. If you can't, I say thank you for your good and well appreciated support in the past, but I have to remove your app from my repo and we "part" as friends. All must be fair for both sides: We each must respect each others "budget"/limits.

**Comment by MartinX3** [comment]
why don't you use travis CI and the github graph api?

**Comment by yakov116** [comment]
@MartinX3 for building the apk??? What are you talking about?

**Comment by k0shk0sh** [comment]
@IzzySoft I literally was thinking of dropping that support because of my experience with FOS users, and I bet you know the story and everything (as I have seen you involving in some conversations) but you were here since the beginning and I don't easily forget those who gave hands. 

@yakov116 could you please proceed with uploading the APK as you usually do into the release when you have time? I know i'm asking for too much, but honestly I have no time right now to do that.

**Comment by yakov116** [comment]
@k0shk0sh sure. Actually it would be much easier for me if I would be able to do it from the app :stuck_out_tongue_closed_eyes::sunglasses:

**Comment by MartinX3** [comment]
@yakov116 

> "for building the apk???"

I don't know, why you are using so many "???", but yes.

> "What are you talking about?"

About building the APK's with travis.
You read the same conversation like me, or didn't you and live on another planet?
https://github.com/harmittaa/travis-example-android

**Comment by yakov116** [comment]
@MartinX3 we got messed up in the past when trying to do this PLUS it would require @k0shk0sh to set it up with his key

**Comment by MartinX3** [comment]
@yakov116 
When he set it up with his key, it is done and will work on every release

But what you you mean with "messed up"?
May I help you somehow?

**Comment by yakov116** [comment]
>@yakov116
When he set it up with his key, it is done and will work on every release automatically.
But what you you mean with "messed up"?
May I help you somehow?

Ok lets give a little background on how the repo is setup. By default the repo is building a debug build ( for reasons I have no time to explain). By uing travis to build the apk 2 things would happen. 

1.  The builds would be debug build and have a different key
2. The pro features would be enabled and there would be a loss for @k0shk0sh

**Comment by MartinX3** [comment]
@yakov116 
Of course are debug builds important to test the software and of course should be everything enabled, if you run a debug build, to test everything.

But of course you can set up travisCI to build release debug build with different keys, if you want.
Other projects did that successful, so with some reading and understanding it would work here to and save time.

https://docs.travis-ci.com/user/deployment/releases

**Comment by yakov116** [comment]
@MartinX3 please read what i wrote. 
>By default the repo is building a debug build ( for reasons I have no time to explain).

Im not saying it not possible but its not an option at this point

**Comment by MartinX3** [comment]
@yakov116 
It's okay if you don't want this service a CI like travis will give you.

And it is not only ONE person.
The automatically build APK can be placed everywhere
github, apkmirror, google playsotre, f-droid, etc.
It is a time saving investment.

**Comment by yakov116** [comment]
@MartinX3 OK lets not fight over this. I cant link you to where we had a whole discussion since it was a private one.

In other news the apk was uploaded

**Comment by MartinX3** [comment]
@yakov116 
If you need some help in the future to implement this, I would be happy to help you. :)

**Comment by IzzySoft** [comment]
@k0shk0sh Thanks!

@yakov116 

> For one person to get just the apk?

You really believe I'm the only one using [my repo](https://apt.izzysoft.de/fdroid) (which is for what my updater grabs your APKs, and those of 350+ other projects) :smile: To give you some numbers: Avg daily hits 100k+, avg daily visits 10k+, monthly throughput ~60GB (i.e. roughly 2GB per day). In 12/2017, there were 106 downloads of the Fasthub APK via my repo for v4.5.7, plus 6 for v4.5.1, plus 1 for v4.4.2 – which suggests there are more than 10 or 20 users behind it (why should one load the same version multiple times); as use of the repo is anonymous (and I'm ***not*** using any tracking on my sites), I cannot give any numbers on "real users" or "installations".

As @MartinX3 pointed out, having an integrated CI has many advantages: while the first-time setup might not be easy (I cannot tell, never having done that), it not only could place the files on a release, but also tell you *at each commit* if you broke something, plus give your testers "nightly builds" if you wish so. Not saying you have to use CI – but agreeing that would be a "once done it's done, just benefit then" thing.

> I will try to upload the APK from now on

Thanks a lot – in the name of all the users obtaining it via my repo!

@MartinX3 Thanks for offering your help! I think the problems @yakov116 is mentioning should be solvable by someone familiar with Travis. And I guess it could even be configured to *not* place every build into "public space" – but just the ones defined such, and even just on a release if so wished. Looks like the team currently lacks time to concentrate on that task – so maybe they can take you up on your offer at a later time.

@ALL: Let's return to "good mood mode". We're not fighting against each other, but against the problems, right? :innocent:
