### ISSUE TITLE
Code takes too much time to get highlighted syntax

### ISSUE THREAD

**Issue by iamsubhranil** [k0shk0sh/FastHub#1209]
**FastHub Version: 4.5.1**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** HM 2LTE-IN  
---

Every time I open a source file, it takes atleast 20 seconds to parse and syntax highlight a 8-10KB file. For a file of size 40-50KB, it stays there almost a minute. Why it takes so much time just to syntax highlight source files?
Also, not always correct syntax highlighting is displayed. Example [Source](https://github.com/iamsubhranil/NumericalAnalysis/blob/master/gaussjacobi.c).

P. S.: Time is relative :stuck_out_tongue_closed_eyes:

**Comment by k0shk0sh** [comment]
For me that file took less than a second, its about devices and their oem and what they do to Android Webview, I understand some large file might take some time to render but not with that file, could you update your webview if it exists in your phone (xiaomi)

**Comment by iamsubhranil** [comment]
That example was for no syntax highlighting. That is also a problem I'm having with fasthub from a long time.

I didn't gave any source for the titled issue. Let me find one.
