### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by Rainer-Lang** [k0shk0sh/FastHub#121]
low(est) prio

**Comment by k0shk0sh** [comment]
Hello Rainer, could you elaborate on this? I didn't get which history you referring to.

**Comment by Rainer-Lang** [comment]
Every search field should provide a history "recently searched repos/users/...".
Like in this lib: https://github.com/lapism/SearchView

**Comment by k0shk0sh** [comment]
The app has this functionality, simply when you search for something, it will be save locally and the next time you key in at least one value. it would list the specific suggestion for you.
