### ISSUE TITLE
Lock issue is shown when user is the author 

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#1211]
**FastHub Version: 4.5.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** HTC  
- **Model:** Nexus 9  
---

I opened an issue on a repo that I don't have write access but I was still offered to lock the issue.

![](https://i.imgur.com/4ItbibP.png)

**Comment by k0shk0sh** [comment]
That's kinda strange, but doesn't really matter because GitHub will handle it. But fixing it would be easy :)
