### ISSUE TITLE
This URL does not fully render

### ISSUE THREAD

**Issue by julianxhokaxhiu** [k0shk0sh/FastHub#1212]
**FastHub Version: 4.5.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

See https://github.com/mattdesl/budo/blob/master/docs/api-usage.md

Open in the app and open in the browser.

On the brower it looks ok, on the app it stops at the `server` option documentation.

**Comment by julianxhokaxhiu** [comment]
Sorry, may I ask on which version is this bug fixed?

**Comment by k0shk0sh** [comment]
definitely the next version (update) :)

**Comment by julianxhokaxhiu** [comment]
Awesome, thanks :)

**Comment by k0shk0sh** [comment]
The update is today most definitely
