### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by Gauti4417** [k0shk0sh/FastHub#1213]
**FastHub Version: 4.5.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5) Plus  
---

I don't know if it is possible or not, but can the 'delete repository' function can be added?

**Comment by k0shk0sh** [comment]
Would you believe that this function is there and works 100% but hidden? Because alot of people scared of this permission I removed the permission and hide it.

**Comment by Gauti4417** [comment]
Lol... Okay thanks... :) Let me find the hidden button then...

**Comment by k0shk0sh** [comment]
RepoPagerActivity onMenuItemClicked or selected can't remember the name

**Comment by Gauti4417** [comment]
I cannot find that hidden option 😅. Can you help me out? Thank you in advance

**Comment by k0shk0sh** [comment]
https://github.com/k0shk0sh/FastHub/blob/7265c76b39093a20a126b4e659710daa186afcd4/app/src/main/java/com/fastaccess/ui/modules/repos/RepoPagerActivity.java#L-544

**Comment by Gauti4417** [comment]
Thanks :)

**Comment by Gauti4417** [comment]
Okay so this feature is present. Damn that's cool

**Comment by k0shk0sh** [comment]
But it will never be enabled :)

**Comment by Gauti4417** [comment]
😂😂😂.. i thought there might be some secret way(like pressing some button 7 times, or like pressing volume button in settings menu like the nova launcher does) would unlock those options. But it's fine. You know what's better for the app and what's not. :)
