### ISSUE TITLE
Labels can't be added

### ISSUE THREAD

**Issue by droidmonkey** [k0shk0sh/FastHub#1214]
**FastHub Version: 4.5.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

When attempting to add labels to an I get two different responses from the app:

1. If adding one label it reports "cannot be found" and redirects to a web based version of the issue.

2. If adding more than one label it reports "cannot be found" and redirects to a json output of the GitHub api for the issue.

In both cases, no labels are actually added to the issue.

**Comment by k0shk0sh** [comment]
Could you tell me more?

Private repo? Enterprise? Did you check if the labels are there and not deleted?

**Comment by k0shk0sh** [comment]
I could add labels just fine

**Comment by droidmonkey** [comment]
Public repo, labels are legit (use them in web version no problem). I'll try again after going to the issue straight from the repo main page instead of from the notification.

**Comment by droidmonkey** [comment]
I hit the pencil icon, then the labels entry, select a label, hit the arrow in top right. The issue (activity?) closes and an error at the bottom shows "Not Found".

**Comment by k0shk0sh** [comment]
That's really weird, 
Could you tell me how many accounts are you logged in with and is there any enterprise acc with them?.  

I'm a bit lost in here because its the first this occurred.

**Comment by droidmonkey** [comment]
Only logged in with my personal account, nothing too sexy. Everything else works great, but i also just now found I can't approve PR's anymore from the app.

**Comment by yakov116** [comment]
@droidmonkey using a VPN or the like?

**Comment by k0shk0sh** [comment]
Thats really weird!, could you make a fresh installation of FastHub? or logout/login.

**Comment by droidmonkey** [comment]
Ok just uninstalled and reinstalled the app. Logged in trying oauth first, same result. Logged out then back in using username/password... Same result.

The repository I am working on here is https://github.com/keepassxreboot/keepassxc

These features used to work about two versions ago and has since been broken. We haven't changed any security settings on our repo.

**Comment by yakov116** [comment]
@droidmonkey sounds like a github issue

**Comment by droidmonkey** [comment]
How embarrassing for me... It looks like I accidentally disabled the access to my organization when removing access granted to other apps that we are no longer using. This is a total non-issue now that access has been restored. Although, it is quite interesting that I could add labels issue using ```Pencil -> Edit``` and not directly through ```Pencil -> Labels```.
