### ISSUE TITLE
Zoom then click on any day in contribution time line

### ISSUE THREAD

**Issue by ozcaan11** [k0shk0sh/FastHub#1215]
**FastHub Version: 4.5.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** General Mobile  
- **Model:** General Mobile 4G  
---

Zoom then click on any day on contribution time line in users profile

**Comment by k0shk0sh** [comment]
Could you elaborate more?

**Comment by ozcaan11** [comment]
There is a section at the bottom of users profile shows the contribution day in this year. Can you make it clickable for any day. When users click on a day it will show which commit have done in this day

**Comment by k0shk0sh** [comment]
that wont be possible because its rendered as an image after retrieving the svg from github, 

i'll loop through the whole svg content, extract the data and draw it on a canvas which in result making each one clickable would be impossible. its only for display :p 

sorry tho.

**Comment by ozcaan11** [comment]
Ok 👍 thanks for such quick reply 😊
