### ISSUE TITLE
Duplicate notification channels

### ISSUE THREAD

**Issue by Burnergames** [k0shk0sh/FastHub#1216]
**FastHub Version: 4.5.1**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

FastHub seems to be generating a lot of duplicate notification channels. 

![from the settings app](https://i.imgur.com/hyD5JId.png)

I have no idea why. Sorry that I'm kinda useless.

**Comment by yakov116** [comment]
@Burnergames something tells me it has to do with Android 8.1 and not fasthub. Will wait for @k0shk0sh to chime in

**Comment by k0shk0sh** [comment]
That's kinda weird, channel names should be unique in Android and idk how they are duplicated.

Could you reinstall the app? In 4.5.1 there is some update regards this and maybe it will fix it.

Im not sure clearing app data will clear notification channel name, you could try that as well.

**Comment by k0shk0sh** [comment]
any update on this?
