### ISSUE TITLE
Contribution graph color error (applies only in M10 31)

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1218]
It is strange. 

The contribution graph color is orange, but in fasthub, it has a different color.

https://i.imgur.com/vEzV2XI.png

**Comment by cozyplanes** [comment]
lol

**Comment by k0shk0sh** [comment]
Because in FastHub its base on theme color, u can change it from settings to whatever color you like. 


P.S: you could ask in slack for such things and you know I'll reply you there.

**Comment by cozyplanes** [comment]
(i know, i know, i just asked for fun. hehe)

**Comment by k0shk0sh** [comment]
Holly shit, I just realized that contribution isn't working because GitHub changed color scheme for the graph.

Daaaaamn

**Comment by cozyplanes** [comment]
RIP FastHub Graph

**Comment by yakov116** [comment]
@cozyplanes lolol are you drunk?

**Comment by cozyplanes** [comment]
@yakov116 i dont understand your point. It was just a joke though, kosh seems to be real
