### ISSUE TITLE
Contribs not showing

### ISSUE THREAD

**Issue by asishadhikari** [k0shk0sh/FastHub#1220]
Contributions in other users profile not showing up. I use this app to keep my GitHub contributions. Not sure if this is only today as GitHub changed the color to yellow and black for today in the contributions graph.
Thanks!

**Comment by yakov116** [comment]
@asishadhikari Please open the issue using the app

**Comment by k0shk0sh** [comment]
The duplicate issue is just one issue away, could you please search before opening new issue :) thanks
![](https://i.imgur.com/YTErP1s.png)

**Comment by asishadhikari** [comment]
My bad.
