### ISSUE TITLE
Python notebook

### ISSUE THREAD

**Issue by spaceVStab** [k0shk0sh/FastHub#1221]
**FastHub Version: 4.5.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 4  
---

Not able to view the the note book

**Comment by yakov116** [comment]
@spaceVStab What?

**Comment by spaceVStab** [comment]
The jupyter notebook displays as JSON format in the application rather than a jupyter notebook would have appeared in Github Desktop version. If you are still confused to understand me try to open a .ipynb format files in ur mobile application you will get the issue.

**Comment by yakov116** [comment]
@spaceVStab duplicate  x4
