### ISSUE TITLE
Feature request: Feed notifications

### ISSUE THREAD

**Issue by svenhofmann99** [k0shk0sh/FastHub#1224]
**FastHub Version: 4.5.2**
**Android Version: 7.1.1**  
- BRAND: Sony 
- MODEL: Xperia Z5  
---

Hello,
as FastHub is the best app for using GitHub on Android devices, I would really like to request a feature.
It would be nice to be notified when something happens in the feed. I saw the notification options but I think they are not for the feed.

Thank you for the great app
Sven

**Comment by yakov116** [comment]
@svenhofmann99 well whatever you are following you will get a notification.  Make sure the notifications is on for web (not just email).
