### ISSUE TITLE
How to buy in？

### ISSUE THREAD

**Issue by forgiveboo** [k0shk0sh/FastHub#1227]
**FastHub Version: 4.5.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** honor  
- **Model:** Honor 8  
---

I'm Chinese, how do you buy your app?

**Comment by iamale** [comment]
@forgiveboo Maybe try https://github.com/thermatk/FastHub-Libre?

(We still need to find another way to support author somehow though)

**Comment by k0shk0sh** [comment]
What type of payments are accepted in your country?

**Comment by k0shk0sh** [comment]
I can't do much about this, Android doesn't accept devs to put anything than in app purchases by google. so i'll figure out something at the end :)
