### ISSUE TITLE
Multiple Notifications

### ISSUE THREAD

**Issue by smiller171** [k0shk0sh/FastHub#1228]
**FastHub Version: 4.5.2**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

Whenever I get a GitHub notification, the app renotifies every hour or so until I read the notification. This is exceedingly annoying. Sometimes I just want to leave it as unread for later.

**Comment by k0shk0sh** [comment]
The only way to fix this, is to save notifications in local db everytime its displayed in the notification and cross check it.

**Comment by smiller171** [comment]
Sounds pretty simple. Hash the payload to get a uid for that comment or whatever else is notifying and do a lookup for the hash before notifying the user.

**Comment by rancidfrog** [comment]
Why not use default notification, which only bring back dismissed notifications on reboot?

**Comment by k0shk0sh** [comment]
@rancidfrog could you elaborate?? 

In every hour, I'll go and grab latest from GitHub and I don't know what is there and what is not which simply will behave as it is now to show the notification.?

How Android will know?

**Comment by smiller171** [comment]
@rancidfrog because he's handling notifications client side. Using GCM requires handling notifications from a central server and pushing them out. I'd prefer he not keep my account logged in on a server he controls. This is however the approach GitHub would take with a first party app.

**Comment by smiller171** [comment]
The app isn't sending the "same" notification each time, it's sending a new notification about the same content.

**Comment by smiller171** [comment]
@k0shk0sh was there a PR for this? Would be interested in seeing how it was implemented. Also, when can we expect the update to hit the Play Store?

**Comment by k0shk0sh** [comment]
Commits from my side are delayed on purpose. 


The way implemented is creating new local db table that stores notification ids and cross check (filter) them and after everything is done, delete old records and insert new ones :)

**Comment by skjnldsv** [comment]
So in the end, is this fixed? Or planned? :)

**Comment by k0shk0sh** [comment]
@skjnldsv it is fixed sometime ago, but haven't got the time to release, sunday or tomorrow :) 


Still thinking of other things to do before releasing.

**Comment by skjnldsv** [comment]
Nice to hear!!
Thank you so much! :)

**Comment by k0shk0sh** [comment]
I just made a release. :blush:
