### ISSUE TITLE
Make reading notification to be done in service

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#123]

**Comment by xdk78** [comment]
Nice. When you upload the newest version of the app? Imo version would be 1.1.0 instead 1.0.7
Btw https://github.com/mikepenz/AboutLibraries 
this is very helpful library to add info about open source libs licenses...

**Comment by k0shk0sh** [comment]
@xdk78 it will be 1.1.0 since I have added stuff here and there. but i'll have to remilestone some issues as they are haven't been done yet.

**Comment by k0shk0sh** [comment]
@xdk78 yea including it would be awesome, PR would be cool but its out of my scope currently
