### ISSUE TITLE
FR: Dont load pictures when on mobile internet

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#1231]
Would be nice if there is an option to disable pictures when not on wifi.

**Comment by k0shk0sh** [comment]
You can go settings and disable playing gifs and on them

**Comment by mueller-ma** [comment]
Not loading pictures saves a lot of data...

**Comment by k0shk0sh** [comment]
Well, as I live in Germany I can tell that data here is sucks and expensive 😂
