### ISSUE TITLE
Issue title cut off

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1233]
**FastHub Version: 4.5.2**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

https://github.com/devRant/devRant/issues/225

In issue view (full mode), the title gets cut off. Even the `...` isnt shown.

**Comment by k0shk0sh** [comment]
Could you please elaborate????????????????????????????? Ian, its getting annoying really. 

![](https://i.imgur.com/NaOgbQU.png)

**Comment by cozyplanes** [comment]
In my side
There is no info button...

Maybe it happens in original poster's side. Let me test it after i logged out

![](https://i.imgur.com/pdvLX05.png)

**Comment by cozyplanes** [comment]
I am in another account, but i dont see the info button in top right.... Strange

![](https://i.imgur.com/gAGQCZb.png)

**Comment by cozyplanes** [comment]
May i ask how this was fixed

**Comment by k0shk0sh** [comment]
By always showing the icon :)

**Comment by cozyplanes** [comment]
That was easy
