### ISSUE TITLE
Error approving pull requests

### ISSUE THREAD

**Issue by simonbtomlinson** [k0shk0sh/FastHub#1236]
**FastHub Version: 4.5.2**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

I get a message that says "Error occurred while communicating with the server" when I try to approve a pull request. Other network functionality, such as commenting on pull requests, still works.

I have AdAway installed and blocking ad sites via a hosts file, but other than that I can't think of a reason why my phone might be intercepting the network traffic.

**Comment by yakov116** [comment]
@simonbtomlinson are you doing this for an org a private repo or public?

**Comment by simonbtomlinson** [comment]
A public repository, although I think I've had the same problem with a
private one recently.
