### ISSUE TITLE
Cannot commit to specific branch

### ISSUE THREAD

**Issue by NoahConstable** [k0shk0sh/FastHub#1239]
**FastHub Version: 4.5.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

Hello. I've tried to commit changes to a file to a specific branch and it always commits to the master branch. 

I've just purchased premium so I could edit and would hate for it to only commit to master. 

Thank you.

**Comment by lexelby** [comment]
In my case, it didn't commit to master.  Instead, I got a red error banner, ".travis.yml does not match <a sha hash>" or something like that.  Made me wonder if it was confused that the file I was editing didn't look like the one on master (because I was on a branch).

**Comment by lexelby** [comment]
In case this is important, I'm also on premium.  Fasthub rocks!

**Comment by Gorislim13** [comment]
Can u fix it 
Bin-chi@mail.com

**Comment by BoBBer446** [comment]
same here
FastHub Version: 4.6.3
Android Version: 7.0 (SDK: 24)
Device Information:

Manufacturer: samsung
Brand: samsung
Model: Galaxy Tab A 10.1

**Comment by BoBBer446** [comment]
Du hast das ganz fantastisch gemacht! Danke!
