### ISSUE TITLE
Quotes in issue comments

### ISSUE THREAD

**Issue by phi1010** [k0shk0sh/FastHub#124]
Quotes such as "t"hese are lost when displaying issue comments.

**Comment by k0shk0sh** [comment]
this issue has been resolved as of 1.0.7 you going to have the comments to act exactly like GitHub website, hashtags & mentions and most links will work properly.

**Comment by k0shk0sh** [comment]
could you on this being fixed in 1.1.0 ?

**Comment by phi1010** [comment]
Yes, much better. Thank you!
