### ISSUE TITLE
Notifications do not work as expected

### ISSUE THREAD

**Issue by filipre** [k0shk0sh/FastHub#1242]
**FastHub Version:**  4.5.2
**Android Version:**  6.0.1
**Device Information:**  
- MANUFACTURER: LG Electronics
- BRAND: Google
- MODEL: Nexus 5
---

Hi!
I might be missing something but I simply cannot get android notifications *outside* the app to work. I would have expected something like a WhatsApp messages or at least a "FastHub" icon in my menu bar indicating a new notification.

Here is what I did:
- [x] Web Notifications activated
![](https://my.mixtape.moe/mfrwtj.png)
- [x] "Enable Notifications" slider is on
- [x] Sync Interval: 20 minutes
- [x] Notifications do appear in the "Notifications" menu *inside* the app

I am also confused. In #877 it is said that push notifications do not work but #1152 opened a bug report about them not working.

Thanks
René

Related Tickets: #1224, #1152, #927, #877

**Comment by yakov116** [comment]
@filipre can you set it to one min? close the app and I will mention you again.

**Comment by k0shk0sh** [comment]
I bet it's because you never enabled email notifications. 

Could you also go to notifications and try out if they load?

**Comment by yakov116** [comment]
@k0shk0sh were loading from email? not from web?

**Comment by k0shk0sh** [comment]
i'm not sure what we even load from, GitHub doesn't state anything, so therefore I'm consfused as well because it simply works for everyone but not him.. 

One question: Where did you download the app from? Foss?

**Comment by filipre** [comment]
Thanks for the fast response!

I enabled Email notifications and set the timer to 1 minute. Now notifications do work. I only realised after that maybe I should not have tried out both suggestions, though.

I deactivated Email notifications again but still have the one minute interval. I wonder if I can reproduce the bug.I can give you some feedback in case I can. Maybe it was also some weird Github-related problem.

**Comment by k0shk0sh** [comment]
It is definitely GitHub related and not Fasthub. :) . So I'm gonna close this, since now we know that u need to enable email notifications too.

**Comment by joblo2213** [comment]
So I was confused because I also did get no notifications.
I then tried to set the github-settings as described in top.
I have no idea if it helped as I havn't been mentioned till now.

Anyway I would suggest providing some information in the app what needs to be done to get notifications as it took me  quite some time to find this.
