### ISSUE TITLE
Login screen does not orient properly on a tablet

### ISSUE THREAD

**Issue by unionhills** [k0shk0sh/FastHub#1243]
**FastHub Version: 4.5.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Alco  
- **Brand:** RCA  
- **Model:** 11 Galileo Pro  
---

When I launch the app using my tablet, the login screen is hard wired to orient itself in Portrait mode, forcing me to turn my head to enter my credentials (I use a tablet with an externally attached keyboard).

**Comment by yakov116** [comment]
@unionhills if the login is your only issue... its only one time :)

Thanks for your feedback
