### ISSUE TITLE
Can not assign to issue.

### ISSUE THREAD

**Issue by soninit** [k0shk0sh/FastHub#1245]
**FastHub Version: 4.5.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 3  
---

Please check this version.

**Comment by yakov116** [comment]
@soninit your going to have to give more info before ei check anything!

Are you trying to do it on a public repo or private?
Is it on an issue or a pull request?

Please give as much info as you can.
