### ISSUE TITLE
Sometimes context menu lacks editing options

### ISSUE THREAD

**Issue by textortexxel** [k0shk0sh/FastHub#1246]
**FastHub Version: 4.5.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Samsung  
- **Brand:** Samsung  
- **Model:** SM-G930  
---

After purchasing Pro, I found out that the context menu for files accidentally reverts to 3-option one (Download, Share, Copy URL) with Edit/Delete gone. Opening repo via another route (organization vs. Pinned) seems to sometimes switch the state.

**Comment by k0shk0sh** [comment]
Its either you aren't collaborator or you ain't the owner of the repo.

Also, maybe you should give it few seconds before it appears because thats a separate api call by itself.
