### ISSUE TITLE
Série 2: Questão 4.2

### ISSUE THREAD

**Issue by MauroAlmeida** [k0shk0sh/FastHub#1247]
Como o id Token é enviado via HTTPS temos garantia que é confiável e autêntico, não foi alterado nem visto por ninguém, por isso não é obrigatório validar a sua assinatura.

**Comment by yakov116** [comment]
@MauroAlmeida english please?

**Comment by k0shk0sh** [comment]
Tokens or whatever aren't transferred to anywhere outside the app but to GitHub once you make any request so you shouldn't worry :) I have plenty of users which uses the app from big companies ;)
