### ISSUE TITLE
Flickering on Google Pixel when text is not long. 

### ISSUE THREAD

**Issue by felipe1982** [k0shk0sh/FastHub#1248]
**FastHub Version: 4.5.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

https://youtu.be/a0zn_edZpf8

**Comment by k0shk0sh** [comment]
the flickering is always happening because you are on low battery mode which disables all the animation. can you try again without battery mode? also it will be great to pass me the repo url :)

**Comment by k0shk0sh** [comment]
nvm, I got the repo myself and I can't produce it :)

**Comment by felipe1982** [comment]
Yes. I think it may be because of battery saving mode. Here is the link https://github.com/mathiasvr/git-pr
