### ISSUE TITLE
Markup languages is unfixed

### ISSUE THREAD

**Issue by i0Ek3** [k0shk0sh/FastHub#1250]
**FastHub Version: 4.5.2**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** oneplus  
- **Model:** A0001  
---

- The markup languages of different repository  unfixed when I flash it under my repository page

**Comment by k0shk0sh** [comment]
Could you explain? I don't get u

**Comment by i0Ek3** [comment]
@k0shk0sh I mean...under Profile option,you can see the repo lists under 'REPOSITORIES' option.However,one of my project write with Java(or other languages),but it show me C++(or others).There are different shows when I flash this page! Can u get me ?

**Comment by i0Ek3** [comment]
@k0shk0sh I sent you pictures with gmail,pleas check it !Merci~

**Comment by cozyplanes** [comment]
The language shown at the side is the language used the most.

**Comment by i0Ek3** [comment]
@cozyplanes Merci my friend~I know you means,and I mean that!

**Comment by yakov116** [comment]
@i0Ek3 what does it show on github? Different than what we are showing?

**Comment by i0Ek3** [comment]
@yakov116 Yes,it show normal on github,but different with app showing.Maybe I should send you some pictures,hold on....(maybe I'm wrong,I dont know)

**Comment by i0Ek3** [comment]
@yakov116 This is picture link,please check it.   https://pan.baidu.com/s/1jIouemM

**Comment by yakov116** [comment]
@i0Ek3 lease upload the picture using the app

**Comment by i0Ek3** [comment]
@yakov116 opps~upload failed,they tell me failed to load pic,so what should I do?

**Comment by i0Ek3** [comment]
不管怎样,还是关闭吧.我还能怎么办?感谢你们的产品,我很喜欢!

**Comment by Phoenix09** [comment]
poorly explained, but seems to be this issue: https://mega.nz/#!VhIxiCLC!wpSq9b_v7lGCPiZtt2C4XJ9gJIQna2ZdCMpGDijK53Q

**Comment by Phoenix09** [comment]
@k0shk0sh

**Comment by k0shk0sh** [comment]
Give me something that I can produce this and I'll reopen it.

**Comment by Phoenix09** [comment]
I posted a screen recording.
I can easily reproduce it.

**Comment by k0shk0sh** [comment]
Could you list down the steps?

Go to which profile, compare what to what?

**Comment by Phoenix09** [comment]
what's wrong with the screen recording?

go to any user, scroll down repos, scroll up, refresh, language for some
repos changes.


On 8 Dec 2017 16:48, "Kosh Sergani" <notifications@github.com> wrote:

Could you list down the steps?

Go to which profile, compare what to what?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/1250#issuecomment-350311882>,
or mute the thread

**Comment by k0shk0sh** [comment]
Ahaaa, now I got you 😂. Damn that's weird.

**Comment by k0shk0sh** [comment]
this is fixed :) thanks. it was due to recycling of old view.
