### ISSUE TITLE
Project view does not show issues' titles

### ISSUE THREAD

**Issue by V-ed** [k0shk0sh/FastHub#1252]
**FastHub Version: 4.5.5**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia X  
---

When inside a project, I'd expect to see the title of the issues in the cards but instead, I only see their URL.

If a card is not an issue, it displays fine (I can see the title correctly), but as mentioned, issues only show the link.

**Comment by k0shk0sh** [comment]
#1016 and more...

**Comment by V-ed** [comment]
Woops, didn't search enough through your repo to find that.

Thanks for the feedback!

**Comment by k0shk0sh** [comment]
Thank you for understanding
