### ISSUE TITLE
Slide bug

### ISSUE THREAD

**Issue by RamazanM** [k0shk0sh/FastHub#1254]
**FastHub Version: 4.5.5**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

Sometimes when I clicked a repo. Readme.md doesn't slide up. Actually slide but reslide after I released my finger.
I hope i expressed myself well. 
Have a nice day...

**Comment by k0shk0sh** [comment]
Sorry but I didn't get you, gif?

**Comment by RamazanM** [comment]
I will try take a gif
