### ISSUE TITLE
Renamed items in pull requests open in browser

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#1255]
**FastHub Version: 4.5.5**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** HTC  
- **Model:** Nexus 9  
---

There should not be a drop down in the first place and it definitely should not open the browser....

_Sent from my Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
You know the drill, a link.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/pull/808

**Comment by yakov116** [comment]
@k0shk0sh thanks
