### ISSUE TITLE
submodules

### ISSUE THREAD

**Issue by Juici** [k0shk0sh/FastHub#1256]
**FastHub Version: 4.5.5**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

Submodules look like regular files and are not sorted to the top

**Comment by k0shk0sh** [comment]
thanks for noticing out. 

however, github returns the submodule as a file type and not submodule and that's why you could see it not included in folders

**Comment by yakov116** [comment]
@k0shk0sh curious if they show it on graphql we can ask for it you know LOL

**Comment by k0shk0sh** [comment]
Sure, if you plan to do it 😎

**Comment by k0shk0sh** [comment]
Why stating the obvious? He knows and I checked and said GitHub says its a file and not a submodule. So I'm unsure what's your point?
