### ISSUE TITLE
Ability to set dark bg for code viewer

### ISSUE THREAD

**Issue by substanceof** [k0shk0sh/FastHub#1257]
Dark code highlight themes looks terrible with light app theme, so it'll be good to be able to control code viewer bg color disregard of app theme
![](https://i.imgur.com/c3FgASf.png)

**Comment by substanceof** [comment]
I'm tried to find original issue but all i found is exactly same issue that marked as duplicate without any explanation.
Can you please provide an issue number or say something concrete about this?

**Comment by k0shk0sh** [comment]
I have written in that issue the duplicated issues as well! https://github.com/k0shk0sh/FastHub/issues/925

**Comment by substanceof** [comment]
But i'm not talking about auto highlight theme switch or something. I mean ability to change code viewer's background color without changing whole app theme. For cases when user like light app theme and one of dark highlight themes or vice versa.

**Comment by k0shk0sh** [comment]
Its the same and I'm not open for customization in there.

Best thing to do is as I mentioned in these issues, someone separate the themes and I'll make them toggle themselves.
