### ISSUE TITLE
how do i unsubscribe an issue

### ISSUE THREAD

**Issue by eromoe** [k0shk0sh/FastHub#1258]
**FastHub Version: 4.5.5**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi Note2  
---

**Comment by k0shk0sh** [comment]
Currently you can only do.that from notifications, other than its not possible.
