### ISSUE TITLE
Flashing images 

### ISSUE THREAD

**Issue by BlasFerna** [k0shk0sh/FastHub#1259]
**FastHub Version: 4.5.5**  
**Android Version: 5.0 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** BLU  
- **Brand:** BLU  
- **Model:** BLU ENERGY X PLUS  
---

Flasing imagen in readme tab on the repo view.

**Comment by k0shk0sh** [comment]
Could you be more specific? What do you mean? What is the problem? And a link to the repo

**Comment by BlasFerna** [comment]
when it is a gif image the full view of the readme file flashes the repo is
https://github.com/Bogdan-Lyashenko/js-code-to-svg-flowchart

**Comment by k0shk0sh** [comment]
Can't produce what you seeing, my best bet it's device related, try to update your Android Webview, maybe that will fix it.

**Comment by k0shk0sh** [comment]
https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en

**Comment by BlasFerna** [comment]
I updated my android webview and it's still the same, maybe it's something else like a webview error? or simply the device does not give more :sweat_smile: . 
Thank you very much!
