### ISSUE TITLE
Times of Commits does not change when refreshing

### ISSUE THREAD

**Issue by INT-ZC** [k0shk0sh/FastHub#1260]
**FastHub Version: 4.5.5**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

Times of commits won't change after refresh.

**Comment by k0shk0sh** [comment]
could you please be more descriptive? 

like commits in which screen?

also the time, you talking about minutes? hours? days?
