### ISSUE TITLE
Long-press shows non-native characters for copy / cut 

### ISSUE THREAD

**Issue by zigurana** [k0shk0sh/FastHub#1262]
**FastHub Version: 4.5.5**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---
 When long pressing on a selection of text, I observe (for me) strange characters in stead of the label for 'copy', 'cut', meanwhile, the label for paste is correct. I'll try to opload a screen shot. (not possible via the app?)

**Comment by zigurana** [comment]
![screenshot_20171116-074337](https://user-images.githubusercontent.com/6103768/32877773-6515adc6-caa3-11e7-9ff8-34c265922340.png)

**Comment by k0shk0sh** [comment]
That's the matrix and you being stuck inside, noway your can exit.


For real, I can't produce this, you might have a second language on your phone? 

Could you close the app and reopen it?

**Comment by zigurana** [comment]
I had one language : 'Nederlands' (Dutch). Changed that to 'English', no difference.
Restarted the app, no effect. Rebooted phone, no effect. 
I'll try removing and installing next.

**Comment by k0shk0sh** [comment]
If I can't produce it then I can't simply do anything about it 😑


![](https://i.imgur.com/ePDPWcE.jpg)

**Comment by k0shk0sh** [comment]
I couldn't produce it, therefore i'm gonna close this as it seems more like device related.

**Comment by trollixx** [comment]
I have exactly the same problem on the same device model. So it might be device related. Another affected app is Telegram. Everything else works fine.
