### ISSUE TITLE
[feature] access and manage organization and repository projects 

### ISSUE THREAD

**Issue by Hartorn** [k0shk0sh/FastHub#1263]
**FastHub Version: 4.5.5**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5)  
---

First, your app is great!
This is not a bug, I'm actually asking for a new feature.
This would be great to access repository and organisation projects from your app.

**Comment by k0shk0sh** [comment]
Simply click on projects from Organization profile. Also you could access orgs repos.

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/yHesLNB.jpg)

**Comment by Hartorn** [comment]
OK, I'm feeling stupid now, was searching for a tab.. Nevermind.

Keep up the good work!

**Comment by k0shk0sh** [comment]
Thanks 😋
