### ISSUE TITLE
Incomplete display

### ISSUE THREAD

**Issue by urnotuname** [k0shk0sh/FastHub#1264]
**FastHub Version: 4.5.5**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3010  
---

Found this bug at wiki sidebar
-------
![](https://i.imgur.com/2p6IQlj.jpg)

**Comment by yakov116** [comment]
@urnotuname you gonna have to splain a bit more for me too understand what your saying
