### ISSUE TITLE
Can't reply to comments/reviews

### ISSUE THREAD

**Issue by srk97** [k0shk0sh/FastHub#1265]
**FastHub Version: 4.5.5**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

Got a toast message saying "Not found" when trying to reply to a comment on a PR.

**Comment by k0shk0sh** [comment]
Please provide more context to your issue.

Link

Comment or a review comment?
