### ISSUE TITLE
PR code review showing all comments in same file multiple times

### ISSUE THREAD

**Issue by droidmonkey** [k0shk0sh/FastHub#1269]
**FastHub Version: 4.5.5**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

Comments made to multiple lines in a single file are showing up buched together in FastHub. FastHub correctly shows the line that is referenced, but it lists all comments made in that file smooshed together.

![](https://i.imgur.com/VVuaxis.png)

**Comment by k0shk0sh** [comment]
Link to the pr thanks

**Comment by droidmonkey** [comment]
Sorry for the delay:

https://github.com/keepassxreboot/keepassxc/pull/1098

**Comment by yakov116** [comment]
@k0shk0sh can we have some update for this?

**Comment by droidmonkey** [comment]
I am still experiencing this in the latest update. It looks like it frequently occurs when other people make comments on the original line comments on a pr.
