### ISSUE TITLE
Back button dont work fine

### ISSUE THREAD

**Issue by giosil** [k0shk0sh/FastHub#1270]
**FastHub Version: 4.5.5**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** HUAWEI P9 lite  
---

Open a project from pinned and navigate in source files. View a source. First press back ok, second come back to pinned.

**Comment by k0shk0sh** [comment]
Could you explain more?
Like what is the expected results? I'm 100% the issue you described is working as intended but I just need confirm its either what I'm thinking or not.
