### ISSUE TITLE
Ignore issues in archived repositories

### ISSUE THREAD

**Issue by mmoayyed** [k0shk0sh/FastHub#1272]
**FastHub Version: 4.5.6**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

If I look at issues I have created over time, I see a number of them that now belong to archived repositories. I can no longer close or update issues because the repository is read only now. I suggest such issues be filtered and skipped in the issues screen.

**Comment by yakov116** [comment]
@mmoayyed link to repo?

This is probably only possible with GraphQl and we will wait another few months before attempting to switch again

**Comment by mmoayyed** [comment]
Here is the issue in an archived repo by me:
https://github.com/Jasig/umobile-app-phonegap/issues/45

Thanks for the feedback.

**Comment by k0shk0sh** [comment]
Could you elaborate on how could you archive an issue? I'm not aware of something called archive in GitHub and never heard of.

**Comment by mmoayyed** [comment]
Archiving a repository is not presently open to public, and is something made available to participants of Github's "early access program", which is somewhat private. If you get in touch with github and request access, they will more than likely get you into the program (I am not sure about the selection process).

Then you'd see this:

![image](https://user-images.githubusercontent.com/1205228/33007544-70b72786-cd8c-11e7-92ca-9d32b63414be.png)

**Comment by k0shk0sh** [comment]
Im in early program but never got an email about it lol. 

Well, if you still can see it on your profile then you should see it in here as well, I'm not sure if there is a filter for it provided by the api, I'll check later if there is one I'll add it.

**Comment by yakov116** [comment]
@k0shk0sh it was added to graphql timeline

**Comment by nmaggioni** [comment]
@k0shk0sh This still applies to PRs, the ones in archived repos are still shown in the app's main panel. [One's PRs page](https://github.com/pulls) uses the `archived:false` filter by default for example.
