### ISSUE TITLE
Navigating to repository milestones when Issues are disabled is not functional?

### ISSUE THREAD

**Issue by mmoayyed** [k0shk0sh/FastHub#1274]
**FastHub Version: 4.5.6**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

If a repository has closed/disabled its issues tab, clicking on a click from the repository's readme (or anywhere else for that matter) that would allow access to the milestones screen of the repository seems not correctly navigate there. 

Here is an example:
https://github.com/apereo/cas

You can see this repository has not enabled issues. 

In the readme however, there is a link to the "release schedule":
https://github.com/apereo/cas#development

Which is supposed to get you here:
https://github.com/apereo/cas/milestones

When I click on that link from the app, it simply *refreshes* the page and doesn't actually get me there.

**Comment by k0shk0sh** [comment]
Milestone links aren't parsed and therefore they aren't opening. But would be cool to parse them.

Thanks

**Comment by k0shk0sh** [comment]
added labels too :)
