### ISSUE TITLE
(Android Bluetooth Keyboard) Snippet Content Title unedit-able after Moving to another textbox

### ISSUE THREAD

**Issue by saterHATER** [k0shk0sh/FastHub#1275]
**FastHub Version: 4.5.6**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

When Creating a snippet with this app. I'm unable to re-edit a snippet's content title (the prompt says to enter file name and type extention). Whatever has been entered when I initially put in the filename+extension cannot be edited once I've left that textbox.

To be fair, I could see someone claiming that is a feature, and that I must re-enter my filename after backing-out of the content editing pop-up. But still, it didn't feel right.

**Comment by k0shk0sh** [comment]
Could you please list down the steps?

Is it after you saved the file? Or during creating the file?
