### ISSUE TITLE
Feature req. -- Favorite Gists

### ISSUE THREAD

**Issue by marmz** [k0shk0sh/FastHub#1278]
**FastHub Version: 4.5.6**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone 2 (ZE551ML)  
---

By now i don't see any **"favorite Gists"** tab/view.
It would be very useful and i think it should be somehow a "must", for a wide used app like this :)

Thank you for your job!

**Comment by klezm** [comment]
I have version 4.5.7 and the changelog says the feature is implemented, but I couldn't find it nowhere.
I would expect to see it as a tab in "gists" and as a tab in "profile"

**Comment by k0shk0sh** [comment]
there is pinned where it contains all your pinned stuff.

**Comment by klezm** [comment]
Its not pinned at any tab in the pinned section. But I'll have a look into that tomorrow (I double checked that I starred the gist)

**Comment by k0shk0sh** [comment]
Starred doesn't mean you pin it.

**Comment by marmz** [comment]
Well, when i said "favorites".. i meant "starred" ;)

**Comment by k0shk0sh** [comment]
But where in GitHub you can see starred gists? There is no api or even s link to it.

**Comment by klezm** [comment]
Right, pinned works, but I was also hoping for seeing started gists...

https://gist.github.com/<username>/starred

**Comment by k0shk0sh** [comment]
Ahaa,  I got you now :). 

Can you open new issue with that? 

Thanks
