### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by karyzJ** [k0shk0sh/FastHub#1279]
**FastHub Version: 4.5.6**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** TECNO  
- **Brand:** TECNO  
- **Model:** S1  
---

Before logging in, I was shown a list of errors and a directive that i should report it

**Comment by k0shk0sh** [comment]
Could you elaborate what error messages you getting?
