### ISSUE TITLE
Incorrect Python highlighting

### ISSUE THREAD

**Issue by spammy23** [k0shk0sh/FastHub#1281]
**FastHub Version: 4.5.6**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4)  
---
![](https://i.imgur.com/XyTkxrL.png)
The `in` at the end of `Player1Win` is being mistaken for the keyword `in`

**Comment by k0shk0sh** [comment]
well, I can't do much about this as its thirdparty js library. 

I'll try and update the library and see if its gonna make any different.
