### ISSUE TITLE
New version notice does not scroll down on Chromebook, everything is stuck

### ISSUE THREAD

**Issue by asitemade4u** [k0shk0sh/FastHub#1282]
**FastHub Version: 4.5.6**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** google  
- **Model:** Thinkpad 13 Chromebook  
---

I am using FastHub both from my Android phone and my Chromebook -- great!
But on the Chromebook, when there is a new version and the new version notice is displayed, there is no way to scroll down and dismiss the notice -- the OK button is at the bottom of the dialog.
I had to close the app using the taskbar and launch it again.

**Comment by k0shk0sh** [comment]
did you try to press escape? I mean I never developed the app for chromebook neither I have one myself. it might be android bug and not the app since it works perfectly on any device.

**Comment by asitemade4u** [comment]
No I did not try that. But now that Android apps are installable on Chromebooks thru Google Play, this will probably be very usual.


Stephen Sinclair ASiteMade4U On Wed, Nov 22, 2017 at 2:29pm, Kosh Sergani < notifications@github.com [notifications@github.com] > wrote:
did you try to press escape? I mean I never developed the app for chromebook neither I have one myself. it might be android bug and not the app since it works perfectly on any device.
