### ISSUE TITLE
Duplicates in trending list

### ISSUE THREAD

**Issue by remicmacs** [k0shk0sh/FastHub#1284]
**FastHub Version: 4.5.6**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus3  
---

In the trending repository list, I just noticed that I had the same repositories 3 times. Same quantity, same order.
Never happened before.
Great app by the way. I use it on a daily basis

**Comment by k0shk0sh** [comment]
is there anyway to reproduce this?

**Comment by yakov116** [comment]
@k0shk0sh I wounder if there was a github glich

**Comment by remicmacs** [comment]
Yes. I manage to double the list every time I pull to refresh

**Comment by remicmacs** [comment]
@k0shk0sh
Yes. I manage to double the list every time I pull to refresh.
No need to refresh though, I just did and noticed the list was larger that's all.

**Comment by yakov116** [comment]
@remicmacs can u please take a picture

**Comment by remicmacs** [comment]
@yakov116
Certainly.

**Comment by k0shk0sh** [comment]
You can do that, just click on image icon scroll to most right in the icons above the text box

**Comment by remicmacs** [comment]
![Top of list ](https://i.imgur.com/huOYxh6.jpg)

**Comment by remicmacs** [comment]
![Middle of list](https://i.imgur.com/fvix8X8.jpg)

**Comment by remicmacs** [comment]
Yeah works like a charm! Didn't find it right away sorry

**Comment by k0shk0sh** [comment]
could you confirm that this duplication is happening on daily, weekly or monthly ?

i'm worried, for example `daily` is selected, then you select `weekly` and maybe that lib is trending since a week and you thought its duplicate? because I couldn't reproduce what you are reporting.

**Comment by remicmacs** [comment]
@k0shk0sh
I manage to do it with the three categories daily weekly and monthly.
Each time I pull to refresh and it duplicates the whole list, in the same order.

**Comment by k0shk0sh** [comment]
Ahaaa, now I got you and can produce it 😅

**Comment by remicmacs** [comment]
@k0shk0sh
Glad I could be of some help! :wink:

**Comment by k0shk0sh** [comment]
done, thanks :)
