### ISSUE TITLE
Can’t login muti account in pro version

### ISSUE THREAD

**Issue by Shadowhack0419** [k0shk0sh/FastHub#1285]
**FastHub Version: 4.5.6**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

When I choose to login at website it automatically login with the previous account.

**Comment by k0shk0sh** [comment]
Obviously this will happen, you have to logout from chrome in GitHub in order to use different account.
