### ISSUE TITLE
Accessibility labels for the tabs at the bottom of the screen

### ISSUE THREAD

**Issue by Piciok** [k0shk0sh/FastHub#1287]
**FastHub Version: 4.5.6**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR  
- **Model:** Honor 7  
---

The accessibility labels allowing the accessibility services such as Talkback to fetch the meaning of the app's controls are missing for the tabs at the bottom of the screen. Examples of this can be seen on the main screen as well as on any screen of a repository. This affects blind users who have to resort to the “trial and error” method to deduce the function of each tab.

More information on accessibility for developers can be found under

http://g.co/androidaccessibility

**Comment by k0shk0sh** [comment]
As far as I can tell, it works fine because even if you long press their title would show up.

**Comment by Piciok** [comment]
Thanks for the tip, it definitely works this way, however, hadn't you told me, I wouldn't have guessed and I wouldn't expect many first-time users think of holding a tab to obtain the label. I think a more user-friendly approach is to have the labels exposed at all times. As I said, it's possible to figure out what they do, yet it shouldn't be too time-consuming to implement.

**Comment by k0shk0sh** [comment]
But its against Android to have labels for more than three tabs and its Android default implementation to long press menu items.

**Comment by k0shk0sh** [comment]
thanks for your feedback.

**Comment by Piciok** [comment]
Hello again,

I allowed myself to reopen the issue as I believe I could have found the solution.

You can place the Content Description tags on those tabs. Ultimately, Talkback will read them and there should be no visual track of these so all is well with the design.

You can learn more at

https://support.google.com/accessibility/android/answer/7158690?hl=en-GB, link

Hope it helps

**Comment by k0shk0sh** [comment]
content description are added :)

**Comment by Piciok** [comment]
Thanks so much. Looking forward to the next release.

**Comment by Piciok** [comment]
I have updated Fasthub to the latest Playstore release and unfortunately the labels still seem to be ignored by Talkback.

**Comment by k0shk0sh** [comment]
If you look at my committ you'll see I have added content description to the menu item. It might be a library bug
