### ISSUE TITLE
Setting to select default browser

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#1288]
**FastHub Version: 4.5.5**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

Currently, `open in browser` in menu opens a chrome custom tab, 
![](https://i.imgur.com/udpnUwp.png)
which itself has another `open in browser` option in menu.
![](https://i.imgur.com/cyo8jir.png)
It would be great to have an option to directly go to browser when selecting the first `open in browser`.
Maybe, an option in settings to select default browser, custom tabs or default browser:
Maybe in behaviour,
![](https://i.imgur.com/7LwRP3y.png)

**Comment by k0shk0sh** [comment]
thanks for your feedback but this is rather a complicated thing to do, if you don't have chrome it will open in different browser, i'm relying on that method to do that.
