### ISSUE TITLE
Not saving last page(s)

### ISSUE THREAD

**Issue by tehw0lf** [k0shk0sh/FastHub#1290]
**FastHub Version: 4.5.6**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Wileyfox  
- **Brand:** Wileyfox  
- **Model:** Storm  
---

Great app, just wondering why the <- button sends me back to the start screen (feed) instead of the last one I visited (e.g. the search I did in trending)

**Comment by k0shk0sh** [comment]
Use phone hardware button to back to where you were only use back button in toolbar to navigate up in stack
