### ISSUE TITLE
Lack of image scaling causes UI issues with large images

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#1292]
**FastHub Version: 4.5.5**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

For example issue 142 change icon in https://github.com/gsantner/markor,

What is shown in FastHub:
![](https://i.imgur.com/5r6Rq2L.png)

What is shown in github:
![](https://i.imgur.com/cVZzpyw.png)

Github seems to scale down image to fit in view, whereas FastHub shows distorted comment.

**Comment by k0shk0sh** [comment]
The problem with this is that its within a table and currently the way I render the html in separate components and therefore its hard for me to figure it is in table 🤔

**Comment by k0shk0sh** [comment]
sorry, but this wont be fixed until proper markdown support is implemented.
