### ISSUE TITLE
Language accent colors inconsistent

### ISSUE THREAD

**Issue by gruhn** [k0shk0sh/FastHub#1294]
**FastHub Version: 4.5.6**  
**Android Version: 5.0.2 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** Lenovo  
- **Brand:** MEDION  
- **Model:** MEDION E4503  
---

While browsing trending repositories I noticed that some of the programming language accent colors don't match those in the filter sidebar. Go for example is emphasized is blue but appears white in the sidebar. Most others seem to match.

![](https://i.imgur.com/NZvhjVR.png)

![](https://i.imgur.com/FES0EF2.png)

**Comment by k0shk0sh** [comment]
It means that in the menu I don't have the color and in list I could get it from GitHub
