### ISSUE TITLE
Support per file actions

### ISSUE THREAD

**Issue by Thaodan** [k0shk0sh/FastHub#1295]
**FastHub Version: 4.5.6**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

Currently there's no way to view things like commits per file.
It would be nice if it would be possible to do this.

**Comment by yakov116** [comment]
@Thaodan hold down on the file to see the commits

**Comment by Thaodan** [comment]
Oh I missed that. Is blame supported too?
