### ISSUE TITLE
Profile settings

### ISSUE THREAD

**Issue by joshuamitchellssoftware** [k0shk0sh/FastHub#1297]
**FastHub Version: 4.5.6**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** ZTE  
- **Brand:** ZTE  
- **Model:** ZTE BLade Zmax  
---

Profile picture hasn't seemed to be updated.

**Comment by yakov116** [comment]
@joshuamitchellssoftware it will update after 24 hours. It's saved in the cache.
