### ISSUE TITLE
Support <details> and <summary> tags

### ISSUE THREAD

**Issue by FloEdelmann** [k0shk0sh/FastHub#1298]
Those tags provide a standard HTML way for displaying collapsible content (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)).

It is used e.g. by the Greenkeeper bot and also useful for manually written messages to keep things like logs or larger code samples out of sight but available with one click.

On FastHub, those tags are stripped out, thus the contents are displayed bit not collapsible.

**Comment by k0shk0sh** [comment]
in comments this will never be fixed :)

**Comment by FloEdelmann** [comment]
Bummer! Can I know why?

**Comment by k0shk0sh** [comment]
Because that's not possible in Android text view.

**Comment by FloEdelmann** [comment]
And building a more complex structure with Android's view widgets is too complicated, I guess?

**Comment by k0shk0sh** [comment]
More than you imagine :) .
