### ISSUE TITLE
Themes settings showing ipsum lorem

### ISSUE THREAD

**Issue by jmagnuson** [k0shk0sh/FastHub#1299]
**FastHub Version: 4.5.6**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** Amazon  
- **Brand:** Amazon  
- **Model:** KFAUWI  
---

I have tried force quitting the app but have not yet cleared cache. I paid for the pro app.

**Comment by k0shk0sh** [comment]
These are dummy data that shows you how the theme would look like.
