### ISSUE TITLE
Authorize access to my organization

### ISSUE THREAD

**Issue by ThallyssonKlein** [k0shk0sh/FastHub#1300]
Hi there, I'm part of an organization that isn't created by me, and it's appear on my profile in Fasthub, but recently I made another, but these isn't appear there. I would like to know the url to authorize access to my organization.

**Comment by k0shk0sh** [comment]
Click on orgs from menu and then click on the (!) Icon and from there you'll see a link that shows you what's going on also, read the faq which mentions how you can do it.

**Comment by ThallyssonKlein** [comment]
I have already done this, but my account already has Fasthub authorized, I also did not find how to look in my organization settings by Fasthub to grant this permission, I would like to have the direct link. With Gitkraken the same problem happened, so I found the direct link of the application in Github (as oauth application) and there was the option to grant permission to the organization.

**Comment by ThallyssonKlein** [comment]
I got the direct link by clicking in the application name on my oauth authorized apps (my profile).

**Comment by atcharatip9035** [comment]
:smile:
