### ISSUE TITLE
kma_onchy.com

### ISSUE THREAD

**Issue by ridwanonchy** [k0shk0sh/FastHub#1303]
**FastHub Version: 4.5.6**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy J1 Ace  
---

http://karyamandirialuminium3.wordpress.com

_Dikirim dari Galaxy J1 Ace menggunakan [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Stop spamming or you'll be blocked

**Comment by SudoLinux** [comment]
Rekt
