### ISSUE TITLE
Opening from home screen kills the previous activity

### ISSUE THREAD

**Issue by Happypig375** [k0shk0sh/FastHub#1306]
**FastHub Version: 4.5.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4X  
---

Pressing the app icon on home screen kills the previous activity, while switching screens does not. I was typing out an issue on a repository and needed to check my mail. After that I pressed the app icon on the home screen then saw FastHub opening the start screen (the feed). MY ISSUE IS GONE! :angry::rage: Fix asap or I am switching to another GitHub app.

**Comment by k0shk0sh** [comment]
Obviously it's your fault and you want to blame the app for it? Why didn't you use the recent apps to go back to where you left? Threatening me to use another app won't help neither force me to do anything for you.

You are welcome to use anything you like.

**Comment by MoonCakeLover123** [comment]
Hi! thanks for this great app!
I search issues and saw this.
I also want to report.
I dont think you intend open from home screen and from recent apps is different?
Thank again for this awesome app.

@Happypig375 calm down please, angry is bad for your health :wink:

**Comment by Happypig375** [comment]
...
