### ISSUE TITLE
Not able to save file after editing 

### ISSUE THREAD

**Issue by maly72** [k0shk0sh/FastHub#1308]
**FastHub Version: 4.5.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia X Compact  
---

When I have editing a file and try to save it.
I getting an error.

**Comment by k0shk0sh** [comment]
Could you elaborate what error you getting? Also is the repo in orgs?
