### ISSUE TITLE
"Please be more specific with your search" for all searches

### ISSUE THREAD

**Issue by BrainBlasted** [k0shk0sh/FastHub#1309]
**FastHub Version: 4.5.7**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** ZTE  
- **Brand:** ZTE  
- **Model:** Z981  
---

The search function always shows this warning, even though the search completes properly.

**Comment by k0shk0sh** [comment]
Its there because people have to know that, I got few 1stars just because people thinks its app limitations while its an api limit. So that message will appear on any search not only the tab you are at :)

**Comment by yakov116** [comment]
@k0shk0sh that toast should say "Too many responses /n Showing the max API allows"

**Comment by BrainBlasted** [comment]
Agreed. It's more descriptive, as what the toast reads now can make the 
user confused as to whether their search terms were proper.
