### ISSUE TITLE
2fa not able to login

### ISSUE THREAD

**Issue by alorma** [k0shk0sh/FastHub#131]
Hi.

I have 2fa enabled on my account (using authenticator app) and i can't login to fasthub

**Comment by k0shk0sh** [comment]
Hi @alorma could you install the version that I just published? v1.1.0 and let me know how it works for you? because I had the same issue with #127  and it has been fixed.

Btw: I made this app because of https://github.com/gitskarios/Gitskarios/issues/623

Thanks man

**Comment by alorma** [comment]
:$ you used gitskarios! Awesome!, it's discontinued ;)

I'm gonna try new version, where is published?

**Comment by k0shk0sh** [comment]
I just published into the playstore and its up there, maybe you try and update the app. 

Yes, I used it and it was my fav until you made that change as described in the issue above :p 

P.S: in the new app you'll be able to click properly on issue comments links. 

If you have 1.0.6 it sucks in this, Please update and let me know.

**Comment by alorma** [comment]
Not work, i installed it from releases and can't login.

I checked the account in web signin and it woks

**Comment by k0shk0sh** [comment]
@alorma damn it, I changed the whole login process in this version tho to fix #127 . 

Do you have any idea how could this be fixed?? in the mean time you can disable 2fa to give it a shot until its fixed if you want to.

**Comment by k0shk0sh** [comment]
Could you also let me know how I enable 2fa to debug on it right away?

**Comment by alorma** [comment]
Just enable it on your security checks

**Comment by k0shk0sh** [comment]
So you set it up using which one? an app or an sms? 

This would be more to handle lol. 

I guess the fallback to this one would be to force login in the browser and receive the token.

Do you think that this is applicable for this case?

**Comment by alorma** [comment]
Ok, disabling the 2fa i can login.

I will check the app and give it a try :p (not like that animations all around, but that's me ;))

About 2fa. It's done on gitskarios, you should check for error response, and header that tells you it needs 2fa.

I not like web login, it's "out of the app".

I will check your code, could you point me to login classes?

**Comment by k0shk0sh** [comment]
you can find it in https://github.com/k0shk0sh/FastHub/tree/master/app/src/main/java/com/fastaccess/ui/modules/login

you can disable the animation from settings :p
