### ISSUE TITLE
'Starred' is supposed to be 'Stars'

### ISSUE THREAD

**Issue by azumukupoe** [k0shk0sh/FastHub#1310]
**FastHub Version: 4.5.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** docomo  
- **Model:** Xperia XZ Premium  
---

![GitHub](https://i.imgur.com/mUmR2uV.png)
![FastHub](https://i.imgur.com/2NKnsTv.png)

**Comment by k0shk0sh** [comment]
If you think about it, starred makes more sense than stars don't you agree?
