### ISSUE TITLE
[Feature request] Disable Mark Notification as read

### ISSUE THREAD

**Issue by SudoLinux** [k0shk0sh/FastHub#1311]
**FastHub-Libre Version: 4.5.5**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** HTC  
- **Brand:** Verizon  
- **Model:** Droid DNA  
---

I like integration of notifications with fasthub-libre, but my one annoyance is that I have to mark notifications as read to stop them from repeating. Please add this! Thanks

**Comment by k0shk0sh** [comment]
I'm not trying to be rude nor anything, but you should report issues in fasthub-libre. 
Thanks

**Comment by SudoLinux** [comment]
@k0shk0sh just curious than why does this app recognize this repository so well?

**Comment by yakov116** [comment]
@SudoLinux it does not. Only in the first version, he has published an update since

**Comment by k0shk0sh** [comment]
Fyi: this feature is added awhile ago and I guess that fork never merged that code :).

Nothing personal tho, I'm against that fork because it simply provides FH pro features for free just like pirated version despite the request made to the forkee to remove these features.
