### ISSUE TITLE
Putting labels on issues in my public repo 404s, every single time.

### ISSUE THREAD

**Issue by ramunecarbonated** [k0shk0sh/FastHub#1312]
**FastHub Version: 4.5.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** HMD Global  
- **Brand:** Nokia  
- **Model:** Nokia 8  
---

Whenever I try to apply a label on any of the issues I own in a repo it 404s. Names of labels vary from just letters to labels with symbols on them like "[category]:[name]".

**Comment by k0shk0sh** [comment]
Can you point me to the repo? Is it under an organization public or private?

**Comment by k0shk0sh** [comment]
I just added the label from the phone. 🤷‍♂️

**Comment by ramunecarbonated** [comment]
https://github.com/redsunservers/LoadoutBugTracker - I forgot to note it's under an organisation.

**Comment by k0shk0sh** [comment]
Awesome then the solution pretty easy,

Can you open fasthub drawer menu and click on FAQ? In there I mentioned what will you need to do.

Sorry its GitHub restrictions.

You can login with access token which will ease alot of things :)
