### ISSUE TITLE
Can't unsubscribe from thread from app

### ISSUE THREAD

**Issue by joshuamkite** [k0shk0sh/FastHub#1313]
**FastHub Version: 4.5.7**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G4  
---

I was unable to unsubscribe from a issue thread in github via the app. Clicking on link in email for the thread updates will go to an unsubscribe option via fasthub and appear to support the action but I continued to receive emails. when I visited in a web browser I saw that I was still subscribed and I was able to unsubscribe as one would expect.

**Comment by k0shk0sh** [comment]
There is no unsubscribe nor subscribe api in GitHub your best pet would be from fasthub notifications there is unsubscribe button there.
