### ISSUE TITLE
Some links open in FastHub weirdly

### ISSUE THREAD

**Issue by bghgary** [k0shk0sh/FastHub#1317]
**FastHub Version: 4.5.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

For example, search for "glTF specification 2.0". The first link for me is:
https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/KhronosGroup/glTF/tree/master/specification/2.0&ved=0ahUKEwj0iJaoqvjXAhUU2GMKHfH5A9wQFgglMAA&usg=AOvVaw0h2meHb-BpcutBDHfR6mlF

This opens with FastHub, but it opens with a single line view of a JSON:

 > [{"name":"README.md","path":"specification/2.0/README.md","sha":"db8155f39abc2c797b5d383992a6cfc224e9f4d6","size":154924,"url":"https://api.github.com/repos/KhronosGroup/glTF/contents/specification/2.0/README.md?ref=master","html_url":"https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md","git_url":"https://api.github.com/repos/KhronosGroup/glTF/git/blobs/db8155f39abc2c797b5d383992a6cfc224e9f4d6","download_url":"https://raw.githubusercontent.com/KhronosGroup/glTF/master/specification/2.0/README.md","type":"file","_links":{"self":"https://api.github.com/repos/KhronosGroup/glTF/contents/specification/2.0/README.md?ref=master","git":"https://api.github.com/repos/KhronosGroup/glTF/git/blobs/db8155f39abc2c797b5d383992a6cfc224e9f4d6","html":"https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md"}},{"name":"figures","path":"specification/2.0/figures","sha":"5d7384c282407ebe6daa61603c0ef38d0cc14af8","size":0,"url":"https://api.github.com/repos/KhronosGroup/glTF/contents/specification/2.0/figures?ref=master","html_url":"https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/figures","git_url":"https://api.github.com/repos/KhronosGroup/glTF/git/trees/5d7384c282407ebe6daa61603c0ef38d0cc14af8","download_url":null,"type":"dir","_links":{"self":"https://api.github.com/repos/KhronosGroup/glTF/contents/specification/2.0/figures?ref=master","git":"https://api.github.com/repos/KhronosGroup/glTF/git/trees/5d7384c282407ebe6daa61603c0ef38d0cc14af8","html":"https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/figures"}},{"name":"schema","path":"specification/2.0/schema","sha":"c9c26556212905c6e20d5924f33ef1d3064e694f","size":0,"url":"https://api.github.com/repos/KhronosGroup/glTF/contents/specification/2.0/schema?ref=master","html_url":"https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/schema","git_url":"https://api.github.com/repos/KhronosGroup/glTF/git/trees/c9c26556212905c6e20d5924f33ef1d3064e694f","download_url":null,"type":"dir","_links":{"self":"https://api.github.com/repos/KhronosGroup/glTF/contents/specification/2.0/schema?ref=master","git":"https://api.github.com/repos/KhronosGroup/glTF/git/trees/c9c26556212905c6e20d5924f33ef1d3064e694f","html":"https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/schema"}}]

**Comment by k0shk0sh** [comment]
Its a directory or something of sort, I'll dig more this weekend.

**Comment by k0shk0sh** [comment]
Any idea?

![](https://i.imgur.com/L9DF3Hn.jpg)

**Comment by bghgary** [comment]
I copied the link from my search results which might not work for you. Can you do the search yourself?

**Comment by Chubukov-Aleksey** [comment]
This one
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0

**Comment by k0shk0sh** [comment]
Apparently android `MimeTypeMap.getFileExtensionFromUrl(uri.toString()))` returns that it has an extension despite its not really a file `2.0` :D ..
