### ISSUE TITLE
Can't submit issues 

### ISSUE THREAD

**Issue by eliocamp** [k0shk0sh/FastHub#1324]
**FastHub Version: 4.5.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Falcon  
---

I'm not able to submit an issue to my repo. I can write title and description but then it says "Moved permanently" when I try tu submit.

**Comment by yakov116** [comment]
@eliocamp is it an organization?

**Comment by eliocamp** [comment]
Nope. It's a personal public repo: eliocamp/metR.

**Comment by yakov116** [comment]
@eliocamp link please

**Comment by eliocamp** [comment]
OK. Found the problem. Some months ago I changed the name of the repo. In FastHub I had it pinned with the old name and if I click on it it still works; I can see files, readme and even issues. But I couldn't submit a new issue.
It seems an odd behaviour, but it was user error.

Sorry for the wasted time!

**Comment by yakov116** [comment]
@eliocamp no worries. 

Glad it's working now :)
