### ISSUE TITLE
Expired Slack Invite

### ISSUE THREAD

**Issue by duke1102** [k0shk0sh/FastHub#1325]
**FastHub Version: 4.5.7 (Pro ❤)**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Fairphone  
- **Brand:** Fairphone  
- **Model:** FP2  
---

Hello,
rather unrelated to the actual app itself, but I just tried to join the Slack server using the Slack Invite the app provides and it just displays the error that the Invitation is expired.
Simple fix. :)

**Comment by k0shk0sh** [comment]
Thanks Danny, I'll look into it later.

**Comment by duke1102** [comment]
@k0shk0sh Perfekt. Should be easily fixable considering you are using a short url redirecting to Slack!

Also if may I recommend additional communication platforms to Slack, then Discord or IRC might be a good choice.

P.S. I just bought the premium features this morning!

**Comment by k0shk0sh** [comment]
done, please recheck. 

for the other platforms, I already have tried them but prefer slack because of app integrations, especially build statues and github.

**Comment by TheComputerGuy96** [comment]
@k0shk0sh Telegram has GitHub and Travis CI bots
