### ISSUE TITLE
Suyntax is not colored while editing code

### ISSUE THREAD

**Issue by maicol07** [k0shk0sh/FastHub#1326]
**FastHub Version: 4.5.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone 3 (ZE520KL)  
---

Hi,
If I edit a file, the syntax of the code is not colored, while in view mode it is coloured.
Could you check this?
Thanks

**Comment by k0shk0sh** [comment]
Unfortunately code highlighting does not work for editing files because I'm using Android edit text and  it doesn't support highlighting.

**Comment by IdiosApps** [comment]
@k0shk0sh what text view does the code viewer use? Would it be worth using that until the user taps (short/long press, not drag) the text they wish to edit, then switch to editText?

**Comment by cozyplanes** [comment]
@IdiosApps
1. Default Android textview.
2. Will make not a good user experience

**Comment by k0shk0sh** [comment]
Correction: the code viewer uses WebView while the editor edittext which inherited from TextView
