### ISSUE TITLE
[ poll ] Make some of GitHub terms translatable

### ISSUE THREAD

**Issue by kejn** [k0shk0sh/FastHub#1329]
Hi everyone!
In my recent pull request (#1322) we discussed with @dedepete if some of currently untranslatable strings should be translated. Therefore I would like to ask for your votes.

Which of below strings should be translated ?

PL (Polish):
- [x] `<string name="gists">Gists</string>`
- [x] `<string name="commits">Commits</string>`
- [x] `<string name="repos">Repositories</string>`
- [x] `<string name="starred">Starred</string>`
- [x] `<string name="code">Code</string>`
- [x] `<string name="issues">Issues</string>`
- [x] `<string name="pull_requests">Pull Requests</string>`
- [x] `<string name="star">Star</string>`
- [x] `<string name="issue">Issue</string>`
- [x] `<string name="branches">Branches</string>`
- [x] `<string name="feeds">Feeds</string>`

Please check the strings that in your opinion should be translated and leave unchecked the ones that should remain untranslated.

I looked up the translators in the closed pull requests. If I skipped anyone, please mention them in the comments so that we could reach as many of you as possible.

@alete89 @ALiangLiang @andylizi @arkon @Astro36 @azumukupoe @caiorrs @cozyplanes @Devifish @Dahnark @dikiaap @failex234 @heinrichreimer @hejsekvojtech @JediBurrell @maple3142 @mistermantas @ptt-homme @Rintan @svenhofmann99 @xDarkWolf @yakov116

@k0shk0sh - please post your final decision on this topic after we get all votes.

**Comment by ALiangLiang** [comment]
zh-rTW:
Ummmmm... In my country -- Taiwan, those most words shouldn't be translated. We are used to using the original words to communicate. Like 「幫我關掉這個 issue。」(Help me close this issue.)

**Comment by azumukupoe** [comment]
I think you can take a look at bitbucket since they've translated some of the terms.

**Comment by heinrichreimer** [comment]
- [ ] `<string name="gists">Gists</string>`
- [ ] `<string name="commits">Commits</string>`
- [ ] ` string name="repos">Repositories</string>`
- [ ] `<string name="starred">Starred</string>`
- [ ] `<string name="code">Code</string>`
- [ ] `<string name="issues">Issues</string>`
- [ ] `<string name="pull_requests">Pull Requests</string>`
- [ ] `<string name="star">Star</string>`
- [ ] `<string name="issue">Issue</string>`
- [ ] `<string name="branches">Branches</string>`
- [ ] `<string name="feeds">Feeds</string>`

I would translate none of the "official" Git/GitHub terms.
They aren't translated on any Git website including GitHub and everyone that uses Git in Germany is pretty used to the English terms.
Moreover it would confuse users if they don't see the same English terms that they are used to from the Git console or the GitHub website.
In my opinion all these terms should still be translatable but the `strings.xml` should contain a clear warning to not translate "official" terms where that would lead to misunderstandings.

**Comment by arkon** [comment]
GitHub itself isn't localised, so I'm not sure if this necessarily makes sense.

**Comment by heinrichreimer** [comment]
IMO consistency goes over localization in this case.
People would only be confused that FastHub uses another terminology than GitHub or the Git console.

**Comment by kejn** [comment]
What I meant by translating these strings, was mainly to adjust the suffixes of these strings so that they will sound more familiar. In English the plural form of a noun is created by adding either '-s' or '-es' suffix to the singular form, whereas for Polish it is more complicated. For example for English "Pull Request" in plural will be "Pull Request**s**" and in Polish the plural form could be "Pull Request**y**" (or with other suffix depending on the context).

Is that popular in other languages, too?

**Comment by heinrichreimer** [comment]
@kejn That's why I would suggest making them translateable but adding a warning/information to only use the translation for grammatical purposes such as plurals or cases.

**Comment by andylizi** [comment]
zh-rCN:
Same with @ALiangLiang.

**Comment by k0shk0sh** [comment]
I have a contribution [Link](https://github.com/k0shk0sh/FastHub/blob/development/.github/CONTRIBUTING.md#contribute-translations) guide that specifically specify 

> Don't translate Git terms. Such as pull request, push, commit, branch...

**Comment by heinrichreimer** [comment]
@k0shk0sh To be honest few people take the time and read the full contribution guidelines.
You should at least link to it from a comment in the `strings.xml` file.

**Comment by Dahnark** [comment]
They should not be translated. In my country those terms are used in english too.

**Comment by yakov116** [comment]
I think it should be left as is. The only thing that "maybe" should be changed is the 3 tabs on the bottom

**Comment by cozyplanes** [comment]
Maybe allow to edit only the plural forms, but overall, I think it is unnecessary.

**Comment by alete89** [comment]
I also think they should be left as is. Git terms translated to Spanish are both confusing and ambiguous. Also, developers most frequently use them in english even mixing them with spanish in spoken sentences.

**Comment by k0shk0sh** [comment]
Alright guys, this is settled then we will remain as we do right now, leave github references without translation, thank you all for your input.

Merry Christmas

**Comment by alete89** [comment]
Hi Guys, sorry to bother you again with this.
Even when I said before that **most** of Git terms should be left as is, I found that **some** of the
`translatable="false"` strings inside the `<!-- DO NOT COPY!  -->` tag should be translated, to match what's actually used by developers. e.g.:
`<string name="repos" translatable="false">Repositories</string>`
`<string name="starred" translatable="false">Starred</string>` (not actually a git term, but github)
`<string name="download_as_zip" translatable="false">Source code (zip)</string>` (maybe this?)

and why not: Enterprise, and Pro/ Premium features...

**Comment by k0shk0sh** [comment]
I think what you said is correct however these terms are knowen in all languages so I rather they stay untranslated. 
Thanks

**Comment by alete89** [comment]
Ok with that. What about FastHub enterprise and pro features? ->
```
<string name="pro_features_list" translatable="false"><![CDATA[Get the PRO features of FastHub which includes:\n
        • All PRO Themes\n
        • PR Reviews & On-line code comments (PRs & Commits)\n
        • Commit from FastHub (Edit, Create & Delete files)\n
        • Supports 2 more Merging methods (Rebase & Squash)\n
        • Login to unlimited accounts\n
        • Edit & Add unlimited Gist Files\n
        • Project Columns & Cards (Edit, Create & Delete)\n
        • Pin Issues, PRs & Gists\n
        • New upcoming PRO features (Coming soon...)
    ]]></string>
    <string name="enterprise_pro_description" translatable="false"><![CDATA[
            • Login to unlimited number of Enterprise & GitHub accounts\n
            • Access GitHub contents along side your Enterprise Account
    ]]></string>
```

**Comment by k0shk0sh** [comment]
Now that's hard to decide on honestly. 

But I'm fine with translating them while keeping some words as they are, for ex PRO, PR, commits etc.

**Comment by alete89** [comment]
Ok, I'll do so in Spanish. Then you check it in PR.
