### ISSUE TITLE
Unable to download private repository

### ISSUE THREAD

**Issue by PvdBerg1998** [k0shk0sh/FastHub#1330]
**FastHub Version: 4.5.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** oneplus  
- **Model:** OnePlus One  
---

I'm unable to download any private repository. Public ones work fine.

**Comment by k0shk0sh** [comment]
Unfortunately it's not possible with GitHub api.

**Comment by PvdBerg1998** [comment]
Okay, that sucks. Maybe you can disable the button on a private repo?
