### ISSUE TITLE
UI lags when viewing issue with high res images

### ISSUE THREAD

**Issue by Alexander-Wilms** [k0shk0sh/FastHub#1331]
**FastHub Version: 4.5.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G 2014  
---

Viewing this issue (https://github.com/octaviopardo/EBGaramond12/issues/9) makes the UI lag for me, which usually doesn't happen. Maybe the resolution of the screenshots causes this.

**Comment by k0shk0sh** [comment]
can't produce it, sorry!.

**Comment by skjnldsv** [comment]
I can too! :/

**Comment by Alexander-Wilms** [comment]
Reinstalled Android, now the lag doesn't occur anymore.
