### ISSUE TITLE
Back button in file explorer

### ISSUE THREAD

**Issue by Droppers** [k0shk0sh/FastHub#1332]
**FastHub Version: 4.5.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

A while ago I left a positive review, but there is one thing that annoys me

When you are in the file explorer in a directory and press the back button, instead of going back to the parent directory it goes back to the previous activity.

**Comment by k0shk0sh** [comment]
I'm aware of that, I'll make sure it'll be in tomorrow's release :)

**Comment by Droppers** [comment]
@k0shk0sh thank you!
