### ISSUE TITLE
Typo in Playstore description

### ISSUE THREAD

**Issue by stablestud** [k0shk0sh/FastHub#1334]
Hey there, 

Thanks for this awesome app!    
To contribute a tiny bit back I want to point you on an small typo in the play store description.

Just above FAQ: 

_Warning! This application may work incorrectly on discontinued CyanogenMod firmware. Since this is a bug of discontinued modified operating system, we can do nothing about it. Please, think of upgrading to **LeanegeOS**  instead of writing bad reviews._ 

Should be: **LineageOS** 

Keep up the work!

**Comment by k0shk0sh** [comment]
thanks, already modified it and it'll be updated soon.
