### ISSUE TITLE
Resize of filter window 

### ISSUE THREAD

**Issue by Fondesa** [k0shk0sh/FastHub#1335]
**FastHub Version: 4.6.0**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

The filter window, opened as a bottom sheet when the FAB in the repository section is clicked, resizes itself the first time that the button reset is clicked or an item in a spinner is selected.

**Comment by k0shk0sh** [comment]
I couldn't get what you mean, could you elaborate what's the issue and what is the expected behavior.

**Comment by Fondesa** [comment]
I added two screenshots to explain it better.
At the opening, the filter window has a certain height (screenshot number 1).
If I press **reset** or change the value of the selected item in a `Spinner`, the height is increased (screenshot number 2) and will remain fixed till I don't reopen the filter window again.
<img src="https://user-images.githubusercontent.com/13958744/34082866-cfdce206-e366-11e7-9cb7-5200b62e6483.jpg" width="300"/> <img src="https://user-images.githubusercontent.com/13958744/34082902-47edc8d2-e367-11e7-8685-b117552469e0.jpg" width="300"/>

**Comment by k0shk0sh** [comment]
Yea, that's a bottomsheetdialog, when it launches it doesn't lunch fullscreen so you have to pull it more up. 

It's working as intended tho.

Thanks
