### ISSUE TITLE
Opening issue on k0shk0sh/fasthub: model not detected

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#1336]
**FastHub Version: 4.5.5**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  
---

See above. I'm using a oneplus X

**Comment by k0shk0sh** [comment]
Its a fall back if I can't get right model or name. So its fine :).
