### ISSUE TITLE
C Syntex in not Highlighted 

### ISSUE THREAD

**Issue by swarupsro** [k0shk0sh/FastHub#1337]
**FastHub Version: 4.6.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4 Prime
---

C Syntex is not highlighting correctly! specially on comment and the closing statement of every single line.

**Comment by yakov116** [comment]
@swarupsro please please search before opening an issue.......
