### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by maicol07** [k0shk0sh/FastHub#1338]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone 3 (ZE520KL)  
---

Hi,
Some Italian translations are missing... could I translate them?
Thanks

**Comment by yakov116** [comment]
@maicol07 sure just make a pull request
