### ISSUE TITLE
Back button goes too far

### ISSUE THREAD

**Issue by lufinkey** [k0shk0sh/FastHub#1340]
**FastHub Version: 4.6.0**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

If you're on a user's profile and you select one of their repositories, hitting the back button completely closes their profile.

The preferred behavior would be that hitting the back button on the repository page (or on the device) returns you to the list of repositories that you were viewing

**Comment by k0shk0sh** [comment]
This has been discussed multiple times. Like plenty of times.

Please do read about Android navigation up and back.

**Comment by lufinkey** [comment]
"The system Back button is used to navigate, in reverse chronological order, through the history of screens the user has recently worked with. It is generally based on the temporal relationships between screens, rather than the app's hierarchy"

**Comment by k0shk0sh** [comment]
Yes, so pressing device back button should bring you where you were while pressing the toolbar back button should navigate you from issue to repo > issue tab.

**Comment by k0shk0sh** [comment]
So, use toolbar back button if you wanna navigate up and use device back btn to navigate back. 

Its simple Android navigation.

**Comment by k0shk0sh** [comment]
https://developer.android.com/design/patterns/navigation.html
