### ISSUE TITLE
Downloads won't open

### ISSUE THREAD

**Issue by brandonscholten** [k0shk0sh/FastHub#1342]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---
I downloaded a JavaScript file and I could not open it in sublime text editor

**Comment by k0shk0sh** [comment]
The file is downloaded so its out of my hands now if another app doesn't open it. You could locate the file in FastHub/repoName/ filename.
