### ISSUE TITLE
DL always fail

### ISSUE THREAD

**Issue by HeavenlyKnight** [k0shk0sh/FastHub#1344]
**FastHub Version: 4.6.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4A  
---

just thinking why everytime i download something, it always fail (on my PC, Mozilla, Chrome, DAP, IDM, and now this phone)

help me please

**Comment by k0shk0sh** [comment]
Contact GitHub on this matter. I can't help you here if everywhere you facing same issue
