### ISSUE TITLE
Change log won't completely go away

### ISSUE THREAD

**Issue by twreid** [k0shk0sh/FastHub#1345]
**FastHub Version: 4.6.0**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

After an update when I open the app and the change log appears I scroll to get rid of it and the screen stays dark and a top 1/4 inch of the change log stays in the middle of the screen.

I have only been able to get rid of that by closing the app and relaunching.

**Comment by k0shk0sh** [comment]
That's abit weird, never encountered such thing, did back button exit it? Or your phone was lagging?

**Comment by yakov116** [comment]
Something tells me that @thread did not pull UP the change log and click OK. He is trying to push it DOWN. Pull up and click ok

**Comment by twreid** [comment]
Back button didn't do anything. To get out of it I pressed the circle to go to the home screen then opened my recent apps and swiped it away. I am attaching a screenshot as well.

![screenshot_20171218-211807](https://user-images.githubusercontent.com/82234/34163532-9369f840-e49c-11e7-9773-b310dd85f789.png)

**Comment by twreid** [comment]
@yakov116 Correct I was pulling down not up and clicking ok. I will remember that next time.
