### ISSUE TITLE
Remove branding from comments for pro users.

### ISSUE THREAD

**Issue by raisedadead** [k0shk0sh/FastHub#1346]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

Hi, I noticed that branding for Fasthub is added in comments along with user's device type etc. in comments.

I think this should be removed or configured to be remove-able from the settings, at least for Pro (paid) users.

Its a deal breaker for me to comment from my mobile only to have it edit again on a desktop.

_Sent from my Moto G(4) Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by raisedadead** [comment]
Example can be seen in the Opening Post

**Comment by k0shk0sh** [comment]
Hmmm, it's disabled by default and you enabled it. So please if you don't want it , head to settings / behavior / signature and disable it.

**Comment by k0shk0sh** [comment]
P.S: it has nothing to do with pro or not. It's your choice :0

**Comment by raisedadead** [comment]
Hi, thanks for responding. I sincerely apologise for that.

Turns out, I may have accidentally turned it on while checking out features. Will be more careful in future.

In any case, wish it was more subtle, instead of giving out device details in clear or with option of editing it. 

Would have definitely used it. 

But never mind that's a different story altogether.

Thanks.
