### ISSUE TITLE
Improve behaviour at launch

### ISSUE THREAD

**Issue by arquolo** [k0shk0sh/FastHub#1350]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---
It seems for me strange that app doesn't have an option to set custom repo as home page. That would be useful for those who ain't supporting their repos yet, but creating them from scratch.
Would be nice if you could add an option to change the current behavior.

**Comment by k0shk0sh** [comment]
Thanks, but u can use pinning other than that I'm not interested in making main screen to be customizable
