### ISSUE TITLE
Notification on wear is shown

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#1353]
**FastHub-Libre Version: 4.5.5**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  
---

I have notifications disabled in fasthub, but I see a notification from fasthub "Mark notifications as read" on my moto 360.

**Comment by k0shk0sh** [comment]
Well, it works perfect from the play store and I do own a smart watch myself and can't produce what you said, if you are on the FastHub libre then you should report it there because the forkee didn't use fasthub notifications implementation.
