### ISSUE TITLE
Can't add/view images in issue comments

### ISSUE THREAD

**Issue by LoganS1** [k0shk0sh/FastHub#1354]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

I recently posted a comment with an image on github and looked at it later on Fasthub, however the image is not shown on Fasthub. It is possible to add images in comments on the github website by simply dragging and dropping the image onto the input box

**Comment by LoganS1** [comment]
Whoops, just had to wait long enough for the image to load. Hiwever, It would be nice if you could add some kind of loading feedback though..

**Comment by cozyplanes** [comment]
You use fasthub? Ha!

**Comment by LoganS1** [comment]
You wouldn't use one of the best mobile github clients?

**Comment by TheComputerGuy96** [comment]
@LoganS1 Because it doesn't support Android KitKat and below
