### ISSUE TITLE
LICENSE template suggestion

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1355]
**FastHub Version: 4.6.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

When one types LICENSE when adding files to the repo, shows a popup of the list of license templates.

**Comment by Yardanico** [comment]
Why? This is available on GitHub desktop website
