### ISSUE TITLE
Reaction button clickable area

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1356]
**FastHub Version: 4.6.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

Why should the reaction button extend all the way from the username label to the button itself?
Shouldn't the reaction button be only inside the border (marked as purple square)?
![](https://i.imgur.com/0v7Gidt.jpg)

**Comment by k0shk0sh** [comment]
Didn't get what you mean? Please ask this kind of questions in slack and I'll answer you there.
