### ISSUE TITLE
Labels don't work at all 

### ISSUE THREAD

**Issue by cyberpwnn** [k0shk0sh/FastHub#1358]
**FastHub Version: 4.6.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

I can't add labels 
I can't create labels 
(fails with red toast saying not found)

**Comment by k0shk0sh** [comment]
Meanin you are on an org repo and you have to grant access to fasthub, please read the faq from the app, or from repo readme.
