### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by toXel** [k0shk0sh/FastHub#136]
It would be really nice to have this app available in [F-Droid](https://f-droid.org).

**Comment by k0shk0sh** [comment]
I thought it is according to #15 . however if its not, I will consider releasing it today.

**Comment by toXel** [comment]
You have to add the app to F-Droid. Releasing it as APK is nice but won't show it there.

**Comment by k0shk0sh** [comment]
@toXel alright, I never published there tho, but I guess it would be aloot easier than the playstore itself. will do and once I did, I will let you know.

**Comment by toXel** [comment]
Cool! Thank you :)
Really nice app btw ;)

**Comment by xasx** [comment]
Might be as easy as a merge request at the Data repo, pick one as an example from https://gitlab.com/fdroid/fdroiddata/merge_requests

**Comment by thermatk** [comment]
Won't be that easy, there is gms in dependencies. Build flavors needed :)

**Comment by toXel** [comment]
Oh okay... so if it's too hard then just let it be. Bug fixes and new features are more important than this :)

**Comment by thermatk** [comment]
Wait, I didn't want to discourage anyone, f-droid needs this awesome app ;) I just checked whether it's really that easy, and it needs some more work

**Comment by k0shk0sh** [comment]
@thermatk you guys could always find the latest release within the release page.

**Comment by thermatk** [comment]
@k0shk0sh with binary blobs, unless the flavors cutting them out are implemented
and there exists a community of F-Droid users who wouldn't know the app exists :+1:

**Comment by toXel** [comment]
Yea a release on F-Droid would be super nice but shouldn't have a higher
priority than bugs/features, right?

**Comment by k0shk0sh** [comment]
@toXel thanks for your understanding.

**Comment by thermatk** [comment]
Now with #294 done, the only remaining thing would be to understand what to do with API keys. It's not possible to login without having one preconfigured API key? It seems that [ForkHub](https://github.com/jonan/ForkHub) doesn't have one, it uses [this library](https://github.com/eclipse/egit-github) to connect to Github, probably other APIs used there?
If there is no way, i can just put my API keys in the flavor, it's relatively easy to get them from the release apk on the playstore anyway to expect it can be dangerous :+1:

**Comment by thermatk** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2179
WIP, you can't imagine how much fun this is :rofl:

**Comment by thermatk** [comment]
Go celebrate
https://f-droid.org/wiki/page/com.fastaccess.github/lastbuild_201
Will be signed and available after the next signing session happens, they usually do it once a week

**Comment by k0shk0sh** [comment]
@thermatk thanks man :D ..

**Comment by thermatk** [comment]
https://f-droid.org/repository/browse/?fdid=com.fastaccess.github

**Comment by ildar** [comment]
No more.
https://f-droid.org/wiki/page/com.fastaccess.github
Goodbye Fasthub

**Comment by k0shk0sh** [comment]
@ildar yep, sorry about that. U guys always can download latest from here
https://raw.githubusercontent.com/k0shk0sh/FastHub/master/.github/assets/direct-apk-download.png

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ildar** [comment]
Not interested, sorry.

**Comment by k0shk0sh** [comment]
Or from @thermatk  repo https://api.github.com/repos/thermatk/FastHub-Libre/readme

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@ildar it's alright :) . Can't force you nor can force myself to complicated code base. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thermatk** [comment]
@ildar floss fork is here: https://github.com/thermatk/FastHub-Libre
For now just build it with simple gradle release(no need for api keys and whatever), I don't want to release on F-Droid until I'm sure I'll be able to maintain it, Telegram is already on me :+1:

**Comment by ildar** [comment]
Wow! 👍👍

**Comment by rugk** [comment]
What happened? Why is not it available on F-Droid anymore? What bad features were actually introduced?

@thermatk Do you were (are?) a contributor of FastHub and now (try to) maintain the libre version?

**Comment by yakov116** [comment]
@rugk the firebase part for notifications. Also some features are pro and cost money which uses Google play billing service.

**Comment by thermatk** [comment]
@rugk yes, but I'm taking a nap since 3.0.0 because of unstable tools
