### ISSUE TITLE
Click Feeds button when in same view to scroll to top

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#1360]
Sometimes when in Feeds view you end up scrolling a long way down.
I suggest clicking feeds button when in Feeds view to take you back to top of page, i.e. Instagram does this in Home view and Search view.

Currently clicking on Feeds view when in same view does nothing, nor does long click:
Click,
![](https://i.imgur.com/rfltCtW.png)
Long click,
![](https://i.imgur.com/GFh2zMh.png)

A long way down, forcing you to grab scroll bar and swing up, click button to top is faster,
![](https://i.imgur.com/kmZro19.png)

**Comment by k0shk0sh** [comment]
this implemented everywhere else but didn't thought that feeds need it because usually they are limited and also the fastscroller will do the trick, but it isn't a big of deal to do :) 

thanks

**Comment by k0shk0sh** [comment]
also, could please don't edit the default FastHub issue template? it has info that I might need.
