### ISSUE TITLE
Enable opening URLs in an external browser

### ISSUE THREAD

**Issue by doronbehar** [k0shk0sh/FastHub#1362]
**FastHub Version:**    Fasthub-Libre 4.5.5
**Android Version:**  LineageOS 14.1
**Device Information:**  
- MANUFACTURER:   HTC
- BRAND:  One
- MODEL:   m8
---

Title says it all I think, it could be great to have a setting that will enable opening links in `README`s and wikis open **externally**  in the browser.
I contacted the developers of fasthub-libre and they said I should contact upstream as well since it may concern users of the original app as well. (https://github.com/thermatk/FastHub-Libre/issues/18)

**Comment by k0shk0sh** [comment]
Hi thanks for reporting this here,

The forke has modified some of my code and therefore I can't accept any issue coming from FastHub-libra, I hope you are okay with that.

**Comment by doronbehar** [comment]
I think it could be useful for users of this version of the app as well. The modified version of the fork for sure would be able to pull small changes like this made here.
