### ISSUE TITLE
Koshosh

### ISSUE THREAD

**Issue by Gorislim13** [k0shk0sh/FastHub#1363]
**FastHub Version: 4.6.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

Where my funds

**Comment by rancidfrog** [comment]
@k0shk0sh
WtH are all these weird issues?
It seems every day at **least**  one new issue is opened with ridiculous topic or just letters

**Comment by k0shk0sh** [comment]
Ikr, idk what these people think :'(

**Comment by rancidfrog** [comment]
This one is strange, though. 🤔
I could not help but laugh.
¿Y u steal his funds?
🤑😂🤐
![](https://i.imgur.com/WLqFlAr.png)

**Comment by k0shk0sh** [comment]
He could get his refund from Google or email me to do so, I never got an email from him lol. All he has to do is providing me with the purchase idb via email and his refund should be in its way.
