### ISSUE TITLE
Pictures are not shown in mk table

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#1366]
**FastHub-Libre Version: 4.5.5**  
**Android Version: 7.1.2 (SDK: 25) Lineageos 14.2**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  X
---
https://github.com/numixproject/numix-core/pull/3997
![a](https://user-images.githubusercontent.com/22525368/34415811-ed1268f4-ebf0-11e7-82e9-49e4e38f253b.png)

**Comment by k0shk0sh** [comment]
I'm aware of that and I have a ticket opened that I'm working on revamping the md handling
