### ISSUE TITLE
FastHub cannot display GIFs correctly

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#1367]
**FastHub Version: 4.6.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

Like #1266 issue reports, I have some troubles while viewing GIFs via FastHub. Infact when I try to open a gif file from a repository I get the correct gif file overlayed with the FastHub "no media found" message
A picture is attached below.

Also, the view that allows you to see the gif is a little buggy, it doesn't support zoom. Maybe it's not relevant but I wanna report it here anyway

![](https://i.imgur.com/oqSxo4c.jpg)

_Sent from my OnePlus5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Did it finish loading? Once that gif finished loading that text will disappear, could you confirm on this

**Comment by AndreaCioccarelli** [comment]
Ok, let me check this.
Finding issues in FastHub is getting harder with time, you've done a very good work :)
