### ISSUE TITLE
Migrate horizontal progressbar somewhere else while loading README.md

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#1368]
**FastHub Version: 4.6.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

A very small but nice improvement that could be applied is a direct progressbar in the toolbar. 
It can make the view more clear, because actually while loading an heavy repository you can see both the content that's being parsed and the progressbar itself.
In SD Maid you can see this difference and it's much more clear than an isolated view.

![](https://i.imgur.com/LwwQe4M.jpg)

If you want to introduce this you have to think something new because there is no space for placing our progressbar, because we cannot attach views under a tabview. Another place can be the bottom bar, also if it's not very clear and aligned to material design style.
One last solution is moving the circular progressbar to somewhere else, like on the repository owner icon.
Let me know your impressions :D

_Sent from my OnePlus5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
The reason the progress is still showing is due to images are still loading and not the whole readme. Its to much effort for a small thing. :). 

Thanks Andrea
