### ISSUE TITLE
Default issues header update

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#1369]
Replacing the texts in favor of a table can result in a more clear general view, make data interpretation faster and keep a small header in every issue

**FastHub Version: 4.6.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

<table>
    <tr>
        <td>FastHub Version</td>
        <td><b>4.6.0</b></td>
    </tr>
    <tr>
        <td>Android Version</td>
        <td><b>7.1.1 (SDK: 25)</b></td>
    </tr>
    <tr>
        <td>Manufacturer</td>
        <td>OnePlus</td>
    </tr>
    <tr>
        <td>Brand</td>
        <td>OnePlus</td>
    </tr>
    <tr>
        <td>Model</td>
        <td>OnePlus5</td>
    </tr>
</table>

_Sent from my OnePlus5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
People alter that info and if they don't know how to work with md tables then the whole rendering going to be redundant.

Thanks for your suggestion.
