### ISSUE TITLE
Show issue title in home view

### ISSUE THREAD

**Issue by JonnyTech** [k0shk0sh/FastHub#1370]
In the home view it shows `someone commented on issue project#xxx`. Is it possible to display the issue title as well as the number?

**Comment by k0shk0sh** [comment]
It is possible "I think" but that will make the home feeds more crowded and I'm trying to avoid that.

**Comment by JonnyTech** [comment]
I understand but it will make locating relevant issues easier - maybe have it as an option and display the title in a smaller and lighter font?

**Comment by yakov116** [comment]
I don't think it will be a good idea. It will make the home screen very crowded

**Comment by cozyplanes** [comment]
Too crowded, especially in phones
