### ISSUE TITLE
Clarification on Kotlin migration

### ISSUE THREAD

**Issue by veyndan** [k0shk0sh/FastHub#1373]
**FastHub Version:**  4.6.0
**Android Version:**  7.1.2
**Device Information:**  OnePlus One
---

I'd like to convert the model classes to use Kotlin for two reasons: increased code conciseness and removal of the Project Lombok dependency, which is useless with the adoption of Kotlin. Another dependency which is useless with the adoption of Kotlin would be the Streams dependency. Would PR's be accepted for conversions of Java classes to Kotlin classes?

**Comment by k0shk0sh** [comment]
Yep, definitely, that will be great, but make sure that some class that has hashcodes and equals to be the same.
