### ISSUE TITLE
[feature request] sharing repo/wiki pages

### ISSUE THREAD

**Issue by xaota** [k0shk0sh/FastHub#1375]
**FastHub Version: 4.6.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 3  
---

please, add button for sharing wiki pages

**Comment by k0shk0sh** [comment]
trending has the share btn as well :)
