### ISSUE TITLE
When reviewing a PR, I cannot choose whether to approve

### ISSUE THREAD

**Issue by riesinger** [k0shk0sh/FastHub#1376]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G6  
---

If I open the review dialog, there seems to be a drop-down for selecting "comment" or something like approve and reject. However, clicking it does not do anything, so I cannot approve a pull request from my phone.

**Comment by k0shk0sh** [comment]
If its disabled GitHub says only allow comments.

**Comment by riesinger** [comment]
But why can't I approve PRs? Why would GitHub disable this?

**Comment by k0shk0sh** [comment]
Its not that you can't approve, check with GitHub website, if u still can approve or request changes then please let me know. 

And I can't disable it, u can create comment review. So it will remain there :).

**Comment by riesinger** [comment]
I cannot check right now, because on the mobile site you can neither comment on a review nor approve it, but I will check as soon as I can :relaxed:

I meant to only disable it visually, so it is clear that you cannot choose something different than "comment". The drop-down should still remain there

**Comment by k0shk0sh** [comment]
Wait, so you mean the drop-down is not disabled and you can choose approve?

**Comment by riesinger** [comment]
No, the drop-down *is* disabled, however it is still blue, indicating it is *not* disabled. While this is functionally correct (as you explained), the UI should represent the disabled state. This could be done by still showing the drop-down, but greying it out, which would enable you to see that you comment on a PR but cannot choose to approve or reject
