### ISSUE TITLE
Can't see organization. 

### ISSUE THREAD

**Issue by Mondei1** [k0shk0sh/FastHub#1377]
**FastHub Version: 4.6.0**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** DOOGEE  
- **Brand:** DOOGEE  
- **Model:** T6pro  
---
I'm currently in two organizations: "EpicGames" and "InstantCodee". But I only see the EpicGames organization in FastHub. I got invited into EpicGames and I created the organization InstantCodee. 

Is the reason that I created InstantCodee and not EpicGames?

**Comment by k0shk0sh** [comment]
Hi thanks, please read the faq from readme or from app menu. It will tell u what to do.

**Comment by Mondei1** [comment]
@k0shk0sh Woops, sorry.
