### ISSUE TITLE
Scroll Area Height in Code View

### ISSUE THREAD

**Issue by michalwa** [k0shk0sh/FastHub#1378]
**FastHub Version: 4.6.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG X power  
---

The height of the scroll area does not fill the screen when reading short files.

**Comment by k0shk0sh** [comment]
yeah, that's true, however it works as intended.
