### ISSUE TITLE
Crashes when trying to edit issues

### ISSUE THREAD

**Issue by azumukupoe** [k0shk0sh/FastHub#1381]
**FastHub Version: 4.6.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** docomo  
- **Model:** Xperia XZ Premium  
---

**Comment by k0shk0sh** [comment]
Cool, now I can find the bug in crash report.

**Comment by k0shk0sh** [comment]
Could you also link me to the issue

**Comment by k0shk0sh** [comment]
i couldn't reproduce it however i add a hacky way if it was the cause and it will not crash.
