### ISSUE TITLE
[Request Feature] Chat for teams

### ISSUE THREAD

**Issue by vlourme** [k0shk0sh/FastHub#1382]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P8 lite 2017  
---

Hi, just a good thing that should be cool, team discussions (I don't know if the API of GitHub propose it actually).

Thanks and happy new year!

**Comment by yakov116** [comment]
No API yet
