### ISSUE TITLE
Purchasing pro doesn't enable pro features

### ISSUE THREAD

**Issue by NoahAndrews** [k0shk0sh/FastHub#1383]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G Plus (5th Gen)  
---

My guess is that the issue may be caused by the fact that I had previously made a $2 donation. I did try the restore purchases option.

**Comment by k0shk0sh** [comment]
Probably, could you please email me at my email from my GitHub profile? And I'll assist from there. 

Please provide your purchases ids as well within the email.

**Comment by NoahAndrews** [comment]
Done.
