### ISSUE TITLE
Following is missing

### ISSUE THREAD

**Issue by mustafaozhan** [k0shk0sh/FastHub#1384]
**FastHub Version: 4.6.0**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

Hello,

Nowadays GitHub started to show our new followers on browse activity tab in GitHub webpage but It is not listed in our feed page of FastHub application.

**Comment by yakov116** [comment]
@mustafaozhan the api for feed is the OLD way of showing it. There is no way for us to grab the new way.
