### ISSUE TITLE
Profile photo is not updated

### ISSUE THREAD

**Issue by juliandavidmr** [k0shk0sh/FastHub#1385]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4)  
---

When in Github web the profile picture is changed, fasthub is not updated.

**Comment by yakov116** [comment]
@juliandavidmr restart the app...........

Please search before opening an issue
