### ISSUE TITLE
Download Unsuccessful 

### ISSUE THREAD

**Issue by BrandonMHurst** [k0shk0sh/FastHub#1387]
**FastHub Version: 4.6.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto Z Play Droid  
---

Download always fails with no explanation, simply says "download unsuccessful master.zip". No issues with wifi. Only trying downloading from my own repository.

**Comment by k0shk0sh** [comment]
if its private, then i'm sorry you can't download private repos (GitHub restrictions)

**Comment by BrandonMHurst** [comment]
Holy shit, thoroughly impressed with your response time. Didn't want to leave a bad review, figured it was my mistake and there seems to be a lot of bad reviews due to user error. Love the app, sorry that it was a known issue, just started Github integration today. 

⁣Sent from Blue ​

**Comment by k0shk0sh** [comment]
Glad I helped you and actually it was the exact issue :) .. 

Enjoy coding :D

**Comment by yakov116** [comment]
@k0shk0sh graphql......

**Comment by timmit99** [comment]
Sorry to reserect a dead thread, is there a way for me to download my OWN private repos?
