### ISSUE TITLE
Opening Label links not working properly.

### ISSUE THREAD

**Issue by rigrassm** [k0shk0sh/FastHub#1389]
**FastHub Version: 4.6.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

## Issue
When clicking a link to a label endpoint in a README, an error is thrown and you're taken to the file browser.

## Example
From the Docusaurus repo, click the"good first issues" link and notice the error. Link provided below.

https://github.com/facebook/Docusaurus/labels/good%20first%20issue

**Comment by k0shk0sh** [comment]
Oops, sorry about that. :facepalm:

Will fix it in next release.

**Comment by rigrassm** [comment]
Holy crap that was a fast response lmao.

No problem at all, not a horrible issue, just wanted to let you know.

Awesome app btw, not often that I'll spend money for premium features after
30 minutes of use!

**Comment by k0shk0sh** [comment]
@rigrassm thanks for your support. 

_Sent from my OnePlus5T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
