### ISSUE TITLE
Can't scroll down on a repo's README when my phone is in Battery Saver mode

### ISSUE THREAD

**Issue by mturley** [k0shk0sh/FastHub#1390]
**FastHub Version: 4.6.0**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

The Android battery saver mode disables animations in fasthub, and it looks like the sticky scrolling in that activity breaks without that animation.

**Comment by yakov116** [comment]
@mturley please search the issues....

**Comment by mturley** [comment]
Sorry about that!
