### ISSUE TITLE
View issues with embedded image crashes the app

### ISSUE THREAD

**Issue by ade90036** [k0shk0sh/FastHub#1392]
**FastHub Version: 4.6.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S6 Edge  
---

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/KZU2zE0.jpg)



How sure are you its because an image?

**Comment by ade90036** [comment]
😊😊, balls, not sure now since you have attached an image to this bug report. However.. this is the issue the app keeps crashing. It seems it is crashing when rendering the second post where i have images. (Jpeg + tiff). 

https://github.com/openslide/openslide/issues/222

Regards

**Comment by ade90036** [comment]
Please confirm if you can reproduce it. Thabks.

**Comment by k0shk0sh** [comment]
That image somehow causing my phone to lag like no tomorrow. Will have a look later. Thanks

**Comment by ade90036** [comment]
Cool.. great app by thr way.. 😁
