### ISSUE TITLE
Wiki access problem

### ISSUE THREAD

**Issue by Galaxy1036** [k0shk0sh/FastHub#1396]
**FastHub Version: 4.6.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR  
- **Model:** honor 6x  
---

When i try to access to the wiki of some of my private repo i get a communication error ("Erreur lors de la communication avec le serveur"). Btw there is also a translation error: should be "Erreur lors de la communiCation avec le serveur" instead of "Erreur lors de la communiSation avec le serveur"

**Comment by yakov116** [comment]
@Galaxy1036 Read the FAQ.....
You can submit a PR to have the translation changed
