### ISSUE TITLE
Disable "Premium Features" option if already purchased 

### ISSUE THREAD

**Issue by tehbasshunter** [k0shk0sh/FastHub#1399]
**FastHub Version: 4.6.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Samsung  
- **Brand:** Samsung  
- **Model:** Galaxy Note8  
---

There's still the option to support you but is it really necessary to show it if it's already been purchased?

**Comment by k0shk0sh** [comment]
its just there and you can ignore it :D. 

P.S: even those who supported FastHub before, base on their support they will get themes unlocked or pro or all.
