### ISSUE TITLE
Link in the repository description

### ISSUE THREAD

**Issue by matematikaadit** [k0shk0sh/FastHub#1401]
**FastHub Version: 4.6.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4X  
---

Sometimes, a repo put a link in their description. But FastHub didn't shows this link.

**Comment by k0shk0sh** [comment]
Could you point me to a repo that I can produce this with?

**Comment by matematikaadit** [comment]
For example:
https://github.com/rust-lang/rust/

![repo_description_with_link](https://user-images.githubusercontent.com/311326/34732218-2f866be0-f597-11e7-8f31-db5f652595f3.png)

There's link to https://www.rust-lang.org/ in rust repo description.

**Comment by dedepete** [comment]
Actually, it is not a part of the description, but another field.  
![default](https://user-images.githubusercontent.com/1936922/34918012-0e613f7e-f95e-11e7-9583-b3a6c4c4678e.png)

**Comment by matematikaadit** [comment]
Is there a particular reason this issue closed? cc @yakov116 
Or this already fixed in the master?

**Comment by matematikaadit** [comment]
While, I agree that it's technically the _website_ field in the github's UI. I think it's still useful to be added to Fasthub, and hence my feature request above is to add the website link in the project's info. Currently, the way to know the link to website of a project by copying the project URL from Fasthub to the browser. Which I think is cumbersome.
