### ISSUE TITLE
Remove pro account 

### ISSUE THREAD

**Issue by adoshem** [k0shk0sh/FastHub#1402]
**FastHub Version: 4.6.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

How do I remove my pro account?

**Comment by k0shk0sh** [comment]
Ask google for refund.

**Comment by k0shk0sh** [comment]
Test

**Comment by adoshem** [comment]
What does that mean? I want to remove my pro account and not pay for services anymore?

**Comment by k0shk0sh** [comment]
That means, contact google for refund. 
https://support.google.com/googleplay/answer/2479637?hl=en

Or email me the purchase id and I'll do it when I'm free

**Comment by adoshem** [comment]
I purchased a pro account from your company. I just want to cancel that. Is that a recurring payment?

**Comment by k0shk0sh** [comment]
Its a one time payment, if you like to refund please email me with what I asked.

P.S: its not subscription based but rather a one time purchase.
