### ISSUE TITLE
[Feature request] Starred repo

### ISSUE THREAD

**Issue by redking974** [k0shk0sh/FastHub#1403]
**FastHub Version: 4.6.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR  
- **Model:** Honor 8  
---

Hi, is it possible with FastHub to see our starred repo?
I've checked in the app but I don't found this section.

Regards

**Comment by k0shk0sh** [comment]
Click on your profile and you'll find it in the forth tab or click on ur pic from the menu and you'll find quick Link to there.


Please do explore the app, you'll be surprised with what you can do.

**Comment by redking974** [comment]
I'm sorry, didn't look right. Thanks.

**Comment by redking974** [comment]
I'm sorry, didn't look right. Thanks.

**Comment by redking974** [comment]
I'm sorry, didn't look right. Thanks.
