### ISSUE TITLE
Add team discussions

### ISSUE THREAD

**Issue by josemvidal** [k0shk0sh/FastHub#1404]
**FastHub Version: 4.6.1**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

Feature request. Add support for the new team discussions that GitHub added a couple of month ago.

**Comment by k0shk0sh** [comment]
No API yet

**Comment by k0shk0sh** [comment]
Test

**Comment by josemvidal** [comment]
API [is here now](https://developer.github.com/v3/teams/discussions/).
