### ISSUE TITLE
'My Repos' in main sidebar

### ISSUE THREAD

**Issue by JakeRunsDnD** [k0shk0sh/FastHub#1405]
**FastHub Version: 4.6.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

Hey guys, love this app! This is just a convenience/QoL request :)

Can we please get a 'My Repos' button on the main sidebar? It's annoying to have to pin all of my personal repos to be able to view them in one click from the main menu, the current fastest way without pinning is to go 'menu > my profile > swipe over a few times to repos', but it seems like it should be common enough for a one-click operation

Cheers!

Jake

**Comment by k0shk0sh** [comment]
Now there are two menus, one on the left and one on the right, on the right side basically is what you see when you click on toggle from the left menu, its accessible just like the first menu from almost everywhere.
