### ISSUE TITLE
Improper Display of Code Blocks

### ISSUE THREAD

**Issue by 95CivicSi** [k0shk0sh/FastHub#1406]
**FastHub Version: 4.6.1**  
**Android Version: 5.0 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S5  
---

When viewing issues and comments, code blocks should not wrap text to the next line automatically. Instead behaviour should mimic that of GiHub.com where the code block can be scrolled horizontally.

**Comment by k0shk0sh** [comment]
That's hard because that's impossible in Android textview.
