### ISSUE TITLE
[Feature Request] Labels

### ISSUE THREAD

**Issue by 95CivicSi** [k0shk0sh/FastHub#1407]
**FastHub Version: 4.6.1**  
**Android Version: 5.0 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S5  
---

Users should be able to modify and update labels on repos where they have permission to do so.

**Comment by k0shk0sh** [comment]
You can do all of that, please discover the app first.
