### ISSUE TITLE
[Feature Request] Assignees

### ISSUE THREAD

**Issue by 95CivicSi** [k0shk0sh/FastHub#1408]
**FastHub Version: 4.6.1**  
**Android Version: 5.0 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S5  
---

Users should be able to assign other users to issues and PRs where they have permission to do so.

**Comment by k0shk0sh** [comment]
Please discover the app.
