### ISSUE TITLE
Initial watch icon should show "not watching" 

### ISSUE THREAD

**Issue by Rainer-Lang** [k0shk0sh/FastHub#141]
Now the icon has the state "watching" even when the repo isn't watched.

**Comment by k0shk0sh** [comment]
it's the other way around, if it has a line then it should be watching and you can unwatch it.

**Comment by HeinrichReimer** [comment]
@k0shk0sh This is counter intuitive...
Here is what the icons should look for each state:
| Icon | State | Appearance |
|:-:|:-:|:-:|
| Star | Not starred | Grey, not filled |
| " | Starred | Blue, filled |
| Fork | Not forked | Grey |
| " | Forked | Blue |
| Eye | Not watching | Grey, not filled |
| " | Watching | Blue, filled |

**Comment by k0shk0sh** [comment]
the commit that closes this issue, actually has the same idea 😀

**Comment by HeinrichReimer** [comment]
You're right, sorry for misunderstanding that.
