### ISSUE TITLE
Opening issue from feed does not remove it from notifications

### ISSUE THREAD

**Issue by nixel2007** [k0shk0sh/FastHub#1411]

**Comment by nixel2007** [comment]
**FastHub Version: 4.6.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5s  
---

**Comment by yakov116** [comment]
@nixel2007 There is no way to link the 2. They use different api's and we cant change githubs server

**Comment by nixel2007** [comment]
OK, thanks.
