### ISSUE TITLE
Purchase  order design is not proper

### ISSUE THREAD

**Issue by fareed543** [k0shk0sh/FastHub#1414]
**FastHub Version: 4.6.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy J7 Neo  
---

**Comment by dedepete** [comment]
What do you mean?

**Comment by dedepete** [comment]
Seems like you are not interested in this one, so I'm closing this down.  
Feel free to reopen this Issue again if you want.
