### ISSUE TITLE
Changelog still showing issues marked as invalid

### ISSUE THREAD

**Issue by failex234** [k0shk0sh/FastHub#1416]
**FastHub Version: 4.6.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI6  
---
![](https://i.imgur.com/RTPV9Kl.png)
![](https://i.imgur.com/94IKCiA.png)

**Comment by k0shk0sh** [comment]
Its fixed :)

**Comment by dedepete** [comment]
I think this is because the changelog used within the latest version has been generated before the changes were made in the generator's configuration file.

**Comment by failex234** [comment]
Oh that's nice! Didn't notice that.
