### ISSUE TITLE
A way to commit and PR in a protected branch

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1420]
**FastHub Version: 4.6.1**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

Currently, when editting a file and committing in a protected branch, it does not allow to commit. It displays an error saying there should be at least one review by someone with write access.

There should be a way to make a PR after editting in a protected branch.

**Comment by stablestud** [comment]
Github does not allow direct pushing to nor editing in a protected branch, every change need to be merged with a pull  request.

**Comment by cozyplanes** [comment]
May I ask y?

**Comment by cozyplanes** [comment]
So I meant is there a way by you to allow to create PR with this? In the web, you can do that
Edit file --> Set new branch name --> Click propose file change green button --> Write PR details --> Open PR

**Comment by stablestud** [comment]
@cozyplanes The protected branch option is used to prevent accidentally committing to a e.g production branch which plays a key-role in some programs and shouldn't be changed without proper testing etc.    
Hope that explains it ;)

**Comment by stablestud** [comment]
Fasthub can't create new branches as it would be too extensive to implement. See #280

**Comment by caffeinatedMike** [comment]
@stablestud It actually isn't as extensive to implement as you & @k0shk0sh think. I've included a simple walkthrough of how to implement it in the original issue (#280) that posed the initial request for this feature.
