### ISSUE TITLE
[Feature Request] Insight tab

### ISSUE THREAD

**Issue by stablestud** [k0shk0sh/FastHub#1422]
This is an excellent app, really glad I found it on F-Droid. Thank you for this!

Is it possible that we may get the Insight tab for our own repos? Like viewing the Traffic, Contributors and so on.    
Thats the only thing I'm missing.

**Comment by k0shk0sh** [comment]
Thanks for your suggestion.

**Comment by cozyplanes** [comment]
He doesn't have plans to implement
