### ISSUE TITLE
Profile picture cached

### ISSUE THREAD

**Issue by quaeler** [k0shk0sh/FastHub#1423]
**FastHub Version: 4.6.1**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

Profile pic has changed since I first started using app. App will not pick up new photo. Tried logging out and logging back in - oauth.

**Comment by k0shk0sh** [comment]
That's weird, caching is cleared upon logout and profile image shall change upon reoping the app. 

![](https://i.imgur.com/hOYgxAc.jpg)

![](https://i.imgur.com/GiJNbag.jpg)

**Comment by quaeler** [comment]
Force quitting the app and restarting it, after logging out and logging back in, did then clear the cache. I'll take it - thanks.
