### ISSUE TITLE
no money

### ISSUE THREAD

**Issue by OlafxD** [k0shk0sh/FastHub#1424]
**FastHub Version: 4.6.1**  
**Android Version: 5.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** HTC  
- **Brand:** htc  
- **Model:** Desire 628 dual sim  
---

can i get promo code for free please?

**Comment by dedepete** [comment]
Please, look through the FAQ.

**Comment by cozyplanes** [comment]
Promo ended.
