### ISSUE TITLE
Having the latest issues in which there was an update. 

### ISSUE THREAD

**Issue by Angelk90** [k0shk0sh/FastHub#1425]
@k0shk0sh: Hello, it would be possible to have the last issues in which there was an update in which you are participating.

**Comment by yakov116** [comment]
@Angelk90 please open all issues via the app

**Comment by k0shk0sh** [comment]
Could you elaborate please

**Comment by Angelk90** [comment]
@k0shk0sh : 
Let me explain better, many times I happen to create a question or comment on a question created by another user.
Even if my account is connected, oddly sometimes I do not get the email.
What I propose as new features, where there are the tabs: create, partecipated, etc ..
To add the following call:
`is:issue author:Username sort:updated-desc 
`
This call takes all the questions created by the author, ordered by the last in which there was an answer.

I could not find the command indicating the same thing, but instead of being created, it should be in which the user participated.

![request](https://user-images.githubusercontent.com/20476002/35095535-11cbdd0c-fc49-11e7-8f8e-15883ed1b8c1.png)

**Comment by k0shk0sh** [comment]
This exists in the main screen my pulls & my issues, other than that there is also search issues or pr per repo and general search you could use.

**Comment by Angelk90** [comment]
@k0shk0sh : 
Forgive me, I'm in the main issues, but I do not find anything that allows me to see for example that the last issues in which I participated (of which I am the author in this case) and there was an update, that is a new comment, is just this, for example.

I have also tried in the tab, partecipated of issues, but the result is different from the one I offer you through that sort of query.

**Comment by k0shk0sh** [comment]
In this case you can write this query in the search screen and it will be saved so you can check them everytime also created tab should show the issues which you are the author for. 

![](https://i.imgur.com/t6MCrHJ.jpg)
