### ISSUE TITLE
Missing slash when sharing wiki link

### ISSUE THREAD

**Issue by The-Compiler** [k0shk0sh/FastHub#1426]
**FastHub Version: 4.6.1**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HMD Global  
- **Brand:** Nokia  
- **Model:** Nokia 8  
---

Sharing https://github.com/ParticleCore/Particle/wiki/Home shares a link with a missing slash: https://github.comParticleCore/Particle/wiki/Home

**Comment by k0shk0sh** [comment]
Its fixed :)
