### ISSUE TITLE
Turkish Translation title wrong on app language menu

### ISSUE THREAD

**Issue by TurboProgramming** [k0shk0sh/FastHub#1430]
**FastHub Version: 4.6.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8+  
---

In the app language menu, Turkish translations are named "Türk". The word is used to describe Turkish people, not the language. The language is called "Turkish".

In Google Translate it's written "Türk" but it's wrong. I've seen this issue in other projects too, please fix.

**Comment by TurboProgramming** [comment]
?

**Comment by TurboProgramming** [comment]
@k0shk0sh ?

**Comment by k0shk0sh** [comment]
There is no need to tag. 

You could open a PR with that fix else I'll do it when I have free time

Thanks

**Comment by TurboProgramming** [comment]
@k0shk0sh OK, opening a new one now.
