### ISSUE TITLE
Unable to upgrade to pro

### ISSUE THREAD

**Issue by samliew** [k0shk0sh/FastHub#1433]
**FastHub Version: 4.6.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

The app crashes when clicking on the link to select the upgrade type.

**Comment by k0shk0sh** [comment]
You don't have Playservice installed i assume?

**Comment by samliew** [comment]
I do have it (Global set), and can install apps via the play store. Funny thing is I can make in-app purchases in other apps but this is the first which crashed.

**Comment by k0shk0sh** [comment]
Does it crash Everytime or u only tried once?

**Comment by samliew** [comment]
A couple of times. I'll try with another device later, if I can't repro it then I'll just close this off

**Comment by k0shk0sh** [comment]
All crashes are coming from Xiaomi
![](https://i.imgur.com/y8HCBsn.jpg)
