### ISSUE TITLE
Redirect to default viewer for filetypes automatically

### ISSUE THREAD

**Issue by iamsubhranil** [k0shk0sh/FastHub#1435]
**FastHub Version: 4.6.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Wingtech  
- **Brand:** Xiaomi  
- **Model:** HM 2LTE-IN  
---

Now PDF doesn't automatically open, and docx opens in unreadable text mode. Wouldn't it be better if the file could be downloaded automatically when an user clicked on it (preferably followed by an information dialogue) that "fasthub doesn't support opening this type of file in place. Would you like to download it and open it with the default viewer for this type?" And when the user clicks yes, fasthub will download the file and feed it to the default reader? This could be done for all file types that fasthub doesn't support.

**Comment by k0shk0sh** [comment]
Its impossible for me to determine all kinda of files that the app can support and can't and therefore its open like that with an option to download it. 

You could simply head to MarkdownProvider.java and add the file extensions there within the Archive list and the app will ignore them :). a PR will be good tho.

**Comment by k0shk0sh** [comment]
this has been fixed by adding some new file types.
