### ISSUE TITLE
Update message gets stuck

### ISSUE THREAD

**Issue by okb1100** [k0shk0sh/FastHub#1440]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G5  
---

![Screenshot](https://image.ibb.co/dhFCrw/Capture_2018_01_20_20_58_26.png)

- I've updated the app
- Started it and closed the dialog
- Then the dialog appeared again and I couldn't close it and had to restart the app.

**Comment by k0shk0sh** [comment]
That's weird, never got a complaint about it. Is it the first time?

**Comment by okb1100** [comment]
Yes, It's the first time I encountered the issue.
