### ISSUE TITLE
Upload Files

### ISSUE THREAD

**Issue by JuKu** [k0shk0sh/FastHub#1441]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5) Plus  
---

Is there a opportunity to upload (commit) Files?

**Comment by k0shk0sh** [comment]
Commits work however uploading is not. There is a ticket that is similar

**Comment by JuKu** [comment]
Yes, but so i cannot commit files...
Where is this issue?

**Comment by yakov116** [comment]
@JuKu search and you shall find
