### ISSUE TITLE
Unable to comment

### ISSUE THREAD

**Issue by vinyasns** [k0shk0sh/FastHub#1442]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5) Plus  
---

Unable to comment on a commit.

**Comment by k0shk0sh** [comment]
Commit url? I just commented and it works fine in a commit

**Comment by vinyasns** [comment]
Comment on a commit of repository under a organisation. I've owner right in that organisation

**Comment by k0shk0sh** [comment]
Hmmm, did u grant access to fasthub??

Please read the FAQ from the app or readme and after you follow it let me know if it still doesn't work by reopening this.

**Comment by vinyasns** [comment]
My bad. Working fine after granting permission :)
