### ISSUE TITLE
Switching between branches causes crash

### ISSUE THREAD

**Issue by danielkrupinski** [k0shk0sh/FastHub#1443]
**FastHub Version: 4.6.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G4c  
---

When I try to switch branches, app crashes.

**Comment by k0shk0sh** [comment]
Link to repo!!

**Comment by danielkrupinski** [comment]
For example: https://github.com/danielkrupinski/FastHub

**Comment by k0shk0sh** [comment]
Nope, it doesn't crash either in files or commits.

**Comment by danielkrupinski** [comment]
On my phone app crashes

**Comment by k0shk0sh** [comment]
Well apparently I can't find the crash in fabric either so I'm not so sure how would I fix something I can't produce nor get a crash report.

Could you use developer tools to get me a crash stack? Otherwise I really can't help 😪
![](https://i.imgur.com/xqJXIQ3.jpg)

**Comment by danielkrupinski** [comment]
I sent a crash report.

**Comment by k0shk0sh** [comment]
What happened daniel?

**Comment by k0shk0sh** [comment]
I haven't look at the crash yet tho

**Comment by danielkrupinski** [comment]
Closed by accident. Reopen.

**Comment by cozyplanes** [comment]
works fine in lg g4 here

Seems like a phone specific issue

**Comment by danielkrupinski** [comment]
On android 7.0 works fine. Closing
