### ISSUE TITLE
Adding labels to issues not working

### ISSUE THREAD

**Issue by Derkades** [k0shk0sh/FastHub#1444]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)** (LineageOS)  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** 2  
---
When trying to add labels to an issue I get a "Not Found" toast message then a webview opens with the issue

**Comment by k0shk0sh** [comment]
Link to repo?

**Comment by k0shk0sh** [comment]
I labeled this issue with FastHub 🤔

**Comment by Derkades** [comment]
It's this issue: https://github.com/NamelessMC/Nameless/issues/954

**Comment by k0shk0sh** [comment]
Please read the faq regards organization.

**Comment by Derkades** [comment]
Oh I see, thanks.
