### ISSUE TITLE
Kotlin port

### ISSUE THREAD

**Issue by danielkrupinski** [k0shk0sh/FastHub#1452]
**FastHub Version: 4.6.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G4c  
---

Have you thought about porting FastHub to Kotlin? That would be nice :smiley:

**Comment by k0shk0sh** [comment]
newly added modules are in kotlin, however it will take sometime to fully port it to Kotlin considering the amount of issues opened. 
a PR is welcome tho :) . 

If this answers your question, please do close the ticket, Thanks

**Comment by danielkrupinski** [comment]
Thanks for the answer :grinning:
