### ISSUE TITLE
"Too many responses"

### ISSUE THREAD

**Issue by hulkish** [k0shk0sh/FastHub#1454]
**FastHub Version: 4.6.2**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

Every search yields this error message: https://i.imgur.com/H4B6R5M.png

Is there a place i can enter my personal access token into the app to bypass this?

**Comment by k0shk0sh** [comment]
Login with access Token but that won't change a thing I guess.

**Comment by hulkish** [comment]
@k0shk0sh Tried that, same thing.

**Comment by k0shk0sh** [comment]
Then nothing we can do about it

**Comment by hulkish** [comment]
What exactly is the error reporting? The limits of GitHub api?

**Comment by k0shk0sh** [comment]
https://developer.github.com/v3/search/#rate-limit
