### ISSUE TITLE
Unable to view organizations created by user

### ISSUE THREAD

**Issue by rushilsrivastava** [k0shk0sh/FastHub#1455]
**FastHub Version:  4.6.2**
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

I can view organizations that I am added to, but not organizations that I have created myself.

**Comment by k0shk0sh** [comment]
Please read the FAQ it has almost any question covered there. Alternatively search issuing is another way of finding a solution quicker than me labeling this duplicated & close it which eventually will result in people being angry. 

I hope u are not one 😂

**Comment by rushilsrivastava** [comment]
@k0shk0sh FastHub is already authorized.

**Comment by rushilsrivastava** [comment]
It keeps saying "Can't connect to server"

**Comment by yakov116** [comment]
@rushilsrivastava how w you connected? Token or oauth?

**Comment by rushilsrivastava** [comment]
@yakov116 Connected with oauth. On my other account I am connected with Token. Bought are facing issues.

**Comment by rushilsrivastava** [comment]
@k0shk0sh I fixed the issue. I just revoked access from GitHub, and reinstalled the App. Seems to be working now.
