### ISSUE TITLE
"Create new repo" option

### ISSUE THREAD

**Issue by danielkrupinski** [k0shk0sh/FastHub#1456]
**FastHub Version: 4.6.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G4c  
---

Is there an option to create new repo? I can't find this.

**Comment by yakov116** [comment]
@danielkrupinski no there is not. Please see #484.

Thanks for your feedback
