### ISSUE TITLE
Multiple devices Log-in failing

### ISSUE THREAD

**Issue by Rool-IO** [k0shk0sh/FastHub#146]
- First log in (to a 2FA enabled GitHub account) on any device is successful.

- First log in on other devices to the same account won't succeed. (The "error" message displayed is about the 2FA otp needed even though correct ones are typed in each time.)

- Logging out from FastHub on first device works but logging in again on this device -and on other ones, still- doesn't.

- Revoking access to FastHub makes logging in from any device working again but still only on one.

**Comment by k0shk0sh** [comment]
@alorma , any ideas on this? according to my last commit, I did actually added `Build.MODEL`. to the token & finger print however @ROOI-IO still can't login with multiple devices.

**Comment by alorma** [comment]
I will check as soon as i go home

**Comment by k0shk0sh** [comment]
@alorma alright Thanks man & sorry for bothering you :) .

**Comment by k0shk0sh** [comment]
@alorma can we actually use the authToken (note) as the fingerprint as well? as this will eliminate at least the fingerprint of being duplicated.

**Comment by alorma** [comment]
But, i used a UUID for fingerprint :s

**Comment by k0shk0sh** [comment]
@alorma , any news on this, as I seem like I can't figure it out nor test it out.

**Comment by alorma** [comment]
Not yet, i coulnd't try yesterday, sorry :P

I will try today, sure

**Comment by k0shk0sh** [comment]
@alorma cool, thanks again, couldn't done without you :)

**Comment by k0shk0sh** [comment]
This issue is fixed now & verified by @Rool-IO .

 @alorma  thanks for your help tho I've followed your login and everything works fine now.
