### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by Henry2o1o** [k0shk0sh/FastHub#1463]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MIX  

How can I pay the premium?

**Comment by k0shk0sh** [comment]
Via Google in app purchases

**Comment by Henry2o1o** [comment]
![photo_2018-01-29_11-55-22](https://user-images.githubusercontent.com/6131799/35506960-7626c0f0-04eb-11e8-93ac-1a9956f077e8.jpg)
![photo_2018-01-29_11-55-23](https://user-images.githubusercontent.com/6131799/35506962-77ef6694-04eb-11e8-98c9-3bd9ecf64473.jpg)

**I can buy other apps.**

**Comment by k0shk0sh** [comment]
Where did u get the app from?

**Comment by Henry2o1o** [comment]
![grafik](https://user-images.githubusercontent.com/6131799/35511904-132bfa8e-04fe-11e8-9119-855a5c01a37d.png)

**Comment by k0shk0sh** [comment]
Can u uninstall and install again from playstore?

**Comment by Henry2o1o** [comment]
Hat worked, weird.
Did the Pro paid, but nothing has changed.
No themes, etc?
