### ISSUE TITLE
Free FastHub premium promo code

### ISSUE THREAD

**Issue by sirkadirov** [k0shk0sh/FastHub#1465]
**FastHub Version: 4.6.2**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** LENOVO  
- **Brand:** Lenovo  
- **Model:** K5 Plus  
---

I wrote a short article about FastHub: https://sirkadirov.com/fasthub-android-application/ (it is in russian)

Can you please give me a free promo? Thanks.

About app: All works really great :relaxed:

**Comment by k0shk0sh** [comment]
hey, thanks for the article, I'm sorry but this promo has already ended months ago. 
really sorry for your effort.

**Comment by dedepete** [comment]
@k0shk0sh this promo was over, but none of the translations have been updated to these changes, except the English one.  
We should take this fact into account.

**Comment by sirkadirov** [comment]
Hmm... Ok, but I will not delete this article :wink:

**Comment by yakov116** [comment]
@k0shk0sh for that alone he should get it :) lol

**Comment by alete89** [comment]
End of promo code included in spanish translation
