### ISSUE TITLE
Feature request: Open Jupyter notebooks via nbviewer by default

### ISSUE THREAD

**Issue by thesemicolonguy** [k0shk0sh/FastHub#1466]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

Since Jupyter notebooks don't open on phone, they should be opened on the app by default via nbviewer.jupyter.org

**Comment by k0shk0sh** [comment]
#1221 #1069  #1132
