### ISSUE TITLE
Forked repos

### ISSUE THREAD

**Issue by alexdecamillo** [k0shk0sh/FastHub#1469]
**FastHub Version: 4.6.2**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

I don't see my forked repos on my list of repos. Is this intended?

**Comment by yakov116** [comment]
@alexdecamillo Org?

**Comment by dedepete** [comment]
@alexdecamillo I closing this Issue since the stated question hasn't been answered for a long time. Feel free to reopen.
