### ISSUE TITLE
Does not understand .diff and .patch urls from emails, but regustered as open with program

### ISSUE THREAD

**Issue by Xiazee** [k0shk0sh/FastHub#1470]
**FastHub Version: 4.6.2**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia Z2  
---

**Comment by yakov116** [comment]
@Xiazee this has nothing to do with the app. Google is your friend or contact github support

**Comment by Xiazee** [comment]
@yakov116 updated the description with details. I think you might have misundeestood the issue.

**Comment by k0shk0sh** [comment]
@Xiazee thats true, so far I haven't find the best way to do this and it isn't in my of todos however I should be able to open it in a chrome tab. I'll do this in the coming weekend.

Thanks
