### ISSUE TITLE
Sort Repositories

### ISSUE THREAD

**Issue by DaStinkingScaliwag** [k0shk0sh/FastHub#1471]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG K20 V  
---

Add an option that also allows repositories to be sorted alphabetically or chronologically, or either in reverse. Have this preferance save, so one doesn't have to change it every time. I'm tired of scrolling to the bottom of a list of 30 repos.

**Comment by yakov116** [comment]
@DaStinkingScaliwag um there is.....

![](https://i.imgur.com/ztZpbva.png)

**Comment by DaStinkingScaliwag** [comment]
For me, filter is the only option available.

**Comment by DaStinkingScaliwag** [comment]
![Screenshot](https://photos.app.goo.gl/wr6fwGswlC2SvdvM2)

**Comment by DaStinkingScaliwag** [comment]
I do see "Type" as well, but no sort

**Comment by yakov116** [comment]
@DaStinkingScaliwag screenshot?

**Comment by DaStinkingScaliwag** [comment]
I posted a new issue, because I am unable to post any image on this app.

**Comment by yakov116** [comment]
@DaStinkingScaliwag Because?

**Comment by DaStinkingScaliwag** [comment]
"Error requesting server, please try again later"

**Comment by yakov116** [comment]
@DaStinkingScaliwag looks like your have some kind of issue with your phone

**Comment by DaStinkingScaliwag** [comment]
I am able to see my images fine through the selector. However after I select my screenshot, it raises the error. That doesn't sound like a phone problem to me.

**Comment by DaStinkingScaliwag** [comment]
![](https://i.imgur.com/16UI0wO.png)

**Comment by DaStinkingScaliwag** [comment]
Well heck i guess it was

**Comment by DaStinkingScaliwag** [comment]
![](https://i.imgur.com/bpOoU6H.png)

**Comment by DaStinkingScaliwag** [comment]
Thats all i see

**Comment by k0shk0sh** [comment]
For orgs that's the only filter we have sent nothing else.

**Comment by yakov116** [comment]
@k0shk0sh due to the api correct?

**Comment by DaStinkingScaliwag** [comment]
@k0shk0sh ^

**Comment by k0shk0sh** [comment]
Yes, of course
