### ISSUE TITLE
Automatically open organization page when "organizations" pressed, if only a member of one organization

### ISSUE THREAD

**Issue by DaStinkingScaliwag** [k0shk0sh/FastHub#1472]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG K20 V  
---

Sorry that this is such a lazy request, but I'd appreciate it.

**Comment by k0shk0sh** [comment]
Could you elaborate?

**Comment by DaStinkingScaliwag** [comment]
![](https://i.imgur.com/dLW6xBH.png)

**Comment by DaStinkingScaliwag** [comment]
When i press organizations...

**Comment by DaStinkingScaliwag** [comment]
I want it to bring me to my ONLY organization, instead of here ![](https://i.imgur.com/tR0FUpU.png)

**Comment by k0shk0sh** [comment]
But I can't know how many orgs do you have until this displayed and an api call is made.

**Comment by DaStinkingScaliwag** [comment]
Oh well

**Comment by k0shk0sh** [comment]
Thanks for your understanding
