### ISSUE TITLE
Unable to Reply  or Post New Issues with Images

### ISSUE THREAD

**Issue by DaStinkingScaliwag** [k0shk0sh/FastHub#1473]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG K20 V  
---

In attempting to present more information on another issue, I found I am completely unable to insert any image via the "Select" option into a comment or post. The error is "Error requesting server, please try again later". Yes, I do have internet connection.

**Comment by yakov116** [comment]
@DaStinkingScaliwag I have no issue. How are you trying to do it?

**Comment by DaStinkingScaliwag** [comment]
@yakov116 I click the Image icon, then select, then I gave FastHub permission to access my photos, then I selected a screenshot. It then raised an error.
