### ISSUE TITLE
Can't access branch's commits

### ISSUE THREAD

**Issue by EmmanuelMess** [k0shk0sh/FastHub#1478]
**FastHub Version: 4.6.2**    
**Android Version: 6.0**  
**Device Information:**  
- MANUFACTURER: Motorola
- BRAND: Motorola
- MODEL: Moto E Gen 2 4G 
---
You are here:
<img height="350px" src="https://user-images.githubusercontent.com/10991116/35651281-eb24df6c-06bd-11e8-9119-82d89c9ec588.png"/>
How do I access the commits in the branch?

**Comment by yakov116** [comment]
@Emmanuel![](https://i.imgur.com/zboU1hK.png) click on the branch name

**Comment by EmmanuelMess** [comment]
I don't want to change branch, I want to see the branch's commits.

**Comment by DaStinkingScaliwag** [comment]
Works for me... Dev Branch ![](https://i.imgur.com/ZwH3Ini.png) Master branch ![](https://i.imgur.com/me7tpEV.png)

**Comment by DaStinkingScaliwag** [comment]
![](https://i.imgur.com/2W1kOHB.png)

**Comment by EmmanuelMess** [comment]
To replicate please go to [this](https://github.com/TeamAmaze/AmazeFileManager/tree/google_plus) link.
Screenshot of what happens when I press on the branch:
<img height="350" src="https://user-images.githubusercontent.com/10991116/35661574-e9249430-06f1-11e8-908a-64e03585db69.png"/>

**Comment by yakov116** [comment]
@EmmanuelMess so what is the issue?

**Comment by EmmanuelMess** [comment]
How do I access the branch's commit

**Comment by k0shk0sh** [comment]
You have to be in repo page to see commits other than that long click the file and you'll see its commit history.

**Comment by EmmanuelMess** [comment]
Is there a good reason for not having a way to access commits directly?

**Comment by k0shk0sh** [comment]
Commits exits in the repo screen, click the arrow key in the toolbar and you'll be directed back to the repo, also as I said, long press the file and you'll see its commit history.

**Comment by EmmanuelMess** [comment]
"back" goes to the last screen (in this case a commit or PR), you are saying I have to track down the repo, then access the branch to see it's commits?
