### ISSUE TITLE
wanna to stay in the original page

### ISSUE THREAD

**Issue by GARENFEATHER** [k0shk0sh/FastHub#1479]
**FastHub Version: 4.6.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Meizu  
- **Brand:** Meizu  
- **Model:** PRO 6  
---

I found that everytime I come back to the default page of fasthub after I temporarily switch to my home page.

 Actually I think it will be appreciated that I could just stay where I was before switching:smiley:

**Comment by k0shk0sh** [comment]
Well it is not my fault that your phone has memory issues and kills apps in the background.

**Comment by GARENFEATHER** [comment]
@k0shk0sh really? Most apps on my phone dont have this problem, they stay where they should be. Im sure that I never set a global memory issue and it will not be killed when I switch just for a while

**Comment by GARENFEATHER** [comment]
@k0shk0sh and there is another topic, I found that the slack link is invalid now? I failed to get the invitation
