### ISSUE TITLE
Cannot edit cards even when premium 

### ISSUE THREAD

**Issue by lucasmelin** [k0shk0sh/FastHub#1480]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5)  
---

I've purchased the premium version of FastHub, and although I can see project boards and cards, when I try to edit one, I get redirected to the purchase page. Clicking on the Restore Purchase button notifies me that the purchase is verified, but I still can't edit any cards, even after force-closing the app.

**Comment by k0shk0sh** [comment]
Thanks for opening this, I'll check it later :)

**Comment by k0shk0sh** [comment]
Hello Lucas, are you still having this issue? 

Could you try to reinstall the app?

**Comment by lucasmelin** [comment]
Tried uninstalling and reinstalling. After the 2nd time, seems to have resolved the issue. Thanks.
