### ISSUE TITLE
home feed list can show project description info just like github web index page

### ISSUE THREAD

**Issue by maoruibin** [k0shk0sh/FastHub#1482]
**FastHub Version: 4.6.2**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI6  
---

like title

**Comment by maoruibin** [comment]
maybe  jsoup will be a choise, just parse page desciption.

**Comment by k0shk0sh** [comment]
No this isn't a choice for me to do, its to much of a work to do ;)
