### ISSUE TITLE
Why this app has premium features?

### ISSUE THREAD

**Issue by danielkrupinski** [k0shk0sh/FastHub#1484]
Why did you put premium features in an open source app? If you wanted to profit you could make app paid and closed source.:confused:

**Comment by k0shk0sh** [comment]
Its open source and I assume people respect open source project :) .

**Comment by danielkrupinski** [comment]
Can I make a fork, remove in-app purchase and make pr? :grinning:

**Comment by k0shk0sh** [comment]
Yea, go ahead and I'll reject it ;). 

What is your point exactly?

**Comment by dedepete** [comment]
I hope this will answer the stated question.  
![default](https://user-images.githubusercontent.com/1936922/35770940-f9183dd8-0935-11e8-9be3-d1380ccc823e.png)

**Comment by danielkrupinski** [comment]
Said black Google worker :smiley:

**Comment by k0shk0sh** [comment]
Why the rasicim statement? Could you pls behave?
