### ISSUE TITLE
Downloaded zip file renamed and missing file extention

### ISSUE THREAD

**Issue by azumukupoe** [k0shk0sh/FastHub#1486]
**FastHub Version: 4.6.2**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** docomo  
- **Model:** Xperia XZ Premium  
---

File name is modified when downloaded from FastHub. It may be causing downloaded files to lose file extention.

**Comment by k0shk0sh** [comment]
Care to show some examples with links as well?

**Comment by azumukupoe** [comment]
@k0shk0sh
Tried with FastHub's source code.

**Comment by k0shk0sh** [comment]
I also tried and everything works fine, can you please be more specific? 

Just provide me something I can produce otherwise I can't do nothing!

**Comment by azumukupoe** [comment]
[Video](https://drive.google.com/file/d/1IISXM64dHoowLC3TjjVyU-kkD9xZHxgT/view?usp=drivesdk)

**Comment by k0shk0sh** [comment]
See, I was looking at file download and not source download ;). I'll look into it later. Thanks

**Comment by dedepete** [comment]
GitHub's API does not provide archives' extensions.  
![default](https://user-images.githubusercontent.com/1936922/35816620-32b7c4b0-0aac-11e8-875d-fa56e0284949.png)

**Comment by cozyplanes** [comment]
Maybe adding `tar.gz ` to the end when it is tarball? (Stupid hack)

**Comment by cozyplanes** [comment]
@k0shk0sh It works fine here. Even though the downloaded archive name doesn't have .zip, it opens well

**Comment by cozyplanes** [comment]
Only happens when it is tar.gz
.zip works fine
