### ISSUE TITLE
some suggestions 

### ISSUE THREAD

**Issue by pollen5** [k0shk0sh/FastHub#1487]
**FastHub Version: 4.6.2**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** Y5  
---
Just some suggestions to improve the app, can you please add a full screen mode or something when editing file when i rotate my phone with keyboard and those things it blocks my way to write anything would be nice to have some options to disable some things and full screen mode.

**Comment by freetnt5852** [comment]
Btw there's a bug too where if you edit a file and commit then open again after the changes didn't refresh in the file. This gets really annoying after i commit then i edit something else i mess up my previous commit.

**Comment by k0shk0sh** [comment]
@freetnt5852 its due to GitHub caching the responses :). I faced this last time and there were no ways to solve it.

**Comment by dedepete** [comment]
@k0shk0sh I think, caching the updated files locally could resolve the problem.

**Comment by ravener** [comment]
Just cleaning up my GitHub issues and stuff, it's been 2 years and i don't think this issue has any need to stay open.
