### ISSUE TITLE
App chrashes when adding new Note/issue to project column

### ISSUE THREAD

**Issue by inhji** [k0shk0sh/FastHub#1488]
**FastHub Version: 4.6.2**  
**Android Version: 6.0.1 (SDK: 23)**  (LineageOS)
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR-7  
- **Model:** HONOR PLK-L01  
---

The app crashes when clicking on the "+"-Button in a project column.

Thanks for making FastHub! :blush:

**Comment by k0shk0sh** [comment]
Bitteschön :), i'll look for it later. 

Danke
