### ISSUE TITLE
Ability to Create Repos & Upload files

### ISSUE THREAD

**Issue by Darshan10298** [k0shk0sh/FastHub#1489]
**FastHub Version: 4.6.1**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

The Title says it all :)
Great App btw :D

**Comment by k0shk0sh** [comment]
thanks :)

**Comment by k0shk0sh** [comment]
#1456 #1117  and so many

**Comment by Darshan10298** [comment]
Whoops 😛
I didn't knew I'm creatin a Duplicate..
Any plans for adding the Features?

**Comment by Darshan10298** [comment]
Whoops 😛
I didn't knew I'm creatin a Duplicate..
Any plans for adding the Features?

**Comment by cozyplanes** [comment]
@ItzNotABug He doesn't unfortunately
