### ISSUE TITLE
No feedback in successfully posting comment

### ISSUE THREAD

**Issue by hex007** [k0shk0sh/FastHub#1492]
**FastHub Version: 4.6.2**  
---

After successfully posting a comment the comment list should scroll down to show the last comment. This provides a feedback to the user that the comment has been posted.

**Comment by k0shk0sh** [comment]
This is hard to do as if I scrolled down and there were any pages to load I have to load them all and then append the newly added comment.

**Comment by hex007** [comment]
How about a message stating that the comment was posted successfully ?
