### ISSUE TITLE
404 not found when merging PR

### ISSUE THREAD

**Issue by The-Compiler** [k0shk0sh/FastHub#1494]
**FastHub Version: 4.6.2**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HMD Global  
- **Brand:** Nokia  
- **Model:** Nokia 8  
---

I tried to merge https://github.com/pytest-dev/pytest/pull/3192 from FastHub - but when I do, I get a "404 not found" error toast.

**Comment by k0shk0sh** [comment]
Please grant FastHub access to the org or login with access token.
