### ISSUE TITLE
Profile images are loaded when images are disabled

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#1495]
**FastHub-Libre Version: 4.6.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  X
---

I have disabled loading images on mobile, but profile images are still loaded. This causes massive trafic, when viewing all issues of a repo.

**Comment by k0shk0sh** [comment]
Loading images in comments.

**Comment by mueller-ma** [comment]
Yes, loading images in comments is disabled, when the option is enabled. But profile pictures are still loaded. Wouldnt it be useful to disable loading of all images?

**Comment by k0shk0sh** [comment]
Nope :). These images are pretty small in size and cached anyway ;)

**Comment by mueller-ma** [comment]
How large is one average picture?

**Comment by k0shk0sh** [comment]
Below 15kb or 10
