### ISSUE TITLE
"Cross referenced" message is misleading

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#1496]
**FastHub-Libre Version: 4.6.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  
---

Lets say you have repo A and B.
When you reference A#10 in B#20. Open A#10 in the app, the message says "user cross referenced this in issue #20 1 day ago". But its B#20, not A#20.

For an example see openhab/openhab-android#685 and the cross reference to openhab/openhab-cloud#160

**Comment by Dev-iL** [comment]
Related issue: The app always says "referenced in **issue**", even when in reality the reference was in a **PR**.

**Comment by k0shk0sh** [comment]
I can't differentiate between the two as there is noway in the api that tells that.

**Comment by Dev-iL** [comment]
suggestion: change the text to "issue/PR"?

**Comment by k0shk0sh** [comment]
Better would be referenced in #0

**Comment by Dev-iL** [comment]
sure, that works too :)

**Comment by yakov116** [comment]
Graph QL LOL

**Comment by mueller-ma** [comment]
I'm not sure why this issue is closed. The message does not contain the repo name, if the issue/pr is referenced to a different repo.

**Comment by yakov116** [comment]
@mueller-ma if the api would give it........
