### ISSUE TITLE
Purchasing pro doesn't enable pro features

### ISSUE THREAD

**Issue by giohappy** [k0shk0sh/FastHub#1498]
Same as in #1383. I've purchased the PRO but I can't find any difference with the free versions.

**Comment by yakov116** [comment]
@giohappy Can you add multiple accounts? Can you try to use the "Squash and merge"? Also please open all issue via the app

**Comment by giohappy** [comment]
@yakov116 nope. If I click "Add content" the login page is shown again and again.
I can't find any button / menu to create, review, merge PRs, nor columns and cards...
Where should all these features be located?

**Comment by yakov116** [comment]
@giohappy ?! When you add an account does it prompt you to pay?

**Comment by giohappy** [comment]
@yakov116 I've already purchased! Now if I click it asks to login. I do it, it logs in, then if I click again it asks to logain again, endlessly.
Refund is not available but please give me a private contact to ask for it...

**Comment by giohappy** [comment]
I've recorded a screencast to demonstrate it: https://drive.google.com/file/d/1LFdw2kfn8c9MyPiVH1HUnArkY9exqCr9/view?usp=drivesdk

**Comment by yakov116** [comment]
@giohappy do you have chrome installed on your device?

**Comment by k0shk0sh** [comment]
Of course it will show again and again as you clicking on add account, also when u click on browser, your previous login credentials is saved in ur browser and therefore u have to go to ur chrome, logout first before doing what you doing with fasthub login.

**Comment by giohappy** [comment]
It happens also with basic auth.
PR management, columns and cards, etc. are not available.
You closed it before receiving my feedback...

**Comment by k0shk0sh** [comment]
You showed us a video of the issue which you had and I thought that was it all. 

When you click basic auth it opens fine meaning it works you just have to use different account to add new account. 


Also, I had suggest to reinstall the app to confirm that everything isn't working as you said.

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/eOiheOF.jpg)

**Comment by giohappy** [comment]
Add account seems to work after reinstall.
I have a different UI then your screenshot. I can't filter by labels or milestones. I can set then for single issue though...

Can you list what are the PRO features that I should have now?

**Comment by k0shk0sh** [comment]
The screen where you purchase the pro has a list of all the things, go to themes/click on purchase pro and then you'll see the list overthere.

That screen isn't something pro, click on a repo/issues tab and then click on the fab and click search ;)

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/l9XXyah.jpg)

**Comment by giohappy** [comment]
@k0shk0sh thanks, I think I'm starting to find the PRO functionalities (e.g. edit files, assign labels and milestones). I will test PR merge and project carda ASAP.
