### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [k0shk0sh/FastHub#15]
Being open-source, would you consider publishing the `.apk` file for each release along with the `releases/` – for other open-source minded people who can't or won't use Playstore? Thanks in advance!

**Comment by k0shk0sh** [comment]
Hello There, sure so!. Please find the apk in the release page under 1.0.3 version.

**Comment by IzzySoft** [comment]
That was fast – thanks a lot! For other "playstore abstinents", I've just added it to my F-Droid compatible repo (see [here](https://apt.izzysoft.de/fdroid/index/apk/com.fastaccess.github)), so they can use the F-Droid client to install your app and keep it updated. New versions are usually available within 24h of your attaching the `.apk` to the corresponding release. My way of contributing :innocent:

**Comment by k0shk0sh** [comment]
Thanks for your contribution 👍

**Comment by IzzySoft** [comment]
Anytime! :blush:
