### ISSUE TITLE
Error toast is shown, when commenting an issue, but comment is successfully posted

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#1501]
**FastHub-Libre Version: 4.6.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  X
---

Since the last update I see the error toast "Error occured while communicating to the server" every time I post a comment on an issue or PR, however the comment is successfully posted.

**Comment by k0shk0sh** [comment]
Please update your app.

**Comment by mueller-ma** [comment]
Thanks for fixing. Well I don't use play store, so I have to wait for the foss fork :(

**Comment by mueller-ma** [comment]
Sure, I should have searched for that issue first. Sorry
