### ISSUE TITLE
Why cant see my followers new following people . 

### ISSUE THREAD

**Issue by ramazan** [k0shk0sh/FastHub#1512]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** General Mobile  
- **Brand:** gm  
- **Model:** GM5 Plus d  
---

Hey.

ı wanna show my following people's starting following people

Why cant see anymore?

**Comment by yakov116** [comment]
@ramazan What!?

**Comment by k0shk0sh** [comment]
If something was there and it disappear then GitHub has dropped that event and I can't do anything to it :).
