### ISSUE TITLE
Wrong url when sharing wiki

### ISSUE THREAD

**Issue by azumukupoe** [k0shk0sh/FastHub#1517]
**FastHub Version: 4.6.2**  
**APK Source: Unknown**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** docomo  
- **Model:** Xperia XZ Premium  
---

- becomes a space when shared
please try

**Comment by dedepete** [comment]
Please, provide a link to the affected repo.

_Sent from my P2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by azumukupoe** [comment]
@dedepete
https://github.com/TilesOrganization/support/wiki/How-to-use-ADB-to-grant-permissions
