### ISSUE TITLE
Show the stats of language used when the language label is long pressed

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1518]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

There is a stats (percentage) showing the language used in the project in github web.

Mayhe fetch from that, or is there an api?

Would love to see it.

**Comment by k0shk0sh** [comment]
it would be awesome to check if there is an API that has such data before posting new issues, since you actively opening issues that gets closed :'( . 

I didn't create GitHub API so therefore help from the community to determine such things would be really really really really appreciated.

**Comment by cozyplanes** [comment]
@k0shk0sh I am in my phone most of the time.... Sorry...

This GRAPHQL API looks promising...
https://developer.github.com/v3/repos/#list-languages

**Comment by k0shk0sh** [comment]
Sorry but I'm not interested to implement this, I don't see what value could it add :).

**Comment by cozyplanes** [comment]
Hey maybe list the languages used
