### ISSUE TITLE
Disable issues button in forked repo

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1524]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

How to reproduce:
- fork a repo
- see bottom tab
- notice issues icon is enabled
- click it
- `issue disabled for this repo`
- issues button gets disabled

How about disabling from the first time?

**Comment by k0shk0sh** [comment]
its intended behaviour, it doesn't mean you knew the app very well then everybody else should know it, if I disable it by default people will never know whats going on.
