### ISSUE TITLE
Unauthorized user toast at FIRST startup

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1525]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

If it is obvious that the user shoild log in, why do you show an `unauthorized user`

**Comment by k0shk0sh** [comment]
Its not obvious as you state :), its design to be that way :)
