### ISSUE TITLE
Button hint errors

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1526]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---
Emoji btn
![](https://i.imgur.com/2a38PdV.png) 

Gist 3rd btn~5th btn
![](https://i.imgur.com/PWNB1xH.png)

Search btn in repo files viewer
![](https://i.imgur.com/Wqjc0p5.png)

**Comment by cozyplanes** [comment]
`hintception`

**Comment by anna64000** [comment]
O my good
