### ISSUE TITLE
Clicking profile from followers and following shows 2 loading circles.

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1528]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

Looks cool though...

**Comment by k0shk0sh** [comment]
Its due to the animation but its only one progressbar :)
