### ISSUE TITLE
Profile image

### ISSUE THREAD

**Issue by Herman-me** [k0shk0sh/FastHub#1529]
**FastHub Version: 4.6.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG K10 LTE  
---
hey
i have a problem with my profile image .
it dosent show my profile image and shows the defult profile picture
i dont know why !

**Comment by k0shk0sh** [comment]
for everyone: 

GITHUB doesn't change the Profile image URL therefore the previous cached image will always load because there are no differences or more like there is no way I could know if the image changed. 

Simple solution: Added a setting button to clear image caches.
