### ISSUE TITLE
Divider between Swift and 1C Enterprise in trending

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1530]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

![](https://i.imgur.com/uke7C3R.png)

**Comment by k0shk0sh** [comment]
Could you please make a more quality issues next time?
