### ISSUE TITLE
Long press a language to pin in the top in trending side menu

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1531]
**FastHub Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

Languages such as C# (my fav) isn't in the top. Maybe add a long press to pin in the top in the feature

**Comment by k0shk0sh** [comment]
use search :)

**Comment by cozyplanes** [comment]
too lazy to click the 
1. search bar
2. c
3. symbols btn
4. # 

lol
