### ISSUE TITLE
Fast hub doesn't update profile image

### ISSUE THREAD

**Issue by sicrs** [k0shk0sh/FastHub#1533]
**FastHub Version: 4.6.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

Recently I changed my profile picture, and Fast hub doesn't seem to update it, even after I've logged in

**Comment by yakov116** [comment]
@sicrs please search before opening an issue 

Thanks for your feedback
