### ISSUE TITLE
On Back press and offline mode issue

### ISSUE THREAD

**Issue by Hardyverma** [k0shk0sh/FastHub#1534]
**FastHub Version: 4.6.2**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note4  
---

First of all i really appreciate your work guys. I  started using fasthub couple of weeks ago there are so issue/bugs which i notice which really effect UX like When in Pinned tab after opening any of the Pinned project if Back button is pressed or click on navigate up arrow it will just navigate Back to the main Activity instead of navigating back to Pinned projects list. Which is kind of irritating Some Times when you have a huge list of Pinned project
Second is there should be some good support for offline Most of the time offline mode don't even work

Thank you

Anyway Keep up the Good work guys

**Comment by k0shk0sh** [comment]
Hey thanks for the issue, however its user fault than the app, do not use the toolbar back icon because it navigate deep on the stack, use the phone back button and you'll return where you were.


Thanks
