### ISSUE TITLE
Purchase PRO features, and also try purchases 'all', no unlock features

### ISSUE THREAD

**Issue by Probot9** [k0shk0sh/FastHub#1538]
**FastHub Version: 4.6.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

Purchase PRO feature, nothing happen, did not unlock any feature.

Also, tried purchase 'all' features, nothing happen neither, no features have been unlocked.

Please fix these asap.

**Comment by yakov116** [comment]
>Purchase PRO feature, nothing happen, did not unlock any feature.
>
>Also, tried purchase 'all' features, nothing happen neither, no features have been unlocked.
>
>Please fix these asap.

What feature did not unlock?

**Comment by Probot9** [comment]
Checked Theme feature, no change after purchase.

**Comment by k0shk0sh** [comment]
Can you try reinstall the app?

**Comment by Probot9** [comment]
I did, no change.

On Feb 19, 2018 01:03, "Kosh Sergani" <notifications@github.com> wrote:

Can you try reinstall the app?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/1538#issuecomment-366604172>,
or mute the thread

**Comment by yakov116** [comment]
@Probot9  can you take a picture of the right side bar?

**Comment by Probot9** [comment]
The right side bar remain unchanged after purchase. When I tried restore
purchase, it seen to restored the purchase. After that, however, it still
does not allow theme change, and remain asking to go Premium. I tried to
click Purchase again, now it did not show the purchase dialog box.

Tried uninstalled and restart the phone, no change.

After trying all these, I decided to ask Google for the refunds. If you
help determine the problem and provide a fix, I would make the purchase
again.

Thanks.

On Feb 19, 2018 13:09, "yakov116" <notifications@github.com> wrote:

@Probot9 <https://github.com/probot9> can you take a picture of the right
side bar?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/1538#issuecomment-366780318>,
or mute the thread
