### ISSUE TITLE
Size of repository is wrong

### ISSUE THREAD

**Issue by iamsubhranil** [k0shk0sh/FastHub#1539]
**FastHub Version: 4.6.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Wingtech  
- **Brand:** Xiaomi  
- **Model:** HM 2LTE-IN  
---

- It happens all the time. The size of the repository stays wrong, or doesn't update after each commit.![](https://i.imgur.com/jS7vHM6.png)

**Comment by yakov116** [comment]
@iamsubhranil I'm assuming it's an api issue but will wait for @k0shk0sh to chime in 

Thanks for your time feedback

**Comment by k0shk0sh** [comment]
well, it works fine, if GitHub gave me wrong size then I can't do anything about it :)
