### ISSUE TITLE
Copy raw direct link without having to leave app

### ISSUE THREAD

**Issue by NightdayLabs** [k0shk0sh/FastHub#154]
Wrote this in an review on the Play Store but were asked to submit an issue here so here we go!

It would be great if you were able to copy the raw direct links to images in a repo without having to leave the app. As of now you need to open up the image in the app and then press the button to open in browser and after that copy the link. Tried the file share option but that only opens up the GitHub page with the image.

Of course, this doesn't only apply to images but also other types of files.To copy a raw link, it requires that the user exits the app.

Best regards.

**Comment by k0shk0sh** [comment]
Thanks for submitting the issue here. 
I will look into and reference the issue once its fixed so you be notified.

**Comment by kutsan** [comment]
@k0shk0sh What do you think about this? I guess, long press to open a ContextMenu with "Copy link" option would be nice. Even, you can add share option to there.

**Comment by Rainer-Lang** [comment]
I would prefer a "share" button.

**Comment by k0shk0sh** [comment]
@kutsan @Rainer-Lang , I guess a share button will be better as rainer suggested, its due to the fact that the image is loading in a webview. so long press gonna be troublesome.

**Comment by kutsan** [comment]
@kosh What you gonna do about other hyper links? Like normal ones.

**Comment by k0shk0sh** [comment]
@kutsan these are selectable if you long press on them, Android framework handle this be default it will show you copy and other stuff.

**Comment by k0shk0sh** [comment]
@kutsan well in a second thought, if the title is not showing (has a title) then this wont work, only test will be copied. I'll have to look into this.
