### ISSUE TITLE
Text "Pro" wears out

### ISSUE THREAD

**Issue by Toshimichi0915** [k0shk0sh/FastHub#1540]
**FastHub Version: 4.6.3**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** MATE 9  
---

![](https://i.imgur.com/IK5boWX.jpg)

**Comment by k0shk0sh** [comment]
I think its a screen density issue

![](https://i.imgur.com/vRoxFm4.jpg)

**Comment by yakov116** [comment]
@k0shk0sh I have the same issue

**Comment by k0shk0sh** [comment]
Owh yeah thanks
