### ISSUE TITLE
Unable to select/upload files with Android file picker

### ISSUE THREAD

**Issue by dragon788** [k0shk0sh/FastHub#1545]
**FastHub Version: 4.6.3**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

I was really hoping to be able to quickly upload some photos and edit the markdown on a site I maintain from my phone, but it appears binary files aren't supported yet?

**Comment by cozyplanes** [comment]
What site is it? How can you edit MD from fasthub if you maintain other site? If you need to find a way to upload binary files, find some MD editor in the internet, not beg for a binary upload to the developer of this app. It is not needed.

**Comment by dragon788** [comment]
I'm uploading the files to GitHub because the site is GitHub Pages hosted and I don't need a fancy markdown editor, I just need to be able to upload files like I can through GitHub's web interface. My understanding was the developer wants to have feature parity with GitHub and this is a gap currently.

**Comment by cozyplanes** [comment]
Do you mean `Upload files` in the main repo page?
Unfortunately, GitHub doesn't provide an api for that currently.
