### ISSUE TITLE
Feature request: View PR deployments

### ISSUE THREAD

**Issue by FloEdelmann** [k0shk0sh/FastHub#1547]
Continuous deployment services like Heroku allow review apps that are deployed automatically in open pull requests (see the [Heroku docs](https://devcenter.heroku.com/articles/github-integration-review-apps)). They add a link to the deployed site (*View deployment*) in the corresponding PR:

![screenshot_2018-02-22_14-26-42](https://user-images.githubusercontent.com/202916/36541091-14a5fb70-17dd-11e8-9b31-0bdff31f3f7b.png)

*Note: This screenshot is taken from <https://github.com/FloEdelmann/open-fixture-library/pull/416>, if you need a live example.*

In FastHub, this link is not visible, which makes finding the deployment much harder. It would be nice if it could be added, possibly via GitHub's [Deployment API](https://developer.github.com/v3/repos/deployments/).

**Comment by k0shk0sh** [comment]
The text is blue for a reason :). Click it. 


![](https://i.imgur.com/vT1sQES.jpg)

**Comment by FloEdelmann** [comment]
I'm not talking about the continuous integration (Travis and Codacy), but the continuous deployment (Heroku). The blue commit hashes take me to the respective commit (as expected).

**Comment by k0shk0sh** [comment]
Cool, so what's the problem?

**Comment by FloEdelmann** [comment]
The link to the deployment (https://open-fixture-library-pr-416.herokuapp.com, *View deployment*) is not visible in FastHub, although it is part of the PR web UI.

**Comment by k0shk0sh** [comment]
```
{
        "id": 1472153940,
        "url": "https://api.github.com/repos/FloEdelmann/open-fixture-library/issues/events/1472153940",
        "actor": {
            "login": "FloEdelmann",
            "id": 202916,
            "avatar_url": "https://avatars1.githubusercontent.com/u/202916?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/FloEdelmann",
            "html_url": "https://github.com/FloEdelmann",
            "followers_url": "https://api.github.com/users/FloEdelmann/followers",
            "following_url": "https://api.github.com/users/FloEdelmann/following{/other_user}",
            "gists_url": "https://api.github.com/users/FloEdelmann/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/FloEdelmann/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FloEdelmann/subscriptions",
            "organizations_url": "https://api.github.com/users/FloEdelmann/orgs",
            "repos_url": "https://api.github.com/users/FloEdelmann/repos",
            "events_url": "https://api.github.com/users/FloEdelmann/events{/privacy}",
            "received_events_url": "https://api.github.com/users/FloEdelmann/received_events",
            "type": "User",
            "site_admin": false
        },
        "event": "deployed",
        "commit_id": null,
        "commit_url": null,
        "created_at": "2018-02-13T17:35:15Z"
    }
```

Now I only show deployed and nothing else tho. not even clickable :)

**Comment by FloEdelmann** [comment]
Sad to see that the deployment URL is not reported by the API. But at least a bit more information than before. Thanks!
