### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Janrupf** [k0shk0sh/FastHub#1548]
**FastHub Version: 4.6.3**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
**Manufacturer:** samsung  
**Brand:** samsung  
**Model:** Galaxy J5  
---

Just a little translation bug:

If a pull request cant be merged it says in the german translation:
"Dieser PR kann jetztjetzt nicht zusammengeführt werden"

Should be:
"Diese PR kann jetzt nicht zusammengeführt werden"

**Comment by yakov116** [comment]
@Janrupf You can create a PR

**Comment by k0shk0sh** [comment]
Entschuldigung, ich nitch spreche deutsch that well yet so I can't really review each pr well. 

You can open a pr fixing that bug tho :)

**Comment by Janrupf** [comment]
ok, I'm going to do this when I have time and not only my mobile :smile:

(Leaving this open for remebering myself ;))
