### ISSUE TITLE
Option where to separate drawer to two or merge to one as previous versions

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1551]
**FastHub Version: 4.6.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

**Comment by dikiaap** [comment]
👍. It's so hard now to reach home button on the top left corner.

**Comment by cozyplanes** [comment]
yeah... and the right drawer bugs me out as well.

**Comment by k0shk0sh** [comment]
I think the new drawer gonna stay for awhile 🤷‍♂️

**Comment by cozyplanes** [comment]
:disappointed:
