### ISSUE TITLE
Feature Request: Simple commit file list

### ISSUE THREAD

**Issue by michalwa** [k0shk0sh/FastHub#1552]
**FastHub Version: 4.6.3**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG X power  
---

Just a suggestion.
When there's a lot of files in a commit, it would be more convinient to view the list without the "Addition, Deletion, Change, ..." at the bottom of each item. There should be an option in the settings for that.

**Comment by k0shk0sh** [comment]
Thanks but I don't want to complicate things more than they are.
