### ISSUE TITLE
GitHub is going to deprecate anonymous Gist creation.

### ISSUE THREAD

**Issue by dedepete** [k0shk0sh/FastHub#1553]
According to their blog [post](https://github.com/blog/2503-deprecation-notice-removing-anonymous-gist-creation), this feature will be removed on **March 19, 2018 19:00 UTC (11:00 am PST)**.  
I think, such functionality of FastHub should be removed as well by this date.

**Comment by k0shk0sh** [comment]
**deprecate** && **remove** are totally different things, which one is going to happen?

**Comment by dedepete** [comment]
They will disable anonymous gist creation via the web and API.

_Отправлено с моего P2 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
