### ISSUE TITLE
Access private repo

### ISSUE THREAD

**Issue by unnamedsid** [k0shk0sh/FastHub#1555]
**FastHub Version: 4.6.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto E (4)  
---

I am not able to access my private repo and it's not showing anywhere

**Comment by arpitjindal97** [comment]
FAQ
> 
> Why can't I see my Organizations either Private or Public ones?
> 
> Open up https://github.com/settings/applications and look for FastHub, open it then scroll to Organization access and click on Grant Button,
