### ISSUE TITLE
Tab Swiping Issue

### ISSUE THREAD

**Issue by ItzNotABug** [k0shk0sh/FastHub#1557]
**FastHub Version: 4.6.3**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

Whenever I try to See a part of the Code written on ReadMe.md by swiping/sliding, instead the ReadMe.md tab slides to Files...
gets really annoying after trying again & again...

**Comment by k0shk0sh** [comment]
You are the first ever to complian about this, because it works fine.

Could you please give me an example repo/readme that I could produce what you mentioned?

**Comment by ItzNotABug** [comment]
@k0shk0sh
Steps to Reproduce:

1) Go to any Repo which includes a ReadMe.md & has Code examples like how to use library etc...

2) As the part of the Code is not Wrap Content, you have to swipe the Code area to see more...

3) As you swipe that code area, the ReadMe TAB slides to Files TAB
This is the Problem :)

**Comment by cozyplanes** [comment]
@ItzNotABug I think it is working as intended. You should put your finger in the code box for about a second, and drag to the left, then you can see it. You are dragging it too fast, which means you are swiping
