### ISSUE TITLE
Cannot pin more than one gist

### ISSUE THREAD

**Issue by danielkrupinski** [k0shk0sh/FastHub#1558]
**FastHub Version: 4.6.3**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G4c  
---

As title says.

**Comment by dedepete** [comment]
Can confirm this Issue. Any other Gist is shown as pinned even if it's not.
