### ISSUE TITLE
cannot sent comment to dev branch

### ISSUE THREAD

**Issue by BoBBer446** [k0shk0sh/FastHub#1559]
**FastHub Version: 4.6.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab A 10.1  
---

hey, i try to edit a repo im admin.
there two branches.
- master
- dev

i change to dev and see the dev brunch. so i edit a file and commit. but if i save file the master brunch becomes the commit.

btw
is it possible to select a main brunch for the client? at the moment i have to switch to dev brunch everytime

thank you for your great work!

**Comment by yakov116** [comment]
@BoBBer446 I think there is an issue open for the above.

I will double check

Thanks for your feedback

**Comment by BoBBer446** [comment]
I have something to thank you for.

I just tried commiting a file to the dev brunch.

I choose the repo
then the brunch - dev
then I create a file and save it
but the file also appears in the master brunch.
https://github.com/shoujii/NeXt-Server/tree/master

the file "test.txt" i have created in dev brunch but is see in the master bruch

**Comment by yakov116** [comment]
@BoBBer446 That is the exact issue as #1239

**Comment by BoBBer446** [comment]
ahh, yes! im so sorry for that! i hope you find the issue ! :)
