### ISSUE TITLE
One buy two Accounts?

### ISSUE THREAD

**Issue by BoBBer446** [k0shk0sh/FastHub#1561]
Hey, i buy from Tablet and that Works.

Now im on Note 4 and restore My buy ans a Green Text is Show "thank you for Support" but there is No Premium on Phone.

Is that right? One buy one device or one buy one Gmail Account unminited devices ?

**Comment by k0shk0sh** [comment]
Its tied to ur Gmail account. Maybe clear app data and click restore again?

**Comment by BoBBer446** [comment]
No, sorry for Spam. But IT dosent Work.

Solution was deinstall and Install again. Now IT works
