### ISSUE TITLE
Can like comment multiple times

### ISSUE THREAD

**Issue by rugk** [k0shk0sh/FastHub#1562]
**FastHub-Libre Version: 4.6.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Model:** LineageOS 14.1
---

STR:
1. Go to an issue, where someone liked a comment (of yours)
2. Tap on the shown :+1: icon.
3. Tap again.

What happens:
For each tap, the number increases: 2, 3, 4, …

What should happen:
 increase only for own like.

**Comment by dedepete** [comment]
Duplicate of #524.
