### ISSUE TITLE
Uppercase labels sorted above lowercase

### ISSUE THREAD

**Issue by droidmonkey** [k0shk0sh/FastHub#1564]
**FastHub Version: 4.6.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

Uppercase labels are being sorted above lower case labels. I expect the case to be ignored when sorting. See screenshot:

Ok, nvm... new bug... the attach image button performs the add link button function.

**Comment by k0shk0sh** [comment]
What????? Of course the attach image will look exactly like the link aren't they links after all? The only difference that image dialog has a select button on the bottom left side lf the dialog.

P.S: I'm not sorting the labels ;)
