### ISSUE TITLE
Some strings are not translatable

### ISSUE THREAD

**Issue by alete89** [k0shk0sh/FastHub#1566]
**FastHub Version: 4.6.3**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto X (2nd Gen)  
---

I'm improving my previous version of Spanish translation, since it's clearer now that strings are shown in its context, and I noticed that some strings are not included in strings.xml. For example the pop-up "This issue will be submitted to  FastHub's repo in GitHub" 

Paradoxically, this issue is about a string that appears when you try to raise an issue :dizzy_face:

I think there are a few more, I'll try to make a complete list and update this issue.

**Comment by alete89** [comment]
Nevermind, I just realized that default strings.xml was updated and has a few more lines that before. I'll update Spanish strings accordingly. You can close this issue.

**Comment by dedepete** [comment]
As you say.
