### ISSUE TITLE
Can't show more wiki page

### ISSUE THREAD

**Issue by Mapaler** [k0shk0sh/FastHub#1568]
**FastHub Version: 4.6.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia XZs  
---

I don't know which page is the "more page", and after click, response error.
![](https://i.imgur.com/KVJls8h.png)
![](https://i.imgur.com/3Xldpxc.png)

**Comment by k0shk0sh** [comment]
I'm scraping the page and therefore I can't do that.
