### ISSUE TITLE
Wrong string "started"

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#157]
In the ~~Activity~~ Feed  tab it says "x __started__ y" instead of starred using the latest Play store release.

**Comment by kutsan** [comment]
It's funny, how did nobody notice it so far. 😂

**Comment by k0shk0sh** [comment]
I guess this should be fixed. will confirm on it 😀

**Comment by k0shk0sh** [comment]
well its not. lol

**Comment by tnguyen14** [comment]
I was just about to report this. Good thing I found this. Thanks for the fix!
