### ISSUE TITLE
Can't use full pro version even after the purchase

### ISSUE THREAD

**Issue by dungeonmaster18** [k0shk0sh/FastHub#1570]
**FastHub Version: 4.6.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5) Plus  
---

I purchased pro version of fasthub today. But I still can't use the full features of it. I am very disappointed and I will initiate my refund. Please fix this.

**Comment by k0shk0sh** [comment]
Can you uninstall and install again??

**Comment by k0shk0sh** [comment]
And please make sure you use the same gmail account as your main

**Comment by dungeonmaster18** [comment]
I have got my refund so I have to make purchase once again.

**Comment by dungeonmaster18** [comment]
It worked but please fix this, it's an unusual behavior from app.
