### ISSUE TITLE
Doesn't show number of contributions

### ISSUE THREAD

**Issue by lilithxxx** [k0shk0sh/FastHub#1573]
**FastHub Version: 4.6.3**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G 2014 LTE  
---

Should show number of contributions like on the github official page.

![](https://i.imgur.com/Itt15gp.jpg)

**Comment by yakov116** [comment]
@lilithxxx does the api provide it?
