### ISSUE TITLE
Ipython/Jupyter notebooks cant be rendered

### ISSUE THREAD

**Issue by Arkoprabho** [k0shk0sh/FastHub#1574]
**FastHub Version: 4.6.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4  
---

On trying to open an ipython notebook on the app, the display was in the form of json, rather than how Jupyter notebooks generally look.

**Comment by cozyplanes** [comment]
@arkoprabho can I get the extension of ipython notebook in you case?

**Comment by Arkoprabho** [comment]
.ipynb
The default that Jupyter creates.

**Comment by cozyplanes** [comment]
Fixed in #1583
