### ISSUE TITLE
Cannot unpin pinned gist

### ISSUE THREAD

**Issue by danielkrupinski** [k0shk0sh/FastHub#1575]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G4c  
---

 After latest update it's impossible to unpin pinned gist.

**Comment by k0shk0sh** [comment]
Dang, you can for now long click on the gist from pinned to remove it.

**Comment by dedepete** [comment]
Long tap is working until the list is refreshed. Attempt to unpin a Gist results a creation of it's copy.

**Comment by danielkrupinski** [comment]
Also if you delete pinned gist it will remain on "pinned gists" list
