### ISSUE TITLE
Notifications do not behave correctly on MIUI

### ISSUE THREAD

**Issue by archmirak** [k0shk0sh/FastHub#1576]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MIX 2  
---

 Notifications do not appear on MIUI unless the app is opened, even if it's running in background. All permissions and autostart are enabled correctly. The app doesn't appear under the **notifications access** list, might be necessary on MIUI.

**Comment by k0shk0sh** [comment]
Its probably your device I had no one ever complained about this. 


Also can you please go to settings/notifications and click on interval and select one?

**Comment by archmirak** [comment]
Thanks for the feedback. Interval is set to 10 minutes (tried all the others too). Believe it or not, they've started working **RIGHT NOW**. I'll try out a bunch of reboots before being 100% sure. Sorry for having opened an issue, karma loves me so much:joy:
