### ISSUE TITLE
Style: Quote mark starts too early

### ISSUE THREAD

**Issue by Gustl22** [k0shk0sh/FastHub#1578]
**FastHub Version: 4.6.4**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S3  
---

If you have a quote, its mark starts one line too early. But in most cases the response to a quote is below it. So the quote mark looks not intuitive.
If you have two quotes successively, the mark is handled the right way. Thx :D

**Comment by k0shk0sh** [comment]
Please provide an example 😊

**Comment by Gustl22** [comment]
"This is some text"

> This is an example quote, plz wait until I uploaded image

"> This is an example quote, plz wait until I uploaded image"

> This is the first quote

> This is a second quote

**Comment by Gustl22** [comment]
In app the quotes begin too early:
![issue1578](https://user-images.githubusercontent.com/18537755/36933551-3544c60e-1edb-11e8-8556-38552237af84.jpg)

In web version, it is done right:
![issue1578_original](https://user-images.githubusercontent.com/18537755/36933541-116503fc-1edb-11e8-9feb-da66271f85ec.jpg)

**Comment by dedepete** [comment]
According to 242585b, this bug has been fixed.
