### ISSUE TITLE
Delete multiple files

### ISSUE THREAD

**Issue by geovanipfranca** [k0shk0sh/FastHub#1579]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4X  
---

 
# Please
I really need to exclude multiple files in a single commit, how i do it?

**Comment by k0shk0sh** [comment]
You can't and there is no api to do that either.
