### ISSUE TITLE
open the web link in the applicantion and show not file found

### ISSUE THREAD

**Issue by loveser** [k0shk0sh/FastHub#158]
when browser the repo  https://github.com/loveser/LearningNotes ，and click the link address 'https://github.com/GeniusVJR/LearningNotes/blob/master/Part1/Android/Fragment.md' in readme.md file，you will find the address to be replaced to https://raw.githubusercontent.com/GeniusVJR/LearningNotes/Android/Fragment.md ， so show not file found
 
the same problem found also some others repo

**Comment by k0shk0sh** [comment]
yea, because Github api does not provide away of giving full links for either images and links, so what FastHub does, to ensure that images and links works (in most cases) is to append a URL to the path. which causes this issue, I couldn't really find  away to solve this.

**Comment by k0shk0sh** [comment]
Alright this issue has been closed, I have check your repo & links, make them work however, it will fall in other scenarios which i'm not aware of, Github for Repo (**ReadMe**) does not provide absolute links for links, so we have to parse them manually which is kinda impossible.
