### ISSUE TITLE
Failed to post notification on channel "Forking gist"

### ISSUE THREAD

**Issue by Chan4077** [k0shk0sh/FastHub#1580]
**FastHub Version: 4.6.4**  
**Android Version: 8.1.0 (SDK: 27, LineageOS 15.1 unofficial)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note3  
---

 ![Warning toast](https://i.imgur.com/YUh0u0Q.png)

**Comment by Chan4077** [comment]
@k0shk0sh Since I've enabled "Show notification channel warnings" (available via Developer options), it shows this toast. This happens when I tap on the "Fork Gist" icon.

**Comment by k0shk0sh** [comment]
U can ignore it tho as the fork is happening.
