### ISSUE TITLE
#issuecomments link does not open in neither fasthub not chrome custom tabs

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1582]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

It seems that fasthub is able to parse(?) the url correctly like following
 https://github.com/YePpHa/YouTubeCenter/issues/2416#issuecomment-300151257

But when there is a link itself, such as
 `https://github.com/YePpHa/YouTubeCenter/issues/2416#issuecomment-300151257` (the same link as above)

Neither fasthub nor chrome custom tabs open the link

Repo with more of these: 
https://github.com/YePpHa/YouTubeCenter

**Comment by k0shk0sh** [comment]
The link is not clickable so I can't do anything about it. 👏

**Comment by cozyplanes** [comment]
Wait what do you mean

**Comment by k0shk0sh** [comment]
The first link is working fine the other one u gave isn't clickable so ?

**Comment by cozyplanes** [comment]
I mean the second one is in codeblocks (aka ticks ` `` `)

Go to https://github.com/YePpHa/YouTubeCenter
and click the 3rd link which is `https://github.com/YePpHa/YouTubeCenter/issues/2416#issuecomment-300151257`

It opens in the web, but not in fasthub, got it?

**Comment by cozyplanes** [comment]
@k0shk0sh

**Comment by k0shk0sh** [comment]
Got you now

**Comment by cozyplanes** [comment]
Umm, what is duplicate with? I don't get any duplicate issues...

**Comment by k0shk0sh** [comment]
Links Not clickable in readme

**Comment by cozyplanes** [comment]
Sorry, but what links? Only `#issuecomments` links?

**Comment by cozyplanes** [comment]
@k0shk0sh hallo?
