### ISSUE TITLE
cannot find achievement

### ISSUE THREAD

**Issue by jmoebius** [k0shk0sh/FastHub#1585]
**FastHub Version: 4.6.4**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

So when going on Owen Wilson through the explore view and accepting the challenge, the system said "no crews available" even for the right location and time and also when clicking "all". However achievement exists for sure and I was able to get on it via a link to it directly.

**Comment by yakov116** [comment]
@jmoebius what in the world are you talking about?!

**Comment by dedepete** [comment]
@yakov116 seems like he confused the repo.
