### ISSUE TITLE
Project views not updating last activity time simultaneously

### ISSUE THREAD

**Issue by iamsubhranil** [k0shk0sh/FastHub#1587]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Wingtech  
- **Brand:** Xiaomi  
- **Model:** HM 2LTE-IN  
---

 ![](https://i.imgur.com/o4T0WaV.png)
This view has been updated whereas the following view has not :
![](https://i.imgur.com/1yYTBfr.png)

**Comment by yakov116** [comment]
@iamsubhranil we display what the api responds no way for us know anything else

**Comment by iamsubhranil** [comment]
Have you read the issue thoroughly? In repository view the correct last activity time is displayed already. Only the list view is displaying the wrong time.

**Comment by yakov116** [comment]
@iamsubhranil have you checked the api thoroughly?

**Comment by k0shk0sh** [comment]
There is something fishy about this. I'll check it out on Wednesday
