### ISSUE TITLE
[Feature Request] link to repo from issue

### ISSUE THREAD

**Issue by danhab99** [k0shk0sh/FastHub#1588]
**FastHub Version: 4.6.4**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S6  
---

 Is there any way to click somewhere on an issue to get to the original repo. That feels like it's missing this.

**Comment by yakov116** [comment]
@danhab99 If I am understanding correctly you can click the arrow button on the top left

**Comment by danhab99** [comment]
It would just go to the last page, which is not always the repo... most of the time its my email.

**Comment by yakov116** [comment]
@danhab99 TOP left not the bottom

**Comment by k0shk0sh** [comment]
As yakov116 mentioned, used top back arrow key
