### ISSUE TITLE
Image is not displayed when opening in README.md

### ISSUE THREAD

**Issue by danmoop** [k0shk0sh/FastHub#1589]
**FastHub Version:  4.6.4**
**Android Version: 7.1.2**  
**Device Information:**  
- MANUFACTURER: Xiaomi   
- BRAND: Xiaomi  
- MODEL: Redmi 4X  
---

When I open an image in some repository that is in README.md, it doesn't display. This image is in **gallery** folder. When I try opening that image not in README.md but in repository folder, it works well.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/20814737/36974093-7b3680ec-2086-11e8-8a36-0af04064d474.gif)

**Comment by cozyplanes** [comment]
Please provide link to repo

**Comment by danmoop** [comment]
[repository](https://github.com/danmoop/FlowerFlow-PC-Version)

**Comment by danmoop** [comment]
It turns out that it displays wrong in any repository.

**Comment by danmoop** [comment]
Maybe it's because I have that images in folder

**Comment by cozyplanes** [comment]
@k0shk0sh

Inline images doesn't seem to show in most readmes

**Comment by avently** [comment]
Duplicate of #1266

**Comment by yakov116** [comment]
Closing as duplicate of #1266
