### ISSUE TITLE
Missing project list in private organization

### ISSUE THREAD

**Issue by develop7** [k0shk0sh/FastHub#1590]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G4 Play  
---

Repro:

- open a private org profile with >1 project available to a current user
- switch to overview tab
-  tap "projects"

Expected: there is a project 8n the list

Instead: there are no projects 9n both tabs

**Comment by develop7** [comment]
Does the issue make sense? Need any new info?

**Comment by k0shk0sh** [comment]
have you granted access to FastHub to use your org? if not please do so also, simplify all of this and use access token to login which then you have the ability to see ur orgs and their stuff without granting access.

**Comment by yakov116** [comment]
@develop7 Closing for lack of response

**Comment by develop7** [comment]
@k0shk0sh 
![image](https://user-images.githubusercontent.com/89889/38922430-cfb388d0-4300-11e8-98de-3b6f86817734.png) 
![image](https://user-images.githubusercontent.com/89889/38922451-de0e1936-4300-11e8-8455-1bf835dc2b50.png)
