### ISSUE TITLE
Can't view source file

### ISSUE THREAD

**Issue by ozeidan** [k0shk0sh/FastHub#1592]
**FastHub Version: 4.6.4**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5T  
---

 I am trying to view the following file: https://github.com/NoelFB/Celeste/blob/master/Source/Player.cs
It's just a blank page for me, when scrolling I can briefly see the text of the file at the top of the screen

**Comment by cozyplanes** [comment]
It is viewed fine here, please update to the latest vereion.

**Comment by Tajnymag** [comment]
Happens to me too. I'm running Fasthub 4.6.4 on Lineageos 14.1 on Oneplus One.

**Comment by krzysdz** [comment]
Can confirm:
![Screenshot](https://i.imgur.com/YVghq8C.jpg)
Xiaomi Mi4s, MIUI 8.3.8 (Android 7.0), Fasthub 4.6.4

**Comment by k0shk0sh** [comment]
its also showing properly here but damn slow because the file is so huge, I think your device is pretty slow to handle the rendering and that's why u couldn't see it. 

P.S: im using oneplus 5t as well ;)
