### ISSUE TITLE
Links to named anchors don't work

### ISSUE THREAD

**Issue by bghgary** [k0shk0sh/FastHub#1593]
**FastHub Version: 4.6.4**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

Click this link: https://github.com/javagl/glTF/tree/update-properties-from-schema/specification/2.0#objects

**Comment by k0shk0sh** [comment]
this requires deep parsing and deep linking to down to the view, i'm sorry as much as I know its important to you but it will complex things up for me.
