### ISSUE TITLE
Display labels in Issue and PR lists

### ISSUE THREAD

**Issue by eode** [k0shk0sh/FastHub#1594]
**FastHub Version: 4.6.4**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

 Hi, I use labels quite a bit - would it be possible to display labels in the PR and Issue lists?  I'd envision that if enabled, they would show up below other issue info, as a bar of colors (lexically sorted by label title), optionally with (potentially truncated) label text.

Thanks for your work!  Easily worth the price for pro.

**Comment by k0shk0sh** [comment]
Please long press on issues and prs :) you'll be surprised with what you'll see.

**Comment by k0shk0sh** [comment]
From issues and prs list and not from feeds screen tho
