### ISSUE TITLE
Cannot render Jupyter notebook

### ISSUE THREAD

**Issue by secsilm** [k0shk0sh/FastHub#1602]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI6  
---

Cannot render Jupyter notebook.

![](https://i.imgur.com/8MJEEmK.jpg) 

It should be something like the following.

![](https://i.imgur.com/tU4yccz.png)

**Comment by dedepete** [comment]
Duplicate of #1069.

_Отправлено с моего P2 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
