### ISSUE TITLE
Follower events not showing in feeds tab

### ISSUE THREAD

**Issue by cujomalainey** [k0shk0sh/FastHub#1604]
**FastHub Version: 4.6.4**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

I am seeing that some of my events such as being followed, or people I am following being followed, are not showing up in the feeds tab but do show up on GitHub.com. Just wanted to let you know in case it was a bug, awesome app by the way.

**Comment by k0shk0sh** [comment]
GitHub doesn't have these evens anymore :)
