### ISSUE TITLE
Mention a participant. 

### ISSUE THREAD

**Issue by Almo7aya** [k0shk0sh/FastHub#1605]
I want to mention a participant in a issue comments.

**Comment by yakov116** [comment]
@Almo7aya ok what would you like us to do about it?

Oh implement it? Please open the issue via the app and give us some more detail.

Thank you for your feedback

**Comment by Almo7aya** [comment]
FastHub Version: 4.6.4 APK Source: Unknown Android Version: 5.1 (SDK: 22) Device Information: • Manufacturer: zte • Brand: zte • Model: N9518

Okay,

Like the github website, 
I want when I type @ It shows all the participants usernames.

**Comment by yakov116** [comment]
@Almo7aya there is an issue about this. 

@k0shk0sh I remember you started on this and then we stopped can't remember why.

**Comment by k0shk0sh** [comment]
Click on expand icon to go full mode and from there you can tag people using `@`
