### ISSUE TITLE
Repository Name after Change

### ISSUE THREAD

**Issue by michalwa** [k0shk0sh/FastHub#1606]
**FastHub Version: 4.6.4**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG X power  
---

 After changing a repo's name FastHub still displays the original one.

*(The repo I've noticed the issue working with was renamed a week ago.)*  

Update:
If it does somehow matter, the repository isn't actually mine.

**Comment by k0shk0sh** [comment]
What was your repo name? And what it become? A link would be helpful ;)

**Comment by michalwa** [comment]
Apparently, the repo's name has been changed back to the original one without me knowing about it. Sorry for the false alert.
