### ISSUE TITLE
please add another payment

### ISSUE THREAD

**Issue by XenoAmess** [k0shk0sh/FastHub#1607]
**FastHub Version: 4.6.4**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** G9 Plus  
---

 Hello bro.Thanks for your amazing software.We Chinese are not able to pay on google store ,so I wish you could add a secondary payment ,like paypal,alipay,or something else. Thanks a lot.

**Comment by k0shk0sh** [comment]
The problem is that Google doesn't allow any other payments :'(. So we are stuck to only use Google play in app purchases.
