### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by Galaxy0419** [k0shk0sh/FastHub#1608]
**FastHub Version: 4.6.4**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

 When you at a project's  page and exit.The app goes back to the home page.I wish it can stay the previous page I visit.

**Comment by k0shk0sh** [comment]
Don't click on toolbar icon and you'll go back to where you left.

**Comment by k0shk0sh** [comment]
Press hardware back button
