### ISSUE TITLE
Last releases lack APK attachment

### ISSUE THREAD

**Issue by IzzySoft** [k0shk0sh/FastHub#1610]
The last release with an `.apk` attached was v4.6.1. Did you stop attaching it on purpose? If not, could you please pick it up again, starting with the latest release? Thanks a lot!

**Comment by IzzySoft** [comment]
I really don't want to annoy anybody – but a statement would be nice (the asked-for attachment even nicer :wink:). @k0shk0sh ?

**Comment by IzzySoft** [comment]
Still no answer. If you don't want to offer the APK here any longer, you should also remove the "direct APK download" link from the `REAMDE.md`. Not that I want to press, but in that case I will have to remove the app from my repo, for obvious reasons.

**Comment by k0shk0sh** [comment]
Sorry I have no time to do that. Nothing personal.

**Comment by IzzySoft** [comment]
That's sad. In this case, I have to remove the app from my repo. No idea where those 1 minute per release is missing (doesn't take longer to attach the file; I'd bet maintaining this issue was more time consuming).

I have to accept this – but it will make some users very unhappy (namely those using my repo and your app).

**Comment by dedepete** [comment]
Why don't you set up building  APKs on CI?

**Comment by IzzySoft** [comment]
@dedepete me or @k0shk0sh ? If you mean me: No build env here. And no build experience either (I'm no Android dev). So as Kosh marked this "abandoned", I've removed the app from my repo. If Kosh changes his mind, I can re-enable it anytime, just notify me then.

**Comment by GeoZac** [comment]
The APK gets released at [apkmirror.com](https://www.apkmirror.com/),so what's this issue about? moreover developer has mentioned the reason as lack of time.

**Comment by dedepete** [comment]
@IzzySoft have a look at the Travis CI configuration in `build` branch of my fork. You might want to do something like that.  
Or, as was written before, you should use APKMirror to get APKs.

_Sent from my P2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by IzzySoft** [comment]
@dedepete thanks, but no. I have no time fiddling with that. So, as you said, folks must use APKMirror instead to get the APKs – no updates via F-Droid then.

@GeoZac please see #15 (especially [this comment](https://github.com/k0shk0sh/FastHub/issues/15#issuecomment-282579566)), #136 and #1208 if you need context on "what's this issue about". And I have already stated [in this comment](#issuecomment-390623947) that I accept Kosh's decision. Plus offered to pick up again if circumstances change. So until then, please excuse me from this issue. I personally do not use the app (one reason being it's not available on F-Droid).
