### ISSUE TITLE
Some PRs counting is wrong

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1611]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---
For some reason, details, commits, and files counter is all 0

 ![](https://i.imgur.com/IHYMViU.png)

Link https://github.com/k0shk0sh/FastHub/pull/1556

**Comment by k0shk0sh** [comment]
yep, sometimes GitHub doesn't return the right data: 

```
"commits": 0,
"additions": 0,
"deletions": 0,
"changed_files": 0
```

look at the last rows of the response https://api.github.com/repos/k0shk0sh/FastHub/pulls/1556

**Comment by cozyplanes** [comment]
Hmm weire
