### ISSUE TITLE
Code blocks in markdown documents have no syntax highlighting.

### ISSUE THREAD

**Issue by krzysdz** [k0shk0sh/FastHub#1612]
**FastHub Version: 4.6.4**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI 4s  
---

There's no syntax highlighting in markdown documents eg [Electron doc about frameless windows](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md).
Wouldn't it be possible to implement it using already existing syntax highlighting  used when displaying single files?

**Comment by k0shk0sh** [comment]
Sorry, but they are different things and it's not applicable for Android textview unless if we create our own android syntax highlight for spans.
