### ISSUE TITLE
Can "react" to comments multiple times

### ISSUE THREAD

**Issue by knyzorg** [k0shk0sh/FastHub#1614]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus2  
---

 Hitting the "thumbs up" on comments multiples times behaves improperly.

**Comment by yakov116** [comment]
@knyzorg Please search before opening an issue.

Thanks for your feedback
