### ISSUE TITLE
Profile image is not refreshed

### ISSUE THREAD

**Issue by dennythecoder** [k0shk0sh/FastHub#1620]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

 Profile image has changed a couple of times, but the app is still showing version from a few weeks ago.  Github shows the appropriate image in the browser.

**Comment by yakov116** [comment]
@dennythecoder please search the issues.....

**Comment by k0shk0sh** [comment]
Settings/behavior &  clean image cache

**Comment by dennythecoder** [comment]
I am so sorry about that, @yakov116.  Must have just searched the open issues.
