### ISSUE TITLE
Listing of organizations is empty. 

### ISSUE THREAD

**Issue by MeanEYE** [k0shk0sh/FastHub#1622]
**FastHub Version: 4.6.4**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7 Edge  
---

When I go to listing of organizations there is nine listed, however I am a member of one.

**Comment by k0shk0sh** [comment]
Please read faq from app or readme

**Comment by MeanEYE** [comment]
Thanks. Probably missed in one of those "what's changed" popups. It might be a good idea to create some sort of notification which is not modal. There are probably redundant reports for issues such as this one which could be prevented by people reading new version information. In my case, and I assume others, I had to access some information urgently and just blindly closed the window without reading.

**Comment by yakov116** [comment]
@MeanEYE the FAQ has been around for a long time. The best thing to do is search the repo before opening an issue

**Comment by MeanEYE** [comment]
@yakov116 true, but for me it wasn't the obvious place to look at something that felt like a bug. I was merely suggesting non-intrusive way of notifying user about changes which doesn't desensitize them over time like modal dialogs do.

Am not implying everyone is acting the same way I do, but people are creatures of habit and if they are use to clicking "Ok" every week or so, then they will miss new things as a result of this habit. Either way, I am glad this wasn't a bug and that I can keep using my application.
