### ISSUE TITLE
Filter starred repos on trending page 

### ISSUE THREAD

**Issue by neonailol** [k0shk0sh/FastHub#1623]
**FastHub Version: 4.6.4**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone 2 Laser (ZE601KL)  
---

 It would be nice addition to the app, if trending page had a filter out repositories starred by user feature, or marked them in a different color 

_Sent from my ZenFone 2 Laser (ZE601KL) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
I don't think that this is a good idea, as I will load every single page (make request) of the user starred repos and filter the trending list which by itself is slow enough due to scrapping.
