### ISSUE TITLE
Adding an assignee to an issue shows a send icon

### ISSUE THREAD

**Issue by Bettehem** [k0shk0sh/FastHub#1624]
**FastHub Version: 4.6.4**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus3  
---

 Adding an assignee to an issue shows a send button, which can be confusing, so I suggest that it would be changed to a check mark

**Comment by k0shk0sh** [comment]
What are u exactly talking about?
The assignee in issue shows person pic and in create issue screen it shows plus icon to indicate click.

**Comment by Bettehem** [comment]
I mean in the assignee screen, in the top right corner, there's a send icon instead of a check mark: :heavy_check_mark:
