### ISSUE TITLE
Scrolling Down when Opening the Profile Section (Right)

### ISSUE THREAD

**Issue by michalwa** [k0shk0sh/FastHub#1625]
**FastHub Version: 4.6.4**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG X power  
---

 
The scroll area scrolls down when sliding-open the right (profile) menu.

![screenshot0](https://i.imgur.com/Mhw3lHO.png)
![screenshot1](https://i.imgur.com/B9NMxWJ.png)
![screenshot2](https://i.imgur.com/7FmrWTq.png)

**Comment by dedepete** [comment]
It happens because of a scrollbar always being visible. Trying to open a right panel always causes an accidental touch of the scrollbar.

**Comment by shamshadali9542** [comment]
Hi
