### ISSUE TITLE
Shortcut shown in Japanese when app language is set to English

### ISSUE THREAD

**Issue by azumukupoe** [k0shk0sh/FastHub#1627]
**FastHub Version: 4.6.4**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** docomo  
- **Model:** Xperia XZ Premium  
---

**Comment by k0shk0sh** [comment]
Shortcut language is outside of my control. I can't do anything about it.
