### ISSUE TITLE
Respect issue templates

### ISSUE THREAD

**Issue by SuperSandro2000** [k0shk0sh/FastHub#1628]
Fasthub should respect issue templates in repos in the .github folder.
---
**FastHub Version: 4.6.4**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

**Comment by yakov116** [comment]
@SuperSandro2000 there is no API for this

Thanks for your feedback

**Comment by SuperSandro2000** [comment]
You could check the repo if this file exists and simply display the markdown.

**Comment by yakov116** [comment]
@SuperSandro2000 not so simple since the file can be in a few places. Plus it would be an api request and look at the file, load the file and display it to the user (in edit mode).

Your more than welcome to send in a PR

**Comment by SuperSandro2000** [comment]
I thought that it can only be in one place. Then it is a bad idea because to much network traffic and wait time. Thanks for the clearing up.

**Comment by yakov116** [comment]
@SuperSandro2000 np :)

Thanks for your feedback
