### ISSUE TITLE
FQA

### ISSUE THREAD

**Issue by bbest31** [k0shk0sh/FastHub#1629]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Model:** Nexus 6  
---

 Back button doesn't work from FAQ page

**Comment by k0shk0sh** [comment]
Yes, its intended, scroll all the way down and click the button to exit that screen. ☺️
