### ISSUE TITLE
Sorting in search repositories 

### ISSUE THREAD

**Issue by xFFFFF** [k0shk0sh/FastHub#1634]
**FastHub Version: 4.6.4**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4 Pro  
---

 Will be nice to have feature to sort results of search in repositories by recently updated. I checking updated forks by this way. Can You implement it?

**Comment by k0shk0sh** [comment]
Definitely, matter of fact there is plenty of feature request regards this.

Please do search for issues/fr before opening new one, its harder for me to track everything in such way.
Thanks
