### ISSUE TITLE
Account deleting

### ISSUE THREAD

**Issue by CatalySstS** [k0shk0sh/FastHub#1636]
**FastHub Version: 4.6.4**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4X  
---

 Please remove my account

**Comment by k0shk0sh** [comment]
This won't be implemented, anything that is sensitive to the user wont be deleted, ex: delete account, delete org, repo. If this was official client it had be possible but users wont trust that I don't delete their acc myself ;)

**Comment by dedepete** [comment]
If you want to remove your GitHub account at all, you can do it within a website.
