### ISSUE TITLE
Changelog close bug

### ISSUE THREAD

**Issue by MatthewOwens** [k0shk0sh/FastHub#1642]
**FastHub Version: 4.6.4**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P9  
---
Screenshot of the bug can be seen here
 https://imgur.com/gallery/80wv4

Occurred when opening fasthub from a link after an update, changelog displayed correctly but them failed to completely close

**Comment by k0shk0sh** [comment]
4.6. 0 and your version is 4.6.4. please only report last issues.
