### ISSUE TITLE
Cannot install apk from Dowload in android 8

### ISSUE THREAD

**Issue by AllanWang** [k0shk0sh/FastHub#1643]
**FastHub Version: 4.6.4**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** 3  
---

 Before this is closed off as a duplicate, it seems that it could arise from [the new change](https://developer.android.com/studio/publish/index.html#publishing-unknown) with Android O.

Steps:
* Go to a release page of a repo
* Download the APK (successfully)
* Clicking the notification will attempt to open the installation then fail.

This works fine on Nougat on my Nexus 5, and I do believe there is a change that needs to be done from your app to enable this.

As a side note:

* Granting external storage permission does not proceed with downloading the file immediately; we need to click it again for it to work. Not sure if this is what you wanted.
* You can consider adding a media scan once the file is downloaded to ensure it shows up in file managers:

`request.allowScanningByMediaScanner()`

**Comment by k0shk0sh** [comment]
PR? It seems you only to ever complain about this. I'm not interested to fix it as it adds no value for me and I no longer upload apk anyway to release page.
Thanks

**Comment by AllanWang** [comment]
@k0shk0sh are you still opened to inviting members to your slack? I'm interested in joining. me@allanwang.ca

**Comment by k0shk0sh** [comment]
Click on link to join from readme or from about screen in app

**Comment by AllanWang** [comment]
@k0shk0sh I'm asking because the link no longer works.

Link in question: https://fasthub.slack.com/join/shared_invite/enQtMzEyNTI1MTM2NDAyLTRkNGNmMjM5ZGY0MjRjZTkzMzNmYzE5MmYxYjU3MDZkNWE0NWY4ZmI4OGQxZTI2ZjBlOWI0ZDE2MWUyODZjYjc

**Comment by AllanWang** [comment]
@SuperSandro2000 so you guys aren't even open to a PR to address this? I'm quite sure the installation issue is related to the Android O update, where this is now a security feature. Second point it just one line and can help users depending on the file manager.

**Comment by SuperSandro2000** [comment]
I am no Dev of this app. Just a random user. 😂  If you want to do a PR then do it. If it doesn't break anything I am sure he would consider pushing it.

And I am on O too and opening the notification flashes the screen and does nothing. This could be considered a bug.

**Comment by AllanWang** [comment]
@SuperSandro2000 it's the same thing as the app crashing when you updated to Marshmallow but the app didn't implement the permission manager. I will take a look when I have time.
