### ISSUE TITLE
Sort/filter stars

### ISSUE THREAD

**Issue by azumukupoe** [k0shk0sh/FastHub#1644]
**FastHub Version: 4.6.4**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** docomo  
- **Model:** Xperia XZ Premium  
---

**Comment by yakov116** [comment]
@azumukupoe please search before opening an issue 

Thanks for your feedback
