### ISSUE TITLE
Change download path

### ISSUE THREAD

**Issue by azumukupoe** [k0shk0sh/FastHub#1645]
**FastHub Version: 4.6.4**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** docomo  
- **Model:** Xperia XZ Premium  
---

**Comment by k0shk0sh** [comment]
Not interested in this, I don't like to complex everything within the app. 


I'm not so sure what's your use case in here but I see no value in that. 

Thanks again and sorry to again close the ticket.
