### ISSUE TITLE
Source anchor link preview is not styled

### ISSUE THREAD

**Issue by arteniioleg** [k0shk0sh/FastHub#1646]
**FastHub Version: 4.6.4**  
**Android Version: 5.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** Meizu  
- **Brand:** Meizu  
- **Model:** PRO 5  
---

* In app https://static.md/78fe6765ac6645c2f17420313552cc97.jpg
* In browser https://static.md/889b070e43186b04c2f494045629214f.jpg

Issue https://github.com/twbs/bootstrap/issues/25910

**Comment by k0shk0sh** [comment]
I'm aware of that and unfortunately I can't implement it due to limitation of the current markdown implementation I have.
