### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by pythoncoder718** [k0shk0sh/FastHub#1647]
**FastHub Version: 4.6.4**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Vodafone  
- **Brand:** Vodafone  
- **Model:** Smart ultra 6  
---

 İt says  no internet connection but there is internet connection .

**Comment by cozyplanes** [comment]
Exactly where? I see you posted this issue in fasthub

**Comment by k0shk0sh** [comment]
he probably had slow internet connection or something like he loaded issue or anything and he lost the internet during the API call which is perfectly fine.
