### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by naloder** [k0shk0sh/FastHub#1648]
**FastHub Version: 4.6.4**  
**Android Version: 5.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** Meizu  
- **Brand:** Meizu  
- **Model:** M1 Note  
---

 When i want to reopened the closed issue，the toast tell me"validation failed"，how can i reslove it

**Comment by yakov116** [comment]
@naloder org?

**Comment by k0shk0sh** [comment]
Look into FAQ from within the app and read the section about Organization.
