### ISSUE TITLE
Image cache should be invalidated at regular intervals.

### ISSUE THREAD

**Issue by raisedadead** [k0shk0sh/FastHub#1649]
**FastHub Version: 4.6.4**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

 Steps to reproduce:

Change profile picture of your account. Or notice a profile picture change of someone else on GitHub.

Visit the FastHub app.

Check the same profile. 

It will not have updated.

This is the case even after days.

Workaround:
Force Stop app, Clear Cache and disconnect from internet.

Relaunch app, reconnect and refresh feed.

Proposal:
Cache should be invalidated at regular intervals, of say 3-4 hours.

**Comment by yakov116** [comment]
@raisedadead 2 options.
 1. Search the issues
2. Go to behavior > Clear image cache

**Comment by raisedadead** [comment]
@yakov116 thanks for the answer. 

However, why would it have to be a manual setting and not an automated CRON?

**Comment by raisedadead** [comment]
Please feel free to link me to an issue if that is answered.

**Comment by SuperSandro2000** [comment]
Common problem on Android.

**Comment by SuperSandro2000** [comment]
@k0shk0sh or buy a enough storage. If you always have like 8 GB free this never happens.

**Comment by k0shk0sh** [comment]
Its not like its going to take much, the main problem with this is that GitHub uses the same link for every image you change and therefore its hard to know when the image changes so clearing the chat is introduced.

**Comment by raisedadead** [comment]
> GitHub uses the same link for every image you change and therefore its hard to know when the image changes so clearing the cache is introduced.

Yes, understood. But can we not possibly not automate it? Running cache clear every few hours, of course as a setting selected by user?

**Comment by SuperSandro2000** [comment]
When every week or two at most.

**Comment by k0shk0sh** [comment]
I'm not really interested on such complexity, the settings are floded enough with customization, you have to understand my decision and not think of it like I'm being lazy or something.

**Comment by raisedadead** [comment]
Sorry for the trouble, but I did not realize this project to be opinionated.

> I'm not really interested on such complexity, the settings are floded enough with customization,

Aren't you contradicting your opinion? You do not want complexity as a maintainer and hand them over to users with flooded customization?

I realize, people are paying so its not a matter of not being able to support either.

Thanks for your time, being in OS I believe I am open to fork and add this myself right?

**Comment by yakov116** [comment]
@raisedadead sure!

But understand the having it cleared at regular intervals may cause unnecessary data usage for some users that use the app on a daily basis. 

I understand where you are coming from, but we have many users. It's hard (actually impossible) to make every one happy.

Thanks for your feedback

**Comment by raisedadead** [comment]
Trust me @yakov116 I share your frustration as a OS maintainer. But in any case thanks a lot for your time. 
I am clear of the stance here. 

And I appreciate the effort ✌️.

**Comment by xenreon** [comment]
Besides what @yakov116 mentioned about causing extra data usage for users, clearing cache like that might also create issues for those on a slow and/or unreliable network by wiping off other images that were cached.

Overall I think it's something that GitHub itself first needs to change, before that better to just add it to the faq and stay with the current approach.

**Comment by Gustl22** [comment]
@yakov116 
A good and intuitive compromise would be, if you tab to load the full avatar, then the thumbnail is updated synchronously (?). Maybe I can handle this in a PR.

**Comment by yakov116** [comment]
@Gustl22 thats a lot of api calls and data.
We have to be very careful not to max out a users requests, plus the users data.

@k0shk0sh what if going to a user profile refresh's the icon?

**Comment by k0shk0sh** [comment]
The refresh is always happening the prob is that GitHub does not change the profile pic url neither size so I can't know if it actually changed or not

**Comment by Gustl22** [comment]
Would work second [method](https://stackoverflow.com/questions/33443146/remove-image-from-cache-in-glide-library) here, to add additional data (like time stamp of image), if url keeps the same? I never worked with `Glide`. But would be really annoying if cannot address and remove a simple cached [image](https://github.com/k0shk0sh/FastHub/blob/development/app/src/main/java/com/fastaccess/ui/widgets/AvatarLayout.java#L84).

**Comment by k0shk0sh** [comment]
Yep, PR?

**Comment by Gustl22** [comment]
@k0shk0sh : I didn't want to invoke any false hopes. Didn't realize it's that hard to get a time stamp from `.png`.

Anyway, I made a solution (following the example of @yakov116), but it's kind of a hack (see [`ProfileOverviewFragment`](https://github.com/Gustl22/FastHub/blob/avatar/app/src/main/java/com/fastaccess/ui/modules/profile/overview/ProfileOverviewFragment.java#L189) & [`AvatarLayout`](https://github.com/Gustl22/FastHub/blob/avatar/app/src/main/java/com/fastaccess/ui/widgets/AvatarLayout.java#L93)). I think this isn't exactly what you search for (and would trigger reloading avatar two times). Sorry for time-wasting, if this solution doesn't suit you :)

**Comment by yakov116** [comment]
@Gustl22 submit the pr and we will try to make it work
