### ISSUE TITLE
Feature Request: Repo main language on search and user pages. 

### ISSUE THREAD

**Issue by beshology** [k0shk0sh/FastHub#165]
In addition to the number of stars and forks, etc. It would be great if we knew the main language of the repo while we are on search pages, and while looking at users' stars and repositories. 
Thanks for your efforts.

**Comment by kutsan** [comment]
Thanks for your feedback. That's definitely necessary. Eventually, you will see this in future.

**Comment by beshology** [comment]
Thank you
