### ISSUE TITLE
Feature Request - search by language

### ISSUE THREAD

**Issue by bearcatsandor** [k0shk0sh/FastHub#1651]
**FastHub Version: 4.6.4**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 It would be nice to be able to search by language. One could search by rust for instance, and pull up all of the repositories that contain rust code. It would be an additional boon to be able to sort by language percentage.

_Sent from my Pixel 2 XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bearcatsandor** [comment]
For the record, which bug # is it a duplicate of? That's usually indicated when marking a bug a duplicate. Thanks.

**Comment by k0shk0sh** [comment]
Why not go 50/50 and search issue before posting?

**Comment by bearcatsandor** [comment]
I did that before posting. I searched "languages" and didn't find it in the search results. Then I looked through all open issues and didn't see it. I looked through the first 5 pages of the 1k+ closed issues and didn't see it.

Even if i had seen it, the point is that the common practice in citing which bug you are marking something a duplicate of is a good one.  Yanno, for the record, as aforementioned.

**Comment by bearcatsandor** [comment]
Why would i search in my own repos for a bug in this repo? I'm talking about the filter field in this repo's issues. Yanno, that one that defaults to "is:issue is:open".  If the dupe can be found, great!  I'll add the link to it myself.

**Comment by yakov116** [comment]
@bearcatsandor can answer my question please

**Comment by bearcatsandor** [comment]
I just did. Alright, I'll answer it directly. The search menu. (Your question isn't properly phrased. There is no "search menu", just a filter field when you click on the "Issues" tab in this repository.)

**Comment by yakov116** [comment]
>Yanno, that one that defaults to "is:issue is:open".

Yanno a duplicate issue can be closed too.

@bearcatsandor sorry for being so sharp, your acting like a 2 year old.

As for your question I will look at the api and let you know if it's even possible.

Just so you understand I understood your original question to be that you would like to filter/sort you own repository's by lang and for that I'm almost positive there is an open issue

**Comment by bearcatsandor** [comment]
I don't think you understand. My point was not about searching, or whether i could find it. My point was that when something is marked a duplicate, that duplicate should be linked to in an issue comment. That's standard operating procedure across Github.  That doesn't seem to be understood, so i'm dropping it.

My question was:  Is there a way to search all repositories by language?  Not just my own. Suppose i open Fasthub, and i want to filter by repositories that contain code in Rust.  If Fasthub can do that, how? If not, can it be made to do so?

However, i just discovered that if you put 'topic::"rust"' in the searchbar, it does that for you.

Done.

Thanks.

**Comment by yakov116** [comment]
@bearcatsandor I am going to say it again, your acting like a 2 year old.

Glad you found what you were looking for.
