### ISSUE TITLE
[Request] Sliding in side menu

### ISSUE THREAD

**Issue by JRoy** [k0shk0sh/FastHub#1653]
**FastHub Version: 4.6.6**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

Since that menu merge in 4.6.6, the left menu should let you swipe inside of it so you can switch between the two. This was hard to put into words, if you need more clarification lemme know.

**Comment by k0shk0sh** [comment]
This isn't possible because the drawer has the full touch event and I have tried that.
