### ISSUE TITLE
Press Home button in menu crashes the app closed

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#1656]
**FastHub Version: 4.6.6**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

 

_Sent from my Pixel 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Newest issue is exactly like this, also technically you are at home so avoid pressing it until next release ;)

**Comment by Gorislim13** [comment]
Kokosh I will pay u 25 Btc if u can help me get Wynn. Bacvk up I got hacked my values gone etc call me 949 395 6325
