### ISSUE TITLE
Back button feature

### ISSUE THREAD

**Issue by kangarang** [k0shk0sh/FastHub#1659]
**FastHub Version: 4.6.6**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** ZTE  
- **Brand:** ZTE  
- **Model:** A2017U  
---

Hello, it'd be great if there was an optional feature to change the way tapping the `back` button works.

Options:
1. Double-tapping exits the app (as it currently works)
2. Tapping when on the top-level opens the drawer (e.g. like how the slack mobile app works)

**Comment by k0shk0sh** [comment]
Thanks but I don't like that. Back button = its never open.
