### ISSUE TITLE
On click "Home" option in left drawer app closes.

### ISSUE THREAD

**Issue by vipulasri** [k0shk0sh/FastHub#1661]
**FastHub Version: 4.6.6**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 In left drawer, on clicking "Home" option app closes rather it should take you to the home screen of the app.

**Comment by k0shk0sh** [comment]
Thanks, but please search before posting the thousand duplicated issue. 😪

**Comment by vipulasri** [comment]
@k0shk0sh I submitted the feedback from the app. If I would have submitted the issue from the web, would have definitely checked the existing issues.

**Comment by cozyplanes** [comment]
@vipulasri You can search in app as well

**Comment by dedepete** [comment]
@cozyplanes but you can't when submitting an Issue via a "Report an Issue" function.

**Comment by yakov116** [comment]
@dedepete I think we should put a notice.

@k0shk0sh can we do a search to check for duplicate issues? Maybe that will slow down the ammount of duplicates

**Comment by cozyplanes** [comment]
@dedepete yeah
@yakov116 interesting
