### ISSUE TITLE
Version indicator in about page

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#1662]
**FastHub Version: 4.6.6**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---
![](https://i.imgur.com/JLohLqT.png)

When a new version is available....

#### Click the version in about page
- Change `Version ` to `Check for Updates`
- Change `4.6.x` to  `Current Version is 4.6.x`

#### Toast appears indicating there is a new version
- Change the toast to be colored like the other toasts
- Open play store to update app

**Comment by k0shk0sh** [comment]
Wow, not so sure but I feel like I'm being commanded to do this.


Have u heard of PR?
