### ISSUE TITLE
Home tab

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#1663]
**FastHub Version: 4.6.6**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

 App exits on clicking Home in the left panel.

**Comment by SuperSandro2000** [comment]
#1658

**Comment by k0shk0sh** [comment]
Don't click on home while you are in home until this is fixed, 

P.S: I'm trying to keep this tidy please search first.

**Comment by abhijithvijayan** [comment]
Sorry I didn't notice
