### ISSUE TITLE
Feature request: move tickets

### ISSUE THREAD

**Issue by Calder-Ty** [k0shk0sh/FastHub#1665]
**FastHub Version: 4.6.6**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** DROID Turbo 2  
---

 It would be really nice to be able to transfer issues between repos. I understand a lot of meta-data would be lost, but for me just the functionality to move tickets would be nice.

**Comment by yakov116** [comment]
@Calder-Ty how in world is this connected to fasthub?!

**Comment by Calder-Ty** [comment]
I really like fasthub, you say it was nearing completion, adding feature
requests, and I'd think adding a feature like this would really enhance the
app.

**Comment by yakov116** [comment]
@Calder-Ty sorry for coming across so strong.

The app is intended to help use the functions that the daily user of github is doing. This kind of function is not part of github.com nor is there an api for this.

Thanks for your feedback
