### ISSUE TITLE
Back-Stack not properly working when visiting Trending

### ISSUE THREAD

**Issue by SirWindfield** [k0shk0sh/FastHub#1667]
**FastHub Version: 4.6.6**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

 If you click on the Trending tab and open up a project, you get redirected to your dashboard/home activity once you clicked the back arrow or button. 

I think it would be more intuitive if you would get sent back to the Trending app to browse for more projects instead of having to click on the Trending tab again to bring it up.

**Comment by yakov116** [comment]
@SirWindfield use your phone back arrow...

Please search the issues before opening a new one

Thanks for your feedback

**Comment by SirWindfield** [comment]
That's still the wrong behaviour in my opinion. Pressing the back arrow should still lead you, in this instance, to the Trending tab.

**Comment by yakov116** [comment]
@SirWindfield back arrow in Android = up phone back arrow = back....

**Comment by SirWindfield** [comment]
So you tell me that the back arrow on the action bar is the same as down on my controls? 

The thing is, they do not behave the same. The action bar one brings me back to the base activity where you see your feed. The one in the control at the bottom of the screen actually pops the activity stack and brings me back to my previous activity, the Trending activity. 

I'm pretty sure that this is not intended. 
And for the next time, I have no clue what you tried to say in your last comment. Just use some more words. It literally takes 1 more minute.

**Comment by k0shk0sh** [comment]
You acted like you know about Android navigation and he assumed that you know so he went with technical explanation.


The behavior is right, use device back button to return where you were and use toolbar back button to navigate up.

**Comment by SirWindfield** [comment]
Ye I know some stuff. I actually thought that both have the same purpose. Sorry for the inconvenience then. My fault.

I guess I learned something new today :smile:
