### ISSUE TITLE
Message window stuck.

### ISSUE THREAD

**Issue by McGoodmen** [k0shk0sh/FastHub#1668]
**FastHub Version: 4.6.6**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus3T  
---

   The smaller fast hub window that opens on startup was stuck after I closed the update window.

**Comment by cozyplanes** [comment]
Screenshot plz

**Comment by k0shk0sh** [comment]
hmmm, which version were you in before updating? because I removed that since 4.6.5. 

Please monitor it for the next release and reopen this if it still occur.
