### ISSUE TITLE
Feature: Use github styled colored icons for issues and PRs

### ISSUE THREAD

**Issue by shanavas786** [k0shk0sh/FastHub#1670]
Use github like colored icons to indicate status of issues and PRs

**Comment by yakov116** [comment]
@shanavas786 in war menu are you talking about?! In the feed? If yes there are older versions of Android that crash when we tried using them.

Also try to open issues via the app.

Thanks for your feedback.

**Comment by shanavas786** [comment]
On March 28, 2018 2:44:42 PM GMT+03:00, yakov116 <notifications@github.com> wrote:
>@shanavas786 in war menu are you talking about?! In the feed? If yes
>there are older versions of Android that crash when we tried using
>them.

>
>Also try to open issues via the app.

This issue was opened from the app.

>
>Thanks for your feedback.

**Comment by yakov116** [comment]
@shanavas786 you removed the top part? If yes its there for us to help us, please leave it intact.

Also please answer my question

**Comment by shanavas786** [comment]
![screenshot_20180328-145408](https://user-images.githubusercontent.com/5337197/38043134-eda34b02-32be-11e8-9772-d973586e44be.png)

This is the one I was talking about.
Yes I removed it as I thought it is not relevant for this.
Here are the details
**App Version: 2.1.0**

**OS Version: 24**

**Model: HUAWEI-RNE-L21**

**Comment by yakov116** [comment]
@shanavas786 Yup sorry were unable to use them since older versions will crash

Thanks for your feedback
