### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by thewama33** [k0shk0sh/FastHub#1676]
**FastHub Version: 4.6.7**  
**APK Source: Aptoide**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi 4X  
---

 When  clicking on  the SearchBar  it lagging  like  have to wait  5 or 4 seconds  to shows the keyboard to write
and so that  when writing   

_Sent from my Redmi 4X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
Your phone is slow
