### ISSUE TITLE
Feature Request: Exploring Github

### ISSUE THREAD

**Issue by beshology** [k0shk0sh/FastHub#168]
A feature that allows us to explore Github.com by trending repositories by day, week, month and/or language

**Comment by GeorgeWL** [comment]
Last I heard, despite many apps over the years asking for it to be exposed to API, Github Explore isn't actually in the API.

Maybe things changed?

**Comment by k0shk0sh** [comment]
@GeorgeWL nope, nothing has changed. the API isn't provided yet.

**Comment by GeorgeWL** [comment]
Jesus, the last I looked was 3 years ago.  Github are shit at listening to user requests.

**Comment by k0shk0sh** [comment]
Idk about that to be honest, me and @kutsan have emailed them few times concerning about some API's they were helpful even tho, they will say, we can't promise you that (which mean they will never do) but yea, they don't care much and I don't think their API has any higher priority.

**Comment by eyalcohen4** [comment]
@k0shk0sh
What about scraping that page?
I didn't dive into this app source yet,
And I guess it doesn't require any server,
But I will love to help with crawl the trending and explore pages.

**Comment by k0shk0sh** [comment]
@eyalcohen4 that would be cool, I really could use some help in here as I start to struggle with all the feature requests & fixes that I need to do in short time. you could join our slack channel from the badge in readme to help you with whatever questions you have.

**Comment by k0shk0sh** [comment]
@eyalcohen4 @GeorgeWL @beshology alright guys, this will be in next release.
