### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by larsonthekidrs** [k0shk0sh/FastHub#1680]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus3T  
---

 Ok on the main page, I think you should add a feature where we can swipe between feed, Issues and pull request.

**Comment by k0shk0sh** [comment]
Sorry, but that's not applicable, use bottom bars to navigate between them.
