### ISSUE TITLE
Can't change notification sound.

### ISSUE THREAD

**Issue by dedepete** [k0shk0sh/FastHub#1681]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LENOVO  
- **Brand:** Lenovo  
- **Model:** P2  
---

Tapping on the "Choose Notification Sound" does not do anything.

_Sent from my P2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
is it your phone? I mean I could press it and select different notification.

**Comment by dedepete** [comment]
I have disabled and re-enabled notification sound and the issue has gone. \\\_(.\_.)\_/
