### ISSUE TITLE
Enable download / make available offline all files

### ISSUE THREAD

**Issue by mo45555** [k0shk0sh/FastHub#169]
1. Enable to download all the files at once instead of one by one
or
2. Enable to make all files available offline by one / few clicks

At least for text files.

**Comment by kutsan** [comment]
Thanks for your feedback.

You mean; all files should be indexed by default, and then you can easily navigate and open whatever file you want as requested, without content of files? Or you want it to be available all content of files by default? Can you explain more?

**Comment by mo45555** [comment]
I guess the second option.

Let me explain you the motivation. I want to learn new things through
reading code. But I do not have internet available on my tablet.
I would love if there is *simple* way to see the files even offline, so I
do not have to download and copy in advance or to do hot spot with my phone
or any WA.

Simple means something like button "make available offline", but this
shouldn't be the default.

It is really "nice to have" feature and not mandatory as WiFi and data is
getting available/cheaper more and more.

Thanks in advance,
Mosh

**Comment by kutsan** [comment]
I understand now. With the current circumstances, I guess it won't be happen in near future. There are more important requested features than this one.

I personally suggest you to clone GitHub repositories to your phone, than you can access files even offline.

Feel free to contact us whenever you want.

**Comment by mo45555** [comment]
It's fine. Thanks for trying to help.

**Comment by k0shk0sh** [comment]
in 1.2.0 files are saved for offline

**Comment by mo45555** [comment]
Wow, many many thanks!.

**Comment by k0shk0sh** [comment]
@mo45555 the current implementation is that you have to be fully offline to this works and also requires you to open the file at least once to save its content then onward offline will load it. if this solution satisfy you, please close the issue. otherwise I don't I will make this available anytime soon unless if I let you download all the repo folder and see them outside of the app, if this option is fine, then let me know so I could label the issue properly.
Thanks

**Comment by mo45555** [comment]
You mean I need to open the files one by one? I think this is how it was before? isn't?

I wish I have something let me save/download/available offline/refresh (whatever it will be called) for all the files by 1-4 clicks but without to iterate all the files and to open them one by one.

It is only for display of the contents of the files (last version). I'm not interested to see in offline branches, commits and so on.

**Comment by k0shk0sh** [comment]
@mo45555 alright, thanks for your reply and explanation.

**Comment by beshology** [comment]
Why not an option to download the zip file for the whole repo

**Comment by mo45555** [comment]
For the first time (new here), I use my laptop + xender + DroidEdit. Not comfortable.
Follow your suggestion, I tried now Chrome + RAR + DroidEdit and it is better, thanks.
Still, if i can avoid all of this by the app, it will be nicer.

**Comment by kutsan** [comment]
"Won't be happen in near future."
*Completed after 2 days*
Damn @k0shk0sh!

**Comment by k0shk0sh** [comment]
@kutsan :p, no fancy work, just download the selected branch files & thats it :p

**Comment by Kimi-Arthur** [comment]
Hi @k0shk0sh , how should I use the downloaded file? And do I still need to be offline completely (which doesn't sound reasonable)?

**Comment by k0shk0sh** [comment]
@Kimi-Arthur you could find the downloaded file in sdcard/fasthub/repoName and from there you can do whatever you want with the file :). 
In order for FastHub to store the file offline, you'll need to at least open the file once from the app and then it will be available offline.

**Comment by Kimi-Arthur** [comment]
@k0shk0sh so the downloaded zip file won't help me to view them in the app?
That feature will actually be cool...

**Comment by k0shk0sh** [comment]
that feature will eventually come but only when I fullfill my goal. after project cards which is next release very soon, only then I'll be doing the stuff I think that are good to have @Kimi-Arthur

**Comment by Kimi-Arthur** [comment]
Awesome! Looking forward to that!

**Comment by Jefwillems** [comment]
Any updates on this feature? I've been using this app for a while now, and just bought the pro version because i love it. Although i'd love to have pinned repositories readily available to browse even though i have no internet available.

**Comment by k0shk0sh** [comment]
I'm reworking on the while in mind offline first. So please be patient, its gonna take some time but its worth the waiting trust me

**Comment by Jefwillems** [comment]
Great to hear! Thanks!

**Comment by vitaly-zdanevich** [comment]
Still no offline!
