### ISSUE TITLE
Menu on mobile not working

### ISSUE THREAD

**Issue by weblegs** [k0shk0sh/FastHub#1692]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5)  
---

 Menu on mobile not working

**Comment by k0shk0sh** [comment]
whaat?

**Comment by geomach** [comment]
@k0shk0sh to fast to furius

_Sent from my W2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by geomach** [comment]
@k0shk0sh to fast to furius

_Sent from my W2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
