### ISSUE TITLE
Back

### ISSUE THREAD

**Issue by YWatchman** [k0shk0sh/FastHub#1695]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5S)  
---

When using the left arrow from a repo it goes to home instead of the search results.

ik@yvanwatchman.eu

**Comment by k0shk0sh** [comment]
Use device back button.

**Comment by k0shk0sh** [comment]
Who says its an issue? This is how Android navigation works, use the device back button to return where you were, use arrow key to navigate deeply in the hierarchy. Which after repo there is nothing but home.
