### ISSUE TITLE
Cancel milestone creation crash

### ISSUE THREAD

**Issue by michalwa** [k0shk0sh/FastHub#1696]
**FastHub Version: 4.6.7**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG X power  
---

 Pressing this button causes the app to crash:

![](https://i.imgur.com/dkThV0f.png)

**Comment by yakov116** [comment]
@michalwa where does this happen?

**Comment by michalwa** [comment]
Can't reproduce this anymore either... Must've been a very special case or some temporary bug.
