### ISSUE TITLE
Add bookmark / favorite repository option

### ISSUE THREAD

**Issue by mo45555** [k0shk0sh/FastHub#170]
Add option to save repositories (not my own) for quick access

**Comment by kutsan** [comment]
GitHub already has star option for that? Is that not enough?

**Comment by mo45555** [comment]
Thanks for the quick! response.

Ok, I checked it now, I tried to star few repositories, but then I couldn't
see them anywhere in the app. I check (under my user) starred, gist,
followers and following.

**Comment by kutsan** [comment]
They should be seen under your profile starred tab. Can you check it out again? If you are sure about successfully starred and doesn't seem under starred tab, maybe a bug going on.

**Comment by mo45555** [comment]
You are right. I clicked on the eye instead of the star :). Now it is
working well.

Many thanks,
Mosh
