### ISSUE TITLE
Submitting reply on PR comment error

### ISSUE THREAD

**Issue by startailcoon** [k0shk0sh/FastHub#1700]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

 When I try to reply to a requested change comment on a PR that I have submitted I recieve an error stating 'Not Found'.

**Comment by k0shk0sh** [comment]
Org repo?

**Comment by yakov116** [comment]
@k0shk0sh did we ever add org detection? I think its about time.

**Comment by startailcoon** [comment]
https://github.com/bitshares/bitshares-ui/pull/1383

**Comment by yakov116** [comment]
@startailcoon did your org add permissions for fasthub?...

**Comment by startailcoon** [comment]
@yakov116 Not what I know of. I didn't know it had to since it works for most other actions performed on the repository.

**Comment by yakov116** [comment]
@startailcoon please read the FAQ
