### ISSUE TITLE
Tab to view repository milestone

### ISSUE THREAD

**Issue by mmoayyed** [k0shk0sh/FastHub#1703]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

 In the set of tabs available to a repository, it's unclear how one might be able to review the milestone defined. Clicking on a link to milestones correctly shows the page in the app but in the absence of the link, it's difficult to navigate there. 

Expose a tab or some other option to review the milestones please.

**Comment by k0shk0sh** [comment]
Milestones are accessible from prs or issues screen and I have no intention to work on this. You are free to open Pr
