### ISSUE TITLE
Refreshing pinned repositories should update repository stats

### ISSUE THREAD

**Issue by mmoayyed** [k0shk0sh/FastHub#1705]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

 If I simply swipe down on the list of pinned repositories, the repository data isn't actually refreshed. Number of stars or forks etc remain the same and I have to navigate to the repository first to have it refresh before I come back to the pinned list of repositories to see updated stats.

**Comment by k0shk0sh** [comment]
That refresh isn't making any API calls for you to update the stats you will have to update the repo and only then I'll update it in the local db. Other than that this is the intended behavior.
