### ISSUE TITLE
Suggestion: Add token to header

### ISSUE THREAD

**Issue by AllanWang** [k0shk0sh/FastHub#1707]
I don't know where you saw that github can't access private repo data, but you can authorize requests by either sending your token in the header or as a query argument. Given that you are using retrofit, it would probably be easiest to add an interceptor to pass a token from a shared pref or something. That way, if it changes, you won't need to make a new retrofit instance.

See api documentation (if you are still using v3): https://developer.github.com/v3/#authentication

This will also resolve #1387, #1330, #1185

I can also confirm that this is possible and not limited to browser cookies, because you can download private releases with OctoDroid

**Comment by k0shk0sh** [comment]
Care to PR?

**Comment by k0shk0sh** [comment]
exactly, the problem with private things is GitHub API issue related not to FastHub. 

but thanks for your time tho.

**Comment by AllanWang** [comment]
Please keep this open. This is definitely not a Github API issue as other apps have successfully done it. I will do some more testing on my own time. And if possible, please update the slack invite link and add me so I can better communicate if there are other issues.

**Comment by k0shk0sh** [comment]
slack link is updated, however Im on vacation so I wont be able to answer you immediately but please PM me and i'll answer you asap.

**Comment by AllanWang** [comment]
I had a look at the code. I added the `kotlin-kapt` plugin since that is deprecated with an error level in Android Studio 3.1, and [Travis wouldn't build properly](https://travis-ci.org/AllanWang/FastHub/jobs/362817879#L1806). Either Lombok isn't updated, or other dependencies are missing, which makes it very hard for any other developer to test. If I ever solve this issue externally, I'll link back, but for now it doesn't seem possible to contribute, as there are too many incompatibilities.

**Comment by k0shk0sh** [comment]
Then don't update kotlin to latest and there should be no prob to compile the app. I'm aware of that and once I have time I'll fix it

**Comment by yakov116** [comment]
@AllanWang take a look at graphql

**Comment by AllanWang** [comment]
I've seen graphql, but being able to use the explorer doesn't mean it is fixed in Fasthub. The issue lies in the authentication; I'm pretty sure the path is the same

**Comment by k0shk0sh** [comment]
Have u tested this? Enterprise and private they mean different things. Enterprise doesn't specifically means private but rather public to all who has access to that Enterprise domain.

**Comment by AllanWang** [comment]
Haven't tested. I'm on Android studio 3.1 now and your project is incompatible. It does make sense since this is the same way you get tokens as the interceptor

**Comment by k0shk0sh** [comment]
@AllanWang  I'm on AS 3.2 alpha 8 and it compile fine, as I said,  don't upgrade kotlin lib and everything should compile fine.
