### ISSUE TITLE
Bought the "All" but nothing works from pro feature

### ISSUE THREAD

**Issue by adamluzsi** [k0shk0sh/FastHub#1711]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** NewBund  
- **Brand:** vernee  
- **Model:** Active  
---

**Comment by k0shk0sh** [comment]
Please logout and login again 😅

**Comment by adamluzsi** [comment]
Sorry about that, after the second login, plus starting to buy again, it found the previous order and terminated the purchase and applied the upgrade! :)

Thank you! Keep up the good work @k0shk0sh ! :)
