### ISSUE TITLE
How-to move notes and issues between project columns

### ISSUE THREAD

**Issue by adamluzsi** [k0shk0sh/FastHub#1712]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** NewBund  
- **Brand:** vernee  
- **Model:** Active  
---

 I would like to know how to move notes or issues between a project (as the repository project feature) columns.

For example, from "Todo" to "in progress" 

Kind regards
Adam L

**Comment by cozyplanes** [comment]
I don't think it will be implement soo

**Comment by adamluzsi** [comment]
But is it in plan to do so ?
Because I thought fasthub support GitHub project feature, it will be a good replacement of Trello .
So I'm hoping that eventually it will be implemented :(

**Comment by k0shk0sh** [comment]
@adamluzsi not in the near future tho, I don't have much of a time to work on new features right now but once I get time I'll work on them.

Btw: I was in Switzerland this weekend, I must say, its beautiful and amazing. 😊

**Comment by adamluzsi** [comment]
@k0shk0sh yes, the weather was amazing!

I'm grateful for you to consider this as a future User Story in your backlog!

Until than, I wait patiently! :)

**Comment by adamluzsi** [comment]
Dear @k0shk0sh,

Did you had any time perhaps to think about this problem ? 

Please feel no pressure or anything like that from my question, I'm just interested.

Kind regards
Adam

**Comment by k0shk0sh** [comment]
I'm in the middle of rewriting the app, all depend on when I reach the project feature and if there is a bettet api right now than the one before ;)

**Comment by adamluzsi** [comment]
@k0shk0sh All the best for the rewrite! Then I wait for it. :)

**Comment by adamluzsi** [comment]
I'm closing the issue. If the feature implemented, that is awesome, 
but I'm happy with the GitHub mobile view as well.

Cheers
