### ISSUE TITLE
Changelog display bug (kinda) 

### ISSUE THREAD

**Issue by knackrack615** [k0shk0sh/FastHub#1715]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

 When clicking on a github link after the app has updated it loads the github repo and shows the changelog on top as expected, however you can't close the changelog (you will get a blackscreen if you do)

A simple app restart fixes it, but i thought its something minor to be looked at sometime

**Comment by k0shk0sh** [comment]
is it the changelog that appears from bottom or in center of screen?

**Comment by knackrack615** [comment]
Bottom one, although when i clicked the back button it tried to load something on the center but the text was cut off
