### ISSUE TITLE
Profile pic / thumb not updated

### ISSUE THREAD

**Issue by Gustl22** [k0shk0sh/FastHub#1719]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S5 LTE-A  
---

The profile pictures / thumbnails are not updated, if they're changed. Only when deleting app data, the new picture is fetched. Maybe can add functionality with swiping down and refresh.

![screenshot_20180410-162018](https://user-images.githubusercontent.com/18537755/38563785-fa437962-3cdd-11e8-8bc2-9c35e9ff2585.png)

![screenshot_20180410-162333](https://user-images.githubusercontent.com/18537755/38563797-ffe431cc-3cdd-11e8-8f8f-7d0a93edb7a9.png)

**Comment by yakov116** [comment]
@Gustl22 please search the issues

**Comment by Gustl22** [comment]
Ok sorry, I used search funtionality only on open issues, but didn't get a result. Thought it never got mentioned. :see_no_evil:
