### ISSUE TITLE
Created branch branch_name shows as created author/repo

### ISSUE THREAD

**Issue by Ra1da35ma** [k0shk0sh/FastHub#172]
On the feed section of the App,

When a ninja creates a new branch of the repo, it shows as if the ninja created the repo.

Its supposed to indicate that a branch was created and then name the branch.

for example the below,

> **omoprodigi** created branch `temp001` at **Ra1da35ma/familypro**

shows as

> **omoprodigi** created **Ra1da35ma/familypro**

**Comment by kutsan** [comment]
Thanks for reaching out. Hopefully this will be fixed in future releases.

**Comment by Ra1da35ma** [comment]
You welcome

Good Job
