### ISSUE TITLE
Starring a repo feels unresponsive / laggy

### ISSUE THREAD

**Issue by mammuth** [k0shk0sh/FastHub#1724]
Hi,

When starring repositories it looks like the UI thread is shortly blocked until the star turns blue / the starring is done.
Depending on the connectivity the lag is longer or shorter. 

**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7 Edge  
---

**Comment by k0shk0sh** [comment]
That's not possible since the request is done in a service and in background, can't produce what you mentioned and I don't think any has ever encountered that 🤔

**Comment by mammuth** [comment]
Strange. I'll try to better understand possible causes / situations of the behavior.
