### ISSUE TITLE
Scrolling is buggy when battery saver mode is enabled.

### ISSUE THREAD

**Issue by rigrassm** [k0shk0sh/FastHub#1729]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

 When battery saver mode is enabled, it becomes difficult to scroll down due to the header area hiding animation. It will keep snapping back to the top of you don't scroll down fast enough.

**Comment by maracuja-juice** [comment]
Where in the app do you have this behaviour?

**Comment by rigrassm** [comment]
Sorry, should have specified that. I'm seeing it in the repo view while
trying to scroll the readme.

**Comment by yakov116** [comment]
@rigrassm please search the issues.

Thanks for your feedback
