### ISSUE TITLE
Clearing notifications

### ISSUE THREAD

**Issue by krodriguez** [k0shk0sh/FastHub#173]
there isn't a way to mark notifications as read unless you go to each one. The button in the top right clears the list and shows "no data available"

**Comment by k0shk0sh** [comment]
It does marking all of them as read, but since GitHub does not provide a one shot readAll, we do it manually in a service, so give it few seconds depending on ur network to mark them all as read :).

**Comment by k0shk0sh** [comment]
I'll be adding a notification for that right now and will be released in Today's version.
