### ISSUE TITLE
Wrong color of code

### ISSUE THREAD

**Issue by dmig** [k0shk0sh/FastHub#1731]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 4  
---

 See screenshot. 'filter-method' must have black face

**Comment by k0shk0sh** [comment]
This is theming related and does not have to do anything with GitHub
