### ISSUE TITLE
Code citation isn't formatted

### ISSUE THREAD

**Issue by dmig** [k0shk0sh/FastHub#1732]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 4  
---

 See screenshot

**Comment by dmig** [comment]
![Screenshot](https://dmig.tk/Screenshot_2018-04-13-19-12-45-446_com.fastaccess.github.png)

**Comment by dmig** [comment]
Test on this comment: https://github.com/quasarframework/quasar/issues/1924#issuecomment-380759026

**Comment by dedepete** [comment]
Duplicate of #1033.
