### ISSUE TITLE
Add Following and Followers Count

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#1734]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

 It would be good if the followers and following count is shown in the profile section.
Thanks

**Comment by k0shk0sh** [comment]
Sorry but no api.

**Comment by abhijithvijayan** [comment]
Fine
