### ISSUE TITLE
Cannot using share sheet button.

### ISSUE THREAD

**Issue by kid1412621** [k0shk0sh/FastHub#1735]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5T  
---

 I want to send a file from another app via share-sheet.But I click the button,nothing happen.

**Comment by yakov116** [comment]
@kid1412621 how exactly would you like to share a file?

@k0shk0sh is there a way to limit it to only links?

**Comment by k0shk0sh** [comment]
When clicking share it only shares link and it works everywhere I'm not sure what the OP problem is as it seems everything working fine for me.

**Comment by yakov116** [comment]
@k0shk0sh when sharing a file FastHub shows us

**Comment by kid1412621** [comment]
@yakov116 @k0shk0sh Sorry for the delay.
I want to upload a file to my repo via FastHub.
There is no way to upload a file stored in the device from FastHub,so I managed to using share sheet in the Solid Explorer to transport file to FastHub. But it seems that it doesn't work out.

**Comment by k0shk0sh** [comment]
its no possible to upload a file since github has no API for that.
