### ISSUE TITLE
Purpose of buttons on the release details view

### ISSUE THREAD

**Issue by janisozaur** [k0shk0sh/FastHub#1742]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

What is the purpose of "Cancel" and "OK" buttons when viewing details of a release? What exactly am I confirming here?

![](https://i.imgur.com/r4jSh4W.jpg)

**Comment by k0shk0sh** [comment]
You ain't confirming anything but rather closing the Dialog

**Comment by janisozaur** [comment]
How is closing with "Cancel" different from closing with "OK"?

**Comment by k0shk0sh** [comment]
I think I answered this question in my previous answer.

**Comment by janisozaur** [comment]
Not really, as I still do not understand the difference between those two buttons.

**Comment by yakov116** [comment]
@janisozaur there is none...
