### ISSUE TITLE
[Feature Request] Open GH links in FastHub

### ISSUE THREAD

**Issue by yochananmarqos** [k0shk0sh/FastHub#1744]
Could FastHub support opening GitHub links natively like OctoDroid does? I searched the issues but didn't find anything related.

**Comment by yakov116** [comment]
@yochananmarqos its a phone setting. It sure does. Look under app defaults

**Comment by yochananmarqos** [comment]
Derp. Usually when a new app is installed that can handle links, Android prompts again even if a default is set. It didn't when I installed FastHub with OctoDroid already installed. For reference for anyone stumbling across this, I had to set FastHub to open GH links and disable it for OctoDroid.
