### ISSUE TITLE
Numbers without context on release download view

### ISSUE THREAD

**Issue by janisozaur** [k0shk0sh/FastHub#1746]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

When listing possible download for a release, there are some numbers listed next to the files, but they don't seem to be connected to the files in any way.

![screenshot_20180418-085454](https://user-images.githubusercontent.com/550290/38916272-02f4967c-42e7-11e8-912e-385dca51bad8.jpg)

I could hazard a guess this could be a file size, if there was any unit next to them or if the numbers related to the file size in any way, but none of that holds true.

The release from screenshot is this one: https://github.com/discordapp/discord-rpc/releases/tag/v3.2.0

**Comment by yakov116** [comment]
@janisozaur those numbers are the download count

**Comment by janisozaur** [comment]
This is interesting, I was not aware GitHub exposed such information, as it is not available through the release page. It is certainly not obvious from the attached screenshot either, can you add some sort of hint explaining that number?

I realise `download count` would be far too long to put there, but perhaps `⭳#` (or the bold arrow you can see in the background) would provide enough of hint?

**Comment by yakov116** [comment]
@janisozaur Dont see how that would help

**Comment by Bettehem** [comment]
I think there maybe should be a button at the bottom of the dialog with a text eg. "more info", which would then inform the user about the numbers

**Comment by yakov116** [comment]
@bernaferrari You would understand that dl = Download Count?

**Comment by Bettehem** [comment]
@yakov116 maybe, or "dl's" which could be short for downloads?
Or would the info button be a better solution?
