### ISSUE TITLE
Tags should be shown on release view

### ISSUE THREAD

**Issue by janisozaur** [k0shk0sh/FastHub#1747]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

While most releases will contain a version number or something akin to that, there are some projects that do not follow that practice. While it can be argued it is the issue with the way upstream project does releases, having a tag displayed on a release view would improve the interface, as you could easily navigate to the linked sources.

![screenshot_20180418-090851](https://user-images.githubusercontent.com/550290/38916553-2bce15d6-42e8-11e8-93e5-400e807cf8c8.jpg)

Example project that is affected: https://github.com/discordapp/discord-rpc

**Comment by k0shk0sh** [comment]
#1491
