### ISSUE TITLE
Can't remove reactions once added.

### ISSUE THREAD

**Issue by JamesCoyle** [k0shk0sh/FastHub#1748]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note4  
---

 Tapping on an already added reaction just keeps incrementing the count rather than removing the reaction.

**Comment by yakov116** [comment]
@JamesCoyle Go out of the issue and go back
See #524
