### ISSUE TITLE
Profile picture not updated in profile section 

### ISSUE THREAD

**Issue by vishalprabha** [k0shk0sh/FastHub#1749]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi 5 Plus  
---

 I changed my profile picture on my GitHub profile through my laptop. This is the first time I added it and it's not reflected in the app, whereas when I click on the profile pic icon(on the app) it opens a web activity and shows the picture.

**Comment by k0shk0sh** [comment]
Its fixed and please search for issues before posting :)

**Comment by vishalprabha** [comment]
May I know the issue number of the duplicate.

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/lZYP8mZ.jpg)

**Comment by k0shk0sh** [comment]
I'm not obligated to post the issue number on every single duplicated issue its hassle to do so, the community should understand that and try to help by any means (search issues)
