### ISSUE TITLE
Feature Suggestion: Language Statistics

### ISSUE THREAD

**Issue by michalwa** [k0shk0sh/FastHub#1752]
**FastHub Version: 4.6.7**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG X power  
---

 On the GitHub web page you can view how much of the code has been written in which language (in percentage). It would be convinient to have that in the app.

**Comment by yakov116** [comment]
@michalwa There is no api for that

Thanks for your feedback
