### ISSUE TITLE
Some translations not working even they exist

### ISSUE THREAD

**Issue by TurboProgramming** [k0shk0sh/FastHub#1753]
**FastHub Version:** 4.6.7
**Android Version:**  7.0
**Device Information:**  
- MANUFACTURER: 
- BRAND: Samsung
- MODEL: Samsung Galaxy Note5
---
Hello,

Recently I was changing some Turkish translations and I switched my app language to Turkish and saw that some phrases weren't working (they were still English). I checked the translations at:

https://github.com/k0shk0sh/FastHub/blob/development/app/src/main/res/values-tr/strings.xml

and they existed.

For example, on the home screen (I mean the feed), the phrase "opened a pull request" translation exist on the translation file but it was not translated including the bottom navigation bar.

Currently I'm not able to send screenshots but you probably got me.

**Comment by yakov116** [comment]
@TurboProgramming the nav bar is not translated on purpose. We don't want to translate those strings.

**Comment by TurboProgramming** [comment]
@yakov116 What about the feed? "opened a pull request", "commented on issue" etc.
