### ISSUE TITLE
Icon change suggestions

### ISSUE THREAD

**Issue by TurboProgramming** [k0shk0sh/FastHub#1754]
FastHub Version: 4.6.7
Android Version: 7.0
Device Information:

MANUFACTURER:
BRAND: Samsung
MODEL: Samsung Galaxy Note5
---
Hello,

I would like to give some suggestions regarding some navigation drawer item icons.

Currently, the icons of the items "Profile" and "Organizations", located on the navigation drawer is styled as outlined.

But I suggest you that they would look better the non-outlined one.

Let me send you the assets here to get all of your opinions regarding this:

Current icons of Profile and Organization tabs:

![account-outline](https://user-images.githubusercontent.com/17576065/39093975-0d6d04e8-4631-11e8-8983-7a1c37611c4a.png)
![account-multiple-outline](https://user-images.githubusercontent.com/17576065/39093976-0ebb8f72-4631-11e8-9778-18d0f35b315b.png)

New icons I suggest:

![account](https://user-images.githubusercontent.com/17576065/39093992-431fc7ba-4631-11e8-9ace-88fd7ea65105.png)
![account-multiple](https://user-images.githubusercontent.com/17576065/39093993-43aced2a-4631-11e8-8810-6c6c1c07418f.png)

Also, besides these, I have a few more suggestions regarding icons.

1. Pinned tab icon to be changed with the pin icon

![pin](https://user-images.githubusercontent.com/17576065/39094003-744a1494-4631-11e8-8b68-82d33eeb0173.png)

2. Gists tab icon to be changed with the code icon

![code-tags](https://user-images.githubusercontent.com/17576065/39094010-900f51f8-4631-11e8-96c1-77236872f783.png)

or with the bulleted list icon

![format-list-bulleted](https://user-images.githubusercontent.com/17576065/39094014-99b35a9c-4631-11e8-83e7-ace60b0f325d.png)

What do you think about these?

If you also don't have time changing these if you like, I can do it for you and open a PR when it is done. 

But before that, I need your opinion regarding it, waiting what you think about these.

**Comment by yakov116** [comment]
@TurboProgramming  we have to be careful as some older phones crash when using certain svg files.

**Comment by yakov116** [comment]
@TurboProgramming we have to be careful as some older phones crash when using certain svg files.

**Comment by k0shk0sh** [comment]
Thanks for the suggestion, however I don't see the point of changing the icons as first the user already got used to them, secondly, these icons are taken from Google material design. 

Thanks tho.

**Comment by TurboProgramming** [comment]
@yakov116 Thank you for responding.

The thing I want to only change those icons to the new suggestions as only these icons are outlined compared to others. That won't cause any crash as we're only changing the icons from the same thing to the same thing, only a different version.

**Comment by TurboProgramming** [comment]
@k0shk0sh Thank you for responding.

The icons you're using and I suggested are already Material Design. They should be :)

The poing I want to come is to make all icons the same. Having some icons non-outlined and some outlined makes them ugly.

What do you think?

**Comment by TurboProgramming** [comment]
See #1777
