### ISSUE TITLE
Enable ads is not saved

### ISSUE THREAD

**Issue by mo45555** [k0shk0sh/FastHub#176]
When reopening the app, it is disabled again.
BTW, where the ads is? 

One more thing, when I open today the app, I asked again for the credentials (in both my phone and my tablet). Then, it was not asked again (tried to restart).  As a read user (with meaningless account), I hope that credentials will not be asked offend.

**Comment by kutsan** [comment]
Could you please give us additional info about your phone? Because when I tested, ads works fine.

FastHub's log-in system changed with v1.2.0 update. That's why was requested again.

**Comment by mo45555** [comment]
Phone - LG3
Tablet - Lenovo Tab2 A10

As for the login, My tablet still in 1.1.1 version and i was required to login today (All the balloons appeared as if it's the first time)

**Comment by k0shk0sh** [comment]
@mo45555 then maybe its due to the fact, that u faced a problem in v1.1.1 where u can't have multiple logins. please update ur tablet to 1.2.0 so you could be able to login and of course if GitHub said you are an authorized user, the app will log you out immediately.

**Comment by k0shk0sh** [comment]
Any updates on this issue or we just close it?

**Comment by mo45555** [comment]
Nothing changed.
In both my phone (LG3, v1.2.0) and my tablet (Lenovo Tab2 A10, v1.1.1) I don't see ads and after exit and enter the app again, the ads option is deselected.

**Comment by k0shk0sh** [comment]
@mo45555 thats really weird, nothing fancy FastHub is doing over there for this scenario. I can't produce it tbh.

**Comment by k0shk0sh** [comment]
this should be fixed in ef25469 as we don't restart app anymore.
