### ISSUE TITLE
OAuth app not working

### ISSUE THREAD

**Issue by Strikerrr** [k0shk0sh/FastHub#1760]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

 The app was called "Dependabot" and when trying to sign in with github it redirected me to the browser in Fasthub and then it said "authentication error."

Relevant code from developer of Dependabot:

```js
const queryParams = queryString.parse(window.location.search);
const storedState = window.sessionStorage.getItem("dependabot.oauthState");
if (storedState !== queryParams.state) {
  this.setState({ stateError: true });
}
```

Relevant Screenshot of the error: ![Image](https://i.imgur.com/AFNC6z7.jpg)

**Comment by k0shk0sh** [comment]
You need to clear default in your app settings from FastHub
