### ISSUE TITLE
App restarted out of nowhere

### ISSUE THREAD

**Issue by Strikerrr** [k0shk0sh/FastHub#1762]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

 Without warning, whilst I was doing some editing on a file in my repo because I realised I needed to add something quickly, your app restarted out of nowhere and I lost 30+ lines of code all hand typed in 10 minutes. Could you please advise as to what went wrong? Obviously I can't recover this code, but I'd highly like to make sure this won't happen again.

**Comment by Strikerrr** [comment]
To add, this was during the process of creating a new file.

**Comment by cozyplanes** [comment]
When your phone decides to kill fasthub because your phone is a serial killer, fasthub has no choice but to shut down
