### ISSUE TITLE
Settings restore function not working correctly

### ISSUE THREAD

**Issue by Leo1003** [k0shk0sh/FastHub#1763]
**FastHub Version:**  4.6.7
**Android Version:**  8.0.0
**Device Information:**  
- MANUFACTURER: asus
- BRAND: asus
- MODEL: ASUS_Z012DA
---
After I restored my previous settings from the backup.json file, all settings are reset to the default. When I tried to access the setting page, the application crashed!  
After reading the source code, I thought that I found the source of this problem.  
  
app/src/main/java/com/fastaccess/ui/modules/settings/category/SettingsCategoryFragment.java:354
```java
if (savedPref != null && !savedPref.isEmpty()) {
    for (Map.Entry<String, ?> stringEntry : savedPref.entrySet()) {
        PrefHelper.set(stringEntry.getKey(), stringEntry.getKey());
    }
}
```
It seems like that it's a typing error.

**Comment by yakov116** [comment]
@Leo1003 pr?

**Comment by yakov116** [comment]
@Leo1003 thanks!
