### ISSUE TITLE
README.md display

### ISSUE THREAD

**Issue by thtang** [k0shk0sh/FastHub#1765]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HTC  
- **Brand:** htc  
- **Model:** U11  
---

 Couldn't display readme.md file in the folder of repo :smile:

**Comment by yakov116** [comment]
@thtang link?

**Comment by thtang** [comment]
https://github.com/thtang/DLCV2018SPRING/tree/master/hw3

**Comment by k0shk0sh** [comment]
Did u click on the link of the readme?![](https://i.imgur.com/nKWqoNO.jpg)
