### ISSUE TITLE
Missing Repository 

### ISSUE THREAD

**Issue by mkxxx** [k0shk0sh/FastHub#1767]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S3  
---

I'm missing my current Repository i only can see my old one

**Comment by dedepete** [comment]
But you don't have any on this account. 🤔  
If you can't see your private repositories, please, go through the FAQ within the app.
