### ISSUE TITLE
Not automatic dismiss notification

### ISSUE THREAD

**Issue by alorma** [k0shk0sh/FastHub#177]
Hi.

I see that opening a notification deletes it from github.com.

Could you add an option to change this?

Sometimes i just see issues or pr on phone, but i want to "keep it for later", so i see on Github.com

**Comment by k0shk0sh** [comment]
By deleting you mean mark it as read am I right? 

Isn't the All option provide you to see these  notification? and as far as I know, even opening the email can actually mark your notification as read.

**Comment by alorma** [comment]
I know, but i like to open in my phone and then review on my mac.

Yes, github marks them as read just by opening email, but that's my problem:

I get a notification, i open it from app when i'm at bus, and think, ok i will review it later.

Once i get home, i want to see in the app the notifications i had before.

If them are marked as read, i has to remember which notification it was.

PS: could you bundle notifications by repo?

**Comment by k0shk0sh** [comment]
Alright Alorma, I'll have an option in settings screen to disable reading a notification upon clicking on it. even tho I'm against that, but I'll be happy to give you something in return :). 
for the notification categories, there is an issue opened for it. I'll make that happen too very soon.
