### ISSUE TITLE
Which login method should I use?

### ISSUE THREAD

**Issue by knpk13** [k0shk0sh/FastHub#1770]
I didn't find this in the FAQ so I'm asking here. Whats the difference between basic authentication, access token, and ouath, and which one should I use?

**Comment by yakov116** [comment]
@knpk13 Google is your friend

**Comment by yakov116** [comment]
@knpk13 Google is your friend

**Comment by jedie** [comment]
> Google is your friend

What a useless answer.

It would be good to add this in FAQ and add links to:

https://github.com/settings/tokens
https://blog.github.com/2013-05-16-personal-api-tokens/
