### ISSUE TITLE
Pull requests referenced in other contexts are marked as "referenced this in issue"

### ISSUE THREAD

**Issue by PiwwowPants** [k0shk0sh/FastHub#1771]
**FastHub-Libre Version: 4.6.6**  
**Android Version: P (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 When referencing a pull request from another context (e.g. an issue or a different pull request) marks on the page that the item was "referenced this in issue". I believe this should state "referenced this in pull request" followed by the number like normal.  

A screenshot can be added if more context is needed. I can definitely see about pushing a change if agreed.

**Comment by yakov116** [comment]
@PiwwowPants it's an api issue. But sure if you would like to send a pr with a fix go ahead!

**Comment by PiwwowPants** [comment]
Gotchya. That's unfortunate. If it's not too much of a hack I'll look at it but if it's an API issue it'll probably come down to checking the URL for context and that might be painful or inconsistent depending on how consistent GitHub URLs are.

**Comment by yakov116** [comment]
@PiwwowPants when we switch to GraphQl it will be fixed

**Comment by yakov116** [comment]
@PiwwowPants Closing this as we are working on switching. (There is also another issue open)
