### ISSUE TITLE
Large files are very laggy until menu button is pressed

### ISSUE THREAD

**Issue by cg505** [k0shk0sh/FastHub#1774]
**FastHub Version:** 4.6.7   
**Android Version:** 8.1.0 stock
**Device Information:** 
- MANUFACTURER: LG   
- BRAND: Google   
- MODEL: Nexus 5x   
---

When opening large files, I experience significant lag in the file view. Good examples can be found in the gradlew and LICENSE files in the root of this repository. gradlew opens, but scrolling is very choppy and difficult to control. LICENSE appears to open quickly, but there is delay before the contents are actually displayed. Scrolling is essentially impossible as it seems there is one frame rendered every 5-10 seconds. The OS dialog box asking if you want to kill the non-responsive app comes up a lot. Larger files essentially hang on opening. In small files (<1 kB) the lag is not noticeable.

What's weird is that problem can be resolved by tapping the menu button in the upper-right hand corner. After tapping the button, scrolling is perfectly smooth.

I'd be happy to try and provide any other useful info.

**Comment by cg505** [comment]
I found #946 but it does not include the info about the menu button.

**Comment by qw-in** [comment]
Could be way off but  `onScrollChanged` [here](https://github.com/k0shk0sh/FastHub/blob/development/app/src/main/java/com/fastaccess/ui/modules/repos/code/prettifier/ViewerFragment.java) looks fishy

**Comment by k0shk0sh** [comment]
That doesn't have to do with scroll lag, its ur device webview and Android webview in general as described in the other issue mentioned

**Comment by cg505** [comment]
The issue has disappeared as mysteriously as it came :/ 

Everything is back to normal for me, are you still experiencing this @qw-in>

**Comment by yakov116** [comment]
@cg505 You updated your webview?

**Comment by cg505** [comment]
I can't be certain but it seems pretty unlikely since the most recent version of FastHub (for which this bug was filed) was released more recently than the most recent version of webview, as far as I can tell.

**Comment by cg505** [comment]
I found https://bugs.chromium.org/p/chromium/issues/detail?id=831248 which was fixed in the most recent version of webview but it seems unlikely to be the issue since it seems like it would cause a full deadlock instead of just severe lag. Also, it doesn't explain the thing with the menu button. Anyway, doesn't seem to make sense to spend any more time on this unless it reappears.

**Comment by qw-in** [comment]
Nope, my phone is still struggling. Going to update to Oreo soon anyway though so I'll check back in after that
