### ISSUE TITLE
Regarding icons

### ISSUE THREAD

**Issue by TurboProgramming** [k0shk0sh/FastHub#1775]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note5  
---

Hello,

I want to request an icon change for the send feedback button. That's also requested on the material Design guidelines.

![](https://i.imgur.com/XD0pIaS.png)

![](https://i.imgur.com/5jN8iFk.jpg)

**Comment by k0shk0sh** [comment]
PR?

**Comment by TurboProgramming** [comment]
@k0shk0sh I'll open a PR ASAP. I'll also change the report a problem string to send feedback as it opens an activity with the title send feedback.

**Comment by TurboProgramming** [comment]
See #1777
