### ISSUE TITLE
Offline Issues

### ISSUE THREAD

**Issue by johnml1135** [k0shk0sh/FastHub#1779]
**FastHub Version:** 4.6.7

Is it possible to view all the issues and other repository information offline?  I see the functionality for downloading the actual files but not the issues.  Is this a planned feature?  Is there some other app that will allow that functionality (none that I have found so far).

**Comment by yakov116** [comment]
@johnml1135 nope it is not on the road map.

Also please leave all the info intact when creating an issue.
