### ISSUE TITLE
Ambiguous "error connecting to server" error when approving PR

### ISSUE THREAD

**Issue by alukach** [k0shk0sh/FastHub#1780]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

When trying to approve a PR, I get an "Error connecting to server" error. I'm unsure why this would be and also don't know how to find out more about the error.

This issue is more about the fact that I can't discover the cause of the error than the error itself. This may just be a lack of knowledge about the app on my part, I'm a new user.

**Comment by yakov116** [comment]
@alukach does the pr require approval?

**Comment by alukach** [comment]
@yakov116 No, it does not appear to require approval before merging.

**Comment by yakov116** [comment]
@alukach org? Can you provide a link?

**Comment by alukach** [comment]
This is a private repo within the github.com/cadasta organization.

**Comment by k0shk0sh** [comment]
Then login with access token or read faq from app

**Comment by alukach** [comment]
@k0shk0sh Yes, I was logged in (how else would I be able to see the PR in the first place?)  The FAQ has nothing related to this issue.  I think this was closed prematurely.

**Comment by k0shk0sh** [comment]
Hmmm, you ignored to read my whole comment. 
LOGIN WITH ACCESS TOKEN OR READ THE FAQ RELATED TO ORGANIZATION AND PRIVATE REPOS.

I hope the capital letters takes your attention.

**Comment by alukach** [comment]
@k0shk0sh I'm a bit taken aback by your response.  Obviously I read your entire comment, I stated that I was unable to find anything in the FAQ related to the issue. The FAQ States: "Why can't I see my Organizations either Private or Public ones?" My issue was not around viewing organizations, it was about approving a pull request and thus not obviously related to that section of the FAQ.  

You are correct that the issue is regarding granting access to the organization.  Thanks for helping me resolve the issue, however I think we could have done it without your theatrics.

**Comment by k0shk0sh** [comment]
> Yes, I was logged in (how else would I be able to see the PR in the first place?)

Obviously my reply was based on this, I was 💯 sure you weren't logged in with access token because otherwise we wont have to talk about this. 


Anyway, I'm glad you solved your prob and sorry for my rudeness.
