### ISSUE TITLE
Issues with PR

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [k0shk0sh/FastHub#1781]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

 I try to modify the reviewers / people assigned / or review a PR of a repo which is in an organisation.
It fails every time. I fully have the rights to perform these actions and can perform them using the Web interface.

Do you know where it could come from?

**Comment by yakov116** [comment]
@DEKHTIARJonathan did you read the faq?

**Comment by DEKHTIARJonathan** [comment]
Oh I didn't see there were a FAQ.
I requested access for the organisation. I will close the issue as soon as I know if it works or not.

Thanks a lot for your rapid answer,

A wonderful application!
