### ISSUE TITLE
md TOC的内联连接无法支持

### ISSUE THREAD

**Issue by JiongZhu** [k0shk0sh/FastHub#1785]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI6  
---

 When I click the TOC link in the md document, I can't jump to the corresponding position in the.

**Comment by yakov116** [comment]
@JiongZhu what?!
