### ISSUE TITLE
Render jupyter notebooks

### ISSUE THREAD

**Issue by damelLP** [k0shk0sh/FastHub#1787]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7 Edge  
---

 GitHub does a wonderful job of statically rendering jupyter notebooks. It would be a create extension if this could also be included within FastHub.

**Comment by yakov116** [comment]
Thanks for your feedback.

Please search the issues
