### ISSUE TITLE
Return from a issue does not jump back to search as expected

### ISSUE THREAD

**Issue by RubenKelevra** [k0shk0sh/FastHub#1789]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5T  
---

 When the users search for an issue and tap on a search result, and then press 'back' the app does not do the expected jump back to the search results, but to the main page of the repository. This makes no sense, please change the app behavior that a press on 'back' always jump back to the previous opend page.

**Comment by k0shk0sh** [comment]
Please use the phone back button and not the arrow key. 

Also please search before posting new issues. thanks.
