### ISSUE TITLE
[Enhancement] Catagorize notifications by repository

### ISSUE THREAD

**Issue by tom-corwin** [k0shk0sh/FastHub#1795]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

 The notification panel is just a chronological list of notifications, and might I add that when you get alot of notifications from many repositories, it's hard to see just one repository' notifications.

**Comment by k0shk0sh** [comment]
There were issued opened like this, simple I can't do that since we have pagination foe the notifications.

**Comment by tom-corwin** [comment]
Whoops, my bad! Didn't even look into closed issues :sweat_smile:
