### ISSUE TITLE
Add a homebutton along with top arrow button

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#1796]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

 Clicking the Back arrow button on top left goes to home(good but still). At times it's frustrating to go back to where you were. If there was a home button along with the back arrow button that redirects to home and the making the back arrow button move only a level up would be awesome.

**Comment by k0shk0sh** [comment]
That's why you should use your device back button for navigation back and toolbar back button to navigate deep.

**Comment by abhijithvijayan** [comment]
Sometimes people don't use the phone's nav button

**Comment by k0shk0sh** [comment]
https://developer.android.com/training/implementing-navigation/ancestral
