### ISSUE TITLE
Saying Cannot open Binary file(like in github webpage) instead of showing scrambled letters is better

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#1797]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

See this file
 https://github.com/abhijithvijayan/FOSS-lab/blob/master/Gambus3/calculator/.gambas/FMAIN

through fasthub and any other browser

**Comment by k0shk0sh** [comment]
How would I know that this is a binary file?

**Comment by abhijithvijayan** [comment]
How do Github website find that as a binary file!

**Comment by k0shk0sh** [comment]
No idea, I don't work for GitHub.

**Comment by abhijithvijayan** [comment]
Still

**Comment by k0shk0sh** [comment]
We are not chatting, could we save each other time and reply with proper sentences? Its open source, you could find out yourself and make a pr or tell me your finding and I'll do my best to fix it. Other than that I'll leave this open until someone figure this out.

**Comment by abhijithvijayan** [comment]
Thanks and I'll look on it myself

**Comment by abhijithvijayan** [comment]
[Closing]
