### ISSUE TITLE
How can I add more organizations?

### ISSUE THREAD

**Issue by jiapei100** [k0shk0sh/FastHub#1798]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR  
- **Model:** Honor V10  
---

  How can I add more organizations ?

**Comment by k0shk0sh** [comment]
not sure what do you mean, but u can create orgs via github website.
