### ISSUE TITLE
slack invite doesn't work

### ISSUE THREAD

**Issue by dtzWill** [k0shk0sh/FastHub#1802]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

 Following in-app link to join fasthub slack doesn't work, LMK if more information needed.

Please fix, or remove it if it's dead and won't be coming back :(.

Thanks!

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/YTEGi2p.jpg)

**Comment by dtzWill** [comment]
Dishonor on me and my family. Sorry! Meant well! :)
