### ISSUE TITLE
Subscribe to issue, PR, etc.

### ISSUE THREAD

**Issue by dtzWill** [k0shk0sh/FastHub#1803]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

 Feature request.  Pinning somewhat addresses this need, but it'd be great to be able to subscribe/unsubscribe to issues and such from the app (instead of having to open with browser to do so).
If this is already possible and I'm blind I apologize :).

**Comment by k0shk0sh** [comment]
Thanks for opening the issue, but please do search issues before opening new ones. This has been discussed plenty of times :)

**Comment by dtzWill** [comment]
Eep, sorry about that! Thanks for quick response!
