### ISSUE TITLE
Issue filtering not working when `is:open` is not in the search term

### ISSUE THREAD

**Issue by AllanWang** [k0shk0sh/FastHub#1805]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** 3  
---

 Both open and close tabs display the same thing when `is:open` isn't part of the search term

**Comment by yakov116** [comment]
@AllanWang repo link?

**Comment by AllanWang** [comment]
I've updated the description since I left out my search term. Basically if you aren't explicitly searching for opened (or closed I guess) issues, no sorting will be done.

![screenshot_20180515-181433](https://user-images.githubusercontent.com/6251823/40094202-7b382efc-587a-11e8-844b-85ffb789c1d2.jpg)

**Comment by yakov116** [comment]
So the issue is by search not by open and closed issue...

**Comment by AllanWang** [comment]
Correct, but I think it makes sense to either keep them sorted or to merge the two columns into one if it won't be filtered

**Comment by yakov116** [comment]
#1728
