### ISSUE TITLE
Problems with reactions on the issues tab

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#1808]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

 ![emoji](https://i.imgur.com/AuwUHTO.png) 

To get this click each one, one time randomly.

After going back and coming forth, Can't take the reaction off unless with 2 consecutive clicks.

**Comment by yakov116** [comment]
@abhijithvijayan thanks for your feedback.  Please search the issues.

**Comment by abhijithvijayan** [comment]
:grinning:
