### ISSUE TITLE
Dark Mode Issue

### ISSUE THREAD

**Issue by shgaurav** [k0shk0sh/FastHub#181]
First of all I love the dark mode! However i am noticing issues related to dark mode where the background color of certain layout within the app is not changing and stays white. it is kind of weird because sometimes it is fine but some times when I go into issues section or commit section, it shows a white background. Here is screenshot: 
https://drive.google.com/file/d/0B7eMBI2WGcwMMWRzVzY5UkM2NEU/view?usp=drivesdk

**Comment by k0shk0sh** [comment]
I noticed that as well when u commented on the issue and opened the apl #180

**Comment by shgaurav** [comment]
oh shit...my bad didn't notice your issue was referring to the same bug. Just thought i would let you know. you want me to close this one?

**Comment by k0shk0sh** [comment]
@shgaura its okay tho. i appreciate your help and please don't stop :)

**Comment by dikiaap** [comment]
@k0shk0sh I just mentioned you in here. That dark theme is great, but the cyan colors is too bright. Could you make it even little bit darker or change to another color? Some colors reference: http://colorhunt.co

**Comment by k0shk0sh** [comment]
the color had changed 😀. it will be in Sundays version. 😎

**Comment by dikiaap** [comment]
Nice! glad to hear that.
