### ISSUE TITLE
Notification bar is wrong height

### ISSUE THREAD

**Issue by CKH4** [k0shk0sh/FastHub#1810]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** ZTE  
- **Brand:** ZTE  
- **Model:** ZTE A2017U  
---

 In the drawer the status bar is calculated as the wrong height. I have a modified status bar height but the app doesn't reflect the actual height. The offset is wrong so the status bar overlaps the profile picture.

**Comment by k0shk0sh** [comment]
The app doesn't calculate any height of the status bar and therefore it wont work if you have custom status bar.

**Comment by CKH4** [comment]
You may want to consider changing this. New phones no longer have a set size for their status bars. The essential phone has one with a height of 28 I believe, while other phones are as small as 20. There is no set size anymore.
