### ISSUE TITLE
Feeds issue

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#1811]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

 Displays the currently non existing activity feeds even though it's not being still displayed at github website 

![](https://i.imgur.com/exL9xSW.jpg)

**Comment by abhijithvijayan** [comment]
![](https://i.imgur.com/GWcoIu7.png)

**Comment by abhijithvijayan** [comment]
See the second feed
The org was deleted hours ago and it still shows the feed

**Comment by k0shk0sh** [comment]
Please, verify on GitHub API first before blaming FastHub :'(.
