### ISSUE TITLE
Application crash when I edit PR's title

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [k0shk0sh/FastHub#1815]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

 I encounter an issue with the application, when I try to edit the title of a PR, the application crash.

I follow these exact steps :
1. Access the PR I want to edit.
2. Enter in edit mode using the pencil icon => edit.
3. I click on the text title that I want to modify. And the **application crash immediately**.

I have tested, if instead of modifying the title I want to modify the content of the PR, the app is running fine.

I have tried to clear memory of the app, restart my phone, and reinstall the app. It's still crashing

**Comment by BBloggsbott** [comment]
Works fine on my device
**FastHub Version: 4.6.7**
**Android Version: 7.0**
**Device Information**
* **Manufacturer:** Samsung
* **Model:** Galaxy J5 Prime

I followed the steps given by you. 
Modifying the title of the PR worked fine and the app did not crash.

**Comment by k0shk0sh** [comment]
Can't produce it, probably rom specific issue. I have seen so many crashes from certain oem related to textviews and unfortunately I can't fix it as its internal.
