### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by joeking82** [k0shk0sh/FastHub#1816]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

 I paid for Enterprise but can not use all themes now my email is fkkinright@gmail.com thanks

_Sent from my Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Hi, enterprise is different form pro version they are totally separate modules, its stated under each section. I'm
