### ISSUE TITLE
Is possible to view the repository if on a issue?

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#1817]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

I would like to know if, for example, when you visit an issue from a mail reply I can directly access to the original repository, it would be useful
Maybe I'm not seeing this and there is but if it's not it would be nice to implement

**Comment by k0shk0sh** [comment]
Click on back button from  the toolbar and it will take u to the repo, always use that button to go back deeply.
