### ISSUE TITLE
Feed not updating correctly

### ISSUE THREAD

**Issue by mattwright324** [k0shk0sh/FastHub#1818]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S9+  
---

 I'm signed into my GitHub account and my feed displayed several new repos someone I was following created. `<User> **created** repository **at** <User>/<Repo>`. This is normal and my feed on the website reflected the same thing. However, a week later the person that created those repos either deleted them or made them private, I'm not sure. They disappeared from the website feed but still show up on my feed here. Trying to access any of them from FastHub makes an error `Not found`. I've tried signing out, clearing app cache & data, then signing back in but those feed items still come back.

**Comment by k0shk0sh** [comment]
If all of this didn't help then the API is returning them therefore I can't really help, your best bet would be contacting GitHub about it and tell them that they have bug in their API (P.S: there are many)
