### ISSUE TITLE
Http 422 Unprocessable entity 

### ISSUE THREAD

**Issue by barcaluxman** [k0shk0sh/FastHub#182]
When I try to login using my id from login Screen I get http 422 unpronounceable entity  
When I try to login using browser I get 404 error 
![screenshot from 2017-03-22 15 57 01](https://cloud.githubusercontent.com/assets/6260014/24192930/ac2b34b6-0f18-11e7-9af0-45e29dc9fb23.png)
![temp](https://cloud.githubusercontent.com/assets/6260014/24192931/ac2f21e8-0f18-11e7-9491-ed1bab8e4825.png)

P.S. I built it myself and trying to run in emulator

**Comment by k0shk0sh** [comment]
are you using production or build it yourself?

**Comment by barcaluxman** [comment]
I built it myself

**Comment by k0shk0sh** [comment]
you seem like you building yourself.
could you please follow the instructions in contribution.md where you have to get github clientId & also secrect to be able to build FastHub & login.

**Comment by k0shk0sh** [comment]
owh yeah & also you have set these values in `debug_gradle.properties` I'll update the contribution guide for more details.

**Comment by barcaluxman** [comment]
Sorry my bad did not notice the contribution.md and yeah waiting for your update in contribution guide
