### ISSUE TITLE
Wiki view on private repositories 

### ISSUE THREAD

**Issue by ryanley** [k0shk0sh/FastHub#1825]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7  
---

 Hello,

Just downloaded your app and I like it so far but I noticed that it glitches out says "difficulty communicating with server" when you try to access the wiki of a private repo.

Thanks!

**Comment by yakov116** [comment]
@ryanley please read the FAQ

Thanks for your feedback
