### ISSUE TITLE
Not showing notification

### ISSUE THREAD

**Issue by bensh4** [k0shk0sh/FastHub#1829]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Micromax  
- **Brand:** Micromax  
- **Model:** A102  
---
I'm using free version. But isn't showing any notification on comments or any..! Thanks

**Comment by k0shk0sh** [comment]
Change the interval in settings screen.


Please search issues before posting
