### ISSUE TITLE
Dark theme not applied when coming from another app

### ISSUE THREAD

**Issue by KabbAmine** [k0shk0sh/FastHub#183]
As the title said, when for example opening fasthub from f-droid, the dark theme is not applied.

**Comment by k0shk0sh** [comment]
Hello @KabbAmine I have just pushed an update for that in 1.3.2 awhile ago, its already available in the playstore. #180 #181

**Comment by KabbAmine** [comment]
Oh, I just had now a notification about the update.

Very good app by the way, thanks :+1:
