### ISSUE TITLE
License not recognized

### ISSUE THREAD

**Issue by giogandola98** [k0shk0sh/FastHub#1830]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi 5 Plus  
---

 I've bought the pro app but it does not work

**Comment by k0shk0sh** [comment]
I have replied to your email so please check ur email. 

Also, please search for issues to get answers faster, because there some issues like
