### ISSUE TITLE
Share image to create a bug

### ISSUE THREAD

**Issue by teolemon** [k0shk0sh/FastHub#1836]
Use case: I often take screenshot of the open source Android app I'm taking care of. I want to create issues out of screenshots. 

Current workaround: Nowadays, I get the screenshot synchronized online through my photo albums, download it, create the bug on GitHub and reupload it.

I'd like to be able to "Share to Fasthub" and be able to select the project I want to create the bug into (from my pinned repository list), and be able to add text and a description.

**Comment by k0shk0sh** [comment]
you could create an issue and select the image you like from within FastHub and upload it either via comment, issue, PR or editing either one. all of these possibilities are available you just gotta scroll the icons above the text field where you write (its scrollable and has more options than you see).
