### ISSUE TITLE
There's no searching for repositories

### ISSUE THREAD

**Issue by Toshimichi0915** [k0shk0sh/FastHub#1837]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** MATE 9  
---

 
I just searched for "Bukkit" then "Showing the max API allows" appeared

**Comment by Toshimichi0915** [comment]
![](https://i.imgur.com/3jddDE1.jpg)

**Comment by Toshimichi0915** [comment]
In addition, this always appear whatever I searched for

**Comment by k0shk0sh** [comment]
There is a search limit so don't exceed it. Also I'm using the search api for other elements within the app and this would cause it as well. 

I got nothing to do about it tho.
