### ISSUE TITLE
Avatar wants to touch the status bar

### ISSUE THREAD

**Issue by KuroiNekoWitch** [k0shk0sh/FastHub#1838]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** ANE-LX3  
---

Hi, I opened this issue as you requested in Twitter 🤔

I hope the info will help you :)

_Enviado desde mi ANE-LX3 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
thanks, but can you please edit the title to more descriptive title? also, it would be awesome to attach the image in here

**Comment by KuroiNekoWitch** [comment]
![img_20180531_071741](https://user-images.githubusercontent.com/20273059/40779947-d1e5d44e-64a4-11e8-94c4-2c1138c9d0a5.jpg)

BTW, When I tried to edit the title, the app crashes... I need to touch first the Description area for later edit the title.


Thanks :octocat:
