### ISSUE TITLE
All Downloads remain with 'Downloading file...' note

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#1839]
**FastHub Version: 4.6.6**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

 All downloads remain with 'Downloading file...' note even after completion.
Yalp handles this by putting package name when completed.
![](https://i.imgur.com/E86nySW.png)
However fasthub keeps note 'Downloading..' even when done.
![](https://i.imgur.com/WtswBiZ.png)
Not sure how this is handled differently.
Normal browsers keeps that id empty:
![](https://i.imgur.com/4nlGrkm.png)

Small annoyance only, though.

**Comment by k0shk0sh** [comment]
downloading releases always going to end up in download while downloading files from repos will result into downloading them into their (repoName folder). 
its working as intended.

**Comment by rancidfrog** [comment]
Misunderstand.
In Downloads app, the tag still remains even after download completed:
 ![](https://i.imgur.com/Dk3gSOz.png) 
Nothing to do where file is being downloaded.

Maybe you pass string "Downloading file..." to system downloader upon download request.
But, this string needs to be updated or cleared upon download completion.

Such as,
![](https://i.imgur.com/JsCdPkN.png)

The issue is that when download with fasthub, all files have "downloading file.." tag, even after completed.

**Comment by rancidfrog** [comment]
@k0shk0sh
To be precise,
This is the string:
https://github.com/k0shk0sh/FastHub/blob/2901771e5a0bdc711371c8aacf1e71f2182a4871/app/src/main/res/values/strings.xml#L163
```
<string name="downloading_file">Downloading file…</string>
```
Which you are using here: https://github.com/k0shk0sh/FastHub/blob/81b044cf12725b4988962d6fe85287072ce58cb4/app/src/main/java/com/fastaccess/provider/rest/RestProvider.java#L114
```
request.setDescription(context.getString(R.string.downloading_file));
``` 
The issue is that this description stays even after download completes.
So, it is not an accurate description.
Maybe not needed, as when it is downloading it already has "in progress" automatically.
So, the description you are adding "Downloading file…" is wrong place or needs to be changed when download completes.
