### ISSUE TITLE
Feature request : Pin repos on home page

### ISSUE THREAD

**Issue by raisedadead** [k0shk0sh/FastHub#184]
It would be interesting to see if __repos can be pinned for quick access__ .

For instance as a maintainer, I would be able to quickly check issues and PRs instead of scrolling and searching through my forks and stars.

P.S: Awesome app BTW. Seems to be the best one by far.

**Comment by k0shk0sh** [comment]
good idea,  I'll try and make by this weekend update.

**Comment by Rainer-Lang** [comment]
This feature I often missed. Glad that's coming. 😀

**Comment by kutsan** [comment]
cc @mo45555

**Comment by raisedadead** [comment]
Thanks for considering. Count me in if you would need help in pre-release testing.

**Comment by dikiaap** [comment]
@k0shk0sh In screen 480x854px has little glitches. The pinned button on repository page will be disappear.

![screenshot_2017-03-27-15-50-51 01](https://cloud.githubusercontent.com/assets/8542502/24348652/a5060da4-1306-11e7-9dc4-90e55667f542.png)

**Comment by kutsan** [comment]
@dikiaap Thank you for that but could you please open another issue? So we can track them easily.
