### ISSUE TITLE
Poss BitBucket Integration

### ISSUE THREAD

**Issue by Stevieag** [k0shk0sh/FastHub#1851]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** oneplus  
- **Model:** One  
---

 Do you think connection to bitbucket is possible? I use this app for github and hoped to continue but the need to use bitbucket has arose.
It would be nice after purchasing this app that I could continue to use it.

_Sent from my One using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dedepete** [comment]
Please, do search through the Issues next time. This question has been answered dozens times. 
GitHub and BitBucket have different API so it is not possible.
