### ISSUE TITLE
Rapidly reacting causes votes to increment/decrement by more than 1

### ISSUE THREAD

**Issue by akkatracker** [k0shk0sh/FastHub#1853]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---
If you rapidly react to people's comments, the counter can do weird stuff:
 https://youtu.be/zJgUg2azTVg

**Comment by dedepete** [comment]
Please, search through the Issues next time. Thanks.

**Comment by akkatracker** [comment]
I did search, but didn't realise I'd have to go all the way back to last
year.

I've only just noticed this, and thumbs up a lot of stuff.

Thanks for the quick response.
