### ISSUE TITLE
Search results doesn't include repo's of Organisations

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#1860]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

 Close it if it's an api issue

Search for sitepoint-editors/pwa-retrofit gave me no results

**Comment by k0shk0sh** [comment]
<img width="1245" alt="screen shot 2018-06-09 at 18 47 20" src="https://user-images.githubusercontent.com/960767/41194024-95d9da04-6c15-11e8-8ad3-8a8a6d04cd55.png">
