### ISSUE TITLE
Can not create secret gist

### ISSUE THREAD

**Issue by danielkrupinski** [k0shk0sh/FastHub#1863]

**Comment by k0shk0sh** [comment]
GitHub doesn't allow that abymore.

**Comment by danielkrupinski** [comment]
I mean this:![](https://i.imgur.com/QGjQiut.png)

**Comment by k0shk0sh** [comment]
https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/


That's for public ones tho sorry, so not sure about whats ur prob.

**Comment by danielkrupinski** [comment]
My prob is I can't create secret gist (private) in FastHub but you can do it in browser (see screenshot above - golden/yellow button on the left).

**Comment by k0shk0sh** [comment]
Left button 
![](https://i.imgur.com/PRcEoXX.jpg)

**Comment by danielkrupinski** [comment]
It opens blog.github.com

**Comment by nyuszika7h** [comment]
@k0shk0sh You misunderstood the issue. Creating secret gists (authenticated) via the API is still very much possible, just set `public=false` (which is in fact the default). It is not possible to create a secret gist from FastHub, clicking the incognito icon just takes me to blog posts which is about a completely different thing: anonymous (unauthenticated) gists, which may still be public.

https://developer.github.com/v3/gists/#create-a-gist
