### ISSUE TITLE
Add "Find in file" feature

### ISSUE THREAD

**Issue by Melvin-Abraham** [k0shk0sh/FastHub#1868]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OPPO  
- **Brand:** OPPO  
- **Model:** CPH1859  
---

 Please add "**Find in file**" feature. That would help developers a lot when traversing through large files. Regular expression support would be great.

**Comment by yakov116** [comment]
Duplicate of #967 
Thanks for your feedback
