### ISSUE TITLE
Battery Saver Mode makes main repo pages hard to drag scroll

### ISSUE THREAD

**Issue by mttmllns** [k0shk0sh/FastHub#1869]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

When battery saver mode is on animations are disabled which makes the auto minimizing action bar really hard to use. When drag scrolling the page you have to fling to get a scroll to actually take.

**Comment by yakov116** [comment]
@mttmllns please search the issues. 

Thanks for your feedback

**Comment by haugerbr** [comment]
@yakov116 you probably need to put some similar issue automatic search in the app otherwise people not familiar with GitHub will just submit duplicate issues.

**Comment by yakov116** [comment]
@haugerbr pr?

**Comment by dedepete** [comment]
@yakov116 there's no need in PR since @k0shk0sh is working on the update.

**Comment by yakov116** [comment]
@dedepete he is rewriting the app. This would be an additional feature
