### ISSUE TITLE
Feeds

### ISSUE THREAD

**Issue by Yamaford** [k0shk0sh/FastHub#1870]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto X Pure Edition  
---

 I have 4 feeds that are on the feed tab that I'd like to remove and add other projects to the feeds tab. I can't figure it out.

**Comment by yakov116** [comment]
@Yamaford What?
