### ISSUE TITLE
Getting API request failures

### ISSUE THREAD

**Issue by haugerbr** [k0shk0sh/FastHub#1871]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 The last few times using the app I have been getting API rate limit exceeded. It's frustrating especially since I supported the app by paying for the PRO features.

**Comment by yakov116** [comment]
@haugerbr We dont control Githubs api
