### ISSUE TITLE
Could not input the file name when editing

### ISSUE THREAD

**Issue by AceAmy** [k0shk0sh/FastHub#1877]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---
when I want to rename my file , the input box couldn't be touched so that I could not rename it .  
hope to fix it dear developer! 
 ![](http://upload-images.jianshu.io/upload_images/1260259-115180ea5654526c.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1080/q/50)

_Sent from my OnePlus5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by arpitjindal97** [comment]
Lol, can't test the fix for Premium feature

The problem seems to be in this line

**Comment by AceAmy** [comment]
@arpitjindal97 so.... change the false value in L63 into true? :joy:

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 OnePlus5 发送_

**Comment by yakov116** [comment]
@arpitjindal97 you can test it. Debug includes them for free
