### ISSUE TITLE
User profile picture is not updated

### ISSUE THREAD

**Issue by christopher-dG** [k0shk0sh/FastHub#1879]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3  
---

 I changed my profile photo long ago but my previous one still shows in the app.

**Comment by yakov116** [comment]
@christopher-dG please search the issues.

Thanks for your feedback

**Comment by christopher-dG** [comment]
Ok, will do. I think it would be nice to make the repo more accessible from the sidebar so that I could do that, instead of just being directed to open an issue.

**Comment by christopher-dG** [comment]
Or even just a message linking to the issue tracker before submitting the issue.

**Comment by yakov116** [comment]
@christopher-dG Yup I agree, Has been brought up a few times.

@k0shk0sh can we put this on the V5 Agenda?
