### ISSUE TITLE
File download doesn't work correctly

### ISSUE THREAD

**Issue by jlelse** [k0shk0sh/FastHub#188]
When I go to the release tab and try to download a file from a release, for example test.apk, it download the file but not with the correct file name. The file name is "Downloading file...". This seems to be wrong right? 🤓

**Comment by jlelse** [comment]
I can't even find the file in any folder on my device. Just the Downloads app (the system app) shows me the file with mentioned name.

**Comment by kutsan** [comment]
Looks like there is a problem. Thanks for reporting.

**Comment by k0shk0sh** [comment]
Well, beside the name, it works as expected, otherwise FastHub has to ask for READ & WRITE permissions, the name has been fixed, but I don't think having the extra permissions just for this. 

i'm open to suggestions tho.

**Comment by jlelse** [comment]
Great that it seems to be fixed. The main issue was, that it wasn't possible to open the downloaded file afterwards, like when downloading an APK, you weren't able to install it.
