### ISSUE TITLE
Unable to select different themes

### ISSUE THREAD

**Issue by Wason1** [k0shk0sh/FastHub#1887]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 Unable to select different themes in settings > themes.

**Comment by arpitjindal97** [comment]
Can't replicate the issue. Have you tried in some other phone?

**Comment by Wason1** [comment]
It is working now on the same smart phone. Thanks.
