### ISSUE TITLE
Landscape layout in portrait

### ISSUE THREAD

**Issue by matthewdias** [k0shk0sh/FastHub#189]
the app is in landscape layout while I have my phone in portrait. Nexus 5x, using the smallest UI scale option.

**Comment by kutsan** [comment]
Thanks for feedback. Please provide a screenshot with your Android version.

**Comment by k0shk0sh** [comment]
Well, this is something out of the app league, we can't do anything about it as far as I know, if you have clue how to solve it, please let me know otherwise I guess this issue should be closed.

**Comment by matthewdias** [comment]
https://i.imgur.com/BMFtwnQ.png

I'll see what I can find.

**Comment by kutsan** [comment]
Looks not bad actually. :D

**Comment by k0shk0sh** [comment]
this seems like tablet mode and not landscape (both looks alike), which is correct since ur phone has density that android categories it as a tablet and loads tablet resources for your phone. I guess this issue has no solution

**Comment by matthewdias** [comment]
@kutsan modals are really wonky :smile:

![](https://i.imgur.com/eJZtkRh.png)

**Comment by k0shk0sh** [comment]
@matthewdias this just proves my previous answer assumption. android thinks your phone is a tablet. therefore, we can't do anything unless if you could find something about it.

**Comment by matthewdias** [comment]
@k0shk0sh I haven't seen this behavior in any other apps that have tablet layouts, though.

**Comment by matthewdias** [comment]
apparently the `large` qualifier is deprecated. https://developer.android.com/guide/practices/screens_support.html#DeclaringTabletLayouts

**Comment by k0shk0sh** [comment]
@matthewdias wait, am I using that 🤔🤔🤔, alright then. it should be fixed within today release. thanks for finding out.
