### ISSUE TITLE
Unable to post reviews to pull requests

### ISSUE THREAD

**Issue by NyanKiyoshi** [k0shk0sh/FastHub#1893]
**FastHub Version:**  4.6.7-debug
**Android Version:**  7.0
**Device Information:**  
- MANUFACTURER: Motorola Mobility  
- BRAND: Motorola
- MODEL: Moto G4  
---

### How to reproduce
1. Create a review to a pull request;
2. Try to submit it;
3. It should fail.

### Demo
[![demo.gif](https://i.imgur.com/FY5Kr7l.gif)](https://i.imgur.com/FY5Kr7l.mp4)

### Expected behavior
1. Be able to post;
2. Not be asked to add another message before submitting as it's not needed;

**Comment by yakov116** [comment]
@NyanKiyoshi closing as duplicate
