### ISSUE TITLE
Embedded code are malformed on issues/pull requests

### ISSUE THREAD

**Issue by NyanKiyoshi** [k0shk0sh/FastHub#1894]
**FastHub Version:**  4.6.7-debug
**Android Version:**  7.0
**Device Information:**  
- MANUFACTURER: Motorola Mobility  
- BRAND: Motorola
- MODEL: Moto G4  
---

### How to reproduce
1. Embed a permalinked code from a repository;
2. It should not show the correctly.

### Screenshot

[![demo](https://i.imgur.com/3Nbpu1ul.png)](https://i.imgur.com/exViqPx.png)

### Example snippet

https://github.com/k0shk0sh/FastHub/blob/4dad56f416dce4f513c19cb20e3d32419c26b4a3/.travis.yml#L3-L11

### Expected result
Having the code snippet showed just like any file on github or any other diffs.

**Comment by dedepete** [comment]
#1033
