### ISSUE TITLE
Found a few bugs and feedback

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#19]
In 2 minutes of usage I already found 3 bugs. Yay!

I screenshotted them in this album, unfortunately the order is reversed and I can't change it on mobile: http://imgur.com/a/icKeH

1. The app icon in the splash screen is stretched beyond the top 
2. "In 24 Minutes" (What does that time even mean?)
3. Double loading indicators in all swipe-to-refresh views

Additionally I found that when deleting a gist the gist list doesn't get refreshed and still shows the one you just deleted.
The preview button in the markdown editor has an empty tooltip.

Moving over to the general feedback:

One thing I immediately noticed is that _everything_ is monospace which looks really ugly. In the Reddit thread you said it should be Roboto iirc, but if so it's not.
Then you could replace the toolbar icons in the markdown editing screen I'm in right now with icons.
You could also include a little tutorial which explains where which thing is and how others work. I just noticed that you can actually scroll the lower markdown tobar to get image shortcuts and such.

I'll update this list if I find any more stuff.

**Comment by wasdennnoch** [comment]
Another thing: I can't edit the issue.

And it shows "in 1 hour" as the creation time, it should take into account the timezone.

**Comment by wasdennnoch** [comment]
I can't edit anything yet, so I guess it'll be implemented soon.
I can still "manage" the tags for this issue although I'm not permitted to (gives a 403).

**Comment by k0shk0sh** [comment]
@wasdennnoch Thanks for your feedback. i really loved your detailed explanation plus the screenshot. I will be working on fixing/adding these stuff and let you know about the process. 

thanks again.

**Comment by k0shk0sh** [comment]
In (time) is actually when the repo last updated, I have did some guides yesterday and still doing throughout the app. next version will have them.

**Comment by k0shk0sh** [comment]
Some of above, are fixed. please do check the last version of FastHub when you get an update. 
I'll keep this open until i fix or add the other things.

**Comment by wasdennnoch** [comment]
The splash screen, label management, app font and tutorials seem to be fixed now. I noticed some other things though:

In the \"you have notifications\" dialog clicking either the button or the layout does nothing other than collapsing the status bar.

It looks like the file titles in a commit view are fixed to 2 rows without ellipsizing (however that's spelled).

The text \"No newline at end of file\" could be replaced with an icon like on the Github website.

Maybe the wrong timestamps are related to my device language being set to EN/US while I'm living in DE (which probably is the reason), I'll try changing it.

**Comment by k0shk0sh** [comment]
I'm driving right now, but gonna keep this here to not forget it, I think I know why the date is wrong is due to the rawOffset I'm adding to the UTC time, while your time is UTC. I will comment later on the others as i need some more info. 
thanks

**Comment by k0shk0sh** [comment]
@wasdennnoch thanks again for your feedback. I'm abit lost to be honest, I really appreciate your feedbacks and love to have more from you, however I wanna ask you for a favor, could you separate these bugs, enhancement & features in separate issue so I can keep track of them & have them organized to easily close each one of them. 

again, Thank you very much.

**Comment by wasdennnoch** [comment]
Can do that.

**Comment by k0shk0sh** [comment]
great mate, I really do appreciate your efforts in helping FastHub and specifically me. 
Thanks

**Comment by wasdennnoch** [comment]
I think I got all of them separated now, will close this one.
