### ISSUE TITLE
How to update from clang 6.0.0 to clang 6.0.1 or latest

### ISSUE THREAD

**Issue by hcltrajesh** [k0shk0sh/FastHub#1901]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A6000  
---

 Hello,
I have to update my current version of clang to latest. Should I redownload the sources from GitHub and run all the steps or is there a better way to do that 
Please help.

**Comment by yakov116** [comment]
@hcltrajesh stop spamming
