### ISSUE TITLE
Organisation not working

### ISSUE THREAD

**Issue by paperbenni** [k0shk0sh/FastHub#1917]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4)  
---

 One of my organisations is not showing up, if I search it manually, I don't have any perms via the app, works fine in the browser.

**Comment by yakov116** [comment]
> I don't have any perms via the app,

So why should it work?

**Comment by paperbenni** [comment]
Okay, I didn't know that you have to grant the app permission for organisations manually, figured it out now.
