### ISSUE TITLE
Not reading my org

### ISSUE THREAD

**Issue by Sammaye** [k0shk0sh/FastHub#1921]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6  
---

 You have org read rights but for some reason I cannot see my org on here

**Comment by k0shk0sh** [comment]
Did you try to login with access TOKEN?

**Comment by Sammaye** [comment]
Ah I see, no, ok, I'll try that

**Comment by Sammaye** [comment]
Hmm, it won't let me login with access token, I have put the same
credentials I did for oauth login but it just says it failed.

**Comment by Sammaye** [comment]
Oh, sorry ignore, my bad, I need to fix my password manager at some point
