### ISSUE TITLE
Pictures 

### ISSUE THREAD

**Issue by Susanxxx** [k0shk0sh/FastHub#1926]
**FastHub Version: 4.6.7**  
**Android Version: 5.0 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S5  
---

 How do I uploaded my pictures 

_Sent from my Galaxy S5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@Susanxxx what when where?

**Comment by Susanxxx** [comment]
Hello
