### ISSUE TITLE
Too many results when searching?

### ISSUE THREAD

**Issue by Glinkis** [k0shk0sh/FastHub#1929]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5T  
---

 When I try searching for something more general, like `error => console.error`, the app gives me an error saying it gets too many results.

**Comment by TurboProgramming** [comment]
GitHub API has a limit for searches. When you search for something general, too many results come up and GitHub API outputs that it can't give more results to FastHub.

So this is not an issue, this is a limitation from GitHub itself.

---

@k0shk0sh Can be closed.
