### ISSUE TITLE
Can't approve PR

### ISSUE THREAD

**Issue by spacekookie** [k0shk0sh/FastHub#1934]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5T  
---

 Whenever I try to approve a PR it just says it couldn't communicate with the server. Not sure what's going on there, if its a but or a legitimate server outage on githubs part but communicating this could probably be done better

**Comment by k0shk0sh** [comment]
Is the pr part of a repo in an org? Because I assume it is, then please login via access token or grant access to FastHub in ur org.

Also please refer to the faq within the app.
