### ISSUE TITLE
When someone starts following you, the feed doesn't show that activity.

### ISSUE THREAD

**Issue by manankalra** [k0shk0sh/FastHub#1940]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

 Although, it is visible on the web version.

**Comment by manankalra** [comment]
You can use [GitMate](https://gitlab.com/gitmate/open-source/gitmate-2), if you want such tags to be automatically added.

**Comment by k0shk0sh** [comment]
Good idea. Thanks
