### ISSUE TITLE
Feature Request: Filter Feed for specific repository

### ISSUE THREAD

**Issue by startailcoon** [k0shk0sh/FastHub#1955]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

 The feed for recent changes and updates  to repositories that I have are very good.

What I lack is a way to filter out one specific repo, since I'm subscribe to several that I don't wish to see when I manage said repo.

**Comment by yakov116** [comment]
@startailcoon please search the issues.

Thanks for your feedback

**Comment by startailcoon** [comment]
Searching for "feed" in issues results in three records, none related to this. Not sure why you say it's duplicate without linking to it.
