### ISSUE TITLE
Viewing trending repos on mobile

### ISSUE THREAD

**Issue by Psypher9** [k0shk0sh/FastHub#1959]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** Verizon  
- **Model:** Galaxy S7  
---

After selecting a repo to view from the list of trending repos, I hit the back button at the top of the screen thinking it will take me back to the list of trending repos I just came from; however, I am taken back to my FastHub home screen.

**Comment by k0shk0sh** [comment]
Use phone back button to go back where you were and toolbar backbutton to navigate deep in the hirachy
