### ISSUE TITLE
Locking Conversation in issue does not use proper name

### ISSUE THREAD

**Issue by JRoy** [k0shk0sh/FastHub#1963]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

 When you lock an issue in fasthub, it does not submit a user for the action and GitHub files the action under @ghost

**Comment by yakov116** [comment]
Its an API issue.
