### ISSUE TITLE
Gists not saving

### ISSUE THREAD

**Issue by jcaprice** [k0shk0sh/FastHub#1969]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 Gists aren't saving for me when I edit them and press the check mark

**Comment by JediBurrell** [comment]
Can not replicate.
Also Pixel 2 on Android P.

**Comment by GeorgeWL** [comment]
@jcaprice we need more detail.

For any bug report the more detail about the steps taken and how to repeat the issue the better.

Some stuff only happens in very specific conditions that we might know to even check for.

_Sent from my Pixel 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
