### ISSUE TITLE
Richer Commit Diffs

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#197]
Can there be a full screen viewer for diffs? Also with an option to view the whole file with the diffs inline?

**Comment by Rainer-Lang** [comment]
+1

**Comment by kutsan** [comment]
Also +1.

**Comment by k0shk0sh** [comment]
+1 as well

**Comment by eygraber** [comment]
@k0shk0sh any update on this?

**Comment by k0shk0sh** [comment]
I'm Abit struggling here and there and can't really work much due to health issues, so I'm focusing more into small stuff currently, I'll try and estimates this tomorrow after work and see if it can be done tomorrow. 
> sorry tho.

**Comment by eygraber** [comment]
@k0shk0sh all good, feel better!

**Comment by k0shk0sh** [comment]
this commit 4c41bb8 fixed this

**Comment by k0shk0sh** [comment]
@eygraber you'll be able to download, share, copy link & view the file in a full screen, plus you could do these as well from full screen, but instead the file will open in code viewer.

**Comment by eygraber** [comment]
@k0shk0sh I think this is a good start, but is it possible to show the diff in the code viewer? Also adding line and review comments, but I guess that belongs to another issue 😁

**Comment by k0shk0sh** [comment]
@eygraber sure, but not so sure why code viewer tho!

**Comment by eygraber** [comment]
@k0shk0sh wrapping, line numbers, maybe expandable sections for unchanged lines, etc...
