### ISSUE TITLE
Display Picture not changed

### ISSUE THREAD

**Issue by rahulganes** [k0shk0sh/FastHub#1970]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 4  
---

I have changed my dp in my github profile but in app it is not changed.

**Comment by yakov116** [comment]
@rahulganes please search the issues.

Thanks for your feedback
