### ISSUE TITLE
Wiki not loading

### ISSUE THREAD

**Issue by Javinator9889** [k0shk0sh/FastHub#1972]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A1  
---

 While trying to access a wiki (https://github.com/Javinator9889/pyGle/wiki) it is not loading.
Tried with other wikis and didn't work

**Comment by Javinator9889** [comment]
@k0shk0sh will wait then ^^

**Comment by Gowa2017** [comment]
same problem

**Comment by diegotejadav** [comment]
I'm having the same problem!

**Comment by DigiLive** [comment]
+1

**Comment by beastdestroyer** [comment]
Having same problem, but really enjoying the app! Can't wait for v5 :)

**Comment by GioPan04** [comment]
Same

**Comment by Z3ROGRAV1TYx** [comment]
Same issue

**Comment by flamendless** [comment]
This is still not fixed? Why?

**Comment by yakov116** [comment]
@flamendless this will be fixed in the next build. However the app is being rewritten and may take some time.

You can contribute to make it go faster.

**Comment by MartinX3** [comment]
@yakov116 
There is a project plan / roadmap so one can know what to contribute to v5?

**Comment by k0shk0sh** [comment]
Soon hopefully :)

**Comment by Grahtni** [comment]
It's been a year guys.

A year.

**Comment by 3xploiton3** [comment]
:flushed:
Still waiting

**Comment by GioPan-sh** [comment]
I think the dev is dead 😂

**Comment by k0shk0sh** [comment]
@GioPan-sh yeep and im his ghost.

**Comment by Javinator9889** [comment]
@k0shk0sh thank you so much for your awesome job :scream:

Waiting for Play Store release

**Comment by k0shk0sh** [comment]
Just released 4.6.9 please ignore 4.6.8 as it contains a bug in issue/pr timeline

**Comment by Gowa2017** [comment]
> Just released 4.6.9 please ignore 4.6.8 as it contains a bug in issue/pr timeline

Waiting for 5.0
