### ISSUE TITLE
Approve pull request does not work anymore

### ISSUE THREAD

**Issue by emilevauge** [k0shk0sh/FastHub#1976]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

Hi 
I cannot approve pull request anymore.
I get an error message at each try.
Keep up the good work!
Emile

**Comment by YesThatAllen** [comment]
I just bought paid access to Fasthub. I can't see HOW to try to approve PRs 

where's the documentation on what I should be trying?

**Comment by k0shk0sh** [comment]
I assume you are trying to approve a PR in organization? 
If so, please read the FAQ from the app or repo or playstore listing, also, search in the issue section.
