### ISSUE TITLE
Cannot create private gists

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#1978]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

 ![Upon trying to create a private gist](https://i.imgur.com/cpYjHzT.png)

Steps to reproduce:
1. Go to gists
1. Add a title and other requirements
1. Press the private symbol
1. The above link opens
1. Unable to create gist

_Sent from my Pixel 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
will be released later today or weekend
