### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#198]
Have you given any thought to using dependency injection?

It would make testing much easier.

**Comment by Rainer-Lang** [comment]
Maybe you could start with a PR... 
@kosh Are you open for this?

**Comment by eygraber** [comment]
If you're good with it I'll try it out with a few classes.

**Comment by kutsan** [comment]
Once we have tests... #190 I guess we can have dependency injection.

**Comment by eygraber** [comment]
I don't have a PR yet, just wanted to know if I should plan on making one.

**Comment by Rainer-Lang** [comment]
DI could even help for testing. I think di should be used as fast as possible.

**Comment by Rainer-Lang** [comment]
@eygraber Please keep in mind that FastHub uses ThirtyInch for MVP. 

https://medium.com/@passsy/i-dont-think-injecting-a-tipresenter-into-a-tiactivity-is-a-wise-decision-afa306227242

**Comment by eygraber** [comment]
Interesting. I might have to take some time getting used to the framework before I try something.

**Comment by k0shk0sh** [comment]
@Rainer-Lang thanks for pointing out, I don't see DI fit any where in the app, but I'm open to Prs, and if it does make sense then I'll take it from there. unit tests as well (+_+)

**Comment by k0shk0sh** [comment]
@eygraber cool, please join our slack and let me know personally on your plans so we could plan it properly.
