### ISSUE TITLE
Can't download APK from release page

### ISSUE THREAD

**Issue by Zeterro** [k0shk0sh/FastHub#1994]
Download fails each time, on each project. Downloading from web browser is fine.    

![screenshot_20180828-172025](https://user-images.githubusercontent.com/10755450/44732951-c63ebb00-aae6-11e8-94de-7a12ad181703.jpg)

**FastHub Version:** 4.6.7
**Android Version:**  8.1
**Device Information:**  
- MANUFACTURER: OPPO
- BRAND: OnePlus 
- MODEL: 5t
---

**Comment by k0shk0sh** [comment]
Will fix soon
