### ISSUE TITLE
Problems with pro features

### ISSUE THREAD

**Issue by pallas1** [k0shk0sh/FastHub#1997]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

Hello, I purchased the pro version to be able to review pull requests and do other stuff. But it doesn't work (always says "server error"), same when I try to comment on a code edit.
Are those known bugs?
Many thanks and keep up the awesome work!

**Comment by pallas1** [comment]
Public repo, within organisation, using access token.

**Comment by k0shk0sh** [comment]
Could you double check ur access token permissions? 

Its kinda strange tho, because I'm using for organization for private repos everyday to review and I have no issues.

**Comment by pallas1** [comment]
Also when I try to edit a file or add a new one, I get the "not found" error.
