### ISSUE TITLE
The ability to subscribe to issues

### ISSUE THREAD

**Issue by adrian109** [k0shk0sh/FastHub#1999]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

Would be great to have the ability to subscribe / unsubscribe from individual issues so that uses can be notified of updates to an issue they subscribe to.  This is a feature within GitHub mobile and desktop version and think it would be a great benefit to have it integrated with FastHub.

Thanks

**Comment by yakov116** [comment]
Thanks for your feedback
Please search the issues

**Comment by adrian109** [comment]
Please can you provide the issue number that this issue is a duplicate of please.  I've tried searching but cannot find an issue or feature request that matches as a duplicate for this issue.

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/44960879-46916180-aed5-11e8-829d-ccfcf021aa11.png)

Quick search of the word subscribe
