### ISSUE TITLE
Issue creation time test.

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#20]

**Comment by k0shk0sh** [comment]
As mentioned in #19, however i can't produce it. as it shows the right creation time.

**Comment by k0shk0sh** [comment]
It's the whole app time in general.

**Comment by silverAndroid** [comment]
Has this been fixed?

**Comment by k0shk0sh** [comment]
This issue has been resolved but yet, i need to test this out.
