### ISSUE TITLE
Wiki screen and hamburger menu are both blank

### ISSUE THREAD

**Issue by spikespaz** [k0shk0sh/FastHub#2000]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

 The Wiki for my project is not visible in the app. Could it be because I have no hone page, just an index?

https://github.com/spikespaz/search-deflector/wiki

**Comment by k0shk0sh** [comment]
I think GitHub has changed something with their HTML and therefore I can't parse it with the existing version.

**Comment by spikespaz** [comment]
@k0shk0sh Any idea what changed? Could you just update the parsing code?

**Comment by spikespaz** [comment]
If I have the chance would you accept a pull request for the current legacy code?
