### ISSUE TITLE
Unable to approve a PR on a public repo

### ISSUE THREAD

**Issue by colindean** [k0shk0sh/FastHub#2002]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

When I attempted to approve a PR, FastHub would show "Error communicating with the server" (or something like that) immediately. 

I opened the PR in Chrome and was able to approve it just a few seconds later. 

I am not a contributor on the repo, but clearly have permissions necessary to approve PR.

**Comment by k0shk0sh** [comment]
Have you check the status of the PR before trying and approving? 

Also if the PR in Organization the you'll need to ask them to grant you access to it or login with Açcess token. 

GitHub Auth api sucks!
