### ISSUE TITLE
Gitlab Integration? 

### ISSUE THREAD

**Issue by jdcrux** [k0shk0sh/FastHub#2006]
**FastHub Version: 4.6.7**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone Max (ZC550KL)  
---

 Gitlab Integration.. pretty much self-explanatory.

**Comment by dedepete** [comment]
Please, search through the Issues next time.  
There were loads of such requests before.  
Due to major differences between services' APIs it would be a very hard work to adapt FastHub's code.  
You can try to do it yourself, but currently this feature is not planned.

**Comment by jdcrux** [comment]
sorry, I submitted this via app, so i didn't know...
