### ISSUE TITLE
Clicking on notification does nothing

### ISSUE THREAD

**Issue by Nekromancer** [k0shk0sh/FastHub#201]
Hi
I have one unread notification on github (new comment on issue i follow) and when i click it - nothing happens. Application does not run, notification does not get dismissed.

It was popping up every few minutes until i dismissed it on github website

**Comment by k0shk0sh** [comment]
what was the notification showing?

**Comment by Nekromancer** [comment]
Well.. Nothing. It's totally empty (for this comment got the same problem)

**Comment by k0shk0sh** [comment]
what version of Android are using? what the notification actually says?

**Comment by Nekromancer** [comment]
It looks like this:
https://dl2.pushbulletusercontent.com/ImiE1SFBz4VdP9683j9DNPiRRo4Y3ljI/Screenshot_20170327-080336.png

It's stable CM 13.0, so Android 6.0.1

**Comment by k0shk0sh** [comment]
in your look screen? could you please use notification panel to screenshot

**Comment by Nekromancer** [comment]
I used lock screen just to take a screenshot. It's looking and working the same from the notification panel

**Comment by k0shk0sh** [comment]
@Nekromancer alright thanks for the clarification, I'll test it out today and see what's going on.

**Comment by k0shk0sh** [comment]
@Nekromancer please monitor this and let me know how it goes in 1.4.1.

**Comment by Nekromancer** [comment]
Now it's working great, thanks!

**Comment by k0shk0sh** [comment]
@Nekromancer 👍
