### ISSUE TITLE
Cannot download 

### ISSUE THREAD

**Issue by PhonyBrony** [k0shk0sh/FastHub#2011]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S9  
---

 When I tap to download files, I get the confirmation screen, but no options to say yes or no.

**Comment by k0shk0sh** [comment]
You might need to pull up that little dialog
![](https://i.imgur.com/N3E5qo7.jpg)
