### ISSUE TITLE
Restore purchase broken

### ISSUE THREAD

**Issue by saschpe** [k0shk0sh/FastHub#2012]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel C  
---

 I bought the pro upgrade on my phoneand restored the purchase on my tablet. I get the "you're awesome" tooltip but that's it. No pro features and still being asked to buy when selecting pro themes.

While at it, proper notifications would be nice

**Comment by k0shk0sh** [comment]
Login again.

**Comment by yakov116** [comment]
@saschpe still having an issue?

**Comment by saschpe** [comment]
Not any more back then, but I also haven't used the app in a while.On Dec 29, 2019 04:40, yakov116 <notifications@github.com> wrote:@saschpe still having an issue?
