### ISSUE TITLE
Whenever I try to merge a PR I get a 404 error

### ISSUE THREAD

**Issue by avalero** [k0shk0sh/FastHub#2016]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** bq  
- **Brand:** bq  
- **Model:** Aquaris X  
---

**Comment by atomdmac** [comment]
Same issue here.
FastHub version: 4.6.7
Android: 9
Device: Pixel 2

**Comment by k0shk0sh** [comment]
Login using access token or grant access to FastHub from ur org.
