### ISSUE TITLE
Modifying Assignee/Reviewer for PR fails unexpectedly

### ISSUE THREAD

**Issue by gkelly** [k0shk0sh/FastHub#2019]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

When trying to change the Assignee for a PR in an org I belong to, on a repo I'm a member with committer rights on, FastHub fails to change it and tells me I need admin rights.

Switching to GH desktop I can change the Assignee/reviewers without problems.

**Comment by k0shk0sh** [comment]
You need to grant FastHub access to ur org or login with access token


You can find more in the FAQ section within the app. 

Also a quick search would show similar issues.

**Comment by k0shk0sh** [comment]
There are tones :( I wish if I could find an easier way to make this easy on you and me. 

![](https://i.imgur.com/oB3Z3cJ.jpg)
