### ISSUE TITLE
Unread notifications stuck

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#202]
After receiving notifications that I have unread GitHub notifications, I open them. After leaving the app, there is still one notification with the header "Notifications" and the text "You have unread notifications". Tapping it doesn't do anything, but I can swipe it away.

**Comment by kutsan** [comment]
Thanks for pointing out. This is a known bug and should be fixed.

**Comment by k0shk0sh** [comment]
@kutsan that one 🤣. I'm aware of it tho.

**Comment by eygraber** [comment]
@k0shk0sh this is still happening.

**Comment by k0shk0sh** [comment]
@eygraber it's intentional tho :D . But maybe I'll consider removing it.
