### ISSUE TITLE
No projects or issues?

### ISSUE THREAD

**Issue by caboosesw** [k0shk0sh/FastHub#2024]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S9+  
---

 Any plans to add that? That is my workflow

Great app thougj

**Comment by k0shk0sh** [comment]
There is projects and issues.

Could you elaborate on your question more please.

Thanks

**Comment by caboosesw** [comment]
Sorry...in the client it looks like I cant wsit my github projects/notes
(cards)
