### ISSUE TITLE
No organisations shown

### ISSUE THREAD

**Issue by fardeen9983** [k0shk0sh/FastHub#2028]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 3  
---

 I am part of 2 different organisations. But none of them appear in the said section

**Comment by k0shk0sh** [comment]
Please read the FAQ section.
