### ISSUE TITLE
One of my repositories not showing up

### ISSUE THREAD

**Issue by aparedes1998** [k0shk0sh/FastHub#2032]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5T  
---

**Comment by yakov116** [comment]
@aparedes1998 what kind of repo...

Details please

**Comment by aparedes1998** [comment]
It's a prívate repo i've Bren added to. Still, muy prívate repositories are showing up

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by k0shk0sh** [comment]
Read the FAQ section from the app menu

**Comment by aparedes1998** [comment]
Found it in the FAQ section, thank you
