### ISSUE TITLE
Unable to view any wiki page

### ISSUE THREAD

**Issue by shaboigan** [k0shk0sh/FastHub#2035]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Huawei  
- **Model:** Nexus 6P  
---

 I've noticed a bug where you can search a GitHub profile but as soon as you press the wiki you just get a line at the top of the page and nothing else, regardless of how long you wait nothing happens and nothing loads, the only way round it is to view GitHub in the browser in desktop mode

**Comment by Adomix** [comment]
Same here

**Comment by Tajnymag** [comment]
The same behaviour on th and same Android and FastHub versions.

**Comment by k0shk0sh** [comment]
It seems like GitHub change something in their html classes & ids. Can't do anything unless I make a new release which will not happen until v5 is ready. 

Please stay tuned
