### ISSUE TITLE
FastHub has square icons even they are disabled

### ISSUE THREAD

**Issue by VincentJoshuaET** [k0shk0sh/FastHub#2045]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 5  
---

**Comment by VincentJoshuaET** [comment]
[it's not even a rounded square](https://i.imgur.com/SwLR1ql.png)

**Comment by k0shk0sh** [comment]
I think that this is an Android version specific bug, there is an issue that is similar to this, I'll fix that when v 5.0 is released.
