### ISSUE TITLE
Dark theme has light elements when opened from notification

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#205]
I have the dark theme enabled. 

If I open the app from a notification, I see some light elements. 

For example, if I open a notification for a comment on an issue, the comment body has a light background. 

![example](http://imgur.com/cnA6lgY)

**Comment by k0shk0sh** [comment]
if you are using Android N then yes its a system bug in nightmode that couldn't really make it to work. its a known bug and for it I'm planning to let go night mode an use custom themes instead.

**Comment by k0shk0sh** [comment]
I label it as won't fix, because I can't do anything about it. as a workaround, you could pause the activity you are currently at and resume it. its not really FastHub bug more like system bug.

**Comment by eygraber** [comment]
👍
