### ISSUE TITLE
Back returns to top of bug list

### ISSUE THREAD

**Issue by reetp** [k0shk0sh/FastHub#2052]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S6  
---

If I view a bug and then go back the bug list has to be reloaded and then scrolled through again.
Very frustrating when you have a couple of thousand bugs to have to start from the top again !!
Thanks.

**Comment by k0shk0sh** [comment]
Don't press the toolbar back button but press the device back button.

**Comment by reetp** [comment]
That's a bit of a GUI bug then?
Not exactly intuitive....
Used for pretty well everytjing else but.....

**Comment by k0shk0sh** [comment]
It's not a bug nor a feature its a behavior.

**Comment by reetp** [comment]
OMG.... I have heard some strange excuses for GUI behaviour over the decades, but that seriously raises the bar....
:smiley:

**Comment by yakov116** [comment]
Please look at the Google Docs. The arrow go up a level, back key goes to the last activity

**Comment by reetp** [comment]
I'll take your word for it.
Still feels odd using it for most stuff except back. As someone new to Fasthub it feels strange. Maybe Google don't get everything right!!
Thanks for a great app.... I did pay :-)

**Comment by k0shk0sh** [comment]
As Yakov, said, it was implemented as you mentioned from the start but people complained alot about it and I had to follow exactly Google docs for it 🤷‍♂️

**Comment by reetp** [comment]
:banghead:

Roll on retirement.....
