### ISSUE TITLE
Accessing Readme through another Readme ends in loop

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#2054]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

Open one of the first 4 links from this readme
 https://github.com/abhijithvijayan/System-Software-lab/blob/master/README.md

And then open the readme in that folder.

**Comment by k0shk0sh** [comment]
What's the problem with that? You are opening a new instance of that readme.
