### ISSUE TITLE
Wiki doesn't render

### ISSUE THREAD

**Issue by gdevenyi** [k0shk0sh/FastHub#2063]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** 3  
---

 Wikis no longer render

**Comment by k0shk0sh** [comment]
That's true, GitHub has changed some of their HTML classes & ids and therefore we can't render that any longer! I'll fix that in v5.
