### ISSUE TITLE
Feed not loading

### ISSUE THREAD

**Issue by pulkitkumar** [k0shk0sh/FastHub#2065]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

 The app doesn't load any organization or feed, pull request etc.

**Comment by yakov116** [comment]
Does it have the correct permissions set?

**Comment by k0shk0sh** [comment]
Please read the FAQ from within the app or from the repo readme.
