### ISSUE TITLE
Slack link does not work

### ISSUE THREAD

**Issue by aslafy-z** [k0shk0sh/FastHub#2067]
**FastHub-Libre Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR  
- **Model:** Honor 9  
---

 The slack link is one more time not valid anymore. Could you please update it?
Thank you

**Comment by yakov116** [comment]
@k0shk0sh was this fixed?
