### ISSUE TITLE
Asks to unlock for theme change after reinstall

### ISSUE THREAD

**Issue by aduguid** [k0shk0sh/FastHub#2068]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7  
---

 I've paid for the pro version but it's asking for a unlock code. I had to reinstall because it didn't refresh some of my projects.

**Comment by k0shk0sh** [comment]
yeah, somehow google is not returning right data either via login/restore purchase. 

maybe its due to you having multiple accs?

**Comment by k0shk0sh** [comment]
`Abandonded` because the implementation will change in v5
