### ISSUE TITLE
AMOLED theme not applied to switch branch activity

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#2070]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

 ![](https://i.imgur.com/uZce3Kj.jpg)

**Comment by k0shk0sh** [comment]
as per the readme, only report if necessary, as i'm changing everything, its ridicules to report something nobody is going to fix. 

thanks : )
