### ISSUE TITLE
Private Repositories commits

### ISSUE THREAD

**Issue by xamo1998** [k0shk0sh/FastHub#2074]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7 edge  
---

 It would be awesome to have all the commits in the main table like in the website.
You can see all private commits but other people see only the public.
In this app you can only see the public commits on your profile.

**Comment by k0shk0sh** [comment]
You mean in your feeds? 

If so, please use access token with the right permissions you could actually see that.
