### ISSUE TITLE
Unauthorized User

### ISSUE THREAD

**Issue by creativetrendsapps** [k0shk0sh/FastHub#2075]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** moto g(6) play  
---
Getting toats about completing webhooks... Afterwards I'm logged out stating I'm an "unauthorized User".

**Comment by k0shk0sh** [comment]
Hi, its GitHub that is down and returning nonsense response, give them sometime until they migrate everything.
