### ISSUE TITLE
The pinned button is little broken on small screen.

### ISSUE THREAD

**Issue by dikiaap** [k0shk0sh/FastHub#208]
In the screen with width 480px has little glitches. The pinned button on repository page will be disappear.

![screenshot_2017-03-27-15-50-51 01](https://cloud.githubusercontent.com/assets/8542502/24348652/a5060da4-1306-11e7-9dc4-90e55667f542.png)

Some people doesn't really needs the pinned button though. I had an idea to move it into those 3 dots button.

**Comment by k0shk0sh** [comment]
Well, thats pretty small screen :D . i'll see what I can do about it.
Thanks :)

**Comment by dikiaap** [comment]
Hey @k0shk0sh. Now, the watch icon is lost their part.

![screenshot_2017-04-01-15-05-22 01](https://cloud.githubusercontent.com/assets/8542502/24576846/56198500-16ed-11e7-8092-5a1d1b040a0e.png)

**Comment by k0shk0sh** [comment]
@dikiaap owh, I guess I know why, it will be up tomorrow.
