### ISSUE TITLE
Can not create issue for the repository

### ISSUE THREAD

**Issue by emartynov** [k0shk0sh/FastHub#2080]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia XZ Premium  
---

 If I try to create new issue I always see status notification that item not found.

**Comment by k0shk0sh** [comment]
Maybe you are creating it into an organization repo or private repo and you don't have access to it? Please read the FAQ about that because I could tell u created this issue from FastHub via the details in ur description and it was a success.

**Comment by emartynov** [comment]
I created it through feedback menu. I failed through FAB in issues list.
Repo is public - I created issues with GitHub app.
