### ISSUE TITLE
Doesn't support halloween contribution graph

### ISSUE THREAD

**Issue by AndreamApp** [k0shk0sh/FastHub#2087]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI6  
---

**Comment by nyuszika7h** [comment]
Can confirm, contribution graphs are completely grey on my OnePlus 5T running Android 8.1.0 (OxygenOS 5.1.5), same app version.

**Comment by yakov116** [comment]
Happened last year too. Will go back to normal when they change it back

**Comment by nyuszika7h** [comment]
It should still be fixed though. I haven't looked at FastHub's code but this suggests it's relying on the color values, but clearly it's not just taking them as-is. The `data-value` attribute could be used to avoid breaking the graph if GitHub ever decides to change their colors around (not just for Halloween).

**Comment by yakov116** [comment]
We use lib.
Anyway there will not be any releases on the 4.0 branch and version 5 is not completed (just yet)

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/kOEfyur.jpg)

**Comment by yakov116** [comment]
@k0shk0sh Sweet!! ~~if only i would be able to~~...
