### ISSUE TITLE
Issue with markdown rendering

### ISSUE THREAD

**Issue by michael-wolfenden** [k0shk0sh/FastHub#2088]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Model:** Nexus 6  
---

When viewing the following markdown
  https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/93e39b8f48169cce4803615519ef87bb2a969c8e/AsyncGuidance.md

The code samples do not render correctly as they contain sections of html formatting

**Comment by yakov116** [comment]
@michael-wolfenden thanks for your feedback please search the issues before opening a new issue
