### ISSUE TITLE
Comment the code to help contributors

### ISSUE THREAD

**Issue by Rainer-Lang** [k0shk0sh/FastHub#209]
This helps contributors to make better PRs and even to write tests for you.... https://github.com/k0shk0sh/FastHub/issues/190

**Comment by k0shk0sh** [comment]
Thanks Rainer, 

Commenting code is not something practical to do, the code by itself should be descriptive enough to tell the contributors what this do and what not, If I sat to write comments on every single line I write then, probably i'll take forever to finish this app. 

However i'm not against that, it just that I understand one thing when I write a single line of code, MAKE IT **UNDERSTANDABLE** & **MAINTAINABLE** therefore, I guess I wont be writing comments unless if I know my code isn't something to get or understand.

**Comment by Rainer-Lang** [comment]
You shouldn't comment every line ;)
But you should comment "tricky" methods, so contributors could write a test for it. :)

**Comment by kutsan** [comment]
I am going to close this issue because I agree with @k0shk0sh. I don't think current code isn't something readable. Other tricky methods eventually will get their comments.

If you or someone see a piece of understandable code, please provide an example to this issue.

**Comment by heinrichreimer** [comment]
In general as long as all API methods have Javadoc, everything should be fine. We don't need to comment every internal method, but especially the `View` and `Presenter` interfaces should have Javadoc.
The Google Java Styleguide has some basic rules for where it is needed: https://google.github.io/styleguide/javaguide.html#s7.3-javadoc-where-required

**Comment by k0shk0sh** [comment]
If the method names are obvious to understand there shouldn't be a javadoc nor comments.
Lets say a method named  `onLogin()`  then should I write about what it does? No right. 

This topic is getting away to much defense, each person and their preference, I can't satisfy all of you, so, I'm putting it under off-topic
