### ISSUE TITLE
#bug propic don't change in app

### ISSUE THREAD

**Issue by RedTgUser** [k0shk0sh/FastHub#2093]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 5 Pro (Whyred)
---

In the app, when I change profile photo, the new one is not displayed in the side menu but the old one still appears

**Comment by RedTgUser** [comment]
![Screen](https://tlgur.com/d/GVKmNoAg)

**Comment by RedTgUser** [comment]
`m`

**Comment by RedTgUser** [comment]
![Screen](https://i.imgur.com/po6sPAM.jpg)

**Comment by yakov116** [comment]
@RedTgUser please search the issues before opening a new one

**Comment by RedTgUser** [comment]
I'm sorry

**Comment by RedTgUser** [comment]
Anyway, The issues say it has been resolved but I still see this problem

**Comment by yakov116** [comment]
@RedTgUser it says that there isd no way for us to know that it changed. So the only is to clear the avatar cashe (its in the settings).

**Comment by RedTgUser** [comment]
Oh it work, thanks
