### ISSUE TITLE
Image  Cannot View

### ISSUE THREAD

**Issue by zawawimanja** [k0shk0sh/FastHub#2105]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 3  
---

 Image not displaying when viewing

**Comment by k0shk0sh** [comment]
Which image you referring to? Link & a more descriptive description would be cool

**Comment by zawawimanja** [comment]
This link https://github.com/GabrielGymkhanaCGN/GoblinWordGenerator.

- Below of the page it has screenshot. When I click the image to view it ,it does not display.

**Comment by k0shk0sh** [comment]
When trying to open the image in browser GitHub shows its too large to display and I have idea of the size of the image as im just loading a URL. So it's something I can't fix.

Maybe the behavior will change in v5 but I doubt that. You could always click on the menu icon and select open in browser or click on download  to view it locally
