### ISSUE TITLE
Password visibility icon on login should be inverse

### ISSUE THREAD

**Issue by yashbmewada** [k0shk0sh/FastHub#211]
The password visibility icon on the login screen should be inverse of what it is right now. i.e. the open eye icon shiuld we shown to user when the password is hidden indicating the action it performs i.e. make password visible and vice-versa.

**Comment by k0shk0sh** [comment]
Well, I guess this should be reported to Android team? As far as I know I'm using the default implementation and this is how Android is doing it.
