### ISSUE TITLE
Doesn't load picture of bots in Feed

### ISSUE THREAD

**Issue by haxzie** [k0shk0sh/FastHub#2110]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P20 lite  
---

News feed uses the usual random github avatar for Bots instead of using the actual profile image / logo of the bot.

**Comment by k0shk0sh** [comment]
we only have one imageurl and there is no where i could tell this is a bot or not 🤷‍♂️

**Comment by haxzie** [comment]
So, this is a problem with the API? Is it possible to find the right image url if we can somehow identify it as a bot? (Since the name contain [bot])

**Comment by k0shk0sh** [comment]
@haxzie GitHub only provide one image URL either using graphql or json api. There is no way :(.
