### ISSUE TITLE
FastHub 2

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#2118]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

Hey, I wanted to ask you a simple question.
How is FastHub 2 development going on? Which changes are you introducing?

**Comment by k0shk0sh** [comment]
You could follow the development at fasthub/fasthub-v5 branch where you could see what im doing. 

to answer your question in one word: everything :)
