### ISSUE TITLE
Add an mark as read action to notifications in the notification panel

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#212]
There are times where I don't want to have to open the notification. A mark As read action would be helpful.

**Comment by eygraber** [comment]
I saw there was something related to this in 1.7.0

I was talking about Android notifications. Is that planned?

**Comment by eygraber** [comment]
@k0shk0sh haha I meant from the notification panel. Although it's useful in the list too 👍

**Comment by k0shk0sh** [comment]
@eygraber the naming tho is confusing notification & notification, they are the same lol. Alright I'll try and make that happen in 1.7.1 too.

**Comment by k0shk0sh** [comment]
Oops, this issue should be closed awhile ago :D
