### ISSUE TITLE
Allow the drawer to be opened deeper in the hierarchy

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#213]
If I come into the app from a notification or something like that the back stack doesn't necessarily let me get back to the main page. If those pages deeper in the hierarchy had a drawer it would make navigation easier than having to close the app and reopen it to get to the main page.

**Comment by k0shk0sh** [comment]
this issue resolved by handling the back button properly & not by adding navDrawer into each screen. i'm open to hear your thoughts if there is a valid reason to add navDrawer in each screen.
