### ISSUE TITLE
Wiki not loading

### ISSUE THREAD

**Issue by afrey15** [k0shk0sh/FastHub#2132]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** moto e5 play  
---

 The wiki for my repository will not load in this mobile device. When I select the wiki icon, it opens a blank page. The right side bar is also blank.

**Comment by yakov116** [comment]
@afrey15 Please search the issues
