### ISSUE TITLE
Tone down needless motion/animation 

### ISSUE THREAD

**Issue by seaneking** [k0shk0sh/FastHub#214]
Meaningful motion is great, and one of the core tenants of material design, but personally finding the jelly-like bouncing animations used through FastHub really distracting. They don't serve a functional UX purpose, and just take away from what you're actually trying to do (browse GitHub).

Wanted to open this issue to see if others felt the same, and see if we might be able to remove or tone down the loading ease-ins.

**Comment by k0shk0sh** [comment]
There were an issues reported regards this and the solution was to add a __disable list animation__ in the settings screen, tbh I myself don't like it anymore and it should be disabled by default. Meantime you could disable it from settings screen.
Thanks for your feedback

**Comment by seaneking** [comment]
Ah gotcha, excellent thanks. 

Yeah does seem an odd thing to have configurable, should just ship disabled IMO. Can always add in more subtle movement later if need be.

**Comment by kutsan** [comment]
Instead of just list animations. You can add more animations and then it could be disabled by default. So, everyone happy.

**Comment by k0shk0sh** [comment]
This issue has been fixed two days ago, but I forgot to close it from my commit message or I actually closed another issue :D. 
now the default behaviour is disabled by default.
