### ISSUE TITLE
Change "noasse" to "view"

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#2140]
**FastHub-Libre Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  
---

 If the license isn't detected by github, the web ui shows "view license", forkhub shows " NOASSE", which is short for "no assertion". A string like "View" seems to me more intuitive.

**Comment by k0shk0sh** [comment]
I didn't get you, what are you referring to? Because this isn't forkhub!!

**Comment by mueller-ma** [comment]
I'm sorry, I mean fasthub ;)
Visit https://github.com/TeamNewPipe/NewPipe in your app. You'll normally see the license under the scale icon, but for this repo it shows "noasse"

**Comment by k0shk0sh** [comment]
@mueller-ma owwh, I'm showing what GitHub returns to me so this isn't a hardcoded value but maybe I'll fix it in v5.
