### ISSUE TITLE
Can we choose the start screen?

### ISSUE THREAD

**Issue by stretchyboy** [k0shk0sh/FastHub#2141]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto C  
---

 The feed is no use to me day to day. I'd much prefer to have access to the latest issues or commits.
Tar

**Comment by yakov116** [comment]
@stretchyboy no there is currently no way. @k0shk0sh has stated before that he will not be changing it.

**Comment by k0shk0sh** [comment]
You have appshortcut which direct you to places you want the most, pin a repo for example and add the pinned repos shortcut to ur home screen. Long click the app icon to find out. Also in v5 there will be different access points to things makes it easier than it is now.
