### ISSUE TITLE
Download repository 

### ISSUE THREAD

**Issue by DCull1984** [k0shk0sh/FastHub#2142]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia XA2  
---
Hi, 
I am trying to get my repository downloaded so I can continue the work from home, however it keeps failing. 
Is there something wrong with the app or am I doing it wrong. 
 Kind regards,

David Cull

**Comment by k0shk0sh** [comment]
Your repo probably is private or in an organization, so please read the faq.

**Comment by DCull1984** [comment]
No I haven't it's public and my own account

**Comment by DCull1984** [comment]
Literally putting that the download is unsuccessful. No errors, codes nor reasons why.
