### ISSUE TITLE
My file upload button is not working

### ISSUE THREAD

**Issue by rachitralli** [k0shk0sh/FastHub#2148]
**FastHub Version: 4.6.7**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** OPPO  
- **Brand:** OPPO  
- **Model:** A37f  
---

 Pls enable my file upload button

**Comment by yakov116** [comment]
@rachitralli what?

**Comment by rachitralli** [comment]
My file upload button is not working and the upload button has been disabled here http://github.com/rachitralli/keyboards and her http://github.com/keymanapp/keyboards please enable the file upload button so that I can upload keyboard files directly to the GitHub.
