### ISSUE TITLE
Old notification is shown repeatedly

### ISSUE THREAD

**Issue by Yeradon** [k0shk0sh/FastHub#215]
A old notification from 2016 is shown repeatedly. It isnt clickable and i cant see it in the app or the web app.

**Comment by k0shk0sh** [comment]
Hello @Yeradon thanks for reporting this issue, 

That's strange tbh, how come it isn't clickable & it isn't showing in Github. 

This sounds strange to me. 

Could you provide more info please.

**Comment by k0shk0sh** [comment]
due to not responding to this issue, I'm going to close it, please do let me know if anything regards this.

**Comment by Yeradon** [comment]
Sorry i didn't saw that you responded. The notification is still there. If i click on it nothing happens. I can swipe it away, but it will be shown again after ~15min. It is a notification for a invite to private repo that doesn't exist anymore. I don't see this kind of notification on GitHubs website. I am using Android 7.1.1 on One plus 3T. Reinstalling the application didn't help.

**Comment by k0shk0sh** [comment]
If the notification exists then GitHub will return the notification & I can't help but to display them, could you open the app & click on the ring icon to open notifications and see if you are able to mark them all as by clicking on the icon on the toolbar,  if that didn't help, then I guess the only way to remove them, is just to disable the notifications scheduler from the settings screen.
