### ISSUE TITLE
FastHub does not provide Android notifications for GitHub notifications

### ISSUE THREAD

**Issue by benji7425** [k0shk0sh/FastHub#2154]
**FastHub Version:**  4.6.7
**Android Version:**  8.1.0
**Device Information:**  
- MANUFACTURER: LG
- BRAND: Nexus
- MODEL: Nexus 5X
---

# Summary
I do not receive GitHub notifications as Android notifications.  
I have used FastHub for months and have never had notifications from it.
I have searched past issues and tried every fix suggested.  

FastHub is my favourite GitHub Android app so I have overlooked the lack of notifications so far, but recently I have missed a few important updates as a result, so went back to try and fix this.

# What I tried
I searched past issues for fixes, and tested with every setting in every configuration I could find. I tested multiple times, with multiple different settings configurations.
Notifications come to my email, the web client, and show when I open the FastHub app, but do not show as Android notifications.

[OctoDroid](https://play.google.com/store/apps/details?id=com.gh4a&hl=en_GB) provides Android notifications as expected, FastHub does not.

I have tried reinstalling, then tested a variety of different settings.

**Test methodology**
1. Choose GitHub/FastHub settings combination (I tried lots of settings on/off combinations)
2. Close all GitHub tabs on my desktop to ensure they are not interfering
3. Close FastHub on my phone to simulate normal usage
4. Open incognito and log into GitHub with a *separate account*
5. Create a new issue on a test repository belonging to my main account
6. Wait about 5-10m (or longer if FastHub interval set higher)

Throughout my entire testing I did once or twice receive a notification, leading me to believe I had solved it, but in each instance I was unable to get any more notifications despite many attempts.

## GitHub notifications are turned on for both Web and Email, for everything
![image](https://user-images.githubusercontent.com/14295333/49691770-5f975780-fb41-11e8-9974-1048c00c8d89.png)

## My email notification preferences are turned on for everything
![image](https://user-images.githubusercontent.com/14295333/49691777-80f84380-fb41-11e8-9d81-d73499f7e1b8.png)

## FastHub notifications are turned on
I also tried turning "Disable Notification Read Status" and "Enable Notification Sound" on and off
![image](https://user-images.githubusercontent.com/14295333/49691848-57d8b280-fb43-11e8-9d30-d957947a33d2.png)

## FastHub notifications interval is set to 1m
I also tried with 5m, 10m and 30m
![image](https://user-images.githubusercontent.com/14295333/49691783-a5542000-fb41-11e8-98ef-fc65c4810908.png)

## Battery saver is turned off for FastHub
I thought this might be causing it to sleep in the background
![image](https://user-images.githubusercontent.com/14295333/49691786-b13fe200-fb41-11e8-92d0-6b88a3272f0e.png)

## FastHub notifications are turned on in Android
![image](https://user-images.githubusercontent.com/14295333/49691803-58247e00-fb42-11e8-8b80-6e04b5b62e47.png)

**Comment by k0shk0sh** [comment]
That's weird, care to share how did you login to FastHub? And ur test repos were public or private? Part of organization or individual?

**Comment by benji7425** [comment]
- Logged in using OAuth (browser)
- Test repo was private, but I don't get public notifications either (eg didn't get this one)
- Test repo belongs to my own account, no organisation

**Comment by k0shk0sh** [comment]
Please login via access token and grant FastHub some of the permissions and importantly notifications permission, basically give it all the read access even the ones that don't make sense. And it shall work. 

For private repos u need to grant FastHub access and oauth wont work apparently. 

You could find more solutions in FAQ from app menu

**Comment by benji7425** [comment]
I have tested with the settings you suggested, and I still do not receive any notifications.

## GitHub token with read and notification permissions
![image](https://user-images.githubusercontent.com/14295333/49702294-98d9d100-fbee-11e8-96d4-ff9be023e742.png)

## Signed in with access token
![image](https://user-images.githubusercontent.com/14295333/49702307-b6a73600-fbee-11e8-8376-38023b103251.png)

## Private test repo
![image](https://user-images.githubusercontent.com/14295333/49702318-cc1c6000-fbee-11e8-88ac-5f705483a7a9.png)

## Add my test account (@benji7426)
![image](https://user-images.githubusercontent.com/14295333/49702322-d9394f00-fbee-11e8-80a2-6fb8dda1b4c5.png)

## Use test account to create test issue
![image](https://user-images.githubusercontent.com/14295333/49702327-ea825b80-fbee-11e8-883e-558cbf2633b8.png)

## 15m later still no mobile notification
![image](https://user-images.githubusercontent.com/14295333/49702337-02f27600-fbef-11e8-9d87-3c8b861f9fda.png)

**Comment by embeddedt** [comment]
I just downloaded FastHub a few days ago. It's a great app but I am not seeing Android notifications either. I did set my notification interval to 5 minutes and they are enabled.

**Comment by zoj613** [comment]
Same here. Tried everything and I still dont get them

**Comment by froth** [comment]
Same here :(

**Comment by zoj613** [comment]
Well,now that im running AOSP 9 rom and set the battery optimise option off for Fasthub, Ive been getting github push notifications via the app. In fact I saw the above issue comment because the app notified me.
