### ISSUE TITLE
Code block reference renders as a table

### ISSUE THREAD

**Issue by gregsdennis** [k0shk0sh/FastHub#2155]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6  
---
I referenced a span of lines of code in one of my issues, and it renders all pretty in the browser, but in the app, it's just a two-column table.  The left column is empty, and the right column is the code with one row per code line.

Screenshot:
 ![](https://i.imgur.com/ojCIw17.jpg)

**Comment by yakov116** [comment]
Known bug. Wait until v5
