### ISSUE TITLE
Add refresh button in header menu

### ISSUE THREAD

**Issue by gregsdennis** [k0shk0sh/FastHub#2157]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6  
---

 On long issues [like this one](https://github.com/json-schema-org/json-schema-spec/issues/643), it can be a pain to have to scroll all the way to the top to refresh.

It'd be nice to have a refresh button in the header menu so that it can be refreshed from the bottom (or anywhere).

**Comment by k0shk0sh** [comment]
You can click on the tab to scroll all the way up in every list that has a tab ;).

**Comment by gregsdennis** [comment]
There's no tab when you have an issue open (like the one I linked).  This isn't in a list. It's in a really long issue.
