### ISSUE TITLE
Long Pressing reactions doesn't work

### ISSUE THREAD

**Issue by tristandruyen** [k0shk0sh/FastHub#2159]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Poco F1  
---
Long Pressing the reaction icon to find out who reacted throws a error 
Although only for issues not for comments 

Reproduce: 
Press 
| |. | |
\\\/ \\\/

**Comment by tristandruyen** [comment]
Works here

**Comment by k0shk0sh** [comment]
this will be fixed in v5 :)
