### ISSUE TITLE
Text color for descriptions is black.

### ISSUE THREAD

**Issue by shgaurav** [k0shk0sh/FastHub#216]
Hey man, Just noticed a bug with the new version where under commit, branch screens. Under headings, the descriptions are using black as text color. Does not happen everytime.
Screenshot: https://drive.google.com/file/d/0B7eMBI2WGcwMLXB0eTlPMldDZ28/view?usp=drivesdk

**Comment by k0shk0sh** [comment]
#181 #205  #207

**Comment by k0shk0sh** [comment]
It's known bug in Android & i'm working on theme engine instead of Night/Day mode.

**Comment by shgaurav** [comment]
No way! That's awesome :D

**Comment by k0shk0sh** [comment]
Sorry to buzz you, but this comment is just a test so please ignore it.
