### ISSUE TITLE
Organizations not showing

### ISSUE THREAD

**Issue by mattshoe81** [k0shk0sh/FastHub#2166]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7  
---

 I am unable to see my organizations in the app.

**Comment by k0shk0sh** [comment]
Hello Matthew, please search issues or explore the app before submitting new issue. 


Read the faq from the app!!!.
