### ISSUE TITLE
Milestones Creation Issue

### ISSUE THREAD

**Issue by shgaurav** [k0shk0sh/FastHub#217]
Hey man, I have noticed i can no longer add a description for a milestone within the app. For now you have to ask for due date and tittle. Is it possible you can add another text heading and text field so we can add description for milestones within the application. 
Screenshot: https://drive.google.com/file/d/0B7eMBI2WGcwMOTZsZEZnY09KSE0/view?usp=drivesdk

**Comment by k0shk0sh** [comment]
this issue fixed by 437706b

**Comment by shgaurav** [comment]
Which version will this fix be released?

**Comment by k0shk0sh** [comment]
Coming Sunday or any release that occur until then
