### ISSUE TITLE
Failed to login in

### ISSUE THREAD

**Issue by abhijithvijayan** [k0shk0sh/FastHub#2173]
Not Logging in.

Resulting in time out.

Tried browser login method, token method.

**Comment by k0shk0sh** [comment]
Try again in different time, maybe ur internet connection was bad? GitHub was down? Some maintenance or something similar.

**Comment by abhijithvijayan** [comment]
> 
> 
> Try again in different time, maybe ur internet connection was bad? GitHub was down? Some maintenance or something similar.

Tried and failed.

**Comment by k0shk0sh** [comment]
Hmmm, that's weird!. Was it first time ever using app? How did u get the app? From where u download it?

**Comment by abhijithvijayan** [comment]
> 
> 
> Hmmm, that's weird!. Was it first time ever using app? How did u get the app? From where u download it?

Nah. I have been using it for sometime. Had to reinstall from google playstore. I tried every way last day to login. 

Will get back at you if the issue still persists.

**Comment by k0shk0sh** [comment]
Please do so, as it seems really strange!

**Comment by abhijithvijayan** [comment]
@k0shk0sh Logged in!!!

Tried with the auth login once again. It works. No idea what happened earlier. :grin:
