### ISSUE TITLE
Status bar on dark theme

### ISSUE THREAD

**Issue by nopesal** [k0shk0sh/FastHub#2178]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7  
---

The status bar has the icons of dark color when the theme of the application is dark. the icons should be lighter.

**Comment by k0shk0sh** [comment]
closed with #2313
