### ISSUE TITLE
Issue screen request

### ISSUE THREAD

**Issue by shgaurav** [k0shk0sh/FastHub#218]
Hey man, I am just curious whether this is possible. Right now the issues screen shows all the issues you have created yourself. Will it be possible to update that list and show issues that you assign to yourself. That will be extremely useful since you won't have to go into the repos and then go into issues etc. It just makes the issues screen extremely efficient and reliable for users using the app. I believe this might be hard. Lol

**Comment by k0shk0sh** [comment]
Hello @shgaurav sure so & seems reasonable request. hopefully Sunday it'll be there :)

**Comment by shgaurav** [comment]
@k0shk0sh Awesome, Looking forward to it!

**Comment by Dimitrees** [comment]
@k0shk0sh are you planning to work on this yourself?

**Comment by k0shk0sh** [comment]
I haven't start anything regards this so far as I'm focusing more in
combining comments & labels together, if you got time for it, then I could
assign it to you if you like.

**Comment by Dimitrees** [comment]
@k0shk0sh  I am interested in working on it, indeed. However I am new to both your project and GitHub in general so I will probably need to be provided with some guidance.

**Comment by k0shk0sh** [comment]
Cool, alright then you could join our slack channel and we could talk from
there or you could just email me from the email in my profile. You could
first follow the contribution guide that we setup to at least get the
project up and running, then we could discuss more. Meantime I'm heading to
sleep 2:58am over here so I'll probably reply you as soon as i wake up.

On Apr 1, 2017 2:53 AM, "Dimitris Stavrou" <notifications@github.com> wrote:

@k0shk0sh <https://github.com/k0shk0sh> I am interested in working on it,
indeed. However I am new to both your project and GitHub in general so I
will probably need to be provided with some guidance.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/218#issuecomment-290798453>,
or mute
the thread

**Comment by k0shk0sh** [comment]
@Dimitrees any updates on this? I'm planning to include it in tomorrow's release.

**Comment by Dimitrees** [comment]
@k0shk0sh Sorry I havent been able to work on this at all. Im going to start working on it by Monday and I am really unsure about how long it will take until its completed. If you feel like this is a high priority issue then feel free to assign someone else.

**Comment by k0shk0sh** [comment]
@Dimitrees alright, its all yours, I'll postponed this to next release then and i'll focus on #220

**Comment by Dimitrees** [comment]
Thanks :) Ill let you know about my progress and in case I face some diffuculties Ill message you on slack

**Comment by k0shk0sh** [comment]
@Dimitrees later when you pull latest, have a look at this [RepoQueryProvider.java](https://github.com/k0shk0sh/FastHub/blob/09e586a8b0d53da9b042cfd1b00b10bec7c11c39/app/src/main/java/com/fastaccess/provider/rest/RepoQueryProvider.java#L25-L25)
`getAssigned()` & `getMentioned()`

**Comment by Dimitrees** [comment]
Thanks for the assistance

**Comment by shgaurav** [comment]
@k0shk0sh Any idea when this would be completed. Also, rather then creating a duplicate issue. I was just wondering if you got rid the of #ofcommits that was displayed beside the commits label under your repo?

**Comment by k0shk0sh** [comment]
@shgaurav maybe within this week. And couldn't get ur second question.

**Comment by shgaurav** [comment]
@k0shk0sh https://drive.google.com/file/d/0B7eMBI2WGcwMcEQ3V1BOeVdvMk0/view?usp=drivesdk

The above link has a screenshot which shows that i am no longer able to see the total number of commits per branch.

**Comment by shgaurav** [comment]
@k0shk0sh lol its alright...i am surprised no one created an issue for it. Lol

**Comment by shgaurav** [comment]
@k0shk0sh Any word on this...is this suppose to be implemented soon?

**Comment by k0shk0sh** [comment]
@shgaurav upcoming release, probably today after work I shall start on it. It just that the UI part is the only thing keeps me away from it until today lol

**Comment by asaeid** [comment]
- ### ___
### 
- 1. ## _ __

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/Mpr3bEd.png)

**Comment by shgaurav** [comment]
@k0shk0sh Cannot wait to see this in the next update...looks awesome!

**Comment by k0shk0sh** [comment]
@shgaurav just released, after awhile you should be able to receive an update
