### ISSUE TITLE
Bug watching wikipage

### ISSUE THREAD

**Issue by goxr3plus** [k0shk0sh/FastHub#2184]
**FastHub Version: 4.6.7**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

 Watchingg the wikihow from FastHub shows empty when i open it in browser it works as expected.

Link of github repository  :

https://github.com/goxr3plus/JavaFX-Web-Browser/wiki/Java-8-and-9-Releases
![Image](https://i.imgur.com/7gM4ZVo.png)
![Browser Image](https://i.imgur.com/7oARv1u.png)

**Comment by yakov116** [comment]
@goxr3plus nope however I can give you a picture of a simple issue search 

![](https://i.imgur.com/Vi16pv9.png)
