### ISSUE TITLE
option to change the startpage to anyother page

### ISSUE THREAD

**Issue by ihatethisusername** [k0shk0sh/FastHub#2186]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy J5(2016)  
---

 I would like to see the starred repos first.

**Comment by k0shk0sh** [comment]
Use app shortcuts to access ur profile and from there u could access ur starred repos.

**Comment by ihatethisusername** [comment]
sure

**Comment by k0shk0sh** [comment]
Thanks for ur understanding :). 
In v5 it will be even easier to access that with just one click
