### ISSUE TITLE
Flashing screen on releases page when viewing patch notes.

### ISSUE THREAD

**Issue by damoos3** [k0shk0sh/FastHub#2187]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

 When I open say a link github.com/person/app/releases and its on the releases page and say I click on version 2.8 to see more info it starts flashing rapidly until i swipe down then it stops and i can read the release notes.

**Comment by yakov116** [comment]
@damoos3 update to the latest version
