### ISSUE TITLE
back my history visits

### ISSUE THREAD

**Issue by zhonghuabao1** [k0shk0sh/FastHub#2188]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3010  
---

  I missing my page after taggle FastHub to google-browser!
  how can I go back to my history visits when I am in home page?

**Comment by yakov116** [comment]
@zhonghuabao1 	what?
