### ISSUE TITLE
Strange overlapping on issue list

### ISSUE THREAD

**Issue by Nekromancer** [k0shk0sh/FastHub#219]
Hey

I found this monstrosity while roaming around your application:

![https://dl2.pushbulletusercontent.com/62R7HzprsaAZ7iL9UzQToOlIWMYn1ZI1/Screenshot_20170328-063222.png](https://dl2.pushbulletusercontent.com/62R7HzprsaAZ7iL9UzQToOlIWMYn1ZI1/Screenshot_20170328-063222.png)

It's like 1 list is over another. One is moving and one is still. Both have same items, so at first you don't notice anything. You need to scroll to see that.

**Comment by k0shk0sh** [comment]
Yup, I noticed that & I thought I fixed it in yesterday release, it'll be fixed in next version :) 
#161
