### ISSUE TITLE
Profile picture not loading

### ISSUE THREAD

**Issue by isakal** [k0shk0sh/FastHub#2190]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Hongmi 6  
---

 My profile picture won't load.

**Comment by yakov116** [comment]
@isakal 	did you change it?

**Comment by isakal** [comment]
Yes i changed it a week ago but never payed attention.
My coworker's picture is able to load.

**Comment by yakov116** [comment]
@isakal clear the picture cashe from the settings
