### ISSUE TITLE
Filtering menu doesn't display

### ISSUE THREAD

**Issue by bitsdanceforme** [k0shk0sh/FastHub#2191]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** google  
- **Model:** Chromebook Plus  
---

 When clicking on the Filter button in the lower right hand corner on the repository page, the pop-up window appears very small. You can scroll up (and see nothing) or scroll down and barely see the options to filter. The pop-up cannot be resized or moved. No work around yet.

**Comment by yakov116** [comment]
picture?
