### ISSUE TITLE
Doesn't show which repository cross-reference is from

### ISSUE THREAD

**Issue by Mikaela** [k0shk0sh/FastHub#2192]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus3  
---

 https://github.com/matrix-org/synapse/issues/1287 - I have referred to this issue from multiple repositories, but from Fasthub it looks like all references are from that/single repository.

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
#1496
