### ISSUE TITLE
Puchase window popup when you already have buyed

### ISSUE THREAD

**Issue by NgLoader** [k0shk0sh/FastHub#2193]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

When your trying to click on Review changes the Purchase window popup (Buyed enterprise)

_Sent from my Galaxy S8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Hi there, purchasing enterprise only grant you to login with enterprise account and does not provide any pro features.
