### ISSUE TITLE
Organisations show only one organisation

### ISSUE THREAD

**Issue by mgks** [k0shk0sh/FastHub#2194]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** XT1686  
---

 I'm a pro user but only able to see one of my two organisations here.

Please do look into it.

**Comment by k0shk0sh** [comment]
Being Pro or not doesn't effect that. 

Best bet is u open the FAQ from the app or search the issues here to be able to see all ur orgs.
