### ISSUE TITLE
Create issues/Prs labels from within the app

### ISSUE THREAD

**Issue by shgaurav** [k0shk0sh/FastHub#220]
Is this possible?

**Comment by k0shk0sh** [comment]
Couldn't get you? could you elaborate? If you mean assign assignees to your issue, then yes you can do it since 1.2.0 or 1.1.0.

**Comment by shgaurav** [comment]
No i meant assigning a label which says "high priority" or "low priority" etc.

**Comment by k0shk0sh** [comment]
So you mean labeling? If so, then it exists since 1.0.0, you could label issues, pull requests as long as you are either owner of repo or collaborator. Matter of fact, I'll this issue with some labels from app now.

**Comment by shgaurav** [comment]
Yes i know but a customized label. Right label include bug and stuff. How can i get a label for urgency...there is none available yet in the label options

**Comment by k0shk0sh** [comment]
Ah, I got you, you mean like creating labels from within the app, currently FastHub does not support that, the labels currently have to be created from GitHub first then you can use them in FastHub. i'll see if I got slot to put it in sunday release. i'll buzz this issue if I ever commit something about it.

**Comment by shgaurav** [comment]
Alright, thanks!
