### ISSUE TITLE
Unable to download from private repository

### ISSUE THREAD

**Issue by Aericio** [k0shk0sh/FastHub#2205]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR  
- **Model:** Honor View 10  
---

 Cannot download .zip from a private repository. Android Download Manager says "Download unsuccessful" when I attempt to download.

**Comment by k0shk0sh** [comment]
That's true, I have answered this in the many dups of this.

**Comment by Aericio** [comment]
Alright.
