### ISSUE TITLE
Temporary storage

### ISSUE THREAD

**Issue by virendera** [k0shk0sh/FastHub#2212]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** POCO F1  
---

 I notice that there is no provision to store feed and project in local device every time you need data connection to get old feeds from server. It should be work as Gmail feature as all old email save in local device and only new emails downloaded when synchronized.

**Comment by k0shk0sh** [comment]
This has been revised in FastHub v5 as the whole app will always load from local db first. 

It will be shipped when v5 is done. Thanks for your patience
