### ISSUE TITLE
didnt receive pro licence

### ISSUE THREAD

**Issue by poisonborz** [k0shk0sh/FastHub#2216]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

just bought pro, but pro features are not unlocked, eg. if I try to comment on a pr the buy FH popup comes up.
tried to tap on restore purchase, success toast comes, but nothing happens

**Comment by k0shk0sh** [comment]
Please logout and login again, if that didn't work, then please uninstall and install the app.
