### ISSUE TITLE
Feature: Enumerate number of commits in repository and branches

### ISSUE THREAD

**Issue by md500** [k0shk0sh/FastHub#222]
Is possible to enumerate number of commits to each repository in a certain branch? Ej. Linux Kernel Repository: In master branch: 420,000 commits

**Comment by k0shk0sh** [comment]
Well, I'm not really sure tbh, I haven't seen it passed along with data returned by the API, if it isn't possible I'll update later.

**Comment by kutsan** [comment]
@k0shk0sh Here you go: https://api.github.com/repos/k0shk0sh/FastHub/stats/participation

**Comment by k0shk0sh** [comment]
@kutsan thanks buddy :)

**Comment by k0shk0sh** [comment]
@kutsan this is weekly commits count and not over all,  however even if we use https://api.github.com/repos/k0shk0sh/fasthub/stats/contributors still the count is incorrect comparing to the GitHub commit count in Github repo. this will go into in preview until we figure out a way of doing it.

**Comment by kutsan** [comment]
I thought you can sum all of them but you are right. Seems like they contain only 52 weeks.

**Comment by k0shk0sh** [comment]
@kutsan  even this https://api.github.com/repos/k0shk0sh/fasthub/stats/commit_activity doesn't help, and I found something weird, if you to write FastHub there will be nothing to show, only when you use small case then it'll work :D

**Comment by kutsan** [comment]
Why they just not serve all informations about that repo under URL like `repos/k0shk0sh/fasthub/stats/`. So, the only way get that count, fetch the HTML URL as XML and parse, get commits count?

**Comment by k0shk0sh** [comment]
@kutsan because it's GitHub 😁

**Comment by kutsan** [comment]
Okay, I found the "only" way to get total number of commits but little expensive, not sure is it worth though.

Here is it:
https://api.github.com/repos/k0shk0sh/FastHub/commits?per_page=100&page=1
https://api.github.com/repos/k0shk0sh/FastHub/commits?per_page=100&page=2
https://api.github.com/repos/k0shk0sh/FastHub/commits?per_page=100&page=3
... then, sum of length of array.

Yeah, a lot of HTTP request. Can't imagine what will happen for 1K+ commits. And probably, we need cloud functions for that. Otherwise not gonna happen.

**Comment by kutsan** [comment]
And as I said the other way, fetching `https://github.com/k0shk0sh/FastHub` link as HTML and then Regex search `\d+\scommits` something like that, more hack-ish but not so expensive.

**Comment by k0shk0sh** [comment]
I guess, the latter is better, not to expensive. but then, I haven't decide yet to do sniffing :D

**Comment by k0shk0sh** [comment]
@kutsan alright we might be able to do it via search commits api, but its in preview so we just do it and if it breaks its okay I guess. Not a big deal

**Comment by kutsan** [comment]
We finally found the real answer and this is single request only.

Just make a HTTP GET request to this link `https://api.github.com/repos/k0shk0sh/FastHub/commits?per_page=1` or your repository and you need to see HTTP response headers. See `Link` fields, second link's `page=` property gives you the last page which is total number of commits.

![](https://i.imgur.com/Ln5aO85.png)

**Comment by k0shk0sh** [comment]
this issued fixed by this commit 8e8baca
