### ISSUE TITLE
Suggest new feature

### ISSUE THREAD

**Issue by FranciumF** [k0shk0sh/FastHub#2225]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P20 Pro  
---

  Add choice for repo on the navigation bar 
Add ability to set default start screen to repo/starred instead of notifications

**Comment by yakov116** [comment]
@FranciumF 	thanks for your suggestion. This has been discussed in the past.

Please search the issues
