### ISSUE TITLE
FastHub, thing that I have no idea what it is, has been very shady on me

### ISSUE THREAD

**Issue by paul300497** [k0shk0sh/FastHub#2230]
It was yesterday, 15.00 to be more precise. Outside was raining and I just woke up. I wait for an e-mail and thus I have checked my mail inbox, and guess what? Apparently my GitHub has recently authorized an OAuth app named "FastHub". This happened at 8 a.m., at 8 a.m. also, my GitHub password was changed.

Now, I have no idea what FastHub is, or why would someone want to change my GitHub password, but apparently someone does.

Tell me how to upload images via phone, and I will show proof to back what I am saying.

**Comment by dedepete** [comment]
You account might be hijacked. Please, enable 2FA and reset your password.  
This issue has appeared recently in #2224.
