### ISSUE TITLE
Wikis Don't Work

### ISSUE THREAD

**Issue by ClockworkSquirrel** [k0shk0sh/FastHub#2240]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** HMD Global  
- **Brand:** Nokia  
- **Model:** Nokia 7 plus  
---

When tapping the Wiki button on a repo that has a wiki, nothing actually loads. Just a blank page.

**Comment by Avi-D-coder** [comment]
see: https://github.com/k0shk0sh/FastHub/issues/1972#issuecomment-437706519
