### ISSUE TITLE
Changing to dark theme

### ISSUE THREAD

**Issue by milianj** [k0shk0sh/FastHub#2241]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Essential Products  
- **Brand:** essential  
- **Model:** PH-1  
---

 Unable to use dark theme with paid version, restart didn't work. Reinstall didn't work.

**Comment by milianj** [comment]
Under menu setting theme,apply restart. Page says Android dummy content. Close and restart app settings did not take

**Comment by yakov116** [comment]
@milianj screenshot? 

Its working by me.

![](https://i.imgur.com/LnAiGKk.png)

**Comment by k0shk0sh** [comment]
Logout and login again, if that didn't work, reinstall the app
