### ISSUE TITLE
Back button on trending not expected behaviour

### ISSUE THREAD

**Issue by dewinterjack** [k0shk0sh/FastHub#2243]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note9  
---

 Pressing the back button on a trending item takes you home, not back to where I just was in trending.

Using my phones back button does take me where I want, back to trending.

**Comment by k0shk0sh** [comment]
You answered yourself tho, that's an intended behavior and hopefully will change in v5 to more better one!
