### ISSUE TITLE
Wrong order of issue assignee and assigner

### ISSUE THREAD

**Issue by sindrenm** [k0shk0sh/FastHub#225]
Hi! Thanks for the great app!

I've found one bug in the issue detail view, it states that the assignee of an issue is actually the assigner and vice versa.

---

**Example:**
Given that I (@sindrenm) assign an issue to you (@k0shk0sh), it should say something like this:

> @sindrenm assigned @k0shk0sh _x time ago_.

The app shows it the other way around:

> @k0shk0sh assigned @sindrenm _x time ago_.

Another correct way of phrasing it is what github.com currently does it:

> @k0shk0sh was assigned by @sindrenm _x time ago_.

---

- **Android version:** 7.1.2
- **FastHub version:** 1.4.1

**Comment by k0shk0sh** [comment]
Good catch, really good one :D . 

Thanks.

**Comment by sindrenm** [comment]
Great response time! O_O

**Comment by k0shk0sh** [comment]
I'm in the middle of working on some stuff, so my eyes are on here to track issues :p

**Comment by sindrenm** [comment]
I would love to submit a PR, btw, but I don't have time to set up the app right now. If you haven't fixed it before the weekend, I might be able to give it a go. :smile:

**Comment by k0shk0sh** [comment]
I'll be doing it right now tho :D because i'm targeting Sunday for another release with new features & enhancements. you could do another one tho :p, but please let me know so at least we don't waste time but working on it both of us. 

P.S: I appreciate your offer & I hope people actually start submitting PRs.

**Comment by sindrenm** [comment]
Perfect! I'm assuming it's a quick fix, and you will definitely spend less time on it than I will, so go ahead. :wink: 

Looking forward to seeing what's new on Sunday! :grinning:

**Comment by k0shk0sh** [comment]
Well, I just reacted to your comment using FastHub, so this will be in Sunday's release :p
