### ISSUE TITLE
Unable to create file if path contains space

### ISSUE THREAD

**Issue by robdyke** [k0shk0sh/FastHub#2252]
**FastHub Version: 4.6.7**  
**Android Version: 6.0.1 (SDK: 23)** 
---

Unable to create a file when path in repo contains a space.

**Comment by robdyke** [comment]
Thanks @k0shk0sh - hadn't had the opportunity to get to a browsers and triage this for myself.

The in-app 'report a bug' is super cool.

**Comment by k0shk0sh** [comment]
@robdyke you could search issues using the app :). 
Navigate to the FastHub repo and click on issues and then on the floatingbutton and from there you can filter issues as you want :)

**Comment by robdyke** [comment]
I totally asked for that...
Currently reviewing issues, see if there is anything I can help with.

**Comment by k0shk0sh** [comment]
Awesome, please be aware that im no longer maintaining FastHub current dev branch but rather rewriting it in v5 branch :)
