### ISSUE TITLE
Merge details and comments views on issues

### ISSUE THREAD

**Issue by seaneking** [k0shk0sh/FastHub#226]
Is there a particular reason the comments in an issue are in a separate view from the original comment/issue description? In every other GitHub UI I have seen (including GitHub itself) comments are just tacked on in a single thread. This behavior seems much more intuitive.

**Comment by k0shk0sh** [comment]
Well, currently i'm in the middle of this, like add reactions & more intuitive UI for comments, 

The problem with what you mentioned would be the pagination for each one, plus the current descriptive UI for labels. I'll try and make this happen as soon as possible.

#59 #94
