### ISSUE TITLE
Followers/Following not updating

### ISSUE THREAD

**Issue by geocine** [k0shk0sh/FastHub#2265]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** POCO F1  
---

My followers/following list is not updating. I tried logging in an logging out but still, the old list is showing

**Comment by yakov116** [comment]
@geocine still an issue?
