### ISSUE TITLE
Unable to Change Labels

### ISSUE THREAD

**Issue by davcpas1234** [k0shk0sh/FastHub#2267]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

I get a not found toast when attempting to Change labels on any of my repos

**Comment by yakov116** [comment]
@davcpas1234 still have an issue?

**Comment by davcpas1234** [comment]
Yes, I'm still experiencing the same issue.

**Comment by davcpas1234** [comment]
![Screenshot_20191229-104843_FastHub](https://user-images.githubusercontent.com/3764587/71555890-caefe800-2a28-11ea-8e0a-86c103034cc4.jpg)

Here's what I get when I attempt to edit the labels on one of my repos

**Comment by yakov116** [comment]
@davcpas1234 is it an organization?

**Comment by davcpas1234** [comment]
Yes, most of the repos I own are based under my organisation

**Comment by yakov116** [comment]
@davcpas1234 OK so then the issue is that fasthub does not have the correct permissions in your organization.  Please see the FAQ.

**Comment by k0shk0sh** [comment]
Pleas refer to the FAQ from the app drawer, you must login via access token

**Comment by davcpas1234** [comment]
Thank you @yakov116 I've checked the organisations third party access and github had denied access. All sorted now.
