### ISSUE TITLE
No dark theme

### ISSUE THREAD

**Issue by aduguid** [k0shk0sh/FastHub#2269]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S9+  
---

 I've got a new phone and applied my purchase but I still can't get the dark theme to work.

**Comment by yakov116** [comment]
@aduguid still an issue?
