### ISSUE TITLE
Greek Alphabet Characters not appearing correctly

### ISSUE THREAD

**Issue by Dimitrees** [k0shk0sh/FastHub#227]
Hello, while browsing in a repository through the application, I noticed that all Greek characters are not appearing properly, but instead some weird symbols are shown. I would like to know if you would consider fixing this, and if so, if I can be assigned to fix this. 

Android Version

Thanks

**Comment by k0shk0sh** [comment]
Hello @Dimitrees thanks for opening the issue, could you point that Repo for me, & if its something that can be fixed i'll appreciate all the prs.

**Comment by Dimitrees** [comment]
Thanks for the quick response, 

Here https://github.com/tushartushar/theGreekLegacy you can browse in the legacy.md file while in an android device. Check out the symbols appearing and confirm that this is an actual issue.

**Comment by k0shk0sh** [comment]
Alright, I got it. it seems like even **Postman** has the same issue, you could try and see if its something fixable, which I guess it would be. but can't confirm on it.

**Comment by Dimitrees** [comment]
UPDATE : 
This is not an issue of FastHub, this was caused because of an error in the character encoding in the file I was looking into. Greek characters are appearing correctly in other repositories. 

Sorry for the needless fuss.

**Comment by k0shk0sh** [comment]
Cool, that's great news then :). 
Thanks though, appreciate the effort you put in.
