### ISSUE TITLE
The "back button" at the top left of the screen can take you back to the search page and not to the previous repo you were in. 

### ISSUE THREAD

**Issue by scarab5q** [k0shk0sh/FastHub#2280]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5T  
---

 This is incredibly weird when browsing the "awesome list" repos and you want to go back to the original repo. I know you can do this with the android back button and I have learned to do so but this is quite frustrating sometimes.

**Comment by k0shk0sh** [comment]
The back button navigate you deep in hierarchy of the context you are in, use the device back button to navigate where you were!.
