### ISSUE TITLE
Commit info popup flashes rapidly

### ISSUE THREAD

**Issue by andrewfhou** [k0shk0sh/FastHub#2281]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 when pushing the info button in a commit, the screen flashes rapidly when the pop up for the full commit message is open

**Comment by yakov116** [comment]
Update to the latest
