### ISSUE TITLE
No notification shows on app

### ISSUE THREAD

**Issue by virendera** [k0shk0sh/FastHub#2292]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
---

 Why there is no notification shows on this app? I subscribe to a project and all notification for this threads are coming to my mail it annoying me :angry:. When will be new update are coming.

**Comment by laloch** [comment]
I can confirm the issue. No notifications on Android Pie (vanilla Android One) for me either.

**Comment by k0shk0sh** [comment]
You have to manually set notification interval in app/settings/notification.

@virendera why so angry? This isn't GitHub official app so I can't do anything about that. If you got an issue, please contact them.

**Comment by laloch** [comment]
> You have to manually set notification interval in app/settings/notification.

I did, of course, set the Sync interval to five minutes. No notifications whatsoever.
I did, however, find a workaround just a few minutes ago - I had to disable "Battery optimization" for FastHub app and now the notifications seem to work. Maybe some new kind of wakelock on Android 9?

**Comment by laloch** [comment]
May it be related to what the guys from KDE Connect team describe in [this blogpost?](https://nicolasfella.wordpress.com/2018/11/04/kde-connect-new-stuff-0x3/)
>Furthermore, Android Oreo introduced some restrictions in regard to apps running in the background. In the future in order to be able to run in the background KDE Connect needs to show a persistent notification.

**Comment by k0shk0sh** [comment]
The app doesn't run in background but it trigger a scheduler job that runs with respect to the user device settings.

**Comment by laloch** [comment]
OK, I did not really take the time to look into the sources, sorry for that.
The "Battery optimization" trick turned out to __not__ solve the issue. Still no notifications for me after several minutes of inactivity :(

**Comment by k0shk0sh** [comment]
What's your device info? It seems like u modified the data.

**Comment by laloch** [comment]
My phone is Xiaomi Mi A2 Lite, Android 9, patch level April 1, 2019.
> It seems like u modified the data.

Does not compute :) Modified what and where?

**Comment by Androz2091** [comment]
I have the same problem...
Here are my device informations :
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** Honor 8 Lite

**Comment by k0shk0sh** [comment]
@Androz2091 did you enabled it from settings and set an interval?

**Comment by Androz2091** [comment]
Yes
The interval is set on "1 minute"
