### ISSUE TITLE
Wiki are not shown....

### ISSUE THREAD

**Issue by naveedhassan913** [k0shk0sh/FastHub#2293]
**FastHub Version: 4.6.7**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Infinix  
- **Brand:** Infinix  
- **Model:** HOT 4 PRO  
---

 

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
... please search the issues
