### ISSUE TITLE
Wiki pages are blank

### ISSUE THREAD

**Issue by Kazzline** [k0shk0sh/FastHub#2294]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MIX 2  
---

 When opening any projects wiki page everything is blank. No text, buttons, or links.

**Comment by Kazzline** [comment]
If it's a duplicate then which Issue # are you working from on this?

**Comment by yakov116** [comment]
@Kazzline 	which one of the 50 issues would you like me to link it to?

Please search the issues
