### ISSUE TITLE
Wiki pages are empty

### ISSUE THREAD

**Issue by akalongman** [k0shk0sh/FastHub#2297]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

**Comment by akalongman** [comment]
@yakov116 closed?

**Comment by yakov116** [comment]
@akalongman please search anmd you will see there are approx. 50 such issues
