### ISSUE TITLE
Test Feedback

### ISSUE THREAD

**Issue by tttcx** [k0shk0sh/FastHub#2299]
**FastHub Version: 4.6.7-debug**  
**APK Source: Unknown**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer&Brand:** Google  
- **Model:** Android Emulator  
---
This is the first demo feedback

**Comment by yakov116** [comment]
@tttcx please stop testing!!! There is no need to notify 1000 people that you are testing
