### ISSUE TITLE
Expand tree files

### ISSUE THREAD

**Issue by shenahobo** [k0shk0sh/FastHub#230]
could you make a faster file tree?

**Comment by k0shk0sh** [comment]
this will literally require calling api on each directory & their subs? which going to be tedious.
We are not doing anything different from GitHub.

**Comment by GeorgeWL** [comment]
I don't see reason for it tbh

**Comment by k0shk0sh** [comment]
@GeorgeWL actually there is a way to do that with only one api call, but this will require restructure of the current implementation. Im keeping an eye on it and as soon as I'm free, it'll be there
