### ISSUE TITLE
Back button in trends goes too far

### ISSUE THREAD

**Issue by paperbenni** [k0shk0sh/FastHub#2308]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4)  
---
Steps to reproduce: 
1. Go into the trending section
2. Tap on any entry
3. Tap the top left back button

It goes all the way back to the starting page instead of putting you in the trending section.

**Comment by k0shk0sh** [comment]
Use the phone back button and only use the top button if u wanna navigate deep in hierarchy .
