### ISSUE TITLE
White on white status bar in about screen

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#231]
• __Android version :__ 7.1.1  
• __FastHub version :__ 1.5.1
-------

https://goo.gl/photos/nHsTtaddu4t4zroeA

**Comment by kutsan** [comment]
Good catch. Thanks for reporting.

**Comment by Younes-L** [comment]
Btw, I am using the dark theme. Any plans for the _About_  screen to follow the _Settings_  layout ?

**Comment by k0shk0sh** [comment]
I guess, I just forgot about it. It shall be fixed in next release.
