### ISSUE TITLE
The screen keeps flashing when click the detail of RELEASE

### ISSUE THREAD

**Issue by NieLamu** [k0shk0sh/FastHub#2310]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 4  
---

 Not all of the RELEASEs make this.

**Comment by k0shk0sh** [comment]
#2187 #2281
