### ISSUE TITLE
Weird flickering when viewing commit description.

### ISSUE THREAD

**Issue by KevinNovak** [k0shk0sh/FastHub#2311]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6  
---

See video:
https://drive.google.com/file/d/1qL92-KfrvwyyNMeQw6kpHfq5CdigEFIh/view?usp=drivesdk 

Edit: updated link

**Comment by rama982** [comment]
+1

**Comment by oscartbeaumont** [comment]
I am also getting this on my phone.

**Comment by DragoCubed** [comment]
This is really getting on my nerves.
