### ISSUE TITLE
Status Bar issue with Galaxy S7

### ISSUE THREAD

**Issue by charlie1024** [k0shk0sh/FastHub#2313]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7  
---

 ![](https://i.imgur.com/ELye9T0.jpg)

Hello,
Like this, in the main screen with Dark themes the status bar doesn't appear. Except of the screen, status bar font color is white, which is entirely visible but in the main display, I cannot see what the status bar has. I would appreciate if the bug can be fixed.

I think #2178 would be similar one but the article hasn't any pictures so I'll attach the screen picture.

Thank you.

**Comment by k0shk0sh** [comment]
all u got to do is restart the app. its a glitch in the framework.
