### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by anudeep0007** [k0shk0sh/FastHub#2316]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---
When I try to download a file it vibrates and does nothing.. Iam not able to download any file.. Plz help me

**Comment by alialooooosh055455** [comment]
- [ ] - [x] 1. - ### **~~_
-------
`
> [](add this)` _ ~~ **

**Comment by alialooooosh055455** [comment]
_Sent from my Galaxy S7 edge using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alialooooosh055455** [comment]
:grinning:

**Comment by alialooooosh055455** [comment]
-

**Comment by alialooooosh055455** [comment]
![](https://i.imgur.com/DymWbnz.png)

**Comment by dedepete** [comment]
@alialooooosh055455 stop spamming or you will be banned.

_Sent from my P2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
