### ISSUE TITLE
Commit info page not working

### ISSUE THREAD

**Issue by jjmark15** [k0shk0sh/FastHub#2317]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note9  
---

 Pressing the info button on a commit causes the screen content to rapidly alternate between seemingly several states.

**Comment by deandreamatias** [comment]
This issue its report here #2311 
DUPLICATED
