### ISSUE TITLE
After refresh unable to remove emojis

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#232]
I can add an emoji multiple times on a comment, but refreshing the screen only shows it added once.

**Comment by kutsan** [comment]
Thanks. It's a known bug. Will be fixed.

**Comment by k0shk0sh** [comment]
I'm not even sure if I'm ever to fix it, since I'm not planning decouple the recyclerview with an api call for each comment.

**Comment by eygraber** [comment]
I haven't looked at source much (I plan to, and make contributions, but work has been crazy 😁 ), but is there a reason not to do that, or you just don't want to re-architecture it?

**Comment by k0shk0sh** [comment]
@eygraber too much to do in the row item level reactions api is still in preview and is sucks

**Comment by eygraber** [comment]
@k0shk0sh now it limits me to adding an emoji twice 😁 (i.e. I can click an emoji twice and it'll show 2 in the counter, but if I refresh there's 1).

**Comment by k0shk0sh** [comment]
@eygraber I guess I'll need to add another hack if that's the case lol

**Comment by nyuszika7h** [comment]
I can still add reactions an unlimited number of times on 2.1.0.

**Comment by yakov116** [comment]
@nyuszika7h but upon refresh its gone no?

**Comment by nyuszika7h** [comment]
Nope, I have to press the back button and go back to the issue for it to be gone.

Normally you can also take away your reaction by clicking on it again, so this is pretty confusing.

**Comment by nyuszika7h** [comment]
Nope, I have to press the back button and go back to the issue for it to be gone.

Normally you can also take away your reaction by clicking on it again, so this is pretty confusing.

**Comment by yakov116** [comment]
@nyuszika7h in other words we have a bug. Unable to remove an emoji!

**Comment by k0shk0sh** [comment]
In user point of view its a bug, but in terms of development & api limitations it's not, 
1. There is no way I could tell if user liked the comment but loading all the users for reactions & loop through them to check that.
1. Fasthub taking care of your first like, wait a second & you shall be able to unlike it.
1. I have contacted GitHub about this, they said they considering adding proper api for this, but that was two months ago.
1. Nothing much I could do here tbh.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyuszika7h** [comment]
I see. But if the user has already reacted within the current session in the app, that can be cached locally, and for the other cases, you should be able to just re-request the counts after the user reacts.

**Comment by k0shk0sh** [comment]
@nyuszika7h I'm doing that, but once you click it multiple times at once, I can't do much, maybe a progress to hang you there until request is finished or disable that item until it's finished. 
Please do open another issue instead. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
