### ISSUE TITLE
Issue with app bar layout.

### ISSUE THREAD

**Issue by Kashish-Sharma** [k0shk0sh/FastHub#2327]
First click is not working when scrolling back to the top in any recyclerView.
This is a known [issue]( https://issuetracker.google.com/issues/66996774 ) when working with AppBarLayout and recyclerView.
It seems like it's fixed in AndroidX, but for support library we need to use [FixAppBarLayoutBehavior.java](https://gist.github.com/chrisbanes/8391b5adb9ee42180893300850ed02f2).

FastHub version: 4.6.7
Devices: Samsung Galaxy J5, J7, LG V30, Oneplus 6 etc.

**Comment by k0shk0sh** [comment]
in latest release i migrated to androidx, could u please check it out
