### ISSUE TITLE
Add support for autocompletion of GitHub usernames in issue editor

### ISSUE THREAD

**Issue by faroit** [k0shk0sh/FastHub#2328]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia XZ2 Compact  
---

 the GitHub web editor supports autocompletion on @user names which is quite convenient when you want to address people as they get notified. I don't know if github provides an API for this, though

**Comment by yakov116** [comment]
@faroit 	currently its supported in the full edit view (not in the small comment box on bottom)

**Comment by faroit** [comment]
that's great to know. thanks
