### ISSUE TITLE
Login Menu

### ISSUE THREAD

**Issue by XD-chill-bro** [k0shk0sh/FastHub#2329]
**FastHub Version: 4.6.7**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** malata  
- **Brand:** VORTEX  
- **Model:** BEAT 8  
---

 In the first order of logging in to fasthub you allow the user to enter there username and password, what I would like to see is the "username" string changed to "username/email" so people who are new will know that they can enter there email instead of there username only.

**Comment by yakov116** [comment]
@XD-chill-bro 	thanks for your feedback
