### ISSUE TITLE
Black on Dark Grey in Dark theme until switch theme on and off

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#233]
Seems somewhat random, and to not affect all screens either. 

![](http://i.imgur.com/ByzHORV.png)

**Comment by k0shk0sh** [comment]
Could you let me know, what OS & phone are u using.

**Comment by GeorgeWL** [comment]
Android Latest,  Sony Xperia z5, 


On app open. Does continue through app restarts. 

Changing theme seems to be the only fix for me.

But it doesn't happen every app open/restart.

**Comment by k0shk0sh** [comment]
@GeorgeWL thanks for your response, one last thing to confirm on, did you update to 1.5.0?

**Comment by GeorgeWL** [comment]
Ooh no I've not, my Internet is bad.  

You think it's fixed in that?

**Comment by k0shk0sh** [comment]
Owh man, you got me cracked-up here because I was like for real? because in 1.5.0 Dark Theme is fixed & shouldn't have any single problem as I dropped the buggyaf Night/Day mode and used custom themes instead. please update to 1.5.1(latest) so you could enjoy a lot of stuff :)

**Comment by GeorgeWL** [comment]
Ha,  yeah,  and due to shit Internet my phone didn't even recognise there was an update until I physically went in to the play app.

**Comment by k0shk0sh** [comment]
I know that feeling :D .. you could watch the repo so you be notified when there is a new release happened. I'll usually release here before I release to PlayStore. 
P.S: 1.5.1 has some issues that are report and i'm expecting to update new version today.
