### ISSUE TITLE
Add Starred topics

### ISSUE THREAD

**Issue by Hunter9888x** [k0shk0sh/FastHub#2335]
Starred topics
https://github.com/stars?direction=desc&filter=topics&sort=created
Browse the top used topics on GitHub
https://github.com/topics

Openhub (Has featured topics)
https://github.com/ThirtyDegreesRay/OpenHub

**Comment by Hunter9888x** [comment]
apk-editor topic
https://github.com/topics/apk-editor
translate-plugin topic
https://github.com/topics/translate-plugin

**Comment by Hunter9888x** [comment]
https://github.com/topics

**Comment by Hunter9888x** [comment]
Openhub
(Has featured topics)
https://github.com/ThirtyDegreesRay/OpenHub

**Comment by yakov116** [comment]
>Openhub (Has featured topics)
>ThirtyDegreesRay/OpenHub

Stole the code from us
