### ISSUE TITLE
Feature Request: Copy-Paste in Issues (or everywhere!)

### ISSUE THREAD

**Issue by dcode** [k0shk0sh/FastHub#2342]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** SM-G975U1  
---

 I'd like the ability to select portions of an issue and copy/paste that into a reply or even another issue. Today, holding down on any rendered text in an issue doesn't do anything. I expect I'd get a popup allowing me to select and copy the desired text.

**Comment by DragoCubed** [comment]
It works on Android 5 :/

**Comment by k0shk0sh** [comment]
it works for me perfectly and I guess for everyone else. 

could u please update to latest and keep an eye on it? 

thanks
