### ISSUE TITLE
Trending for Weekly and Monthly fails to load

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#2343]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

1.  Access the Trending View
1.  Slide open the right side drawer
1. Select Weekly or Monthly
1. States failed to load
1. Attempting to refresh the feed doesn't make the trending items load

**Comment by GeorgeWL** [comment]
Doesn't seem to be consistently happening on each opening of the trending view, but when it does fail, no amount of refreshing loads the data.

**Comment by jsmithdev** [comment]
Ditto here with Pixel 2 XL

**Comment by cheetosysst** [comment]
Same on redmi 6, for a long time

**Comment by GeorgeWL** [comment]
My first guess: and this should be relatively easy to test using the built in tools of Android Studio, slow network causes the request to fail, and the API handler isn't being told to return an error/retry, so just silently fails and leaves the page blank. @k0shk0sh

**Comment by k0shk0sh** [comment]
Trending stopped working because my scrapping failed, it has nothing to do with network!

**Comment by GeorgeWL** [comment]
@k0shk0sh duplicate of which issue btw? think you could link it?

**Comment by k0shk0sh** [comment]
There are dozens of this issue around, a search will lead you to at least 50 issues or more!

**Comment by GeorgeWL** [comment]
You need any helpers by any chance? I'd be up for adding some PRs every now and again.
