### ISSUE TITLE
Erro de alteração no gir

### ISSUE THREAD

**Issue by AlvaroPereiradoNascimento** [k0shk0sh/FastHub#2353]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

 when I save an edited file  give a error: fail to access de server

**Comment by yakov116** [comment]
@AlvaroPereiradoNascimento we need more info
