### ISSUE TITLE
Screen layout missing on bottom

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#236]
No matter which screen I'm on I am missing an inch on the bottom!

**Comment by yakov116** [comment]
I also cannot attach a screen shot just shows []()

**Comment by k0shk0sh** [comment]
I hope you can add a screenshot tho, because tbh I didn't get your issue.

**Comment by yakov116** [comment]
I will add the 2 screenshots 
![screenshot_20170402-214854](https://cloud.githubusercontent.com/assets/16872793/24593155/7a4c304c-17ee-11e7-9a2c-d58fe9903178.png)
![screenshot_20170402-214925](https://cloud.githubusercontent.com/assets/16872793/24593156/85356532-17ee-11e7-991a-bcd770b57456.png)

**Comment by yakov116** [comment]
you were correct! fixed!

What about the second issue?

**Comment by yakov116** [comment]
Also it took me a while to figure out where the "issues" tab was.

**Comment by yakov116** [comment]
for such quick service i have donated $5.00 thanks for your support

**Comment by k0shk0sh** [comment]
@yakov116 thanks :). 
For the second issue, I'm planning to add it very soon. It just that I didn't find slot for it in 1.5.0. hopefully 1.6.0 will have it.

**Comment by yakov116** [comment]
would like if you would show "Thanks for your support" after giving a donation

**Comment by k0shk0sh** [comment]
@yakov116 I'm showing thanks for being awesome msg, isn't showing? I'm going to change that screen with new UI because tbh it looks ugly 😂
