### ISSUE TITLE
Invalid relocation when using return arrow after looking trending repo

### ISSUE THREAD

**Issue by iemejia** [k0shk0sh/FastHub#2360]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** moto g(7)  
---

When sing return arrow after looking trending repo it does not return to the list of repos (as user would expect) but to the main page.

Forgot to thank for the app. It is awesome! Great job!

**Comment by k0shk0sh** [comment]
Use the device back button, I have answered similar questions as well explaining more in details. Please use the search functionality from FastHub to find if the issue exists.


Thanks

**Comment by iemejia** [comment]
Ok sorry for the noise. I submitted this bug report with the app which probably should suggest a search or similar issues first.

**Comment by k0shk0sh** [comment]
Yeah, something to think about in v5 :)
