### ISSUE TITLE
Purchases not restoring at all

### ISSUE THREAD

**Issue by nwiadomodemo** [k0shk0sh/FastHub#2362]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Mi A2 Lite  
---

My issue is if I click "restore purchases" in menu on the left, my pro isn't restoring from google play.

E-Mail: nwiadomodemo@gmail.com

Note: English is not my native language so I could make some mistakes

**Comment by dedepete** [comment]
See #2216.
