### ISSUE TITLE
"releases" tab empty even after refresh

### ISSUE THREAD

**Issue by twig** [k0shk0sh/FastHub#237]
https://github.com/furqanZafar/react-selectize/releases

I searched for "react selectize" in the browser and opened fasthub from the first result.

When I clicked on releases tab, it was empty.

The website shows 49 releases.

Let me know if you need any further information.

**Comment by k0shk0sh** [comment]
Thanks, that's strange because I can see all others releases. Will check on it.

**Comment by twig** [comment]
Thanks @k0shk0sh. You able to replicate it?

**Comment by k0shk0sh** [comment]
@twig from the link you provided, yup I can't seem to see any releases
