### ISSUE TITLE
Where to see v5 roadmap

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [k0shk0sh/FastHub#2373]
I am trying v5 and there are some issues that they are features not implemented yet (I can't open repos, settings, etc).

How can I see what is already implemented so I can know if it is an issue or a 'known issue"

**Comment by k0shk0sh** [comment]
That's a good question, I'll write up the roadmap into the branch readme later. 


Thanks

**Comment by k0shk0sh** [comment]
So far:

Search, trendings, profile, issue/prs filter, issue screen (not done yet), orgs, multiple accounts, logout, login.

That's what in my mind right now, but I'll finalize it later

**Comment by SecT0uch** [comment]
A roadmap would be great

**Comment by k0shk0sh** [comment]
@SecT0uch the roadmap is within the PR :)

**Comment by k0shk0sh** [comment]
Closing this as the roadmap is within the PR now :)
