### ISSUE TITLE
Too much ads

### ISSUE THREAD

**Issue by JayjeetAtGithub** [k0shk0sh/FastHub#2379]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy J7 Max  
---

  Too much ads are coming...very annoying

**Comment by k0shk0sh** [comment]
Huh? What ads are u talking about? The app doesn't have any ads.....
