### ISSUE TITLE
App crashed after opening GitHub link in another app

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#238]
I clicked a GitHub repo link in another app, and chose to use FastHub to open it. The repo loaded, and then after a couple of seconds FastHub crashed.

**Comment by eygraber** [comment]
I sent feedback from Android's crash reporting tool. It has the message "Crash report for issue #238"

**Comment by k0shk0sh** [comment]
If the crash occur then I should be getting it. Could you let me what is your phone? So I could later filter by it.

P.S: I just opened this issue from slack & chose FastHub, no crash :p

**Comment by eygraber** [comment]
It's a Pixel running 7.1.1
