### ISSUE TITLE
Notification bar icons bad color on blue theme

### ISSUE THREAD

**Issue by JesseyWhite** [k0shk0sh/FastHub#2386]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8+  
---

When using the premium dark blue theme, the notification bar icons are too dark to see easily. To fix the issue, just need to set a lighter colored icons.

Picture that shows issue:
https://drive.google.com/file/d/1N1WGNIikhvBiTkA9oPdmEDng542muzAr/view?usp=drivesdk

Picture that shows properly:
https://drive.google.com/file/d/1Emcx0Sh55ov2kdnnkgA9tSHqv8209wiq/view?usp=drivesdk

**Comment by k0shk0sh** [comment]
Could you please post direct image link.

**Comment by JesseyWhite** [comment]
Fixed links:

Picture that shows issue: https://drive.google.com/uc?id=1N1WGNIikhvBiTkA9oPdmEDng542muzAr

Picture that shows properly: https://drive.google.com/uc?id=1Emcx0Sh55ov2kdnnkgA9tSHqv8209wiq

**Comment by k0shk0sh** [comment]
Owwh, yeah, you need to kill app and reopen again if theme didn't apply properly.
