### ISSUE TITLE
[UI issue] View Overlap in landscape mode

### ISSUE THREAD

**Issue by tzutalin** [k0shk0sh/FastHub#239]
![5a6a8538-0fe4-11e7-8622-8c71b2ac92b6](https://cloud.githubusercontent.com/assets/3283822/24593668/46976676-1858-11e7-9d87-be49f2e26c24.jpg)

- **Android version:** Android M
- **FastHub version:** 1.3.2

**Comment by k0shk0sh** [comment]
We are in version 1.5.1 could you update your app?
