### ISSUE TITLE
Wiki of repo don't load

### ISSUE THREAD

**Issue by tGstep** [k0shk0sh/FastHub#2392]
# system info
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P 8 Lite 2017
---

The wiki section can't load properly, in fact i can load in browser the page. I tested it with the SFML repo, a C++ library.

**Comment by yakov116** [comment]
@tGstep please search the issues
