### ISSUE TITLE
Wrap code setting not working

### ISSUE THREAD

**Issue by bender2k14** [k0shk0sh/FastHub#2395]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG K20 V  
---

The code wrapping setting is not working for me.  I will post screenshots next.

**Comment by bender2k14** [comment]
The code in this image is not wrapped...

![Screenshot_2019-04-20-08-10-53](https://user-images.githubusercontent.com/34664007/56457911-f1f90480-6346-11e9-9864-1c824f751792.png)

...even though I have the setting configured to wrap the code.

![Screenshot_2019-04-20-08-11-29](https://user-images.githubusercontent.com/34664007/56457922-1c4ac200-6347-11e9-955b-e9f2491b5536.png)

This issue seems similar to the recently abandoned issue #1824.

**Comment by k0shk0sh** [comment]
That settings is only applicable to viewing code not comments (including codes).

Only the code viewer.
