### ISSUE TITLE
Starred icon become into unstarred icon after rotating the screen

### ISSUE THREAD

**Issue by dikiaap** [k0shk0sh/FastHub#240]
But the counts is still same.

![screenshot_2017-04-03-09-30-11](https://cloud.githubusercontent.com/assets/8542502/24593783/d0dec8b8-1850-11e7-90ca-ba2648069971.png)
![screenshot_2017-04-03-09-30-23](https://cloud.githubusercontent.com/assets/8542502/24593788/e082b0ea-1850-11e7-9c83-51e872f69036.png)
![screenshot_2017-04-03-09-30-29](https://cloud.githubusercontent.com/assets/8542502/24593789/edb50ee8-1850-11e7-82fb-cca1ce50a384.png)

- **Android version:** 5
- **FastHub version:** 1.5.0

**Comment by k0shk0sh** [comment]
I see that you don't have internet connection? Could it be the cause? The starring happens in background tho.

**Comment by dikiaap** [comment]
Okay, Already connected and it's still same. It's also happens on watch icon.

**Comment by GeorgeWL** [comment]
I just checked, same here.

**Comment by k0shk0sh** [comment]
@GeorgeWL it's fixed, all the new bugs reported are actually fixed but yet to commit as I'm in the middle of adding org support
