### ISSUE TITLE
Feature Request: add stars and language to activity feed repos

### ISSUE THREAD

**Issue by atomi** [k0shk0sh/FastHub#2410]
**FastHub Version: 4.6.7**

I think whatever extra information you could add for the activity feed repos being starred or forked would be nice. But language and the amount of stars would be ideal.

**Comment by yakov116** [comment]
@atomi it's what the api returns

**Comment by atomi** [comment]
@yakov116 Yeah. Of course.

**Comment by yakov116** [comment]
@atomi I'm saying no since we are only showing what the api returns

**Comment by atomi** [comment]
@yakov116 No. I know.

**Comment by yakov116** [comment]
@atomi so what would you like?

**Comment by atomi** [comment]
Well yeah, I suppose making an extra api call per each repo in the activity feed would be too slow? Or pre-fetching the repo information for every repo in the activity feed too many calls? I don't think the api is rate limited.

**Comment by k0shk0sh** [comment]
I'm not interested in this neither find any added value to the feed. 
. thanks
