### ISSUE TITLE
[FR] Create secret gist

### ISSUE THREAD

**Issue by rubaboo** [k0shk0sh/FastHub#2411]
Please provide ability to create secret gists, as explained in [this comment](https://github.com/k0shk0sh/FastHub/issues/1863#issuecomment-482568810). Not ANONYMOUS, which is deprecated, but SECRET, which is a supported functionality.

**Comment by deepseven** [comment]
This is still a problem.

A year ago anonymous gists became deprecated, effectively making the 'left button' in the gist creation screen useless.

As another commenter [suggests](https://github.com/k0shk0sh/FastHub/issues/1863#issuecomment-482568810), the solution might be very simple. Have a look @k0shk0sh !

Related issues: #1863 , #1978 , #1553

**Comment by k0shk0sh** [comment]
@deepseven I'm of that and it will be fixed in v5.

**Comment by deepseven** [comment]
Awesome, thanks @k0shk0sh !

**Comment by k0shk0sh** [comment]
its done in v4.7.0 which will be released later today or weekend.
