### ISSUE TITLE
Is It Better to Merge Details and Comments in Issues?

### ISSUE THREAD

**Issue by coderfox** [k0shk0sh/FastHub#242]
I think the "details" and "comments" tab in an issue should be merged to improve reading experience. Is it proper to change so?

**Comment by k0shk0sh** [comment]
Hello @coderfox  could you please update to FastHub v1.5.1? this has been fixed & updated in yesterday's release. 

Thanks for taking the time to report this

**Comment by coderfox** [comment]
Sorry for the disturb. I thought I have the latest version installed.

**Comment by k0shk0sh** [comment]
@coderfox not disturbing at all. 
Please do keep reporting stuff that you see are either not suitable or needs to be fixed, my only request would be, to search for it before posting to avoid duplication
