### ISSUE TITLE
Open in browser just opens in app

### ISSUE THREAD

**Issue by sonicintrusion** [k0shk0sh/FastHub#2428]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia Z5 Compact  
---

when selecting to "open in browser", the page just reloads in the fasthub app.
There doesn't seem to be an option to disable that behaviour

**Comment by MohamedElidrissi** [comment]
I'm able to reproduce this if I disable chrome, do you have it installed?

**Comment by sonicintrusion** [comment]
yes, i have chrome installed and actively use it.

**Comment by k0shk0sh** [comment]
Hmmm, thats strange, cuz it should launch the chrome tab!!

**Comment by sonicintrusion** [comment]
what version of chrome is supported?

**Comment by k0shk0sh** [comment]
Two years ago chrome version 😢

**Comment by sonicintrusion** [comment]
oh yea. i'm using the stock chrome on my phone. i'll upgrade it and see. thanks

**Comment by yakov116** [comment]
@sonicintrusion still an issue?
