### ISSUE TITLE
Issue labels not readable

### ISSUE THREAD

**Issue by heinrichreimer** [k0shk0sh/FastHub#243]
Issue labels always have the standard text color regardless of which background color they have.
It would be better if the label text color would be calculated based on the background color.
`ColorUtils` from the support library have some useful methods to calculate contrast so you could compare contrast for white and black text color and then decide which would have the most contrast.

**Comment by k0shk0sh** [comment]
Hi Heinrich, any screenshots for that? Text color is either going to be black or white depending on the label background.

**Comment by heinrichreimer** [comment]
![screenshot_20170403-151046](https://cloud.githubusercontent.com/assets/5065698/24611345/15fe3254-1882-11e7-90af-fae703c26bbc.png)
