### ISSUE TITLE
Check checkboxes in issues without editing

### ISSUE THREAD

**Issue by chazapp** [k0shk0sh/FastHub#2434]
**FastHub Version:** 4.6.7  
**Android Version:** 9  
**Device Information:**  
- MANUFACTURER: OnePlus  
- BRAND: OnePlus  
- MODEL: 5T  
---
 - [ ] Example checkbox  

These checkboxes can't be checked by touching them, only by editing the issue and add a x between the brackets.  On desktop Github these checkbox can be checked by clicking on them, this would be a nice addition to FastHub.

**Comment by k0shk0sh** [comment]
unforetunely this isn't possible as this requires to adjust the whole markdown editor to cater fo this.
