### ISSUE TITLE
I cannot see my repositories

### ISSUE THREAD

**Issue by hbrtra2048** [k0shk0sh/FastHub#2435]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Hongmi 6  
---

 I have some code at my repository, I log in my account, I can see my feeds, why can not see my repository?

**Comment by yakov116** [comment]
Use a token and read the FAQ
