### ISSUE TITLE
Tapping reactions multiple times causes them to be constantly subtracted. 

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [k0shk0sh/FastHub#2438]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** SM-G975U  
---

 https://photos.app.goo.gl/C6dHoPEoPCTyTetg8

**Comment by yakov116** [comment]
@ThinkDigitalRepair know issue will be fixed in the next release
