### ISSUE TITLE
[Feature Request] See GitHub Services Status

### ISSUE THREAD

**Issue by jjavierdguezas** [k0shk0sh/FastHub#2439]
Please add a view to see the status of GitHub services [https://www.githubstatus.com/](https://www.githubstatus.com/)

**Comment by k0shk0sh** [comment]
If there is something wrong, you'll see it when u open up FastHub or any screen.

**Comment by jjavierdguezas** [comment]
You mean that if GitHub has a problem with some of its services, FastHub will show it as it appears on githubstatus.com?  If that's what you mean, then sorry for open this issue (feature). Anyway I would like to see it whenever I wanted.

**Comment by k0shk0sh** [comment]
@jjavierdguezas all u got to do is open fasthub and it will tell u when there is something is down in GitHub, I don't see the need to display a full screen that only says (GOOD).

**Comment by yakov116** [comment]
@k0shk0sh I think the app changed for the app status and it is not showing now.

**Comment by k0shk0sh** [comment]
@yakov116 yep, they changed their API but I fixed earlier today and its already pushed but not gonna make a release for it specifically, maybe on the weekend I'll a new release
