### ISSUE TITLE
Feature: autocomplete of @mention  for others in the issue thread. 

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#244]

**Comment by k0shk0sh** [comment]
You could reply anyone who had commented, however mentioning someone would be pretty tedious considering the API limit in search api.

**Comment by eygraber** [comment]
@k0shk0sh you could do something like search the usernames that are already loaded for the issue, PR, etc...

**Comment by k0shk0sh** [comment]
@eygraber isn't the reply button in each comment is enough? Or you want something like multiple tags?

**Comment by eygraber** [comment]
@k0shk0sh multiple tags

**Comment by JediBurrell** [comment]
This issue has been appealed in 5fc4d63.

**Comment by k0shk0sh** [comment]
@JediBurrell great job 👏👏

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
