### ISSUE TITLE
tasto blocca/sblocca pvt

### ISSUE THREAD

**Issue by asteride** [k0shk0sh/FastHub#2446]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P10  
---

In seguito all'ultimo aggiornamento dell'app, il pulsante blocca/sblocca privati dal menu a tendina non risponde al comando. Il blocco privati deve pertanto essere inserito manualmente.

**Comment by yakov116** [comment]
English please
