### ISSUE TITLE
Support for Fully Gestural Navigation in Android Q

### ISSUE THREAD

**Issue by michaelgosling** [k0shk0sh/FastHub#2447]
**FastHub Version: 4.6.7**  
**Android Version: 10 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 3 XL  
---

 I understand Android Q is pre-release but better to deal with these issues now rather than later. Attempting to pull open the side drawer will trigger the back command with Android 10's Fully Gestural Navigation. I believe the latest sdk has the ability to override the back navigation option, might consider doing that for the left side to handle the drawer (as the right hand edge swipe also triggers the back command).

**Comment by k0shk0sh** [comment]
V5 has no issues with that as im also using pixel 3 xl and on beta3. Its a matter of me finding time.to finish it up :)

**Comment by michaelgosling** [comment]
Oh awesome. Slightly off topic, but will there be support for dark mode as well?

**Comment by k0shk0sh** [comment]
FastHub has few times and one is dark and one amold so I don't think so!. You either get the free dark theme or buy the amold theme oooor enforce all apps in ur phone to use the phone dark theme

**Comment by michaelgosling** [comment]
Ah. I like the dark themes, I paid for them, but I don't like going all the way into the apps individual settings to enable them. Would be nice if we could pick a theme that would be enabled when the system dark mode is enabled. Idea for a future feature, possibly.

**Comment by k0shk0sh** [comment]
Good idea, but it's just a one time thing so you enabled it once and you are good to go! 

Can't promise anything meantime as I want to focus on improving current features and have a better navigation & UI.

**Comment by michaelgosling** [comment]
@k0shk0sh yeah enabling it once is fine if you only use one theme, but I (and I think others) use the quicktoggle to go back and forth between light and dark mode depending on the situation.

But I understand. Navigation is definitely a priority. Thanks for hearing me out! :)
