### ISSUE TITLE
Notification Issues

### ISSUE THREAD

**Issue by heinrichreimer** [k0shk0sh/FastHub#245]
- **Android version:** 7.1.2
- **FastHub version:** 1.5.1

## Issues:
1. Notification has no icon. Maybe use [this icon](https://materialdesignicons.com/icon/github-circle).
2. Notifications don't group. See [the docs](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#bundle).

**Comment by heinrichreimer** [comment]
![screenshot_20170403-185550](https://cloud.githubusercontent.com/assets/5065698/24621028/4ce724a6-18a0-11e7-91dc-42686e8be27f.png)

**Comment by k0shk0sh** [comment]
Update to 1.6.0? Which has this fixed.
