### ISSUE TITLE
organization cannot found

### ISSUE THREAD

**Issue by LEODPEN** [k0shk0sh/FastHub#2452]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P10  
---

 it seems that if there's no repo in one organization, the organization then cannot be displayed.:broken_heart:

**Comment by yakov116** [comment]
@LEODPEN link?

**Comment by LEODPEN** [comment]
> @LEODPEN link?

here is the organization that cannot be seen:   https://github.com/imgrin.

**Comment by yakov116** [comment]
@LEODPEN is it private

**Comment by LEODPEN** [comment]
> @LEODPEN is it private

certainly not, but there's no repos in it.

**Comment by k0shk0sh** [comment]
Login with access token and then it will appear!
