### ISSUE TITLE
Add My repositories for logged user and size for each repository

### ISSUE THREAD

**Issue by md500** [k0shk0sh/FastHub#247]
Posibility to see own repositories without having to search itself and show size of each repository?

Ej:

 =Username= (swipe left to rigth) -> My repositories

 =Username= / =Repository=
X MB(TB,GB,KB,MB)

**Comment by k0shk0sh** [comment]
I couldn't get you, could you please elaborate more?

**Comment by md500** [comment]
Like this:

![](https://drive.google.com/file/d/0ByF29pyl-DHeQ3NxcjhWTlBkNTQ/view) <--- My repositories

[](https://drive.google.com/file/d/0ByF29pyl-DHeY0t6aXNJcGxfcXM/view) <--- Size of each repository

**Comment by k0shk0sh** [comment]
Your repos are located under your profile? If you like to have faster access to specific repo you could pin it and access it from pinned item in the menu drawer? 

does the size really matter?

**Comment by k0shk0sh** [comment]
Now you can see the repo size,  but having My Repos in the drawer is redundant currently with the current design. 
you could always use Pin button to pin the repos that matter the most to you.
Thanks for understanding.
