### ISSUE TITLE
Password change 

### ISSUE THREAD

**Issue by cruegether** [k0shk0sh/FastHub#2472]
**FastHub Version: 4.6.7**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy J5  
---

 Hello , I want to change my github password but I can't see any option . So please help

**Comment by yakov116** [comment]
@cruegether login online and change the password. There is no such option in the app.

**Comment by yakov116** [comment]
@cruegether login online and change the password. There is no such option in the app.

**Comment by yakov116** [comment]
@cruegether login online and change the password. There is no such option in the app.
