### ISSUE TITLE
Weird UI issue

### ISSUE THREAD

**Issue by MarioMarietto** [k0shk0sh/FastHub#2474]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** SM-A505FN  
---

 Hey there,
I found an issue with the UI. When using the dark theme (the second one in the list), a weird UI bug happens.
Steps to reproduce:

Select a repository
Select a Commit
Click on the "i" button
Weird bug

**Comment by beastdestroyer** [comment]
Yup can confirm this happening; UI popup just buzzes in and out very rapidly


Probably will be fixed for the upcoming v5 :)

**Comment by alexa-v2** [comment]
"upcoming"?

**Comment by k0shk0sh** [comment]
Aware of that bug and fixed in v5 

Soon I'll be releasing as beta version. Stay tuned
