### ISSUE TITLE
Add proper markdown rendering in project tasks

### ISSUE THREAD

**Issue by caffeinatedMike** [k0shk0sh/FastHub#2479]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** Verizon  
- **Model:** Galaxy S7 Edge  
---

This is a feature request, but I'm not sure if it's possible. I'd like to see project tasks properly render markdown, especially checkboxes. Seeing how issues properly render markdown I'm hoping this could  be possible. Thanks for hearing me out! 😊

**Comment by yakov116** [comment]
@caffeinatedMike 	lets wait for V5

**Comment by caffeinatedMike** [comment]
@yakov116 Any idea of a timeframe? I see that the V5 project was created in February, but since it doesn't include tasks I can't tell how far along it is.
