### ISSUE TITLE
Issues and PRs Are Mixed Up

### ISSUE THREAD

**Issue by coderfox** [k0shk0sh/FastHub#248]
In the latest version, PRs are shown in the "Issues" section, while they cannot be opened, which caused great confusion.

I think PRs should not show up in "Issues" section.

**Comment by k0shk0sh** [comment]
I couldn't get you, any steps to produce this?

**Comment by coderfox** [comment]
Open <https://github.com/orvice/ss-panel> and go to issues.

There is #690 shown in "Issue" tab which actually is a PR.

In fact, all PRs are shown in "Issue" tab and mixed up with issues.

**Comment by k0shk0sh** [comment]
Owh yes!. I literally forgot about that, this issue I guess it exists when I added the count. 
it'll be fixed in today's release.
