### ISSUE TITLE
FastHub Restarts Upon Editing Issue

### ISSUE THREAD

**Issue by MrTeeXD** [k0shk0sh/FastHub#2481]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** HUAWEI P smart  
---

 There is  problem where if you try to edit an issue within FastHub, the app will unexpectedly restart without input from the user. This only happens when you try to edit the title.

**Comment by narongrit01** [comment]
get clone

**Comment by k0shk0sh** [comment]
the problem is with your device ** HUAWEI** I see the crashes coming from all the `HUAWEI` devices which they are impossible to fix due to them altering the framework components. sorry, but i honestly can't help with this.
