### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by dban520** [k0shk0sh/FastHub#2484]
**FastHub Version: 4.6.7**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** RCA  
- **Brand:** RCA  
- **Model:** RCA_Q1  
---

 My account will not let me verify my additional email acct

_Sent from my RCA_Q1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@dban520 	what?

**Comment by dedepete** [comment]
You can't verify your account via the app, but it's possibly to do via a website.  
Feel free to reopen the issue, if I misunderstood you.
