### ISSUE TITLE
Approving PRs

### ISSUE THREAD

**Issue by kjenney** [k0shk0sh/FastHub#2485]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** SM-G973U  
---

 I can view a PR and comment on changes but I don't see any option to approve it.

**Comment by dedepete** [comment]
Are you submitting your PR into a private repository? Is it an organisation's one?

**Comment by kjenney** [comment]
It's a private repo in an organization.
