### ISSUE TITLE
FastHub does not provide Android notifications for GitHub

### ISSUE THREAD

**Issue by takealook-global** [k0shk0sh/FastHub#2486]
I have the FastHub Pro and i do not receive any notifications about Pull Requests, Commits.....
I made a login with access token, i have a organization with private respositories, 
but also public outside the organization did not come.

**Comment by yakov116** [comment]
@takealook-global 	did you read the FAQ?

**Comment by takealook-global** [comment]
Where is the faq? and what the problem with my issue, if it is an issue? could you awnser the question, or put the faq link before close my question, I paid, i'm not using free version, i paid today, i will ask my money back and open a claim on open store, Did you treat all costumer like that?

I paid because said something, and dont do it, so you just could put the awnser a copy and paste here.

**Comment by yakov116** [comment]
@takealook-global 	Do you have web notifications on?

In the FAQ (In The app) we go through all there questions that we get daily. 
You could have just gave a quick search before opening the issue. That is why i closed it

**Comment by yakov116** [comment]
https://github.com/k0shk0sh/FastHub/issues?q=is%3Aissue+sort%3Aupdated-desc+notification+is%3Aclosed

**Comment by takealook-global** [comment]
I did a quick search i already read now the faq here on github, and still no awnser why someone make a pull request and i dont get my notification.

But you instead of help me, treat me like a dummy, this because i paid imagine if was the free version!

**Comment by yakov116** [comment]
@takealook-global 	Lets take this slow.

Do you have your github email notifications on?

**Comment by takealook-global** [comment]
Yes i have notifications on, but ok man, you have persuade me i get my money back.

I cant understand why someone do a software(i do the same it's my job, i'm not a dummy), sell it and treat the customer, like CLOSED.

I was slow, you think the problem was me or your way of treat customer.

**Comment by takealook-global** [comment]
even the notification from this chat, i don't receive. lol

**Comment by yakov116** [comment]
Do you have your github **email** notifications on?
What interval is your notifications set on?

**Comment by takealook-global** [comment]
Ok yakov let's start over, so please be a little patience, i have worked all day, and all night, you now what is to be a developer.

Yes i have e-mail notification ON
Is configured like this.
http://pt-br.tinypic.com/r/2v7t2sp/9

The e-mail of notification is not the same as Play store.

**Comment by takealook-global** [comment]
Whats the best way to do a login, Basic, Token ? 
Token From here https://github.com/settings/tokens or on App browser ?

**Comment by takealook-global** [comment]
I did use token

**Comment by yakov116** [comment]
@takealook-global 	 All the same.

What is you interval for notifications set in the app?

**Comment by takealook-global** [comment]
for now 1 minute.

**Comment by takealook-global** [comment]
The e-mail notification is setup right :?

**Comment by yakov116** [comment]
@takealook-global yes

**Comment by yakov116** [comment]
When you click the bell do you see any notification?

**Comment by takealook-global** [comment]
No notification on b the bell, but the feed is ok, the bell on the 3 sections are empty, with a reload button

**Comment by takealook-global** [comment]
Shoud i see something on Repositories? In organization, repositories section i can see. they are all private and inside an organization.
Another question is, i should receive notifications about our chat here? if yes i'm not gettin

**Comment by yakov116** [comment]
@takealook-global you should be.
Are you opening  the emails? That would mark it read

**Comment by takealook-global** [comment]
no, notification on mail are unread.

The app has a play store e-mail that is not the same of notifications, 
example: play store email: email@email.com, fasthub(organization,login) email email2@email.com

I did login using access token, made here https://github.com/settings/tokens
I did check all options

I also do not have that(e-mail receiving notifications) e-mail on my phone.

The repositories are inside a private organiztion.

Before I get in on organization,  Feed Works, Issues are empty, Pull Requests and Bell also
Once i choose organizations -> the organization, Feed, Repositories, Overview, People, Teams works

I shoud do some configuration for the organization ? should i configure the e-mail of notifications in google account on the cell phone ?

Thanks

**Comment by k0shk0sh** [comment]
That doesn't matter, the notifications are tied to ur login via the app to GitHub. 


You need to grant fasthub permission to ur org, or better login via access token and grant all orgs permissions.

**Comment by takealook-global** [comment]
I did use the acess token, and grant all permissions,

**Comment by takealook-global** [comment]
i made the token here, and checked all options
https://github.com/settings/tokens

**Comment by k0shk0sh** [comment]
You can see ur orgs within the app right? If so, do u get any emails from GitHub about notifications from ur repos? If not, please enable email notification from GitHub profile settings and also one last thing, did u set an interval for fasthub in app/settings/notifications? Its important that you do that!

**Comment by takealook-global** [comment]
YEs i see the organizations, i can get in, edit file, merge pull request do all, 
Email are enable notification http://pt-br.tinypic.com/r/2v7t2sp/9
The interval for now is 1 minute

**Comment by k0shk0sh** [comment]
Hmmm, went through the discussion here you seem to have enabled things up, that's weird. 

Just to confirm is ur org listed in fasthub? 

If that's the case, could you tell me what device do you have?

**Comment by takealook-global** [comment]
Yes is listed and working fine all functions, 
Samsung Galaxy S9+
https://github.com/settings/tokens

I created the token on this link, should I made one inside organization? has this possibility ?

**Comment by takealook-global** [comment]
In this link 
https://github.com/organizations/platypusbrasil/settings/apps

**Comment by takealook-global** [comment]
I did check the e-mail, all notification are there unread, this chat also is there.
Have some configuration more to apply on github ?

**Comment by takealook-global** [comment]
Should i have an option to create an access token to the organization? or are all the same?

**Comment by takealook-global** [comment]
http://pt-br.tinypic.com/r/r7lp5e/9
http://pt-br.tinypic.com/r/126elj9/9

Fasthub permissions on github

**Comment by k0shk0sh** [comment]
And nothing has worked?? 😭😭. 

Can u check on battery optimization on ur phone and make sure fasthub is not checked, it might be that ur phone restricting fasthub

**Comment by takealook-global** [comment]
Yes i did check battery, and notifications are all enabled, with permissions.

I did login with user+access token, Android 9, Versão One Ui 1.0, Security path 1/05/2019, Kernel 4.9.112-15678484
Phone Model Sm-G9650 Galaxy S9+
Fast Hub notification enabled on phone, fasthub battery allowed email notification enabled on github, fasthub sync time 1m

Organizations: Ok
Edit FIle : Ok
Feed: Ok
Pull Request: ok
Repositories in Organization OK.

Notification from Organization: Not working.
Notification from normal account ( like this chat, and other ) : Not working.
Notification on e-mail: On, Automatic Mark as Read : False
Email : On Inbox, not going to spam, or trash.
Login Type: UserName +  Access token Created here https://github.com/settings/tokens
Permissions Checked : http://pt-br.tinypic.com/r/r7lp5e/9   http://pt-br.tinypic.com/r/126elj9/9

**Comment by takealook-global** [comment]
The issue for example show on the FastHub app, but when you send me a message, or change status like closed, open, reopened, no notification, but 16 email notifiyng about it on inbox.

Gthub login email and play store are not the same, just to be clear, and the e-mail is not a google account on my phone.

**Comment by yakov116** [comment]
>Gthub login email and play store are not the same, just to be clear, and the e-mail is not a google account on my phone.

They have no connection.

Weird @k0shk0sh 	any other idea?

**Comment by k0shk0sh** [comment]
Nothing I could think of tbh, 

Could you try and login via login via browser option and tell us if you see ur orgs? Cuz you granted fh access so it should behave fine and in that case, double check if u get notifications again, by making sure to set interval in notification.

**Comment by yakov116** [comment]
@takealook-global 	Can you change it to 5 min and then change it back?

**Comment by takealook-global** [comment]
Ok i can do, so for be sure,
Logout, and log in again throught the option Oauth(Browser) 

And yues @yakov116 i can change to 5 min

**Comment by takealook-global** [comment]
I should clean the tokens on github, remove app, and connect again throught the option Oauth Browser on fasthub app?:

**Comment by yakov116** [comment]
@takealook-global 	No need

**Comment by k0shk0sh** [comment]
Do all of that and if u need to delete the token, delete it :)

**Comment by takealook-global** [comment]
Ok we got an evolution, now bell on the app show notification, but the push on phone still not working.

**Comment by takealook-global** [comment]
> Do all of that and if u need to delete the token, delete it :)

Yes I removed token, app, clear the phone cache.

**Comment by takealook-global** [comment]
I have mentioned my username on a issue comment i received 1 notification, 
Tried again more 6 times, comment on pull request and issues, but no more notification.

**Comment by yakov116** [comment]
@takealook-global 	did this work?

**Comment by takealook-global** [comment]
So the bell (notification section on fast hub ) is filled, notification i received 2 for now on Issue comment, but seens random, and only for Issue, if i receive a pull request or comment on pull request do not work.
but if i get on fast hub and use the bell all are there now.

But i wish to receive notifiations about new pull request, commits....
And even for issue of 11 tries only 2 I got

**Comment by yakov116** [comment]
@takealook-global 	you will not get a notification from your own comments

**Comment by takealook-global** [comment]
Ok, not a problem, but i get if someone has mentioned me, works 2 times of 13 now.
Pull request, commit, merge, ....still not get notification, but now is on the bell inside the fasthub app ( before was not displaying)

**Comment by yakov116** [comment]
@takealook-global 	Explain again

**Comment by takealook-global** [comment]
I'm doing a few tests, wait a little please. but i think now all works.

**Comment by k0shk0sh** [comment]
🍾🍾🍾🍾🍾🍾🥳🥳🥳

**Comment by takealook-global** [comment]
Ok now works.
If someone has the same problem.
What i did:
Uninstall The app FastHub
Clear OS Cache
Remove Token, App, Oauth from github referer to fasthub app.
Install the app
login with oauth with browser
And test, if Notification section now has notifications but phone don't push, create a issue, and make comments from another account and mention with your username, after some comments, and some notifications, all notifications about, pull requests, issues..... start comming.

Solved!

**Comment by takealook-global** [comment]
@k0shk0sh @yakov116 today stopped work again =/

**Comment by yakov116** [comment]
@takealook-global 	something is wrong with your phone

**Comment by takealook-global** [comment]
I don't think so, i got all notifications both on phone and gear watch.
Only fasthub doenst work, or 1 time each 3 days come some.
but ok. i will accept that my brand new s9+ that receives all apps notifications, Whatsapp,facebook,instagram, bank,gmail....... is broken cuz fasthub does not work.

**Comment by yakov116** [comment]
@takealook-global 	the only thing is that why are you getting messages sometimes?

**Comment by takealook-global** [comment]
normally when i get on fast hub and exit, the notifications come, some of them.
if i do not open the app I will never get one notification.
But even when i open app and exit (not close from memory ), i don't get all.

**Comment by takealook-global** [comment]
Looks like it only works and it's running on brackground.
Already checked battery configuration and notification. all are the same as other apps.

**Comment by takealook-global** [comment]
No answer thanks

**Comment by takealook-global** [comment]
@yakov116 i just have change my phone Galaxy  S9+ for Galaxy S10+ i still get the same problem with organizations notifications.
