### ISSUE TITLE
Paid organizations not listed in new orgs menu

### ISSUE THREAD

**Issue by seaneking** [k0shk0sh/FastHub#249]
Awesome to see organization support! Now just need searching in issues and this is a total GitHub replacement on mobile :-)

One issue I'm seeing with orgs is that paid orgs (ie: with private repos) aren't showing up in the list.

**Comment by k0shk0sh** [comment]
I guess I know why, do expect another release very soon with more awesome stuff :p 

Now you could see Organization feeds as well like the Feeds event in FastHub but specified for the Org you are member of.

**Comment by k0shk0sh** [comment]
You should be receiving 1.7.0 very soon, please check and let me know if everything works :)

**Comment by seaneking** [comment]
Still not seeing private orgs listed in 1.7

**Comment by k0shk0sh** [comment]
https://developer.github.com/v3/orgs/#list-your-organizations

Your private repos has to allow FastHub to access them, you could go settings and select FastHub after that you should see a button that request your organization to grant access to FastHub to see them.

**Comment by seaneking** [comment]
Ah gotcha - FastHub should request this during initial setup/auth no? Or if that's not trivial with current auth setup, at least have a link in FastHub settings to authenticate private orgs

**Comment by k0shk0sh** [comment]
@seaneking tbh I'm not sure how this works, as most of the time I'll login using my username and password (basic auth) however I'm not so sure, if you try and login from (browser) that will make any difference. There are scopes to grant listing orgs, however orgs have to grant that access. I'm not so sure about this steps because I can't debug on it nor find useful info in GitHub API about it.

**Comment by seaneking** [comment]
Okay I'm pretty confused - can't see FastHub in my personal authorized apps settings or anywhere in org settings to manually ad a new authorized app.

Can I get FastHub to reauthenticate with GitHub somehow?

**Comment by k0shk0sh** [comment]
Hah? that strange? I could see mine & other dummy account I have both are listed.  I've even revoked access to it & login again using basic Auth (login screen) and it was listed back in my Authorized Applications. 

There are paginations over there, maybe you missed that out? if not then really dafuug

**Comment by k0shk0sh** [comment]
@seaneking have a look at this https://help.github.com/articles/about-third-party-application-restrictions/

**Comment by seaneking** [comment]
Sorted! Think it was GH's fault - fasthub was in my authed apps list on desktop but not mobile ¯\_(ツ)_/¯
