### ISSUE TITLE
Image Attachments

### ISSUE THREAD

**Issue by MrTeeXD** [k0shk0sh/FastHub#2490]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** HUAWEI P smart  
---

 The app should allow for Attaching Images

**Comment by yakov116** [comment]
@MrTeeXD it does.

**Comment by MrTeeXD** [comment]
Oh oops, did not notice this
