### ISSUE TITLE
Missing Milestones

### ISSUE THREAD

**Issue by MrTeeXD** [k0shk0sh/FastHub#2492]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** HUAWEI P smart  
---
It seems as if the app is missing milestones which prevents me from looking at a Project Version Progress

**Comment by yakov116** [comment]
@MrTeeXD link please?

**Comment by MrTeeXD** [comment]
Hello there, sorry for the long wait. Here is an Example of Milestones not showing in FastHub.
https://github.com/k0shk0sh/FastHub/milestones

**Comment by k0shk0sh** [comment]
They show up really fine for me when I click on the link.
