### ISSUE TITLE
Issue comment reaction problem

### ISSUE THREAD

**Issue by persello** [k0shk0sh/FastHub#2495]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

 If you tap more than once on the like button on a comment inside an issue view, it gets increased first and then it goes down by one with each tap. When it reaches zero the icon disappears.

_Sent from my Galaxy S8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
Known issue
Will be fixed in the next version

**Comment by yakov116** [comment]
@persello this has been fixed in the latest version
