### ISSUE TITLE
Profile picture doesn't update even after logging out and back in

### ISSUE THREAD

**Issue by persello** [k0shk0sh/FastHub#2496]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

 I have recently added a profile picture to GitHub but I can't see it in the side menu or in the profile information, but if I click on the placeholder in my profile information I get redirected to a browser which shows the new picture.

_Sent from my Galaxy S8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@persello 	in the settings there is an option to clear the picture cashe
