### ISSUE TITLE
Committing a Markdown file while in preview mode commits the preview text instead of the raw Markdown

### ISSUE THREAD

**Issue by swordglowsblue** [k0shk0sh/FastHub#2498]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

When editing a Markdown file from the app, clicking the eye icon to switch to preview mode and then committing the file will commit the text of the preview rather than the source Markdown. This leads to total loss of formatting, including headers, inline formatting, and the conversion of list bullets to Unicode bullets.

**Comment by kgscialdone** [comment]
Closing this due to no response. Mostly to get it out of my lists.
