### ISSUE TITLE
No trending tab

### ISSUE THREAD

**Issue by Oredna** [k0shk0sh/FastHub#2508]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** SM-G975F  
---

 I have problem in the past 3 days to see that trending tab

**Comment by k0shk0sh** [comment]
GitHub changed their HTML tags and my client scrapping stopped

**Comment by flamendless** [comment]
Can confirm this

**Comment by twsI** [comment]
Same

**Comment by zeromake** [comment]
@k0shk0sh 
I launched a pr to fix the problem, but ci run is error
#2519

**Comment by wuchenchen** [comment]
"No trending"

**Comment by MInner** [comment]
I confirm that I am also experiencing this problem.

**Comment by mafeifan** [comment]
yes.  no trending  is there something wrong ?
