### ISSUE TITLE
Trending repos Not working

### ISSUE THREAD

**Issue by ygunduz** [k0shk0sh/FastHub#2510]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 5  
---

 There is an error while fetching trending repositories.  It says 'No Trending'

**Comment by yakov116** [comment]
@ygunduz 	
Duplicate of #2508

**Comment by flamendless** [comment]
Can confirm this

**Comment by circa10a** [comment]
Having same isshe

**Comment by eaglexiang** [comment]
the same issue

**Comment by qingspring** [comment]
have the same issue

**Comment by mafeifan** [comment]
same issue, i am premium user.  plz fix asap.  thx

**Comment by mafeifan** [comment]
seems the structure  of github trending page changed, so fasthub parse html failed.. i think it's not hard to fix.

**Comment by muellercornelius** [comment]
Same problem here ;(

**Comment by BaldEagleX02** [comment]
Same issue here

**Comment by k0shk0sh** [comment]
It isn't hard to fix, its fixed in v5 but its not possible anymore in old FastHub 🤷‍♂️

**Comment by eaglexiang** [comment]
@k0shk0sh Could you push the update to google play store?

**Comment by k0shk0sh** [comment]
V5 isn't ready for prod yet but im working on that! Please be patient :)

**Comment by glebcha** [comment]
@k0shk0sh when it will be finished?

**Comment by k0shk0sh** [comment]
No exact timeline, end of October max!

**Comment by ilazaroy** [comment]
@k0shk0sh thanks for the help.

**Comment by zeromake** [comment]
You can use [my-fix](https://github.com/zeromake/FastHub/releases/tag/4.6.7-debug)

**Comment by ilazaroy** [comment]
Yep, did the trick.
Thanks man and thank you for the great app! Super easy to explore trending
repos this way.

**Comment by glebcha** [comment]
When it'll be fixed? Just write damn date.

**Comment by yakov116** [comment]
>Just write damn date.
date 😄

**Comment by glebcha** [comment]
@yakov116 whatever, think about "date" in context of time
