### ISSUE TITLE
Issue with rating a post

### ISSUE THREAD

**Issue by Jabster28** [k0shk0sh/FastHub#2518]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy A6  
---

 You can mark (upvote) a post on an issue multiple times, and the number just keeps increasing

**Comment by yakov116** [comment]
@Jabster28 	its a known issue. It will be fixed in the next relese
