### ISSUE TITLE
Avatars Not Rounded

### ISSUE THREAD

**Issue by HarshKhandeparkar** [k0shk0sh/FastHub#2522]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus3  
---

 After updating to Android 9 recently, the rounded avatars suddenly changed to squares. Below is a screenshot to demonstrate the same. The squarish avatars option is also off.

![Pic](https://i.imgur.com/fPyUJXj.jpg)

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AndreaCioccarelli** [comment]
Same for me, OP5

**Comment by yakov116** [comment]
@HarshKhandeparkar should be fixed
