### ISSUE TITLE
Trending section not working

### ISSUE THREAD

**Issue by paperbenni** [k0shk0sh/FastHub#2532]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4)  
---

 Title says it all. The trending section is not working anymore. "No trending, reload"  I'd guess it's a server side change, it's been reliably not working for a while.

**Comment by rancidfrog** [comment]
@k0shk0sh
trending please.
Some users are idiots and do not check issues to see if there are 10 already created exactly the same. So please fix trending...
trending

**Comment by paperbenni** [comment]
@rancidfrog sorry, I just used the in-app report feature. Should've looked at the issues.

**Comment by rancidfrog** [comment]
It is just that there are 20 or more issues with trending as subjects
