### ISSUE TITLE
Disable send feedback button

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#2533]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

 Please disable Send feedback:
![](https://i.imgur.com/5hu79PK.png)
As users are using it to spam issues list with issues before checking if issue already exists and also just to spam issues

You might want to disable issues until new version, too.
Since no changes to older version so issues are useless at the moment

**Comment by rancidfrog** [comment]
Examples, Trending: #2526 #2527 #2530 #2531

**Comment by eigan** [comment]
To be fair, I didnt even know it created an issue here _(well, I might if I wasnt in a rush and just submitted the form..)._ 

This could also be solved by showing "related issues" like how Github does when typing the title.

**Comment by k0shk0sh** [comment]
Once you open send feedback a toast will be showing to tell that it will be submitted to FastHub, the title of the feedback is the repo name 🤷‍♂️ . 

But yeah, maybe I'll work on this in v5
