### ISSUE TITLE
Can't load trendings anymore

### ISSUE THREAD

**Issue by Diliz** [k0shk0sh/FastHub#2534]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6T  
---

 Hello there,

I'm not the only one experiencing this issue, since 1/2 weeks, I can't load any trending from the app, maybe there's a problem with my github account strings or else.

If you know a way to fix it, i'll be really happy with my trendings working again :)

Thanks for reading.

**Comment by rancidfrog** [comment]
You need uninstall fasthub

**Comment by rancidfrog** [comment]
Use forkhub, pockethub, tutuHub, kakahub instead

**Comment by k0shk0sh** [comment]
@rancidfrog could you please stop trolling people on fasthub behalf? You giving them a bad experience.

**Comment by rancidfrog** [comment]
Bad experience is users opening 100s of trending issues because of ease of Send feedback button, the click on button and open issue without checking if it already exists.
there are still 2/4 open trending issues

Also, maybe just push the fix if it works to stop these spammers: #2519

**Comment by k0shk0sh** [comment]
They aren't spamming they are helping by sending their feedback, yeah, they should search before posting an issue but that's not an excuse to get on everyone nerf. 

Thanks tho for keeping an eye, but I had prefer if you take it easy

**Comment by rancidfrog** [comment]
If you say so:
![](https://i.imgur.com/6z76AbH.png)

**Comment by dedepete** [comment]
And still this is not an excuse for being toxic.
