### ISSUE TITLE
Contribution section fails to load if activity overview is turned on

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [k0shk0sh/FastHub#2535]
**Android Version: 9**  
**Device Information: OnePlus 5T**  
**FastHub Version: 4.6.7**
---

Contributions section fails to load if activity overview is turned on.

### On the website

![image](https://user-images.githubusercontent.com/30529572/59872155-c7631080-93b6-11e9-9905-346d470393a2.png)

<br/>

### On the app

<img src="https://user-images.githubusercontent.com/30529572/59872272-08f3bb80-93b7-11e9-8fc4-3f84b50b1911.jpg" height=500px>

**Comment by yakov116** [comment]
Github changed the HTML

Were not planning on adding it back


Thanks for your feedback
