### ISSUE TITLE
Profile picture fails to change when changed from the website

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [k0shk0sh/FastHub#2536]
**Android Version: 9**  
**Device Information: OnePlus 5T**  
**FastHub Version: 4.6.7**
---

#### What I did
Changed github profile picture from the website

#### What was expected to happen
The profile picture should have changed in the app

#### What actually happened
Even after `a month` of having changed the picture, it didn't reflect in the app

**Comment by yakov116** [comment]
Clear the picture cashe from the settings

@L04DB4L4NC3R 	Please search the issues 
![image](https://user-images.githubusercontent.com/16872793/59873874-f0f64a80-936a-11e9-97b6-b16bc793f3b7.png)
