### ISSUE TITLE
Collapse empty directories

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#254]
If there are a bunch of nested empty directories (e.g. Java packages) can they be displayed as `directory1/directory2/directory3` instead of having to click through each one?

**Comment by k0shk0sh** [comment]
Currently no way, unless if we use different API which then, we will need to redo the repo files from zero :D

**Comment by eygraber** [comment]
@k0shk0sh what about using the current API, but do a "lookahead" request to the current directories children, and keep doing that until there's a child that's not empty. Should never be more than a few levels deep.

**Comment by kutsan** [comment]
@eygraber I don't think extra a few request for each directory is good solution

@k0shk0sh But maybe this can be parsed 
https://api.github.com/repos/k0shk0sh/FastHub/git/trees/master?recursive=1
