### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gianiaco** [k0shk0sh/FastHub#2544]
Hello all,
when i clone the project in Android Studio, it immediately give me this warning:

> The project is using an incompatible version of the Android Gradle plugin.  To continue opening the project, the IDE will update the plugin to version 3.4.1.  You can learn more about this version of the plugin from the release notes.

I have to agree and proceed with update.
After that, the first error is:

> No such property: dir for class: org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection

Searching in the internet i solved substituting in build.gradle the jacopo-android plugin to version 0.1.4

` classpath 'com.dicedmelon.gradle:jacoco-android:0.1.4'`

But then other two errors... 

> ERROR: The Android Gradle plugin supports only Crashlytics Gradle plugin version 1.25.4 and higher.
> The following dependencies do not satisfy the required version:
> root project 'FastHub' -> io.fabric.tools:gradle:1.24.1
> Affected Modules: app
> 
> 
> ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
> The following dependencies do not satisfy the required version:
> root project 'FastHub' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.10
> Affected Modules: app

If i try to fix it others errors appears and so on.

Here are more info of the enviroment:
Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 1, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Thanks

**Comment by mateodevia** [comment]
HI, did you find any solutions, I am having the same problem

**Comment by k0shk0sh** [comment]
Please use development branch and not master.
