### ISSUE TITLE
SVGs don't load

### ISSUE THREAD

**Issue by isaac2004** [k0shk0sh/FastHub#2547]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8+  
---

 I would expect SVGs to load in the app 

Example

https://github.com/dotnet/swag/blob/master/dotnet-bot-summer/dotnet-bot-summer.svg

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/UH7MxoO.jpg)
