### ISSUE TITLE
Organization private repos

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#255]
In the organization view, the repo tab only shows public repos. I gave FastHub access to my organization repos, so I can see the organization private repos throughout the test of the app. Just not in the organization view.

**Comment by k0shk0sh** [comment]
If you haven't update to 1.7.0 please do so, because I have added this earlier today.  Close this issue if it actually fixed :) otherwise let me know.

**Comment by eygraber** [comment]
@k0shk0sh 1.7.0 fixed it, but there was another issue. I'll make a separate issue for it.
