### ISSUE TITLE
Can't star project

### ISSUE THREAD

**Issue by AtHeartEngineer** [k0shk0sh/FastHub#2551]
**FastHub Version: 4.6.7**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 I tried to star a project and it popped up with a toast message saying it failed and to check the logs, I don't see anywhere on the app to check the logs though.

**Comment by yakov116** [comment]
Link?
