### ISSUE TITLE
why not fix trending bug?

### ISSUE THREAD

**Issue by aiyolo** [k0shk0sh/FastHub#2553]
**FastHub-Libre Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI 8  
---
this bug has been appearing for several days, still no solution yet?

_Sent from my MI 8 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by dedepete** [comment]
PRs are welcome.

**Comment by dedepete** [comment]
Nvm, I don't think it will be merged.
