### ISSUE TITLE
Trending broken

### ISSUE THREAD

**Issue by ShayBox** [k0shk0sh/FastHub#2557]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Amazon  
- **Brand:** Amazon  
- **Model:** KFKAWI  
---

 Has been broken for months

**Comment by yakov116** [comment]
@ShayBox 	Months Wow. Just About A week

However were have to wait for a new release

**Comment by ShayBox** [comment]
Maybe have the report bug button search existing issues so you don't get so many duplicates, or just show the issues page instead of directly creating an issue
