### ISSUE TITLE
Closed issue is in open issues

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#256]
If I open a list of issues, then open an open issue, then close it and press back, the issue is still in the open list until I refresh. If I go to the closed issues list, it isn't there until I refresh.

**Comment by k0shk0sh** [comment]
I'm aware of that but I guess I've forgotten about it because it wasn't reported or tracked somewhere. It I'll be in 1.7.1.

**Comment by FallenKN** [comment]
@k0shk0sh
Also Pull Requests are viewable in Issues Tab but the click is without an function

**Comment by k0shk0sh** [comment]
@FallenKN 1.7.0 :D please.

**Comment by k0shk0sh** [comment]
this commit 7e0a407  actually fixed this.
