### ISSUE TITLE
Reactions do not function correctly in archived repos

### ISSUE THREAD

**Issue by sonjoonho** [k0shk0sh/FastHub#2564]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6  
---

When attempting to add a reaction to an issue in an archived repository, an unbounded number of reactions are able to be added.

Example issue:

https://github.com/npm/npm/issues/19883

Screen capture:

![19-06-28-15-44-53](https://user-images.githubusercontent.com/20669173/60351273-54acf300-99bd-11e9-99d2-52ddecb1ab36.gif)

**Comment by yakov116** [comment]
Its all repo's will be fied in the next version
