### ISSUE TITLE
Write this for the reason that you had repeated me under Openhub

### ISSUE THREAD

**Issue by CenJIl** [k0shk0sh/FastHub#2576]
your appliction has the same empty trending repos.
last commit  time is 2018 but last issues repeat just a few days ago.
it seems that you have many time to quarrel with code thief but have not time to make your application better.
openhub has such many star not only because of your great work, it  has something new in it.It collect all the popular project,it's useful.
another reason is that  not  entire earth use google's market.
You could  recognize another popular market coolapk

**Comment by dedepete** [comment]
So you came here just to write this? Waste of time.  
Firstly, @k0shk0sh is working on `fasthub/fasthub-v5`, and that's the reason why there's no updates on `master` and `development`.  
Secondly, it was described in details why it's not possible to follow FOSS lines. If you don't use GP, feel free to compile the app yourself without Google Services or use any of available FOSS forks.
