### ISSUE TITLE
Subscriptions ~~and Watching~~

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#259]
It would be cool to be able to subscribe or unsubscribe to issues or PRs.

~~Also setting whether a repo is watched or not.~~ I see this is already there 😁

**Comment by k0shk0sh** [comment]
for repo, you could unwatch & watch it, however unsubscribing to issues isn't there yet.

**Comment by AlexWayfer** [comment]
I don't see any "Subscribe" button for issue 😓

![](http://i.imgur.com/IF8B3ez.png)


_Sent from my Sony E5823 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@AlexWayfer please read my comment above!

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AlexWayfer** [comment]
@k0shk0sh I don't see comment about API, or `want-fix` label, but I see `completed` label and closing commit :) But OK.

**Comment by k0shk0sh** [comment]
@AlexWayfer completed was for seeing either u watching repo or not, however the subscription isn't possible but could be done though notifications screen or unsubscribe. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jhass** [comment]
It seems to me that you can enable a subscription with https://developer.github.com/v3/activity/notifications/#set-a-thread-subscription but I found no way to obtain the thread id for any given issue :(

The GraphQL API seems to fix that gap: https://developer.github.com/v4/object/issue/ -> https://developer.github.com/v4/interface/subscribable/ and there update the `viewerSubscription`.

**Comment by yakov116** [comment]
@jhass now it does not. It only helps for Unsubscribe (and even that I'm not sure)

**Comment by jhass** [comment]
Are you referring to the first or second part of my comment?

**Comment by jhass** [comment]
Okay, in theory https://developer.github.com/v4/explorer/?variables={%0A%20%20%22id%22:%20%22MDU6SXNzdWUyMTk0NzQyOTY%22%0A}%0A&query=query%20findIssueId%20%7B%0A%20%20repository(owner:%20%22k0shk0sh%22,%20name:%20%22FastHub%22)%20%7B%0A%20%20%20%20issue(number:%20259)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Amutation%20updateStatus($id:%20ID!)%20%7B%0A%20%20updateSubscription(input:%20%7BsubscribableId:%20$id,%20state:%20SUBSCRIBED%7D)%20%7B%0A%20%20%20%20subscribable%20%7B%0A%20%20%20%20%20%20viewerSubscription%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A should work, but it fails with an internal server error :/

**Comment by yakov116** [comment]
@jhass yup...
