### ISSUE TITLE
prioritize just the main action 

### ISSUE THREAD

**Issue by ZakTaccardi** [k0shk0sh/FastHub#26]
https://material.io/guidelines/growth-communications/onboarding.html#onboarding-quickstart

too many material onboarding bubbles. could definitely drop the one for dates

**Comment by k0shk0sh** [comment]
I totally understand that and just did for dates because #19 . it make sense tho to explain what they are and your request is valid. so I'm stuck in between and can't really satisfy everyone. it would be cool if you could suggest how to handle that

**Comment by k0shk0sh** [comment]
@ZakTaccardi  any feedback on this?

**Comment by ZakTaccardi** [comment]
I thought it was fairly obvious what the dates were for.

Instead of the bubble, a long press that pops up a toast explanation (like
menu icons in a toolbar) would be the best route for icons.

**Comment by k0shk0sh** [comment]
@ZakTaccardi Well that's a good suggestion. I'll be implementing this in next release. thanks
