### ISSUE TITLE
Trending

### ISSUE THREAD

**Issue by ShayBox** [k0shk0sh/FastHub#2600]
You would think having 77 issues because of trending not working, at this point you would either release an update for the latest build so it works, or remove the tab entirely. Seems a bit annoying to constantly get issues on this doesn't it.

**Comment by k0shk0sh** [comment]
If it was possible to release, I had released but my old branch doesn't build anymore :)

**Comment by ShayBox** [comment]
You should spend some time getting the old branch to build then, when you refractor you have to keep the old version working to fix issues, especially when the project is actually popular

**Comment by k0shk0sh** [comment]
This require to remove lombok from the project which mean refactoring tons of files and I had rather spend that time on the new branch, please be patient and instead of stressing me stay positive and keep me positive 🙏
Thanks
