### ISSUE TITLE
(feature request) more infos contributions graph

### ISSUE THREAD

**Issue by Androz2091** [k0shk0sh/FastHub#2606]
It would be nice to be able to click on a point on the contribution graph to see the number of commits / pull requests / etc... of the selected day

**Comment by yakov116** [comment]
@Androz2091 this is going to be removed in the future and is not going to be improved.

**Comment by Androz2091** [comment]
What? The contributions graph will be removed?

**Comment by yakov116** [comment]
@Androz2091 I dont even think its working now

**Comment by Androz2091** [comment]
But... why?

**Comment by k0shk0sh** [comment]
The way it works is using scrapping, going through an svg file from GitHub that could change anytime and its hard to maintain, basically what happens now, it stop working cuz GitHub changed how the svg works.
