### ISSUE TITLE
Not sure how to follow organizations

### ISSUE THREAD

**Issue by DroidFreak32** [k0shk0sh/FastHub#261]
I can follow users . I can follow a specific repository of an organization. But I'm can't find any option to follow the organization itself (ex omnirom )

**Comment by kutsan** [comment]
That's because there is no API nor GitHub support for that. See https://github.com/isaacs/github/issues/50

**Comment by DroidFreak32** [comment]
Then could you add an option to bookmark the organisation? No offense..Like how octo droid does it

**Comment by kutsan** [comment]
It's good idea but since this issue already irrelevant for that, I opened new issue for you: https://github.com/k0shk0sh/FastHub/issues/262. Thanks for understanding.
