### ISSUE TITLE
Merging PR not possible

### ISSUE THREAD

**Issue by martinfrancois** [k0shk0sh/FastHub#2611]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

 When I open a PR that I approved, it does say "This pull request can be merged" but there is nowhere a button to merge the PR.

**Comment by k0shk0sh** [comment]
Re-open the PR, this thing can happen! I saw it few times.

**Comment by martinfrancois** [comment]
What do you mean with re-open? Just pressing the back button and tapping on the PR again or to really close the PR and re-open it?
