### ISSUE TITLE
Error requesting server

### ISSUE THREAD

**Issue by lhriley** [k0shk0sh/FastHub#2613]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus3T  
---

 Nondescript error when opening the app. Nothing works.

**Comment by yakov116** [comment]
@lhriley try the latest version and report back
