### ISSUE TITLE
Open issue without footer 

### ISSUE THREAD

**Issue by Androz2091** [k0shk0sh/FastHub#2614]
I can't open an issue without the footer "Sent with Fasthub". I've purchased the app and I find that's not normal...
Please add the possibility to remove this footer!! 

_Envoyé depuis mon Honor 8 Lite en utilisant [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
You enabled that from the settings and this has nothing to do with pro features, its ur reference :)) .
I reckon you found out and that's why you closed the issue?

**Comment by Androz2091** [comment]
Yes that's it... 🤦‍♂️
Thank you
