### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by HitaloKun** [k0shk0sh/FastHub#2619]
**FastHub Version: 5.0**  
**Android Version: 9 (SDK: 28)**  
- **Manufacturer:** Samsung 
- **Brand:** Samsung  
- **Model:** Galaxy J7 2016
---

When I try to login it gives error at the time to connect on the server, no login method works.

**Comment by k0shk0sh** [comment]
I'm curious, how is that solved?

**Comment by k0shk0sh** [comment]
I reckon GitHub was down?

**Comment by HitaloKun** [comment]
To solve I had to use an old version (5.0) and log in it, after that I updated the APK.

**Comment by k0shk0sh** [comment]
@HitaloKun I appreciate that you are using v5. but this is still in development and therefore this might happen from now and then. I fixed it and gonna commit now. please do not open issues yet until V5 goes to beta :)
