### ISSUE TITLE
No trending

### ISSUE THREAD

**Issue by ugurozturk** [k0shk0sh/FastHub#2629]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S10+  
---

 It does not shown to trending. Tried via Access token and OAth

**Comment by ugurozturk** [comment]
Well I already checked opened issues. Yet there has no opened issue, but there is so much closed ones as shown it's dublicate. To which ? Which one is the original ?

**Comment by k0shk0sh** [comment]
Its hard to keep track of all of them, maybe I closed the original one after I got so confused about all of them. 

Anyway, its fixed in v5.
