### ISSUE TITLE
Feature request: skip onboarding

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#263]
- FastHub Version: 1.7.0
 - Android Version: 7.1.1
 - Phone Model: bacon

If a user is installing the app again, it prompts them with all the onboarding steps again, which is highly unnecessary.

**Comment by k0shk0sh** [comment]
You mean it shows the hints again?  Or the changelog?
If the first, that's kinda impossible lol.
If the latter, then in every update I'm showing you guys what's new, because trust me, some people need to know.

**Comment by arkon** [comment]
The first. I mean to offer a "skip" button somewhere.

**Comment by k0shk0sh** [comment]
@arkon well, if that happens then there is something wrong, I never encountered that nor anybody else I guess,  these will only be showing when user either logout, cleared app data or the user has already seen them. I can't produce it tbh.

**Comment by arkon** [comment]
@k0shk0sh It'll definitely happen if a user installs the app on multiple devices (like I did today), or they're reinstalling things after flashing a new ROM, for example. In these cases, they'll already be familiar users so onboarding isn't necessary, therefore having an option to skip it would be great.

**Comment by k0shk0sh** [comment]
Well then, that make sense now. They are just  few and I don't think they make any harm tho, I'll see what I can do about it.

**Comment by chamini2** [comment]
I support adding a `skip` button that marks all hints as shown already.

**Comment by k0shk0sh** [comment]
Alright, I'll see what I can do about that, however this will increase the complexity of adding new hints which you guys might not even notice it, so skipping previous one will also mark new ones as skipped. I haven't really come up with something about it till today.

**Comment by smichel17** [comment]
I presume right now there's a trigger for each hint; when that happens, it checks if the hint has been shown and, if not, shows it.

If you added a `Skip all hints` action while hints are shown (which seems to make sense here), it would set a global `skipHints` value in the preferences, and before showing a hint you'd just check `if (!skipHints)` as an additional condition.

**Comment by k0shk0sh** [comment]
@smichel17 PR?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
This issue has been appealed to in commit 6d4f715.
