### ISSUE TITLE
Scrolling problems

### ISSUE THREAD

**Issue by RuthwikHM** [k0shk0sh/FastHub#2632]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5S) Plus  
---

 Cant scroll down the in the readme tab when viewing repository. Only catches scrolling when you switch to the code tab scroll down there and switch back to the readme tab.

**Comment by yakov116** [comment]
@RuthwikHM link?

**Comment by RuthwikHM** [comment]
Yea man it works fine now.
