### ISSUE TITLE
[Feature Request] Provide greater organisation of notifications like GitHub

### ISSUE THREAD

**Issue by beastdestroyer** [k0shk0sh/FastHub#2639]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI 8 Lite  
---

 Hey there, first want to say this is a great app!

On GitHub's website, the notifications page is organised in such a way that ot separates them by repo:

org/repo
10 notifications
Read more

org/repo2
10 notifications
Read more

You get the point, my idea is to do something like that in this app, it would really help! 

EDIT: This is for the "Unread" section 

Additionally, GitHub has a drop down where you can filter notifications by repo, so you could show only notifications from this repo, or another repo or all notifs, which again would be very helpful.

**Comment by k0shk0sh** [comment]
Isn't that what all notifications does? 
Also this has been discussed many times here, lack of proper API is what makes the notifications to be how they are now!
