### ISSUE TITLE
Weird glitch

### ISSUE THREAD

**Issue by Mannivu** [k0shk0sh/FastHub#2640]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI 8  
---

After pressing the "Info" button in the top corner of the issue view, I encountered a weird glitch, with the repository Infos bouncing up and down.

![Short video](http://imgur.com/a/8V5fYu9)

**Comment by yakov116** [comment]
Thanks for your feedback
