### ISSUE TITLE
Bugs with reactions

### ISSUE THREAD

**Issue by Androz2091** [k0shk0sh/FastHub#2641]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** Honor 8 Lite  
---

https://imgur.com/a/oudVehk

**Comment by yakov116** [comment]
Thanks for your feedback

**Comment by yakov116** [comment]
@Androz2091 this has been fixed in the latest version
