### ISSUE TITLE
Trending section is not working anymore

### ISSUE THREAD

**Issue by oscargm** [k0shk0sh/FastHub#2647]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P10  
---

 Trending section always worked but seems that is kot working anymore.
No update done to break the functionality.

### steps to reproduce

- navigate to trending
  - no trending results are shown
- navigate to trending
  - filter by a language
  - no trending results are shown

**Comment by CalvinNor** [comment]
Yep. Wait for v5. Won't be fixed in this version. Check some other issues, you'll find Kosh's reply.

**Comment by oscargm** [comment]
Now I see. Sorry for the noise.
