### ISSUE TITLE
trending not available 

### ISSUE THREAD

**Issue by MichaelPan24** [k0shk0sh/FastHub#2657]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S10  
---

 The trending failed to load

**Comment by rancidfrog** [comment]
Peter should fix it

**Comment by rancidfrog** [comment]
#2510 #2654 #2647 #2637 #2633 . . .
