### ISSUE TITLE
Star function isn't working

### ISSUE THREAD

**Issue by evram94** [k0shk0sh/FastHub#2665]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** POCO F1  
---
When you start anything like a gist for instance it's not in the starred section in your profile

**Comment by k0shk0sh** [comment]
the gists in ur profile aren't what u starred, but rather the ones u forked or created
