### ISSUE TITLE
Why can't I start a new repositorie


### ISSUE THREAD

**Issue by phoenix4life84** [k0shk0sh/FastHub#2667]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Alcatel  
- **Brand:** TCL  
- **Model:** TETRA  
---

 Help

**Comment by k0shk0sh** [comment]
You can't create new repo from fasthub.

**Comment by phoenix4life84** [comment]
Thank you
