### ISSUE TITLE
Downloaded Apk's Crash When Opened From Notification Bar

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [k0shk0sh/FastHub#2675]
Issue: When an APK is downloaded, it pops up stating the download is complete in the notifcation bar, when this is clicked (To install), it takes to the Apk install, then you click "Install" and it crashes. If I then go back to the Fasthub folder in file manager, open the apk and click install again, everything works properly. I have not had this issue with any other app/file.

---

**FastHub Version:**  4.6.7
**Android Version:**  9
**Device Information:**  Unrooted
- MANUFACTURER: LG
- BRAND: LG
- MODEL: LM-V405TA (V40 - T-Mobile Variant)

**Comment by k0shk0sh** [comment]
No idea tbh, its a system download and nothing to do with Fasthub, but I improved on the download on next release. give it another shot when its released.
