### ISSUE TITLE
Problem assigning reviewers to issues

### ISSUE THREAD

**Issue by danielmombourquette** [k0shk0sh/FastHub#2682]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 3  
---

 Hello,

When I attempt to assign someone to an issue after having created and submitted the issue, it allows me to choose the assignee but after I hit submit, and then click the issue, it hasn't updated and still has there's no assignee.

If you have questions you may email me.

Kind regards,

Daniel Mombourquette
Couryah Courier Services
Dan.mombourquette@couryah.com

**Comment by k0shk0sh** [comment]
you might just need to refresh the list :)
