### ISSUE TITLE
Open/Close link bug

### ISSUE THREAD

**Issue by HirotakaTech** [k0shk0sh/FastHub#2686]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI MIX 2S  
---
If you try to open a link to GitHub of an inexistent page the app will open and close very fast several times. Here there is an example link:
 https://github.com/Exit93/vk-media-crawler

**Comment by yakov116** [comment]
@HirotakaTech it's not found so fasthub opens the browser page. 

This is the correct action.
