### ISSUE TITLE
Way too high polling rate

### ISSUE THREAD

**Issue by ShayBox** [k0shk0sh/FastHub#2691]
In the past 14 hours the app has requested github 1000 times, I haven't opened the app or even used my tablet, it shouldn't be polling that often.
![image](https://user-images.githubusercontent.com/9505196/64089826-f92d1780-cd15-11e9-9751-8ea786c3f9dd.png)

EDIT: It's gone up 600 in 4 hours since I made this issue
EDIT: It's gone up to 2300 since I made the last edit

**Comment by k0shk0sh** [comment]
the app doesn't pull anything in the background except for one thing (notifications) if they are enabled. so I honestly, the author of this app have no idea what are you referring to! 
raw.github is basically a base url for all the images you are seeing from within the app.

**Comment by ShayBox** [comment]
Well that would be the problem then, either way if its accessing github that many times, you need to cache, that's insane, it's making more connections than anything else on the network, and that's a hard contender with amazon devices.

**Comment by k0shk0sh** [comment]
This will be improved in v5 when I get to use graphql more often to avoid calling punch of apis to get u a better content :)
