### ISSUE TITLE
Please add a back to top, down to bottom in issue view in V5

### ISSUE THREAD

**Issue by escamoteur** [k0shk0sh/FastHub#2715]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 3a  
---

 Hi,

If you have really long conversations or logs in issues it's annoying to scroll to the bottom or back to the top manually.
Adding a button to get to the first/last comment would be helpful

Cheers
Thomas

**Comment by k0shk0sh** [comment]
Already added. 

Thanks for requesting/reporting.. but as I mentioned in readme, only report things if necessary! Im trying to focus on v5 and forgetting that v4 exists. 

Thanks!

**Comment by escamoteur** [comment]
That's why I wrote for V5 😁Am 22.09.2019 20:31 schrieb Kosh Sergani <notifications@github.com>:Already added.
Thanks for requesting/reporting.. but as I mentioned in readme, only report things if necessary! Im trying to focus on v5 and forgetting that v4 exists.
Thanks!
