### ISSUE TITLE
README.MD Scrolling

### ISSUE THREAD

**Issue by Randoragon** [k0shk0sh/FastHub#2718]
**FastHub Version: 4.6.7**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia\xe2\x84\xa2 M4 Aqua  
---

In repository view, the scroll position resets back to top when attempting to scroll down the README. It's possible to "break through" with quick finger strokes, but it appears very jittery and is annoying.

**Comment by yakov116** [comment]
@Randoragon let's wait for v5
