### ISSUE TITLE
Navigation drawer is cut off my the status bar on Android 10

### ISSUE THREAD

**Issue by afollestad** [k0shk0sh/FastHub#2719]
**FastHub Version: 4.6.7**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 3 XL  
---

Especially on the Pixel 3 XL, since the status bar is taller than other devices.

**Comment by k0shk0sh** [comment]
Yeah, I'm aware of that, since im not working on v4 anymore and in v5 the drawer has been replaced with bottomSheet. 

Soon I'll be releasing a beta version as soon as im done with displaying the repo.

Stay tuned for that ;)
