### ISSUE TITLE
Up button doesn't follow Android guidelines

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#272]
The up button in the app bar is acting like the back button, which isn't what the behaviour [is expected to be](https://developer.android.com/design/patterns/navigation.html).

**Comment by k0shk0sh** [comment]
Its fixed locally.

**Comment by k0shk0sh** [comment]
This one
https://github.com/k0shk0sh/FastHub/commit/7e0a407863060cd66cc9765b128ddec815340175
