### ISSUE TITLE
Account delete

### ISSUE THREAD

**Issue by phoenix0168** [k0shk0sh/FastHub#2722]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy J2 Pro  
---

 Hello please don't fuck me around delete my total account from yr system don't need account didn't want account, thanku

**Comment by 488315** [comment]
Go to unwatch tis repository

**Comment by phoenix0168** [comment]
Please I tryed to delete my account I followed all prompts and whn it came to hit the final stage of account deletion it won't highlight and allow me to click on link to delete please help me by deleting my account
