### ISSUE TITLE
Support for geojson file preview

### ISSUE THREAD

**Issue by kid1412621** [k0shk0sh/FastHub#2723]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 5T  
---

 Just like GitHub web .

**Comment by yakov116** [comment]
@kid1412621 let's wait for v5. If you still have an issue please open a new one 

Thanks
