### ISSUE TITLE
svg file is not loaded on markdown.

### ISSUE THREAD

**Issue by jjangga0214** [k0shk0sh/FastHub#2725]
Svg image is not rendered on markdown file. 

For example, README.md of [jjangga0214/hasura-cli](https://github.com/jjangga0214/hasura-cli) has a banner svg image. It's rendered well on mobile chrome like the screenshot below.

**chrome mobile**

![Screenshot_2019-10-01-13-07-03-782_com android chrome](https://user-images.githubusercontent.com/28584151/65933577-f4f73580-e44c-11e9-86b5-229481f61ad3.jpg)

However, on FastHub, it's not shown like the screenshot below.

**FastHub** 

![Screenshot_2019-10-01-13-06-07-974_com fastaccess github](https://user-images.githubusercontent.com/28584151/65933591-0a6c5f80-e44d-11e9-8b13-4db0ed1898d1.jpg)

**FastHub Version:**  4.6.7
**Android Version:** 9
**Device Information:**  
- MANUFACTURER: Xiaomi
- BRAND: Xiaomi
- MODEL: Redmi Note 8 pro

**Comment by yakov116** [comment]
@jjangga0214 let's wait for v5 and see if it's still an issue.

Thanks for your feedback and don't hesitate to open a new issue once it's released.
