### ISSUE TITLE
Cannot see the blue contributions grid when github accounts have activity overview enabled 

### ISSUE THREAD

**Issue by elihschiff** [k0shk0sh/FastHub#2729]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6T  
---

The blue contributions grid only shows up for accounts that haven't enabled the new github activity overview feature

To see if someone has this feature enabled go to their profile on the desktop github website and if it has the bottom stuff they have it enabled you cannot see their contributions on FastHub

**Comment by yakov116** [comment]
@elihschiff the entire feature is gooing to be removed in V5
