### ISSUE TITLE
Feature request: show overall PR file changes

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#273]
- FastHub Version: 1.7.0
 - Android Version: 7.1.1
 - Phone Model: bacon

The PR view currently shows the conversation and commits, but not having an overall files changed tab (like GitHub or Octodroid) makes reviewing PRs difficult.

**Comment by eygraber** [comment]
I think this is somewhat related to https://github.com/k0shk0sh/FastHub/issues/197
