### ISSUE TITLE
Notifications without GCM

### ISSUE THREAD

**Issue by thermatk** [k0shk0sh/FastHub#274]
It turns out there is a notifications service, which doesn't work if there are no Google Play Services.

- minSdkVersion 21 - so there is the standard [JobScheduler available](https://developer.android.com/reference/android/app/job/JobScheduler.html), why not use it?
- https://github.com/evernote/android-job is also a nice and flexible solution, more universal

Just for fun, I have already ported it to android-job :)
What do you think?
This is also important for #136

**Comment by k0shk0sh** [comment]
Well, I used it because at first I had plans for it & of course, using 21 doesn't mean that we don't use support libs, because we should :D. If you have ported it to something that works properly, please feel free to submit a PR & I'll review it as soon as I discharged from hospital.

Thanks for your effort tho.

**Comment by thermatk** [comment]
I'm only concerned about firebase jobdispatcher, which is not needed for its features, yet harmful in this case.
I'll be happy if someone will test it properly, WIP here:
https://github.com/thermatk/FastHub/tree/android-job

**Comment by k0shk0sh** [comment]
@thermatk I just checked it from my phone and everything looks fine, I'll definitely check it more when I discharged which probably tomorrow.
Thanks.

**Comment by thermatk** [comment]
There is one possible bug I would expect, but i don't know how to test for it:
https://github.com/evernote/android-job/blob/master/FAQ.md#how-can-i-remove-the-gcm-dependency-from-my-app
