### ISSUE TITLE
Error wiki page

### ISSUE THREAD

**Issue by 3xploiton3** [k0shk0sh/FastHub#2746]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 5  
---

 Error cant view wiki page
![](https://i.imgur.com/TRRFHRj.jpg)

**Comment by ringosham** [comment]
Known issue since last year.

Duplicate of #1972
