### ISSUE TITLE
User feed: code review

### ISSUE THREAD

**Issue by Androz2091** [k0shk0sh/FastHub#2754]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** Honor 8 Lite  
---

Code reviews like pull request reviews are not displayed in the feed tab on the user profile page

**Comment by yakov116** [comment]
@Androz2091 if github does not add them to the user feed, There is no way for us to get the information.  

You can contact github to add them to the feed.
