### ISSUE TITLE
Don't realize that one cannot add an image to an issue until it's too late

### ISSUE THREAD

**Issue by jidanni** [k0shk0sh/FastHub#2755]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone 3 (ZE552KL)  
---

 The user enters the title, and the description to an issue. Only then does he realize there is no way to add an image. So he wasted all that typing.

**Comment by Androz2091** [comment]
😂

**Comment by k0shk0sh** [comment]
there is a markdown editor for the description that u can use and scroll to left and there will be an image icon where it allow u to upload an image.
