### ISSUE TITLE
Item missing from 'Issues' -> 'Participated' list

### ISSUE THREAD

**Issue by metaMMA** [k0shk0sh/FastHub#2758]
**FastHub-Libre Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

 
A few months ago, an item that was listed in my 'Issues' -> 'Participated' list went missing. Here is the issue I participated in:

https://github.com/astrada/google-drive-ocamlfuse/issues/420

It is the only one missing from the list.

**Comment by metaMMA** [comment]
This issue is also missing from my 'participated' list.

**Comment by yakov116** [comment]
@metaMMA we do not support the libre version

**Comment by metaMMA** [comment]
The issue is in the app I downloaded from the Google play store. You can see in the attached photo, I'm using that one. I have the libre one downloaded too, though (perhaps that's why the version was autopopulated that way)
