### ISSUE TITLE
Issues missing from Participated' list

### ISSUE THREAD

**Issue by metaMMA** [k0shk0sh/FastHub#2763]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

 
A few months ago, an item that was listed in my 'Issues' -> 'Participated' list went missing. Here is the issue I participated in:

https://github.com/astrada/google-drive-ocamlfuse/issues/420

This issue is also missing from my 'participated' list.  
https://github.com/k0shk0sh/FastHub/issues/2758

Screenshot: 
https://pasteboard.co/IERWxJa.jpg

**Comment by k0shk0sh** [comment]
please refer to FAQ if these are private repos or organization repos
