### ISSUE TITLE
Can't download file from repo

### ISSUE THREAD

**Issue by yokidjo** [k0shk0sh/FastHub#2765]
**FastHub Version: 4.6.7**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR  
- **Model:** honor 6x  
---

 I can't download files from repo

**Comment by yakov116** [comment]
@yokidjo is it a private repo?

**Comment by yokidjo** [comment]
yesОтправлено с моего устройства Huawei-------- Исходное сообщение --------Тема: Re: [k0shk0sh/FastHub] Can't download file from repo (#2765)От: yakov116 Кому: k0shk0sh/FastHub Копия: Oleg ,Mention @yokidjo is it a private repo?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/k0shk0sh/FastHub/issues/2765?email_source=notifications\u0026email_token=AEAVMLB6XEE7KV6453ASGLDQ3CVPNA5CNFSM4JJFPNCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHZAISQ#issuecomment-569508938",
"url": "https://github.com/k0shk0sh/FastHub/issues/2765?email_source=notifications\u0026email_token=AEAVMLB6XEE7KV6453ASGLDQ3CVPNA5CNFSM4JJFPNCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHZAISQ#issuecomment-569508938",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yakov116** [comment]
#2742
