### ISSUE TITLE
Can't login using Access Token method. 

### ISSUE THREAD

**Issue by NP-Prob** [k0shk0sh/FastHub#2769]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

 I can't login using Access Token method, even when I disabled the 2-step authentication. 
I can login but will log out in just 1 second.
Don't know why. 
Could you solve this problem please? Thank you !

**Comment by k0shk0sh** [comment]
please refer to the FAQ
