### ISSUE TITLE
Mark as read and mute buttons hard to hit

### ISSUE THREAD

**Issue by alerque** [k0shk0sh/FastHub#2779]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

I've started using this app more regularly to triage issues from the train before I get to work so I am left with just things I want to dig into when I get there. What was a minor annoyance before has now become almost a blocker…

In the notifications list, the two buttons on the right, mark as read and mute, are both very hard to hit reliability. I regularly miss and open the issue instead. This might be exacerbated by the very small dpi and fort size settings I use.

Idealy the entire area of the notification that has buttons would actuate the buttons. If I want to open instead I would not be trying to hit the slivers around those buttons.

**Comment by k0shk0sh** [comment]
just removed the unsubscribe button and hopefully that will add more space. 
P.S: in v5 there is no buttons but rather swipe functionality to mark as read, so please for now lets stick to the icon and when v5 is released it will improve this alot
