### ISSUE TITLE
Two dropdowns on PR and Issue views

### ISSUE THREAD

**Issue by adriaanzon** [k0shk0sh/FastHub#278]
The pencil icon on the left button suggests an immediate action when clicking on the button, but it opens a dropdown instead.

I think it would make more sense let the 'pencil' button open the edit view immediately, and move the remaining actions to the dropdown of the button on the right, under the 'share' option.

These buttons are the ones I'm talking about:

![screencast_2017-04-08-01-16-16](https://cloud.githubusercontent.com/assets/4326420/24823283/fa1fe9c8-1bfc-11e7-9490-5a8f90066ae1.gif)

---

 - FastHub Version: 1.7.0
 - Android Version: 5.1.1
 - Phone Model: Xiaomi Redmi Note 3

**Comment by k0shk0sh** [comment]
I might drop the overflow with share action instead of having a drop down on a just single action, but the edit icon going to remain to avoid any breaking behavior.

**Comment by adriaanzon** [comment]
Alright. Great job on the app BTW. It's the first GitHub app I've come across that's actually useful 😆
