### ISSUE TITLE
Profile icon always showing squarish one only

### ISSUE THREAD

**Issue by MinkiDev** [k0shk0sh/FastHub#2780]
**FastHub Version: 4.6.7**  
**APK Source: Unknown**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** SM-N976N  
---

disabled square icon option, but it always showing square profile icon from left drawer.

**Comment by yakov116** [comment]
@MinkiDev this should be fixed
