### ISSUE TITLE
Purchase Not Going Through

### ISSUE THREAD

**Issue by johnny-nguyen-ck** [k0shk0sh/FastHub#2783]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S9  
---

 I purchased the Enterprise features for FastHub but the app is not giving me access to the advanced features.

**Comment by yakov116** [comment]
@johnny-nguyen-ck still an issue?
