### ISSUE TITLE
Github's official android app

### ISSUE THREAD

**Issue by MartinX3** [k0shk0sh/FastHub#2784]
How will fasthub compete with it?
https://www.xda-developers.com/github-will-soon-release-an-android-app-with-dark-mode-support/amp/

**Comment by k0shk0sh** [comment]
The way I see it, GitHub is gonna compete with FastHub. The only difference, they have over advantage cuz they could use a apis aren't public.

**Comment by ShayBox** [comment]
The advantage I see is a working app that doesn't have hundreds of closed reports about the same problem.

**Comment by MartinX3** [comment]
@ShayBox 
But
1. The github app has no git repo for issue tickets
2. I applied for te beta test, but still didn't got a download link to test it
