### ISSUE TITLE
Editing an issue crashes the app

### ISSUE THREAD

**Issue by Androz2091** [k0shk0sh/FastHub#2787]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** Honor 8 Lite  
---

When I try to edit my issue, the app reloads: https://gfycat.com/ignorantdecentamazondolphin

**Comment by k0shk0sh** [comment]
its a device specific issue and unforetunely it can't be solved unless `HUAWEI` stop messing around with android framework component.

**Comment by Androz2091** [comment]
Ok, too bad...
