### ISSUE TITLE
Unable to merge approved PR?

### ISSUE THREAD

**Issue by Integralist** [k0shk0sh/FastHub#2788]
**FastHub Version: 4.6.7**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2  
---

Hi! This is very likely a user error issue but for the life of me I cannot locate the button for merging an approved PR?

I'm using the pro version. 

If you could provide a screenshot or instructions on how to that please. 

Many thanks!

**Comment by busybox11** [comment]
To merge a PR you click on the edit button on the top right of the comment and click "Merge"

**Comment by Integralist** [comment]
Heya @busybox11 thanks for the info but I seriously cannot see what you seem to be seeing 🤔 

Could you provide a set of screenshot images so I can visually see where you're clicking an on which buttons/menu items as it could be that I'm just being very dumb and not understanding what you've told me properly.

Thanks again!

**Comment by busybox11** [comment]
![](https://i.imgur.com/sHHkO90.png)
Click on the edit button in the top right corner and then you should have a pop-up menu showing containing "merge".

Sorry for the late response and for not providing a second screenshot, I just merged this PR ^^'
