### ISSUE TITLE
Low contrast in main features of the app

### ISSUE THREAD

**Issue by mateodevia** [k0shk0sh/FastHub#2798]
**FastHub Version:**  v5 Debug
**Android Version:**  API 29
**Device Information:**  
- MANUFACTURER: Motorola
- BRAND: Moto G
- MODEL: Moto G6 Play

There are several places in the app where the choice of text color makes the reading very dificult of nearly imposible. In some cases the pure visibility of text may hide some important functionalities.
Here are some examples:
![image](https://user-images.githubusercontent.com/35933399/69487834-c4b98b00-0e2e-11ea-829d-fecee3ece341.png)
![image](https://user-images.githubusercontent.com/35933399/69487850-f16da280-0e2e-11ea-801d-427a9eb4eb10.png)
![image](https://user-images.githubusercontent.com/35933399/69487842-d9961e80-0e2e-11ea-914c-ab54f6e94c2f.png)
![image](https://user-images.githubusercontent.com/35933399/69487805-157cb400-0e2e-11ea-9ca0-e4b6f12e31aa.png)
This last two example are important because users may ignore the existance of those buttons . For example, in the Notifications VIew, the users might ignore the fact that they can switch between READ and UNREAD notifications. In my case, I discovered that functionality by accident.

**Comment by k0shk0sh** [comment]
Aware of that and FastHub v5 is still under development and in no chance its done or useable. 

Please wait until its done and only then report bugs.
