### ISSUE TITLE
Can I create forks/branches? 

### ISSUE THREAD

**Issue by camillo777** [k0shk0sh/FastHub#280]
Hi, 
I did not find a way to edit/modify files and commit/push changes. 
Is there some source control actions or is it a github browser only by now? 
Thank you 
Camillo

**Comment by k0shk0sh** [comment]
Nope, FastHub does not behave as a source control, it'll be massive to implement that. 
You could merge PRs but you can't create branches or do any other source control actions. 
Thanks.

**Comment by caffeinatedMike** [comment]
@k0shk0sh Having added this feature in a python program I made a few years back I can confirm it's possible and not too hard.

In fact, here's [a simple walkthrough of the steps](https://gist.githubusercontent.com/Potherca/3964930/raw/b92c9522add82ff2a1c33f555cf52e996478e1e6/Create-branch-with-Github-API.md) using the api. 

Disclaimer: This isn't my walkthrough.

**Comment by lokal-profil** [comment]
With #1143 now being planned this should be possible using the create a reference action
