### ISSUE TITLE
User Access Token Stored as Plain Text

### ISSUE THREAD

**Issue by mateodevia** [k0shk0sh/FastHub#2800]
**FastHub Version:**  v5 Debug
**Android Version:**  API 29
**Device Information:**  
- MANUFACTURER: Motorola
- BRAND: Moto G
- MODEL: Moto G6 Play
---
When a user logs in, the login functions call the insertUser from the loginWithAccessTokenUseCase found in the com.fastaccess.github.usecase.auth package. As an example, we show the loginBasic function found in the LoginViewModel class in the com.fastaccess.github.ui.modules.auth.login package.
![image](https://user-images.githubusercontent.com/35933399/69488133-6216be00-0e33-11ea-9a46-5909a03fcea3.png)
The loginWithAccessTokenUseCase.insertUser function is shown next, note that the function calls the loginRepository.insert method.
![image](https://user-images.githubusercontent.com/35933399/69488141-6f33ad00-0e33-11ea-991b-d9daaf6800ef.png)
The loginRepository.insert function is found in defined in the LoginRepositoryProvider class in the com.fastaccess.data.repository package. This function, as seen here, simply class the login’s Dao insert function.
![image](https://user-images.githubusercontent.com/35933399/69488155-9e4a1e80-0e33-11ea-8f37-f5d86aa1864d.png)
Following the app’s flow, the login’s Dao insert function is found on the LoginDao class in the com.fastaccess.data.persistence.dao package.
![image](https://user-images.githubusercontent.com/35933399/69488168-c76aaf00-0e33-11ea-99ce-ce2a40c4866b.png)
Finally, in order to understand what is being persisted, let us look at the LoginModel to understand what is being persisted in the Room Database, this class can be found in the com.fastaccess.data.persistence.models.
![image](https://user-images.githubusercontent.com/35933399/69488200-157fb280-0e34-11ea-890f-46b87fda6dd4.png)
Note that the model contains the user’s authorization token, additionally, note that nowhere in the app’s flow is the information that is being inserted into the database cyphered, meaning that the Authentication token is being saved, in plain text on the room database, which could be accessed by any other app on the cellphone.

In order to demonstrate this vulnerability, we copied the database to our personal computers and opened the database using the sqlite command line, as it is now shown, we were able to extract the token with a simple SQL query.
![image](https://user-images.githubusercontent.com/35933399/69488208-2b8d7300-0e34-11ea-9004-0ed7d7a6a532.png)

**Comment by emansih** [comment]
> which could be accessed by any other app on the cellphone

From what I can tell, it is stored in the Fasthub's private data folder (/data/data/com.fastaccess.github/databases/FastHub-Login-Room-DB). The reason you are able to access the db file is because you are running a debug build. If you were to run a release build  **NO APPS** can access this folder unless it has UID 0, which is essentially root.

**Comment by k0shk0sh** [comment]
Android apps only work with their sandbox and the only way, the only way that someone can access the app database outside of FastHub then its via root access which I reckon whoever has root access understand the vulnerability that comes with it.

**Comment by rujbodyslam** [comment]
> **FastHub Version:** v5 Debug
> **Android Version:** API 29
> **Device Information:**
> 
> * MANUFACTURER: Motorola
> * BRAND: Moto G
> * MODEL: Moto G6 Play
> 
> When a user logs in, the login functions call the insertUser from the loginWithAccessTokenUseCase found in the com.fastaccess.github.usecase.auth package. As an example, we show the loginBasic function found in the LoginViewModel class in the com.fastaccess.github.ui.modules.auth.login package.
> ![image](https://user-images.githubusercontent.com/35933399/69488133-6216be00-0e33-11ea-9a46-5909a03fcea3.png)
> The loginWithAccessTokenUseCase.insertUser function is shown next, note that the function calls the loginRepository.insert method.
> ![image](https://user-images.githubusercontent.com/35933399/69488141-6f33ad00-0e33-11ea-991b-d9daaf6800ef.png)
> The loginRepository.insert function is found in defined in the LoginRepositoryProvider class in the com.fastaccess.data.repository package. This function, as seen here, simply class the login’s Dao insert function.
> ![image](https://user-images.githubusercontent.com/35933399/69488155-9e4a1e80-0e33-11ea-8f37-f5d86aa1864d.png)
> Following the app’s flow, the login’s Dao insert function is found on the LoginDao class in the com.fastaccess.data.persistence.dao package.
> ![image](https://user-images.githubusercontent.com/35933399/69488168-c76aaf00-0e33-11ea-99ce-ce2a40c4866b.png)
> Finally, in order to understand what is being persisted, let us look at the LoginModel to understand what is being persisted in the Room Database, this class can be found in the com.fastaccess.data.persistence.models.
> ![image](https://user-images.githubusercontent.com/35933399/69488200-157fb280-0e34-11ea-890f-46b87fda6dd4.png)
> Note that the model contains the user’s authorization token, additionally, note that nowhere in the app’s flow is the information that is being inserted into the database cyphered, meaning that the Authentication token is being saved, in plain text on the room database, which could be accessed by any other app on the cellphone.
> 
> In order to demonstrate this vulnerability, we copied the database to our personal computers and opened the database using the sqlite command line, as it is now shown, we were able to extract the token with a simple SQL query.
> ![image](https://user-images.githubusercontent.com/35933399/69488208-2b8d7300-0e34-11ea-9004-0ed7d7a6a532.png)
