### ISSUE TITLE
Premium code

### ISSUE THREAD

**Issue by hajaren1466** [k0shk0sh/FastHub#2802]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy J3 Orbit  
---

 Can I get the promo unlock code? I cant afford the pro version.

**Comment by MartinX3** [comment]
no

**Comment by hajaren1466** [comment]
Why not? A simple minded response deserves a little more insight. Please explain. Also, who are you?

**Comment by hajaren1466** [comment]
Besides, I can compile the debug build with the features if I wanted. It just seems like too much effort when a simple code and a button press could unlock it all in one operation. Why deny me it if I could obtain such things regardless of the decision?

**Comment by nitrog0d** [comment]
It's simple, just no.

**Comment by MartinX3** [comment]
please respect the work/effort the author/developer put into this app and be happy, that the app is partially free.

**Comment by DMSalesman** [comment]
@hajaren1466 Forks, my friend, exist for a reason. Just like search engines, now that I think about it.

**Comment by FADEOffical** [comment]
Funny. You don't get to decide the prize of most things. If you go to Walmart or so, you can't just say. "Aye yo lemme get a *everything* for free". :)

It simply won't happen. :P

**Comment by DMSalesman** [comment]
Goods made of bytes != goods made of atoms. Physical world != virtual world.

... unless one can claim to CTRL-C everything inside a Walmart at a whim, that is.

**Comment by FADEOffical** [comment]
[*quietly hides copy-pasted Walmart in the basement*]

**Comment by MartinX3** [comment]
Bytes are represented in atoms.
And you pay for the time which took the recombination of these atoms and the service of support and getting a compiled binary ready to install.

I don't know what's wrong in some brains thinking just because something is IT based it must be free for all and the original author should die poor....

**Comment by DMSalesman** [comment]
You're half correct, you know. As a "pirate", I can't stand lazy "pirates", especially when a piece of work can be forked and built at will. Doubly so when one could simply check F-Droid.

Anyway, this should be an issue in a public repo, not another pointless debate in the sea of pointless debates of the web. Why isn't this marked as "wontfix" and closed already?
