### ISSUE TITLE
Milestone: Due_one is not a permitted key

### ISSUE THREAD

**Issue by hennell-git** [k0shk0sh/FastHub#2806]
**FastHub Version: 4.6.7**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7  
---
When creating an issue, and assigning a milestone, you can create a new millstone. However creating a milestone with a due date returns a notification that 'due_one' is not a permitted key.

Presumably this is a typo for 'due_on' somewhere, but makes it impossible to create a milestone with a date through the app.

**Comment by k0shk0sh** [comment]
Will be fixed and hopefully update today
