### ISSUE TITLE
GitHub Semantics

### ISSUE THREAD

**Issue by datwheat** [k0shk0sh/FastHub#281]
When PR's are empty, it says `No issues`, when it should be `No pull requests` since issues are in another tab and can be confusing. Screenshot is below: 
![](https://dl2.pushbulletusercontent.com/XmLTFValKkGtNzj7WTvjPEeLjHoAokpw/Screenshot_20170408-182214.png)

Thanks!

**Comment by k0shk0sh** [comment]
Nice catch.
