### ISSUE TITLE
Edit gist comment

### ISSUE THREAD

**Issue by MeirBon** [k0shk0sh/FastHub#2810]
**FastHub Version: 4.6.7**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S10+  
---

 When I try to edit one of my comments on a gist, the app crashes. I can post new comments just fine, but editing causes the app to crash.

**Comment by k0shk0sh** [comment]
@MeirBon can u post the comment in here that causes the crashe? I have the same phone as urs and i can't produce.

**Comment by MeirBon** [comment]
@k0shk0sh It's my last comment on this gist: https://gist.github.com/c99ae4e9e40f7e542361f646e4f637f5

When I try to edit it, the app just restarts.

**Comment by k0shk0sh** [comment]
@k0shk0sh  this guide is quite old by now and probably isn't up to date. When I got my XPS 15, Nvidia's Pascal GPUs were causing many issues if you weren't using Nvidia's drivers. The nouveau driver probably is a lot better nowadays thus you don't necessarily require all those flags. Still, if you want all the performance you can get out of your GPU I'd suggest installing the proprietary drivers.

**Comment by k0shk0sh** [comment]
still no crashes :'( 

can u try again and i'll check the crashlytics

**Comment by MeirBon** [comment]
I tried again :/ even just updated the app to the latest version which just came out but it still doesn't work. Anything else I can do to help? I'm also not running any custom rom or anything, just stock Galaxy S10+

**Comment by k0shk0sh** [comment]
@MeirBon do u get a dialog asking u to report the issue? as I can't actually see it in crashlytics. 
the thing is: i'm using the same device as yours and couldn't produce it! 🤦‍♂

**Comment by MeirBon** [comment]
@k0shk0sh no I don't get that. I did get that the first time hence why this issue was created (I wasn't aware at first it was going to create an issue on github). Anyway, I might just try to clear the caches and see if that helps. Btw you were testing it out on my gist, but could it be that it only happens when you're the owner of a gist?

**Comment by k0shk0sh** [comment]
alright, lets try this out, i'll create a gist and invite u to it.

**Comment by MeirBon** [comment]
@k0shk0sh doesn't crash for me either. Only that specific gist of mine seems to be a problem and I have no idea why. I just tried it on some other gist of mine as well and it worked fine, so I have no clue what it is either..

**Comment by k0shk0sh** [comment]
will make a release when i make other fixes/improvements

**Comment by MeirBon** [comment]
@k0shk0sh that's fine. Thank you for fixing the issue. It was just a minor inconvenience so I can wait :)
