### ISSUE TITLE
Translation.

### ISSUE THREAD

**Issue by FADEOffical** [k0shk0sh/FastHub#2817]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** FIG-LX1  
---

 Some texts are in German (phone language) and some in English. Pls fix c':

_Sent from my FIG-LX1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@FADEOffical you are welcome to contribute to the translation of these strings
