### ISSUE TITLE
Invalid repository size expression (ej. KB instead to MB)

### ISSUE THREAD

**Issue by md500** [k0shk0sh/FastHub#282]
Repositories doesnt show correct size:

Size of my repos showing invalid size( Linux kernel source has a size of 480Kb ? -Really??- )

https://drive.google.com/file/d/0ByF29pyl-DHeakRJOEFMejdHNjA/view?usp=drivesdk

Correct size in an other app (kernel size is 480Mb )

https://drive.google.com/file/d/0ByF29pyl-DHeTmw3ekRMLVdGN1E/view?usp=drivesdk

So, The problem is doesnt show correct size KB instead of MB)

Posible to fix this?

**Comment by k0shk0sh** [comment]
Its fixed in #251 probably tomorrow I'll release new version with issues/prs filter/search and alot of cool stuff.

**Comment by k0shk0sh** [comment]
https://drive.google.com/file/d/0BxbjAF1sbwjaMEJtZDFvZHhQa2s/view?usp=drivesdk
