### ISSUE TITLE
Crash when opening and scrolling a pull request

### ISSUE THREAD

**Issue by philoez98** [k0shk0sh/FastHub#2827]
**FastHub Version: 4.6.8**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P10 lite  
---

 The application crashes and restarts when scrolling inside a pull request

**Comment by k0shk0sh** [comment]
fixeed.

making a release right away

**Comment by philoez98** [comment]
@k0shk0sh thanks!

**Comment by k0shk0sh** [comment]
U can update now ;)
