### ISSUE TITLE
PR event strings could be improved

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#283]
- FastHub Version: 1.7.0
 - Android Version: 7.1.1
 - Phone Model: flo

In the attached screenshot:
- "referenced/merged This" should be "referenced/merged this"
- "review_requested" and "head_ref_deleted" need to be humanized

![2017-04-10 03 34 02](https://cloud.githubusercontent.com/assets/4098258/24845118/675da2ce-1d7d-11e7-9edb-d2b3ecb37c6d.png)

**Comment by k0shk0sh** [comment]
The first is done, however the second not yet 👍👍
