### ISSUE TITLE
Remove new version notifications

### ISSUE THREAD

**Issue by Bikonja** [k0shk0sh/FastHub#2830]
**FastHub Version: 4.6.9**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6  
---

 I just got a notification about a new version.
I have Google Play Store for that and yet I do not have the option to turn this notification off without turning off repo notifications as well. This is not ok at all, please remove this notification asap!

**Comment by k0shk0sh** [comment]
@Bikonja this notification was pushes by hand by me via firebase, you don't see this happen before right?
take it easy and promise next time wont be notification unless if its necessary!
