### ISSUE TITLE
Long files causes system freeze

### ISSUE THREAD

**Issue by Javinator9889** [k0shk0sh/FastHub#2831]
**FastHub Version: 4.6.9**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi A1  
---

 When trying to load big files (bigger than ~15 KiB) the system freezes because of an _ANR long dispatch_ (this error is usually caused because the load is blocking the main thread)

I'm having this error, for example, in Google Chrome while loading big webpages

**Comment by k0shk0sh** [comment]
the same for fasthub, the webview component is trash and it can't handle much load 🤦‍♂ so far, I have zero ideas on how to make this work without getting rid of code highlight

**Comment by Javinator9889** [comment]
@k0shk0sh maybe this can be helpful?
Instead of using system one use an alternative: https://wiki.mozilla.org/Mobile/GeckoView

**Comment by k0shk0sh** [comment]
I'll check it out despite it look complex and might increase app size a tones.
