### ISSUE TITLE
Viewing glitch at Releases

### ISSUE THREAD

**Issue by remaves** [k0shk0sh/FastHub#2832]
So when I on the releases menu on a rep. there is a sort of glitch when I tap on the "description" of the file
![Here a gif for that](https://i.imgur.com/XIVgrgI.gif)
 
**FastHub Version: 4.6.9**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 5T  
---

**Comment by k0shk0sh** [comment]
its better than before if u asked me :p
