### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by JoshuaGarrison27** [k0shk0sh/FastHub#2835]
**FastHub Version: 4.6.9**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 3 XL  
---

 This isn't a bug or anything. I just wanted to let you know I am sorry to hear that your mom was diagnosed with Cancer. I will pray for you and your family. Thank for you making a great app. I hope things get better for you.

**Comment by yakov116** [comment]
#2826
