### ISSUE TITLE
Starring Repositories Fails in 4.7.2

### ISSUE THREAD

**Issue by OnBeyondBeing** [k0shk0sh/FastHub#2844]
Starring a repository generates a notification, which doesn't go away until it's manually dismissed. The notification contains the text "Starring $RepositoryName" and a cyclical progress bar. 

Starred repositories are never actually added to account.

This bug was introduced in version 4.7.2. The previous version (4.6.9) could star repositories successfully.

**FastHub Version: 4.7.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** V20  
---

**Comment by yakov116** [comment]
@OnBeyondBeing link to repo. I just tried it and did not have any issues.

**Comment by yakov116** [comment]
@k0shk0sh I think we have an issue I am unable to star a repo too.
