### ISSUE TITLE
Not able to edit, delete files

### ISSUE THREAD

**Issue by rajibhalder** [k0shk0sh/FastHub#2848]
**FastHub Version: 4.7.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** xiaomi  
- **Model:** Redmi Note 4  
---

 I have purchased "All" license of Fast hub but could not able to edit, delete files. Could you please check.

**Comment by yakov116** [comment]
@rajibhalder is it a repo that is part of an org?

**Comment by rajibhalder** [comment]
No, it is my personal private repository.

**Comment by yakov116** [comment]
What error do you get?

**Comment by k0shk0sh** [comment]
U have to go to ur repo files and from there click on the menu next to the file and then click edit/delete it only works from there...

**Comment by rajibhalder** [comment]
Thanks for your support. I got it. You can close the ticket now.

Happy New Year !!!

Cheers,
Rajib
