### ISSUE TITLE
FC in Android 5.0.1 : Unexpected end of document While opening App.

### ISSUE THREAD

**Issue by md500** [k0shk0sh/FastHub#285]
---

 - FastHub Version: 1.8.0
 - Android Version: 5.0.1
 - Phone Model: Galaxy S4 I9500

App doesnt open:

1/3: Trying to run...

https://drive.google.com/file/d/0ByF29pyl-DHeNDRxLXZFRFpRSFU/view?usp=drivesdk

2/3: Fasthub has stopped

https://drive.google.com/file/d/0ByF29pyl-DHeRkVWY1I5MkRJX00/view?usp=drivesdk

3/3 :Partial logcat

https://drive.google.com/file/d/0ByF29pyl-DHec2o1dkhxQkxtczA/view?usp=drivesdk

Complete logcat:

https://pastebin.com/hxeDgh2W

Tried Deleting all data for the app and is keeping FC...

**Comment by k0shk0sh** [comment]
Hmmm that's strange, let me get back home and look at the source of crash. Sorry for the inconveniences caused. 
P.S: if you try opening repo from​ outside of FastHub the app will crash. First reported in 1.8.0 by @kutsan

**Comment by k0shk0sh** [comment]
P.S: you could grab 1.7.0 from releases page until I fix this.
Sorry again

**Comment by md500** [comment]
Here The complete logcat:

https://pastebin.com/hxeDgh2W

**Comment by k0shk0sh** [comment]
I got the crash, its Android bug, they couldn't parse the repo icon (SVG).

```Exception android.content.res.Resources$NotFoundException: File res/drawable/ic_repo.xml from drawable resource ID #0x7f0200c9```

`Caused by java.lang.NumberFormatException: Invalid float: "-.55.45"` 

I guess 1.8.1 coming very soon & gonna drop that icon with another one for now.

**Comment by k0shk0sh** [comment]
I guess this is a specific OS issue. as I'm not having that crash :'(

**Comment by k0shk0sh** [comment]
1.8.1 is released it might take 30minutes to be in playstore.
sorry for the inconvenience
