### ISSUE TITLE
[FR] Use issue templates when opening issues with FastHub

### ISSUE THREAD

**Issue by erip** [k0shk0sh/FastHub#2852]
**Is your feature request related to a problem? Please describe.**

Issues created using FastHub are occasionally closed because the app ignores issue templates.

**Describe the solution you'd like**

The client should follow prompts like the GitHub web app does as drawn from `.github/`

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by yakov116** [comment]
@erip is there an API for that?

**Comment by erip** [comment]
@yakov116 not directly, no. You could use the content API with path `.github/ISSUE_TEMPLATE` and see the files listed there to construct the appropriate views; if nothing exists under that directory, free text issues as a fallback seems most reasonable. 

e.g., see https://api.github.com/repos/k0shk0sh/FastHub/contents/.github/ISSUE_TEMPLATE vs  https://api.github.com/repos/k0shk0sh/KAM/contents/.github/ISSUE_TEMPLATE

**Comment by k0shk0sh** [comment]
It has been done in v5 :)
