### ISSUE TITLE
Replace member with username when someone added in repository

### ISSUE THREAD

**Issue by dikiaap** [k0shk0sh/FastHub#287]
**App Version: 1.8.1**

**OS Version: 22**

**Model: Evercoss-EVERCOSS A65**

Sometimes I confused, who is this, when someone added into organization repository.

This is what FastHub does:
`org added member org/repo`

In GitHub website:
`org added username to org/repo`

**Comment by k0shk0sh** [comment]
Well, tbh GitHub doesn't have a good documentation for its API, so I couldn't really know what will be passed & what not, hence, that's why you are seeing such events that don't make sense.

**Comment by dikiaap** [comment]
@k0shk0sh Hmm, It still doesn't appear.
![screenshot_2017-04-24-00-28-59 01](https://cloud.githubusercontent.com/assets/8542502/25315816/8b2ff5ea-2885-11e7-86bb-b6965fbf35fa.png)

**Comment by k0shk0sh** [comment]
Oops, I thought I handled this!! P.S: I tried fixing it without simulating a real situation. Github might returning something different then what I'm excepting. Will look more into it
