### ISSUE TITLE
[FR] Show FAQ better when no organisations

### ISSUE THREAD

**Issue by ElianCodes** [k0shk0sh/FastHub#2879]
**Is your feature request related to a problem? Please describe.**
When you first use the app, it may not be really clear to people they have to grant access to FastHub to show the organisations

**Describe the solution you'd like**
Maybe it's an idea to show the FAQ instead of the no organisation found: try again button. I think people overlook the FAQ icon to quick.

maybe you could just set a text like this: No organisations found, did you grant access? Read full FAQ here. or something...

**Comment by MohamedElidrissi** [comment]
There's already an icon on the top right that shows some help text, do you think that's not enough?

**Comment by ElianCodes** [comment]
@MohamedElidrissi well, when you know it. It's obvious, but when you look at the issues, there's people still reporting this as an issue, so I think it would be a good solution to just display this as a text

**Comment by MohamedElidrissi** [comment]
Yeah ok, I think I can do something about it and open a PR
