### ISSUE TITLE
Cannot show contributions if the user has organizations

### ISSUE THREAD

**Issue by Macyrate** [k0shk0sh/FastHub#2884]
**FastHub Version: 4.7.3**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 6  
---

 ![Screenshot_20200313-081723.jpg](https://i.loli.net/2020/03/13/KkHRrDN5g4C298U.jpg)

**Comment by alyonatischenko** [comment]
Зуйня

**Comment by cmario92** [comment]
same here, exact same mobile, don't know if that matters

**Comment by cmario92** [comment]
managed to resolved my issue by accessing my GitHub applications from the website and granted access for my organization.
