### ISSUE TITLE
Can't authorize when Firefox is default browser

### ISSUE THREAD

**Issue by ffes** [k0shk0sh/FastHub#289]
- FastHub Version: 1.8.1
- Android Version: 6.0.1
- Phone Model: Nexus 5

I use Firefox for Android as my default browser. When I try to authorize the app through the browser it fails.

When I click on "Open in browser" I see Chrome opening the URL and almost directly the choice pops up to select an app to open the github URL. In my case three options show up: FastHub, ForkHub and Firefox. I select Firefox. Then I enter my credentials and my TFA code. After that a blank page opens and nothing happens. The apps remains unauthorized.

**Comment by k0shk0sh** [comment]
Does firefox closes itself upon success login? 
Does FastHub say anything? Like popup message or something. It could be a firefox issue than FastHub. But I'll be happy if we could sort it out.

**Comment by k0shk0sh** [comment]
I guess by blank screen you meant firefox does not close itself and return the data, well if that's the case, then its firefox bug.

**Comment by FallenKN** [comment]
It's a Firefox Bug since Firefox tries to open the redirected URL.
Click on the Android Icon in the URL Bar in Firefox after Authentification and select Fasthub. This way will work.

**Comment by k0shk0sh** [comment]
@FallenKN Thanks for clarifying this.
