### ISSUE TITLE
Navigation arrow bug

### ISSUE THREAD

**Issue by JLean30** [k0shk0sh/FastHub#2894]
**FastHub Version: 4.7.3**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** POCO F1  
---

 Hi great app I'm just bought it the premium freatures, but I have noticed a issue with the navigation arrow locate it at the top of the headers pages, this arrow sends me to the home page instead of the previous pages that I navigated it. Please fix this issue thanks.

**Comment by nt4f04uNd** [comment]
This is annoying thing for me too, but I guess this is intended to work like that, because he doesn't fix this for months. Really wanna see a change here

**Comment by k0shk0sh** [comment]
This is working as intended,

Please use device hardware back button or navigation to go back where you were or press top left back button to navigate deeply in hierarchy.
