### ISSUE TITLE
Support gitlab instances

### ISSUE THREAD

**Issue by ghost** [k0shk0sh/FastHub#2895]
**FastHub Version: 4.7.3**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi K20 Pro  
---

 Add support for gitlab instances and other git based providers.

**Comment by yakov116** [comment]
Was asked mutiple times search the issues
