### ISSUE TITLE
Pro version doesn't allow to edit files 

### ISSUE THREAD

**Issue by goxr3plus** [k0shk0sh/FastHub#2896]
**FastHub Version: 4.7.3**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** HUAWEI Mate 20 lite  
---

 I have pro version and i see nowhere the option to edit files...  :'(

**Comment by Username404-59** [comment]
Did you try to use the three dots on the right of the file you want to edit? http://imgur.com/a/2a5McKi 

I had the same problem when i started to use the pro version ^-^

**Comment by goxr3plus** [comment]
Hello :), now I see the problem I can't restore purchases I did.

I bought pro version with another phone how can I get it here again :'(. I logged in with the Gmail I made the purchase but nothing happens.

This app is full of bugs
