### ISSUE TITLE
Clicking the "You have notifications" notification or the action button doesn't do anything

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#29]

**Comment by k0shk0sh** [comment]
Are you using version 1.0.4? because in v1.0.4 this issue has been fixed. if you are using 1.0.4 and clicking on the notification doesn't do anything then there is a problem and we need to fix it. could you confirm that you are using 1.0.4.

**Comment by wasdennnoch** [comment]
I'm running 1.0.4 now but I hadn't yet updated the app when I had the issue, I can't confirm it's fixed but it should be now I guess.

**Comment by wasdennnoch** [comment]
Can confirm it's fixed now.

**Comment by k0shk0sh** [comment]
@wasdennnoch yup I'm aware of that and got it fixed locally. will be released in next release.
