### ISSUE TITLE
Back arrow from file in subfolder

### ISSUE THREAD

**Issue by gko** [k0shk0sh/FastHub#291]
**App Version: 1.8.1**

**OS Version: 24**

**Model: samsung-SM-G930F**

Hello,

Thank you for this app.

The «back arrow» within file(in file view mode) that is situated in subfolder(or any folder other than root) brings you back to root of the repository instead of folder where this file was located.

**Comment by k0shk0sh** [comment]
Hi @gko this issue has been resolved and soon will be released to playstore. 
thanks for ticket :)
