### ISSUE TITLE
Close collapsible markdown coming from details and summary tags

### ISSUE THREAD

**Issue by nitrocode** [k0shk0sh/FastHub#2912]
**FastHub-Libre Version: 4.6.7**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 3a  
---

Using the [details and summary tags](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d), we can add a collapsible widget to GitHub comments and PRs. Currently they show up as expanded in fasthub and cannot be collapsed (and surprisingly works fine in the gist i posted above).

<details>
<summary>testing expanded output</summary>

```
Line 1
Line 2
Line 3
```
</details>

**Comment by yakov116** [comment]
...FastHub-Libre
