### ISSUE TITLE
Links to github crash fasthub

### ISSUE THREAD

**Issue by mrwhale** [k0shk0sh/FastHub#292]
**App Version: 1.8.0**

**OS Version: 24**

**Model: motorola-Nexus 6**

Hey great project! Very pretty and useful. Since upgrading to the latest version I can't open github links with fasthub. It seems to crash the app.didnt have this problem with the last release.

Let me know if you want some logs and I can make it happe
Cheers!

**Comment by kutsan** [comment]
Hey @mrwhale. Could you please upgrade your version to 1.8.1 from Play Store? Because this issue already solved. Let me know if happens again.

**Comment by mrwhale** [comment]
Thanks @kutsan should have checked here first :P I'll update now

**Comment by kutsan** [comment]
No problem. Thanks for reaching out by the way. Any feedback greatly appreciated.
