### ISSUE TITLE
[BUG] Cant Log in - HTTP 422 Unprocessable Entity

### ISSUE THREAD

**Issue by UltraBlackLinux** [k0shk0sh/FastHub#2937]
Thats basically it. I cant login: All my tries return HTTP 422 Unprocessable Entity. On top of that the access token option is the same login as username + pass. Oauth doesnt work cause I hate chrome - why do I even need chrome (thats a good example for sth being bad: Being forced to use chrome.)

**FastHub Version:**  2.1.0.210
**Android Version:**  10
**Device Information:** 
- MANUFACTURER: Razer 
- BRAND: Razer Phone
- MODEL: cheryl  
---

**Comment by Qrashi** [comment]
This is (as far as i know) a bug on GitHubs side, 422 means that your request was valid and understood by the server but the server couldn't process your request

**Comment by hosin76** [comment]
في الخميس، ١٧ سبتمبر ٢٠٢٠ ٧:٣٥ ص Qrashi <notifications@github.com> كتب:
