### ISSUE TITLE
Download errors

### ISSUE THREAD

**Issue by Shenron0** [k0shk0sh/FastHub#2945]
**FastHub Version: 4.7.3**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus 7  
---

 I have been trying to download files from repositories that I'm following but the downloads are showing up unsuccessful every time

**Comment by Alauddinmallick** [comment]
Hiii

**Comment by Shenron0** [comment]
Hello

**Comment by Alauddinmallick** [comment]
Good morning

**Comment by Shenron0** [comment]
Good morning to you too

**Comment by cypher01-droid** [comment]
hi
