### ISSUE TITLE
I'm not able to find the application on Google play!

### ISSUE THREAD

**Issue by m98** [k0shk0sh/FastHub#295]
I'm from Iran, some applications are not accessible for us, actually, it means that the developer limited the country and people of the country, and they can't install the application. 

What's the reason that Iranian should not use FastHub?!
![media-20170412](https://cloud.githubusercontent.com/assets/7496103/24952437/a7453fee-1f8c-11e7-81c0-2838897058b1.png)

 - Android Version: 6.0 MRA58K
 - Phone Model: Xiaomi MI5

**Comment by k0shk0sh** [comment]
@m98 take it easy, i'm not limiting anybody to use the app lol. 

I guess it might be due to in-app-purchase? 

Let me also confirm on this from the developer console.

**Comment by m98** [comment]
Sorry if I seemed rude :) I did not mean bad.
But one of the main reasons that some apps are not accessable are because of their developers and their limitations, other things **maybe** is becuase of SDKs you used in the app. Like ads services (I'm not Android developer, I'm not sure if SDKs are a problem.)

Anyway, There are always these problems and they do not hurt me, but I did not expect an open-source app to be limited. I installed the Fast Hub (Thanks for VPNs) and that was great 👍  

Thanks for your hard work, everything works as expected in Fast Hub

**Comment by k0shk0sh** [comment]
@m98 trust me, I didn't limit it to anywhere & if I wanted to limit it to some regions I wouldn't have uploaded each release APK in releases page in GitHub, i'm investigating on this right now & thanks for the heads up. 

It might be due to Ads SDK but let me confirm and get back to you.

**Comment by k0shk0sh** [comment]
https://support.google.com/googleplay/android-developer/table/3541286?visit_id=1-636275895294727710-1560287421&rd=1

**Comment by m98** [comment]
Thank you for fast response.

By the way, even Google developer is blocked in Iran (developers.google.com), beside some more services from some other famous companies. I wish there was somewhere on Google to fill an issue about it 😀
We get used to it

**Comment by k0shk0sh** [comment]
I'm sorry about that tho, You could watch repo & always update the app from the releases page. 
I'm also considering fdroid thanks to @thermatk for his PRs regards fdroid distribution.

**Comment by thermatk** [comment]
@m98 how is it with F-Droid? Even if the main repo is blocked(where FastHub is not available yet :) ), there is the https://apt.izzysoft.de/fdroid/ binary repo which has FastHub uploaded already.

**Comment by m98** [comment]
@thermatk We have our own Android markets in Iran, they are working very well. But you can't find all programs there :)
I think F-Droid is also a good alternative for Google Play.

**Comment by kutsan** [comment]
Hey everyone, you can now download FastHub from F-Droid.
