### ISSUE TITLE
error

### ISSUE THREAD

**Issue by silentx07** [k0shk0sh/FastHub#2951]
**FastHub Version: 4.7.3**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** SM-A515F  
---

**Comment by magestic0100** [comment]
I have the CA Installer file on my device in my settings security. SSL SNAKEOIL. It is missing the key core.js/test/agent-proxy/ssl-cert-snakeoil.key
The target is SM-A205U my device with Boost Mobile is has enterprise sim kit protection with Sprint. I own the AdGuard CA used on https://aka.mw/aws I also own the L1K CA Root - for authorized use only that Sprint and Boost Mobile url uses.

**Comment by magestic0100** [comment]
I also own the digicert global root ca and secured server ca used on the url for https://jobs.amazon.com
