### ISSUE TITLE
Command settings in package termux-tools

### ISSUE THREAD

**Issue by Pavel-jpg** [k0shk0sh/FastHub#2959]
https://wiki.termux.com/wiki/Termux_Google_Play

_Отправлено с моего Galaxy S8 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mangalbimla** [comment]
Unable To Access E Drive Error

**Comment by mangalbimla** [comment]
Not resolved
