### ISSUE TITLE
Dosent display organization 

### ISSUE THREAD

**Issue by haxzie** [k0shk0sh/FastHub#297]
**App Version: 1.8.1**

**OS Version: 23**

**Model: samsung-SM-A700FD**

# whenever i click the tiny icon near the profile in nav drawer it shows a red toast saying no organization..  But in reality am owner of an organization :(

**Comment by k0shk0sh** [comment]
Hello @haxzie  were you an existing user of FastHub? 

If yes, then please re-login again so Github register the org scope.

if not: then please go to your profile/settings/auth apps & request your org to auth fasthub 

for more info #271
