### ISSUE TITLE
No private repos loading

### ISSUE THREAD

**Issue by TheDanniCraft** [k0shk0sh/FastHub#2990]
**FastHub Version: 4.7.3**  
**Android Version: 11 (SDK: 30)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** SM-A405FN  
---
Im New to this App, but my private repositorys does not load. Also other Page like the home Page don't load.
Every time the following Error:

![](https://i.imgur.com/xEsSS1j.jpg)

Plese fix that, then I may buy premium.

**Comment by umer9060** [comment]
Hi bro how are you alright

**Comment by umer9060** [comment]
:kissing_heart:
