### ISSUE TITLE
(9a812e0d7ddd20e68e40e431e44bb4da3e6e9da8"            

### ISSUE THREAD

**Issue by joydeygs** [k0shk0sh/FastHub#2991]
**FastHub Version: 4.7.3**  
**Android Version: 10 (SDK: 29)**  
**Device Information:**  
- **Manufacturer:** OPPO  
- **Brand:** OPPO  
- **Model:** CPH1933  
---

**Comment by l3laze** [comment]
@joydeygs This needs more information.

**Comment by Joanisrael** [comment]
Eo
