### ISSUE TITLE
Feature Request: Get notifications for new actions on repositories.

### ISSUE THREAD

**Issue by TheClashster** [k0shk0sh/FastHub#300]
**App Version: 1.8.1**

**OS Version: 25**

**Model: Motorola-MotoG3**

It would be a lot more functional if the app sent a notification along with a sound whenever there was a new comment or any new action involving the user such as a comment or star on their repositories or if the user wants, on repositories they watch.
Currently, the application does not give a notification for new comments on commits.

**Comment by k0shk0sh** [comment]
Well, I didn't include sound nor popup due to the fact, there might be to many notifications, I'll include that in settings to disable the sound. Thanks

**Comment by TheClashster** [comment]
Thanks a lot, sir! Great work with the app.

**Comment by TheClashster** [comment]
What constitutes a notification though, FastHub doesn't notify anything even on the repositories I watch, including my own even when someone pushes commits although t=all that activity is visible in the main stream when I open the app. I have to rely on emails for all activity since notifications on FastHub don't work. Not sure where the problem lies.

**Comment by k0shk0sh** [comment]
@TheClashster you should be receiving notifications, check in settings that you didn't disable it from notification interval & also when you read notification from email, it will be marked as read so FastHub won't display it.

**Comment by TheClashster** [comment]
@k0shk0sh Oh, but still shouldn't the read notification from email be displayed in the 'All' notifications tab?

**Comment by k0shk0sh** [comment]
yup they should ![image](http://i.imgur.com/uHrVCQu.png)

**Comment by TheClashster** [comment]
@k0shk0sh That's weird, doesn't happen with me.
![image](https://cloud.githubusercontent.com/assets/27063113/25008858/84f9c940-2082-11e7-858e-7b76d2d8d840.png)

**Comment by k0shk0sh** [comment]
yup, that's really weird. 

[NotificationService.java](https://github.com/k0shk0sh/FastHub/blob/a9dc6016c200eff2fd0751c00673017885dc2542/app/src/main/java/com/fastaccess/data/service/NotificationService.java#L29-L29)

[Github API](https://developer.github.com/v3/activity/notifications/#list-your-notifications)

not doing anything special or different :'(

**Comment by TheClashster** [comment]
Okay, I think I fixed it, I poked around in the GitHub profile settings and saw that in the watched option, notifications were set just to email, checking the web option did the thing. All cool now, thanks so much :)
