### ISSUE TITLE
Add check box keyboard shortcut

### ISSUE THREAD

**Issue by chamini2** [k0shk0sh/FastHub#302]
**App Version: 1.8.1**

**OS Version: 25**

**Model: LGE-Nexus 5X**

In the shortcuts there are lists and numbered lists, but sometimes we want to-do lists. I propose adding a shortcut that introduces `- [ ]` at the beginning of the line.

**Comment by k0shk0sh** [comment]
![Image](http://i.imgur.com/ui74d1f.png)

**Comment by k0shk0sh** [comment]
This is test, please ignore it.

- [x] todo checked
- [] todo unchecked
