### ISSUE TITLE
[Feature request] Option to disable multi-column lists

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#303]
**App Version: 1.8.1**

**OS Version: 25**

**Model: asus-Nexus 7**

Lists are shown as 2 columns on a tablet, but it makes it harder to read (in my opinion, at least). It'd be nice if this was configurable.

**Comment by k0shk0sh** [comment]
Could you attach an image? basically tablets should have 2 columns to make use of the screen, but I'd be glad if you could provide an image.

**Comment by k0shk0sh** [comment]
Oops, you are using nexus-7, its alright I got you, in portrait there should be one column & in landscape should be two. I'll fix that right away.

**Comment by arkon** [comment]
Not if you adjust the display settings. Here's a few screenshots: http://imgur.com/a/e4gJb

It becomes particularly problematic when things start getting misaligned between the two columns. In general, it's difficult to parse the information when reading on a Z pattern.

**Comment by k0shk0sh** [comment]
@arkon I have fixed this locally however, however in landscape it'll be in two columns & indeed I need to do something about that in terms of UI. - [x]

**Comment by k0shk0sh** [comment]
Hello Arkon, I guess i'll be closing this, since, now only in landscape the list will turn into two columns, I guess this would be perfect, because now comments only who are actually going to be two columns while labels, events will be in one column by themselves.
