### ISSUE TITLE
Bug | Issues comments markdown parser

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#305]
**App Version: 1.8.1**

**OS Version: 24**

**Model: samsung-SM-G950F**

When you're writing a comment, if you press on the "Preview" button without adding text (chars), as shown below, you cannot back to edit mode

![screenshot_20170414-085936](https://cloud.githubusercontent.com/assets/23010471/25036222/ca146966-20f2-11e7-8867-b9d9fe086c94.png)
 

In this case the original input was:
![screenshot_20170414-085930](https://cloud.githubusercontent.com/assets/23010471/25036251/fd2d4052-20f2-11e7-8953-7f2775d1abb9.png)

**Comment by k0shk0sh** [comment]
Good catch, thanks for reporting.
