### ISSUE TITLE
Readme files in viewer anchor links doesn't work

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#306]
**App Version: 1.8.1**

**OS Version: 25**

**Model: htc-m8**

**Comment by camillo777** [comment]
Yes link is like this, is it correct or modified by Fast hub? 

file:///android_asset/md/#availablefields

**Comment by k0shk0sh** [comment]
@camillo777 probably, I haven't checked on it and just yesterday noticed it. I'll try and fix it today

**Comment by k0shk0sh** [comment]
@camillo777 here is the hack :p https://github.com/k0shk0sh/FastHub/blob/b17ddc9646288f410f4455ae0afac7b2971e446f/app/src/main/assets/md/intercept-hash.js
