### ISSUE TITLE
Programming language badges not changes color between different themes

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#308]
**App Version: 1.8.1
OS Version: 24
Model: samsung-SM-G950F**
I observed that programming language badges not changes their color between light and dark mode. This is ok, but if in the light mode these color are perfect, in dark mode they're too saturated<br>
![20170414_112620](https://cloud.githubusercontent.com/assets/23010471/25039723/6b4f0158-2105-11e7-8d07-2b7accd1a258.jpg)

**Comment by k0shk0sh** [comment]
@AndreaCioccarelli this behaviour changed now, as we use same colors as in github. so the same color will remain there either in dark or light theme.
