### ISSUE TITLE
Android N+ App Shortcuts

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#312]
**App Version: 1.8.1**

**OS Version: 7.1.1**

**Model: Samsung-SM-G800F**

You could add launcher shortcuts in Android 7.1+ in order for users to be able to have a quick access to things like:
- The user's profile
- The most frequently visited repo
- The app settings
- The app's notifications

**Comment by k0shk0sh** [comment]
#260 

I'll try and do that soon. Thanks
