### ISSUE TITLE
Repository dialog buttons have the same behaviour but different labels

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#317]
**App Version: 1.8.1
OS Version: 24
Model: samsung-SM-G950F**

FastHub's repository Activity haves an information  shortcut that will show a dialog containing repository info. The dialog haves 2 buttons, "OK" and "Cancel", but they both dismiss the dialog
You should remove the "Cancel" button to have an unified UX

![screener_20170415 09 28 44](https://cloud.githubusercontent.com/assets/23010471/25061858/8f30bf84-21bf-11e7-968f-61349b51950e.png)

**Comment by k0shk0sh** [comment]
Nice screen :p using screener?

**Comment by AndreaCioccarelli** [comment]
Yep ;)
