### ISSUE TITLE
Drawer's organizations space isn't proportioned with needed space

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#318]
**App Version: 1.8.1
OS Version: 24
Model: samsung-SM-G950F**

Drawer organizations space isn't proportional to real views total height.
Also, organizations TextView should be aligned at left instead of be aligned under Spinner

![screener_20170415 09 29 22](https://cloud.githubusercontent.com/assets/23010471/25061924/4f6f55c0-21c1-11e7-8b5c-0d5fb896bf9f.png)

**Comment by k0shk0sh** [comment]
This  [commit](https://github.com/k0shk0sh/FastHub/commit/00ebcb3f92a88e23bc0ec432c72532676052aab6) should close this
