### ISSUE TITLE
[Suggestion] Have FastHub as a default pinned repo instead of in side nav

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#322]
I feel like the side nav could provide quick access to various things, but right now it's somewhat cluttered at the top with the FastHub repo link + donations/ads. A possible way to clean it up would be to have FastHub as a default pinned app (which could be part of the onboarding process) instead.

I do also think that enable ads should live in settings, and that the donations should be by Settings/Logout.

EDIT: it might be nice to separate out "About" from settings into an item in the side nav too, similar to Phonograph.

**Comment by dikiaap** [comment]
Sounds good to me. Also the feeds of the public gists should be removed. I don't use it anyway, might be everyone.

**Comment by JediBurrell** [comment]
This issue has been appealed in b041269.
