### ISSUE TITLE
[Feature request] Ability to see/make PR file comments

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#323]
- FastHub Version: 1.8.1
 - Android Version: 7.1.1
 - Phone Model: OnePlus One

Currently, it's impossible to see review comments on files in PRs. You can [look at this PR](https://github.com/arkon/uoft-enrolment-charts/pull/10) as an example.

**Comment by eygraber** [comment]
+1

**Comment by k0shk0sh** [comment]
This has been implemented and shall out today however replying isn't currently available also creating, viewing will be there

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/9p6UcC0.png)

**Comment by eygraber** [comment]
@k0shk0sh does this story cover adding an initial comment on a line, or should a separate issue be created for that?

**Comment by k0shk0sh** [comment]
@eygraber thanks for reminding me of this lol, there is an open issue for what you asked for :) hopefully soon

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
@k0shk0sh which issue is that? The ability to create review/commit comments on code is basically the only thing keeping me from using FastHub as my daily driver.

**Comment by k0shk0sh** [comment]
@eygraber this related to displaying pr reviews created from browser plus interacting with them, the possibility to add PR changes isn't available yet, you could add commit comments but not yet on line commments as I couldn't find how to do that with the possibility of calling each file separately and get it's line number and stuff like that which going to be complicated, however its on my list of todo and hopefully start this week. I got the overall idea and hopefully it works 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
