### ISSUE TITLE
Got like 5 notifications in 1 minute

### ISSUE THREAD

**Issue by be54002** [k0shk0sh/FastHub#324]

**Comment by k0shk0sh** [comment]
What was the notification :D . i'm testing push notifications lol
It wasn't there in the app & just included it? 

You got like hello world and stuff or what?

**Comment by k0shk0sh** [comment]
@be54002 Could you please elaborate?

**Comment by k0shk0sh** [comment]
#325

**Comment by be54002** [comment]
Sorry for the delay! I thought I was leaving an anonymous report inside the app, not an actual issue on GitHub. I didn't realize until I logged in on a browser. Basically I got like 4 or 5 "Hello worlds" and thought it was an error, but now that you said you were testing notifications, that must have been what caused them.
