### ISSUE TITLE
notification test's are annoying

### ISSUE THREAD

**Issue by bumbeishvili** [k0shk0sh/FastHub#325]
I am keep getting push notifications from the app

first was 'test' notification which appeared 3 times

Now I got 'first notification' 

can you test it in testing environment, I don't know what is the point to annoy users, which have already installed this app ....

ps. thanks for this awesome app

**Comment by k0shk0sh** [comment]
I'm abit confused about this to be honest :D 

The notification feature I just included in the app & was testing it. 

I got no freaking idea how this does even happen?

the whole feature it isn't there in the app and now i'm confused 

Sorry for the inconvenience tho.

**Comment by bumbeishvili** [comment]
No problem
