### ISSUE TITLE
[Feature request] Group notifications by repo

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#328]
- FastHub Version: 1.8.1
 - Android Version: 7.1.1
 - Phone Model: OnePlus One

Similar to GitHub's web interface, it'd be nice if notifications (in the actual activity at least -- the notifications might be more challenging) were grouped by repo, and offered the ability to quickly mark a single notification or a an entire repo's worth as read without actually tapping into it.

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/VttIPi2.png)


![](http://i.imgur.com/WCtKlHi.png)

**Comment by k0shk0sh** [comment]
Please ignore

**Comment by k0shk0sh** [comment]
![notification](http://i.imgur.com/wOl6bzN.png)
