### ISSUE TITLE
Make list of repository in user profile more clean

### ISSUE THREAD

**Issue by dikiaap** [k0shk0sh/FastHub#329]
**App Version: 1.8.1**

**OS Version: 22**

**Model: Evercoss-EVERCOSS A65**

Like GitHub does. Only create and forking repository what we do, instead of including all organization repository.

**Comment by dikiaap** [comment]
Hey @k0shk0sh.

Could you bringing back this on filter?<br>
I mean, I can't save the current filter, and make me repeat, repeat some filter again.<br>
Or just made filter as owner for default.

**Comment by k0shk0sh** [comment]
@dikiaap hey, I guess it went away when Adi did the filtering I'll try and make it work in today's release. Thanks

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dikiaap** [comment]
Is this already fixed?

**Comment by k0shk0sh** [comment]
@dikiaap totally forgot about it. 😰

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
