### ISSUE TITLE
Change followers sorting order

### ISSUE THREAD

**Issue by aviaryan** [k0shk0sh/FastHub#331]
**App Version: 1.8.1**

**OS Version: 23**

**Model: Xiaomi-Redmi Note 4**

Right now followers are being shown in the order of oldest first. I think newest first order is more advantageous as it shows someone 's newest follows right at the top. 
Btw, best would be if we can change the order as needed.

**Comment by k0shk0sh** [comment]
Please have a look at this #75 currently there is no way we could do that.
