### ISSUE TITLE
The app's Back button always sends to <code>

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#332]
**App Version: 1.9.0**

**OS Version: 25**

**Model: OnePlus-A0001**
-------
Pressing the app's back button when viewing an Issue or PR sends to Readme under Code tab instead of the Issues/PR lists.

**Comment by k0shk0sh** [comment]
Oops, if the issue/pr is clicked from outside app & clicked back button and not home button should bring you to the issue tab, but home up it doesn't. I guess I missed that out 😞

**Comment by Younes-L** [comment]
@k0shk0sh thanks for the quick reaction, i noticed that the loading still happens after exiting an issue/PR, is that intentional ?

**Comment by k0shk0sh** [comment]
@Younes-L couldn't get you, could you elaborate more?

**Comment by Younes-L** [comment]
@k0shk0sh got it, thanks for clarifying :-)

**Comment by k0shk0sh** [comment]
@Younes-L np. 191 is uploaded to playstore which has this issue fix, soon you'll be receiving an update. 
Thanks

**Comment by Younes-L** [comment]
@k0shk0sh when i said "still" i meant after i installed the 1.9.1 update (got it from the releases tab) , the system back button is here to be used to it's all good :)

**Comment by Younes-L** [comment]
@k0shk0sh the app has disappeared from the Play Store, at least from my end. Even with a Google search or Play Store search.

**Comment by Rainer-Lang** [comment]
Same here. No FastHub on Google Play.

**Comment by k0shk0sh** [comment]
Well I just wokeup and have received this
![](http://i.imgur.com/u5S4wm9.png)

Which is so laaame

**Comment by Younes-L** [comment]
New package name and new name ???
This is ridiculous... Sad news :(

**Comment by k0shk0sh** [comment]
@Younes-L I have submitted appeal and waiting for a response. I hope it doesn't reach that point.

**Comment by alamo18** [comment]
wait wtf how tf is this impersonation

**Comment by k0shk0sh** [comment]
@alamo18 Idk really, it's ridiculous i know, but can't do anything unless they replied me with some valid reasons, **for GitHub** name is being used by multiple apps, there are even names with GitHub in their title like it was GitHub app, their logo was exactly the same as GitHub's logo, but yet remain there. just gotta wait I guess :'(

**Comment by alamo18** [comment]
were they so autistic from the start?

**Comment by alamo18** [comment]
btw I LOVE FASTHUBBBBB

its like the best...btw, i live in Singapore (causeway), right next to you

**Comment by k0shk0sh** [comment]
@alamo18 probably the ban came from an automated system rather than humans, that's lame but I can't really nag about it much instead i'm working on some improvements here and there and waiting for the appeal reply 😢  .

I have few friends from Singapore where we used to play COD3 back then.
