### ISSUE TITLE
[Feature Request]Pinned Tab to have a drop down menu for easier access.

### ISSUE THREAD

**Issue by TheClashster** [k0shk0sh/FastHub#336]
**App Version: 1.9.0**

**OS Version: 25**

**Model: Motorola-MotoG3**

This would help a user quickly access their pinned repositories instead of opening the pinned tab every time, in case the user has a lot of pinned repositories, a __view more__  option at the end could open the pinned tab. Additionally, a __'My Repositories'__  tab like the one in GitHub could solve this issue too because currently the see has to navigate to his repositories via their profile or through the pinned tab if they have pinned them. Thanks a lot.

**Comment by k0shk0sh** [comment]
**view more** option like where to place this?

**Comment by TheClashster** [comment]
When you implement the pinned tab drop down menu, if a user has a lot of repositories pinned say like 15-20, they'll have to scroll a lot and it'll be really weird for them, so say after 5 repositories in the drop down menu, if the user has more repositories pinned, a small view more option to open the pinned tab. This would help those who interact with a small number of repos actively to access those repos quickly.

**Comment by k0shk0sh** [comment]
I got you, however I can't promise to be very soon, as I have more issues that has been hanged for awhile.
 I see that you still using 1.9.0, could you update from the releases page to 1.9.1? as FastHub has been suspended from the play store and I've applied for an appeal hopping to bring it back with its same package and name.

**Comment by TheClashster** [comment]
No issues there man, I understand there are more pressing issues to deal with first. And yeah, I'll update it right now, thanks!

**Comment by ciscorucinski** [comment]
I have been thinking of a similar improvement to Pinned Repos.

Instead of having a menu item that leads to a list of Pinned Repos, how about a dynamic menu that posts your top 4 or 5 Pinned Repos you visit the most. Of there are more Pinned Repos then that, then you can provide a view more  mechanisms to expand the menu to fit all....Or take the user to the lost that is currently displayed.

The Navigation Menu is not user centered at all. Some of the things should be removed or moved down or hidden a little. My Pinned Repos should not be hidden.... especially my top Pinned Repos.

**Comment by TheClashster** [comment]
@ciscorucinski yep, that's what I meant. As of now, you need to navigate to the whole list to find your pinned repositories. This stands in contrast since the point of pinned repositories was to quickly access those repos which you interact frequently with. A drop down with 4-5 items would suffice I guess. And you could always expand to see the whole list of pinned repositories like how it is currently.

**Comment by k0shk0sh** [comment]
@TheClashster @ciscorucinski  isn't the `Pinned` shortcut is more suitable in this case? 

In case you didn't know, this feature has been implemented awhile ago, like two months or more.

You could then create the shortcut in your launcher and access the pinned items with a click even outside of FastHub?

**Comment by ciscorucinski** [comment]
Pinned shortcut. The new Android feature where you hold an app icon and a list of actions are displayed and you can jump directly into that part of the app?

In that case, yes that is great. However, my phone will not be upgraded to that version of Android that supports that feature (Note 4).

The list of pinned repositories in the Navigation View is something that all Android version will be able to use

**Comment by k0shk0sh** [comment]
@ciscorucinski that's true, well, within the new release you'll be able to see 10 pinned items under your account (since now we will support multi accounts) which these 10 will be ordered based on the number of repos you entered as you mentioned in your previous comment. however this will behave as below: 


1- Open drawer
2- Click on dropdown button (right beside your name) 
3- List of pinned repos will appear under your multi accounts (if any).

will update with a pic after this comment.

**Comment by yakov116** [comment]
@ciscorucinski no no. I think you misunderstood him. We're talking about in the nav view.

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/4aPfzh3.png)


_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ciscorucinski** [comment]
@yakov116 no I am talking about what is shown I. The picture above. We are talking about the same thing.

**Comment by yakov116** [comment]
@ciscorucinski good. Glad we're on the same ~~page~~  Menu. LOL

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh will we be able to pin org projects?

For example https://github.com/PureNexusProject

**Comment by k0shk0sh** [comment]
Alright, this will be in next release. (y)

**Comment by ciscorucinski** [comment]
It would be better if we didn't have to click on the drop down by your name. 

 - Open drawer
 - See list of 10 pinned repos

**Comment by k0shk0sh** [comment]
Nope, that won't be possible, I'm with you with that, however, the drawer menu is already occupied by other items, adding more items to it, will just be bad.

**Comment by k0shk0sh** [comment]
@yakov116 I don't care much about its coming from Enterprise or Orgs or from mars, as long as its a repo then you can definitely pin it :)

**Comment by yakov116** [comment]
@k0shk0sh its not a repo. Its a project that contains many repo's Github took away that functionality (of following a project) about 2 years ago. This would be a nice substitute.

**Comment by TheClashster** [comment]
@k0shk0sh this is exactly what I was talking about! Great work!

**Comment by yakov116** [comment]
@TheClashster Enjoy! (and donate 😉 )
