### ISSUE TITLE
The app keep crashing

### ISSUE THREAD

**Issue by felixfong227** [k0shk0sh/FastHub#337]
When trying to open the app from home screen
![image](https://cloud.githubusercontent.com/assets/13918481/25133459/50110c2e-247f-11e7-8aba-f1dc29e61f53.png)

When trying open the app from the notification bar
![image](https://cloud.githubusercontent.com/assets/13918481/25133500/69b70886-247f-11e7-8866-aff5d2d01328.png)

---

 - FastHub Version: 1.8.1
 - Android Version: 6.0.1
 - Phone Model: Samsung C5

**Comment by k0shk0sh** [comment]
Hello Felix, could you update to 1.9.1 from the releases page and get back to on this? or from here 
https://github.com/k0shk0sh/FastHub/releases/tag/1.9.1

**Comment by k0shk0sh** [comment]
Due to no response, this issue will be closed. Please do open it if the issue still persist in 1.9.x
