### ISSUE TITLE
The App translate

### ISSUE THREAD

**Issue by naloder** [k0shk0sh/FastHub#340]
**App Version: 1.9.1**

**OS Version: 22**

**Model: Meizu-M3s**

I want to help you to translate this app to chinese,then our chinese developer can use it more convenient.

**Comment by arkon** [comment]
#335 seemed like a good start, but I'm not sure why it was closed.

**Comment by kutsan** [comment]
Hello! Thanks for supporting us. You can start from [here](https://github.com/k0shk0sh/FastHub/blob/master/CONTRIBUTE.md#contribute-translations), if you want to translate to your local language.

As @arkon said, @Devifish already translated but he/she has closed the issue and pull request with no reason. At least we don't know why. So, you can check that translation (whether it is correct or not) or copy and submit newly reviewed one. Thanks again!

**Comment by k0shk0sh** [comment]
#343 has been merged, you could have a look at it.

**Comment by naloder** [comment]
I'm use github the first,any things i don't know,I want to send the xml from my email,I hope you understand,I will try to learn to use it😓
