### ISSUE TITLE
Can't find app on play store

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#341]
**App Version: 1.8.1**

**OS Version: 25**

**Model: HTC-Nexus 9**

I would upload a pick if it would work...

**Comment by k0shk0sh** [comment]
Please read the top header in readme file, to update your app currently please do it from the releases section. __1.9.1__ is the latest version.

**Comment by AdrianVovk** [comment]
Just curious. Why was it suspended?

**Comment by k0shk0sh** [comment]
@AdrianVovk https://www.reddit.com/r/androiddev/comments/662hsw/fasthub_for_github_got_suspended_for_violating/?utm_content=title&utm_medium=hot&utm_source=reddit&utm_name=androiddev

**Comment by camillo777** [comment]
It's weird because I try to go to release page but fast hub opens and clicking on the link does send me to the readme again...

**Comment by k0shk0sh** [comment]
@camillo777 I'm aware of that, release page is two tabs away, I'll try and fix that soon

**Comment by felixfong227** [comment]
So will you try to republish a new app with a different name @k0shk0sh ?

**Comment by k0shk0sh** [comment]
@felixfong227 so far nope, still waiting for my appeal. This will be my last option, I believe I didn't break any rules so I'm going to stick to my point until proven wrong

**Comment by Younes-L** [comment]
I just got notified, didn't knew the app could do that ^^

Well great news, glad you had this sorted out 👍

**Comment by k0shk0sh** [comment]
@Younes-L neither I lol, I just included it to the last version I released to playstore, however while testing before releasing I have been informed that people received my push notifications without me including the FCM into my app, I guess it was included into the ads dependency I assume. 

Thanks for ur support.

**Comment by k0shk0sh** [comment]
@Younes-L I'm wondering if the full message was actually received. :P

**Comment by Younes-L** [comment]
@k0shk0sh here's a screenshot of the notification
![](http://i.imgur.com/sYY9YMI.png)

Also thanks for clarifying the notification thing x) I've seen people report notification but I hadn't received any until now.

**Comment by wxl** [comment]
Might want to go F-Droid.

**Comment by k0shk0sh** [comment]
@wxl  @thermatk  working hard on it, besides that, do expect that you'll find it later today in playstore as my appeal has been approved and just wrapping things for new release.

**Comment by wxl** [comment]
@k0shk0sh will this include the fix for #259?if so, can't wait!

**Comment by k0shk0sh** [comment]
@wxl you mean this 😝
![FastHub Notifications](http://i.imgur.com/SfHe7Yu.png)

**Comment by wxl** [comment]
@k0shk0sh Well i mean being able to subscribe to issues. I think I find the commit that contains the fix but I can't find the sha to refer to it. Another bug? 🐛

**Comment by k0shk0sh** [comment]
@wxl well, there is no way for me to do currently, the API doesn't provide such call, so even to unsubscribe from an issue, you have to do it from notifications. the API missing loads of stuff & I don't really know why :D

**Comment by arkon** [comment]
@k0shk0sh You might be able to just do it yourself by POSTing to `https://github.com/notifications/thread` with the appropriate form parameters.

**Comment by k0shk0sh** [comment]
@arkon yup, i'm looking at this right now lol :D

**Comment by wxl** [comment]
Maybe we should reopen the issue then since it isn't completed after all?

**Comment by k0shk0sh** [comment]
@wxl @arkon  the problem with that, as we can see from the form below, is that how we determine the issue ID??

```
<form accept-charset="UTF-8" action="/notifications/thread" class="thread-subscribe-form" data-remote="true" method="post">
    <div style="margin:0;padding:0;display:inline">
        <input name="utf8" type="hidden" value="✓">
        <input name="authenticity_token" type="hidden" value="token">
    </div>
    <input type="hidden" name="repository_id" value="82405191">
    <input type="hidden" name="thread_id" value="223118222">
    <input type="hidden" name="thread_class" value="Issue">
    <input type="hidden" name="id" value="unsubscribe">
    <button class="btn btn-sm" type="submit" data-disable-with="">
        <svg aria-hidden="true" class="octicon octicon-mute" height="16" version="1.1" viewBox="0 0 16 16" width="16">
            <path></path>
        </svg>
        Unsubscribe
    </button>
</form>

```

**Comment by arkon** [comment]
Well the `repository_id` is in the response of <https://api.github.com/repos/k0shk0sh/FastHub>, and the `thread_id` is in the response of <https://api.github.com/repos/k0shk0sh/FastHub/issues/341>.

The only other things you'd need are `utf8` (`✓`), an `authenticity_token`, `thread_class` (`"Issue"`), and an `id` (`"mute"` or `"subscribe"`).

**Comment by k0shk0sh** [comment]
@arkon owh yea, owh yea :D .. thanks man :D ..

**Comment by k0shk0sh** [comment]
@arkon & @wxl this wont work :D, tried with even postman 

> What‽
Your browser did something unexpected. Please contact us if the problem persists.

**Comment by camillo777** [comment]
@k0shk0sh what did you use for notifications? Firebase? They work pretty well.

**Comment by k0shk0sh** [comment]
@camillo777 yup :p . I guess I should close this issue now :D
