### ISSUE TITLE
Not existing repository can generate an empty activity

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#342]
- FastHub Version: 1.9.1
 - Android Version: Nougat 7.0
 - Phone Model: SM-G925F

If FastHub gets a broken URL it can generate an activity that cannot be used from the user like this picture

![20170419_085338](https://cloud.githubusercontent.com/assets/23010471/25167025/279411ba-24de-11e7-85c5-73c891837267.jpg)

**Comment by k0shk0sh** [comment]
I love how you demonstrate these issues :D.
Thanks for your continuous reports :)

**Comment by k0shk0sh** [comment]
This issue is fixed in 1.9.4 and forgot to close it via a commit.
