### ISSUE TITLE
Tapping grouped notification goes to a specific item

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#344]
**App Version: 1.8.1**

**OS Version: 25**

**Model: asus-Nexus 7**

Tapping a grouped notification in Android N goes to one of the issues/PRs instead of going to the notification view as expected.

**Comment by k0shk0sh** [comment]
1.8.1 ? we are in 1.9.1 @arkon , please update from the release page :D then get to me about this.

**Comment by arkon** [comment]
Whoops, forgot to update. I'll reopen this if needed.

**Comment by arkon** [comment]
Still an issue in 1.9.1.

**Comment by k0shk0sh** [comment]
@arkon hello arkon, I cant really know what are you talking about exactly,
 [Video](https://drive.google.com/file/d/0BxbjAF1sbwjaYVh3ay10ZTR1OHc/view?usp=drivesdk)

**Comment by arkon** [comment]
@k0shk0sh I don't have a screenshot/video right now, but I mean tapping something like what's on the left of this image:

![](http://cdn01.androidauthority.net/wp-content/uploads/2016/03/Hangouts-8-Android-N-notifications-1-840x750.jpg)

Instead of going to an overview of all the notifications, it goes directly to (presumably) the first item.

**Comment by k0shk0sh** [comment]
Opps, i'm not so sure, but i'll test this out later.

**Comment by yakov116** [comment]
@arkon Test 1

**Comment by arkon** [comment]
For future reference: more testing of this showed that it goes directly to the first item in the grouped notification when tapped, which is just how N handles it.

**Comment by k0shk0sh** [comment]
I finally got this :D & fixed it :) will close it with my next commit.

**Comment by k0shk0sh** [comment]
this fixed in 04244d50cba1b6335faeca51a4a6769a2fe967f6
