### ISSUE TITLE
Markdown quotes in black mode are too dark

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#345]
- FastHub Version: 1.9.1
 - Android Version: 7.0
 - Phone Model: SM-G925F

Quotes not change color between dark and light mode

![screener_20170420 12 33 09](https://cloud.githubusercontent.com/assets/23010471/25226787/726a60b6-25c6-11e7-81bc-965d9fee760b.png)

**Comment by Younes-L** [comment]
It looks okay to me :)

**Comment by k0shk0sh** [comment]
What about this?

![](http://i.imgur.com/iftR15J.png)

**Comment by arkon** [comment]
You should try this: https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor

**Comment by k0shk0sh** [comment]
@arkon not available in my country lol

**Comment by arkon** [comment]
@k0shk0sh http://www.apkmirror.com/apk/google-inc/accessibility-scanner/accessibility-scanner-1-1-2-release/accessibility-scanner-1-1-2-android-apk-download/
