### ISSUE TITLE
BaseAligned dialog appear on top

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#346]
- FastHub Version: 1.9.1
 - Android Version: 7.0
 - Phone Model: SM-G925F

In the Issue reply activity you can input some text with your keyboard, if you press the exit (top left corner) button, the keyboard will be dismissed but the dialog will be generated at the activity center, not at the bottom, as shown below. The dialog should be generated at the page bottom (after the keyboard.Dismiss();)

![screener_20170420 12 44 50](https://cloud.githubusercontent.com/assets/23010471/25227042/6c68c742-25c7-11e7-80fd-db83422859ce.png)

**Comment by kutsan** [comment]
Thanks for reporting.

**Comment by k0shk0sh** [comment]
I'm still seeing this 😭
