### ISSUE TITLE
Settings missing in drawer

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#349]
**App Version: 1.9.1**

**OS Version: 25**

**Model: Google-Pixel**

If I'm not on the home screen the settings don't show in the drawer. 

It would be nice if it did, so I didn't have to lose my place if I wanted to change a setting.

**Comment by k0shk0sh** [comment]
That's a bit tricky tho, I don't want to recreate all the activities in the backstack once you change something, this will require new dependency to listen to events, or we could use rxjava as an eventbus, it's a bit tricky, I'll think about it but there is an issue like this which I have closed by just putting logout only :p
