### ISSUE TITLE
Where can I download?

### ISSUE THREAD

**Issue by DarkByte2015** [k0shk0sh/FastHub#350]
I used your application and I really liked it, but I accidentally deleted it. And now I do not find it on Google Play and the link in the repository does not work. What was it removed? Why? Please return it to Google Play!

**Comment by kutsan** [comment]
It has been suspended from the Play Store due copyright reasons but it will be available in a few days. You can install the APK from https://github.com/k0shk0sh/FastHub/releases for now.
