### ISSUE TITLE
Find file in repo

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#352]
**App Version: 1.9.1**

**OS Version: 25**

**Model: Google-Pixel**

GitHub's website allows you to search for a file in a repo, showing a list of files that match your query. 

Any chance of getting something like that?

**Comment by alamo18** [comment]
more of a feature request instead of bug...

**Comment by aadithyabk** [comment]
Can I pick this issue? 

Also, I see an api for finding the contents in a file but I don't see one for finding a file in the repository itself.  Am I missing something?
https://developer.github.com/v3/search/

**Comment by arkon** [comment]
I believe you'd need to actually [go through the tree](https://developer.github.com/v3/git/trees/) yourself.

**Comment by aadithyabk** [comment]
I was just about to post this. I found the same thing on website but it seems to be different from the usual api.github.com and I didn't find any documentation about it either

**Comment by k0shk0sh** [comment]
What about using the same search code screen in search activity? And strict it to a repo? https://developer.github.com/v3/search/#search-code

**Comment by aadithyabk** [comment]
Wouldn't that give us files that contain the search string and not the file names that contain the search string?

**Comment by k0shk0sh** [comment]
@aadithyabk sure you can, I guess it will be more like copy paste and just modifying the search query. Let me know if you wanna do it, also you may join our slack channel.

**Comment by k0shk0sh** [comment]
@aadithyabk
> in Qualifies which fields are searched. With this qualifier you can restrict the search to the file contents (file), the file path (path), or both.


> filename Matches files by a substring of the filename.

**Comment by aadithyabk** [comment]
Aha! Thats what I missing. Thanks and yes, I'll do it

**Comment by k0shk0sh** [comment]
@aadithyabk nice, hit me up in slack if you needed my help.
