### ISSUE TITLE
Notification looping

### ISSUE THREAD

**Issue by Maxr1998** [k0shk0sh/FastHub#353]
**App Version: 1.9.1**

**OS Version: 25**

**Model: Huawei-Nexus 6P**

On the latest version, FastHub notifications tend to loop dismissal and creation, even if they were already clicked/dismissed manually.
This causes lag on the phone and a huge overnight battery drain on my Android Wear watch.

Here's a YouTube video showing the issue:
[link](https://youtu.be/UN50rSJLBGM)

**Comment by k0shk0sh** [comment]
@thermatk  😓, could you check on this

**Comment by thermatk** [comment]
Please share logcat

**Comment by thermatk** [comment]
And also what's the notification interval, whether you changed it and if it ever was set under 15 minutes is also relevant. Finally, could you go to settings and re-set the interval to some value now(30 minutes?), if 1.9.1 is not the last version you had installed and we should rule out a migration bug

**Comment by Maxr1998** [comment]
Here's the [logcat](https://github.com/k0shk0sh/FastHub/files/946798/fasthub.txt).
I didn't have any notification interval selected in settings, and I didn't change it before I think.
![Screenshot](https://cloud.githubusercontent.com/assets/5903699/25274344/ecf05aa6-268f-11e7-9949-6db9fa617e58.png)
I set the interval to 30 minutes now. Please send me a reply that  cab test whether it works now.

**Comment by thermatk** [comment]
here is a reply

**Comment by k0shk0sh** [comment]
@Maxr1998 owh damn, no interval means zero lol. I guess I know what is the cause and it has been fixed locally, so you gotta wait until next version, however setting the interval manually to any value should disable the bug

**Comment by thermatk** [comment]
We'll probably see in 25-40 minutes =D

**Comment by thermatk** [comment]
@k0shk0sh why would a pref disappear?

**Comment by k0shk0sh** [comment]
@thermatk not quite sure tbh, it might be due to an old commit to change some English phrases that caused that

**Comment by Maxr1998** [comment]
@k0shk0sh oops! 😄
Well, that makes sense of course, after having set the interval it's fixed now.
Awesome work on the app btw! I hope it quickly gets restored to the Play Store, your app definitely is the best GitHub client out there. ☺️

**Comment by k0shk0sh** [comment]
@Maxr1998 it has gotten restored, however I need to update my Icon before releasing new update & i'm still waiting for the Icon Designer. thanks for your support 👍
