### ISSUE TITLE
Adaptative background for PNG images

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#357]
**App Version: 1.9.1**

**OS Version: 25**

**Model: OnePlus-A0001**

Using dark theme, this is hard to read
![](http://i.imgur.com/cPLFlcF.png)

Is there a possibility to switch from dark grey to white or light grey background depending on the PNG displayed ?

Here's how it looks on the mobile GitHub website
![](http://i.imgur.com/0wN3UK1.png)

**Comment by k0shk0sh** [comment]
well, that's abit impossible lol, since the image is loaded in background :D, the settings will come become in every screen so you could switch themes more easily, tomorrow i'll be publishing new update to play store with new icon for my appeal.

**Comment by Younes-L** [comment]
@k0shk0sh sorry if it sounded confusing, but I'm only talking about the PNG's background, not the whole app's theme, if that makes sense.

**Comment by k0shk0sh** [comment]
I kinda got you the first time :p, it just that I don't want to introduce more complexity for that, because if I started to allow modification of webview then i'll eventually end up allowing more webview customizations :D . I hope you can understand that.
