### ISSUE TITLE
Pull requests don't show reviews

### ISSUE THREAD

**Issue by silverAndroid** [k0shk0sh/FastHub#36]
Any reviews posted on pull requests, don't appear, unsure if this is an API limit or just a missing feature

**Comment by k0shk0sh** [comment]
reviews api are still in preview & I'm afraid that this might break things up if ever github thought of changing it. i will try and make it but should mention that it might break at anytime

**Comment by eygraber** [comment]
This would be awesome. Even if you had a switch to disable it if it breaks.

**Comment by k0shk0sh** [comment]
@eygraber I'll see about it within this week,  if I find space(time) for it, I'll and make it before coming Sunday release.

**Comment by eygraber** [comment]
@k0shk0sh any idea of when this might get in? It's the number one thing I use GitHub on mobile for.

**Comment by k0shk0sh** [comment]
Hopefully soon, maybe tomorrow :p I'm not sure tho.

**Comment by k0shk0sh** [comment]
Alright guys, you got it :p. it'll be up today in 1.8.0. 

Thanks
