### ISSUE TITLE
Possibly consider pulling out GitHub API stuff into a separate package?

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#360]
As time goes on, it seems like there's a lot of work being put into developing functionality for various GitHub features that aren't actually available as part of the API. I think it'd be nice to actually pull out all the code that handles interfacing with GitHub (both via the official API and the unofficial stuff) into a separate package, possibly published to Maven. It'd be great for FOSS, and might even be better for other people to develop things without necessarily working in the context of the app.

**Comment by k0shk0sh** [comment]
The app isn't designed that way, as these classes are used for offline usage as well, if one, wants to use them, then they should be pulled out from FastHub and remove all the database usage.
