### ISSUE TITLE
Cant see anything in commits

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#362]
**App Version: 1.9.4**

**OS Version: 25**

**Model: HTC-Nexus 9**

It shows blank
![](http://i.imgur.com/bZJ8AsI.png)

**Comment by k0shk0sh** [comment]
Link to commit?

**Comment by yakov116** [comment]
Ha ha the share is not wprking

**Comment by yakov116** [comment]
I looked in many repo 's not one commit is showing

**Comment by k0shk0sh** [comment]
@yakov116 owh damn, yup it doesn't

**Comment by k0shk0sh** [comment]
@yakov116 I just pushed update to the playstore fixing this, you'll get an update maybe in less than an hour. 

Thanks for your contribution.
