### ISSUE TITLE
Not taking back when clicking issue

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#363]
**App Version: 1.9.4**

**OS Version: 25**

**Model: HTC-Nexus 9**

Before this last update when you click issue it took you back. Now you have to click the back icon.

**Comment by k0shk0sh** [comment]
I really couldn't get you, if you click an issue outside of FastHub, when you press back button ( phone back button ) it will navigate you to the stack, however clicking home up anytime should bring you back to stack as well. I just tested this out and it still behaves as before.

**Comment by yakov116** [comment]
No no

Clicking the icon in the app for issues when you clicked it a second time it took you out of issues

**Comment by k0shk0sh** [comment]
@yakov116 I'm lost lol.  Can you like elaborate more, sorry tho I couldn't get you.

**Comment by yakov116** [comment]
What should happen when I click the issue icon when I am already in issues

**Comment by arkon** [comment]
Could you provide a screenshot of which screen you're talking about, and where you're expecting it to go?

**Comment by yakov116** [comment]
I dont have my tablet  with me but..

> What should happen when I click the issue icon when I am already in issues

**Comment by k0shk0sh** [comment]
@yakov116 which issue icon? There is no issue icon in issue view? That's why I cant really understand you 😅

**Comment by yakov116** [comment]
On the left side the circle with the "!" in the middle

**Comment by arkon** [comment]
@yakov116 Do you mean when looking at the list of issues?

**Comment by yakov116** [comment]
yes

**Comment by arkon** [comment]
It shouldn't do anything, as far as I'm aware. What did you expect it to do?

**Comment by yakov116** [comment]
go back

**Comment by k0shk0sh** [comment]
@arkon could you please snap a screenshot to me, I'm lost tbh 🙄

**Comment by arkon** [comment]
@yakov116 Go back to what exactly though?

**Comment by arkon** [comment]
@k0shk0sh I'm assuming they mean the issues icon in the (side?) navigation bar here:

![2017-04-23 15 45 12](https://cloud.githubusercontent.com/assets/4098258/25314895/61c31b26-281a-11e7-9906-f7ee82a8db8e.png)

**Comment by yakov116** [comment]
yes

**Comment by k0shk0sh** [comment]
Owwwh, finally I got you, its the issues list tab.

**Comment by yakov116** [comment]
ok are we good?

**Comment by arkon** [comment]
I'm confused as to what you'd expect tapping the issues icon to go to though. Wouldn't it make sense to just stay in the issues tab?

**Comment by yakov116** [comment]
no it should go back

**Comment by arkon** [comment]
@yakov116 You still haven't said go back to _what_. Do you mean just whatever you were looking at before? If so, the Android navigation bar's back button should be responsible for that, not the tab icon. If it did that before, that would have been considered a bug.

**Comment by yakov116** [comment]
it should take you back to the repo you were looking at

**Comment by k0shk0sh** [comment]
@yakov116 that tab to navigate to Issues, the below tab to navigate to PullRequests & first tab to navigate to ReadMe. clicking the (Arrow back, Home button) is what should bring you back to whatever you were at.

**Comment by yakov116** [comment]
ok
Why would you not want it to take you back?
Its highlighted unhighlight should take you back

**Comment by arkon** [comment]
Tabs don't function like that anywhere though. That's like if I clicked the active tab in Chrome and it took me to another tab?

**Comment by k0shk0sh** [comment]
Take you back to what? are you looking at original repo or a forked repo? if you are looking at a forked repo, then the issue tab won't do anything but rather show a message says that the repo doesn't have issues enabled. and as @arkon said,  I can't really figure out the argument in here.

**Comment by yakov116** [comment]
Ok 
I was looking at the issues like this..
You cant fit all the options on one line (ReadMe commit etc...) so you made a new icon for the issue.
In other words i was looking at as a "more" button. so unclicking would show "less"

**Comment by k0shk0sh** [comment]
Owwh, now I got you.
this feature was in FastHub from 1.0.0, so i'm not sure how did you seem them before, if you are using tablet, then will appear in the screen shot @arkon showed, if you are using phone, they will appear in the bottom.

**Comment by yakov116** [comment]
I have a tablet.

At least we endoff on the same page :)
