### ISSUE TITLE
controls silently fail on notifications panel

### ISSUE THREAD

**Issue by wxl** [k0shk0sh/FastHub#368]
**App Version: 1.9.4**

**OS Version: 24**

**Model: samsung-SM-G930V**

Tapping the mark read buttons, the unsubscribe buttons or the repo name all silently fail. You can hold to get tool tips so they're not dysfunctional. Also, no action is updated as even restarting the app shows no changes.

**Comment by k0shk0sh** [comment]
fail like how? they both will be done in background, while showing a notification progress in the notification panel, you might not really seem them as they disappear fast depending on your internet speed. so I'm abit lost here on what is the issue?

**Comment by wxl** [comment]
Perhaps I'm wrong. Different behavior than previously. Mark read would remove from list before. 

Subscribe/unsubscribe seems to do something but the but doesn't change appropriately.

**Comment by k0shk0sh** [comment]
Owwh, yeah It changed :p, now all notifications will remain there, however those unread will look highlighted, once they are marked as read they will appear same as the rest :) 

Unsubscribe, will mark the notification as read & unsubsribe you from the thread.

**Comment by arkon** [comment]
The read items need to be more obviously marked as read, and eventually removed. It's sort of confusing seeing a big list of notifications that seemingly can't be dismissed.

**Comment by k0shk0sh** [comment]
@arkon how obvious than changing their highlight state, something similar to gmail for example. They don't disappear but they are un-bold-ed in FastHub unread state & read state has different highlight experience.

**Comment by arkon** [comment]
Talked about this on Slack too. It's currently confusing since it shows all notifications (i.e. [this page](https://github.com/notifications?all=1) on GitHub), which could potentially be quite long. I proposed having filters like GitHub (i.e. unread vs. all).
