### ISSUE TITLE
Empty screens and app crashes

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#369]
**App Version: 1.9.4**

**OS Version: 23**

**Model: samsung-SM-G800F**

I don't know how to call these, but when you click on "pushes" (see the top item in the first screenshot), the app shows an empty screen (see the second screenshot). When you click on the comment FAB, the app crashes.

![](http://i.imgur.com/3uJYLYA.png)
![](http://i.imgur.com/yCcCM7a.png)

**Comment by k0shk0sh** [comment]
Please update to 1.9.5 which fixes this
