### ISSUE TITLE
Could not mark notifications read

### ISSUE THREAD

**Issue by Rainer-Lang** [k0shk0sh/FastHub#37]

**Comment by k0shk0sh** [comment]
once u click on a notification, It will mark it as read & if you referring to notification icon, im aware of it. could you confirm on this.

**Comment by Rainer-Lang** [comment]
I know this. But i wanna mark all notifications read, without opening every of them.

**Comment by k0shk0sh** [comment]
Alright, I got you know. marking them all, this means you no longer going to see them again tho, I will be adding an action for that to mark all as read. 
Thanks for your feedback.

**Comment by Rainer-Lang** [comment]
Appreciate it, thanks.
