### ISSUE TITLE
Text previews don't show images

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#372]
**App Version: 1.9.5**

**OS Version: 23**

**Model: samsung-SM-G800F**

When you type a message, comment or issue that has an image in it, the preview window doesn't display the image. By preview window I mean the eye icon in the bottom right corner.

**Comment by k0shk0sh** [comment]
Lol, I was just testing that :D

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/p2JdEbX.png)
