### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by felixfong227** [k0shk0sh/FastHub#374]
**App Version: 1.9.5**

**OS Version: 6.0.1**

**Model: samsung-SM-C5000**

---
Mobile
![](http://i.imgur.com/8baJvOe.png)

GitHub
![](http://i.imgur.com/jNj3Jl2.jpg)

And FastHub just got way too much notification, and that is killing my phone battery

**Comment by k0shk0sh** [comment]
Got that like how? I mean, why purposely go into notification screen if you don't get any notifications? I cant really understand the argument in here.
Could you please elaborate on what's the problem here?

**Comment by k0shk0sh** [comment]
Nice screenshot btw :)

**Comment by felixfong227** [comment]
My phone static bar keep showing up FastHub notification, like more then 5 of them, and once I want to see what it is, they just all gone, and sometimes just left one

**Comment by k0shk0sh** [comment]
@felixfong227 hmm, strange, could you go settings & either disable notifications or set them to 30mins

**Comment by felixfong227** [comment]
Will do @k0shk0sh thanks a lot

**Comment by k0shk0sh** [comment]
@felixfong227 np, btw if you received notifications, then you definitely received notifications, it might just be GitHub api bug, also in screenshots you seem to subscribe to few issues & that might be the cause you receiving notifications.
