### ISSUE TITLE
Repository without issues 

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#377]
**App Version: 1.9.5**

**OS Version: 23**

**Model: samsung-SM-G800F**

If you click on _issues_ in a repository that doesn't have any issues, nothing happens.

**Comment by arkon** [comment]
To be clear, this is for repos that don't have issues _enabled_. It works fine if there's just 0 issues.

**Comment by k0shk0sh** [comment]
There should be a message stating that no issues for this repo, the reason it remains there is due to the fact we can't have 2 tabs only at bottom. #guidelines
