### ISSUE TITLE
Issues/PRs tabs differ

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#378]
- FastHub Version: 1.9.5
 - Android Version: 7.1.2
 - Phone Model: OnePlus One

The main feed activity has 3 tabs: Feeds, PRs, and Issues. In a repo activity, it has Code, Issues, and PRs. The ordering of Issues/PRs should be made consistent.

**Comment by k0shk0sh** [comment]
Looking at main website, you could see that feeds are first, looking up, pr are second & issues are third.

**Comment by arkon** [comment]
Hmm true. I guess it bothers me more in the app since they're very similar in the bottom nav bar.
