### ISSUE TITLE
[Feature Request] link to referred Issues/PRs in commits

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#382]
**App Version: 1.9.1**

Ability to directly access mentioned issues or PRs via dedicated tab next to "commits" and "comments", or #links in the commit's title
.
![](http://i.imgur.com/o2GNYr5.png)
.
![](http://i.imgur.com/kdPRmZr.png)
.
(preferably not in the list tabs to avoid accidental taps)

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/TL83Cny.png)
