### ISSUE TITLE
Repo & Org Project Cards & Columns 

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#384]
Soon.

**Comment by aadithyabk** [comment]
Can you fill me in on this? I can pick it up unless you have already started on it

**Comment by k0shk0sh** [comment]
@aadithyabk I havs started on it locally but never committed :D . Planning to make it look something similar to GitHub, however im confused on where should I put the tab lol.

**Comment by aadithyabk** [comment]
Haha okay. That's fine, I'll look at other issues

**Comment by k0shk0sh** [comment]
@aadithyabk adi are you still interested in this? If so, please make it yours :D . I will be focusing on other things (test) :D

**Comment by aadithyabk** [comment]
@k0shk0sh Yup, I can pick it up. May be I can pull your branch into my fork and work off of that? I'll hit you up on slack. I have couple of questions

**Comment by cassidyjames** [comment]
Adding the word "projects" here so it comes up in search. 😄 I'd love to help this feature be developed; do you all have a bug/feature bounty program where I could chip in monetarily?

**Comment by k0shk0sh** [comment]
@cassidyjames unfortunately I don't practice that nor encourage community to do it either.

**Comment by cassidyjames** [comment]
@k0shk0sh no worries! I'll pitch something your way through the app. 😉
