### ISSUE TITLE
Github OAuth login will crash app

### ISSUE THREAD

**Issue by ciscorucinski** [k0shk0sh/FastHub#385]
**App Version: 1.8.1**

**OS Version: 23**

**Model: samsung-SM-N910L**

Whenever something Github needs to be opened, then this app will be opened. This is true when a user is performing OAuth login via another app. 

__This will try to open up this app and then fail.__

**Comment by k0shk0sh** [comment]
hey, thanks for reporting, this has been solved locally, where 
```
Stream.of("notifications", "settings", "blog", "explore",
            "dashboard", "repositories", "site", "security", "contact", "about", "logos", "login", "")
```

are ignored now.
