### ISSUE TITLE
反馈 打开含有issues的链接会闪退 

### ISSUE THREAD

**Issue by zdzliqian** [k0shk0sh/FastHub#387]
---

 - FastHub Version: 1.95
 - Android Version: 7.1.2
 - Phone Model: xiaomi mi4

**Comment by k0shk0sh** [comment]
@zdzliqian thanks for reporting, could you write the issue in English so I could be able to help you? 

@Devifish  maybe you can help with this? I can't understand.

**Comment by zdzliqian** [comment]
@k0shk0sh thank you

**Comment by zdzliqian** [comment]
When the link contains "issues", there will be "FastHub has stopped running"
For example, when you open "https://github.com/SeaHOH/GotoX/issues", you will exit FastHub

**Comment by k0shk0sh** [comment]
@zdzliqian what app version are you using?

**Comment by zdzliqian** [comment]
1.9.2

**Comment by k0shk0sh** [comment]
Oops, can you update from playstore to 1.9.5?

**Comment by zdzliqian** [comment]
@k0shk0sh  1.95

**Comment by k0shk0sh** [comment]
got it :D .. thanks, solving it right now.
