### ISSUE TITLE
Lack of notification options

### ISSUE THREAD

**Issue by Generator** [k0shk0sh/FastHub#388]
Nice to see notifications on FastHub but lacks some options:

- Choose a custom notification sound
- Notification vibration options (default, long, sort, disabled)
- Priority

Had to disable the notifications here because of the annoyances like not being able to disable vibration

**Comment by k0shk0sh** [comment]
@Generator , customizing the notification in this manner currently isn't in my scope, however you made a point, i'll try and implement this soon, meantime, by next release notifications again has been revamped, it will have two tabs`Unread` & `All` so you could easily see your unread notifications on the fly.
