### ISSUE TITLE
[Feature Request] sort by last updated 

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#389]
**App Version: 1.9.5**

**OS Version: 25**

**Model: HTC-Nexus 9**

Is there a way you can add in the issues sorted by last updated. Currently it is by created time. 

Thanks for the great app

**Comment by kutsan** [comment]
Right bottom of issues screen, there is floating action button that you can search from. In there, you will see sort option.

**Comment by k0shk0sh** [comment]
Is it the my issues tab or repos issues ? If repos issue, then as @kutsan mentioned, otherwise I'm planning to implement that for my issues & pull requests

**Comment by Younes-L** [comment]
@k0shk0sh is it possible to add a permanent sorting button next to the "add" and "search" from the FAB?

**Comment by k0shk0sh** [comment]
@Younes-L its definitely possible, I'll try and have a settings for that.

**Comment by yakov116** [comment]
@kutsan thanks I didn't even think to look there

**Comment by k0shk0sh** [comment]
@yakov116 glad its solved. @kutsan thanks.

**Comment by yakov116** [comment]
@k0shk0sh why would you not make the default issue page look like this?
![Issue tab](http://i.imgur.com/GPIJ9wE.png)

**Comment by k0shk0sh** [comment]
@yakov116 you are using tablet :p now imagine that in phone :D with phone UI which you could see from play store listing.

**Comment by yakov116** [comment]
@k0shk0sh can you make just for tablets like that?

**Comment by k0shk0sh** [comment]
@yakov116 that's selfish lol but good point. i'll see about that :)

**Comment by yakov116** [comment]
@k0shk0sh if you say so 😀

**Comment by k0shk0sh** [comment]
@Younes-L it will be in 2.2.0 :)

**Comment by Younes-L** [comment]
@k0shk0sh good to know, keep it up ! ☺️

**Comment by k0shk0sh** [comment]
this should have been closed awhile ago lol.
