### ISSUE TITLE
Please add a switch to turn animations off

### ISSUE THREAD

**Issue by Rainer-Lang** [k0shk0sh/FastHub#39]
I start using your app now, and I really don't need the animations. They are a bit disturbing.

**Comment by k0shk0sh** [comment]
Im using custom Rom and I can't see any animation 😂😂

**Comment by Rainer-Lang** [comment]
You should use another phone. 😉

**Comment by k0shk0sh** [comment]
Probably, meantime if you got time, can you record your experience and share it with me. if that's possible.

**Comment by alashow** [comment]
https://drive.google.com/file/d/0B5up2CgQawSDcVlxc050N3ZOLW8/view?usp=drivesdk

I actually liked them first, but I agree, they are bit annoying now :)

**Comment by k0shk0sh** [comment]
@alashow So you guys referring to the recyclerView animations. well then. you got urself a button to disable it :p

**Comment by Rainer-Lang** [comment]
@k0shk0sh I don't understand what you try to tell us.

**Comment by k0shk0sh** [comment]
It's going to be in next version.

**Comment by Rainer-Lang** [comment]
Perfect :)
