### ISSUE TITLE
[Feature Request] change the add/search

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#390]
**App Version: 1.9.5**

**OS Version: 25**

**Model: HTC-Nexus 9**

I like the way tapatalk does it would you be able to do something like that?
![Tapa](http://i.imgur.com/bDDpz8N.png)

**Comment by k0shk0sh** [comment]
I actually changed the way current one displayed with an overflow layout on top of the fab with some animations :p . i'm not against fabMenus maybe i'll consider this.

**Comment by yakov116** [comment]
@k0shk0sh thank you guys are the best

**Comment by yakov116** [comment]
https://github.com/futuresimple/android-floating-action-button

**Comment by k0shk0sh** [comment]
Its changed however not to fab menu, but rather fab card menu :D
