### ISSUE TITLE
slack channel link doesn't work

### ISSUE THREAD

**Issue by Dreamersoul** [k0shk0sh/FastHub#393]
the links in contributing and the readme file point to fasthub.herokuapp.com which is broken :( i want to join the discussion since i want to contribute as soon as i get the architecture of the app

**Comment by k0shk0sh** [comment]
```
[Action Required] - You have used all of your Free Dyno hours
You have used all of your 550 Free Dyno hours for April 2017.
```
:'( 

Pass me your email & i'll invite you manually.

**Comment by Dreamersoul** [comment]
:( here's my email
hamad.y.alghanim[at]gmail[.]com

**Comment by k0shk0sh** [comment]
@Dreamersoul done :)
