### ISSUE TITLE
Image attachments sometimes crash app

### ISSUE THREAD

**Issue by wxl** [k0shk0sh/FastHub#396]
**App Version: 1.9.5**

**OS Version: 24**

**Model: samsung-SM-G930V**

Some images such as [this one][1] cause the app to crash. This is also the case with multiple images such as [these][2] [two][3].

[1]: https://pictor.ialis.me/media_attachments/files/000/035/774/original/aab22f881c0e22a2.jpg
[2]: https://pictor.ialis.me/media_attachments/files/000/035/803/original/33ccaee924aae6df.jpg
[3]: https://pictor.ialis.me/media_attachments/files/000/035/810/original/3789e2f27111f479.jpg

**Comment by k0shk0sh** [comment]
Crash it like how? Are you trying to upload the image via markdown? Or seeing it in comments causes the crash?

**Comment by wxl** [comment]
This is when uploading with the 📎icon when trying to make a new toot. There's no success or error, no progress meter. The app just crashes.

**Comment by k0shk0sh** [comment]
@wxl thanks for clarification, 
P.S: your title actually mentioned it but I just wokeup so please ignore my silly question :'(

**Comment by k0shk0sh** [comment]
Strange, but I can :p

![](http://i.imgur.com/g1SaUrL.jpg)
![](http://i.imgur.com/5CG5X4K.jpg)

**Comment by wxl** [comment]
You know those links might not be useful. I note that the image is transformed, including a modification of the size and what appears to be stripping of the metadata. 

Looking at information from `file`, the original was:

```
20170429_135455.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=13, height=3024, manufacturer=samsung, model=SM-G930V, orientation=upper-right, xresolution=188, yresolution=196, resolutionunit=2, software=G930VVRU4BQA4, datetime=2017:04:29 13:54:55, GPS-Data, width=4032], baseline, precision 8, 4032x3024, frames 3
```

The one I linked was, however:

```
aab22f881c0e22a2.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, baseline, precision 8, 960x1280, frames 3
```


Keep that in mind when testing. If you need the original, let me know.

**Comment by wxl** [comment]
Omg. Wrong pinned repo. 🤦🏽‍♂️

**Comment by k0shk0sh** [comment]
you mean this issue belongs to different repo? :D ..
