### ISSUE TITLE
Can't close issues

### ISSUE THREAD

**Issue by ProgrammingWizzard** [k0shk0sh/FastHub#397]
**App Version: 1.9.5**

**OS Version: 23**

**Model: samsung-SM-A510F**

Hello, I clicked to "Close issue", but I can't it. A bug has escaped: "You can't close this issue" or something like this :V

**Comment by k0shk0sh** [comment]
Is it a specific issue? Or all? I just tried in your issue and everything seems to be fine

**Comment by ProgrammingWizzard** [comment]
`Is it a specific issue? Or all?`
All.

**Comment by k0shk0sh** [comment]
@ProgrammingWizzard strange, could you try and close this issue & screenshot the message displayed? You can upload the image from FastHub markdown editor. 
Thanks.

**Comment by ProgrammingWizzard** [comment]
Ok, wait a minute ;)

**Comment by ProgrammingWizzard** [comment]
LOL, i can close issues, but 5 minutes ago I could not :V

**Comment by k0shk0sh** [comment]
@ProgrammingWizzard I see that you can close & open ? Are the issues you trying to close are yours or you are a collaborator in the repo ? 
If you aren't one of above, then the option shouldn't even be showing.  😕

**Comment by ProgrammingWizzard** [comment]
`Are the issues you trying to close are yours or you are a collaborator in the repo ?`
Definitely yes.

I might suggest something if it helps:
https://github.com/FunnyGuilds/FunnyGuilds/issues/413

**Comment by k0shk0sh** [comment]
@ProgrammingWizzard I'm not so sure how that will help me because I can't even understand what's written there 😀

**Comment by ProgrammingWizzard** [comment]
OK no problem ;)
I think it was some kind of temporary API error. Thanks for the help!

**Comment by k0shk0sh** [comment]
@ProgrammingWizzard np & glad its solved, 
The issue you mentioned actually helped me find something, the label doesn't look nice lol. 

![](http://i.imgur.com/ZVos853.png)

**Comment by kutsan** [comment]
@ProgrammingWizzard Please re-open this issue if you encounter again.

**Comment by ProgrammingWizzard** [comment]
@kutsan ok, no problem ;)
