### ISSUE TITLE
Keep getting the notifications over and over after dismissing.

### ISSUE THREAD

**Issue by arieljannai** [k0shk0sh/FastHub#399]
After dismissing a notification (swipe it from notifications bar), it comes back after a short time.

I believe that the correct behavior is that it shouldn't show the notification if it was already dismissed (in case there wasn't any new activity regarding that notification).

I saw that the issue #353 was closed, and I think it's similar

---

 - FastHub Version: 1.9.5
 - Android Version: 7.0
 - Phone Model: LG G5 (H850)

**Comment by k0shk0sh** [comment]
Hello there, thanks for reporting, the current impl is that you have to click on read the notification so it doesn't appear again,  if it's still unread GitHub will definitely push it again which that's why you see it .

**Comment by arieljannai** [comment]
Will it be possible to filter them in the app in some way?
I tend to dismiss them when I can't look at it at the moment (as a lot of people does).

Maybe mark them as read in GitHub, and have a __save for later__ section in FastHub?

**Comment by k0shk0sh** [comment]
@arieljannai if you mark them as read you'll see them again in app currently in the version you have which contain all notifications, it will be listed there, upcoming release will have two tabs one for unread and one for all. 
I'm not so sure tbh if I could do that anytime soon. But I'm open for it. 
Thanks

**Comment by arieljannai** [comment]
Ok, thanks!
I'll see how things get evolved and we'll see over time. Thanks for considering it 😀
