### ISSUE TITLE
Side nav item shouldn't disappear if currently viewing it

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#403]
- FastHub Version: 1.9.5

If the user is on the home page, "Home" is missing from the side nav. Likewise, if the user is on their profile, "Profile" is missing. It's sort of weird behaviour, since it doesn't do that for any of the other items in the side nav. It should simply be highlighted (i.e. visibly selected).

**Comment by k0shk0sh** [comment]
good point :D

**Comment by k0shk0sh** [comment]
this 787d603 should closes this
