### ISSUE TITLE
[Feature Request] Unread badge counts

### ISSUE THREAD

**Issue by dikiaap** [k0shk0sh/FastHub#404]
**App Version: 1.8.1**

**OS Version: 22**

**Model: Evercoss-EVERCOSS A65**

Add unread badge counts in the home screen and to the bell icon inside the app, previously just make the bell color to blue.

I don't know if this already happened in other users, no? I use ZenUI launcher.

**Comment by k0shk0sh** [comment]
Why did you close it :D

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
