### ISSUE TITLE
Please add an option to turn off update notifications. 

### ISSUE THREAD

**Issue by thirashima** [k0shk0sh/FastHub#405]
**App Version: 1.9.5**

**OS Version: 25**

**Model: LGE-Nexus 5X**

The notifications are annoying and completely redundant.

**Comment by k0shk0sh** [comment]
You could easily disable notifications from settings screen, please also do update to 2.0.0. Thanks

**Comment by thirashima** [comment]
I already had that set to "never", and I still got the update notification.

**Comment by k0shk0sh** [comment]
Could you update to 2.0.1 and let me know? Thanks

**Comment by k0shk0sh** [comment]
@thirashima  please correct me if I'm wrong
You were referring to the push notification I sent asking you to update the app?
If so, then this option isn't available for you to disable that. 
Will try and add that in next version

**Comment by thirashima** [comment]
Yes, that was the one. Thanks for considering it.

On May 1, 2017 11:40 PM, "kosh" <notifications@github.com> wrote:

@thirashima <https://github.com/thirashima> please correct me if I'm wrong
You were referring to the push notification I sent asking you to update the
app?
If so, then this option isn't available for you to disable that.
Will try and add that in next version

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/405#issuecomment-298509592>,
or mute
the thread

**Comment by JediBurrell** [comment]
This issue has been appealed in bc856e1.
