### ISSUE TITLE
[Enhancement] Hide "read all" button in all notifications tab if all from repository are read

### ISSUE THREAD

**Issue by Maxr1998** [k0shk0sh/FastHub#406]
**App Version: 2.0.0**

**OS Version: 25**

**Model: Huawei-Nexus 6P**

 The clear all button (three lines) in the all notifications tab can be hidden if all items of a repository are actually read:
![Screenshot](https://cloud.githubusercontent.com/assets/5903699/25575543/b46e6f94-2e58-11e7-9825-1048bfd81efe.png)

**Comment by k0shk0sh** [comment]
Wanna take over this? 😛

**Comment by Maxr1998** [comment]
@k0shk0sh I would! Sadly I'm pretty busy with my final exams atm. I already took a quick look at the Notification (header) adapters and viewholders, but I didn't see yet how and where the clear button is handled.

Btw, your `build.gradle` and project structure are really amazing, e.g. I didn't know you could put resources in custom subfolders. :+1:

**Comment by k0shk0sh** [comment]
@Maxr1998 it will be handled in `AllNotificationsFragment` & `AllNotificationsPresenter` we could add a flag to the `group model` in header row to hide the icon. 
I'll look at it later, good luck with your exam.

**Comment by JediBurrell** [comment]
This issue has been fixed in commit 749cedd.
