### ISSUE TITLE
Unread notifications not grouped by repo

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#408]
**App Version: 2.0.1**

**OS Version: 25**

**Model: asus-Nexus 7**

 The "all" notifications has the repo grouping feature previously added, but the unread tab is just one big list.

**Comment by k0shk0sh** [comment]
Works as intended, however I'll see about it 😛

**Comment by k0shk0sh** [comment]
I guess this will be tricky, as the unread notifications has pagination, meaning, that for example, you have 40 unread notifications, first 20 items are for FastHub, 10 items for Arkon repo, 10 for FastHub, you'll end having two groups of FastHub. its tricky and therefore i'll abandon it. I hope you got what I mean.
