### ISSUE TITLE
Deleting Branch in Feed

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#410]
**App Version: 2.0.1**

**OS Version: 25**

**Model: Google-Pixel**

If I delete a branch on a repo, in the feed it says I deleted the repo, not a branch.

**Comment by k0shk0sh** [comment]
What does it really say?

**Comment by eygraber** [comment]
eygraber **deleted** <repo name>

It's on an organization repo if that makes a difference.

**Comment by k0shk0sh** [comment]
Probably there are more events that I'm not handling

**Comment by adriaanzon** [comment]
Yeah I noticed some more:   

1. branch creation appears as repository creation
2. message for when a user gets added as collaborator: 
    > `<owner>` added member `<repository>`
3. message for when a new release gets tagged:
    > `<user>` published released `<repository>`
4. message for when a user edits a wiki
    > `<user>` wiki `<repository>`

If you need some reference for how it actually shows op on the github website, ask away, I'll look it up.

Some others that aren't faulty but could be improved:

* "created comment on issue" should be "commented on issue"
* "created pull request comment" should be "commented on pull request"
