### ISSUE TITLE
Code in comment running off screen

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#417]
**App Version: 2.0.1**

**OS Version: 25**

**Model: Google-Pixel**

 Looking at a comment that has a code snippet in it, it renders off the end of the line, but I can't scroll horizontally to see the rest of it. 

![Example](http://i.imgur.com/98bBkU5.png)

**Comment by k0shk0sh** [comment]
`Observable<Pageable<ReviewModel>> getReviews(@Path("owner") String owner, @Path("repo") String repo, @Path("number") long number)`

**Comment by eygraber** [comment]
@k0shk0sh this is now happening when creating a comment:

`This is an example of some long text in a code block that runs off the screen in the preview while I'm writing it`

![Edit mode](http://i.imgur.com/Sv0ao7q.png)

![Preview mode - line is not scrollable](http://i.imgur.com/IAOsgVp.png)

**Comment by k0shk0sh** [comment]
Oops, it happens in editor as well? :'( 

i'm on it right now.

thanks buddy.
