### ISSUE TITLE
Notification tabs swipe

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#419]
**App Version: 2.0.1**

**OS Version: 25**

**Model: Google-Pixel**

 I can't swipe to switch between unread and all in notifications.

**Comment by k0shk0sh** [comment]
If I ever did #418 then this should be fixed. Gonna close this & edit the other to include this within it.

**Comment by JediBurrell** [comment]
This issue has been fixed in 8b4c2ba.
