### ISSUE TITLE
Publish an alpha/beta

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#423]
**App Version: 2.0.1**

**OS Version: 25**

**Model: Google-Pixel**

 Using CD (Travis or some other option) you can setup a deploy to either the Play Store alpha/beta channels or something like Fabric Beta.

**Comment by eygraber** [comment]
@k0shk0sh does this get deployed somewhere?

**Comment by k0shk0sh** [comment]
@eygraber yep, we will update readme ASAP to include nightly builds badge 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
