### ISSUE TITLE
Idea for new logo

### ISSUE THREAD

**Issue by ffes** [k0shk0sh/FastHub#425]
I am not a designer so I can not make it myself. But it somebody likes the idea, feel free to create a new logo for FastHub based on this idea:

Use the git logo from https://git-scm.com/downloads/logos and make it look **fast**

**Comment by k0shk0sh** [comment]
It would be really cool if we get new icon :D . I could pass the old vector to anyone and change whats inside it to something looks nice & fast :p

**Comment by kutsan** [comment]
Even you can't make a new logo for FastHub, you can contribute how logo should look with saying your ideas about. This can help to future potential designer.

Tones, colors, shape, design; welcome.

**Comment by Younes-L** [comment]
As much as I like the blue colour, I think it looks too generic, especially on the new icon. Maybe dark yellow + grey/black 
*à la* XDA, or teal + dark grey/black 🙂

![](http://i.imgur.com/psdOMIF.jpg)

**Comment by kutsan** [comment]
@Younes-L Probably, our blue accent color won't change. It's kind of brand-ish at this moment. I appreciated, to putting your time to change that logo color but this is too generic to use for us. Should be probably an illustration with unique aura like old one.

**Comment by Younes-L** [comment]
@kutsan I am no design either, I was just suggesting colour combinations and uses this icon as an example ^^

**Comment by ozyx** [comment]
I'm also not "artistically gifted" but I'd like to say that I second the request for a more fitting icon, preferably something more "symbolic". Also, I'd like to extend the icon redesign to the notification icon as it looks very similar to the Textra notification icon.

**Comment by k0shk0sh** [comment]
@ozyx which notification icon? Its Android default material icon, they can't do nothing about it :) , I'm also with changing FastHub icon

**Comment by ozyx** [comment]
@k0shk0sh I'm not sure as I'm brand new to android mobile dev but I'm running Android v6.0.1 and it's a message icon with a '!' in the middle.

**Comment by k0shk0sh** [comment]
@ozyx as you can see, it's an icon from Android official icons. 

![](http://i.imgur.com/XODfONA.png)

![](http://i.imgur.com/ihX3MeG.png)

**Comment by arkon** [comment]
It is more typical to see a variation of the app icon as the notification icon though. It helps distinguish it from other apps.

**Comment by k0shk0sh** [comment]
@arkon we will need that in svg format & also not colorful :D .

**Comment by arkon** [comment]
I guess it depends on whatever the new icon will be. :)

**Comment by jgkamat** [comment]
Just wanted to say it might not be a good idea to base the logo for this project on the git logo. There is a bunch of licensing stuff for the logo to prevent confusion. I also think that FastHub should have a more distinctive icon than the git logo: https://git-scm.com/trademark

**Comment by k0shk0sh** [comment]
@jgkamat true, I don't like the git icon neither :D. If anybody knows any designer that likes to contribute to open source & with given a credit to, Please let me know how I can contact them.

**Comment by jgkamat** [comment]
I would reccomend contacting the creator of [twelf](https://f-droid.org/repository/browse/?fdid=org.twelf.cmtheme&fdpage=58), which is simply the best icon pack I've ever found for android (and focusing on FOSS icons). 

Their [gitlab hq is here](https://gitlab.com/xphnx/twelf_cm12_theme) and their [user is here](https://gitlab.com/xphnx). You can also use their 'turtl' app to get into contact with them (although that's meant for reporting missing app icons).

**Comment by daycode** [comment]
# New icon

## With git icon
![ic_launcher](https://cloud.githubusercontent.com/assets/13915512/25822902/8559e0fc-343a-11e7-97fb-a8ef6546ca37.png)

## With fork icon
![ic_launcher](https://cloud.githubusercontent.com/assets/13915512/25822923/969953f2-343a-11e7-9804-a4a551a6e540.png)

Feel free to tell me what you think about them (icon and colors), and I'll ajust that :kissing_heart:

**Comment by kutsan** [comment]
@daycode Wow, thanks. In my opinion, those are good enough to replace current one but not so mature enough to be final icon. But still better than current.

**Comment by daycode** [comment]
I agree, the application should have its own icon referring to git, but not same.

**Comment by k0shk0sh** [comment]
@daycode great news, cookicons.co going to make FastHub new icon :)

**Comment by Younes-L** [comment]
Awesome ! Cookicons is one of the best icon designers I've seen 😃

**Comment by ffes** [comment]
I still hope that the "fast" part of the name of the program will show in the new icon

**Comment by k0shk0sh** [comment]
@ffes can't really confirm, I trust the designer would something amazing, I even let him decide the icon himself. Anyway any icon is better than the current one 😂😂😂😂

**Comment by k0shk0sh** [comment]
@Younes-L he definitely is, old icon was so amazing & Kevin has done a pretty well job on it.

**Comment by wasdennnoch** [comment]
I'm not quite sure about the fork icon since there already is an app called 'ForkHub' out there which it may be confused with. I like the git one but as already said it should have a variation to make it unique.

**Comment by deavmi** [comment]
The current logo is great; don't change it.

**Comment by k0shk0sh** [comment]
@deavmi well, tbh it isn't :p . i'm still waiting for cookicons to finish the new icon & i'm sure it will be more greater than this.

**Comment by deavmi** [comment]
Maybe for you but I like it. Just stating my opinion but you must do what you want :).

**Comment by dikiaap** [comment]
Hey guys, Does that [Cookicons](https://www.cookicons.co/) still handle this?
Just FYI, there is another community that helps design for open source like this.
[mozilla/OpenDesign](https://github.com/mozilla/OpenDesign)

cc: @elioqoshi
His works are amazing.
https://elioqoshi.me/open-source-projects-logos/
https://elioqoshi.me/mozilla-logos/

**Comment by k0shk0sh** [comment]
@dikiaap yep he is on it, I'll let you know if anything

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
This issue shall be closed now with the new icon

![](http://i.imgur.com/EI8onrH.png)

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
This issue shall be closed now with the new icon

![](http://i.imgur.com/EI8onrH.png)

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
This issue shall be closed now with the new icon

![](http://i.imgur.com/EI8onrH.png)

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ozyx** [comment]
@k0shk0sh it's so beautiful...

**Comment by elioqoshi** [comment]
@dikiaap Thanks for the nice words! I see you have already handled this, love the new icon!
