### ISSUE TITLE
Editing an issue crash

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#427]
**App Version: 2.0.1**

**OS Version: 25**

**Model: HTC-Nexus 9**

 I sent the logs when I edit an issue it crashes.

I don't this the issue is with the app. I think git hub is having issues. ( I used the app since the website was crashing on me)

**Comment by k0shk0sh** [comment]
Issue link? And also could you elaborate on  website was crashing on you?

**Comment by yakov116** [comment]
@k0shk0sh it's a private repo

![Website](http://i.imgur.com/AgfLkte.jpg)
And when I tried to reply using the website
![Number 2](http://i.imgur.com/PoAAGyT.jpg)
