### ISSUE TITLE
Add app to XDA

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#432]
---

 - FastHub Version:  Desktop 2.0
 - Android Version:  Windows 10
 - Phone Model: Dell Inspiron 3847

Maybe you can add the app to XDA?
I think it would do add a lot of publicity

**Comment by alamo18** [comment]
xda ? like open a new thread or xda labs? i mean most ppl should have fdroid or play store, soz its really easy to install. I see no need to do this... @koshk0sh what do you think?

**Comment by yakov116** [comment]
> I think it would do add a lot of publicity

**Comment by yakov116** [comment]
Any yes i think there should be a thread and add to XDA labs doesn't take much work (or time)

**Comment by k0shk0sh** [comment]
@alamo18 well I think it's fine to add it to XDA for publicity as yakov mentioned, however it doesn't mean I have to do it, anyone of you guys could do that :) if you think FastHub is worth sharing, please do so 😊

**Comment by yakov116** [comment]
I can create a thread, but i thought you as the "Owner" (as github calls you) ) you should start the thread. I think it would get more PR that way

**Comment by k0shk0sh** [comment]
@yakov116 you could do it if you want to :) , if you did please share link with us in slack & close this. Otherwise let me know and I'll try and fine time for it.

**Comment by yakov116** [comment]
@k0shk0sh just need the logo and android min ver

**Comment by k0shk0sh** [comment]
@yakov116 __minSdk:21__ logo is [Here](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/res/drawable-nodpi/web_hi_res_512.png)

**Comment by yakov116** [comment]
@k0shk0sh xda username?

**Comment by k0shk0sh** [comment]
@yakov116 ![k0sh](https://forum.xda-developers.com/member.php?u=3851059)

**Comment by yakov116** [comment]
Should have opened as a thread not a DB right?

**Comment by yakov116** [comment]
I started it will update it a soon when i have a min

**Comment by yakov116** [comment]
https://forum.xda-developers.com/android/apps-games/app-fasthub-github-t3603079

**Comment by k0shk0sh** [comment]
@yakov116 clicking on App opens app aliexpress :?
![](http://i.imgur.com/WJojslV.png)

**Comment by yakov116** [comment]
@k0shk0sh let me check! I'm not sure?

**Comment by yakov116** [comment]
@k0shk0sh I dont know what you are seeing but this is the code behind "apps"

```
[SIZE="3"][B]App [/B][/SIZE]
```

**Comment by k0shk0sh** [comment]
@yakov116 perhaps it's an Ad. Nvm :D. 
Thanks btw
