### ISSUE TITLE
Truncate the diff on a PR comment

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#433]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Google-Pixel**

 The diff displayed on a PR comment shows the whole file until the comment line. Maybe only show a few lines above and below the line the comment is on, and bold it.

**Comment by k0shk0sh** [comment]
I wish if I could do this, but simply  can't, as GitHub returns the diff text without even a line number indicates where it is exactly.

**Comment by eygraber** [comment]
So what about only showing the last few lines of what they send back?

**Comment by k0shk0sh** [comment]
@eygraber I wanted to do that but then how am I supposed to know which line to keep and which one to truncate :D it's complicated trust me and I had to do many things to make it work nicely their review api is so bad designed

**Comment by eygraber** [comment]
@k0shk0sh I haven't looked at the API responses, but it seems like the diff they send back always ends with the line the comment is on. If that's the case, then only showing the last few lines that they send back should do it.

**Comment by Younes-L** [comment]
@eygraber that with an "expand" button would be good 🙂👍

**Comment by k0shk0sh** [comment]
@eygraber will if that's the case then truncate it is :D
