### ISSUE TITLE
Add reactions to a PR comment

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#434]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Google-Pixel**

 My team usually uses reactions to acknowledge a comment. It would be cool to do that here.

**Comment by k0shk0sh** [comment]
PR comments has reactions? 
Isn't there?

**Comment by eygraber** [comment]
I mean emoji reactions like regular comments.

**Comment by k0shk0sh** [comment]
@eygraber isn't all comments in app has reactions & reactions can be given to comment? Except for gist comments.
I'm confused lol

**Comment by eygraber** [comment]
@k0shk0sh with the new PR comments feature that you added, I can see PR comments in the app, but I can't add emoji reactions to them.

**Comment by k0shk0sh** [comment]
If you mean review comments then yup, it isn't there otherwise the pr comments has reactions :D

![](http://i.imgur.com/fiegDkc.png)

**Comment by eygraber** [comment]
@k0shk0sh derp, yeah sorry I meant review comments.

**Comment by k0shk0sh** [comment]
@eygraber well review comments are still read only ad I mentioned in the changelog, the api is pretty bad & had to do pretty hardcore stuff lol. Its my focus for next release to finish that api up.
