### ISSUE TITLE
Creating a tag in feed

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#435]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Google-Pixel**

 In GitHub there's an item in my feed

> <user> created tag <tag> at <repo> 

But in FastHub it's

> <user> created <repo>

**Comment by k0shk0sh** [comment]
There will be more lol until we figured out all of the events :D it really had be nice if I could see them all in one response to construct them properly
