### ISSUE TITLE
[FR] Allow to preview previous comments when composing a new comment

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#438]
I like your Markdown Editor with preview feature. However, it appeared pretty inconvenient to add new comments because it's impossible to see the previous comments in the meanwhile.

For instance, you want to reply to the some Issue or PR comment of substantial size. You might even want to quote some parts of the comment. However, currently Markdown editor doesn't allow you to get back to comments and copy something from there or review it for one more time. If you press the _back_ button, FastHub suggests to discard everything you just typed. The only way to work around this is to use some other tool (e.g. `OctoDroid` or browser) simultaneously.

I want to request a feature inside the FastHub to access previous comments during a new reply. Potentially, I see a few ways to implement this:

- don't make the Editor full screen, so you still have access to the previous replies. You might add special controls to make it resizable, so user can select the height which is most convenient to me;
- if you use the `Reply` button, add a special button to see the original message. I don't like this way too much, because you might need more than the latest comment only;
- don't discard everything when you press the _back_ button. Rather, keep it in memory and change color for the `Add comment` button to show it's dirty. Next time you press the dirty `Add comment` button, you should see everything you previously typed. When you leave the current screen, notify that pending comment is present and it will be discarded if continue;
- like the previous one, however draft is never discarded. Rather, you put it to stash. Next time the `Add comment` button is pressed, you ask whether FH should put any of the stashed replies. This way you could even implement the auto-save feature. Also it allows to navigate to any other screen you might need (e.g. other issue to copy a link to it).

Let me know if you need further clarifications from me.

Thank you in advance.

---

 - FastHub Version: 2.1.0
 - Android Version: M
 - Phone Model: Xiaomi MI5

**Comment by k0shk0sh** [comment]
Seems like a good idea, I'll see what I can do about it.
Thanks for the report.

**Comment by yakov116** [comment]
@zvirja in the last update this was added. Do you have anything to add on the way it was done?

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment]
Wow, so quickly :) Well, it's working. However, I have a couple of concerns:

1. Now the "previous reply" occupies half of the textbox, leaving much less space to review what you compose. Given that we don't need original message for each time, it would be much better to implement that via toggle button.

1. It still doesn't cover all the needs, because usually I read more than one previous reply. However, it's still better than nothing and I'm not sure which other options we have.

**Comment by k0shk0sh** [comment]
What version are you at? You should be using 2.5.3 which has the toggle & by default only 2-3 lines are showing and you have to toggle them. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment]
Likely, I'm on the right version:

![image](https://cloud.githubusercontent.com/assets/1074182/26573610/241b235c-4527-11e7-837a-61bb8fa4c252.png)

Now original messages takes half of the textbox (about 5 edit lines), while I might not necessarily need them. I liked large textbox and believe it's better to hide all the previous reply and add a "toggle" button instead.

**Comment by k0shk0sh** [comment]
@zvirja oops, your reply slipped away and just noticed it :'(, sorry about that. Once I'm done with revamping the PR apis, I'll focus on this.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment]
@k0shk0sh Happy that you will follow up on this and will solve this :blush: Thank you for the reply, appreciate that!

**Comment by k0shk0sh** [comment]
This has been done & now commenting is in place. while editing comment will remain in the Editor.
