### ISSUE TITLE
Add profile tab to bottomNavigation in tablet mode

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#439]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 I think my profile should be pinned.
( I am talking on the tablet on the side bar without having to open the sidebar)

I also think it would be nice if we can customize what screen we want to be the default upon opening the app

**Comment by k0shk0sh** [comment]
Why would you want it to be pinned? You could open it easy from drawer or even from app shortcut. 
Having that said, choosing what to open by default will never happen I guess, however you can use app shortcut to jump to some where.

**Comment by yakov116** [comment]
@k0shk0sh Shall i take my paint brush and show you what i mean!?!

I think you got the wrong picture (pun intended)

**Comment by k0shk0sh** [comment]
Owwh, 
Sorry, I just opened my eyes lol

**Comment by yakov116** [comment]
![image](https://cloud.githubusercontent.com/assets/16872793/25785791/ca00674c-3356-11e7-89c2-f620de50010c.png)

**Comment by yakov116** [comment]
Side note:

Can you add word next the pictures? (sorry it just does not look right)

**Comment by yakov116** [comment]
@k0shk0sh 

> or even from app shortcut
What is that?

**Comment by k0shk0sh** [comment]
@yakov116 not sure about that, I think its against material guidelines to do that. And I had to fork the lib & customize & maintain it myself which will be an extra work overload. PRs are accepted tho.

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/5bf4S8e.png)

**Comment by yakov116** [comment]
@k0shk0sh not a programmer yet...

But when i become one I will try my best to help out

**Comment by yakov116** [comment]
@k0shk0sh that is with any launcher?

**Comment by k0shk0sh** [comment]
Min API 25+

**Comment by yakov116** [comment]
ok thanks

**Comment by JediBurrell** [comment]
@k0shk0sh Some launchers support it back to API 21.

Nova Launcher works, not sure about others though.

**Comment by k0shk0sh** [comment]
@JediBurrell most of them do actually. But I'll try and add this to my list.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
@k0shk0sh
Oh, I've already added it, just haven't pushed it global yet.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
This issue has been appealed in 8c95153.
