### ISSUE TITLE
Missing ability to show the feed for a specific user

### ISSUE THREAD

**Issue by vvug** [k0shk0sh/FastHub#441]
Sometimes I want to check out what a specific user did lately. This is possible with ForkHub, where there is a "Following" pane showing the list of followed users, and I there can chose the user. In FastHub everything is shown together in the "Feeds" pane, and I found no way to restrict the feed to a specific user .

 - FastHub Version: Latest on f-droid
 - Android Version: 7.1.1

**Comment by k0shk0sh** [comment]
sounds cool, I'll about that if I should I add it to the profile page.

**Comment by yakov116** [comment]
@k0shk0sh adding to this idea. I think it would be great to have the activity of a specific repo too.

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
