### ISSUE TITLE
Can't see an easy way to switch accounts

### ISSUE THREAD

**Issue by amc90** [k0shk0sh/FastHub#443]
It doesn't seem that there is an easy way to switch accounts. It'd be nice to be able to switch between two usernames without having to regenerate the access code.

Thanks

**App Version: 2.0.1**

**OS Version: 23**

**Model: LGE-Nexus 5**

**Comment by yakov116** [comment]
I like that idea

**Comment by cozyplanes** [comment]
You mean `multiple accounts`, right?

**Comment by yakov116** [comment]
@cozyplanes yes

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 multiple accounts will be worked on very soon :) 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
