### ISSUE TITLE
Menu items should not have color accent

### ISSUE THREAD

**Issue by sepehr** [k0shk0sh/FastHub#445]
Menu items are way too blue that actually hurt the eyes. Would be great if it  had a neutral color or it was configurable.

_P. S. Thanks for developing this 🙏_

**Comment by k0shk0sh** [comment]
Hey, thanks for the report, did you mean the items in the navDrawer?

**Comment by sepehr** [comment]
Yup.

**Comment by Younes-L** [comment]
@sepehr light or dark theme ?
I think they look great using dark theme 😃👍

**Comment by sepehr** [comment]
Both. 

Too high contrast and not a Material design standard AFAIK.

**Comment by k0shk0sh** [comment]
this commit fixed by 694d3c6

**Comment by k0shk0sh** [comment]
They look better now I guess
![](http://i.imgur.com/AKbcZ7q.png)
![](http://i.imgur.com/Yf2mPDm.png)


_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sepehr** [comment]
Beautiful 😍

**Comment by k0shk0sh** [comment]
@sepehr scrollbars are by default following the accent color, so no hardcoding colors there. But for menu, yep, it was me who made their color to be accent :D

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
