### ISSUE TITLE
Show contributor/member badges

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#448]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Google-Pixel**

 When a contributor or member of a repo comments on something, the comment is badged with that.

![](http://i.imgur.com/6kzIaJS.png)

**Comment by k0shk0sh** [comment]
bad news, there is no way for me to know that unless if I call contributors api which then i'll have to load at least a minimum number of lets 50 to be safe to actually know if the user is contributor or no. thill slow down the loading as mentioned in #440 . i'm sorry about that.

**Comment by eygraber** [comment]
@k0shk0sh I think there are 2 ways to handle it

1. I didn't look at the implementation, but are you making all these requests in parallel or serial? If you're using retrofit and Rx you can use `zip` to make the requests in parallel and then merge the results together when they all complete. 

2. The other option would be what was suggested in #440 where you load the base stuff first, and then start loading the others. I think this way is best for loading times, even if it's a bit more complicated.

**Comment by k0shk0sh** [comment]
It's not really about complicity here but rather about user experience and as I said, there is no straight api to tell me if you are a contributor or not with that said, I'll have to go for all the contributors list and check them one by one and then only notify the list that currently presented. If there is an easy way to tell, I had done it by now. 
Btw: in PR API I'm abusing the heck outta of `zip`  lol. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
