### ISSUE TITLE
[Idea] add signature for the app

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#453]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 Maybe you can add a signature for the app so people can get to know this project.
Something like the attached picture 
![Xda](http://i.imgur.com/h1ese4W.png)

Please make sure there is an easy way to disable it 

1. Add a check box next to it for one time disable
2. Add in the settings to disable entirely

**Comment by k0shk0sh** [comment]
Check out my signature
> Sent from my Htc m8 using FastHub

![](http://i.imgur.com/mWpNvdd.png)

**Comment by k0shk0sh** [comment]
This is a test with a link in signature
Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)

**Comment by yakov116** [comment]
@k0shk0sh it's not italic!

**Comment by k0shk0sh** [comment]
@yakov116 here is italic for you :)

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh quick fix the space should not be part of the hyperlink

**Comment by yakov116** [comment]
@k0shk0sh quick fix the space should not be part of the hyperlink

**Comment by yakov116** [comment]
@k0shk0sh when you want to try something  out there a will there's a way

_Sent from my Unknown Android SDK built for x86 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
