### ISSUE TITLE
Forward in navigation history 

### ISSUE THREAD

**Issue by sepehr** [k0shk0sh/FastHub#457]
I go a few levels deep, hit back button and I'm lost if I want to get back to something I was reading, for example.

**Comment by JediBurrell** [comment]
Most apps don't have the capability to go forward. Once you click the back button, the Activity is finished and the information is released from memory.

_Sent from my LGE Nexus 5X using [FastHub for Android](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@sepehr I didn't get you, but isn't if you go forward and click hardware back button it should bring you to where you were, however clicking back button from toolbar it will navigate you to the context you are at backstack for example if you were in issue and click it, it will take you to its repo.

P.S: opening a link from outside FastHub will clear the whole backstack you were at. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sepehr** [comment]
Right. But you need to see the issue from a UX point of view rather than low level concepts, like activities, or how most other apps have been designed.

**Comment by k0shk0sh** [comment]
@sepehr could you please elaborate more? I didn't get your point. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sepehr** [comment]
@k0shk0sh Sorry for the late reply here.

Imagine you're reading an issue, you read a few posts, then there's a linked issue or pull request there, you click the link and start reading the second issue, then there's another one, you click and start reading the third...

Then, when you get back one or two levels and start reading the original issue you were reading at first. Something clicks, and you want to go forward (back in your mind history!) and see the third post you were reading to check something. You're lost unless you scroll a dozen posts up to find the linked issue.

It might seem to be a rare occasion, but come on! it's github, we're reading nested issues all the time.

**Comment by yakov116** [comment]
@sepehr you are talking about the feed? Or did I miss something?

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sepehr** [comment]
@yakov116 Not the feed, necessarily. Let me demonstrate the workflow using the browser:  

[Notice the case when you need to hit the forward button](http://i.imgur.com/xJjGHpZ.gifv)

**Comment by k0shk0sh** [comment]
@sepehr you made a point indeed but I'm just thinking this is what hardware button does, it navigates you back to where you were unless you clicked link from outside app then this will clear the whole thing and starts fresh FastHub. Are you using the toolbar back button or hardware back button? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sepehr** [comment]
@k0shk0sh No matter which one I use, the scenario will be the same as there is no **forward button** to go forward in FastHub history.

**Comment by k0shk0sh** [comment]
@sepehr owh, now I got you, well this isn't something that behaves like browser sorry about that tho, this will require alot of effort to do & I don't see any app actually does that, this is what makes mobile apps different from browsers tho. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sepehr** [comment]
OK, then. 

Actually, that's your fault! You made FastHub so great and useful that I want every feature that I have in my browser! 

Thanks ;)

**Comment by k0shk0sh** [comment]
@sepehr I realized that lately :p . But soon more features will come @JediBurrell working on alot of them. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
