### ISSUE TITLE
Long tap should hint

### ISSUE THREAD

**Issue by ildar** [k0shk0sh/FastHub#458]
The introductory hint set is fine, but according to Android practice, it should subj.

**Comment by JediBurrell** [comment]
@k0shk0sh
If you long tap an icon that used a hint, it would show the hint again.

I'm working on it.

_Sent from my LGE Nexus 5X using [FastHub for Android](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@JediBurrell  hmmm, this is so wrong I wish you didn't waste time on it. the icons should remain their accessibility which mean long press should actually tell the user what is this not showing a hint. If you look at foregroundImageView there will be a longClick that shows you the contentDescription which is mean for accessibility and to tell you what this icon is, if I missed some, simply adding contentDeacription in the xml layout would solve this. 

This will break accessibility longClick. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ildar** [comment]
This is somewhere in Google guidelines. And also seen in all Google apps,
check it out.

**Comment by JediBurrell** [comment]
I looked it up, but can't even find anything for hints.
If you could link it, that would be great.

**Comment by ildar** [comment]
Googled a bit and couldn't find either.
It's up to you whether to implement it. I don't mind if you close the
issue. Sorry if I'm irritating you guys.

**Comment by JediBurrell** [comment]
@ildar I wasn't irritated, and was going to implement it, but @k0shk0sh did bring up a pretty​ valid point; it would mess with accessibility, and for that reason I'll be closing this issue.

But don't be discouraged from reporting any other requests or issues if you come across any. Thank you for understanding the complications.

Cheers,
Jedi
