### ISSUE TITLE
Ui is ugly

### ISSUE THREAD

**Issue by ildar** [k0shk0sh/FastHub#459]
Markdown edit screen (which I'm in now):
- Top left button (right to left arrow): cancels the new issue.
- top right button (kinda "send" button): brings back to the previous screen.

Huh?

**Comment by yakov116** [comment]
Can you include a picture?

**Comment by ildar** [comment]
The picture is fine. The problem is that the buttons are assigned strange
to say the least.
The sequence is:
New issue, tap issue body area -> the Markdown editing view

**Comment by JediBurrell** [comment]
He means a screenshot.

_Sent from my LGE Nexus 5X using [FastHub for Android](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Ugly? Have you ever use Android before? Back button & send button. Aren't they obvious? Maybe I didn't get you but definitely the UI isn't ugly. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ildar** [comment]
I'm an Android user for years and seen many apps. That's why I write "ugly"
when I see the Back button doing Cancel and Send button doing Back.
It's not the view ugly but UX.

**Comment by k0shk0sh** [comment]
@ildar back button will take you back to where you were, send button will submit or return result to where you start the editor from, so I'm not sure about your argument here.
Can you enlighten me in what is your point ? I mean what do you expect them to do other than their behavior?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
I think he's saying that it should be a cancel button instead of a back button.
It's a valid point, but don't see why it's an issue.

**Comment by ildar** [comment]
Thanks.
It's not a critical issue, because nothing is crashing and anyone can get
used to the messed behavior. It's an issue because it's UX craziness.

**Comment by JediBurrell** [comment]
This issue has been appealed to in commit 2d57c54.
