### ISSUE TITLE
Subscribe one issue

### ISSUE THREAD

**Issue by ildar** [k0shk0sh/FastHub#460]
**App Version: 2.0.1**

I read an issue and want to subscribe to it. Where's the button?

**Comment by smichel17** [comment]
Related: It would also be nice if `Watching` appeared alongside `Created`, `Assigned`, and `Mentioned`, if this is possible.

**Comment by k0shk0sh** [comment]
Please search before submitting new issue to avoid duplicates and extra effort to explain again.

Thanks

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
