### ISSUE TITLE
Profile icon not updating

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#461]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 I updated my icon and the only way it refreshed was with a login log out.

**critical** bug!

**Comment by JediBurrell** [comment]
Isn't this just caching?

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@JediBurrell not really, I'm not updating user details on app start which I should :D . Its a bug

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
