### ISSUE TITLE
Translation: use "deletion" instead of "delete"

### ISSUE THREAD

**Issue by dedepete** [k0shk0sh/FastHub#462]
**App Version: 2.1.0**  
**OS Version: 23**  
**Model: Yota Devices Limited-YD201**  

Probably, there should be "deletion" instead of "delete" in commit's details.  
Presently the same word "delete" is used both in commit's details and gist's action menu, causing difficulties during the translation process.

Btw, there's also "deletion/s" in GitHub's web version.

**Comment by dedepete** [comment]
Also, it seems like there's no plurization for words Addition/Deletion, though there's a plural word Changes. So the usage of plural Additions/Deletions would be better.

**Comment by k0shk0sh** [comment]
@dedepete are you willing to do PR for this? I guess it would be easy for you? :D if not just let me and i'll do it right away

**Comment by dedepete** [comment]
Should I just update the content of `/src/main/res/values/strings.xml`?  
I'm not completely familiar with Android apps development, so it could be difficult for me to update the code.

**Comment by k0shk0sh** [comment]
@dedepete sorry about that, I'll do it from side because definitely it needs to be edited from code as well. Thanks

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
