### ISSUE TITLE
PR Review requests are displayed wrongly

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#465]
Review requests are displayed wrongly and information about reviewers is missing.
How it looks in app:
![screenshot_2017-05-11-20-31-23-603_com fastaccess github](https://cloud.githubusercontent.com/assets/1074182/25964123/719c479a-368c-11e7-8fb9-e49f6cdafc48.png)

How it looks in mobile version:
![screenshot_2017-05-11-20-32-03-813_com android chrome](https://cloud.githubusercontent.com/assets/1074182/25964154/8ceba130-368c-11e7-9d35-a7599abf58eb.png)

If you need link to PR, it's [here](https://github.com/AutoFixture/AutoFixture/pull/757).

Thanks.
---

 - FastHub Version: 2.1.0
 - Android Version: M
 - Phone Model: Xiaomi MI5

**Comment by k0shk0sh** [comment]
Hello @zvirja in today's release it has an attempt to fix this, please do reopen it if you find it still incorrect.

**Comment by zvirja** [comment]
@k0shk0sh Sorry for the delay. Unfortunately, this issue hasn't been fixed and is still reproducible (v 3.1.0):
![photo_2017-06-15_12-37-35](https://user-images.githubusercontent.com/1074182/27175588-44fc2c1c-51c8-11e7-81ac-462782654baa.jpg)

Also I found that it's not this PR specific and happens on other PRs as well 😞

**Comment by k0shk0sh** [comment]
Its complicated to be honest will try again

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment]
Thanks for the fix! Can confirm that everything looks fine after the recent update. 

I'll let you know if issue happens again.
