### ISSUE TITLE
Languages and ads

### ISSUE THREAD

**Issue by Raffaele74** [k0shk0sh/FastHub#466]
Hi.
FastHub is a so good app that it does not need any presentations. 
It is therefore easy to install, as it has happened to me, I do not remember how, without reading it. 
So I just found out that I can activate ads and change my language.
I think that would be better if you put in a pop up (with "don't show again") that reports these two things. 
I'm according to you about choice of using default English, but, if I download the app from the Italian store and by default it's not Italian, I think this option is not foreseen and I'm will not search it. 
The same for ads.
Cheers.

**Comment by k0shk0sh** [comment]
@JediBurell since you are doing the settings, what do you think of this?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
@k0shk0sh Are you sure you understand what he's saying?

Maybe I'm wrong, ( If so, @Raffaele74, do correct me. ) but I'm pretty sure he's saying on the initial launch of the app to show a dialog that lets you change these settings.

That seems like it would be a bit annoying for the user, especially if they have to click "Don't show again" to keep it from showing up.

**Comment by Raffaele74** [comment]
Yes. I say "make you shure users read it (user, you can set ads and language)" also if it is in Google Store presentation.

**Comment by k0shk0sh** [comment]
@Raffaele74 we will have to discuss this internally later, I can't really see the usage or benefits it will tell user. But definitely we will come up with something about it. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Raffaele74** [comment]
Ok. I setted ads on. I could do it before. Only this. Cheers.

**Comment by k0shk0sh** [comment]
@Raffaele74 thanks mate, ads currently doesn't work as admob haven't yet accept my appeal so it will be removed/replaced with something else in next release • Sunday • 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Raffaele74** [comment]
When it will happen, if it will happen, I was setted on. Thankyou for all.

**Comment by Younes-L** [comment]
What about a first launch introduction/experience ?

**Comment by yakov116** [comment]
@Younes-L there is a dismissed all

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
@yakov116 That's for the hints, this issue suggests a dialog on the first ( and if you don't click "don't show again", the next ) run(s).

**Comment by yakov116** [comment]
@JediBurrell I missed that explain 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@JediBurrell why can we not show right in the beginning "App language" from the login page

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
Well.. It's possible, but a dialog on start is generally bad practice.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@JediBurrell no on top of the login dialog

**Comment by JediBurrell** [comment]
@yakov116 This is possible, I'll see about it.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by arkon** [comment]
The app should just follow the system's language normally and allow the user to change it manually from the settings.

**Comment by JediBurrell** [comment]
@arkon That's the plan. I'm adding the dialog _if_ the app doesn't support the system language, otherwise it's hidden.

**Comment by JediBurrell** [comment]
This issue is appealed in bf7250e.
