### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Raffaele74** [k0shk0sh/FastHub#467]
Hi.

I know it's a strange iusse, but it's related to the fact that uniformity in aesthetic uniform makes devices more enjoyable.

In the dark theme you use black (for background), blue, gray, strong white (eg "Choose Language"), pale white (eg "Choose your preferred language").

In other dark themes they usually do not use strong white color and in my device there is even a command to replace strong white with cream when used as a background to not tire the sight.

Looking at others I will like a theme that uses cyan instead of strong white.

Very low priority, of course.

Cheers.

Huawei VNS-L31 Emui 4.1.1 Android 6.0

**Comment by JediBurrell** [comment]
Unless @k0shk0sh is opposed, I can change the pure whites to Material Grey 200.

**Comment by k0shk0sh** [comment]
Yea I'm fine with that

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Raffaele74** [comment]
You can do a 3th theme .... :-)

**Comment by JediBurrell** [comment]
This issue has been appealed in d364d4c.

**Comment by Younes-L** [comment]
@k0shk0sh omg amoled !! 😄👍🏼
