### ISSUE TITLE
Switching to organization account

### ISSUE THREAD

**Issue by dikiaap** [k0shk0sh/FastHub#47]
It would be great if you adding this feature. :)

**Comment by k0shk0sh** [comment]
well, due to not being able to test the functionality of this, I can't promise I'll make it anytime soon. anyone that wants to contribute to do so, I'll really appreciate it.

**Comment by eygraber** [comment]
@k0shk0sh I'm using with an organization account, and I'd be happy to help test. 

FWIW you can create an organization for free. It's only private repos that require paid plans.

**Comment by Rainer-Lang** [comment]
Info: https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/
