### ISSUE TITLE
Add (edited) when something is edited

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#470]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 Is this possible? 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
Test post.

**Comment by JediBurrell** [comment]
This issue has been appealed in 084cf9b.
