### ISSUE TITLE
The feed does not Bold or italic correctly

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#475]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 See picture
![The if is wrong](http://i.imgur.com/pP3rI9f.png)

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
This has been _partially_ fixed in 4d86e5d.
Will leave open.
