### ISSUE TITLE
Show soft keyboard when click on toolbar search icon

### ISSUE THREAD

**Issue by Rainer-Lang** [k0shk0sh/FastHub#476]
**App Version: 2.1.0**

**OS Version: 23**

**Model: LGE-Nexus 5**

Now: only search field in toolbar is opened/shown. User has to click once more in the search field to get the keyboard. 
Why not showing keyboard immediatelly?

**Comment by JediBurrell** [comment]
Are you on the latest commit, or version?

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Rainer-Lang** [comment]
Version 2.1.0

**Comment by JediBurrell** [comment]
Where?
It opens automatically for me.

**Comment by k0shk0sh** [comment]
@JediBurrell it does for me too. I'm not so sure Rainer is referring to wish exactly. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@JediBurrell @k0shk0sh 
![image](https://cloud.githubusercontent.com/assets/16872793/26035471/5f398832-389a-11e7-9d47-92a4a570e5d0.png)

**Comment by k0shk0sh** [comment]
@yakov116 this picture is different from what he is referring to. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Rainer-Lang** [comment]
![Search](http://i.imgur.com/ir5CVk2.png)

**Comment by yakov116** [comment]
@Rainer-Lang what did you click on before this? (which menu are you coming from)

**Comment by yakov116** [comment]
When i click search (From the main feed)
![image](https://cloud.githubusercontent.com/assets/16872793/26036438/b0b1fa1c-38ab-11e7-9bb7-a371b4d6cf32.png)

**Comment by Rainer-Lang** [comment]
When i click search from main feed - too.

**Comment by yakov116** [comment]
@Rainer-Lang could be that's the issue dono

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@Rainer-Lang ![From my tablet using BlackBerry keyboard ](http://i.imgur.com/yZYIi5k.png)


_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Rainer-Lang** [comment]
Changed to gboard, same.

**Comment by yakov116** [comment]
@Rainer-Lang interesting 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
Next version will fix.

**Comment by Rainer-Lang** [comment]
Yes it's ok thanks
