### ISSUE TITLE
Incorrect timestamp

### ISSUE THREAD

**Issue by alashow** [k0shk0sh/FastHub#48]
After submitting my last issue (#45), I noticed that it was showing time incorrectly. Just after opening an issue, it was showing "58 minutes ago," instead of 2 minutes ago.

[![image](https://dotjpg.co/00Uh.png)](https://dotjpg.co/00Uh.png)

**Comment by k0shk0sh** [comment]
it has been fixed in #20 it will be in next version but if you willing to test it out, please pm me.

**Comment by alashow** [comment]
No, I will just wait for the next release.

Offtopic:
I have a Nexus 5X, and I set Display size to small. FastHub UI looks like on tablets on my phone. Bottom bar left, dialog activities (new issue activity for example). And writing on dialogs is super inconvenient.

**Comment by k0shk0sh** [comment]
I'm not really sure about that tbh, I guess its something that out of my lead. i hope there is someone out there have a fix for ur issue.

**Comment by k0shk0sh** [comment]
@alashow I'v just released 1.0.5 could you confirm if this issue is fixed.

Thanks.
