### ISSUE TITLE
Add a backup setting 

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#482]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

1. Backup theme
2. Text color
3. Sig settings
4. Pinned repo's
5. Notification settings
6. Lang settings.

Also it should save to the SD card by default

If I forgot any, everyone is welcome to add

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
This issue has been appealed in ee6d21f.
