### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by szechyjs** [k0shk0sh/FastHub#483]
**App Version: 2.1.0**

**OS Version: 25**

**Model: LGE-Nexus 5X**

 I would like to be able to disable notifications. I follow way too many repos which causes this app to constantly spam my phone with notifications.

**Comment by k0shk0sh** [comment]
You could disable notifications from settings/notificatio interval & select turn off. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by szechyjs** [comment]
I would not consider that intuitive. Most apps settings have a parent notifications on/off toggle. This setting then enable/disables the notification related settings below it.

**Comment by k0shk0sh** [comment]
@szechyjs true, @JediBurell have revamped the settings screen. 
Maybe you could open a separate issue for this. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
