### ISSUE TITLE
Not able to make new repositories?

### ISSUE THREAD

**Issue by GlitchMasta47** [k0shk0sh/FastHub#484]
**App Version: 2.0.1**

**OS Version: 22**

**Model: **

 I can't seem to add a new repository under my account, maybe as a nice + button for that under Profile > Repositories

**Comment by yakov116** [comment]
@GlitchMasta47 how would one gain from being able to open a repo?
You are not able to add any files anyway.

**Comment by GlitchMasta47** [comment]
It adds more usability to the app, that way I could use it all the time fir anything GitHub.

**Comment by yakov116** [comment]
@GlitchMasta47 if you can think of a good reason to have a blank repo, maybe it can be implemented. As of now I don't see a reason for this.

Thanks for your feedback it's always good to hear new idea's.

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
@yakov116 Maybe bragging that you have 100+ repos in github ti a recruiter

**Comment by yakov116** [comment]
@cozyplanes for that github website in just what you are looking for

**Comment by cozyplanes** [comment]
@yakov116 Rephrase???? What do you mean??

**Comment by yakov116** [comment]
@cozyplanes  If you would like to brag and have a whole bunch of empty repo's github.com is your friend

**Comment by cozyplanes** [comment]
Oh yeah, like write `I have 100+ repos in GitHub.`
