### ISSUE TITLE
Add notification setting icon

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#486]
**App Version: 2.1.0**

**OS Version: 25**

**Model: unknown-Android SDK built for x86**

 From the notification menu

Add a gear icon

![image](https://cloud.githubusercontent.com/assets/16872793/26034964/11541db4-3893-11e7-9601-a087e541e35b.png)

_Sent from my Unknown Android SDK built for x86 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
Why?

**Comment by k0shk0sh** [comment]
@JediBurrell the drawer easily can be accessed from there

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
It gives direct access to its own settings. It very common to see that

**Comment by JediBurrell** [comment]
@yakov116 No, just drag from the side.
It's there, just no drawer button.

**Comment by yakov116** [comment]
@JediBurrell cool never knew that!
