### ISSUE TITLE
Show repo name when viewing issue

### ISSUE THREAD

**Issue by rugk** [k0shk0sh/FastHub#487]
- FastHub Version: 2.1.0
 - Android Version: 6/CM 13

Currently when I go to my notifications and tap on an issue to view it, I directly get to the issue/comment and then I wonder: "Uhh, which project is this issue actually about?"

There is just an repo/author indicator missing when viewing an issue. Otherwise I often tap these issues and then have to figure out what this is actually about.
In the notifications view this information is small, I almost never read it and I don't want to get back when I already tapped on an issue there as it is then read and going back is cumbersome as I need to swipe to the "all notifications" tab there and click on the issue again…
Actually not even when tapping on the (i) in the issue "header" I can see the repo name.

**Comment by JediBurrell** [comment]
This issue has been appealed in 2e5a784.
