### ISSUE TITLE
In tablet mode the pictures are not in line

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#488]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 See the picture below ![](http://i.imgur.com/oio1THU.png)

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
The picture should be under the words 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 are you sure you aren't adding new line between the text n image?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
@k0shk0sh I think that's it, the comment he's referring to has been edited, and it has an additional line.

**Comment by yakov116** [comment]
@JediBurrell @kosh no no

In tablet mode the pictures ends up being on the same line as the text

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
@yakov116 Well, if you did that, the user may  think it will add a line.

**Comment by yakov116** [comment]
Look at the below 

Ha it's a picture of a picture, but from that you should get the picture.
![Picture in a picture](http://i.imgur.com/NhzuPBz.png)


_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@JediBurrell ?

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
Oh, now I see.

**Comment by yakov116** [comment]
@JediBurrell you got the picture?
Lol

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
This issue has been fixed in 6d2ffe0.
