### ISSUE TITLE
View date and time of last commit in the list of branches

### ISSUE THREAD

**Issue by avently** [k0shk0sh/FastHub#491]
**App Version: 2.1.0**

**OS Version: 25**

Would be cool to have a possibility to view date and time of last update of branches. 
For example, tap on Commits. You can select a branch, but i can't see when this branches was updated. 
GitHub has this feature but I don't know how easy it is to implement in your app

**Comment by k0shk0sh** [comment]
Well, its possible but then requires us to `FlatMap` each branch during getting the `branches` and retrieve its full data to be able to show the time. https://developer.github.com/v3/repos/branches/#get-branch

**Comment by avently** [comment]
@k0shk0sh it's not a good option... Ok, thank you

**Comment by k0shk0sh** [comment]
It is, its just that it'll slow down listing branches tho. thanks for understanding.

**Comment by avently** [comment]
I think it's a bad idea to open a new issue for my next questions so I'll ask here. 
What does the timestamp "47 minutes ago" means? 
Is there a way to show a timestamp of last repo update at Pinned tab or it's hard to do because of the API? I think now I see a wrong timestamp in the list of pinned repos. 

![screenshot_20170516-143050](https://cloud.githubusercontent.com/assets/7953703/26104014/bba5ca9e-3a44-11e7-9d79-3b3eb34c2891.png)
