### ISSUE TITLE
Notification fixes

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#493]
**App Version: 2.1.0**

**OS Version: 25**

**Model: unknown-Android SDK built for x86**

**Comment by yakov116** [comment]
![image](https://cloud.githubusercontent.com/assets/16872793/26067362/f53daa2a-3967-11e7-918d-822eb72deb57.png)

- [ ] It should have an "s" "notifications"

- [ ] I can't figure out the style is every word capital or not?

![image](https://cloud.githubusercontent.com/assets/16872793/26067388/13a67a96-3968-11e7-9f96-7051a3bd0910.png)

- [ ] When disabled the other 3 should not show

**Comment by JediBurrell** [comment]
This issue has been appealed in d8611ef.
