### ISSUE TITLE
Tags not highlighted

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#494]
**App Version: 2.1.0**

**OS Version: 25**

**Model: unknown-Android SDK built for x86**

When selecting tags the icon does not follow the highlight theme

**Comment by yakov116** [comment]
Also the tags themselves dont follow the color scheme

**Comment by JediBurrell** [comment]
The first one is not a bug, I'm looking into ways to show indication of toggle, but that is not going to be it for reasons.

As for your second comment, could you please better explain yourself?
