### ISSUE TITLE
Add ability review changes in pull requests

### ISSUE THREAD

**Issue by sschuberth** [k0shk0sh/FastHub#496]
- FastHub Version: 2.1.0
 - Android Version: 6.0.1
 - Phone Model: Samsung Galaxy S6

I couldn't find a way to approve / comment on / request changes for PRs. It'd be nice to have that possibility in the app.

**Comment by JediBurrell** [comment]
All of these options are in the pencil.

![](https://lh3.googleusercontent.com/GcOVy6unARMpPLrkKxi29X12yFvOavHijJRLfMdwwkt78FBJDMRT6g6NiH8QZhfRA_OOS0zbsUsQDNIsKCWCQw4UPAYmzPoocqzhizbAOWU__N9J_RXAclYNMKuMkHJvX9jTibmmXxMbLK941SBedb_n9UWy57AOPiS1GZsFR6lpdA835IlUlftulv0lLrMITg256AmcaoPX6YPOWUTKnsYBunF6w1ntxC5HPnodWimBYsewPBaji7tZJjhB9ulo5PSsYpYGygp4JSR1fvLA8h-H37OvfbOh_NoHM3VnyVRNg08kxRrEh-7J06XiOpx8qRV1iZxu9C_XcAqqB6ANNAo3vXoE-vlWrFeXW1dobdsIfmDP0IB2irsPoFs8tovrkRh_bYGIxOAHDpG9mrt8e4qrVr6NbpxEbTBh9USd2QjLU-SopGd_Jw1SYKxivlsguYRfeV0ce9WQPpoysoYjIaFIQsrcOyvG8seznrYLsiQ42Js7fuLY_gMScQv72s97aGNd_Sa0qvfvq7kg6AWKylA3px-MYp5R_PAtr5h0si6IG2XTpqU5COlJbj4u6B6zkmljDpT5niwsQteO0jvns0-Z1pZYnkKosal05crqWOsYk1-V7UZIVQ=w406-h721-no)

Except for commenting, the FAB does that.

**Comment by k0shk0sh** [comment]
@sschuberth thanks for reporting, review prs isn't correctly implemented yet there is an open issue for it in #375 #429 , next version you'll be able to reply to reviews, interact to them via emojies and maybe after that there will a way to review the PRs.

**Comment by sschuberth** [comment]
Thanks for the info. Actually, I believe none of the linked issues is a strict duplicate of this issue:

- #323 is about making file comments, which is something you can do without starting a review.
- #375 is a duplicate of #323 (according to the author).
- #429 is about adding reviewers to PRs.

All of these are different from being able to do what is possible from this dialog in the web UI:

![2017-05-16_141040](https://cloud.githubusercontent.com/assets/349154/26105238/79f6d672-3a41-11e7-965b-ca6fa7fa9e0e.png)

**Comment by k0shk0sh** [comment]
@sschuberth Oops, please forgive my misunderstanding. I thought they are somehow related. I'll try and do that, but can't promise you anytime soon, but its in my list.

**Comment by k0shk0sh** [comment]
this should have been closed few days ago :D . I hope I didn't close another issue instead.

**Comment by sschuberth** [comment]
Thanks @k0shk0sh. Mind explaining where the feature to add review summary comments and approve reviews is hidden? I was unable to find it in the UI so far.

**Comment by yakov116** [comment]
@sschuberth its in the nightly builds.

Will be in the next public release too.
