### ISSUE TITLE
[Enhancement] Disable horizontal scrollbar for comment reactions

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#498]
**App Version: 2.1.0**

**OS Version: 25**

It just looks out of place.
![](https://puu.sh/vSaAs/27955c2767.png)

**Comment by JediBurrell** [comment]
It's there because there's too much content for the size of your display. Removing the scrolling would make parts of it inaccessible.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@JediBurrell what about moving the items a bit closer together? Or that won't work?

**Comment by k0shk0sh** [comment]
@yakov116 they will be so close to each other and won't look good without spacing. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh if you look at the picture he is a tiny bit off from the last one

**Comment by k0shk0sh** [comment]
@yakov116 he should because there is no enough space on his screen. So they have to go scrollable 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
Actually I noticed I used the wrong word; the ScrollView should stay there, no question, but the scrubber or whatever you call the blue thing at the bottom of the screenshot looks wrong.

**Comment by k0shk0sh** [comment]
@wasdennnoch owh the horizontal scrollbar. I'll see about that. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
This issue has been appealed in 01860ad.
