### ISSUE TITLE
Feature Request: Asciidoc  Rendering

### ISSUE THREAD

**Issue by EvanOman** [k0shk0sh/FastHub#501]
---

 - FastHub Version: 2.1.0
 - Android Version: Nougat
 - Phone Model: Galaxy S6 Active

Github Web renders [AsciiDoctor](http://asciidoctor.org/) source files (`.adoc`), is there any way to add this to this app?

**Comment by EvanOman** [comment]
[AsciidoctorJ](https://github.com/asciidoctor/asciidoctorj) looks like it handles the rendering on the JVM.

**Comment by k0shk0sh** [comment]
@EvanOman  good finding for the library, are there any other extension besides that for ascii? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by EvanOman** [comment]
I do not think so, obviously any extension would work but `.adoc` seems to be the convention. Some people use `.txt` but there isn't much we would be able to do for them.

Looking at [MarkdownInterceptorInterface.java](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/java/com/prettifier/pretty/callback/MarkDownInterceptorInterface.java) and [prettify.js](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/assets/highlight/js/prettify.js) maybe a JS rendering library would be  better? If that is the case then there is [asciidoctor.js](https://github.com/asciidoctor/asciidoctor.js/tree/master).

**Comment by k0shk0sh** [comment]
@EvanOman the class you referenced is meant to intercept touches coming from the webview that renders the HTML from a markdown extension. & The prettify has nothing to do with it meant for the rest of files, txt, .java, .php etc. I'll try and look around the possibilities about this and see what I can do about it. 
Thanks for the continuous advices

**Comment by k0shk0sh** [comment]
@EvanOman could you point me to any file in github that is written in that format?

**Comment by yakov116** [comment]
https://github.com/drinckes/testrepo/blob/master/README.adoc

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/NjpVbFN.png)


_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
