### ISSUE TITLE
[Bug] FastHub does not properly handle deleted users

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#502]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 When clicking on a profile that does not exist. FastHub loads a blank profile and a toast "not found" .

I think you can show just a toast "user not found"   

![](http://i.imgur.com/j79BEGH.png)

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
Could you link the profile here for testing?

**Comment by yakov116** [comment]
@JediBurrell https://github.com/USBhost/FIRE-ICE/commit/f563c5c14da15d736cc32077b7f4c332426235cf

The author of this commit 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
I guess in Presenter we should extend onError coming from the basePresenter and check for the error code to either finish/stay. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh I think anonymous (in public gists) should have an icon, right now its just blank.
What ever icon you put for deleted users use for this too.

**Comment by k0shk0sh** [comment]
This is a sneak peak

**Comment by k0shk0sh** [comment]
Again

**Comment by k0shk0sh** [comment]
Test @yakov116 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
