### ISSUE TITLE
3 taps are needed to reply in a PR/Issue, overflow button contains 1 action

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#503]
**App Version: 2.1.0**

**OS Version: 25**

**Model: htc-Nexus 9**

Previously it was 2, optimum would be 1 but I won't be asking that much 🤣
Plus on tablet UI there's plenty of room everywhere 

I suggest replacing the overflow menu by a reply button when the comment is not made by user, which the case MOST of the time (who replies to himself?)

**Comment by JediBurrell** [comment]
When was it two?

_I'll do something about it though._

**Comment by Younes-L** [comment]
@JediBurrell it was 2 a couple version ago, I think 1.9.2
I can only see _Reply_  button, and on message by user (me) there's an _Edit_  button
![](http://i.imgur.com/TJkFlpk.png)

**Comment by yakov116** [comment]
@JediBurrell he does not have share `yet`

**Comment by Younes-L** [comment]
Exactly, I'm not part of beta testing that's is happening behind the scenes   🤣

**Comment by yakov116** [comment]
@Younes-L you mean like the icon below?

![image](https://cloud.githubusercontent.com/assets/16872793/26215959/5c9fa582-3bd0-11e7-9998-d1cb147c9049.png)

**Comment by Younes-L** [comment]
@yakov116 not against text buttons but... In a medium mostly made of text, icons stand out 😃

I'm not complaining, I just thought going from a reply button (arrow) to a 3 dots menu is a regression

**Comment by k0shk0sh** [comment]
@Younes-L 
![Share](https://imgur.com/gallery/GebKw)

**Comment by Younes-L** [comment]
@k0shk0sh you can edit and delete my comments, so it makes sense to keep them ^^ I didn't think of that 😀
