### ISSUE TITLE
Image loading

### ISSUE THREAD

**Issue by deavmi** [k0shk0sh/FastHub#507]
**App Version: 2.1.0**

**OS Version: 22**

**Model: samsung-SM-N910F**

 I have a readme.Md file within a folder which resides in the root of the repo and it gets images in said directory in a directory called `img/` but they don't load in FastHub maybe the scheme yiu have going for URLs.

**Comment by k0shk0sh** [comment]
Could you point me to the repo.

**Comment by deavmi** [comment]
Will do. Here it is deavmi/HaikuDocs and take a look at a README.md in a directory.

**Comment by k0shk0sh** [comment]
@deavmi they don't seem to appear even in browser in GitHub. I cant see any directory for images as well, are you sure you pushed properly 😛

**Comment by deavmi** [comment]
Sure I did. Works in my browser.

**Comment by k0shk0sh** [comment]
@deavmi owwh, now I noticed that the readme is deep within the repo.

**Comment by deavmi** [comment]
Sorry that I wasn't clear.

**Comment by deavmi** [comment]
Using relative links also.
