### ISSUE TITLE
[Bug] Notification gets triggered every few seconds

### ISSUE THREAD

**Issue by DreierF** [k0shk0sh/FastHub#509]
Hey,

Since I switched to the Android O Beta (Nexus 6P) and new notification arrives it gets triggered every few seconds until I open the app.

Thanks

**Comment by k0shk0sh** [comment]
Could you go settings and make sure the current notification settings is selected, you might be hitting a bug with notification string resources are being translated.

**Comment by DreierF** [comment]
What setting are you referring to?
The notification sync interval is set to 30 min. I've set it to 20 and back to 30, but doesn't solve the issue.

**Comment by k0shk0sh** [comment]
well then, this sounds weird, i'll try it later on an emulator and see whats going on. thanks for reporting.

**Comment by DreierF** [comment]
I took a short video of the bug in action ;-) https://www.dropbox.com/s/9vam8ip3z7lxj54/Notifications.mp4?dl=0

**Comment by k0shk0sh** [comment]
@DreierF could you turn off the notifications & select again another interval. I guess I might know why.

**Comment by auscompgeek** [comment]
I'm also repeatedly receiving the same notification, except I keep receiving the notifications with the app open, and I'm on Android 5.0.

**Comment by DreierF** [comment]
@k0shk0sh I played around with the notification settings for the past few days, but it didn't resolve the issue

**Comment by yakov116** [comment]
@k0shk0sh any update on this

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
this bug was introduced when we migrated from firebase dispatcher to stock jobScheduler, since now we dropped support for fdroid, we could use firebase jobDispatcher without any hesitation.
