### ISSUE TITLE
Testing multiple mark as read.

### ISSUE THREAD

**Issue by FastAccess** [k0shk0sh/FastHub#51]

**Comment by FastAccess** [comment]
**Test....**

**Comment by FastAccess** [comment]
testing....

**Comment by FastAccess** [comment]
testttti

**Comment by FastAccess** [comment]
testing..

**Comment by FastAccess** [comment]
testing

**Comment by FastAccess** [comment]
testing

**Comment by FastAccess** [comment]
multi

**Comment by FastAccess** [comment]
testing dark theme from notification.

**Comment by FastAccess** [comment]
testing.

**Comment by FastAccess** [comment]
Testing.

**Comment by FastAccess** [comment]
@k0shk0sh

**Comment by FastAccess** [comment]
@k0shk0sh hello world?

**Comment by kutsan** [comment]
Jesus christ!

**Comment by kutsan** [comment]
This is test string for <3.

**Comment by kutsan** [comment]
This is test string for ultra <3

**Comment by k0shk0sh** [comment]
@kutsan hello there

**Comment by FastAccess** [comment]
testing testing.

**Comment by FastAccess** [comment]
testing again!

**Comment by FastAccess** [comment]
testing again & again.

**Comment by FastAccess** [comment]
Hello i'm testing.

**Comment by FastAccess** [comment]
Notification test!

**Comment by FastAccess** [comment]
Hello World.

**Comment by FastAccess** [comment]
hello world2.

**Comment by FastAccess** [comment]
comment.

**Comment by FastAccess** [comment]
hello world

**Comment by FastAccess** [comment]
heell

**Comment by FastAccess** [comment]
hello

**Comment by FastAccess** [comment]
commen

**Comment by FastAccess** [comment]
hellloooo

**Comment by FastAccess** [comment]
false/true

**Comment by FastAccess** [comment]
readonly

**Comment by FastAccess** [comment]
again

**Comment by FastAccess** [comment]
notify

**Comment by FastAccess** [comment]
last but not least.

**Comment by FastAccess** [comment]
comment test.

**Comment by FastAccess** [comment]
hello world

**Comment by FastAccess** [comment]
Testing

**Comment by FastAccess** [comment]
hello

**Comment by FastAccess** [comment]
Hello World 2

**Comment by FastAccess** [comment]
Hello world 3.

**Comment by k0shk0sh** [comment]
@kutsan hello world.

**Comment by FastAccess** [comment]
Hello World

**Comment by FastAccess** [comment]
another hello world

**Comment by FastAccess** [comment]
hello

**Comment by FastAccess** [comment]
third

**Comment by kutsan** [comment]
hi from curl with access token

**Comment by kutsan** [comment]
hello from github graphql API

**Comment by k0shk0sh** [comment]
@kutsan hello graphql nice meeting you lol 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@kutsan was wondering where you got lost. Must somewhere in that query encoded json!

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kutsan** [comment]
@yakov116 Surely, under the dirty GitHub API ocean. :D _now with GraphQL._

**Comment by yakov116** [comment]
@kutsan LOL 

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@kutsan @yakov116 is willing to accompany you please take him 🤣🤣🤣

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh the reactions work in case your wondering...

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh I got lost in v3 they added the `accept` header, I was never accepted. 

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 I know they do I did them hahaha. 😅😅😅

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
