### ISSUE TITLE
Cannot show more than 100 comments on an issue

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#511]
**App Version: 2.1.0**

**OS Version: 25**

**Model: samsung-kminilte**

 That's about all I can say.

**Comment by k0shk0sh** [comment]
Link to issue/Pr? Maximum is set by default to 200

**Comment by StanNL** [comment]
@k0shk0sh https://github.com/Spookcity/ROMS-G800F/issues/10

**Comment by StanNL** [comment]
I really like the new update! The app feels so complete now and I think you've implemented everything the GitHub API allows you to do.

However, this issue still hasn't been solved. Now, the app crashes when I scroll too far, which also isn't ideal

**Comment by StanNL** [comment]
It might be because I scroll too fast.

**Comment by StanNL** [comment]
But it also doesn't work when I don't

**Comment by k0shk0sh** [comment]
@StanNL that's weird, I have really test it well from the link you provided. Strange tho. I'll see what causes it and make release fixing it.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
It's fixed, sorry about that, it will be in today's release

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by StanNL** [comment]
@k0shk0sh That's awesome! This app is getting better and better every single week and I really like it! This version feels more refined than ever before. There are a few tiny things that can be improved though.

1. It would be nice to be able to change your signature.
2. I believe the "teal" accent colour isn't teal.
3. And lastly, the reply/quote text you recently added gets cut off on the top, not the bottom like you would expect (see screenshot).

![](http://i.imgur.com/RykWeyR.png)


_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by StanNL** [comment]
You used #00BEA5 for your "teal" color code, while it should be #009688 in my opinion, because this just looks like light blue. Not that it's a big issue, but feedback is always welcome, right?

**Comment by k0shk0sh** [comment]
for the teal, it should be #00796B according to material design colors.

**Comment by StanNL** [comment]
Well I meant # 00 96 88, but GitHub (the desktop version) somehow removed the leading zeros because it thought I was referring to an issue. # 00796B looks good as well, but like I said, you chose # 00BEA5, which is more like a light blue color.

**Comment by k0shk0sh** [comment]
I didn't do that part to be host, but I changed that now. i'm going to make a release in awhile. after the issue you opened.

**Comment by StanNL** [comment]
Great! Thanks

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by StanNL** [comment]
I think I'm going to use this as a 'question' topic if you don't mind. I was wondering if your notifications shouldn't appear in the feed tab.

Also, some of the bold 'action indicators' in the feed tab, aren't in correct English. I'm talking about things like _Person X created comment on issue Y_, when I talk about those action indicators. So here's a list of the indicators that need to be changed.

*  _Person X created comment on issue Y_ should be _Person X commented on issue Y_ 
* _Person X comment on commit Y_ should be _Person X comment**ed** on commit Y_ (mind the _ed_ behind comment that indicates a past tense)
* _Person X published released Y_ should be _Person X released Y_.

That's all of the "indicators" (I still don't know what to call them) that I could see. If you could link me to the file where these strings come from, I might be able to update them all. English isn't my native language either, but these just sound much better in my opinion.

**Comment by StanNL** [comment]
Another one: _Person X created comment on pull request Y_ should be _Person X commented on pull request Y_ 

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@StanNL Thanks for reporting. @k0shk0sh and I will one day (ahem) and go through all of them and correct them all. It is my understanding the we are taking the way github reports it in the api.

**Comment by StanNL** [comment]
@yakov116 I might be able to help you with that if necessary

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@StanNL you are welcome to join our special group

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
