### ISSUE TITLE
Feature Request: Proxy Support

### ISSUE THREAD

**Issue by gappleto97** [k0shk0sh/FastHub#513]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Huawei-Nexus 6P**

 It would be nice if I could proxy your app through Orbot without needing to use their VPN interface. When I do that my adblocker can't run.

**Comment by k0shk0sh** [comment]
I cant understand the issue there & how would FastHub effect your adblock?

**Comment by gappleto97** [comment]
So the most common rootless adblocks that I'm aware of all use the VPN API. The one I use specifically is DNS66, which redirects DNS requests for bad domains.

If you want to use Orbot for a TOR connection, there are two methods: setting a proxy to Orbot, or using Orbot in the VPN slot.

Because DNS66 is usually more useful in the VPN slot, that means I usually can't use Orbot unless an app integrates with them or offers proxy support.

**Comment by k0shk0sh** [comment]
@gappleto97 hmm, I'll see what effort this might take to integrate with tor. Can't promise anything soon tho. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gappleto97** [comment]
Here's the PR that added it to AntennaPod, if that helps.  https://github.com/AntennaPod/AntennaPod/pull/1732

**Comment by k0shk0sh** [comment]
sorry, but I have to close this issue as its out of my league.
