### ISSUE TITLE
Clicking a link to create an issue opens the "Submit feedback" screen

### ISSUE THREAD

**Issue by adueppen** [k0shk0sh/FastHub#515]
- FastHub Version: 2.1.0
 - Android Version: 7.1.2
 - Phone Model: Nexus 6P

Clicking on any link to create an issue in a repository and opening with FastHub will open the app's "Submit feedback" screen and will automatically fill the description field with the app and device info. Submitting it will create a new issue in the repository in the URL that was clicked.

Test page: [https://adueppen.github.io/fasthub-bug.html](https://adueppen.github.io/fasthub-bug.html)

It looks like the issue here is that the "Submit feedback" screen is a modification of the "Create Issue" screen so the wrong one is being opened for that link handler.

**Comment by k0shk0sh** [comment]
@adueppen it worked fine for me it just that it says submit feedback :D

**Comment by yakov116** [comment]
@k0shk0sh open the link in a browser and then open with fasthub 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 yea, the link will open in browser, and the issue posted in the repo that is tied to his, so I'm not sure what are you referring to?

**Comment by adueppen** [comment]
Something that I think could help the issue somewhat is displaying the name of the repo that the issue is being submitted to in the app bar as a subtitle. I can probably make a quick mockup tomorrow.

**Comment by k0shk0sh** [comment]
the subtitle now displayed as well.
