### ISSUE TITLE
Feature request : jump to top by tapping on the currently displayed tab

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#516]
**App Version: 2.1.0**

**OS Version: 25**

**Model: OnePlus-A0001**

 Alternatively just add fast scrolling everywhere...

**Comment by Apply55gx** [comment]
It would be great if it also would be possible to create an option for the app to use OrBot.

**Comment by k0shk0sh** [comment]
@Apply55gx orbot? What's that

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh a TOR project but i thing he posted it in the  wrong issue
