### ISSUE TITLE
UI fix needed

### ISSUE THREAD

**Issue by deavmi** [k0shk0sh/FastHub#518]
**App Version: 2.1.0**

**OS Version: 22**

**Model: samsung-SM-N910F**

 Wheb pressing the "i" for information button of a repository the mesaage that pops up should not have a cancel button.

**Comment by yakov116** [comment]
@deavmi this has been reported. Its not a simple fix and may take some time.

Thanks for your feedback

**Comment by deavmi** [comment]
That whole dialog needs a redesign. Maybe give it arguments to enable the Cancel or not.

**Comment by deavmi** [comment]
Maybe a function with an enum for the pop up type.

Enum MessageType
{

    Cancellable, Default;

}

**Comment by yakov116** [comment]
@deavmi I have been told by @jedi the following
I just haven't found a solution for that yet. May need to redo the way it's made. :confused:

**Comment by k0shk0sh** [comment]
@yakov116 that dialog is being used everywhere :D . Its an easy fix & doesn't effect behavior of app nor break it so its in my lowest priority, I'll do it tonight.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by deavmi** [comment]
Cool bru. BTW I love this app and its design - very sexy.
