### ISSUE TITLE
Assignees not loading for me

### ISSUE THREAD

**Issue by deavmi** [k0shk0sh/FastHub#519]
**App Version: 2.1.0**

**OS Version: 22**

**Model: samsung-SM-N910F**

 Assignees are not loading for my repi HaikuDocs.

**Comment by k0shk0sh** [comment]
https://github.com/k0shk0sh/FastHub/issues/436

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
