### ISSUE TITLE
GitHub's markdown Emoji's Support `Example: :heart:`

### ISSUE THREAD

**Issue by deavmi** [k0shk0sh/FastHub#521]
**App Version: 2.1.0**

**OS Version: 22**

**Model: samsung-SM-N910F**

 Add support for GitHub's emojis like in the profile description.

**Comment by yakov116** [comment]
@deavmi Where are you not seeing emoji's?

![image](https://cloud.githubusercontent.com/assets/16872793/26321755/1f745ed6-3ef6-11e7-843f-97dffa9b37d3.png)

**Comment by deavmi** [comment]
Not seeing the :heart:

**Comment by yakov116** [comment]
![image](https://cloud.githubusercontent.com/assets/16872793/26322261/251c8c3a-3ef8-11e7-9e9c-eb02a1a62941.png)

**Comment by deavmi** [comment]
Are you putting Unicode emojis in there?

I mean that I want to get `:heart:` which is part of GitHub's amrkdown I assume to render.

**Comment by yakov116** [comment]
@deavmi nope i'm using  `:heart:`

**Comment by yakov116** [comment]
Can you take a screenshot of what you see?

**Comment by deavmi** [comment]
Oh. Vreemd. I am using the FDroid version of the app? Are the builds behind?

**Comment by deavmi** [comment]
I literally just see the literal `:heart:`.

**Comment by yakov116** [comment]
OK if that's the case then this is fixed in the next build. It will be released in the next day or 2.

**Comment by deavmi** [comment]
Oh okay. Thanks. :)

**Comment by deavmi** [comment]
👍
