### ISSUE TITLE
Navigating back from viewing a commit in a PR opens repo home page instead of list of commits

### ISSUE THREAD

**Issue by phanimahesh** [k0shk0sh/FastHub#522]
**App Version: 2.1.0**

**OS Version: 24**

**Model: motorola-Moto G (5) Plus**

###  Steps to reproduce:
1. Open any repo
2. Go to PRs
3. Open any PR
4. Switch to commits tab
5. Tap on any commit
6. Try to navigate back using in app icon.

### What is expected?
App returns to viewing all commits in PR. Imagine wanting to review on the go. Any other behaviour would make it very inconvenient not to mention unintuitive.

### What happens?
App navigates to home page of the repo.  
###

**Comment by yakov116** [comment]
@phanimahesh I am only having the issue when using the app back icon

**Comment by phanimahesh** [comment]
Android back key works? Let me verify again. Brb

**Comment by phanimahesh** [comment]
Yep. Backkey works. Edited issue to update.

Also, after opening a commit, first tab should read changes or files instead of commits.

**Comment by yakov116** [comment]
@phanimahesh this a know issue in FastHub. For now try to only use the android back key.

**Comment by phanimahesh** [comment]
Thanks. Works for me for now. What about the tab label btw? Should I open a
new issue or pr?

**Comment by k0shk0sh** [comment]
@yakov116 it's not a known issue nor a bug, its how Android framework behaves & its called `navigateUp` pressing that button will always navigate you to the proper way, while pressing home back button which is called `back` will navigate you accordingly to where you were. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh I take that back "Know issue in android"

**Comment by k0shk0sh** [comment]
@phanimahesh if you willing to PR that would be great, if you think that it might take time & you want it by tomorrows release, please open an issue for it. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by phanimahesh** [comment]
I assume it can be overridden? Current behaviour appears counterintuitive
for me. Can this be reconsidered?

**Comment by k0shk0sh** [comment]
@phanimahesh well it definitely can be overridden, but that would be an issue for people that get used to it, in fact, it wasn't implemented at first but then few issues opened asking for it which I think its the right way :). 
Clicking device back button if you need to back where you were, click navigateUp if for example you were in an issue, but you wanna go to its repo/ issue list assuming you opened the issue from anywhere but it's repo. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by phanimahesh** [comment]
If other users are used to it I guess I'll have to get used to using back
key then. Thanks for the explanation.
