### ISSUE TITLE
Using H1-H3 shortcuts when writing issues inserts hashes at cursor instead of beginning of line

### ISSUE THREAD

**Issue by phanimahesh** [k0shk0sh/FastHub#523]
**App Version: 2.1.0**

**OS Version: 24**

**Model: motorola-Moto G (5) Plus**

 Title says it all

**Comment by yakov116** [comment]
@phanimahesh Are you seeing somthing different than below?
![2017-05-23_12-27-01](https://cloud.githubusercontent.com/assets/16872793/26364713/371619f4-3fb3-11e7-8055-331160d0c8b5.gif)

**Comment by phanimahesh** [comment]
Let me explain.
Type some stuff.
Then remember to mark one line as heading
Tap on a line above. Somewhere in the middle.
Tap h1 etc

I expect it to insert hashes at beginning of line. They are instead inserted at cursor, breaking the line oddly.

**Comment by yakov116** [comment]
@phanimahesh I now see the issue. But this is normal practise when using a shortcut in middle of a line

See below for my example

![2017-05-23_12-40-21](https://cloud.githubusercontent.com/assets/16872793/26365244/03f57e1e-3fb5-11e7-8cf8-08833d44b04d.gif)

**Comment by k0shk0sh** [comment]
Didn't get you much, but isn't when you put the cursor on a word for example, pressing the header will actually break that line into new one which is the right behavior.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by phanimahesh** [comment]
Ah. Did not notice that. Never used shortcuts on web, they required mouse to be worth the trouble.

Closing then.

**Comment by k0shk0sh** [comment]
@phanimahesh thanks for being understandable. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by phanimahesh** [comment]
I maintained a once popular project so I understand the effort it takes. I
like the app and the fact that ads are opt in in settings and not even
nagged about on first run. Thanks for your efforts.
