### ISSUE TITLE
Notification interval == off doesn't save from notifications

### ISSUE THREAD

**Issue by ildar** [k0shk0sh/FastHub#530]
**App Version: 2.1.0**

**OS Version: 23**

I suffer from https://github.com/k0shk0sh/FastHub/issues/483 . I have interval set to off. But that doesn't turn off notifications and I get a lot of them.
Please make the big OFF switch for notifications.

**Comment by yakov116** [comment]
@ildar #483 was fixed today and will be in the new release. We hope it  should be out tomorrow and this will fix your issue .

Thanks for your feedback
