### ISSUE TITLE
Add 1 - 3 hour Notification timings 

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#533]
@k0shk0sh and there is no default selected when just turning them on. I think that it's taking still the default value of "turn off"

**Comment by chamini2** [comment]
What about setting a [number picker](https://developer.android.com/reference/android/widget/NumberPicker.html) for the number and a select for `hours` or `minutes`

**Comment by yakov116** [comment]
@chamini2 its coming in 3.0
