### ISSUE TITLE
More "iusses"

### ISSUE THREAD

**Issue by Raffaele74** [k0shk0sh/FastHub#536]
I can view iusses opened (by me) and closed. If I search for iusses opened from others (and I answered) I cannot.

---

 - FastHub Version: Browser
 - Android Version: 6.0
 - Phone Model: VNS L31

**Comment by k0shk0sh** [comment]
How would you search for that? you could see them from mentioned if they don't appear there could you point me how you could do that in GitHub?

**Comment by Raffaele74** [comment]
I did understand well.
This is project
https://github.com/carat-project/carat-android
It is iusses #2

**Comment by Raffaele74** [comment]
More. It was a child from a previous pull request.

**Comment by k0shk0sh** [comment]
I couldn't really get you. 

This is how I understand your question.

1- you can search for issues closed & opened by you. (definitely)
2- I can't search for issues answered by me. (how would you do that in GitHub?) as far as I know there is no way you could do that & haven't even seen that option anywhere in github.
3- You can search for issues by others, you just have to type their names in the search box within the Repo/Issue Tab/ Search.

Please let me know if this is your question.

**Comment by Raffaele74** [comment]
No. But solved searching iusses by "Carat". Very fine. Thanks you very much.
