### ISSUE TITLE
Adding info dialog for long press on issue

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#538]
**App Version: 2.1.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 In a follow up to #535 it would be nice to have the following.

add that it should show a dialog with info 
1 author 
2. Time created 
3. Last edited
4. Current labels 
5. Milestone's added

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Hello this is a test from issue details popup.

**Comment by k0shk0sh** [comment]
Hello this is a test
