### ISSUE TITLE
Bug in syntax highlighting for Haskell

### ISSUE THREAD

**Issue by andrew-lei** [k0shk0sh/FastHub#539]
Apostrophes, which are a valid part of function/variable names in Haskell, are interpreted as quotes, so parts between apostrophes are highlighted as strings.

**App Version: 2.1.0**

**OS Version: 25**

**Model: Huawei-Nexus 6P**

**Comment by k0shk0sh** [comment]
Hello Andrew, thanks for reporting, could you provide a screenshot with the issue you described.

**Comment by andrew-lei** [comment]
Note the blue lines.

![Screenshot](http://i.imgur.com/v9588mK.png)

**Comment by SitiSchu** [comment]
![screenshot_20170606-113019](https://cloud.githubusercontent.com/assets/18517178/26822950/1be1120c-4aac-11e7-9b31-e0a39a6b7238.png)

An example where it is more obvious.

https://github.com/ghc/ghc/blob/master/ghc/Main.hs

**Comment by k0shk0sh** [comment]
@SitiSchu thanks for sharing that out, i'll look into it and can't promise much as i'm using Google prettify code library to highlight the code, i'll try and update the library and see how.
