### ISSUE TITLE
Dark theme 

### ISSUE THREAD

**Issue by xdk78** [k0shk0sh/FastHub#54]
Hey, great app. Could you add dark theme?

**Comment by k0shk0sh** [comment]
I hope I can make it before Sunday release but it will be in my final list of improvements and feature otherwise it might be released in 1.0.6 in the next weekend.

**Comment by PDDStudio** [comment]
Is there something new relating dark/night mode? Otherwise I would like to work on this ☺️

**Comment by k0shk0sh** [comment]
@PDDStudio nope, nothing have been done on it so far, it will be great if you could make it so I can focus more on bugs. could you also join our slack channel to discuss it more. Thanks

**Comment by PDDStudio** [comment]
@k0shk0sh yeah sure, sounds good. I'll join the slack channel - everything else can be discussed there then. ☺️
