### ISSUE TITLE
Crash when tapping on open source libraries.

### ISSUE THREAD

**Issue by dedepete** [k0shk0sh/FastHub#540]
**App Version: 2.5.0**  
**OS Version: 23**  
**Model: Yota Devices Limited-YD201**

**Comment by k0shk0sh** [comment]
Hmm, not with me tho. strange.

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/85OxOtb.png)

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dedepete** [comment]
I'll upload a video when I get home.

**Comment by k0shk0sh** [comment]
@dedepete sure, i'll wait for that :)

**Comment by anastr** [comment]
the same crash when open repo, issue ...
**OS 21**.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fastaccess.github/com.fastaccess.ui.modules.repos.RepoPagerActivity}: android.view.InflateException: Binary XML file line #95: Error inflating class com.fastaccess.ui.widgets.ForegroundImageView
...
at android.app.ActivityThread.main(ActivityThread.java:5576)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: android.view.InflateException: Binary XML file line #95: Error inflating class com.fastaccess.ui.widgets.ForegroundImageView

...

Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_label.xml from drawable resource ID #0x7f0200cb
...
```

**Comment by k0shk0sh** [comment]
@anastr thank you man, I hate android 21, :'( I fixed that internally & expect an update within an hour or two.

**Comment by k0shk0sh** [comment]
@anastr  @dedepete  do you guys confirm that it's fixed in `2.5.1` ? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by anastr** [comment]
Yes it is 👍 @k0shk0sh  good work.

_Sent from my Lenovo TB3-710F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dedepete** [comment]
@k0shk0sh yep, works perfectly.

_Отправлено с моего Yota Devices Limited YD201 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
