### ISSUE TITLE
Design: Match language colors

### ISSUE THREAD

**Issue by mistermantas** [k0shk0sh/FastHub#541]
This feature request is about the language colors which you can see when viewing a list of repositories, like in a profile.

The current colors are random. This is mildly annoying. It’d be neat to have all of the colors match just like on the GitHub website. [There's a good list](https://github.com/ozh/github-colors) of all the colors, so you could refer to that when solving this issue.

If there was some free time, I'm sure someone would be open to copying over the hex values. At some point.

**Comment by mistermantas** [comment]
Did you really close this issue in 20 minutes? 😂 That's amazing.

**Comment by k0shk0sh** [comment]
:p
