### ISSUE TITLE
Redundant about views

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#542]
**App Version: 2.5.0**

**OS Version: 25**

**Model: asus-Nexus 7**

 There's an about view in settings and one from the drawer which has more info. They should be merged into one.

**Comment by yakov116** [comment]
@arkon was supposed to be done...  one of the many little things.


_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
