### ISSUE TITLE
Truncate issue and comment date

### ISSUE THREAD

**Issue by mistermantas** [k0shk0sh/FastHub#543]
`25 seconds ago` can easily be turned into `25s ago` or even `25s`.

![Example](http://i.imgur.com/Jg66Yuw.png)

**Comment by k0shk0sh** [comment]
small density?

**Comment by mistermantas** [comment]
Just change the long date format to a shorter one so I can read my username. ✌️

**Comment by k0shk0sh** [comment]
hmmm, for the emoji, i see that you used android emoji yet i'm seeing my log something like

` ✌️` that space is what I guess causing the prob

**Comment by mistermantas** [comment]
Discuss in #545 for the emoji thing.
