### ISSUE TITLE
2 emoji show up as 1

### ISSUE THREAD

**Issue by mistermantas** [k0shk0sh/FastHub#545]
[In the app](http://i.imgur.com/q0KUXOu.png)

[On the web](http://i.imgur.com/ij4rFUN.png)

**Comment by k0shk0sh** [comment]
✌️😁😋🤣😉😛👏

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
somehow the peace sign only having this problem ✌ ✌️  as you see from the image below
![screen shot 2017-05-28 at 9 18 27 am](https://cloud.githubusercontent.com/assets/960767/26525307/a8b4afcc-4386-11e7-94c6-25092018d511.png)
