### ISSUE TITLE
Link not opening in fasthub

### ISSUE THREAD

**Issue by kinglau66** [k0shk0sh/FastHub#546]
**App Version: 2.5.0**

**OS Version: 25**

**Model: OnePlus-ONEPLUS A3003**

 Fasthub cannot open the github link. It work previously, before Google play updates.

**Comment by k0shk0sh** [comment]
What link is it? Could you point me to it?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kinglau66** [comment]
https://github.com/chaosbot/Chaos

I cannot open this repo link. But replies link such as the current link can be shown properly. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
thanks was waiting for your reply to make new release :)

**Comment by k0shk0sh** [comment]
@kinglau66 please update to 2.5.1

**Comment by kinglau66** [comment]
@k0shk0sh thx, works perfectly now.
