### ISSUE TITLE
Contribution's box lags.

### ISSUE THREAD

**Issue by GrimDevelopment** [k0shk0sh/FastHub#547]
**App Version: 2.5.1**

**OS Version: 25**

**Model: samsung-SM-N910P**

 When swiping left or right to and from the contribution's box via the profile page the app would lag.

**Comment by k0shk0sh** [comment]
Yup, I'm aware of that as it's too much data to render especially if you are seeing someone's profile which has many contribution. I'll see what I can do about the drawing of the view & see if it could be improved

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by GrimDevelopment** [comment]
@k0shk0sh I am not to familiar with development as I am new but would something like this be helpful?

http://i.imgur.com/07GLGZs.png
