### ISSUE TITLE
Show multiple build statuses

### ISSUE THREAD

**Issue by chamini2** [k0shk0sh/FastHub#549]
**App Version: 2.5.1**

**OS Version: 25**

**Model: LGE-Nexus 5X**

 Now we only see __one__ build output, I propose to show a summary (3 out of 4 passed) and make it clickable to show details.

**Comment by k0shk0sh** [comment]
Link to pr to test with

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chamini2** [comment]
Can't, it's in a private repository. Let me check if I find another one.

**Comment by chamini2** [comment]
Ok, found one:

https://github.com/greenkeeperio/greenkeeper/pull/433

Notice that the first commit of the pull request has three builds and the others have two builds.
