### ISSUE TITLE
Add filter to news/events

### ISSUE THREAD

**Issue by RSDamasceno** [k0shk0sh/FastHub#55]
It's possible add filters to news/events like discontinued Gitskarios? <br /><br />https://github.com/gitskarios/Gitskarios<br /><br />

**Comment by k0shk0sh** [comment]
sure so, but can't promise that with specific time. all I can say, maybe in v1.1.0

**Comment by RSDamasceno** [comment]
Any ETA about this, since it was not released on today's version?

Congratulations on the excellent work!

**Comment by k0shk0sh** [comment]
@RSDamasceno  Thanks for your support,

According to the api, they don't have such thing @alorma actually has done it manually if i'm correct, for me to do this right now will require an extra work, I'm planning to change a bit of the app structure, once I started that, I'll definitely include it

**Comment by RSDamasceno** [comment]
It's all right! I will wait anxiously for this day! ;)

**Comment by k0shk0sh** [comment]
Cool, Thanks for your understanding. I really appreciate it.

**Comment by RSDamasceno** [comment]
I did not find the filters in version 2.1.0. Are they there or have not they been implemented yet?

**Comment by k0shk0sh** [comment]
Shamelessly replying **not yet implemented**

**Comment by RSDamasceno** [comment]
Hey, man ... I'm sorry to resurrect this request.
Did you give up on implementing this?
Thank you.

**Comment by k0shk0sh** [comment]
No official API so honestly I'm not interested 🤷‍♂️
