### ISSUE TITLE
Release notes in About

### ISSUE THREAD

**Issue by StevenMagdy** [k0shk0sh/FastHub#550]
**App Version: 2.5.1**

**OS Version: 21**

**Model: samsung-SM-N900**

You could show the release notes in About when Version is clicked. 

_Sent from my Samsung SM-N900 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@StevenMagdy no this will show if you have the latest version. There is a change log tab, go to setting and they about. (We know it's double it will be fixed soon)

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
