### ISSUE TITLE
Order issues by description "thumbs up"

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#552]
I think it would be cool if we could order the issues by the amount of thumbs up the description received, so that we can see what the most "requested" features are.

**Comment by k0shk0sh** [comment]
I have added this however, it isn't really working,

try it out by yourself.

https://api.github.com/search/issues?q=repo:k0shk0sh/FastHub%20is:open%20is:issue%20%20sort:%22reactions-+1-desc%22

**Comment by eygraber** [comment]
@k0shk0sh this link seems to work - [](https://api.github.com/search/issues?q=repo:k0shk0sh/FastHub%20is:open%20is:issue%20%20sort:"reactions-%2B1-desc)

Side note - tapping that link in FastHub shows an error.

**Comment by k0shk0sh** [comment]
@eygraber weird as I'm not handling such scheme, 
It doesn't really work tho, compare it to the GitHub one matter of fact, its there in 2.5.3 give it a shot and you'll see what I'm talking about.

About the link I will see what's going on. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
@k0shk0sh I posted a different link than you (changed "+1" to "%2B1") and it returns the issues in the proper sorted order.

**Comment by k0shk0sh** [comment]
@eygraber nicee, so that's the problem? Could you pass me the other encoded values for each one of them :p. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
@k0shk0sh it's not really an encoded value for the emoji. It's that the "+" needed to be url encoded.

**Comment by k0shk0sh** [comment]
@eygraber yup, that's what I was referring to, strangely that I have set it to `encoded=true` yet it seems needs to be manually encoded. Will fix that in next release

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
