### ISSUE TITLE
Add a setting that permanently hides the signature and formatting bar

### ISSUE THREAD

**Issue by mistermantas** [k0shk0sh/FastHub#554]
**App Version: 2.5.1**

The signature button takes up quite a bit of screen space as shown in this [screenshot](http://i.imgur.com/10B86Gg.png).

Perhaps it would be better to move it to the settings to permanently hide? Same goes for the formatting bar.

**Comment by k0shk0sh** [comment]
There is an option in settings to remove it

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mistermantas** [comment]
Apologies!

**Comment by k0shk0sh** [comment]
missed the markdown bar part, I don't think that will be removed as its part of that screen, otherwise I just let you comment from place. it is going to remain there tho 😀
