### ISSUE TITLE
Let the user change the signature

### ISSUE THREAD

**Issue by mistermantas** [k0shk0sh/FastHub#555]
**App Version: 2.5.1**

“Sent from my Samsung SM-G930F using FastHub” is not a very appealing signature, I mean, do you know the model name by memory? That's an S7, but I wouldn't be able to guess.

This is a better “signature”:

> John Smith
> Example, Inc.
> Support Specialist

But, you can't have that on FastHub yet. Unless I missed some setting…

**Comment by k0shk0sh** [comment]
This isn't what the signature here means. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mistermantas** [comment]
Sure, but it would still be useful.

**Comment by k0shk0sh** [comment]
@mistermantas if you were writing an email to your clients then it definitely is 😝

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mistermantas** [comment]
Some companies do actually setup issue repositories, though, like Microsoft for their Bash on Windows program.

**Comment by StanNL** [comment]
Yeah I don't like his signature either, but it would be a good idea to be able to change it, anyway. SM-G800F or kminilte isn't a nice device name either, so it would be nice to have an option to change it.

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@StanNL I think we should let the app mature a little. Maybe later we will come back to this.

**Comment by mistermantas** [comment]
If you ask me, the app is fairly mature. And honestly, if maturity is the problem, maybe the signatures shouldn't have been a feature in the first place. Don't add half baked features… They're basically useless right now anyway.

**Comment by k0shk0sh** [comment]
@mistermantas I guess what yanki meant to say, is that this isn't going to be change anytime soon but in a bit nice way. 

P.S: if you don't like it, you always can disable it :) 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@mistermantas He is right i should have said "Let the app _age_ a little bit."

**Comment by mistermantas** [comment]
@k0shk0sh Yup, I got the gesture. I did disable it.

**Comment by k0shk0sh** [comment]
@mistermantas cool, no hard feelings there nor forcing anyone to use it :) 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
