### ISSUE TITLE
not responding followed by crashing 

### ISSUE THREAD

**Issue by karthikbhyresh** [k0shk0sh/FastHub#557]
**App Version: 2.5.1**

**OS Version: 22**

**Model: Micromax-Micromax E485**

 After this recent update the app is showing not responding followed by crashing whenever I try to pin a repository.. sometimes even when staring. It pauses at the shading animation and restarts. This cycle continues several times before it is finally pinned. pls fix asap. 

_Sent from my Micromax E485 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Yup, figured this out and has been fixed

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
