### ISSUE TITLE
Wrong tooltips in markdown editor

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#559]
**App Version: 2.5.1**

**OS Version: 25**

**Model: samsung-GT-I9305**

 Some tooltops when long pressing the editor toolbar are wrong (copy-paste cone wrong :p)

Actual item - its tooltip:  
Checked checkbox - Numbered list  
Unchecked checkbox - Numbered list  
Horizontal divider - Header

**Comment by k0shk0sh** [comment]
:p
