### ISSUE TITLE
Shows notifications even though notifications are disabled

### ISSUE THREAD

**Issue by jochenberger** [k0shk0sh/FastHub#561]
**App Version: 2.5.1**

**OS Version: 25**

**Model: LGE-Nexus 5X**

 

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Rainer-Lang** [comment]
Same here.
Turning on/off - doesn't change anything.
