### ISSUE TITLE
Gists link files don't work 

### ISSUE THREAD

**Issue by camillo777** [k0shk0sh/FastHub#563]
**App Version: 2.5.1**

**OS Version: 23**

**Model: samsung-SM-N910F**

 For example this link:

https://gist.github.com/bojzi/67ed55b16cb60b5d36ad/raw/030199f2e7ea115a779300a96d50ae0150af530a/package.json

Opens FastHub with a "not found" error. 

![Not found]()

**Comment by yakov116** [comment]
https://gist.github.com/bojzi/67ed55b16cb60b5d36ad/raw/030199f2e7ea115a779300a96d50ae0150af530a
