### ISSUE TITLE
Suggestion: Add more color to the side menu

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#564]
**App Version: 2.5.1**

**OS Version: 25**

**Model: samsung-kminilte**

The side menu icons (next to home etc) are dark grey now, but I think they should have the same accent colour that the user those in the settings menu. It would look a lot more colourful and way better if you would implement the accent colour there.

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@StanNL It was like this before and people complained that it was to hard to see. So it was changed to a set color.
Allowing the user to set just the side bar color will end up being too many options and will only confuse people and also make thing harder to maintain.

Thank you for all your feedback.

**Comment by StanNL** [comment]
@yakov116 Hmm I guess you're right. Or you could just add a switch that says "add accented side menu icon colors" so it won't get too confusing. Anyway, you can't please everyone, right?

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
