### ISSUE TITLE
Back vs Up Navigation

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#568]
If I open FastHub from a link in another app, pressing back should take me back to that other app, vs up which takes me to the "logical" previous screen in FastHub. 

Currently both back and up function like up should.

https://developer.android.com/design/patterns/navigation.html

**Comment by eygraber** [comment]
@k0shk0sh this started happening again (version 3.2.0).

**Comment by k0shk0sh** [comment]
@eygraber nothing happened in 3.2.0 it still behaves normally. You could be more specific and tell me what is going?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
@k0shk0sh here are the steps:

1. Open a GitHub link from chrome using FastHub
2. Press home
3. Open a GitHub link from chrome using FastHub
4. Press home
5. Open a GitHub link from an email using FastHub
6. Press back (device)
7. Get taken to the page from step 3
8. Press back (device)
9. Get taken to the page from step 1

**Comment by k0shk0sh** [comment]
@eygraber well, can't you see that you doing something wrong? I mean if you open link from chrome FastHub should replace its process and be on top of it, I'm not sure how you open another chrome and maybe that's why this happen? Could you confirm that it happens from any other apps? 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
@k0shk0sh that's not the case. I just confirmed from Inbox and Gmail as well. 

Obviously my example was simplified. What usually happens is I open a link from chrome, press home, and then a few hours later open a link from an email. I press back expecting to go back to the email client, but instead I go back to the link I opened a few hors earlier.

**Comment by k0shk0sh** [comment]
Hmm, that's weird. How can I make a proper test on this? Wait few hours?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
@k0shk0sh that's just my typical flow. If you follow the first repro I posted it should be instantaneous.

**Comment by k0shk0sh** [comment]
@eygraber its strange, it seems Google apps starts any other app in a different process which that's why you seeing this behavior, you can try for example open a link from any other apps than Google, slack for example, you'll see that FastHub is on top and you can't back slack without pressing back from FastHub. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
@k0shk0sh I think it's up to the app to decide if they should open the intent in a new task or not. Google probably does it that way as a best practice. 

Personally, I agree with how Google does it.

**Comment by eygraber** [comment]
Have you looked into [launch_mode](https://inthecheesefactory.com/blog/understand-android-activity-launchmode/en)?

**Comment by k0shk0sh** [comment]
@eygraber could you elaborate on why you think Google following `best practice` ? and just not a google way of saying i'm doing my own thing? also, a link will be great. 


`launch_mode` ? one instance of FastHub? I imagine how people will go nuts when they click a link or anything within the app will override their current instance.

**Comment by eygraber** [comment]
@k0shk0sh I think the reason they did this is:

1. I get an email with a link to an article I want to read
2. I tap the link which opens in my browser
3. I realize the article is really long, and I want to read it later
4. I press home and go back to reading my emails

If the article blocked me from going back to my email client, I'd get pretty pissed 😎

For `launch_mode` I actually meant something else: [documents](https://developer.android.com/guide/components/activities/recents.html) (so much random Android knowledge bouncing around in my head I sometimes forget what's what).

If `SchemeParser` starts activities in a new document, there should be separate entries for each "instance" in the recents menu, and I could then press back and have it behave as expected.

**Comment by k0shk0sh** [comment]
PR?? :D
