### ISSUE TITLE
Crash when adding reaction to issue comment

### ISSUE THREAD

**Issue by SoullessWaffle** [k0shk0sh/FastHub#569]
**App Version: 2.5.3**

**OS Version: 23**

**Model: HTC-HTC 10**

I opened an issue though [a link](https://github.com/prettier/prettier/issues/13#issuecomment-304556764) in my email, scrolled down to the last comment, clicked the reactions button on the top right of that comment and then clicked the heart reaction. The app crashed almost immediately. I've done the exact same thing twice and it crashed both times.

I was unable to send a crash report through Android because it also pops up saying the app has crashed when I click send, although it's possible the report was sent anyway.

**Comment by k0shk0sh** [comment]
Hello text

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Yup it definitely does, strange tbh. I'll see about it later today, however u could try with comment and its working :D. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh I didnt get a crash but i do see this line
```java
05-29 09:33:47.281 9328-9328/com.fastaccess.github E/IssueDetailsViewHolder || addReactionCount(): [com.fastaccess.data.dao.TimelineModel@0]
```

**Comment by k0shk0sh** [comment]
@yakov116 they're is only crash in that comment specifically

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
This has been fixed and later will be closed with a commit

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
