### ISSUE TITLE
Add remove ads option with price even we have disable button

### ISSUE THREAD

**Issue by kutsan** [k0shk0sh/FastHub#57]

**Comment by kutsan** [comment]
Also you should definitely add a warning that Submit button gonna create a GitHub issue.

**Comment by k0shk0sh** [comment]
could you elaborate on this? is it some sort of donation button?

**Comment by kutsan** [comment]
@k0shk0sh Yes exactly but it also removes ads.

**Comment by k0shk0sh** [comment]
alright, that's fare enough. it shall be in later release I'm testing things up and aiming on later release or max tomorrow.

**Comment by k0shk0sh** [comment]
@kutsan alright kutsan, I'll see what i can do about it.

**Comment by kutsan** [comment]
Thats great app. You at least deserve our tiny donations. Thanks!

**Comment by k0shk0sh** [comment]
@kutsan thanks for your kind words, stay tuned for upcoming release, where it has most of the missing features in previous version.

**Comment by yngwi** [comment]
I was also missing a donation possibility or something similar as I hate ads (they take away valuable screen space and are annoying) but I still would like to support the development as this app is on my opinion by far the best GitHub client that I'm aware of. Just sayin'!

**Comment by k0shk0sh** [comment]
@yngwi thanks for your kind words, since you guys insist, I'll implement a donation button in app in the next version.

**Comment by yngwi** [comment]
Thanks 😃
