### ISSUE TITLE
View & scrolling

### ISSUE THREAD

**Issue by coderecess** [k0shk0sh/FastHub#570]
**App Version: 2.5.3**

**OS Version: 23**

**Model: motorola-XT1254**

 Hello,

When swiping up to view content below the current view, the repository information and options minimizes to one line to maximize the view of the contents, which is great.

However, when swiping down to go back up, the repository information returns to normal and minimizes the view of content.

It will be great if the repository information and options would remain one line until scrolling has reached the top or that section is dragged down itself.

Please consider this change.

Thank you.

**Comment by k0shk0sh** [comment]
Well after a second thought, you could open the readme from the files tab & read it in a full screen, having to change the whole layout or customize it on just a matter of a file can be opened in different will take more efforts. So I guess the best about this is that you head to files tab & click on readme to go into more like readable screen. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by coderecess** [comment]
OK Sounds good.

_Sent from my Motorola XT1254 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
