### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by coderecess** [k0shk0sh/FastHub#571]
**App Version: 2.5.3**

**OS Version: 23**

**Model: motorola-XT1254**

 When using the back button in the navigation area of the interface, the app takes me back to the app's home screen.

Is this by design?

I tap it to go up a directory level, and then have to work my way back to where I was.

Thank you.

**Comment by k0shk0sh** [comment]
You are always recommend to use phone back button to go back from where you were, pressing the toolbar back button will try to mimic a navigateUp scenario. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
