### ISSUE TITLE
Feature request: Preview

### ISSUE THREAD

**Issue by coderecess** [k0shk0sh/FastHub#572]
**App Version: 2.5.3**

**OS Version: 23**

**Model: motorola-XT1254**

Hello,

 I'm new to markdown and like being able to preview posts before submitting them.

Please consider adding this feature.

Thank you.

**Comment by StanNL** [comment]
@coderecess You can preview comments/issues by clicking the "eye" icon in the bottom right of the screen.

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by coderecess** [comment]
Awesome! I see that now.  Thank you!!

_Sent from my Motorola XT1254 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
