### ISSUE TITLE
Star count of pinned repos doesn't update

### ISSUE THREAD

**Issue by Maxr1998** [k0shk0sh/FastHub#573]
**App Version: 2.5.3**

At least not until you unpin and re-pin the repo.

**Comment by k0shk0sh** [comment]
Couldn't get your question, 
Pin-Unpin doesn't have count.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Maxr1998** [comment]
No problem, didn't even see your first comment :grin:

**Comment by k0shk0sh** [comment]
@Maxr1998 I have edited it three times 😀

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
