### ISSUE TITLE
Long language names wrap to second line in repo header

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#576]
**App Version: 2.5.1**

**OS Version: 25**

**Model: samsung-GT-I9305**

 
![](https://puu.sh/w4nvh/6c53f9a8d0.png)

Looks like the info box thingy only stretches until the first toolbar item, making the HTML tag break lines.

**Comment by wasdennnoch** [comment]
Just wondering, in which version did that get fixed? I still see the line breaks in many repos.

**Comment by k0shk0sh** [comment]
Along time ago? Can't remember, can you screen shot what you still seeing?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
Literally the first repo I opened.


![](http://i.imgur.com/eyzwbTw.png)

**Comment by k0shk0sh** [comment]
@wasdennnoch 😁, it seems like somehow I reverted the change or something went nuts, just redid it again

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
