### ISSUE TITLE
Cannot copy repo link directly

### ISSUE THREAD

**Issue by ibrokemypie** [k0shk0sh/FastHub#578]
**App Version: 2.5.3**

**OS Version: 25**

**Model: HTC-HTC 10**

 There is no way to directly copy the link to the currently viewed repo. For some devices there is a copy action under share, but not all. Only reliable way to get the url is to open the repo in browser and copy from there.
Having a copy url button on the repos overflow menu along with share would make much more sense.

**Comment by yakov116** [comment]
@ibrokemypie there is a share link. no?

**Comment by ibrokemypie** [comment]
cant embed photo from fasthub afaict

no, not for me

**Comment by mistermantas** [comment]
Copying repo link is possible? Look: http://i.imgur.com/yMnUctl.png

As for uploading images, all I can do is recommend this: https://play.google.com/store/apps/details?id=net.moosen.imgur

**Comment by yakov116** [comment]
@mistermantas he is referring to getting the repo link. Not copying a link like #489

**Comment by k0shk0sh** [comment]
You can embed photo from FastHub, go to markdown (add comment) scroll the bottom icons and select image. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh we are talking about getting the link of the repo to the clipboard. Nothing to do with pictures.

**Comment by k0shk0sh** [comment]
@yakov116 

> cant embed photo from fasthub afaict
no, not for me

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ibrokemypie** [comment]
![](http://i.imgur.com/nfu0zV4.png)
sorry, had no idea you could scroll, wow!
