### ISSUE TITLE
Participated issues tab

### ISSUE THREAD

**Issue by ibrokemypie** [k0shk0sh/FastHub#579]
**App Version: 2.5.3**

**OS Version: 25**

**Model: HTC-HTC 10**

 It would be really helpful to have a tab for issues in which you have participated in, but have not been mentioned in

**Comment by mistermantas** [comment]
Does GitHub's website even have this feature? I don't think so. I know you can view the issues you've created but not ones you've been just mentioned in. Can't speak of the technically possibility of this aspect, though, since I haven't worked with GitHub's API.

**Comment by ibrokemypie** [comment]
nothing official but this would work
https://stackoverflow.com/a/33478315

**Comment by k0shk0sh** [comment]
So basically this will duplicates the other tabs results as well. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh some it's a good idea but

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ibrokemypie** [comment]
@k0shk0sh none of the other tabs show the issues you are involved in but did not create or get mentioned in though, something which applies to most issues I am interested in

**Comment by yakov116** [comment]
@ibrokemypie it was added. 

Thanks for all your feedback

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
