### ISSUE TITLE
Back button does not return to app when fasthub is opened as url handler for github

### ISSUE THREAD

**Issue by ibrokemypie** [k0shk0sh/FastHub#581]
**App Version: 2.5.3**

**OS Version: 25**

**Model: HTC-HTC 10**

 eg in chrome, after tapping a github link and having it open in fasthub, pressing back then goes to whatever you were last doing in fasthub, rather than returning to chrome

**Comment by yakov116** [comment]
Duplicate of #568

**Comment by k0shk0sh** [comment]
It's fixed and soon will be released

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
