### ISSUE TITLE
Not All My Repositories Showing

### ISSUE THREAD

**Issue by alexanderepstein** [k0shk0sh/FastHub#582]
**App Version: 2.5.3**

**OS Version: 24**

**Model: samsung-SAMSUNG-SM-G890A**

I just updated the application to the newest version but when I did that now when I go to my profile under repositories it only lists the most recent two.

**Comment by yakov116** [comment]
@alexanderepstein can you attach a picture?

**Comment by yakov116** [comment]
Or maybe can you log out and log back in?

**Comment by alexanderepstein** [comment]
Tried logging out and in but that didnt work heres what I am referring to 

![fasthub issue](https://cloud.githubusercontent.com/assets/16146094/26562800/d9625f5e-4497-11e7-8a4a-fd247179f441.png)

If you go to my account however you will see I have more repositories then the two listed.

**Comment by Dreamersoul** [comment]
Maybe you need to login with token since it will give the app more permissions

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alexanderepstein** [comment]
@Dreamersoul I already am logged in with token, and even relogged in again still nothings changed. I suspect its not a permissions/authentication issue, if it can grab any of them (which it grabs 2/12) then it must have the authentication correct because i can alter the two repositories I am shown. I think there may be bug in how its populating this list

**Comment by k0shk0sh** [comment]
@alexanderepstein what are your repos? Are they private? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@alexanderepstein that's strange tbh, I'll debug on later today and let u knos

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alexanderepstein** [comment]
@k0shk0sh thanks I appreciate the quick response :smiley:

**Comment by k0shk0sh** [comment]
this has been solved, it was due to some language color was missing which cause the observable to never be emitted.

**Comment by alexanderepstein** [comment]
@k0shk0sh awesome glad to hear it! How quickly do you generally release updates?

p.s. thanks for making and continously developing this app. Github has never been easier to use from my phone 👍

**Comment by k0shk0sh** [comment]
well, it depend, I could make three updates in two days :p , its not about how regularly tbh, but more like what has been fixed & if there is any critical bug, I might release new update later today if I made a good progress if terms of fixing bugs & sunday will usually have new features.

**Comment by alexanderepstein** [comment]
Sounds good to me, Ill be eagerly awaiting the update 😄
