### ISSUE TITLE
Follow material guidelines for dialogs

### ISSUE THREAD

**Issue by smichel17** [k0shk0sh/FastHub#587]
Quotes are from the [Material Guidelines for Dialogs](https://material.io/guidelines/components/dialogs.html).

> **Alerts without title bars**
> 
> Most alerts don't need titles.
> 
> They summarize a decision in a sentence or two by either:
> 
> - Asking a question (e.g. "Delete this conversation?")
> - Making a statement related to the action buttons
>  
>> **Do:** "Discard draft?" `[Cancel]` `[Discard]`
>> The affirmative action text “Discard” clearly indicates the outcome of the decision.
>> 
>> **Don't:** "Discard draft?" `[No]` `[Yes]`
>> The dismissive action text “No” answers the question, but does not suggest what will happen afterwards. A better action pair would be an explicit “Cancel” and “Delete.”

- Markdown editor discard confirmation dialogue
    - [ ] Actions: "Discard" and "Cancel"
    - [ ] Text: ~~"**Close** / Any unsaved changes will be discarded"~~ => "Discard unsaved changes?"
        - It would be better if the dialog were specific to whether you're editing a comment / issue / whatever, but I'm guessing that would be significantly more work.
- Fork dialog:
  - [ ] Actions: "Fork" and "Cancel"
  - [ ] Text: ~~"**Fork** / Are you sure?"~~ => "Fork?" or "Fork ${name_of_repo}?"
- Repo details dialog (`{i}` to the left of the repo title)
    - [ ] Remove the `Cancel` action, since it is redundant with the `ok` action.
- Other dialogs I could find / what needs updating
    - [ ] "Organizations" info dialog: Remove 'Cancel' action
    - [ ] Closing an issue/PR: Text and actions
    - [ ] Locking an issue/PR: Actions
    - [ ] Logout: Text and actions

> **Navigation**
> 
> The “X” used in a full-screen dialog differs from an up arrow, which indicates the view’s state is constantly being saved. For example, an up arrow used in Settings indicates all changes are committed immediately without explicit confirmation or cancel actions.

- [ ] Use a back arrow instead of an X the settings
- [ ] Use an X instead of a back arrow in the add comment dialog
  - Alternative: Keep the back arrow, and save a draft of the comment
  - [ ] Nitpick: The cancel animation should match the launch animation; the dialog should fall downward off the screen instead of sliding off the right of the screen.
- [ ] Use an X instead of a back arrow in the new issue dialog

> **Full-screen dialogs | Discard**
> - If no changes have been made, the dialog closes and no discard confirmation is required.
> - If the user has made any changes, they are prompted to confirm the discard action. 

- [x] Show a confirmation dialog before discarding a new issue, if the user has entered a title or text
- [x] Same for creating a gist

**Comment by k0shk0sh** [comment]
Well, thanks for the brief description of issue, as you mentioned this will take some time to modify things up, btw the guides made to not strictly follow them, but to take them as example.

**Comment by smichel17** [comment]
> btw the guides made to not strictly follow them, but to take them as example.

I agree. I think of them like rules of grammar in speech/writing: in the words of one of my English teachers long ago, "[The rules] are hard and fast... until you have a good reason to break them." Personally, I often prefer non-standard bottom navigation, like the [ninja browser](https://f-droid.org/repository/browse/?fdid=io.github.mthli.Ninja).

In this case I happen to agree with the guidelines anyway, so it's a bit of a moot point :)

**Comment by k0shk0sh** [comment]
Idk what's up with GitHub, but whenever I mark checkbox as checked leaving and coming back find them still not checked.
