### ISSUE TITLE
Issue search dropdown menus should not re-open while open

### ISSUE THREAD

**Issue by smichel17** [k0shk0sh/FastHub#588]
- FastHub Version: 2.1.0
 - Android Version: 7.0
 - Phone Model: Samsung galaxy S6 (`SAMSUNG-SM-G920A`)

**Steps to reproduce:**

- Open issues search
- Open a drop-down menu with a limited number of options (eg, `Sort`)
    - If you open a menu with lots of options it'll cover the menu title, so the next step is not possible
- Tap on the drop down menu title (`Sort`) again

**Expected result:** Drop-down menu closes and remains closed
**Actual result:** Drop-down menu closes and re-opens

The `Created` / `Assigned` / `Mentioned` drop-down menus on the top-level issues screen behave as expected.

**Comment by k0shk0sh** [comment]
why not just click outside of it? clicking in anywhere on the screen will hide it but not the tab itself. I don't know where the issue could be here.

**Comment by smichel17** [comment]
<img alt="why" align="left" height="700" src="https://cloud.githubusercontent.com/assets/6563664/26617828/50f09a46-45a5-11e7-9e91-3f3343ca7ec0.png">

- Tapping the green area causes the notification area to peek down
- Tapping the purple area focuses the search bar, causing the keyboard to be shown, so only half as many issues are shown
- Tapping the blue area causes another drop-down menu to appear (the bug as originally reported)
- Tapping the red area causes that issue to be loaded
- Tapping the yellow area causes the sort to be changed (duh)

The only way to cause the drop-down to be hidden without adverse side effects is to scroll the list. Not having a way to back out once I've opened a dropdown strongly discourages me from wanting to open that drop-down at all, unless I am 100% sure I want to change that setting. This decreases the discoverability and usability of the search feature (which is otherwise excellent).
