### ISSUE TITLE
UI render bug

### ISSUE THREAD

**Issue by mistermantas** [k0shk0sh/FastHub#589]
**App Version: 2.5.3**

**OS Version: 24**

**Model: samsung-SM-G930F**

 How to reproduce: visit twbs/bootstrap.

[Screenshot](http://i.imgur.com/XsSOwAA.png)

**Comment by k0shk0sh** [comment]
Tnx reporting, it's fixed locally :p

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
