### ISSUE TITLE
My general thoughts, feature requests

### ISSUE THREAD

**Issue by kutsan** [k0shk0sh/FastHub#59]
Here is my general thoughs. Since they're too long, I've divided them into groups.

1. **Main Screen**
    1. ~~Remove "Gists" and "Profile" pages from bottom bar. Instead add Feeds, Issues, Pull Requests, respectively. Honestly, who cares about Gists more than their own open issues and pull requests?~~
    2. Remove notifications icon and add notifications above to the feeds like this: [https://i.imgur.com/3GowH1N.png](https://i.imgur.com/3GowH1N.png). In my opinion this adds more meaning to the main screen. Only feed not useful enough.
    3. Don't repeat the same user profile picture over and over again. Instead group them.

2. **Drawer**
    1. ~~Redesign drawer.~~
    2. ~~Add Gists option to here.~~
    3. If user touch to the their name, navigate to profile.
    4. ~~Add About section to here.~~
    5. ~~Add Settings to here.~~
    6. ~~Remove FastHub version and FastHub name itself.~~
    7. Enable ads by default and remove this "enable ads" option from there. Instead add this to the settings.

3. **Repository Screen**
    1. **Navigation Bar**
        1. There are 3 bars above the screen in repository overview.  
1- Repository name, date, x days ago  
2- Back button, watch, stars, fork, and three dot  
3- Tabs  
And I think looks too messy in smaller screens. Can't even see the content of README because of this messiness. You can combine first and second bar into one bar. Like:  
1- Left: Name, date, x days ago. Right: watch, star, fork buttons, three dot.  
2- Back button and other tabs. Something like that.
        3. If user touch the license icon in above bar navigate to LICENSE file.
        4. Remove forked repo URL from three dot menu (there is no sense here to be here) if repo is forked. Instead add to the below of the repo name as small text like "forked from lorem/ipsum"

    2. **Tabs**  
        1. **Readme**  
            1. Add GitHub tags.  
            2. ~~Add repository description.~~
            3. ~~If someone touch the external images in README file, like Imgur image embedded with markdown. Navigate to the link in internal browser or open internal browser or something. For now if I touch it says in progress and 404 not found.~~  
        2. **Files** 
            1. Use better icons by file type. Like if it's a Java file, show Java icon instead of just paper. You SHOULD use this [https://github.com/PKief/vscode-extension-material-icon-theme](https://github.com/PKief/vscode-extension-material-icon-theme). Their license is MIT and they keep updating the icons.
            2. In Files section pre-load all folder and files in once (at leasts load 4 depth) but don't load content of files just indexes. Then user easily navigate without loading bar. If want to open a file you can then load what is inside in viewer.  
            3. Remove all loading bars for file navigation and add something like this: [https://i.imgur.com/wdSwO1C.gif](https://i.imgur.com/wdSwO1C.gif) to above or below path. This is more smooth and looks nice for file navigation.  
            4. Remove three-dot menu from right of the files. Instead add long press option for share and download.
            5. You can also add last commit name for that file to the right of the files instead of three dots. At least add this option for bigger screens like tablets.  
        6. **Viewer**
            1. Add "open external text editor" option.
            2. Remove dots from gutter / line numbers.
            3. Add word wrap option.
        3. **Commits**
            1. Add 3D touch like long press for profile picture like Flaming for Twitter has. If user long press profile names in commit (or other places) show quick pop-up for user.
            2. In commit changes, add option to view full content of file. (#197)
        4. **Releases**
            1. Remove download button and if user touch the one of the releases add downloadable files to the bottom of the pop-up. And add download buttons to here.
        5. **Contributors**
            1. Remove "Contributors" and replace this with Graphs in a standart way. In Graphs section add "Contributors" to here. You can also add many this in here in future.  
        6. Add **Pulse** section
    3. **Bottom Bar**
        1. Remove bottom bar completely for that screen. Move Issues and Pull Requests sections to the tabs after the Commits. Like GitHub mobile website design has. If you don't want to remove bottom bar I understand.
        2. **Issues**
            1. Add search option but don't add this like a icon. You should add as a bar below to the Opened, Closed tabs.
            2. ~~Combine details and comments section into one screen. Really, no need to separate comments.~~
            3. ~~Re-design comments something more like this [https://www.figma.com/file/QQzlZCxSi9fPqobY1JDNqVUU/FastHub-Issues](https://www.figma.com/file/QQzlZCxSi9fPqobY1JDNqVUU/FastHub-Issues). Trust me, this is way better than cards. More compacts and we can see more comments. I don't like "material cards" in everywhere.~~
        3. **Pull Requests**
            1. ~~Same things with issues. Combine details and comments.~~
            2. ~~Add search bar.~~

4. **Profile Screen**
    1. Redesign profile page completely. I didn't like current design.
    2. Remove Followers and Following tabs. Navigate them by just pressing its number.
    4. Remove repositories tabs, instead of you can add them below to the overview. Like popular repositories with expand button below.
    4. Add share button to the navigation bar for sharing user profile.
    5. ~~Move the follow button to the below.~~
    7. Add activities to the below overview and popular repositories.

5. **Gists Screen**
    1. The default screen is public gists stream and this is irrelevant. No body cares about that. Instead you should replace it their own gists and starred gists in one page. This will be more useful to everybody. You can add option to see public gist stream if somebody wants to see.

6. **General Things**
    1. Remove "In Progress" loading dialog/spinner from ANYWHERE. This one not looks good.
    2. Add your Bitcoin address to README.md for donations. It's nice to have IMO.
    3. Add gh-pages branch and design project website or someone eventually will design one.
    4. Upload your APK to F-Droid. If you don't know, it's Play Store for open source projects.

There are more thoughts about your app but this post already became so big. Thanks for reading.

Edit: ~~Strikethrough~~ formatting means completed.

**Comment by k0shk0sh** [comment]
Hello @kutsan  thanks for the detailed suggestion and feedback on FastHub, I really see your point there and really liked most of your suggestions, however doing that currently will require me rewrite the whole application or at least modify the whole structure of the app. This will take plenty of time to do, but I can promise you once I get all the bugs fixed I'll start taking them step by step. 

I'm currently working on adding the missing features and fixing bugs, once these are done, I'll be more focusing on enhancing FastHub as per your suggestions. 

Thanks for your time and effort on putting this list together, I really appreciate that. Will start hitting this issue with commits once i start working on, so you get update about it.

Thanks again.

**Comment by kutsan** [comment]
No worries. Thanks for your reply. I will look forward to.

Just out of curiosity, is there a suggestion that absolutely not going to do?

**Comment by k0shk0sh** [comment]
Not really something impossible, but some stuff such as combing stuff together in one screen, this will require some custom API calls that happens all together to retrieve some data and then construct them in a custom adapter this is what concern me other than that nothing really.

**Comment by k0shk0sh** [comment]
especially when we have pagination, I'll have to customize a lot of stuff, such as lets say, displaying the details and comments in one screen, it would be impossible for use to know the current size of the comments immediately instead I'll have to have custom wrapper that tells me when actually a n amount of comments are load minus the details timeline to retrieve the next page. its API limitation tho, but we will see how when i actually start working on.

**Comment by k0shk0sh** [comment]
Thanks, nothing impossible tho as i mentioned. will keep you in track with each commit happens regards this ticket.

**Comment by Rainer-Lang** [comment]
@kutsan Some of your suggestions I really like and I have even thought about them - I would like to "upvote" them....but it's only one issue...
@k0shk0sh Are you planning to implement all of the suggestions? Or which one? Maybe there are some to discuss a bit more.....

**Comment by kutsan** [comment]
@Rainer-Lang Thanks. I know I shouldn't open all of them in one issue but I didn't want to open separate issues either.

Since FastHub now open-source project, we also should discuss some of features before get implemented, if @k0shk0sh appropriate it.

**Comment by k0shk0sh** [comment]
These features/Improvements will start development when FastHub gets stable, which I guess very soon. stay tuned for commits reference.

**Comment by k0shk0sh** [comment]
@Rainer-Lang could you list down which ones you need to discuss about? 
I'm not quite sure yet which one shouldn't be implemented or added yet until I actually start development, therefore, I can't really decide right now.

**Comment by Rainer-Lang** [comment]
1-i
So the ViewPager/tabs could be removed and the navigation will be via bottombar?

**Comment by k0shk0sh** [comment]
I guess this commit ef25469  handle almost of this, please @kutsan when you finalize the last version, do edit this issue so we could know what is done and what left <3

**Comment by kutsan** [comment]
@k0shk0sh Thanks Kosh, really. I'll update.

**Comment by dikiaap** [comment]
Those all are nice features and don't forget to adding Reaction feature.

**Comment by k0shk0sh** [comment]
@dikiaap  did you mean #194  ? its already there but haven't released yet.

**Comment by dikiaap** [comment]
@k0shk0sh yes. I didn't realize that. 👌

**Comment by kutsan** [comment]
I was satisfied about new features so I'm gonna close this issue. Thanks @k0shk0sh to put your time on that.
