### ISSUE TITLE
Branch selector wrong orientation in portrait mode

### ISSUE THREAD

**Issue by rapgenic** [k0shk0sh/FastHub#590]
**App Version: 2.5.3**

**OS Version: 25 (LineageOS)**

**Model: asus-Nexus 7**

When my device is in portrait orientation, in the "Files" tab of any repository in the branch selector/indicator the characters are displayed in a narrow vertical line, causing the icon bar to expand, too. This doesn't happen in landscape orientation.

I will add a screenshot as soon as possible.

By the way, there doesn't seem to be a feature to upload a image directly from inside FastHub, or at least I couldn't find it... It may be a nice enhancement :) 

_Sent from my Asus Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Hi thanks for the report, there is an embedded feature for that as u can see from here lol. All you have to do is scroll bottom icons in this screen.

![](http://i.imgur.com/MKU4guE.png)


_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rapgenic** [comment]
Hi, thanks for your answer. I actually found it just now :)

By the way here's the screen:

![](http://i.imgur.com/M0YfbMQ.png)


_Sent from my Asus Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
I just fixed this, thanks for reporting :)

**Comment by rapgenic** [comment]
320 DPI, which should be the default for the nexus 7.

_Sent from my Asus Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rapgenic** [comment]
You're welcome :)

_Sent from my Asus Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
