### ISSUE TITLE
Images in commits don't shop up

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#591]
**App Version: 2.5.3**

**OS Version: 25**

**Model: samsung-GT-I9305**

When you e.g. commit a new image to the repo it doesn't load when you expand the modified (added) file in the commit file list, only actual text diff loads properly.

**Comment by k0shk0sh** [comment]
clicking on an image will open it isn't?

**Comment by wasdennnoch** [comment]
For me it only rotates the expand button and doesn't open it externally. I can grab any log you want if you need one.

**Comment by k0shk0sh** [comment]
do you have chrome installed in your phone? also could you point me to the commit?

**Comment by wasdennnoch** [comment]
Yes, I have the normal chrome version installed. An example is the very last commit in this repo which added tue direct download button. Clicking on the card only "expands" it. 
![](https://puu.sh/w6CH7/bdd1e8ad80.png)

**Comment by k0shk0sh** [comment]
Ooops, it works on PR commit files tab however not in the commit files itself, thanks for catching   this up.  will be closed later with my commit.
