### ISSUE TITLE
Unable to Edit Issue

### ISSUE THREAD

**Issue by jerryn70** [k0shk0sh/FastHub#596]
Iam unable to edit my issues . Issue title also not editable. When I try to edit it shows "issue can't be edit by jerrn70' . 
There is no problem with github website.
   
   
 

 - FastHub Version: 2.5.3
 - Android Version: 6.01
 - Phone Model: moto x play
 

Testing

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@jerryn70 how do you login to FastHub? is it via token or how? it might be a temp github is down or something, i'm going to close this as per #427

**Comment by jerryn70** [comment]
@k0shk0sh  i think I used Basic authentication

**Comment by k0shk0sh** [comment]
@jerryn70 could you please try again? If github said that, I can't really help much :p

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jerryn70** [comment]
I tried fresh install. When I open the app there is toast message showing 'unauthorised user' . And then I logged in using basic authentication but still I'm unable to edit.

**Comment by k0shk0sh** [comment]
@jerryn70  can u please try and edit this issue? Also could you point me to the issue? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jerryn70** [comment]
@k0shk0sh  Now its working. I have edited the issue using fasthub

_Sent from my Motorola XT1562 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@jerryn70 cool, P.S: there is a known bug where u edit issue isn't reflected immediately, its fixed in coming release

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jerryn70** [comment]
@k0shk0sh the issue is only with some repository. I don't know why

**Comment by k0shk0sh** [comment]
@jerryn70 maybe github restriction or tbh idk lol

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyuszika7h** [comment]
I also have this problem at https://github.com/NyaaPantsu/nyaa/issues/1057 on my Nexus 5X (Android 7.1.2, FastHub 3.2.0).

**Comment by k0shk0sh** [comment]
@nyuszika7h give it few minutes and try again. 

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyuszika7h** [comment]
OK, will try in a few minutes. (I used OAuth, by the way, and logout & login again didn't help.)

**Comment by k0shk0sh** [comment]
@nyuszika7h alright thanks, I'll modify the message to show the message that GitHub returned. 

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
