### ISSUE TITLE
When editing an issue the issue text is "No description provided"

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#597]
**App Version: 2.5.3**

**OS Version: 25**

**Model: samsung-GT-I9305**

 When you edit an issue, submit the changes and the app returns to the issue view the text is "No description provided" instead of the just submitted text. Reloading the issue fixes that.

**Comment by k0shk0sh** [comment]
#596

**Comment by wasdennnoch** [comment]
That's a different issue; there he can't edit it at all. Here I can edit it perfectly fine but the text doesn't show up properly at first.

**Comment by k0shk0sh** [comment]
Its the same, fixing that will fix this too :) 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
