### ISSUE TITLE
ANR after opening large file

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#598]
**App Version: 2.5.3**

**OS Version: 25**

**Model: Google-Pixel**

 Opening a large file causes an ANR (I can repro it reliably by opening `Flowable.java` from RXJava).

**Comment by k0shk0sh** [comment]
I could trigger that if I start scrolling :'(

**Comment by eygraber** [comment]
@k0shk0sh yup, forgot to mention the scrolling part.

**Comment by k0shk0sh** [comment]
@eygraber this fixed and will be in todays release, however the fix is a bit ugly, meaning, you wont be getting syntax highlighting on large files which the `WebView` can't take :D, `Flowable.java` has more than 16K line of code :D around 900000+ character. its huge `in trump voice`.
