### ISSUE TITLE
Expand profile picture on click in profile view

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#602]
**App Version: 3.0.0**

**OS Version: 25**

**Model: Samsung Galaxy S5**

I really appreciate the new update! The app keeps getting better and better. 

I would like to be able to expand the profile picture when I click on it when I am at a profile page. 

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
you could, just click on the title and not the avatar, sorry for the confusion tho :D

**Comment by k0shk0sh** [comment]
In a second thought, I should make the avatar clickable instead of the whole layout

**Comment by StanNL** [comment]
@k0shk0sh Oops I didn't notice that, but maybe you should make both of them clickable indeed

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
