### ISSUE TITLE
Large file text color

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#603]
**App Version: 3.0.0**

**OS Version: 25**

**Model: Google-Pixel**

 If my app is set to the dark theme, and I open a large file (e.g. `Flowable.java`), then the text is dark colored on a dark background. 

![](http://i.imgur.com/JYDLdSy.png)

**Comment by k0shk0sh** [comment]
Daamn, 3.0.1 tomorrow? Lol. Didn't release test on it tbh, the good thing is that it doesn't crash any more :p

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
