### ISSUE TITLE
Can't filter/sort repos in organization

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#604]
**App Version: 3.0.0**

**OS Version: 25**

**Model: Google-Pixel**

 If I go to the repo tab for an organization, I can't filter/sort them.

**Comment by k0shk0sh** [comment]
You could filter them base on source, forks, etc but not sort them. I guess its API limitation that's why I believe adi hide it in that screen.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
No API for that, only type is allowed 😥

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
