### ISSUE TITLE
Opening any gist follows to some random gist

### ISSUE THREAD

**Issue by nixel2007** [k0shk0sh/FastHub#606]
**App Version: 3.0.0**

**OS Version: 23**

**Model: Xiaomi-MI 5s**

 When I open any of my gists I've been redirected to specific one (not that I've opened)

**Comment by yakov116** [comment]
@nixel2007 link please

**Comment by StanNL** [comment]
@yakov116 It works with any of his gists on his profile page. It links to one of k0sh's gists, and I think it's just a debugging error

_Sent from my Samsung Galaxy S5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@nixel2007 @StanNL Correct Reproduced

**Comment by k0shk0sh** [comment]
Hmmm, strange as I never touched anything regards that and more strange is that opening gists from public gists works but profile is not. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@nixel2007 since u are here :p could you tell me why codecov isn't working :p 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
