### ISSUE TITLE
5$ support button does not open a Google play window 

### ISSUE THREAD

**Issue by nixel2007** [k0shk0sh/FastHub#607]
**App Version: 3.0.0**

**OS Version: 23**

**Model: Xiaomi-MI 5s**

 2, 10 and 20$$ works correctly

**Comment by yakov116** [comment]
@nixel2007 My fault... I was supposed to test them all.

Thanks for reporting

**Comment by k0shk0sh** [comment]
Its not really broking, it might take time to open I guess, could u like click on it and wait few seconds. I find that strange tho.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Matter of fact I just received that someone has purchased the 5$ item. So I assume it just that you didn't wait longer or you previously had purchased that item. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh I am unable to buy a $5 all others work

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 did you previously  purchased the item?

**Comment by yakov116** [comment]
@k0shk0sh yes

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 then simply that's the answer, google play doesn't allow you to purchase the item twice unless if I allow it from code :) .. never thought someone wants to support twice :p

**Comment by nixel2007** [comment]
looks like i've already supported too :)

**Comment by k0shk0sh** [comment]
@nixel2007 probably lol. I should actually tell you that, I'll see what I can do about it. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh which is really #446
