### ISSUE TITLE
Google play links should open Google play

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#608]
**App Version: 3.0.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 They should not open in web view

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Well I can't simply because fasthub catchs urls & opening chrome tab is the safest way for me to no go into a loophole

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
