### ISSUE TITLE
After updating notification timing is not set

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#609]
**App Version: 3.0.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 Had it set to a half hour did not get any notifications after updating. Checked and saw it was not set.

Number 2 the default shouldbe set to a half hour

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Yanki, you have updated to latest version, did your notification interval gone? I don't think so, then I guess this issue should be closed?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh the question is on a fresh install is this fixed? If yes close the issue

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh This was not fixed in a fresh install

![image](https://user-images.githubusercontent.com/16872793/27013772-b4e12ffe-4eb8-11e7-9062-3a69c017f9f2.png)
