### ISSUE TITLE
Enhancements for Release details

### ISSUE THREAD

**Issue by BehindTheMath** [k0shk0sh/FastHub#61]
- All the data in the release details is one long line. There should be some newlines to break it up. 

- Each issue number mentioned in the release details should link to the issue.

**Comment by k0shk0sh** [comment]
if it is in one line then there is something wrong with the markdown parser. I will see what I can do about it.

**Comment by k0shk0sh** [comment]
Sorry, it wont be in 1.0.6 as i had to quickly fix a crash in PR and the date issue.

**Comment by k0shk0sh** [comment]
this has been fixed in 3618211, it will be up in Sunday max.
