### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by mabbamOG** [k0shk0sh/FastHub#612]
**App Version: 3.0.0**

**OS Version: 23**

**Model: OnePlus-ONE A2003**
(Oneplus 2)
 
I did not get a notification but it was reported under my profile activity and also it was there when i clicked on notifications.

_Sent from my OnePlus ONE A2003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Did you select your notification interval? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mabbamOG** [comment]
yes. 30 minutes is set, notifications are enabled. disable marking as read... is disabled and enable notifiaction sound is enabled.

**Comment by yakov116** [comment]
@mabbamOG I will wait for @k0shk0sh on this I am having the same issue

**Comment by mabbamOG** [comment]
I also forgot to mention that my oneplus 2 does have a battery saving feature that disables/delays all background data usage (i think) until you turn on the screen. It might be part of the problem...but still other apps (eg telegram) get around this by providing notifications as soon as i turn on the screen.

**Comment by yakov116** [comment]
@mabbamOG I am the same I don't think that is the issue

**Comment by mabbamOG** [comment]
Just got a notification from your reply and battery saving was disabled. It could that for me, or an intermittent bug

_Sent from my OnePlus ONE A2003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
its definitely that @mabbamOG FastHub doesn't use GCM to push the notifications, so if you were in doze mode or battery saving mode, do expect that FastHub will respect that and wont run in background.

**Comment by mabbamOG** [comment]
@k0shk0sh alright. So actually telegram is capable of doing that because of gcm? (Which is reliant on google play services tho?)

_Sent from my OnePlus ONE A2003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@mabbamOG we also rely on Firebase (which relies on GPS) but then, we don't trigger GCM because Github simply ain't our server :p , but the job guaranteed will run after device awake from doze mode or battery saving mode.
