### ISSUE TITLE
[FR] Be able to see Git history on long press

### ISSUE THREAD

**Issue by robcore** [k0shk0sh/FastHub#613]
**App Version: 3.0.0**

**OS Version: 21**

**Model: samsung-SM-N900W8**

 Excellent App mate! I'd recommend just silently failing when a readme isn't found, as it's a relatively common occurrence that probably doesn't require a toast/error message client side. While I have you, octodroid has an awesome feature allowing one to hard-press a directory or file to view its git history, and I guess I'm requesting a feature...sorry lol
Have a good one, love your work and it is very useful!

_Sent from my Samsung SM-N900W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@robcore Can you explain your 2 points?

**Comment by robcore** [comment]
I'm happy to!

Whenever I open a git repo from another app (be it a browser, or an app like tophub), a little mini-toast style error pops up briefly saying "error: no readme found!." I think this is unneccessary from an end-user's perspective because it is an issue with repos themselves, not with anything we have the ability to fix on our end, so the error isn't really useful for the app.

As far as the hard-press/git history request, it is based on the gh4a capability of long-pressing a directory or file within a repo which exposes a popup with "commit history" as an option for that specific path. I believe this is the fragment they use https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/fragment/CommitListFragment.java
I know I know, different libraries, different code base, but it's such a useful feature!

Anything specific you'd like me to explain?

**Comment by robcore** [comment]
Ps. the feature request is pretty much implementing git log path/git log --follow filename.

**Comment by yakov116** [comment]
@robcore Renamed it to be clear

**Comment by robcore** [comment]
Thanks man! Sorry I suppose i should have made these two separate issues.

**Comment by k0shk0sh** [comment]
I totally agree about the toast tho :p . I'll remove that.
Thanks

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
