### ISSUE TITLE
White splash screen on dark theme

### ISSUE THREAD

**Issue by gappleto97** [k0shk0sh/FastHub#615]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Huawei-Nexus 6P**

 If there's an easy way to change the splash based on selected theme, can you please do so? Its a bit bothersome to get blinded when opening the app at night.

**Comment by k0shk0sh** [comment]
It's hard to do that in Android as the splash screen is a run time theme 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
I guess you could create a copy of the launch activity but with the dark theme and enable/disable them dynamically? Would be hacky but it works.

**Comment by k0shk0sh** [comment]
@wasdennnoch we Tried, some launchers won't update immediately & upon clicking on the app, it will say its uninstalled until a minute or few seconds only then the app icon will be clickable,  you could give it a try tho :) PRs are welcome :p

**Comment by gappleto97** [comment]
Could the dark one be default?

**Comment by yakov116** [comment]
@gappleto97 Maybe with the new logo
But at the rate we are going we should have it within a year 😉

**Comment by k0shk0sh** [comment]
@yakov116 lol dude, chillx I'll try and see what I can do about it. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
