### ISSUE TITLE
Incorrect number of stars in pinned screen

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#617]
**App Version: 3.0.1**

**OS Version: 25**

 Currently FastHub has 1598 stars but on my pinned screen it shows 1555
Tried pull to refresh but it did nothing

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Well, you have first to go to Fasthub repo at least to update it otherwise they will never be updated, Pinned doesn't know GitHub, meaning there are no API calls for that list. So you have to at least open FastHub repo to update it. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh um... stayed the same by me

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 did u follow my state above?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh yes. I went to FastHub repo, refreshed and..... Nothing changed

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
I noticed this while looking at the FastHub repo ^^

**Comment by k0shk0sh** [comment]
@Younes-L well according to my impl, you have to exit the repo and enter it again for it to update. I don't that this is really critical tho. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
For info the starred tab under my profile shows the correct amount of stars, but so far I haven't found a way to refresh the stars count on the pinned screen...
It's minor, no big deal x)

**Comment by k0shk0sh** [comment]
@Younes-L I'll look into a way of doing this :p

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
this is fixed in b345bf7f879604dd8e7541f40d92fc40ed9f5d05
