### ISSUE TITLE
Disable signature returns after editing a comment that contains a sig

### ISSUE THREAD

**Issue by krokofant** [k0shk0sh/FastHub#620]
**App Version: 3.0.1**

**OS Version: 25**

**Model: OnePlus-ONEPLUS A3003**

1. Wrote comment with signature
2. Disable signature in settings
3. Edit previous comment
4. Signature is now active in settings 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
Test

**Comment by yakov116** [comment]
@krokofant There are 2 steps to disabling the sig. Did you do both?
It should have been fixed but..
![2017-06-07_16-42-29](https://user-images.githubusercontent.com/16872793/26900505-628de6cc-4ba0-11e7-9739-409640f1453f.gif)

**Comment by yakov116** [comment]
Test

_Sent from my Unknown Android SDK built for x86 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
Test

_Sent from my Unknown Android SDK built for x86 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 what is the bug you referring to? 
Couldn't get the issue?

Is it like when you disable the signature I should remove it from a previous comment? Isn't this the current case?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh test with sig

_Sent from my Unknown Android SDK built for x86 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
