### ISSUE TITLE
Duplicated "S/sort"

### ISSUE THREAD

**Issue by dedepete** [k0shk0sh/FastHub#621]
**App Version: 3.0.1**  
**OS Version: 23**  
**Model: Yota Devices Limited-YD201**  

> Content of [strings.xml](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/res/values/strings.xml)
>```xml
><resources>
>    ...
>    
>    <string name="sort">Sort</string>
>    ...
>    
>    <string name="Sort">Sort</string>
>    ...
><resources>
>```  
Seems like these strings have the same meaning.

**Comment by k0shk0sh** [comment]
Oops, I guess it was added in one of the PRs for filtering repos, you could ignore the latter that starts with `S` I'll remove it later. Thanks for finding this 😥

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dedepete** [comment]
@k0shk0sh i also have a question about contextual meaning of some strings.  
I'm going to make a PR soon with updated translation, but I didn't find, where the following strings are being used for:
```xml
    <string name="todo_checked">Todo checked</string>
    <string name="todo_unchecked">Todo unchecked</string>
    <string name="divider">Divider</string>
```
Can you help me, please?

**Comment by k0shk0sh** [comment]
@dedepete they are used in the markdown editor icons for accessibility & also when you long press them they'll show a `Toast` with that text. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dedepete** [comment]
@k0shk0sh got it, thank you!

**Comment by k0shk0sh** [comment]
Glad I was helpful :) . Thanks @dedepete 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
