### ISSUE TITLE
Clicking on current version under about sometimes says that there's an update

### ISSUE THREAD

**Issue by failex234** [k0shk0sh/FastHub#623]
**App Version: 3.0.1**

**OS Version: 25**

**Model: samsung-GT-I9505**

 In 4 of 5 cases my app tells me there's an update even though there is none. In one case I actually got the message that my app is up to date.

**Comment by k0shk0sh** [comment]
the current implantation checks the local database for FastHub releases, so its not really accurate you'll need to at least open FastHub repo once so it checks properly. I don't remember which Issue I described that & closed it, the better option would be going to the releases API and grab latest to check on that.

**Comment by yakov116** [comment]
@k0shk0sh you told it to me on slack...

**Comment by k0shk0sh** [comment]
@yakov116 owh yeah and you also said I should go to release to get latest. Kudos to you

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
