### ISSUE TITLE
Design issues in profile view

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#626]
---

 - FastHub Version: 3.0.1
 - Android Version: 7.0

![screenshot_20170608-215757](https://user-images.githubusercontent.com/10360816/26959462-e55e5140-4c95-11e7-8e08-dc18f69a3c8b.png)

**Issues:**
1. Profile details elevation is different than Organizations and Contributions. Or at least the shadow seems darker.
2. There's no pull to refresh nor even an icon to do it there.
3. The bottom padding of the "Join date" is too small compared to other items like Location, email, etc.

Additionally, I would like you to change the order of username and name. Currently these texts are shown (e.g. for my account) like this:
```
jahirfiquitiva
Jahir Fiquitiva
```

I think it would be better if they were shown like this:
```
Jahir Fiquitiva
jahirfiquitiva
```

Keeping the same style: first line primary text colored, second line secondary text colored.
**Be sure to do this in Navigation Drawer too, please.**

Thanks in advance.

**Comment by yakov116** [comment]
@k0shk0sh @JediBurrell Redid this one want to wait for him?

**Comment by jahirfiquitiva** [comment]
@yakov116  I'm sorry, but I don't understand your reply.

**Comment by yakov116** [comment]
@jahirfiquitiva no worries this was a message for him

**Comment by k0shk0sh** [comment]
@yakov116 its alright, I could rework on it. let Jedi later focus on something more important :)
