### ISSUE TITLE
Make the whole app comply with Material Design guidelines

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#627]
---

 - FastHub Version: 3.0.1
 - Android Version: 7.0

# Floating Action Button

According to [Material Design FAB Guidelines](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button), FAB actions should be "positive actions like Create, Favorite, Share, Navigate, and Explore."

And you shouldn't put a menu in a FAB.
![screenshot](https://user-images.githubusercontent.com/10360816/26959630-96f486ae-4c96-11e7-8b19-7fb22788c459.png)

Please move the Search and Last updated options to toolbar (the second one could be replaced with something like Sort or Filter), and make the FAB have only one action: create an issue, which would make more sense and would be correct to guidelines.

# Navigation Drawer

There are a couple issues with current navigation drawer:

1. Its width should be the device screen width - toolbar height, right now is way lower than that.
2. When an item is selected, its text should be tinted with accent color.

# Icons and Texts Colors

There are a couple things that annoy me a bit regarding the current colors implementation:

1. In light theme, all icons are black, instead of semitransparent black as guidelines say. I think the full back is a bit annoying to see.
2. In dark theme, primary and secondary text colors are barely differentiable, which makes it a bit bad for readability.

Right colors:

<table>
<tr><td rowspan="2">Icons</td><td colspan="3">Light background</td><td colspan="3">Dark background</td></tr>
<tr><td>Color</td><td>Opacity</td><td>Result in HEX</td><td>Color</td><td>Opacity</td><td>Result in HEX</td></tr>
<tr><td>Active</td><td>Black <code>#000000</code></td><td>54%</td><td><code>#8a000000</code></td><td>White <code>#ffffff</code></td><td>100%</td><td><code>#ffffffff</code></td></tr>
<tr><td>Inactive</td><td>Black <code>#000000</code></td><td>38%</td><td><code>#61000000</code></td><td>White <code>#ffffff</code></td><td>50%</td><td><code>#80ffffff</code></td></tr>
<tr><td>Texts</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>Primary</td><td>Black <code>#000000</code></td><td>87%</td><td><code>#de000000</code></td><td>White <code>#ffffff</code></td><td>100%</td><td><code>#ffffffff</code></td></tr>
<tr><td>Secondary</td><td>Black <code>#000000</code></td><td>54%</td><td><code>#8a000000</code></td><td>White <code>#ffffff</code></td><td>70%</td><td><code>#b3ffffff</code></td></tr>
<tr><td>Disabled/Hint</td><td>Black <code>#000000</code></td><td>38%</td><td><code>#61000000</code></td><td>White <code>#ffffff</code></td><td>50%</td><td><code>#80ffffff</code></td></tr>
</table>

Thanks in advance.

**Comment by jahirfiquitiva** [comment]
Additionally, I would like to suggest using this app while fixing the inconsistencies: [Keyline Pushing](https://play.google.com/store/apps/details?id=com.faizmalkani.keylines)

It has the right metrics, and I'm sure you will be able to find even more inconsistencies, like in lists and stuff.

Thanks

**Comment by k0shk0sh** [comment]
says `Google` who have it in Inbox & other apps? the guidelines were never meant to be followed if Google themselves follow their guides then i'll definitely do that.

**Comment by jahirfiquitiva** [comment]
Don't expect Google to do that, it won't ever really happen.

Anyways, I think these things indeed make a difference in making the app better looking and with a better UI/UX.

I don't want to go further with this, because you might end up hating me. So, if you implement this or not, is up to you, but for me these changes will really make some improvements.

**Comment by k0shk0sh** [comment]
@jahirfiquitiva I see your point and wont be hating you :p it just that, people always tell me guidelines but yet google don't follow them :p , I'll really consider the icons and other things, but please let me keep the fab popup :p I like it lol

**Comment by jahirfiquitiva** [comment]
@k0shk0sh Great.
Well, I do things that follow guidelines, I like to think about it like "I did it properly, even when Google didn't or even wasn't able to". Just for personal satisfaction.

If you want to keep the FAB pop-up, I think that's ok, but at least change the FAB icon, move the "Add issue" option to the bottom and make the checkbox aligned with options icons and also align all options texts. I think it wouldn't look so bad then.

Good luck with the app. Keep up the good work.

**Comment by k0shk0sh** [comment]
@jahirfiquitiva that's really good suggestion, I'll do that today hopefully. Thanks Jahir 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
