### ISSUE TITLE
Remove README tab when a repo has no README

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#628]
---

 - FastHub Version: 3.0.1
 - Android Version: 7.0

I think this would be better than having an empty section and colored toast saying "No readme found".

Thanks in advance.

**Comment by yakov116** [comment]
@jahirfiquitiva Nope. I think he is just removing the toast as he said in#613

**Comment by jahirfiquitiva** [comment]
I think an empty section makes no sense, so why don't just remove it?
