### ISSUE TITLE
Make navigation drawer comply to Material Design guidelines

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#630]
---

 - FastHub Version: 3.0.1
 - Android Version: 7.0

There are a couple issues with current navigation drawer:
1. Its width should be the device screen width - toolbar height, right now is way lower than that.
2. When an item is selected, its text should be tinted with accent color.

Thanks in advance.

**Comment by yakov116** [comment]
@jahirfiquitiva can you put all this in #627?

**Comment by jahirfiquitiva** [comment]
@yakov116 ok, let me write it there, and then I'll close these.

**Comment by jahirfiquitiva** [comment]
Added this to #627
