### ISSUE TITLE
Switch username and name from navigation drawer

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#631]
---

 - FastHub Version: 3.0.1
 - Android Version: 7.0

Currently these texts are shown (e.g. for my account) like this:
```
jahirfiquitiva
Jahir Fiquitiva
```

I think it would be better if they were shown like this:
```
Jahir Fiquitiva
jahirfiquitiva
```

Keeping the same style: first line primary text colored, second line secondary text colored.

Thanks

**Comment by yakov116** [comment]
@jahirfiquitiva put this in #626

**Comment by jahirfiquitiva** [comment]
Added this to #626
