### ISSUE TITLE
Make it easier to contribute with translations

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#632]
---

 - FastHub Version: 3.0.1
 - Android Version: 7.0

I would like to do the whole Spanish translations, but I don't want to fork the whole project to do this.

I already suggested this to @k0shk0sh some time ago, but I'm doing it again.

Can you please upload the strings.xml to [OneSky App](https://www.oneskyapp.com/)? It's an easier way to translate the project, without having to fork it. And it's free.

Thanks

**Comment by yakov116** [comment]
@jahirfiquitiva If you want you can update the stings file and I can upload it for you

**Comment by jahirfiquitiva** [comment]
@yakov116 
That's the thing, even the simple XML file is annoying to edit, and even harder for new people.
I can edit the XML file, but what if I don't have a good editor for it? What if I want to do some translations now, and some later? What if you add more texts? I would have to re-download the file, search for the new texts and translate them.

All those things are managed by OneSky.

And the translation is simple as:
```
Original text: This is a text.
Your translation: <insert input form here>
```

Way easier and user friendly, and also easier to maintain, since OneSky won't show the already translated texts, and when updated, it will have a specific section for updated texts.

You should really give it a try.

**Comment by k0shk0sh** [comment]
#98 I guess this issue was opened by you, I have added the oneSky as you suggested but yet 3 months after you recreated one like it :p

**Comment by jahirfiquitiva** [comment]
Yeah, I thought the OneSky site was removed since I saw you created a repo specifically for translations, which is also removed now.

So... Can I do translations on OneSky? Are they still going to be included? And are those texts there updated?

**Comment by k0shk0sh** [comment]
@jahirfiquitiva I didn't :p its still there and it was open because of you, but you abounded it :'(

**Comment by jahirfiquitiva** [comment]
@k0shk0sh 
Yeah, sorry about it. The thing is I got busy and since I wasn't doing the whole switch to FastHub, I didn't find the need to make translations and ended forgetting about it. Maybe in the near future, I will make them.

**Comment by k0shk0sh** [comment]
@jahirfiquitiva sure buddy, its still open and you can do it any time you like :)

**Comment by Younes-L** [comment]
So for translation, refer to this http://fasthub.oneskyapp.com ? 
It seems inactive, need confirmation :)

**Comment by k0shk0sh** [comment]
@Younes-L well I have never used since then, so it might be. @yakov116 has done new one let him know if you want to translate it so he pass you the link.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
