### ISSUE TITLE
Start doesn't search by search icon

### ISSUE THREAD

**Issue by just-Nob** [k0shk0sh/FastHub#635]
**App Version: 2.1.0**

**OS Version: 23**

**Model: LGE-LG-D855**

If searching for issues in the corresponding "issues screen", the search doesn't start by clicking (i.e. tapping) on the virtual keyboard's search/magnifier icon.

It needs an additional tap on the category tab (open/close) to start the search.

**Comment by k0shk0sh** [comment]
Hey thanks for reporting, 

You made me doubt for a second until I went to trigger it, clicking the keyboard search Icon will trigger search for the only selected (closed or opened) issues which one of them I assume it will be selected by default. could you tell me how would you trigger it?

**Comment by yakov116** [comment]
@k0shk0sh Version 2.1.0!!

**Comment by k0shk0sh** [comment]
@just-Nob could you please update to 3.0.1?

**Comment by just-Nob** [comment]
@k0shk0sh:
Newer versions aren't delivered via F-Droid? I got it there...

Anyway, I think my bug description wasn't good enough:

1) Pick one project in FastHub.

2) Switch to "issues" by tapping on the corresponding tap at the screens bottom. You'll be displayed the project's issues.

3) Tap on the blue, floating button at the right lower side, where you can choose to add a new issue or to search the issues.

4) Select "search". The search field will be predefined by "is issue is open" (or something similar).

5) Add your search, tap the magnifier icon and see... - that nothing happens! ;) 

6) By tapping on "open issues", for example, the search results are shown.

If you have further questions, please don't hesitate to contact me again, but please btw a little patient. :)

**Comment by k0shk0sh** [comment]
@just-Nob I did exactly like you said & I have zero problems with that, can you update from the releases page in GitHub repo? Try it and let me know, it might be a specific device bug but can't be sure unless if u are on latest :p 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by just-Nob** [comment]
Hi @k0shk0sh,
tried to install, but wasn't successful.
After trying, my device always tells me something like "Alp wasn't installed" (in German, for sure), neither giving any further information, nor a hint for guessing.
Maybe this is a problem of memory being low, I have to get rid of some test apps... ;) 
Giving you additional feedback about the search problem asap.

Anyway, was there a huge increase in size from release 2.1.0 to 3.1.0?

**Comment by k0shk0sh** [comment]
@just-Nob I don't think that this is the problem? I had try uninstalling my current FH & install the new one :p

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Matter of fact, Fdroid signs the apks themselves which that's why you got conflict, you'll definitely need to uninstall and reinstall. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by just-Nob** [comment]
Ok... - I installed v. 3.10, but behavior still remains.
I could send you a screen recorded video, if you want to, or I could install a debug version.

**Comment by k0shk0sh** [comment]
@just-Nob that will be great, could you do asap :) 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@just-Nob 3.2.0 has an attempt to fix this, please check it out. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by just-Nob** [comment]
Hi @k0shk0sh,

I sent you an eMail with the video attached (about 4.3MByte), recorded on the latest version 3.2.0.

Please let me know of this clarifies my description of the potential misbehavior.

**Comment by just-Nob** [comment]
Hi @k0shk0sh,

thx foryour hint referring to the keyboard!

I used the LG G3's standard, build-in stock keyboard.
The keyboard's search function works well with other apps, like internet browsers, for example.

Anyway, I made some tries with some alternative keyboards, and found out this really interesting facts:
1. Using AnySoftKeyboard (German also installed, but switched to English) results in the same behavior like with the LG stock keyboard, i.e. the search function doesn't work - no filtered result before switching the category (open/closed issue, for example).
2. When switching to Hacker's Keyboard, all seems to  work fine - search is done immediately after tipping the keyboard's magnifier icon!

Hope this will help to find this bug...

**Comment by k0shk0sh** [comment]
@just-Nob does it happen in search activity as well? I'm curious to know since it's the same implemention

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by just-Nob** [comment]
@k0shk0sh, that's really funny... - it works like a charm when starting the search via "your" upper right magnifier icon.

**Comment by k0shk0sh** [comment]
Well I haven't yet but I'll do today, btw which upper right icon you referring to? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by just-Nob** [comment]
You've got a small video by email. :)
Hope this clarifies what I mean.

**Comment by k0shk0sh** [comment]
@just-Nob could you please, head to any repos & click on each tab then click on the fab button, the click search after that could you check if the search icon is working there?

**Comment by Vampire** [comment]
Having the same issue here. I tried with standard AOSP keyboard and with Swype, both show the behaviour described at #802. With the "Hacker's Keyboard" it works fine, or when changing the tab after changing the search term. While changing between open and closed tab does not influence the search result, but just triggers the search.
