### ISSUE TITLE
Line numbering creates inconsistent indentation

### ISSUE THREAD

**Issue by gappleto97** [k0shk0sh/FastHub#639]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Huawei-Nexus 6P**

 ![](https://i.imgur.com/TXmL83j.png)

This is a problem in indent-sensitive languages like Python

**Comment by k0shk0sh** [comment]
could you give a me link to the file?

**Comment by gappleto97** [comment]
https://github.com/gappleto97/overpassify/blob/master/overpassify.py

**Comment by k0shk0sh** [comment]
this is fixed in 1c1908fa17b7006a84ead04d5c0b02e2ff59eb61 by revamping the whole syntax highlighting
