### ISSUE TITLE
Rounded and circular avatars options are switched 

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#641]
---

 - FastHub Version: 
 - Android Version: 
 - Phone Model: 
![image](https://user-images.githubusercontent.com/16872793/27011954-f9b60f60-4e94-11e7-93b0-81c1c307643b.png)

Also disabling list animation should be disabled from settings too

**Comment by k0shk0sh** [comment]
are switched? could you please elaborate?

**Comment by yakov116** [comment]
@k0shk0sh you win!
