### ISSUE TITLE
Crashes if you try to edit an issue's main body

### ISSUE THREAD

**Issue by gappleto97** [k0shk0sh/FastHub#642]
**App Version: 2.1.0**

**OS Version: 25**

**Model: Huawei-Nexus 6P**

 The screen goes black and I need to kill the app.

**Comment by yakov116** [comment]
@gappleto97 please update your app to the latest

**Comment by gappleto97** [comment]
When I try to edit this issue it just says "validation fails" on submit. The crash behavior happens on my repo: https://github.com/gappleto97/issues/7

**Comment by yakov116** [comment]
@gappleto97 can you update the app and try again?

**Comment by gappleto97** [comment]
I cannot. This is the latest on F-Droid.

**Comment by yakov116** [comment]
https://github.com/thermatk/FastHub-Libre
@thermatk is has made F-Droid compatible 3.0.0.

As of now we are no longer supporting F-droid. This may change in the future.

**Comment by gappleto97** [comment]
I'm very sorry to hear that. Might I ask why?

**Comment by yakov116** [comment]
@gappleto97 It got very hard to support F-Droid. 
It meant having to compile two versions and maintain both of them.

I think that we jumped the boat a bit too quick. But what happened, happened.

Sorry
