### ISSUE TITLE
Distinguish between merged and closed PRs

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#644]
**App Version: 3.0.1**

**OS Version: 25**

**Model: asus-Nexus 7**

 Pretty straightforward, as the title says.

**Comment by k0shk0sh** [comment]
in where exactly?

**Comment by arkon** [comment]
The PRs view's tabs, specifically.

**Comment by k0shk0sh** [comment]
aren't they showing? of course in the PullRequests in main screen this won't happen due to the use of search API, otherwise in repos this is what is showing right? 
have a look at this URL https://api.github.com/search/issues?q=type:pr+author:k0shk0sh+is:open&page=1

**Comment by k0shk0sh** [comment]
compare it to repos PRs api https://api.github.com/repos/k0shk0sh/FastHub/pulls?state=closed&page=1

P.S:  it doesn't even tell us who merged however we check if the `merged_at` date is available then I show that it has been merged

**Comment by arkon** [comment]
Ah, that's a shame. I do like how Octodroid has separate tabs for a repo's open/merged/closed PRs.

**Comment by k0shk0sh** [comment]
@arkon but `merged` it actually shows that its merged right?

**Comment by arkon** [comment]
@k0shk0sh Yes, it does show as that within the closed tab, so it's fine. :)

**Comment by k0shk0sh** [comment]
@arkon cool I hope that satisfy you even tho there just a little that u ain't satisfied about :p
