### ISSUE TITLE
Profile repos list items should include third party usernames

### ISSUE THREAD

**Issue by arkon** [k0shk0sh/FastHub#645]
**App Version: 3.0.1**

**OS Version: 25**

**Model: asus-Nexus 7**

 Bit of a long winded title, but...

If you're a collaborator on somebody else's repo, it'll show up in your list of repos on your profile. This causes sorting by name to seem weird because that takes their usernames into account (see the GitHub web UI).

**Comment by k0shk0sh** [comment]
But GitHub Repo sorting API is different from the one that they have on their website,
If we use type then we are forbidden to use affiliation 
https://developer.github.com/v3/repos/#list-your-repositories

**Comment by k0shk0sh** [comment]
just made an attempt to just use one of the types in the github website however it didn't work :'( 

https://api.github.com/users/k0shk0sh/repos?sort=pushed&type=source

**Comment by yakov116** [comment]
@arkon Test 2
