### ISSUE TITLE
[Enhancement] animate the readme header appearing/disappearing upon scrolling

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#649]
**App Version: 3.1.0**

**OS Version: 25**

**Model: htc-Nexus 9**

Currently it only takes a single frame for the header to glitch in and out

**Comment by k0shk0sh** [comment]
yep, I noticed that :p the thing is, it was ugly to do it anyway since we have plenty of fragments in there with only one header and bottomNavigation :D. @kutsan actually told me about it earlier after I released and did change it but was waiting for someone to comment about it :p

**Comment by kutsan** [comment]
It's not a bug if no one noticed it. :D

**Comment by k0shk0sh** [comment]
@kutsan I did it tho :p it looks away better now :D

**Comment by Younes-L** [comment]
~~At least it's better than the weird scrolling from before~~ 🙃
