### ISSUE TITLE
Scrolling problem with links to lines of file

### ISSUE THREAD

**Issue by AlexWayfer** [k0shk0sh/FastHub#655]
**App Version: 3.1.0**

**OS Version: 24**

**Model: Sony-E5823**

 Example link: https://github.com/dry-rb/dry-struct/blob/master/dry-struct.gemspec#L29-L33

_Sent from my Sony E5823 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
What is the problem? I clicked linked and it was being highlighted + scrolled to 33? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AlexWayfer** [comment]
Yes, and I can't scroll to top: it's scrolling to highlighted line again and again.

_Sent from my Sony E5823 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@AlexWayfer owh yeah, didn't test it with small files, it's definitely a bug :'(

Thanks 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
Actually shouldn't all lines fron 29 to 33 be highlighted?

**Comment by k0shk0sh** [comment]
@wasdennnoch this feature is not implemented, could you open an issue for it.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
Sure.
