### ISSUE TITLE
add wiki support

### ISSUE THREAD

**Issue by Dreamersoul** [k0shk0sh/FastHub#66]
some repos are wiki only, adding support would be helpful

**Comment by k0shk0sh** [comment]
currently wikies are out of my scope, until at least the app becomes stable. I can't promise you when it will be released or even when development will start on it, however I think it should be in FasuHub but I don't think any time soon. I'm open to PR tho.

**Comment by Dreamersoul** [comment]
I'll look into it, will try to understand the code and see if i can add it through a PR.

**Comment by k0shk0sh** [comment]
sure, that will be great, hit me up if you want faced any difficulties, the structure would be pretty simple tho, most of modules are the same. but i know the struggle of digging in into something new or not urs and how difficult it would be. don't hesitate to buzz me.

**Comment by Dreamersoul** [comment]
@k0shk0sh awesome! thanks man
