### ISSUE TITLE
Public Gists not opening

### ISSUE THREAD

**Issue by secrethash** [k0shk0sh/FastHub#666]
**App Version: 3.1.0**

**OS Version: 23**

**Model: LENOVO-Lenovo K50a40**

When clicking the link to the gist in the browser, the FastHub app opens automatically and says "No gist found".

While the gist is opening just great in the browser when checked without auto launch to FastHub.

**Comment by k0shk0sh** [comment]
Hi @secrethash it will be really helpful if you could provide a link to the gist.

**Comment by secrethash** [comment]
Sure, https://gist.github.com/flipace/cbd8e913140d2ca650f6.

**Comment by k0shk0sh** [comment]
I see, its definitely due to the username path, will be fixed in tomorrow's release :)

**Comment by secrethash** [comment]
Also just found out, when commenting in the issue and pressing `enter key`, the app crashes.

**Comment by k0shk0sh** [comment]
@secrethash where do you find the enter key? I'm confused abit

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by secrethash** [comment]
The keyboard's enter key. I am using gboard, google's keyboard.

**Comment by k0shk0sh** [comment]
@secrethash I'm using that too, I'll look it up in the crash report with your device name and will try and fix that too. Thanks

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by secrethash** [comment]
Sure, thanks alot.
