### ISSUE TITLE
Filter FAB is shown and persists in non relevant org tabs

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#667]
**App Version: 3.1.0**

**OS Version: 25**

**Model: OnePlus-A0001**

 When viewing an organisation from the side panel, there's no FAB in feeds tab, but then it shows up on all other tabs (even overview and members) and stays visible after going back to the feed tab.

This does not happen on a user view, where the FAB is only shown in repos tab.

**Comment by k0shk0sh** [comment]
Lol, I just fixed that 10minutes ago :D .

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
