### ISSUE TITLE
Dismiss all button appearing when logged in for first time on other's repo

### ISSUE THREAD

**Issue by Sparker0i** [k0shk0sh/FastHub#670]
**App Version: 3.1.0**

**OS Version: 25**

**Model: Xiaomi-Redmi Note 3**

 When we login for the first time, and open other's repo, there appears a red button with "dismiss all" text.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Yep, clicking on that will dismiss all the other guides so you don't see it any more.

**Comment by Sparker0i** [comment]
No, but what I meant to say is that after all the guides go away, the Dismiss All button stays there. By logic, if all guides have been shown, there is no need of that button.

**Comment by yakov116** [comment]
@Sparker0i there is still some that do not show corretly so thats why you get that "dismiss all". One day it will be fixed.
