### ISSUE TITLE
Watch/star/fork repo

### ISSUE THREAD

**Issue by Frioo** [k0shk0sh/FastHub#671]
**App Version: 3.2.0**

**OS Version: 25**

**Model: OnePlus-ONEPLUS A3003**

 The star count (or whatever the action is) resets when you star it.

**Comment by k0shk0sh** [comment]
Could elaborate? I just unstar & star a repo and everything works fine??

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@Frioo any update on this?
