### ISSUE TITLE
Emojis in preview mode

### ISSUE THREAD

**Issue by AlexWayfer** [k0shk0sh/FastHub#673]
**App Version: 3.1.0**

**OS Version: 24**

**Model: Sony-E5823**

 I type Emoji, enter preview mode — and I don't see Emojis in preview 😭

_Sent from my Sony E5823 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment]
It's really a must-have feature. Usually I use a lot of emoji and it's pretty hard to remember all their names. Another great feature would be see how they look on Github, as some of them looks different from what you expect :)

**Comment by k0shk0sh** [comment]
Please do use the shipped Emojies in FastHub from next version 4.1.0 as now FastHub supports GitHub emojis `:confused:` for example and it will render properly.

**Comment by zvirja** [comment]
@k0shk0sh Thanks for that. Could you please also confirm that you will use the same render as GitHub? It's quite important, as usually I choose smile by look, rather than by meaning..

**Comment by k0shk0sh** [comment]
they won't really look asame but they are identical only skin maybe different but the names are correct. I'm trying to avoid to load them as an api call to render the images. instead I have them locally and depending on Android version they will be rendered

**Comment by k0shk0sh** [comment]
they will look like below

![](https://i.imgur.com/DtmqmGg.png)

**Comment by zvirja** [comment]
Would it be possible in that case to have a pack with GitHub smileys instead locally? Or at least the setting, to switch to them?

They look a bit differently as the current skin and this thing is worrying me. As I mentioned above, I pick up smileys by comparing how they look and the ones above looks completely different. I believe I'm not the only one who does so. Given that it's a core feature of your tool - have similar to GitHub look, this will be important.

**Comment by k0shk0sh** [comment]
not really possibe unless I render them base on their url. 
you still have to write the name in GitHub anyway to be able to see the emoji so the search is there for you to do something like that.

**Comment by zvirja** [comment]
Usually I use [this](https://gist.github.com/rxaviers/7360908) page to pick up a smile by look. It will be very inconvenient to use that page on mobile.

Is there any issue to pack all the smileys icons to the local db and later use them instead of the system look? I could help to grab smileys to some particular format if needed..
