### ISSUE TITLE
Releases bug

### ISSUE THREAD

**Issue by ozcaan11** [k0shk0sh/FastHub#674]
**App Version: 3.1.0**

**OS Version: 25**

**Model: General Mobile-General Mobile 4G**

 There is a bug in releases tab.
When you scrolling to bottom all items in the recycle views text become the same 

_Sent from my General Mobile 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@ozcaan11 can you take a picture of what you are seeing?

**Comment by k0shk0sh** [comment]
Update to 3.2.0 and please check & comment back

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh one thing I am seeing is (even on 3.2.0) that my 3.0.0 is saying drafted.

**Comment by k0shk0sh** [comment]
@yakov116 what are talking about

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh When i look at my releases page I see instead of **released** I see **drafted**. I don't have it with me now will post a pic later.

**Comment by ozcaan11** [comment]
@k0shk0sh it seems problem solved ;)

_Sent from my General Mobile 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@ozcaan11 great!

**Comment by k0shk0sh** [comment]
@yakov116 what says draft yanki? I'm abit lost because I never wrote that word in FastHub, it could be coming from GitHub so 😕

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh look at 3.0 
![](http://i.imgur.com/rMfZhqX.png)


_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 then its drafted :) and I should do it from github.

**Comment by yakov116** [comment]
@k0shk0sh it's not. Only in my tablet app does it show drafted. On the emulator it does not. I think that there is a bug casing it now to update

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh Look now.
![image](https://user-images.githubusercontent.com/16872793/27289576-6c722a22-54d8-11e7-8a57-51d1f9ac09f9.png)

This is the emulator
