### ISSUE TITLE
Labels List doesn't load more than 30 labels

### ISSUE THREAD

**Issue by tigerhawkvok** [k0shk0sh/FastHub#677]
**App Version: 3.1.0**

**OS Version: 25**

**Model: Huawei-Nexus 6P**

 If there are many labels in a repo, the list gets cut off, rendering some of the labels inaccessible.

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@tigerhawkvok Can you update to 3.2.0?

After updating if there is an issue, please attach a link to the repo issue.

Thanks for your feedback

**Comment by tigerhawkvok** [comment]
Yep, replicates still

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@tigerhawkvok can you give me a link?

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/27263811-d4dc5c20-543f-11e7-880b-3e3aa45a50f7.png)

As you can see. I dont see any issue here

**Comment by yakov116** [comment]
@tigerhawkvok are you talking about the list of labels you can add? Like the pic below?

![image](https://user-images.githubusercontent.com/16872793/27263823-169c9d5a-5440-11e7-8241-44e7a9a8e705.png)

Which by the way I noticed a new bug @k0shk0sh. the style stops at one point

**Comment by tigerhawkvok** [comment]
Sure, consider these labels from the app label picker:

![screenshot_20170618-132526](https://user-images.githubusercontent.com/165937/27263986-3f3cc1b0-542a-11e7-8332-dd6f8d37169d.png)

![screenshot_20170618-132535](https://user-images.githubusercontent.com/165937/27263987-413c472e-542a-11e7-805b-aaa26d076c51.png)

![screenshot_20170618-132544](https://user-images.githubusercontent.com/165937/27263988-43a4b6cc-542a-11e7-9212-cd3568a860f3.png)



(note that the last one is at the bottom of the scroll)

but look at the same issues on the website:

![image](https://user-images.githubusercontent.com/165937/27263981-1309a6ee-542a-11e7-806e-965dbe9f595f.png)


You'll see that below `os-win`, there are several more labels that are clearly below the bottom of the list provided in the app. So, not all 39 labels are available to be selected.
