### ISSUE TITLE
[FR] Allow Zoom in/out when looking at files

### ISSUE THREAD

**Issue by swarupsro** [k0shk0sh/FastHub#678]
**App Version: 3.2.0**

**OS Version: 23**

**Model: Xiaomi-Redmi 4**

 Currently Syntex Zoom in and Zoom out is not possible....

**Comment by yakov116** [comment]
@swarupsro What when where?
What place in the app? Where would you like it to happen?

**Comment by swarupsro** [comment]
if I wanted to see any large code - we can't zoom in or zoom out the full code!!

**Comment by yakov116** [comment]
@swarupsro in a commit? in a file? in a pull request?

**Comment by swarupsro** [comment]
in a file !

**Comment by yakov116** [comment]
@swarupsro Got you. Ok I am going to rename the issue and wait for @k0shk0sh to respond.

I am taking this as a feature request to allow zooming in when you are looking at a file

**Comment by k0shk0sh** [comment]
You can zoom in/out, have u tried before creating issue?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by swarupsro** [comment]
yes ! i tired ..

**Comment by k0shk0sh** [comment]
@swarupsro then? You could zoom in/out am I right? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
If you enabled wrap content, disable it as you won't be able to zoom in/out

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
https://drive.google.com/file/d/0BxbjAF1sbwjaTkFGZDZnRDdxVzA/view?usp=drivesdk

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
