### ISSUE TITLE
API19?

### ISSUE THREAD

**Issue by i-kocevski** [k0shk0sh/FastHub#679]
Are there any plans of adding support for 4.4 KitKat?

**Comment by yakov116** [comment]
@i-kocevski nope sorry.

Were almost up to android 8 I think it may be time for an upgrade.

**Comment by k0shk0sh** [comment]
It's hard to target 19 at this stage, I never had the thought of downgrading tho, sorry about that. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TheComputerGuy96** [comment]
Sir k0shk0sh, when FastHub for Android KitKat?

**Comment by k0shk0sh** [comment]
@TheComputerGuy96 I'm sorry, but it isn't in my mind at all. 
21 ftw :p

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
