### ISSUE TITLE
Enhance Rendering of <code>

### ISSUE THREAD

**Issue by coderfox** [k0shk0sh/FastHub#68]
I think the `<code>` tags should be rendered with a background for better understanding.

**Comment by k0shk0sh** [comment]
Totally agree, however if you check the commit before the last one, you could see that I have made improvements on that and made sure there is a background behind the code and to be well highlighted.  it will be released in the next version, perhaps coming Sunday.

**Comment by coderfox** [comment]
Sorry for my carelessness. Thanks for your effort in having it implemented.

**Comment by k0shk0sh** [comment]
@coderfox you are most welcome & nothing to be sorry for, have a great night/day.
