### ISSUE TITLE
Download link given in issue ticket don't work (download doesn't start)

### ISSUE THREAD

**Issue by just-Nob** [k0shk0sh/FastHub#682]
**App Version: 3.2.0**

**OS Version: 23**

**Model: LGE-LG-D855**

I've got a download link for a test/debug version of another app hosted at Github. Trying to follow the link on FastHub for downloading the debug version led only to the app's "main page", but failed to download the app.
When logging in to Github via a web browser, the link worked and I was able to download the app via tapping the link.

Here's the link itself:
https://github.com/fralik/Duorem/files/1082631/duorem-v1.1.0-debug.zip
It can befound at that issue:
https://github.com/fralik/Duorem/issues/2

**Comment by yakov116** [comment]
@just-Nob It was fixed (or at least I reported it) will be in the next release.

Thanks for your feedback.

@k0shk0sh add __.zip__ and __.tar__ to the list

**Comment by k0shk0sh** [comment]
Well, this link is new to me lol, never seen link like it before

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by just-Nob** [comment]
@yakov116,
thx for your hint, I have to have a better investigation before starting ghee next issue.

**Comment by yakov116** [comment]
@just-Nob I reported it internally. I didn't make an issue on github.
