### ISSUE TITLE
Opening images is broken since last GitHub API change

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#683]
**App Version: 3.2.0**

**OS Version: 25**

**Model: htc-m8**

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/27294184-aeb1d47e-54e6-11e7-94e5-0eb5b177fa6e.png)?

**Comment by k0shk0sh** [comment]
@yakov116 only FastHub some others nope

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
for reference: GitHub has internally fixed this & therefore its been fixed automatically in FastHub.
