### ISSUE TITLE
Access Token login not working

### ISSUE THREAD

**Issue by cnordhougen** [k0shk0sh/FastHub#688]
**App Version: 3.2.0**

**OS Version: 25**

**Model: asus-Nexus 7**

 When I choose the Access Token login option, I get the exact same prompt as the Basic Auth option, asking for a username and password. When I enter my username & password, it asks for my 2FA code, but always rejects it. If I choose the open in browser OAuth option, I can log in successfully that way, but it never allows me to enter an access token and therefore I am unable to see any of my org repos, just my personal ones.

_Sent from my Asus Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@cnordhougen Org? 

Please read what it says.

There is no way for us to allow 2FA for orgs since it times out.

**Comment by k0shk0sh** [comment]
@cnordhougen  as @yakov116 mentioned, using OTP with Access Token will log you out in less than a minute, what I suggest you to do, either go to your github profile/settings/auth apps and there will be a button for you to ask your orgs to allow FastHub to access them, other than that I really don't know what could be possible.

**Comment by k0shk0sh** [comment]
Please follow up on this https://github.com/k0shk0sh/FastHub/issues/271
