### ISSUE TITLE
[Theme] Brighter text for Amlod theme

### ISSUE THREAD

**Issue by tatulpin** [k0shk0sh/FastHub#692]
Set text (for example in hamburger menu) a little bit more whiter so it'd be a lot easier to read.

**Comment by k0shk0sh** [comment]
Isn't this clear enough? 


![](http://i.imgur.com/rQtM338.png)


_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
