### ISSUE TITLE
Can't fully zoom out

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#693]
**App Version: 3.2.0**

**OS Version: 25**

**Model: Google-Pixel**

 When viewing code that runs off the end of the screen, I used to be able to zoom out to see the whole thing. Now there's an upper limit on zooming out.

**Comment by k0shk0sh** [comment]
Didn't really limit it, but its due to the css file that is being used in the new highlightjs library. I'll see what I can do about it. 

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
