### ISSUE TITLE
No file found

### ISSUE THREAD

**Issue by igorkulakov** [k0shk0sh/FastHub#694]
**App Version: 3.2.0**

**OS Version: 23**

**Model: Xiaomi-Redmi Note 3**

I can not read some files. Gives an error message 'no data available. no file found'. However, the file exists.
Screenshot: https://drive.google.com/file/d/0B4p7bjF5i3nsZlg0U1dvRWs3ZlU/view?usp=drivesdk

_Отправлено с моего Xiaomi Redmi Note 3 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Could you tell me more details?

- How you opening the file?
- The file link?

**Comment by igorkulakov** [comment]
I open documentation: https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/README.md
Almost all links do not work.

**Comment by yakov116** [comment]
@k0shk0sh @igorkulakov 
It looks like this was fixed. It will be in the next release

![image](https://user-images.githubusercontent.com/16872793/27389974-fbe237ce-566d-11e7-8c60-17de182e767c.png)

**Comment by k0shk0sh** [comment]
There is no fix for this, it should work.
Could you try again?

**Comment by yakov116** [comment]
@k0shk0sh you are correct I misread his reply

06-21 10:42:57.293 5189-7189/com.fastaccess.github.debug D/OkHttp: <-- 404 Not Found https://raw.githubusercontent.com/yiisoft/yii2/master/start-installation.md (98ms)

**Comment by yakov116** [comment]
Why are you not gettinh
https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/start-installation.md?

**Comment by k0shk0sh** [comment]
https://raw.githubusercontent.com/yiisoft/yii2/master/start-installation.md
This link definitely doesn't work 😥

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh its not supposed to :stuck_out_tongue_winking_eye:
