### ISSUE TITLE
Cannot load teams on my own organisation

### ISSUE THREAD

**Issue by Sparker0i** [k0shk0sh/FastHub#697]
**App Version: 3.1.0**

**OS Version: 25**

**Model: Xiaomi-Redmi Note 3**

I'm the owner of TheAndroidPeople organisation. When I try to view the Teams in my organisation, it pops an error saying that I need admin rights to load teams. C'mon man I'm the owner and it still asks for this permission.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
First of all, you are using an outdated version of FastHub. Second, If GitHub said that then it ain't my problem.

you would have been more helpful if you had provided a proper info such as: 

1- How did you login?
2- How did you open the Organization.

**Comment by k0shk0sh** [comment]
Well, I just have create an org, created a team & I could see everything, so i'm really unsure what is going on with you, could you please elaborate?

**Comment by Sparker0i** [comment]
I'm the owner of TheAndroidPeople org. I can see it on my profile in GitHub inside the browser. But in this app, I can't even see that.

![In the app](http://i.imgur.com/GQWfMNd.png)

![Browser](http://i.imgur.com/jJYZuzS.png)

But even so I'm able to view teams in the browser.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Sparker0i** [comment]
I've updated the app now.

How did I login : entering user name and password
How did I open org: didn't show up on my profile in the app, so had to search for the org. The org loaded but teams aren't loading.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Did you read what has been said in the Orgs dialog clicking on (!) icon? if not then please do, also you could refer to #255 #271  in short: 

```
 open up https://github.com/settings/applications and look for
        FastHub, open it then scroll to Organization access and click on Grant Button.
```

**Comment by Sparker0i** [comment]
Fixed

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
