### ISSUE TITLE
No starred repositories category?

### ISSUE THREAD

**Issue by woeijiunn88** [k0shk0sh/FastHub#698]
**App Version: 3.2.0**

**OS Version: 24**

**Model: asus-ASUS_Z012D**

Is able to add the starred category in sidebar?

_Sent from my Asus ASUS_Z012D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
starred category? Do you mean adding the starred to be opened from sidebar?

**Comment by yakov116** [comment]
@k0shk0sh I think that's what he means. I would mark it as duplicate 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by woeijiunn88** [comment]
Yes, likely mean that, request to add the starred category in sidebar to view the starred repositories.

Hmm... I try to search for this and likely didn't see any duplicate of this...🤔🤔

_Sent from my Asus ASUS_Z012D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
#625 same idea .

**Comment by woeijiunn88** [comment]
Ok, i see.

_Sent from my Asus ASUS_Z012D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by woeijiunn88** [comment]
Lol, i think that the starred repositories is not available and now I found it in the profile section there... XD

_Sent from my Asus ASUS_Z012D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@woeijiunn88 and I thought u knew about it :p .

All of your stuff are going to be in your profile as well as others too :) 

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
