### ISSUE TITLE
Replace "X assigned X bla ago" with "X self-assigned bla ago"

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#699]
**App Version: 3.2.0**

**OS Version: 25**

**Model: samsung-GT-I9305**

Like on the github website, when you assign an issue to yourself it should say "self-assigned" instead of "you assigned yourself".

**Comment by yakov116** [comment]
@k0shk0sh he means the below


![](http://i.imgur.com/0p2zMYo.png)

It should say self assigned.

_Sent from my HTC Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
Edited the initial message for clarification ;)
Minor thing but I guess you want to get it to be as close as possible to tue website.

**Comment by yakov116** [comment]
I noticed 2 thing when looking at the above. When assigning a label there is an extra space after the name.
Number 2, the "All checks are passes" should say "All checks __have__ passes"

_Sent from my HTC Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 another thing I noticed is that you referring to an old pic from an old FastHub version which has that label changed 😥

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh look at the labels you assigned in this issue. After your name there is an extra space

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
its going to be something like

k0shk0sh assigned **self** bla time :p

**Comment by yakov116** [comment]
@k0shk0sh 
"Name" self assigned is the correct way to say it 

_Sent from my HTC Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
alright, you got it 😞

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/q7yBc75.png)


_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
It's actually self-assigned with a dash.

**Comment by yakov116** [comment]
@k0shk0sh self assigned is bolded because?

_Sent from my HTC Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 removed, @wasdennnoch done

**Comment by wasdennnoch** [comment]
"this" is still missing :P
![](http://puu.sh/wuME6/78909ff35d.jpg)

**Comment by k0shk0sh** [comment]
`spannableBuilder.append("self-assigned this");`

**Comment by wasdennnoch** [comment]
`R.string.self_assigned` pls

**Comment by k0shk0sh** [comment]
@wasdennnoch nope, learned that the hard way, I shouldn't let people translate these GitHub stuff, I will really have hard time removing the translation myself. 
![](http://i.imgur.com/GuhGCaw.png)


_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
Alright then, I'm happy now ^^

**Comment by yakov116** [comment]
@k0shk0sh iI will try to be happy with this :wink:

_Sent from my HTC Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
