### ISSUE TITLE
issue format when use mail

### ISSUE THREAD

**Issue by vvb2060** [k0shk0sh/FastHub#701]
When I comment to  issues with mail, the format is abnormal

_The picture has been deleted, please see the explanation below_

---

 - FastHub Version: e35493
 - Android Version: 7.1.2
 - Phone Model: nexus 6p  Stock Rom

**Comment by k0shk0sh** [comment]
What app version are you using? The version showed isn't familiar to me, could you please tell me what app version are u using? And how did you get the app ?

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vvb2060** [comment]
git commit: e354939 FastHub Debug version.
I build this version to test the Chinese translation.

This is a newline test.

Kosh Sergani <notifications@github.com>于2017年6月26日周一 上午10:28写道：

**Comment by k0shk0sh** [comment]
This is a reply from email that is literally stripped out its reply email.

**Comment by k0shk0sh** [comment]
As you can see from my previous comment, I replied from email and the message got stripped out as per FastHub impl which it does remove the reply at all .

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vvb2060** [comment]
I mean it will not wrap, instead of not removing the reply

**Comment by vvb2060** [comment]
> Kosh Sergani <notifications@github.com>于2017年6月26日周一 上午10:28写道：

This is because Google Inbox uses Chinese to show and reply, but GitHub does not recognize it. This is known and does not need to care.

**Comment by k0shk0sh** [comment]
@vvb2060 alright then, can I close this?

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vvb2060** [comment]
why close？
I mean Fasthub will not wrap, instead of not removing the reply. You can
compare with the web page.
test

test
test

You look, like this.

Kosh Sergani <notifications@github.com>于2017年6月26日周一 下午1:04写道：

**Comment by yakov116** [comment]
@vvb2060 it's not possible (or very hard) due to the way the issues are displayed. In order for it to look ok we just removed the bottom portion. 

Also if github does not recognize it, how can we?

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vvb2060** [comment]
@yakov116 I just want Fasthub to have the same display as GitHub page
![photo_2017-06-26_13-50-49](https://user-images.githubusercontent.com/26996262/27526152-7f218cdc-5a76-11e7-89dd-78ac91b8a423.jpg)
![photo_2017-06-26_13-47-17](https://user-images.githubusercontent.com/26996262/27526104-110707b8-5a76-11e7-9658-bb57faa42c1d.jpg)

**Comment by yakov116** [comment]
@vvb2060 I am saying that that is not possible as of now. Due to the way the issue layout is setup. 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
