### ISSUE TITLE
Crash when opening issue from link in commit message

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#702]
**App Version: 3.2.0**

**OS Version: 25**

**Model: Google-Pixel**

 If I go to a commit that has links to an issue in its message, and tap one of those links, the issue loads, and then the app crashes.

**Comment by k0shk0sh** [comment]
Link please

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
https://github.com/k0shk0sh/FastHub/commit/a8aa669c42e7a982990ce427924a1af64821e2b7

**Comment by k0shk0sh** [comment]
@eygraber got it, Thanks man :) . Fyi: pr reviews are done ;)

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
I saw that in the debug builds. Totally made my week! I really like how it was implemented 😄

**Comment by k0shk0sh** [comment]
Hmm, due to the list is still being populated for commit files, the app will crash with `TooLargeTransication`  which I got no idea why :D

**Comment by k0shk0sh** [comment]
If all the files loaded, clicking on link will work. strange :D

**Comment by k0shk0sh** [comment]
@eygraber  I assume you have an Enterprise account? Can u join FastHub slack so I could pass u test apk to test it out :p

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
@k0shk0sh I tried to through the app. It says the link expired.

**Comment by k0shk0sh** [comment]
@eygraber I just implemented it, so haven't committed it yet. Want me to commit so you give it a shot?

_Sent from my Htc m8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@eygraber the link will always expire after 5 min. Just go to app veyor and re-download 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eygraber** [comment]
I should've been more specific. I was referring to the slack link.

**Comment by kutsan** [comment]
@eygraber I updated the link, can you check it out again? Honestly, we are having problem how we would invite people to Slack. Slack doesn't accept public invitations, so we use shared invite link. The problem is, that link always expire after 1 week. Someone needs the updated it.
