### ISSUE TITLE
Crash on empty repo

### ISSUE THREAD

**Issue by joe2k01** [k0shk0sh/FastHub#703]
**App Version: 2.5.3**

**OS Version: 25**

**Model: samsung-SM-T813**

 Hi, I just found out that opening an empty repo results in a crash. The app recognizes that the repo is empty creating a toast but then crashes. If you need a log tell me what do I have to grep in logcat

_Sent from my Samsung SM-T813 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by joe2k01** [comment]
Upgrading to latest version fixes the issue. You should update the apk in XDA labs

_Sent from my Samsung SM-T813 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@joe2k01 we have problems updating apk in XDA #yakov16

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@joe2k01 XDA is having issues with any app that has been compiled with Android Studio 3.0. They are working on a fix.

For now you can download from GitHub the latest

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
