### ISSUE TITLE
Share URL is using generic text/* type instead of text/plain

### ISSUE THREAD

**Issue by talhacohen** [k0shk0sh/FastHub#705]
In shareUrl@HelperActivity the save intent is using the generic MIME Type text/* instead of indicating text/plain.

It doesn't have any major effect, though it's cleaner and the type should indicate what you are sharing.
(In addition, it's possible to add the title of the link that is shared)

**Comment by k0shk0sh** [comment]
Hey thanks for reporting this, wouldn't specifying the file as text will eliminate some apps from appearing? For example if some app listening to `.java` and the file you shared is a Java a file would the app ever be able to receive the intent? 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by talhacohen** [comment]
Hey, true it will eliminate some apps (I haven't thought about it).
Maybe I miss something, but you are not sharing the URL itself and not the java file, will an app that listens to .java will know how to handle it? wouldn't it be as EXTRA_STREAM as a file?

**Comment by k0shk0sh** [comment]
@talhacohen yep, you're right, only urls that I'm sharing, would you like to submit a PR with the changes? Or should I proceed with changing it?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by talhacohen** [comment]
I'll send a PR later today.
Thanks!

**Comment by k0shk0sh** [comment]
@talhacohen alright thanks :) 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh does this have to do with #489?

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 nope, unrelated. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
