### ISSUE TITLE
First comment date is displayed wrongly

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#706]
I've noticed the date of the first comment is displayed wrongly and equals the date of the last comment. Also, likely, it's marked as updated, even if GitHub UI doesn't show that.

For instance:
![photo_2017-06-27_17-06-26](https://user-images.githubusercontent.com/1074182/27591669-0e347184-5b5b-11e7-82e4-897a0af5caf8.jpg)

It looks like I've updated the first comment a few minutes ago, however that is not true and you check it [here](https://github.com/AutoFixture/AutoFixture/issues/747). Actually, the [last comment](https://github.com/AutoFixture/AutoFixture/issues/747#issuecomment-311347510) was added at that time. 

This issue happens with open PRs as well.

Thank you!

---

 - FastHub Version: 3.2.0
 - Android Version: N
 - Phone Model: Xiaomi MI5

**Comment by k0shk0sh** [comment]
This is a test comment

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Yeep, it seems like the updated date is actually when something happened to the issue and not like editing the issue itself, I guess the best thing to do, just remove the checking for the pr/issue detailes. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
