### ISSUE TITLE
Bug | Progress bar bug when loading missing README.MD

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#708]
**App Version: 3.2.0**

**OS Version: 24**

**Model: samsung-SM-G950F**

 If a repo have not README.md, you will get a empty progress bar, and an empty page. To fix check if the repo have a readme. Then if a readme cannot be parsed FastHub should load a dedicated image to explain at the user the problem

**Comment by yakov116** [comment]
@AndreaCioccarelli Thanks for reporting!

@k0shk0sh #613 was probably the cause

**Comment by k0shk0sh** [comment]
@yakov116 what 613 has to do with this?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh prob when you removed the toast this happened

**Comment by k0shk0sh** [comment]
@yakov116 I guess you were right. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh as always :)

_Sent from my HTC Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
