### ISSUE TITLE
Refresher circle(or icon) not stopped

### ISSUE THREAD

**Issue by ozcaan11** [k0shk0sh/FastHub#710]
**App Version: 3.2.0**

**OS Version: 25**

**Model: General Mobile-General Mobile 4G**

 At notification > all tab the refresher icon doesnt stop 

_Sent from my General Mobile 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Noticed that yesterday and fixed it, will close this with my next commit.
Thanks

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ozcaan11** [comment]
Ok 👍
