### ISSUE TITLE
Show owner and Original Poster

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#712]
**App Version: 3.2.0-debug**

**OS Version: 25**

**Model: unknown-Android SDK built for x86**

 ![image](https://user-images.githubusercontent.com/16872793/27692125-ed0c4900-5cb3-11e7-9579-29f32af39d5d.png)

![image](https://user-images.githubusercontent.com/16872793/27692147-f691d454-5cb3-11e7-8292-ff76ac2dfe5c.png)

![image](https://user-images.githubusercontent.com/16872793/27692154-fb0a6c26-5cb3-11e7-8522-80921beba6ce.png)

_Sent from my Unknown Android SDK built for x86 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
> _Sent from my Unknown Android SDK_

Alright.

**Comment by yakov116** [comment]
@wasdennnoch 😄 
Its an emulator

**Comment by yakov116** [comment]
Cxz

_Sent from my Android Emulator using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Skayo** [comment]
Also show Collaborator and Contributer please!

**Comment by k0shk0sh** [comment]
@Skayo not possible, as there is no way I could tell unless i make API call for each comment.
