### ISSUE TITLE
Pricing is treated as a user

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#728]
**App Version: 3.2.0**

**OS Version: 25**

**Model: Google-Pixel**

 Opening an https://GitHub.com/pricing link treats it as a user. It should probably redirect to the browser.

**Comment by k0shk0sh** [comment]
could you add this to your PR? simply to this list https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/java/com/fastaccess/provider/scheme/LinkParserHelper.java#L25

**Comment by yakov116** [comment]
was this not fixed in 1c24c2b10db5d6703e55f166c7c7b77b5dd6e554 ?
