### ISSUE TITLE
Unsubscribe emails

### ISSUE THREAD

**Issue by yuyang1995** [k0shk0sh/FastHub#729]
**App Version: 3.2.0**

**OS Version: 23**

**Model: ZUK-ZUK Z1**

 I have received a lot of emails from this project. I have tried to unsubscribe several times but I still received a very very large numbers of emails. Please help me.

**Comment by yakov116** [comment]
@yuyang1995 are watching this repo?

**Comment by k0shk0sh** [comment]
@yakov116 thanks for being around yanki <3

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yuyang1995** [comment]
The emails says,
> You are receiving this because you are subscribed to this thread.
View it on GitHub or mute the thread.
I have clicked `mute the thread` several times but I still received a lot of emails.

**Comment by k0shk0sh** [comment]
mute the thread from where? 

are you watching the repo? if so, simply click the `eye` icon in FastHub Repo and it will unsubscribe you.

**Comment by yakov116** [comment]
@yuyang1995 will only mute **that** issue

**Comment by yuyang1995** [comment]
Thank you very much.
