### ISSUE TITLE
Check notifications whenever app lauches only

### ISSUE THREAD

**Issue by poutros** [k0shk0sh/FastHub#730]
**App Version: 3.2.0**

**OS Version: 25**

**Model: LGE-LG-D855**

Add an option to only check notifications when app launches.

**Comment by yakov116** [comment]
@poutros but then you have the feed. no?

**Comment by poutros** [comment]
The feed and the notifications are different. My feed is filled with unimportant stuff.

**Comment by poutros** [comment]
Basically, what I was thinking was to open the app and see the notification icon with the notifications. For example, fasthub didn't notify me of your comment because I have set the interval to 3 hours. I also use greenify so background processes for fasthub are stopped if the app is hibernated. When I reopen fasthub, I don't see if I have anything new because it didn't check anything.

**Comment by yakov116** [comment]
>And it doesn't tell me when someone comments on my issues like you just did.

How would this help?

**Comment by poutros** [comment]
Notifications tell me when someone comments on my issues.

**Comment by k0shk0sh** [comment]
Why not open the notifications yourself since you already opened the app too quickly check?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by poutros** [comment]
I can but it would save me time and I usually forget to open the notifications anyway.

**Comment by yakov116** [comment]
@poutros so what exactly should be done?

_Sent from my HTC Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by poutros** [comment]
@yakov116 What do you mean?
