### ISSUE TITLE
Loved it

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#734]
**App Version: 3.2.0-debug**

**OS Version: 21**

**Model: LGE-LG-F460L**

 Damn, the free dark theme is awesome!
Also the code themes.

_Sent from my LGE LG-F460L using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
This should have been in slack 😛

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
Oops! Didnt knew it was going straight to the issues.
