### ISSUE TITLE
Load Readme 

### ISSUE THREAD

**Issue by juliandavidmr** [k0shk0sh/FastHub#736]
**App Version: 3.2.0**

**OS Version: 24**

**Model: motorola-Moto G (4)**

The load bar in the Readme file goes blank when the repository does not exist.

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@juliandavidmr instead of?

**Comment by juliandavidmr** [comment]
Hi @yakov116 , That is to say, I propose that the bar does not continue loading but it shows a message saying that there is not yet a readme available.

**Comment by yakov116** [comment]
@juliandavidmr can you paste a link with the repo your talking about?

**Comment by yakov116** [comment]
@juliandavidmr I take that back
This is duplicate of #708
