### ISSUE TITLE
[FR] Switch between rendered MD and MD syntax

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#738]
**App Version: 3.2.0**

**OS Version: 21**

**Model: LGE-LG-F460L**

 There are times when i want to see the syntax of the markdown files. Can you add a simple button in the overflow menu (to switch between rendered markdown and and markdown syntax.  

_Sent from my LGE LG-F460L using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
Maybe you can just show the `Raw` file

@k0shk0sh

**Comment by k0shk0sh** [comment]
@cozyplanes aware of that, will try n make it on next release. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
thz
