### ISSUE TITLE
Tool crashes when PR is opened

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#739]
Open [this PR](https://github.com/AutoFixture/AutoFixture/pull/773) and try to scroll down to the bottom. In my case application crashes somewhere in the middle of the PR :(

-------

**App Version: 3.2.0**

**OS Version: 24**

**Model: Xiaomi-MI 5**

**Comment by k0shk0sh** [comment]
Yeep, crashes I'll look into it once I'm on my laptop. Thanks.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment]
I've submitted you the Android report and added issue ID to description.

**Comment by k0shk0sh** [comment]
@zvirja thanks alot & sorry for the inconvenience. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zvirja** [comment]
No problem, thanks for looking into this :wink:

**Comment by k0shk0sh** [comment]
Alright, got what is the cause, `requested_team` which I didn't handle this & always thought that its `requested_reviewer` :'(  ... its fixed and will be released tomorrow hopefully.
