### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by AdrianVovk** [k0shk0sh/FastHub#74]
I'm signed into my account and I belong to an organization. Please give me a way to view my feed from the organization perspective.

**Comment by AdrianVovk** [comment]
I just noticed that this is a duplicate of #47. Closing

**Comment by k0shk0sh** [comment]
@AdrianVovk hello Adrian, I'm trying my best to bring this very soon, please stay tuned for it.

**Comment by AdrianVovk** [comment]
@k0shk0sh Thank you! Looking at this comment thread I noticed that references (#1 @user) don't show up as links in comments.

**Comment by k0shk0sh** [comment]
yup, neither issues hashtags, I did implement that yesterday night but find it ugly so I removed it, going to look in a better way in implementing this since even links with names aren't handled properly yet. still more for improvements here and there but I'm on them.
