### ISSUE TITLE
Inconsistent Status Bar Colors

### ISSUE THREAD

**Issue by smiller171** [k0shk0sh/FastHub#742]
**App Version: 3.2.0**

**OS Version: 26**

**Model: Google-Pixel**

 In some screens with the dark blue theme you are using black status bar icons instead of white, which is difficult to read

![Status Bar unreadable](http://i.imgur.com/zjS9ocy.png)

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
There is no way that I'm having custom themes for each screen but rather a theme for overall. Could you restart the app and let me know if it worked?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by smiller171** [comment]
huh, I thought I had already rebooted, and it had at least been overnight since I opened the app, but killing the app seems to have fixed it.

**Comment by k0shk0sh** [comment]
@smiller171 restarting app isn't required in many devices but for some devices it is really required which I guess the system UI is not updated instantly just a guess tho. But I'm glad it worked for u :). Thanks for your support.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
