### ISSUE TITLE
FastHub crashes Nexus 7

### ISSUE THREAD

**Issue by FloEdelmann** [k0shk0sh/FastHub#744]
I have a very weird issue. Installed the latest version on both my phone (Motorola Moto X, Android 6.0.1, CyanogenMod 13) and my large tablet (bq Aqaris M10 FHD, Android 6.0.1, stock rooted) with no problems. Installing from Google Play Store on my old Nexus 7 (Android 5.1.1, CyanogenMod 12.1) worked. But now, every time I open my home screen (Trebuchet, default CyanogenMod launcher), it immediately crashes before I can open any app, rendering my tablet completely unusable. I also tried it using Nova Launcher with the same result. I then tried uninstalling via the settings app, but even the package installer app crashes. Uninstalling via the Play Store worked fine though and resolved all the issues. I could reproduce it by reinstalling.

I guess this sounds as weird to you as it does to me, but maybe you have a starting point for me to debug and find out more details.

**Comment by yakov116** [comment]
@FloEdelmann we have had this issue before. It's Google services crashing

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Can u please follow steps in here to get me a crash report? 

https://github.com/firebase/firebase-jobdispatcher-android/issues/116

As the crash report embedded into FastHub doesn't say much since this is an internal bug in the google play service. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FloEdelmann** [comment]
[bugreport-2017-07-11-07-15-55.txt](https://github.com/k0shk0sh/FastHub/files/1137802/bugreport-2017-07-11-07-15-55.txt)

**Comment by FastAccess** [comment]
@FloEdelmann thank you very much, I'll be given the crash report to firebase and see what they can do about it.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@FastAccess thanks :)

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FastAccess** [comment]
@yakov116 damn, now I'm confused lol. I thought I'm using my acc lol

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@FloEdelmann that log doesn't really show much, gonna update to `0.7.0` and push a commit right now, could you then install the debug version of FastHub from the readme nightly builds link & test it again.

**Comment by k0shk0sh** [comment]
Oops, sorry about that @FloEdelmann 

Could you tell me what is your Google Play service version?

**Comment by FloEdelmann** [comment]
`11.0.55 (230-156917137)`, as it says in *Google Settings → Help → Version Info*

**Comment by k0shk0sh** [comment]
my version is 

`11.0.66 (448-156917137)` i'll try and pass that info to Firebase team as well, maybe they could do something about it which i doubt, since it will require you to at least to update your GPS.

**Comment by k0shk0sh** [comment]
I guess there is nothing I can do in here anymore :'( https://github.com/firebase/firebase-jobdispatcher-android/issues/116#issuecomment-315532971

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FloEdelmann** [comment]
Thanks anyway, maybe this is a reason to try out Lineage OS on my old device then :)

**Comment by k0shk0sh** [comment]
@FloEdelmann I had Lineage nightly on my old HTC m8 which basically was the device which I developed FastHub on, I'm really sorry for this, but I simply can't know what is going nor how to fix it as it seems like internal bug than FastHub, maybe you could try disabling CM theme engine? (just a random guess). 

Let me know when you upgrade and how it went with you.

**Comment by k0shk0sh** [comment]
@FloEdelmann I hope you didn't yet install Lineage OS, I have just cloned Firebase job dispatcher, made some slight changes on it to avoid the crash and hopefully it will work, can you please let me know your email to send you a test apk?

**Comment by FloEdelmann** [comment]
I didn't – currently I don't have the time to tackle projects this big 😉 

My email is florian-edelmann@online.de. Let's hope that I can install it without the package installer crashing...

**Comment by k0shk0sh** [comment]
@FloEdelmann can you install 4.0.2 from PlayStore? Hopefully it will fix your issue. I really hope so

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FloEdelmann** [comment]
I have tried both the version from the play store and the latest debug version (at the same time, uninstalling the debug version also crashes) and unfortunately, the issues persist.

**Comment by k0shk0sh** [comment]
@FloEdelmann i'm reworking on the firebase library, i'll email you a build once I'm done, this thing has to be done unless if really really there is no way :D

**Comment by szachara** [comment]
Ok, so I will wait for stable Lineage 13, then try it again, because cyanogenmod is death.

**Comment by k0shk0sh** [comment]
@szachara thanks for your understanding, I tried my best without any luck, according to firebase team its  CM theme that crashes :'( . I hope this sort out for you guys

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by szachara** [comment]
I read whole thread on firebase, good work thx
