### ISSUE TITLE
[FR] Ability to open github links in fasthub

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#745]
**App Version: 3.2.0**

**OS Version: 21**

**Model: LGE-LG-F460L**

I want to open github links in fasthub

- Browser-> go to github repo-> share-> click `open with fasthub` -> opens in fasthub

**Comment by k0shk0sh** [comment]
this fixed with 6360f03986e85ccec4e9c23780dbddd2c71c0a86
