### ISSUE TITLE
Followers list order

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#75]
_Followers order should be ordered from newest to oldest_

**Comment by k0shk0sh** [comment]
the current api does not provide specific order of follower/following order.

**Comment by raisedadead** [comment]
Hi @k0shk0sh apologies for the duplicate issue, I just did a quick visual diff of the follower list on GitHub and the app, and to me, it looks that the API is giving the data set in 1st to the latest follower.

So, simply reversing the order should be enough.

But, that said it's my quick analysis.

Meaning, this approach is, of course, undocumented, and not being an Android dev, I can not gauge the cost of implementation too.

I'll let you put your thoughts into it.

Thanks and happy coding.

**Comment by k0shk0sh** [comment]
I was thinking about this all the time, but it requires some magic plus an extra api call to determine the whole pagination. 

but I really would love to do it, I'll notify this issue if I ever got time for it
