### ISSUE TITLE
Option Spain

### ISSUE THREAD

**Issue by MoonAntonio** [k0shk0sh/FastHub#750]
**App Version: 3.2.0**

**OS Version: 24**

**Model: samsung-SM-G928F**

 In options languajes no view spain options.

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/qAA0ERl.png)


It's the last language. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
