### ISSUE TITLE
[Bug] No comments are shown when loading commit from a pr

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#752]
**App Version: 3.2.0**

**OS Version: 25**

**Model: HTC-Nexus 9**

 Look at the following pictures 

![](http://i.imgur.com/Kuqy2jF.png)

![](http://i.imgur.com/Tsztofq.png)

Look at the last pull request on FastHub to reproduce 

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
What is this issue? I can't understand??? You made comments in the PR and you want them to appear in commit? How is that even possible?? 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
I just commented either normal or on code line and everything seems to be fine, could you tell how did you comment or is there any comments actually?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh open this pr in GitHub and you will see.


There were comments on one of the commits, if you go to his repo and you go to the commit you will see the comments. But when you open the commit from the PR you will not see any comments

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh below is a pic of when I open the commit from his repo


![](http://i.imgur.com/wX6lMwc.png)


_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
This is a pic from the pr on github

![image](https://user-images.githubusercontent.com/16872793/28197594-f3368020-6825-11e7-908f-621e10fb7e30.png)

**Comment by k0shk0sh** [comment]
So did you comment in here or you commented in there? Could you elaborate?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
I commented on the commit in his repo

**Comment by k0shk0sh** [comment]
Hmmm. 😔😔😔

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
these comments are now displayed in the PR.
