### ISSUE TITLE
Show number of changes in a PR

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#754]
**FastHub Version: 4.0.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- Google  
- google  
- Pixel  
- Account Type: GitHub

---

 GitHub shows the amount of additions and deletions for commits and PRs

![](http://i.imgur.com/xC7rg5F.png)

**Comment by k0shk0sh** [comment]
Isn't that showing in FastHub in the Commit top header? and on each file ?

**Comment by eygraber** [comment]
@k0shk0sh good point. Didn't notice that for commits. But it isn't there for PRs

**Comment by yakov116** [comment]
Amazing!
