### ISSUE TITLE
Indicate that a PR line has a comment

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#755]
**FastHub Version: 4.0.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- Google  
- google  
- Pixel  
- Account Type: GitHub

---

 There's no way to tell if a line has a comment on it.

**Comment by k0shk0sh** [comment]
in Commits there is in the comment, there will be something like (commented on line **1** in path) in PR, there are in details screen.

**Comment by eygraber** [comment]
@k0shk0sh I'm talking about during a review

**Comment by k0shk0sh** [comment]
owh, you while doing the review changes? then this is valid FR.
