### ISSUE TITLE
Default code colour palette to prettify_dark when using dark themes

### ISSUE THREAD

**Issue by Younes-L** [k0shk0sh/FastHub#758]
**FastHub Version: 4.0.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- htc  
- google  
- Nexus 9  
- Account Type: GitHub

---

 Additionally, since most palettes have their dark version, you could make it so that switching from a light to a dark theme (or vice versa) also affects the code palette.

**Comment by yakov116** [comment]
@Younes-L IMHO that whole menu has to be done :) 
We started redoing it (look [here](https://github.com/k0shk0sh/FastHub-code-theme-images)) but there was too much work involved.

**Comment by k0shk0sh** [comment]
in a second thought, this will be plenty of work to do, i'll have to restructure 81 themes and convert them to an object, where i have manually go to each theme and decide that this is a light them or dark theme and will have to fall to something else if its dark/light, 

In a second thought, its more to the user and not the developer to choose the theme, by default there are two themes which will work on light & dark (depending on the theme selected) unless if someone, wants to go and make a list or a json object of the list like below, i wont really mind 

```
[
  {
    "light_theme": "Younes-L",
    "dark_theme": "Younes-L-Dark"
  },
  {
    "light_theme": "Yanki",
    "dark_theme": "some alternative theme"
  }
]
```
