### ISSUE TITLE
Signature validation for purchases are able to be bypassed

### ISSUE THREAD

**Issue by MisterBianco** [k0shk0sh/FastHub#759]
**FastHub Version: 4.0.1**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- samsung  
- samsung  
- SM-N9005  
- Account Type: GitHub

---

Using apps like lucky patcher and freedom, purchases are able be made for free. Implementing signature validation or some other check for purchase authenticity could be good for security of the app. 

I only used this method on your app to report it if it worked. Not trying to be a thief. This is the best client for github by far and deserves the donations.

**Comment by yakov116** [comment]
@MisterBianco Thanks for reporting!

This is an open source project and anyone can go and compile them self. I will wait for @k0shk0sh for his input, but I don't think he will go any great lengths to attempt to fix this.

Thanks for being on the lookout

**Comment by MisterBianco** [comment]
Still thought it was worth reporting. 
I am not 100% sure of the difficulty of protecting against this but I don't think it requires too much effort although I understand having it open source does limit security of the few purchases of the app. 

Either way kudos to such a great client. :)

**Comment by wasdennnoch** [comment]
@MisterBianco Lucky Patcher can also disable signature validation, there really is nothing good that protects against piracy reliably. And Xposed could just hook into those protections as well. Currently the only good detection would be SafetyNet but that doesn't really make sense in an app that gets used by many modders.

**Comment by MisterBianco** [comment]
Fair enough, although I have seen apps that detect lucky patchers lvl
emulation and won't open... So it is possible but I see your point. :/

**Comment by k0shk0sh** [comment]
Thanks for reporting and understand your point, but as others mentioned, I think I can't do much about it, matter of fact, running the debug version of FH will have all features unlocked. 
So really can't do much, the app is for developers & I'm sure they know how it feel when someone steal their beef. So its up to the community :)

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
