### ISSUE TITLE
RecyclerView animation settings don't take effect immediately

### ISSUE THREAD

**Issue by BehindTheMath** [k0shk0sh/FastHub#76]
I turned off the RecyclerView animation in Settings, but it didn't work right away. I had to back out of the app and relaunch it.

**Comment by k0shk0sh** [comment]
It works this way tho, I don't to call `PreferenceManager' Every time you touch the list. so it should be work as intended.

**Comment by k0shk0sh** [comment]
One way I think of that could solve this is just forcing the whole app to be recreated. I will think about it tho and see what could be the best way to go around it.

**Comment by BehindTheMath** [comment]
Can you have `BaseRecyclerAdapter` implement an [`OnSharedPreferenceChangeListener`](https://developer.android.com/reference/android/content/SharedPreferences.OnSharedPreferenceChangeListener.html)? That way it could be notified as soon as the setting is changed so it can set `enableAnimation`, and you wouldn't have to manually keep checking the `PreferenceManager`

**Comment by k0shk0sh** [comment]
@BehindTheMath this would be another possible way, but then I will have to decouple the adapter with activities & fragments life cycler where I will need to unregister that listener.  my previous suggestions is the only thing I could think of right now. I will see what I can do about it.

**Comment by k0shk0sh** [comment]
@BehindTheMath it'll be in 1.1.0 which I might release it later today or tomorrow.
