### ISSUE TITLE
Why would app's feedback be full of my email？

### ISSUE THREAD

**Issue by lynxhawk** [k0shk0sh/FastHub#762]
**FastHub Version: 4.0.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- asus  
- google  
- Nexus 7  
- Account Type: GitHub

---

It seems many feedback e-mails are forwarding to me.How can I cancel it?

**Comment by k0shk0sh** [comment]
Simply click on the `eye` icon in FastHub, this is how GitHub behaves, once you watch a repo, you will be receiving stuff from it unless you specify not to. 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lynxhawk** [comment]
@k0shk0sh Thanks for your reply. I have understood it.


_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Google Nexus 7 发送_
