### ISSUE TITLE
Touchscreen not responding

### ISSUE THREAD

**Issue by Apply55gx** [k0shk0sh/FastHub#763]
**FastHub Version: 4.0.1**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- Sony  
- Sony  
- Xperia Z1  
- Account Type: GitHub

---

 When you open up the app(after the process was stopped) the app doesnt responds to touchscreen interactions.
After you press the home button and open the app again everything is fixed.

**Comment by k0shk0sh** [comment]
After the process has stopped does that mean the app crashes? Also can you provide more info, such as where did you install the app?

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NeoChontrix** [comment]
Nope the app didn't crash. If you open the app while it is not running in the background already it will not respond to any interactions until you go back to home/other app and open it again.

I got the app from the Github release page.

**Comment by k0shk0sh** [comment]
Hmm,  I guess I know why, and already fixed that `hopefully` . could you guys tell me from where you installed the app? Playstore or somewhere else?

**Comment by k0shk0sh** [comment]
@NeoChontrix I assume you don't have google play service? Am I right?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NeoChontrix** [comment]
Yep no google stuff

**Comment by k0shk0sh** [comment]
@NeoChontrix well yep, that ensures my assumption and have made a fix for it, if you don't mind, I could send u a test apk, to test it out. You could pass me ur email and I'll send it right away

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NeoChontrix** [comment]
johnz@posteo.net

**Comment by k0shk0sh** [comment]
@NeoChontrix Please check your email

**Comment by NeoChontrix** [comment]
@k0shk0sh this version does hang in the splash screen...

**Comment by k0shk0sh** [comment]
dang, one minute

**Comment by k0shk0sh** [comment]
building new one & sending to your email :'(

**Comment by k0shk0sh** [comment]
@NeoChontrix please check ur email.

**Comment by NeoChontrix** [comment]
@k0shk0sh thx, works fine now

_Sent from my ZUK Z2 Plus using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Apply55gx** [comment]
@k0shk0sh I installed it also from Github

**Comment by k0shk0sh** [comment]
nice :D . alright then,  it will be in next release

**Comment by Apply55gx** [comment]
Cool😀

**Comment by k0shk0sh** [comment]
sorry for the inconvenience caused :)
