### ISSUE TITLE
Screen flickering issue in README

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#764]
**FastHub Version: 4.0.1**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- LGE  
- lge  
- LG-F460L  
- Account Type: GitHub

---

 When scrolling in readme ( especially long one, and especially the very top ) the screen flickers. ( i have no idea how to explain this though, just flickers like crazy )

_Sent from my Lge LG-F460L using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
you said it yourself, long readme, its more of Android `WebView` than FastHub, its known issue in WebView and it was never been fixed.

**Comment by k0shk0sh** [comment]
als i'm curious to know which readme, can you point me to it.

**Comment by cozyplanes** [comment]
Any long one, like fasthub

_Sent from my Lge LG-F460L using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
with FastHub never had a problem, maybe its your device webview version problem
