### ISSUE TITLE
App hangs when trying to buy/donate without Google play services.

### ISSUE THREAD

**Issue by Apply55gx** [k0shk0sh/FastHub#765]
**FastHub Version: 4.0.1**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- Sony  
- Sony  
- Xperia Z1  
- Account Type: GitHub

---

 When I click a buy/donate button the app hangs and can't be used until restart.

I think this is because I dont have google play services installed.

**Comment by k0shk0sh** [comment]
yep & I don't know what should I do about it ;D, I mean to be fair for all tho, by right I shouldn't unlock them if I detected no Google Play service, and also I don't know of any other alternatives for IAP, so i'll really need to know more about this scenario.

**Comment by k0shk0sh** [comment]
P.S: in Debug, the features can be easily unlocked, just by tapping unlock, but the debug version really meant for testers and not production users.

**Comment by Apply55gx** [comment]
I thought maybe you could do it so it just shows a message that Google Play services are needed for this or something like that. ;)
