### ISSUE TITLE
[FR] Add copy to URL in commits and pr's

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#773]
**FastHub Version: 4.0.2-debug**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: HTC  
- BRAND: google  
- MODEL: Nexus 9  
---

 Add copy url's to the above  

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh

**Comment by yakov116** [comment]
@k0shk0sh plase all copy SHA too thanks

**Comment by k0shk0sh** [comment]
Hmm, this has been added in 4.0.3 however the hash not. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
![gif](https://media.giphy.com/media/720g7C1jz13wI/giphy.gif)

**Comment by k0shk0sh** [comment]
Hi

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Test

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
