### ISSUE TITLE
[FR] Setting  custom notification sound. 

### ISSUE THREAD

**Issue by cdysthe** [k0shk0sh/FastHub#775]
It would be helpful with an option to set a custom notification sound to be able to identify FastHub notifications sonically. 

_Sent from my BLU Life One X2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@cdysthe if I am not mistaken this has been requested before and there is no simple way how to do this.

Thanks for your feedbac!

**Comment by k0shk0sh** [comment]
@yakov116 , yep it has been requested before, @JediBurrell actually did that, but I guess he forgot to add the sound picker, lets see if Jedi, still interested on taking this.
