### ISSUE TITLE
Python multi-line string syntax highlighting

### ISSUE THREAD

**Issue by totallyhuman** [k0shk0sh/FastHub#777]
**FastHub Version: 4.0.1**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- OnePlus  
- OnePlus  
- ONEPLUS A3000  
- Account Type: GitHub

---

Python has multi-line strings denoted by `"""text"""`. However, the syntax highlighting does not parse this correctly:
 
![](http://i.imgur.com/2FfzkhA.png)

Any love for the Pythons? :D

**Comment by k0shk0sh** [comment]
@totallyhuman thanks for reporting this, I don't I'll be able to fix this as this is a plug-in bug and not really FastHub. The better place to report this would be  `highlightjs`

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by totallyhuman** [comment]
Ok, thanks for letting me know. FYI, this only occurred a few updates ago. Did you happen to change the plug-in used?

**Comment by k0shk0sh** [comment]
@totallyhuman yep I did, I was using Google prettify, but let it go as it wasn't really working properly on some other languages. That's the beauty of fragmentation, you fix something for some, it breaks for some others 😅

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
