### ISSUE TITLE
Graphics-Bug: Buttonbar is transparent

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [k0shk0sh/FastHub#779]
**FastHub Version: 4.0.2**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: LGE
- BRAND: google  
- MODEL: Nexus 5X  
---

Hi,

on my device the buttonbar of Android (back, home, recent apps) is transparent. The app background is white and so is the buttonbar. But the buttons are also white which means that I have white buttons on white background... This happens on nearly all pages (activities), tested on the personal news startpage and the notification page. Screenshot:

![screenshot](http://i.imgur.com/S7l1TRX.png)

Thanks for the great app and the heavy development!

**Comment by k0shk0sh** [comment]
Go to settings/customization/disable navbar tinting, restart app and you should be good to go.


_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NIPE-SYSTEMS** [comment]
Thanks for the fast answer! It is fixed for me now!

What is the feature/idea behind that tinting? It is enabled by default, I guess, but decreases usability (on my device)?

**Comment by k0shk0sh** [comment]
The light theme slipped and shouldn't be tinted. I have fixed it and should be dark by default next version

![](http://i.imgur.com/7XijPxF.png)

![](http://i.imgur.com/sclVYWO.png)

![](http://i.imgur.com/fLTUMNZ.png)


_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/yYfXSiI.png)


_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NIPE-SYSTEMS** [comment]
Sounds great! Looking forward to this version. Thanks! 👍
