### ISSUE TITLE
Markdown doesn't render HTML tables

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#78]
I guess your markdown parser either doesn't support inline HTML or doesn't support GitHub flavored markdown

**Comment by k0shk0sh** [comment]
Are you referring to the Readme or comments? if Readme then it definitely does, however for comments, it literally doesn't really work properly, I hope in 1.0.7 it would be much better.

**Comment by HeinrichReimer** [comment]
I checked it for issue descriptions such as https://github.com/pinpong/equalizer-issue-tracker/issues/269

**Comment by k0shk0sh** [comment]
I'll use as a reference for my testing, thanks

**Comment by HeinrichReimer** [comment]
I can also confirm that tables work properly in readme files.
