### ISSUE TITLE
Latest version 4.0.2 doesn't work here...

### ISSUE THREAD

**Issue by repsorp** [k0shk0sh/FastHub#780]
stuck on logo after launch

nexus 5x
android 7.1.2

**Comment by yakov116** [comment]
@repsorp You don't have google play services? This will be fixed.
Please uninstall and go back to 4.0.1

**Comment by repsorp** [comment]
Ok
Done
Thanks

**Comment by yakov116** [comment]
@repsorp Sorry we attempted to fix something and we broke another.

**Comment by k0shk0sh** [comment]
Matter of fact 4.0.2 has the fix for Google Play Service and 4.0.1 shouldn't actually 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 no we e didn't, it worked fine on all the other devices that don't have google play service, so I'm not really sure what's up with his phone. 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@repsorp  please update to 4.0.3 which has more workarounds around your case, the penalty, is 10 seconds of waiting tho. as i'm not even sure how could it stop in your case since i'm making sure that GPS check is there but you seem like passing it with success or something went nuts.

**Comment by repsorp** [comment]
Still stuck on logo on launch with 4.0.3

But FastHub notifications are ok (was the case with 4.0.2 also)

If I click on notification then FastHub opens a new window (stuck logo window still there) and seems to work fine.

Couldn't find any detail in log.



_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
In 4.0.3 you'll have to wait for 10 seconds, if the whole process didn't succeed then it will launch the main screen even tho as I said, it should open if it triggers that you don't have the GPS, could you tell me your device info? plus did you wait for 10 seconds in 4.0.3?

**Comment by repsorp** [comment]
Ok
It's working fine after waiting 10sec
GPS not activated

device: LGE bullhead | Nexus 5X | google | N2G47Z
Android version: 7.1.2 | REL

**Comment by k0shk0sh** [comment]
@repsorp so its there, but its not activated? then this is the case, I only check if its available or not. the reason I put 10 seconds because I can't know for sure the time amount my implementation would take to check for your In-App-Purchase (IAP)  it usually would take 1 second, but yet, can't be sure that it will be the case on every device. 

I suggest you to remove it at all if you want to avoid this waiting time which can be SUCKS.

**Comment by repsorp** [comment]
Don't get it...
Remove it at all ? You mean the GPS ??

**Comment by k0shk0sh** [comment]
@repsorp  yep, the GPS, it seems like you passing the Google Play Service availability checking & went into IAP purchase check which in return doesn't really work because the GPS isn't working properly. /shrug

**Comment by repsorp** [comment]
How am I supposed to do that, remove it all ??
And what if I need it later ?

**Comment by k0shk0sh** [comment]
Well, you disable something that most Android APPs rely on, for example, push notifications, IAP, & alot more. 

I have improved my checking but can't be sure it'll work, but it will be added next time. 

```
public static boolean isGoogleAvailable(@NonNull Context context) {
        int status = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(context);
        return status != ConnectionResult.SERVICE_DISABLED && status == ConnectionResult.SUCCESS;
    }
```

**Comment by repsorp** [comment]
I have no problem with any of my other apps even with disabled gps which is activated when I really need it...
I'll give a look to your next version though
My best
