### ISSUE TITLE
Can't access Wiki of private Repo

### ISSUE THREAD

**Issue by JulianBerger** [k0shk0sh/FastHub#782]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G950F  
---

 I get an "Error occured while communication with the server" error... 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
#726

**Comment by k0shk0sh** [comment]
> Why my Private Repo Wiki does not show up?
It's due to FastHub scraping GitHub Wiki page & Private Repos require session token that FastHub doesn't have.
