### ISSUE TITLE
Don't load some README

### ISSUE THREAD

**Issue by pda11111** [k0shk0sh/FastHub#785]
**FastHub Version: 4.0.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- MANUFACTURER: BQ
- BRAND: BQ  
- MODEL: BQS-5520  
---

 Don't load README in twbs/bootstrap

**Comment by yakov116** [comment]
@pda11111 what? 

Please include a link and a brief description. 

Also please note there was an update today to version 4.0.3

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
