### ISSUE TITLE
进入有问题

### ISSUE THREAD

**Issue by netw0rm** [k0shk0sh/FastHub#787]
**FastHub Version: 4.0.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: HUAWEI
- BRAND: HONOR  
- MODEL: NEM-AL10  
---

 有时候会出现进入不了应用的情况

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 HONOR NEM-AL10 发送_

**Comment by k0shk0sh** [comment]
English please

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh "Sometimes there will be no application of the situation"

**Comment by netw0rm** [comment]
sometimes  it stopd at the logo ,  not  into the app
...

**Comment by k0shk0sh** [comment]
#780
