### ISSUE TITLE
Profile Pictures not updating within app

### ISSUE THREAD

**Issue by BrainBlasted** [k0shk0sh/FastHub#788]
**FastHub Version: 4.0.3**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- MANUFACTURER: ZTE
- BRAND: ZTE  
- MODEL: Z981  
---

 Updated my profile picture earlier today, works across GitHub and on other clients, but the change is not shown in app.

**Comment by k0shk0sh** [comment]
well, that's strange, I can see your new image, could you go to your profile and see if it change? from FastHub

**Comment by BrainBlasted** [comment]
![Here's a screenshot of my profile.](http://i.imgur.com/J2h4aiZ.png)

**Comment by k0shk0sh** [comment]
@BrainBlasted then I start to think that its the same url & therefore you have to wait one day to find out or clear app cache or data. 

P.S: image caches are kept for one day. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BrainBlasted** [comment]
Yup, a cache wipe fixed it. My bad

**Comment by k0shk0sh** [comment]
I found out why its not updated, it has been broken in latest version :'( it will be fixed in next version :)
