### ISSUE TITLE
trending repos list favors early requests

### ISSUE THREAD

**Issue by gruhn** [k0shk0sh/FastHub#789]
**FastHub Version: 4.0.3**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-J510FN  
---

Not a big deal I guess but I just noticed, changing the language filter in the trending repos list, while it's still loading, doesn't seem to effect the outcome. 

For example: I tab on trending repos -> it starts loading -> I change the filter settings to Java -> loading is finished -> displays unfiltered list anyway.

_Sent from my Samsung SM-J510FN using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@gruhn that makes sense since we are scrapping the data and it can't sort it until after it scrapped it.

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
