### ISSUE TITLE
Use rounded corners for profile pictures instead of clipping a circle.

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#79]
GitHub uses rounded corners for avatars everywhere on their page so it would be much more familiar if the app would use that too instead of a circle.
A circle also looks weird for many square shaped profile pictures such as the default GitHub profile image.

**Comment by k0shk0sh** [comment]
That make sense, I'll just then have an option for that in Settings screen, because in my opinion circles look better on small devices & this is a user preference, so I guess a settings for it won't harm. thanks for your feedbacks

**Comment by HeinrichReimer** [comment]
Yeah, a setting for that would be nice! Still open to discuss which one to keep as default.

**Comment by k0shk0sh** [comment]
The current one will remain default tho, it would be up to you guys later to choose either one.

**Comment by HeinrichReimer** [comment]
That's fine!
