### ISSUE TITLE
[FR] Ability to sort repos in search by main language and more

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#793]
**FastHub Version: 4.0.2**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- MANUFACTURER: LGE
- BRAND: lge  
- MODEL: LG-F460L  
---

 I found there is no sort option in repo search mode. Can you add sort option? Such as by main language, last updated, most stars/forks, and so on.

_Sent from my Lge LG-F460L using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
dup with what?

**Comment by k0shk0sh** [comment]
search for filter/sort repos.
