### ISSUE TITLE
Viewing wiki doc of neovim gives error

### ISSUE THREAD

**Issue by LordKrishna91** [k0shk0sh/FastHub#794]
**FastHub Version: 4.0.3** 

 Was just browsing the neovim wiki doc and clicking the section from introduction to users gives server communication error.
 This error does not happen after the users section

**Comment by k0shk0sh** [comment]
Could you please pass me the link to the repo/wiki? That will be really helpful

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Hmmm, well obviously after checking the links are relative & have to be handled but I would suggest that you browse them from the navigation menu (right top icon) until this gets fixed

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LordKrishna91** [comment]
link to repo & wiki + screenshot of the error

https://github.com/neovim/neovim
https://github.com/neovim/neovim/wiki


On 23-Jul-2017 2:19 pm, "Kosh Sergani" <notifications@github.com> wrote:

Could you please pass me the link to the repo/wiki? That will be really
helpful

*Sent from my Samsung SM-G950F using FastHub
<https://play.google.com/store/apps/details?id=com.fastaccess.github>*

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/794#issuecomment-317238565>,
or mute
the thread
