### ISSUE TITLE
Bottom tabs

### ISSUE THREAD

**Issue by kenumir** [k0shk0sh/FastHub#796]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: OnePlus
- BRAND: OnePlus  
- MODEL: ONEPLUS A5000  
---
Bottom tabs margin
 https://photos.app.goo.gl/iwl3Ucd2nYtMX6qH2

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@kenumir did you turn ads on?

**Comment by k0shk0sh** [comment]
Go settings/behavior & disable ads 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
