### ISSUE TITLE
Too many notifications

### ISSUE THREAD

**Issue by nicolimo86** [k0shk0sh/FastHub#797]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: LGE
- BRAND: google  
- MODEL: Nexus 5X  
---

Despite I disabled all the notifications from the Fasthub's configuration menu, I'm receiving notifications on the top bar of my phone. This behaviour has started about 2 weeks ago more or less.

 

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Did you disable the notification from settings screen? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolimo86** [comment]
Yes I did it from there. 

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@nicolimo86 weird tbh, but it might be due to 4.0.2 which introduced a notification check on opening app despite the fact that it was only one time job, it might be a bug in Google play service. Does it happen regularly? Or sometimes? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolimo86** [comment]
It happens randomly but constantly (every day). For example now I'm not receiving any notification about our messages.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@nicolimo86 alright, I'll fix it in next release and make sure it's cancelled. Sorry about that

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
I couldn't really produce it, but I just added the cancellation, I did fix it in a different branch which has WIP jfyi.
