### ISSUE TITLE
HTML Rendering issues inside code box

### ISSUE THREAD

**Issue by LordKrishna91** [k0shk0sh/FastHub#799]
**FastHub Version: 4.0.3**  
**Android Version: 5.1 (SDK: 22)**  
---

 Was reading the ch1 of YDKJS came across this badly or hardly rendered &lt; span &gt; element. I assumed there must be something I'm missing checked the same stuff in save page offline it rendered the code box correctly (this works correctly on the  browser).
![screenshot_2017-07-27-22-50-33](https://user-images.githubusercontent.com/29010161/28684115-dc788e40-7320-11e7-89b0-e89fa779c611.png)
![screenshot_2017-07-27-22-52-43](https://user-images.githubusercontent.com/29010161/28684165-06acd388-7321-11e7-99d0-92d6f73e7537.png)

original repo i came from

https://github.com/P1xt/p1xt-guides/blob/master/wd-cs.md

  Link to ch1 of issue page 

https://github.com/getify/You-Dont-Know-JS/blob/master/up%20%26%20going/ch1.md

**Comment by yakov116** [comment]
@LordKrishna91 please include a link to the repo

**Comment by LordKrishna91** [comment]
@yakov116 
check below the screenshots for links to original refered repo and the ch1 rendering issue repo

**Comment by yakov116** [comment]
@LordKrishna91 Thanks I see it.

@k0shk0sh Github allows HTML formatting inside the .md. This is the issue

**Comment by k0shk0sh** [comment]
the reason for that it was that the html entities are escaped & I don't know why :D a simple replace was enough tho. 
```
.replaceAll("&lt;", "<")
.replaceAll("&gt;", ">")
```
