### ISSUE TITLE
Elevations of toolbar and bottom nav still visible when toolbar/bottom bar is hidden

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#80]
When you scroll down the toolbar and bottom navigation hide as expected but their shadows are still visible at the screen edge.
As this looks unfamiliar (looks like the system status bar and nav bar were elevated) the shadows should be hidden too if the toolbar/bottom nav go off screen.

**Comment by k0shk0sh** [comment]
They definitely do, I'll have a look at what I can do about it. Hopefully it could make it to 1.0.7.

**Comment by HeinrichReimer** [comment]
No hurry at all! Keep up this great project! I just started using your app and as it's open sourced I thought sharing some feedback might be helpful. I would try to fix it in a PR but I'm on vacation currently so I can't really help there.

**Comment by k0shk0sh** [comment]
As long as they are small stuff, They shouldn't bother, I'm trying my best as well to close as much issues as I could so I could focus on my next target. PRs would be awesome tho.
Enjoy your vacation.
