### ISSUE TITLE
Add count numbers of comments in PR

### ISSUE THREAD

**Issue by dikiaap** [k0shk0sh/FastHub#800]
**FastHub Version: 4.0.3**  
**Android Version: 5.1 (SDK: 22)**  
**Device Information:**  
- MANUFACTURER: Evercoss
- BRAND: google  
- MODEL: EVERCOSS A65  
---

Because sometimes PR becomes less interesting since it looks like no one commented.

The comments count is already exists in the issue page and in the PR search feature, but not in PR page yet.

**Comment by yakov116** [comment]
@dikiaap are you talking about in the list of pr's?

If yes that would require an api call for each PR

**Comment by dikiaap** [comment]
@yakov116 Yes, you're right.

**Comment by dikiaap** [comment]
@yakov116 Can you tell me why this closed and what the impact of requesting this feature?

**Comment by yakov116** [comment]
@dikiaap it would require an api call for each and every pr. Just imagine there are 40 Pr's that is 40 calls. It will slow down the app and it will use more internet then need from the users.

**Comment by dikiaap** [comment]
@yakov116 Ah okay. But it's already implemented in issue page, how is it different?

**Comment by yakov116** [comment]
@dikiaap it is due to github api. They give us the amount of comments for the issues, but not for the pull requests.
