### ISSUE TITLE
[Feature request] Github Projects support?

### ISSUE THREAD

**Issue by GitSquared** [k0shk0sh/FastHub#801]
I use Github Projects to keep roadmaps of my repos and I would love to be able to consult & edit them in Fasthub, even if it's a pro feature.

Is the Projects API stable enough for this to be implemented?

_-S_

**Comment by yakov116** [comment]
@GitSquared Good idea and thanks for your feedback.

This has been suggested in issue #384 its on the radar. Hopefully it will come soon.

**Comment by GitSquared** [comment]
@yakov116 Oops, sorry i didn't see the other issue. Thanks for the fast answer.
