### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#802]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F 
- OS: Lineage OS
---

I have FastHub repo issues open in FastHub, then I select Search from the button in the lower right. I enter a search string and press Search on the keyboard. 

Now the focus moves away from the search field, no cursor is shown, the keyboard is still shown, but in normal input mode and not in search mode anymore. But that was it. Nothing else happens, no search is performed.

**Comment by k0shk0sh** [comment]
What keyboard are you using? You might be falling under same issue as someone else which having trouble with the keyboard they are using. I'll workaround this and make an icon to search by. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
I tried with standard AOSP keyboard and with Swype before I reported, both show the same behaviour. I now additionally tried my third one, the "Hacker's Keyboard", with that it works fine.

**Comment by Vampire** [comment]
Is it #635 you mean this duplicates?

**Comment by yakov116** [comment]
@Vampire yes
