### ISSUE TITLE
Markdown editor is not used everywhere

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#803]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

 When adding a code line comment or a review comment or a commit comment, there is only a simple input field. No formatting buttons, and no way to preview the rendered comment. 

I don't know whether this is also like that for other places, but in some places like when reporting an issue or commenting on an issue, there is a proper rich editing dialog with preview function. Would be nice if this is used in all other places where you write Markdown too.

**Comment by yakov116** [comment]
@Vampire thank you for your feedback!

@k0shk0sh maybe add an option for both. In other words add "open in editor"

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
