### ISSUE TITLE
Support all of GFM syntax

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#804]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

In the Markdown editor it would be nice if all GFM syntax is available as buttons, or at least if there would be a help dialog where you can display all available and valid syntax.

**Comment by k0shk0sh** [comment]
Hi, thanks for your feedback, did you scroll the buttons to check for more md syntax? The editor supports everything even image uploading, you need to scroll it left & right

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/xFFRytH.png)

![](http://i.imgur.com/Nxb7hO7.png)


_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
Ah, nice, I didn't observe this list is scrollable. But still there are things not supported / explained. E. g. tables or code blocks.

**Comment by yakov116** [comment]
@Vampire code blocks is there its the `<>`

I don't see how you can support tables? The syntax is not simple and is not really possible to add.

**Comment by Vampire** [comment]
Ah yes, overlooked it.
My request was not solely for rich editing buttons, but also for a help button. 
Maybe the GFM guide can be incorporated, or the points not covered by buttons like tables described in some help pop-up or something like that. Just a help for easing the manual writing.

**Comment by yakov116** [comment]
@Vampire it's an interesting idea, but that would require a bit of work. 

As for the tables me as a regular user of github find myself using HTML for tables since  GitHub's way is 1. Very limited 2. Very complicated. 

Besides tables I don't see any need for an explanation page etc. Your more than welcome to make a pull request. 

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
I agree that it is limited, but for a simple tabular display it is enough. And me personally, I don't think the syntax is complex. You just separate the columns by pipes and the header row from the body rows by dashes. 

The explanation page could describe besides tables e. g. user mentions, auto-linking of issues of same and other repos, syntax highlighting in code blocks, ...

Btw. there is no button for inline code formatting. Especially the backticks are often not too accessible on virtual keyboards. 

It would also be nice if the code button would / could ask for the syntax highlighting language to select from a list. 

And regarding PRs, I often to some, but I never made Android development, so maybe not too likely in this case.

**Comment by k0shk0sh** [comment]
@Vampire I don't see the need of an explanation to be showing here, I also expect who uses GitHub are developers or maintainers who uses GitHub in daily basis, if I find that I need to explain to them how to mention some or paste how to construct a link then imho they shouldn't be using GitHub, as much as I understand your sole purpose behind this but I don't think I'll really put effort on it as I have plenty of things that I need to settle in FastHub. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
@k0shk0sh sure, I just mentioned stuff that could be explained additionally of a help dialogue is added at all. 

But either a button or an explanation for table syntax would still be helpful I think. Tables are not used on a regular basis by many and a reminder or button for the syntax could be helpful. 

As would be a button for inline code highlighting and a selection list for valid code syntax languages when creating a code block as I mentioned in my last comment.

**Comment by k0shk0sh** [comment]
@Vampire can you open a different issue for the language name & also for the table hint? Fyi: I had myself plenty of trouble doing the table showing that showing the images in FastHub readme so I believe this will be good. Or a better option is to implement it :D. It seems challenging, could you make sure its not a hint but rather a FR to add table support?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
