### ISSUE TITLE
Can't change theme of app

### ISSUE THREAD

**Issue by shangshiyjn** [k0shk0sh/FastHub#808]
**FastHub Version: 4.0.3**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- MANUFACTURER: LeMobile
- BRAND: LeEco  
- MODEL: LEX720  
---

 I have install the app from google play, when I try to change the theme of the app, a toast appears, says "%1$s won't run without Google Play services, which are not supported by your device."
Hope to solve the problem~

_Sent from my LeEco LEX720 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Well if you tend to apply premium theme you have to purchase it and without google play service you can't purchase them. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shangshiyjn** [comment]
sorry...I think you mislead what I want to say, I only want to apply the dark theme which need not a premium version but the same toast appears...

_Sent from my LeEco LEX720 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@shangshiyjn that's really weird, could you screenshot which theme you try to apply?

**Comment by k0shk0sh** [comment]
@shangshiyjn I found whats going on, its due to me setting the check for GPS. will be fixed in next release.

**Comment by shangshiyjn** [comment]
OK，thank you very much😄😄

_Sent from my LeEco LEX720 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
