### ISSUE TITLE
Various card margin/padding issues

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#81]
Cards should have 8dp margin and 16dp padding as per the material guidelines.
Places where I spotted wrong margin or padding:
- Profile page (wrong margin, wrong vertical padding)
- issue details/comments (wrong vertical padding)

**Comment by k0shk0sh** [comment]
for Comments, it's due to the markdown parser that somehow adds bottom (empty spaces) for profile page, yup, just noticed them. thanks for the heads up.

**Comment by HeinrichReimer** [comment]
I'm just curious: are you using different markdown parsers for the readme and comments/issues?

**Comment by k0shk0sh** [comment]
Yup, for Readme I'm using WebView to render the readme files as well as in Viewer view, however in Comments I'm using textView to render it, I guess I'll be reverting to what I have done previously which loads them in a webview, but the problem with this approach its going to be view recycling imagine >10 webViews in `RecyclerView`  that will be massive, however I will think about it carefully and either to go for creating my own parser or use WebView, it depends on my availability & time.

**Comment by HeinrichReimer** [comment]
Ah I see the problem...
