### ISSUE TITLE
Always a submit button in Markdown editor

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#810]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

The Markdown editor always has a submit button, even if it does not submit. If you e. g. add a new issue and click into the description field, the Markdown editor opens. If you then press on the submit button, nothing is submitted, it is just inserted into the parent dialogue. This is confusing and semantically not fully correct.

**Comment by k0shk0sh** [comment]
Good catch :D , there are still more stuff to catch tho xD

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
I'm good at catching, I'll create tickets if I find more of those minor issues. :-)

**Comment by k0shk0sh** [comment]
@Vampire please do so, FastHub relies on the community to be better. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
Like any FOSS software. :-)
I'm active in some myself on GitHub and SF.
