### ISSUE TITLE
API answer part in display of rendered files

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#812]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

If you open https://github.com/k0shk0sh/FastHub/blob/master/README.md with FH (in the code tab) it is displayed rendered, but in the beginning and end there is still one wrapping JSON element from the API answer.

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/04mXQM6.png)

![](http://i.imgur.com/MwlNECt.png)

I guess it has been fixed :p 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
Yeah, seems so, great. :-)
