### ISSUE TITLE
Completely blowed up my CM13, only black screen

### ISSUE THREAD

**Issue by szachara** [k0shk0sh/FastHub#815]
I love this app, but I tried it on one of my devices, Nexus 10 with CM13 and it completely blowed up my OS.

After install many apps crashed, trebuchet crashed, so many modals showed up, somehow I managed to switch to play store, I should uninstall, but I clicked open ( I hoped that after first run will be everything ok, may be happen some initializations ), didn't help.

So I restarted and only black screen, so I have to go to adb and manually delete /data/app/com.fasthubXXX and /data/data/com.fasthubXX and CM13 works normally again.

FastHub for GitHub: 4.0.3
Android: CM13 latest build

**Comment by k0shk0sh** [comment]
https://github.com/k0shk0sh/FastHub/issues/744

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
