### ISSUE TITLE
Unread notifications tab does not show all unread notifications, while the bell actually was blue

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#816]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

 If I open FastHub, the notification bell is blue (dark theme), which I interpret means that there are unread notifications. But if I open the notifications, the `Unread` tab shows nothing. When I open the `All` tab it shows unread notifications. Those notifications were there before I installed FastHub. Newly arriving notifications are shown in the `Unread` tab though.

**Comment by k0shk0sh** [comment]
Yep, that would happen, for example, you got a notification however you opened the email for example & the notifications were marked as read but then you opened fasthub which then didn't really yet started its next checking therefore the cached notifications locally has an unread notifications :'(, this has been fixed locally but not according to this issue but with another issue so the next version will has the check on app start as well.

**Comment by Vampire** [comment]
I think you maybe misinterpret the issue. There *are* unread notifications. If I go to the `All` tab, they are listed and shown in unread style, if I go to the `Unread` tab, nothing is shown, even after manual reload. Yet the notification bell is blue. This also was like that, right after installing and logging in, so no cached data available. It seems the app only shows the unread notifications in the `Unread` tab that were created after the app was installed.

**Comment by k0shk0sh** [comment]
Owh, the app will only show last 7 days notifications in unread.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
Yeah, those others are older than 7 days. But it is still confusing that the bell is blue, you tap on it and you get to the Unread tab that is empty. Maybe to make it clearer the bell should only be blue if Unread will show something and the tab renamed to `Unread (last 7 days)` or something like that, to make it clear why there can be a deficiency.

**Comment by k0shk0sh** [comment]
Your issues are pretty much confusing to be honest, how would it show there are unread but there is no unread? As I mentioned in my first reply then, once next version is released please give it another try. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
I'm really sorry, I always try to make my issue reports as clear and detailed as possible, so that they are understandable, especially by developers. If you don't understand something I write, don't hesitate to ask about it. :-)

Yes, the blue bell could actually be the caching issue you mentioned and I'll have an eye on it after the next version is released. Do you have a rough estimate when this could happen? 

But besides the notification icon, I still think that it is pretty confusing that the `All` tab shows unread notifications, that are not shown on the `Unread` tab, which _is_ the case here. That's why I suggested a rename for the `Unread` tab in my last comment, e. g. to `Unread (last 7 days)` or maybe `Recently Unread` or anything else that makes clear that not all unread messages might be shown in that tab.

**Comment by yakov116** [comment]
@Vampire i think it would be very helpful if you would look over the github API doc's.

You would understand much more what we can and can't do.

_Sent from my Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
@yakov116 I know the API docs, I even used the API myself already. But what's your point? 

My point is, that in the `All` tab there are unread notifications shown, that are not shown on the `Unread` tab, which is pretty confusing. I also don't know why you put a 7 days limit on the `Unread` tab. But if you do, you should make clear that the tab is only showing a subset of the unread messages potentially.

**Comment by k0shk0sh** [comment]
@Vampire please search here & play store then you'll know why. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
