### ISSUE TITLE
Markdown editor button for inline code highlighting

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#817]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

 Please add a button for inline code highlighting to the Markdown editor like for bold, italic and strike-through.

**Comment by yakov116** [comment]
@Vampire it's not there?! I have it what exactly are you referring to?

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
-------

Test

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116  he is referring to **``**
