### ISSUE TITLE
Strike-through words are not rendered correctly

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#818]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

 Strike-through formatting is not displayed properly. FastHub shows ~~word~~ as `~~word~~`, instead of a stroke-through word. 

__Update:__ It is rendered correctly when displaying an issue, but not in preview mode or in the create issue screen where you can enter the title and see the rendered body.

**Comment by yakov116** [comment]
@k0shk0sh in the feed and in preview it's not correctly shown

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
In preview itb would but fire feeds or shouldn't as I'm stripping the highlighting

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh what!? 

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Strikethrough isn't displayed.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
