### ISSUE TITLE
Markdown editor syntax highlighting issues

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#82]
In syntax highlighting mode you can still edit the `EditText` but edits won't be saved when you switch back to normal edit mode. One simple solution would be to use 
```java
EditText.setEnabled(false)
```
which basically makes the `EditText` behave like a `TextView`.

The syntax highlighter also doesn't display horizontal lines and it displays ordered lists as unordered lists.

**Comment by k0shk0sh** [comment]
Yup, that will fix it, Thanks again for the heads up, I really appreciate it.

**Comment by HeinrichReimer** [comment]
Just a suggestion but maybe adding a small indicator to the preview toggle could help to identify whether you are in edit mode currently. `AnimatedVectorDrawable` will be useful there.

**Comment by k0shk0sh** [comment]
Yup, I'm looking at implementing that in some places, like right now i'm doing them for star/fork/watch however thanks for pointing out that for the markdown editor.

**Comment by HeinrichReimer** [comment]
It may also be an idea to use the same markdown render as for the readme and then just crossfade the editor `EditText` and the preview `WebView`

**Comment by k0shk0sh** [comment]
Yup, great idea, right now I'm working on changing the comments to WebViews. so for the mean time since sunday almost here, I guess I will go with this approach first then I'll see what I could do about it in term of enhancement as I really don't like the idea of having WebView in RecyclerView.

**Comment by HeinrichReimer** [comment]
That's right.

**Comment by HeinrichReimer** [comment]
You should hide the text controls like bold, italics, ... too when in preview mode

**Comment by k0shk0sh** [comment]
@HeinrichReimer great idea 😄
