### ISSUE TITLE
Improvements for the pre-filled text when reporting a FastHub issue

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#820]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

When reporting an issue for FastHub with FastHub, some pre-filled text is added to the description. I have two improvement suggestions for this:

1. Add the current OS including version, some issues could be specific to the OS. I e. g. run Lineage OS on my Galaxy S7, but the info above does not hint about that
1. The pre-filled text includes a leading space on the line where the caret is; this is superfluous and should be removed

**Comment by yakov116** [comment]
@Vampire the prefilled data has been retweaked and will be updated in the next release. I do not believe there is a way for us to get the OS the user is running. 

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
[Device Information](https://play.google.com/store/apps/details?id=com.happy.deviceinfo) shows `Product: Lineage_herolte`

[CPU X](https://play.google.com/store/apps/details?id=com.abs.cpu_z_advance) shows `ID: lineage_herolte-userdebug 7.1.2 NJH47B 7178885b21`

[Device Information for Android](https://play.google.com/store/apps/details?id=net.kibotu.android.deviceinfo) shows `Display: lineage_herolte-userdebug 7.1.2 NJH47B 7178885b21 ` and `Product: lineage_herolte`

[CPU-Z](https://play.google.com/store/apps/details?id=com.cpuid.cpu_z) shows `Build ID: lineage_herolte-userdebug 7.1.2 NJH47B 7178885b21`

So I'd say one of these two fields that are shown by these apps should do, or maybe even both. If only one I guess the display build ID would be the better one, as it includes more information, like the incremental version (Git hash in this case I think).

**Comment by yakov116** [comment]
@Vampire I just played around with this.

There is no way for us to get a normal response on a Custom Rom so...

**Comment by Vampire** [comment]
@yakov116 I'm sorry, but I don't really understand what you are saying. What do you mean by "normal response"?

What is wrong with `lineage_herolte-userdebug 7.1.2 NJH47B 7178885b21` which is the build ID, that is meant for display to the user?

**Comment by yakov116** [comment]
@Vampire If the user has a custom rom that field is not reliable to give a normal response. On Pure nexus for example I get a random ID.

The only benefit there is in getting the ROM is only if they are on a custom one so....

**Comment by Vampire** [comment]
@yakov116 Are you sure it is a __random__ id? It should be an id that is shown to the user and should identify the build. Maybe our just looks random, but with a quick Google search you could determine what OS is running because it is not random? 

And even if it would really be random for some OS, wouldn't it still be helpful to see which OS the user has if the field has a meaningful content and if not at least to know that it is some custom ROM? 

Don't get me wrong, I don't have too strong feelings about getting this added. I just think it could be helpful information when trying to find a problem that might happen in some ROM but not on others. I'm developer myself (just not Android yet) and I'm always grateful for every tiny piece of environmental information I can get from the user.

**Comment by yakov116** [comment]
@Vampire many roms mess up the build print so yes many times it will not be any help

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
Well, then you still would have the product name if they didn't mess up that one too. And if they did, so what, be happy about the cases where it is _not_ fucked up. Why dismiss the information just because it is sometimes helpful, but not always? ;-)

**Comment by k0shk0sh** [comment]
@Vampire I don't do per-rom custom fixes, that's dangerous, so the less I worry about rom you using the more happy I'll be. 

The SDK for is enough however I wish if there is a way to tell if the user using a custom rom or not, just that label would be helpful enough. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
@k0shk0sh sure, per-rom fixes might be not nice and even not wanted. But it might still be helpful to have the information when interpreting a bug report. e. g. if someone with an S8 reports a problem and you cannot reproduce it no matter what you do while you too are on S8, it might be helpful information that he was on a custom ROM while you are on stock ROM. You surely should - if at all - keep `if rom == "whatever"` as a very last solution, but it might simply be helpful for reproduction and if able to reproduce maybe some generic solution can be found that might work on other roms the same.

I only say from my own experience that the more information you have, the better it is. Whether you need it or use it in the end is a totally different story. :-)

**Comment by k0shk0sh** [comment]
@Vampire yep, it will be really helpful that's why I'll look into a flag that could determine if there rom is custom or stock. Thanks

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@Vampire I do not think there is a way to detect it. If you find a way please post it. I don't think there is any way to tell if the rom is custom and have it correct all the time to make it worth it.

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
I also doubt there is an easy way to determine programmatically whether a rom is stock or custom without checking for specific custom roms. But if you have the information from the device id and / or product string, I think the answer is just a quick Google search away, if not obvious already.

**Comment by yakov116** [comment]
@Vampire I did that quick Google search and tried for about a half hour and it's a nogo

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
@yakov116 you googled for what? *confused*

**Comment by yakov116** [comment]
@Vampire a way to determining what rom the user is on. 

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Couldn't find away myself. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
@yakov116 then no, you didn't do "that quick Google search". I said add the product name and display build id as demonstrated in my comment above to the pre-filled issue text. **Then**  a quick google search can tell you what OS the user is running in most cases and whether it is a custom rom or a stock rom.

**Comment by k0shk0sh** [comment]
So we go fully manual? Why not just ask user? Wouldn't that save us time by Googling? While user can tell us? Hmmm that's tedious to do. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@Vampire please try it your self and you will see I am correct. I actually compiles the app 6 times trying all different options and it did not work..... Please if you have a way please try it yourself? 

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
@k0shk0sh if you have `MODEL: SM-G930F` in the issue, how do you know this is an S7? Exactly, either you just know it because you remember it, or you manually Google it. It's the same for the OS. If you see `Build ID: lineage_herolte-userdebug 7.1.2 NJH47B 7178885b21` and `Product: lineage_herolte`, then you can either know that this is Lineage OS 14.1, or you can Google for it and find out, **if** you need the information in that detail.

@yakov116 I should try what? I tried to google those values and found instantly that this is Lineage OS 14.1. What options do you mean? Do you mean how to get those strings? As I said, I'm not an android developer, thus I told you several apps that show the information and partly also are open source. Device Information for Android e. g. can be found at https://github.com/kibotu/net.kibotu.android.deviceinfo and I'd say that `android.os.Build.DISPLAY` gives the diplay build id string and `android.os.Build.PRODUCT` gives the product name like used here: https://github.com/kibotu/net.kibotu.android.deviceinfo/blob/e1e5629e74a7abe009aeb839dacb0ce49783f002/app/src/main/java/net/kibotu/android/deviceinfo/ui/buildinfo/BuildFragment.java

**Comment by yakov116** [comment]
@Vampire this will only work on some roms NOT all it depend do on the DEV of the rom.

Like I said Pure nexus will not work, so I am assuming that others will not either.

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
@yakov116 I understood this. It's just that I think that it is better to have the information that will be helpful for some roms, even if it is not helpful for all roms, because the cases where it is helpful are not influenced by the cases where it is not, are they?
