### ISSUE TITLE
Bug with emoji

### ISSUE THREAD

**Issue by Adizbek** [k0shk0sh/FastHub#821]
**FastHub Version: 4.0.3**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- MANUFACTURER: LGE
- BRAND: lge  
- MODEL: LG-H502  
---

 
![](http://i.imgur.com/YwQduIq.png)

![](http://i.imgur.com/lA5nT82.png)

![](http://i.imgur.com/uapeQZX.png)

I think You have noticed the bug in these pictures...

_Sent from my Lge LG-H502 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Please search for issue before submitting new one, thanks for your feedback.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
