### ISSUE TITLE
Confirm mark all notifications as read

### ISSUE THREAD

**Issue by wopian** [k0shk0sh/FastHub#822]
Currently the `mark all as read` button just does what it says. 

So if you accidentally double tab to access the notifications view, you've just cleared your unread notifications.

A confirmation popup _or_ an undo snackbar would be 👌 

**FastHub Version:**  4.0.3
**Android Version:**  6.0.1

**Comment by yakov116** [comment]
@wopian  Great Idea! 
Thanks for your feedback.
