### ISSUE TITLE
Crashes while in Background

### ISSUE THREAD

**Issue by SISheogorath** [k0shk0sh/FastHub#824]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: motorola
- BRAND: motorola  
- MODEL: Moto G (4)  
---

 It's a bit annoying, the app often crashes while it's in background. It doesn't really affect the working with the app or notifications, but it's super annoying to have android's pop-up every time it happens. "FastHub has stopped". The Android hint isn't really useful, but if you provide instructions I can maybe provide better debug output.

**Comment by yakov116** [comment]
@SISheogorath do you have a custom ROM?

**Comment by SISheogorath** [comment]
Nope. Stock-ROM, latest version installed.

**Comment by yakov116** [comment]
@SISheogorath ok I will wait for @k0shk0sh to look at the firebase logs.

Thanks for reporting.

**Comment by k0shk0sh** [comment]
Its firebase that crashing which I have no idea how to fix that, could you please in the meantime disable notifications at all from FastHub/settings/notifications . @SISheogorath 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mati865** [comment]
On Xperia Z1 stock 5.1.1 there are at least 2 kinds of errors:
```
08-18 02:15:31.762 E/AndroidRuntime(31166): java.lang.RuntimeException: Unable to unbind to service com.fastaccess.provider.tasks.notification.NotificationSchedulerJobTask@2d5dc001 with Intent { act=com.firebase.jobdispatcher.ACTION_EXECUTE cmp=com.fastaccess.github/com.fastaccess.provider.tasks.notification.NotificationSchedulerJobTask }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
```
And
```
08-16 21:46:55.423 E/AndroidRuntime(30499): java.lang.RuntimeException: Unable to unbind to service com.fastaccess.provider.tasks.notification.NotificationSchedulerJobTask@11770286 with Intent { act=com.firebase.jobdispatcher.ACTION_EXECUTE cmp=com.fastaccess.github/com.fastaccess.provider.tasks.notification.NotificationSchedulerJobTask }: java.lang.ClassCastException: android.app.ActivityThread$BindServiceData cannot be cast to com.firebase.jobdispatcher.JobParameters
```

**Comment by k0shk0sh** [comment]
@mati865 what version are you using? 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mati865** [comment]
@k0shk0sh the same as OP latest 4.0.3 from Google Play.

**Comment by k0shk0sh** [comment]
@mati865 any custom rom? Or stock? I might just remove firebase integration at all and rely on official jobScheduler since this cause plenty of drama, could you disable notifications at all from settings 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mati865** [comment]
@k0shk0sh customized stock 5.1.1 but I'm planning to migrate to custom 7.1 in following days since touch driver got fixed.

**Comment by k0shk0sh** [comment]
FastHub now ships its own fork of Firebase to avoid the crash!!
