### ISSUE TITLE
only public entries on an organisations feed

### ISSUE THREAD

**Issue by heikomat** [k0shk0sh/FastHub#825]
**FastHub Version:**  4.0.3
**Android Version:**  7.1.2
**Device Information:**  
- MANUFACTURER: OnePlus  
- BRAND: OnePlus  
- MODEL: One  

When i open the feed of an organisation, only entries that belong to public repositories of that organisation show up. Entries belonging to private repositories of that organisation are not visible.

Is that intended behaviour, or a bug?

**Comment by k0shk0sh** [comment]
@heikomat it should be showing the org feeds according to what GitHub has returned me, if you could see the feeds of an organization that means you are a member of it & should display it's feed correctly unless GitHub returned me something I can't know, could you screenshot the top tabs, content aren't needed.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Like for example going into your org, I only can see these tabs but not feeds

![](http://i.imgur.com/wQJ22s2.png)


Do you have the same exact tabs with only feeds added? Or there are more like in normal user profile?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by heikomat** [comment]
This is what i see for the organisations feed:
![screenshot_20170731-030112](https://user-images.githubusercontent.com/20770029/28759382-d19ac01e-759c-11e7-8f57-1851052ed0fd.png)

as described, only events that happen in public repositories show up. There have been dozens of events in that organisation that show up when i visit github with the browser, but in the app, the events that belong to private repositories of that organisation don't show up

**Comment by k0shk0sh** [comment]
Let me find out what I'm doing wrong and get back to u on this

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by heikomat** [comment]
ok. Let me know if i can help with that. btw: the blue theme is nice!

**Comment by k0shk0sh** [comment]
I looked over my code & everything seems to be fine 

according to [GitHub API](https://developer.github.com/v3/activity/events/#list-events-for-an-organization) & [FastHub called API](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/java/com/fastaccess/data/service/OrganizationService.java#L43-L43) i'm calling the right path so now i'm a bit confused tbh with you.

**Comment by heikomat** [comment]
@k0shk0sh according to the code, you are calling `orgs/{username}/events`, which according to the GitHub-API:
> List public events for an organization

If you look at the very end of the GitHub-AOI-Page you linked, you'll find
> List events for an organization

and the path for that is `/users/:username/events/orgs/:org`

**Comment by k0shk0sh** [comment]
isn't this event for the specific user in an org and not the whole? org

**Comment by k0shk0sh** [comment]
well, I hope not because I just updated it to that :D

**Comment by heikomat** [comment]
@k0shk0sh correct, it is

> This is the user's organization dashboard.

I'd guess, that if you use the username of the logged-in user there, you should get all the organisation-events the user can see, which is exactly what you'd expect, isn't it?

**Comment by k0shk0sh** [comment]
@heikomat I guess so, thanks for catching that up :) , really appreciate your help :)
