### ISSUE TITLE
Syntax highlighting in issues not working

### ISSUE THREAD

**Issue by heikomat** [k0shk0sh/FastHub#826]
**FastHub Version:**  4.0.3
**Android Version:**  7.1.2
**Device Information:**  
- MANUFACTURER: OnePLus  
- BRAND: OnePlus
- MODEL: One 

The syntax-highlighting in issues seems to not be working correctly. All these code-blocks are set to
```
   ```TypeScript
```
![screenshot_20170731-032016](https://user-images.githubusercontent.com/20770029/28759679-60d9477a-75a0-11e7-83fd-c7c85a286520.png)

However the highlighting looks fine in markdown files (for example the `README.md` is ok)

**Comment by yakov116** [comment]
@heikomat link to repo please

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by heikomat** [comment]
@yakov116 the repo from the screenshot is not public. But here is an issue that has the exact same problem, from a repo that is public: https://github.com/5minds/typescript-guidelines/issues/5

**Comment by k0shk0sh** [comment]
This is a textView and therefore we can't have it behave like in html nor have a proper syntax highligting. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by heikomat** [comment]
ok, thanks for the info :)

**Comment by k0shk0sh** [comment]
@heikomat thanks for understanding :) 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
