### ISSUE TITLE
Dead Slack link

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#827]
In `ISSUE_TEMPLATE.md`, `CONTRIBUTING.md`, `README.md` and two places in the actual app there is a link to the public Slack channel https://rebrand.ly/fasthub, but this link is dead. If you follow it, you are told:

> This invite link is no longer active.
> Please check with the person who shared it with you to see if there's a new link available.

**Comment by yakov116** [comment]
@kutsan up we need an updated link..

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 I'll do it & maintain the link myself don't want to bother Kutsan about it everytime 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh also I don't think it can be updated using the GraphQl

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@Vampire please check the slack link again.

**Comment by Vampire** [comment]
@k0shk0sh yep, worked now. You are aware that you didn't fix the code occurences? just want to make sure. :-)

**Comment by k0shk0sh** [comment]
@Vampire code occurences? Didn't get that, could you tell me what are you referring to?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh in the app...

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
@k0shk0sh app/src/main/java/com/fastaccess/ui/modules/settings/SlackBottomSheetDialog.java and app/src/main/java/com/fastaccess/ui/modules/about/FastHubAboutActivity.java also contain that link

**Comment by k0shk0sh** [comment]
@Vampire owh dang. thanks :)

**Comment by k0shk0sh** [comment]
-------
Hello

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
Hey, i thought you said you will shut down slack... Change to discord

**Comment by cozyplanes** [comment]
@k0shk0sh

**Comment by k0shk0sh** [comment]
@cozyplanes slack wont be shutdown however all links should be changed to discord. You gotta wait until next release in order for it to reflect in app

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
