### ISSUE TITLE
Use medium font weight for repo titles

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#83]
If you open a repo the toolbar title appears to be very small.
It would help to emphasize the title by using the `sans-serif-medium` typeface.

**Comment by HeinrichReimer** [comment]
I don't see how the commit fixed this :(

**Comment by k0shk0sh** [comment]
damn, I should have closed the syntax highlighting problem and not this one. #fail

**Comment by HeinrichReimer** [comment]
No problem :)
