### ISSUE TITLE
Input help for Emojis

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#830]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

It is hard to remember the dozens of emojis that are possible. It would be cool if there would be a button like the link, image, ... buttons for inserting Emojis where all Emojis from http://www.emoji-cheat-sheet.com/ are listed and can be filtered. Actually the API also provides a dynamic list with all valid Emojis on GitHub.

Maybe it would even be possible to have some auto-completion popup, so if you start to type an Emoji manually in the text field, it will show all Emojis that start with what you have entered so far.

**Comment by k0shk0sh** [comment]
Why don't you use your keyboard to insert emojie? Aren't they the same after all? 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
No, not really. If I use the keyboard, then the Unicode character is inserted that represents that Emoji. It then depends on the displaying client to have a glyph for that Emoji and it also can look differently on each client.

If you insert a Markdown Emoji like `:this:`, the Markdown renderer translates the Emoji sequence to an image that is the same for everyone. And also the set of valid Emojis is different of course. 

So it would be helpful to have a list with all valid Emojis and to be able to filter them, as an auto-completion popup filtered with what was entered so far would be helpful additionally.

**Comment by k0shk0sh** [comment]
Hmmm, as much as it sound valid FR, but honestly currently I have no interest on implementing it so I'll keep this open until I'm done with everything else. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vampire** [comment]
Sure, no problem. I don't expect FRs to be done immediately. But if it is reported, it is documented at least and if someone searches something to contribute, she can also find it. :-)
