### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by ShineYang** [k0shk0sh/FastHub#831]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G9500  
---

 Chinese support ?

_Sent from my Samsung SM-G9500 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Settings / App language & choose either traditional or semplified 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ShineYang** [comment]
@k0shk0sh Thx ,I didn't see that just now.

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Samsung SM-G9500 发送_
