### ISSUE TITLE
Jerky scrolling through README

### ISSUE THREAD

**Issue by Busimus** [k0shk0sh/FastHub#833]
**FastHub Version:**  4.0.3
**Android Version:**  7.1.2 (official LineageOS 14.1)
**Device Information:**  
- MANUFACTURER: Xiaomi
- BRAND: Xiaomi
- MODEL: Mi5
---

I'm having issues with scrolling while reading the README. The menus on the top and bottom keep popping up and down erratically, creating a very unpleasant scrolling experience, even though I'm making very smooth scrolling motions. It happens on any README that I could find.

Here are 2 videos of it happening [with AOSP WebView that comes with LineageOS](https://streamable.com/80wij) and [with Google WebView from the Play Store.](https://streamable.com/ilvpd)
As you can see, the results are identical. 

Starting with a completely fresh install didn't help. Changing the display and font size in system settings to default didn't help.

**Comment by yakov116** [comment]
@Busimus I think this was fixed already it was a fast scroller issue

**Comment by k0shk0sh** [comment]
@yakov116 not related.

@Busimus I'm aware of that,  imo you are fighting the nestedScroll by doing that and not really smooth scrolling you are intentionally holding your finger and scrolling up & down which trigers that, if you for example scrolled properly this wont happen. 

I'll try and fix that.
Thank

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Busimus** [comment]
@k0shk0sh I'm scrolling up and down to showcase it. I initially noticed it while "scrolling properly". 
[Here's a great example](https://streamable.com/4q8ud) you can examine frame-by-frame if you wish -- my finger never stops moving up, yet the page does the opposite of what that motion means.

**Comment by Rukenshia** [comment]
I also just experienced this and it's very annoying (and maybe can be considered higher than a Low priority?). When I scroll, I always keep my finger on the screen and scroll slowly while I read. This makes it jerk even more which is somewhat annoying.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@Rukenshia its not something that really requires higher priority, you could ignore it at least for a second and then you'll be fine, there are more things that are higher than this.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
