### ISSUE TITLE
Support stargazers links

### ISSUE THREAD

**Issue by nyuszika7h** [k0shk0sh/FastHub#834]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: LGE
- BRAND: google  
- MODEL: Nexus 5X  
---

 
Currently, when you click a link like [this](https://github.com/pakastin/open-source-flash/stargazers), the app simply takes you to the repository instead of showing who starred the repo.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@nyuszika7h Please wait on all Feature request's for another 2 weeks

Thanks for your feedback

**Comment by k0shk0sh** [comment]
forks, watchers & stargazers are now handled properly.
