### ISSUE TITLE
Change invitation link

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#835]
**FastHub Version: 4.0.3**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- MANUFACTURER: LGE
- BRAND: lge  
- MODEL: LG-F460L  
---

 Change Join Slack to Join Discord

It is a quick fix, right?

**Comment by k0shk0sh** [comment]
Yep, in different branch I guess I have changed these, in master I guess readme only has been changed, could you point me to where you find join slack?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
#827

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
In about screen

**Comment by k0shk0sh** [comment]
Owh, I'll have to make a release first :p

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
doesnt seems that it has been fixed @k0shk0sh

**Comment by k0shk0sh** [comment]
obviously you didn't read my msg in discord

**Comment by k0shk0sh** [comment]
Owh you did, then why the comment? 😕  as per my comment, i'll be maintaining slack link

**Comment by cozyplanes** [comment]
Oh. I was expecting to have 2 buttons, one for slack, the other for discord and mentioning the difference above

**Comment by k0shk0sh** [comment]
@cozyplanes no not really, I can't keep up with all later I had to choose one & after trying discord & seeing its limitation I have decided to revert back to slack and maintain the link myself.

**Comment by cozyplanes** [comment]
ok then
