### ISSUE TITLE
Linebreaks go lost in Markdown preview

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#838]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

If you are in Markdown editor preview, linebreakes go lost. If you e. g. create a new comment and enter

```
Test
This
```

then the preview displays

```
Test This
```

instead. Normal view rendering works fine.

**Comment by k0shk0sh** [comment]
Please use two new lines instead.
