### ISSUE TITLE
Code Language Selector

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#839]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

When pressing the code block button, it would be nice to get a filterable list of valid language names to select from (including the option to select none).

Also when positioning the caret after the opening three backticks or within a language string that is already present, it would be nice if you can open this list of languages to select from, or maybe even some completion popup, that shows the valid options and narrows according to what is left of the current caret position.

**Comment by yakov116** [comment]
@Vampire please wait on all feature requests for another 2 weeks

**Comment by Vampire** [comment]
@yakov116 I don't expect it to be implemented right away, but this way it is documented. And actually kosh told me to create issues for the points I have in mind.

**Comment by yakov116** [comment]
@Vampire Thank you fr all the issues you have brought up! its really good to ave you around just this it will be easier if you would list you FR's in one place so we can squash all the bugs first

**Comment by Vampire** [comment]
@ya do I get you right, that you want me to list all FRs in one issue? Especially after kosh told me to create individual issues? I'm slightly confused to be honest.

**Comment by yakov116** [comment]
@Vampire Yes please do make it all one issue. I will make sure they are looked at.

The best is list format with check boxes.

If you dont to merge all the tickets that would be the best

**Comment by k0shk0sh** [comment]
@Vampire & @yakov116  please keep things simple, 

@Vampire  logically, if (many FRs/Issues) related to the same feature please put them in one place, but don't mix with FRs & issues.  I'd go with what @yakov116 suggested, since most of your issues/frs are related to one place & they just takes away visibility from what I should be seeing when I go to Issues. 

Now what happened has happened, so keep this in mind for future!.

**Comment by k0shk0sh** [comment]
Sorry, but i have no interest to implement this.  as I couldn't see what would it bring from a feature perspective.
