### ISSUE TITLE
Links and Images are inserted at end instead of at the caret

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#842]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

When entering links or images with the respective button in the Markdown editor, the produced Markdown is inserted at the end of the existing text instead of where the caret was at the time the button was pressed.

**Comment by yakov116** [comment]
@Vampire please make an issue will all the markdown issues a one

**Comment by Vampire** [comment]
@ya which issues exactly do you want me to merge? I'm used to separate issues that are individual, so that you can fix and close the issues individually. If you practice this differently in FastHub, I fear I need some guidance on how you prefer your issues.

**Comment by yakov116** [comment]
@Vampire Sure.

All issues that have to do with the markdown and editor should go in one issue.

Take a look at the Pull request that is open to see how I made my list

**Comment by Vampire** [comment]
But then why did kosh tell me to create separate issues? *confused*

**Comment by k0shk0sh** [comment]
@Vampire FR & issues are separate thing and will definitely be treated differently, 
FR = issue on its own.
Issue (related ones) = combined. 




_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
