### ISSUE TITLE
Cannot login to Enterprise

### ISSUE THREAD

**Issue by Rukenshia** [k0shk0sh/FastHub#843]
**FastHub Version: 4.0.3**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- MANUFACTURER: Google
- BRAND: google  
- MODEL: Pixel  
---

 Whenever I click on the Enterprise button on login, I see a message telling me some kind of Warning regarding the GitHub API. The warning keeps appearing and I have no way to log in to my Enterprise instance. I also had to login with GitHub.com to report this bug.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Yes, first thing you need to do is logging in with your GitHub account then only you'll be able to login with Enterprise.

P.S: Enterprise is a premium feature, so once you login and click on add account you'll be promoted to purchase it to be able to login. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@Rukenshia was I right about my assumption?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Rukenshia** [comment]
@k0shk0sh yes, it just didn't really understand the message at first (what it said there didn't make any sense in a context of just wanting to use an Enterprise account). I'm otherwise quite happy with the app so far, good work :)

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@Rukenshia sorry about that, I'll look into rephrasing the warning. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
