### ISSUE TITLE
when editing labels on an issue/PR, only labels I'd added myself show up as selected

### ISSUE THREAD

**Issue by ixdy** [k0shk0sh/FastHub#844]
**FastHub Version:** 4.0.3

I opened up https://github.com/kubernetes/kubernetes/pull/50052 with the intend to remove the `do-not-merge` label, but when I attempted to edit labels, I was confused, since no labels were selected in the menu. I selected `do-not-merge` from the list and saved, which ended up removing all other labels from the issue (not my intent). When I opened the list of labels again, I saw that `do-not-merge` was now selected, but nothing else was.

I looked at a few other issues/PRs I've opened, and realized that only the labels I'd previously added myself (not in FastHub, but through using the GitHub web UI) were showing up as selected in FastHub.

**Comment by k0shk0sh** [comment]
@ixdy thanks for your descriptive ticket. 

I don't that this is the case, for FastHub it doesn't matter where the labels were labeled. 


Is the do not merge label is in second pagination? If so maybe it could be then problem, I'm in a vacation right now and going to be back later today, as soon as I as arrive I'll dig in into this. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ixdy** [comment]
We do have a lot of labels in our repository, and many are missing from even just the menu, so pagination is likely at play here.

**Comment by ixdy** [comment]
in particular, kubernetes/kubernetes has [176 labels](https://github.com/kubernetes/kubernetes/labels).

**Comment by k0shk0sh** [comment]
@ixdy it's definitely the cause then, please bare with me until this weekend and it should be in that release. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ixdy** [comment]
great, thanks! I'll wait for the next release and will update here when it arrives.
