### ISSUE TITLE
PR commit status display is missing contexts

### ISSUE THREAD

**Issue by ixdy** [k0shk0sh/FastHub#845]
**FastHub Version:** 4.0.3

We have quite a few tests which run on every PR, with test results added to the commit status on GitHub.
Many of these statuses are produced by the same tool, and so we use the status context to differentiate.

On GitHub's web UI, this looks something like
![screen shot 2017-08-05 at 12 45 13 pm](https://user-images.githubusercontent.com/8061296/28998290-10586444-79dc-11e7-8007-b443eb8fa478.png)

But on FastHub, the context is missing, so it's hard to tell what jobs may have failed:
![screenshot_20170805-115525](https://user-images.githubusercontent.com/8061296/28998297-3492c2be-79dc-11e7-9f5c-173f9ad39098.png)

**Comment by yakov116** [comment]
@ixdy this is in middle of being fixed int he revamping_timline branch. We are switching to the new github api and it may take another week until it's implemented 

_Sent from my Google Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Dup of #814

 however as @yakov116 mentioned, now we are switching for Graphql for the PR timeline and that will be out within coming weekend hopefully. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
