### ISSUE TITLE
The markdown view is mixed with HTML

### ISSUE THREAD

**Issue by zt515** [k0shk0sh/FastHub#846]
**FastHub Version: 4.0.3**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- MANUFACTURER: Meizu
- BRAND: Meizu  
- MODEL: M5 Note  
---
Here is the [Markdown File](https://github.com/NeoTerm/NeoTerm-wiki/blob/master/NeoLang-Introduction-zh.md) in the screenshot.
Screenshot:
![s70806-134031](https://user-images.githubusercontent.com/9902643/29000916-88052b9e-7a40-11e7-8f82-ff7743ab7d73.jpg)

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/WaJgqsO.png)
