### ISSUE TITLE
Update branch

### ISSUE THREAD

**Issue by fxedel** [k0shk0sh/FastHub#847]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: bq
- BRAND: bq  
- MODEL: Aquaris X5 Plus  
---

Reproduce:
1. Create a feature branch with a single commit and open a PR.
2. Push another commit to the master branch.
3. On desktop, I can click "Update branch" in order to merge the newest commit from my master branch into my feature branch. I'd like that functionality on FastHub, too.

**Comment by k0shk0sh** [comment]
@fxedel thanks for opening the FR, however this isn't possible in GitHub API. 

Maybe my search skills aren't good enough, but if you find a way in github API, feel free to reopen this issue.
