### ISSUE TITLE
Show phone name rather than model number in signature?

### ISSUE THREAD

**Issue by Daniel15** [k0shk0sh/FastHub#848]
When I leave a comment using FastHub, it adds a signature like this:

> Sent from my Samsung SM-G950U using FastHub

I think it would be nicer if it mentioned the model name ("Galaxy S8") rather than model number ("SM-950U"). There's a Java library to do this: https://github.com/jaredrummler/AndroidDeviceNames

**Comment by yakov116** [comment]
@Daniel15 Bingo! it's in the process of being done. I did it just never committed yet....

Thanks for your feedback

**Comment by Daniel15** [comment]
Nice, glad to hear! Thanks for the great app. 😃

**Comment by k0shk0sh** [comment]
@yakov116 have you managed to make it work? Or should I go ahead for it?

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh I got it to work just need help on one small thing

**Comment by k0shk0sh** [comment]
@yakov116 alright, give me an hour and I can join you via TeamViewer

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
Yup it's working

_Sent from my Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
