### ISSUE TITLE
Feature: Show recently viewed repos

### ISSUE THREAD

**Issue by LeapingDragon** [k0shk0sh/FastHub#856]
**App Version: 2.1.0**

**OS Version: 23**

**Model: LGE-LG-H850**

From the hamburger menu there should be a section to show a list of recently viewed repos for easy navigation. Often times I may accidentally click back too many times and leave a repo, or just want to refer to something I recently viewed.

**Comment by k0shk0sh** [comment]
There is a pin functionality that you could use. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@LeapingDragon please update to the latest version. You are 2 master versions behind.

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 didn't realize that, dang!. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LeapingDragon** [comment]
I'm on the latest F-Droid version, I don't see any updates

**Comment by k0shk0sh** [comment]
@LeapingDragon well then its bad news, as FastHub dropped support to foss, you can download latest from the release page or tab in FastHub. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
