### ISSUE TITLE
Make issue events into links

### ISSUE THREAD

**Issue by LeapingDragon** [k0shk0sh/FastHub#857]
**App Version: 2.1.0**

**OS Version: 23**

**Model: LGE-LG-H850**

I was surprised to find that when an issue event happens eg given a label, given a milestone etc this event is not a clickable link. It would very helpful for usability to be able to use these to redirect to the filtered issue view.

**Comment by k0shk0sh** [comment]
That's good point, I'm not really sure where it has been mentioned before but please look it up if there is an issue open close this.

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Labels, Milestones, Assignees would open the filter activity with whatever you clicked on.
