### ISSUE TITLE
JavaScript repo type label hard to see

### ISSUE THREAD

**Issue by compumike08** [k0shk0sh/FastHub#859]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-T713  
---

 For repositories which are predominantly JavaScript, the yellow text of the JavaScript label is very hard to see against the white background of the app.

![](http://i.imgur.com/9vpaHKA.png)

_Sent from my Samsung SM-T713 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
As far as you are literally right about that however people wanted GitHub's language color and that's what you get out of it. So I can't change it either. :'(

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
