### ISSUE TITLE
Commits Inside of FastHub

### ISSUE THREAD

**Issue by DavidAylaian** [k0shk0sh/FastHub#860]
**FastHub Version: 4.0.3** 
**Android Version: 7.1.2**
**Device Information:**  
- MANUFACTURER: LGE
- BRAND: google
- MODEL: Nexus 5X
---
FastHub would be the perfect GitHub client for me if I was able to make commits inside of the app. It would either work similar to how GitHub's online commits do or, even better, you're able to edit multiple files and then make one commit for all of the edits. The text editor doesn't need to have lots of fancy features, it just has to work.

**Comment by k0shk0sh** [comment]
This will be in next version :)
