### ISSUE TITLE
Default to Signature On

### ISSUE THREAD

**Issue by chainsol** [k0shk0sh/FastHub#861]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: motorola
- BRAND: motorola  
- MODEL: Moto G (5) Plus  
---

 Quite an annoying behavior of this app is the default to adding a signature to all comments.

This should be an opt-in feature, or at the very least, shouldn't hide itself by not appearing while I'm editing a comment.

**Comment by k0shk0sh** [comment]
Hi @chainsol thanks for coming here, if the (`Checkbox`) above the keyboard that shows `sent from my device using FastHub` isn't appearing then you are literally right, its annoying & its something that can be disabled forever or on every comment depending on your settings, could you confirm that it isn't appearing when adding/editing a comment?

**Comment by chainsol** [comment]
I've reenabled the feature but have the checkbox currently unchecked - let's see if I get a signature. :)

**Comment by k0shk0sh** [comment]
If you are wondering here is what I'm referring to: 

![](http://i.imgur.com/PJou0xl.png)


_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@chainsol apparently you didn't have signature in your comment 😋

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@chainsol you won't see it because it isn't added until the end to not distract you from what you typing, it depends on the  - [x]  if it was enabled or not. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chainsol** [comment]
@k0shk0sh oh, I did! I used the checkbox to turn it back off, haha! Here's a handy-dandy signature enabled post.

_Sent from my Motorola Moto G (5) Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chainsol** [comment]
@k0shk0sh there is an actual bug regarding this feature - when editing a comment the app has previously added a signature to, but with the signature feature turned off, I can't remove the signature.

_Sent from my Motorola Moto G (5) Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@chainsol was the comment body empty? if it was then it definitely won't be deleted 😕 

@yakov116 can you debug on this?

**Comment by chainsol** [comment]
@k0shk0sh I currently have the feature disabled, but it keeps defaulting the signature back on, and when editing the previous post, I can't remove the signature. Heh, this is actually why I posted that review! The behavior is buggy.

**Comment by k0shk0sh** [comment]
@chainsol i'm abit lost, let me try and produce it and once I did, i'll fix it and will be in next release, could you in the meantime disable it at all?

**Comment by chainsol** [comment]
@k0shk0sh
To reproduce:
- post a comment with the signature feature enabled
- disable both the signature checkbox and auto-signature
- edit the original comment

The app won't show you that the comment has a signature, and won't allow you to remove it. Saving the edited comment also turns back on the auto-signature.

**Comment by k0shk0sh** [comment]
Owh, that make sense then, because the signature will be removed from the text lol. 

Thanks, you saved me plenty of time trying to produce it.

**Comment by chainsol** [comment]
@k0shk0sh 
Haha, no worries. The app works so well for everything else, I'll be happy to see this bug fixed!

**Comment by k0shk0sh** [comment]
it'll :), i'll close it with a commit so you can be notified, thanks for your help.

**Comment by yakov116** [comment]
@k0shk0sh actually this was reported already in #620

**Comment by k0shk0sh** [comment]
starting next release, the checkbox will be no longer there & the signature could only be enabled from settings or via a `FastHub` markdown icon which is located at the icon of the markdown icons.
