### ISSUE TITLE
Actionbar auto hide feature could be implemented better

### ISSUE THREAD

**Issue by sevenupcan** [k0shk0sh/FastHub#863]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Google
- BRAND: google  
- MODEL: Pixel  
---

Hello. Thanks for listening to my feedback. I wanted to raise a point about the auto hiding feature of the action bar as I find it really frustrating to use.

I find it frustrating because the screen jumps around when you slowing scroll the page down/up. I wonder if you might be able to mimick the way Twitter app handles the hiding of its actionbar as it feels much less jarring.

Many thanks for a great app!

**Comment by sevenupcan** [comment]
Having looked at this a bit more closing I believe it may be a bug rather than implementation.

When I navigation to a repository and scroll gradually down the page the actionbar appears and dissapears repeatedly.

This issue doesn't seem to happen on other screens.

**Comment by k0shk0sh** [comment]
@sevenupcan thanks for opening the ticket, i'm aware of that & it will be fixed very in next release.

**Comment by k0shk0sh** [comment]
the quirking only happen in Readme.

**Comment by sevenupcan** [comment]
👍
