### ISSUE TITLE
'You reached the impossible' on some Settings screens

### ISSUE THREAD

**Issue by tom-ando** [k0shk0sh/FastHub#866]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: OnePlus
- BRAND: OnePlus  
- MODEL: ONEPLUS A3003  
---

 On some Setting screens, such as customization, backup, notification or anything else apart from the top two options, when the screen is rotated everything disappears and a little notification comes up saying 'You reached the impossible :'('

![](http://i.imgur.com/zANdZe9.png)

Great app though
- tom-ando

**Comment by k0shk0sh** [comment]
😂😂😂 does it happen occasionally or sometimes? Its due to the app is being killed and couldn't restore from process death. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tom-ando** [comment]
Well I just opened it then (wasn't open at all, but I no process ect), went
straight to settings and pressed notification and rotated the screen. No
big deal, I just saw that little comment and thought I'd bug you with it :)

**Comment by k0shk0sh** [comment]
@tom-ando at first I was crashing the app but then found out that there are some devices that had this help  happened to them so I show the massage only 😁

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
