### ISSUE TITLE
Indicate if a pull request is open/closed/merged on the pull request's screen

### ISSUE THREAD

**Issue by whisperity** [k0shk0sh/FastHub#868]
**App Version: 3.2.0**

**OS Version: 23**

**Model: Xiaomi-Redmi 4X**

Currently there is no way to easily see if a PR is merged or closed or still open other than scrolling all the way down and seeing the last comments which would indicate a "close" or "merge" in the issue's history. Some texts exist in the title bar but it's not graphically apparent.

**Comment by k0shk0sh** [comment]
Isn't the top text under the PR name is enough to indicates that?

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
![](http://i.imgur.com/0iQAgfZ.png)

![](http://i.imgur.com/dheUvQ8.png)


_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
