### ISSUE TITLE
Toolbar shadow clipping issue

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#87]
The toolbar shadow clips content below itself.
You can see this effect in the repo list by scrolling down some distance.
![screenshot_20170308-123055](https://cloud.githubusercontent.com/assets/5065698/23702389/4ce6af8a-03fb-11e7-9789-5f44051bbc74.png)
Are you using a drawable to implement the shadows? As your app is SDK 21+ you should use the elevation property.

**Comment by HeinrichReimer** [comment]
_(Don't mind the rounded corners of my screen. They are overlayed by an app I'm using.)_

**Comment by k0shk0sh** [comment]
Yup, I'm using drawable to draw the shadow. At first the application was going to be targeting 19+. So I really didn't change it afterwards. I'll see what I can do about it. nice catch.

**Comment by HeinrichReimer** [comment]
May also be related to #80
