### ISSUE TITLE
Don't know how to connect Enterprise account

### ISSUE THREAD

**Issue by wendsday** [k0shk0sh/FastHub#870]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Google
- BRAND: google  
- MODEL: Pixel  
---

 Hi there. I'm a designer with an Enterprise account. I just upgraded my fasthub app so I can add an Enterprise account but now that I have the option, I don't know what to do next. Do you have documentation on this?

Thanks!

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@wendsday which part are you having issues with?

**Comment by wendsday** [comment]
I'm not sure which credentials to use and I don't understand the explanation when I tap on "login with oauth"

**Comment by yakov116** [comment]
@wendsday

**Comment by k0shk0sh** [comment]
Click on ( your profile name in the drawer menu) then click on add account, choose Enterprise and please login either via Access Token or basic auth as Github does support Oauth in Enterprise accounts. 

I hope that explain it.

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wendsday** [comment]
@yakov116 

>@wendsday put in your enterprise info. Or create a token and login using the token

The enterprise info didn't work.
I don't know how to create a token - can you link to a step by step guide?

@k0shk0sh I need more guidance than that. Basic Auth didn't work and I don't know how to do the Access Token thing.

**Comment by k0shk0sh** [comment]
@wendsday could you tell me what error message you receiving? If there is any? 

The guide is straight forward if you followed the steps correctly above you should end up logging in. 

Have you entered the right Enterprise url? 

Could you please be more specific on what have you tried/steps you did?

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wendsday** [comment]
Of course!

Here, I chose `Enterprise`
![screenshot_20170817-122938](https://user-images.githubusercontent.com/840674/29430062-d17a37aa-8347-11e7-8a64-ea2e8bfc0e26.png)

I then tried entering my credentials, which I didn't think would work because If I wanted to log into my enterprise account in my browser, I'm taken to my organization auth page. But I tried it anyway:
![screenshot_20170817-121848](https://user-images.githubusercontent.com/840674/29430036-b5c9e140-8347-11e7-85b4-fa7213cc43d4.png)

I then tried the `Login using your default browser (OAuth)` link and got this Warning which honestly, I don't understand:
![screenshot_20170817-121856](https://user-images.githubusercontent.com/840674/29430123-10d0bc08-8348-11e7-979a-06e40c8ce3e3.png)

**Comment by yakov116** [comment]
@wendsday can you generate a access token? I dont have an enterprise account so i don't know exactly where to direct you. it should be under the settings of your account.

**Comment by wendsday** [comment]
Let me try that. I assume you mean that it's in the settings of my enterprise GitHub account ?

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@wendsday yes

**Comment by wendsday** [comment]
Hah! That was easier than I thought. 
I was doing the wrong thing - creating a new OAuth Application instead of creating a Personal Access Token. I used that instead of the OAuth password in the login page and it worked. Thanks!

**Comment by yakov116** [comment]
@wendsday yw glad it worked enjoy!

_Sent from my Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
