### ISSUE TITLE
Color schemes / themes dont work 

### ISSUE THREAD

**Issue by cpriest** [k0shk0sh/FastHub#871]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G955U1  
---

 Color schemes show When selecting them however the background color doesn't change and when viewing code from Repository the color theme is not present. The theme chooser just has a bunch of duplicated entries that don't seem to do anything, even after closing and restarting. 

_Sent from my Samsung SM-G955U1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@cpriest Which theme are you trying to change?

**Comment by k0shk0sh** [comment]
I'm not sure what are you referring to? Could you please screenshot your issue or take a video that shows the steps to produce your issue? 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cpriest** [comment]
@k0shk0sh you know I just went in and tried it again and realized that I slide left to right to choose a theme and could choose a dark background theme, after which I can see my color scheme is showing.

I was confused on my end by the UI. Used to a color scheme to set the background color of code as well.

_Sent from my Samsung SM-G955U1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Owh, you didn't hit the apply button 😁.
Glad you solve it.

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cpriest** [comment]
Actually I didn't realize at first try that I could swipe left/right to 
choose a different theme.  I thought the 'gibberish sample entries' were 
the theme choices.  When I went in this time I realize I could swipe 
left/right to choose the theme.

Thanks!
