### ISSUE TITLE
Html code is visible when ad fails to load 

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#872]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Sony
- BRAND: Sony  
- MODEL: E6653  
---

 My assumption is it's a issue with the module that's serving the ads, but I haven't checked for certain. 

It doesn't happen every screen,  seems to be infrequently,  I'd say one in every 5 view changes. 

![screenshot](http://i.imgur.com/kawnVLt.png)

**Comment by k0shk0sh** [comment]
@GeorgeWL long time no see 😁, I suggest you to disable the ad as FastHub no longer inlcude them & its officially removed by next release. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
