### ISSUE TITLE
Doze in Android O causes fasthub to never show notifications

### ISSUE THREAD

**Issue by tjhrulz** [k0shk0sh/FastHub#876]
**FastHub Version: 4.0.3**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- MANUFACTURER: Huawei
- BRAND: google  
- MODEL: Nexus 6P  
---

 Title says it all, disabling doze optimizations causes notifications to happen normally

**Comment by k0shk0sh** [comment]
We use Job schedules to run the notifications relying on firebase, unfortunately we can do much unless we use Push notifications to do that. 

Its really normal thing. As Github doesn't send push notifications instead FastHub goes by itself and grab latest. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tjhrulz** [comment]
Not to bother you again but now even with doze turned off for Fasthub I am not getting notifications. I have tried reinstalling the app as well as double checking that notifications are on in the app and online. I have notifications set to pull every 10 minutes and never get a notification even after a day has passed. Any idea what I might be able to do to fix?

**Comment by yakov116** [comment]
@tjhrulz do you have web notifications on?

**Comment by tjhrulz** [comment]
Yup double checked that before I posted, even turned it off and on for good measure. I may try to build the app and deploy to my phone when I am back in front of my computer in a day or two, then I can add some debugging and try to see what is up.

**Comment by yakov116** [comment]
@tjhrulz something tells me that it's the phone not the app...

**Comment by tjhrulz** [comment]
Yeah that is kinda my thought too but I could not find anything out of place so I figured I would ask if there was something I might have missed that would cause it suddenly to stop working one day (I even checked that I did not somehow set the app to ignore notifications 😝)

**Comment by k0shk0sh** [comment]
@tjhrulz you should enable web notifications as well because these what will be returned by GitHub API

**Comment by tjhrulz** [comment]
yeah those are on, and the panel itself is working and shows unread notification when I open the app. I just tried turning off email notifications but I doubt that will change it. I'll see if building from scratch or using another device makes any difference

**Comment by k0shk0sh** [comment]
By any chance, custom rom? Google play service?

**Comment by tjhrulz** [comment]
Nope, running stock Android O still have not had this months security update but the notifications stopping working was not correlated to an update.

Services version is 11.5.18
