### ISSUE TITLE
Notify on pull request

### ISSUE THREAD

**Issue by mfoysal** [k0shk0sh/FastHub#877]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: OnePlus
- BRAND: OnePlus  
- MODEL: ONEPLUS A3003  
---

Not  much of an issue but a feature request. I would really like a notification when someone requests a pull request.

**Comment by k0shk0sh** [comment]
This isn't possible as we don't rely on hosted server to do, but Github api which doesn't provide a push notifications service

**Comment by atcharatip9035** [comment]
@mfoysal

**Comment by atcharatip9035** [comment]
Atcharatip9035@gmail.com​
