### ISSUE TITLE
screen flicker when sliding on repo page with HuaWei Mate8 android7

### ISSUE THREAD

**Issue by shmilyoo** [k0shk0sh/FastHub#879]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: HUAWEI
- BRAND: HUAWEI  
- MODEL: HUAWEI NXT-AL10  
---

 It looks like due to the repo name and star/foke... area. 
when sliding down , this area will hide. And then my phone's screen start twinkling. The area show hide again and again cause twinkling.

_Sent from my HUAWEI NXT-AL10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Please search for issue before submitting new one. 

Thanks
