### ISSUE TITLE
Use custom layout for empty states

### ISSUE THREAD

**Issue by heinrichreimer** [k0shk0sh/FastHub#88]
Sometimes there's nothing to display in a list or layout.
You're currently displaying a simple text saying "No Data Available." And a button to reload.
It would be nice to have a more personalized experience when you stumble upon an empty list.
I can ask some graphic designers if they would draw some images to inform the user. Also the button should be a normal (probably elevated) `Button` instead of a simple text.
![screenshot_20170308-123608](https://cloud.githubusercontent.com/assets/5065698/23702670/8911da24-03fc-11e7-90a0-4c8149338868.png)

**Comment by k0shk0sh** [comment]
sorry, closed it mistakenly.

**Comment by HeinrichReimer** [comment]
No problem :smiley:
I've posted on G+ about this.

**Comment by HeinrichReimer** [comment]
Wow, this "Close and comment" button is trolling us 😱

**Comment by k0shk0sh** [comment]
ikr lol. btw, comments now should be displayed properly with code highlighting and basically like how github comments behave.  it will be in next version which expected to be out in Sunday.
