### ISSUE TITLE
search history and browsing history

### ISSUE THREAD

**Issue by shmilyoo** [k0shk0sh/FastHub#880]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: HUAWEI
- BRAND: HUAWEI  
- MODEL: HUAWEI NXT-AL10  
---

you mentioned in #121，when type the first letter , there will be a search history start with the first letter.
Have you ever think about to implement a full search history show in the searching page？
And a browsing repo history page？ thanks, a great app！

_Sent from my HUAWEI NXT-AL10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Hi, 

When I said search, I mean going to fasthub repo, clicking on issue tab, and clicking on the fab buttom will showup a list that has search so you only search in fasthub repo.
