### ISSUE TITLE
Feature request: Autocomplete names of users in issues

### ISSUE THREAD

**Issue by MarkBennett** [k0shk0sh/FastHub#886]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Google
- BRAND: google  
- MODEL: Pixel  
---

 I always try to mention people directly in issues when it makes sense. It would be brilliant if FastHub autocompleted these for me as I often have to switch to my browser or discard a post to check the names of people. It would be great if this worked like GitHub and was biases in favour of people participating in the issue and in my organization but this could be an extra feature later.

Thanks for the great work! ☺️

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@MarkBennett Great idea. If i am not wrong this has been done quite some time ago. If you type the first letter of the user it will show it on top of your keyboard

**Comment by k0shk0sh** [comment]
in next release to mention someone all you to do is click on reply since the comment will be in place and won't need to go to new screen

**Comment by MarkBennett** [comment]
Thanks guys. I'll try again!
