### ISSUE TITLE
Images that are uploaded from the app aren't using HTTPS

### ISSUE THREAD

**Issue by mistermantas** [k0shk0sh/FastHub#887]
**FastHub Version: 4.0.3**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

Most (good) sites now use HTTPS, that little green padlock on the browser toolbar shows if a site is secure and encrypted.

Images that are uploaded using the Fasthub app have their links with the `http` prefix. This therefore breaks the padlock because everything on the page must be in HTTPS. (GitHub could be using a proxy, I don't know, but this is the case by default.)

Also it's just gross to see the `http` prefix.

**Comment by k0shk0sh** [comment]
buildConfigField "String", "IMGUR_URL", '"https://api.imgur.com/3/"'

obviously I'm using https, GitHub then uses their own image urls so you better be speak to GitHub about it.

**Comment by mistermantas** [comment]
@k0shk0sh Uh, no.

You're using HTTPS *just* for the API. The fact that Imgur returns a non-TLS URL is, well, I don't really know why that's the case. Probably for backwards compatibility. You could just use the returned URL and add an "S" to the end of https if it's not there.

(I assume you know that you're using Imgur for uploads, not GitHub. There's no way for me to talk to Imgur so there you go.)

**Comment by k0shk0sh** [comment]
![Hello](http://i.imgur.com/dy2BxnB.png)

**Comment by k0shk0sh** [comment]
I'm confused, GitHub should use their god damn image urls because they convert it, so I'm not really what has happened 😕

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/cpHuNKY.png)

**Comment by mistermantas** [comment]
Ah, GitHub proxies all images to `cameo` to make sure HTTPS never breaks. That’s my quick assesment of it, anyway. So I guess it doesn’t really matter if the images are linked with HTTP or HTTPS.

**Comment by k0shk0sh** [comment]
@mistermantas yep, anyway I have changed that.
