### ISSUE TITLE
Replace Slack invite link with Discord link in About

### ISSUE THREAD

**Issue by sid-maddy** [k0shk0sh/FastHub#888]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Xiaomi
- BRAND: Xiaomi  
- MODEL: Redmi 4X  
---

[For quick access](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/java/com/fastaccess/ui/modules/about/FastHubAboutActivity.java#L146)

_Sent from my Xiaomi Redmi 4X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
hey thanks for noticing that, please do search for an issue before submitting new one. 👍
