### ISSUE TITLE
Pinned repos are gone

### ISSUE THREAD

**Issue by GroovinChip** [k0shk0sh/FastHub#889]
**FastHub Version: 4.0.3**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- MANUFACTURER: Google
- BRAND: google  
- MODEL: Pixel XL  
---

Opened up FastHub to look at pinned repos to find that they were gone.

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
were you forced to logout? could you please be more specific?

**Comment by GroovinChip** [comment]
Nope, no logout. Everything is the same except my pinned repos are gone.
Not sure what more detail I can give you :/

On Aug 25, 2017 10:11 PM, "Kosh Sergani" <notifications@github.com> wrote:

were you forced to logout? could you please be more specific?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/889#issuecomment-325073875>,
or mute
the thread

**Comment by k0shk0sh** [comment]
@GroovinChip then maybe you switched accounts? Could it be?

**Comment by GroovinChip** [comment]
Oh my God. I changed my username. That's it.
