### ISSUE TITLE
Submit feedback layout

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#89]
The feedback layout could be improved by making the button elevated and with a colored background.
Also the margin is wrong and the cards shadows get clipped horizontally. Maybe omitting the cards at all and placing the text views on the same layer would be even better. Or you might want to use some code from https://github.com/HeinrichReimer/android-issue-reporter

**Comment by k0shk0sh** [comment]
I actually have changed this along side #81  however, the button should be changed to fab as I liked your design :p
