### ISSUE TITLE
[FR] Make it possible to accept invitations with the App

### ISSUE THREAD

**Issue by SitiSchu** [k0shk0sh/FastHub#890]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: motorola
- BRAND: google  
- MODEL: Nexus 6  
---

 Would be great if you could accept Invitations through the app...right now clicking invitation links only opens the repo so I'd have to clear defaults for the app since opening he link in the browser just opens the app again.

I'm not sure if it is possible but if it is it would be grest. if it was added.

**Comment by k0shk0sh** [comment]
FastHub now once it catches its an invitation it will open chrome tab or browser for you.
