### ISSUE TITLE
.svg cannot display correctly

### ISSUE THREAD

**Issue by maple3142** [k0shk0sh/FastHub#891]
**FastHub Version: 4.0.3**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- MANUFACTURER: Xiaomi
- BRAND: Xiaomi  
- MODEL: Redmi Note 4  
---

 I try to open `.svg` file, but cannot see anything, both xml and image

_從我的 Xiaomi Redmi Note 4，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by k0shk0sh** [comment]
link to file???

**Comment by maple3142** [comment]
@k0shk0sh the file is inside a private repo...

_從我的 Xiaomi Redmi Note 4，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_
