### ISSUE TITLE
Cannot able to see list of files in repo

### ISSUE THREAD

**Issue by satishbabariya** [k0shk0sh/FastHub#892]
**FastHub Version: 4.0.3**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-A700FD  
---

 Error while selecting Files in repo 

_Sent from my Samsung SM-A700FD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
it would be really helpful to tell me what is the repo that is having this issue. 

it mean that you facing issue that everyone one is facing it too. 
please be more specific.
