### ISSUE TITLE
PowerShell tag almost not visible in dark theme in repo list

### ISSUE THREAD

**Issue by bramborman** [k0shk0sh/FastHub#894]
As you can see on the screenshot, my repo AppVeyorBuildScripts is writen mostly using PowerShell so GitHub gave it the PowerShell tag. But in dark mode the tag can barely be seen.

**FastHub Version:  4.1.0**
**Android Version: 7.1.2 (SDK 25)**  
**Device Information:**
- MANUFACTURER: LGE
- MODEL: Nexus 5X
---

![Screenshot](https://user-images.githubusercontent.com/20975774/29753680-122f7850-8b77-11e7-954a-78609b1af201.png)

**Comment by k0shk0sh** [comment]
I can't do much about it honestly, people want it GitHub language color and here it is.

**Comment by bramborman** [comment]
What about having an option to use the default colors or colors contrasting with current theme? Or adding a background or outline to the tag?

**Comment by k0shk0sh** [comment]
adding background to the language will make it look ugly imo, I'm against adding customization and complexity just for this. we just gotta live with it 🙂
