### ISSUE TITLE
Bigger comment edittext (getting bigger!)

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#896]
**FastHub Version: 4.1.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

So when typing comments in a new comment edittext in 4.1.0 release, the textview size is fixed. Can you increase the textview size as there is a new line until such limit like 5 sentences? Then users should scroll to see other text.

See telegram chat edittext for example.

**Comment by k0shk0sh** [comment]
you could click the toggle full screen first icon on the right hand side to go full screen.

**Comment by cozyplanes** [comment]
oh that was hidden.... didnt noticed it

**Comment by yakov116** [comment]
@k0shk0sh I think you should remove the non essential items so it will be easy to find

**Comment by k0shk0sh** [comment]
@yakov116 what about it to find? its the first item visible from the right side.  he didn't see it at first because he never toggled the markdown as it was your idea to hide them at the first place, so what you suggesting doesn't add anything, its still going to be hidden. ><

**Comment by yakov116** [comment]
@k0shk0sh My idea was to hide the non-essential items too! 

![image](https://user-images.githubusercontent.com/16872793/29776666-5ebb6ad4-8bd7-11e7-8a61-ab809a4805d2.png)

**Comment by k0shk0sh** [comment]
it doesn't matter, your point is still to hide everything, and keeping not keeping the others doesn't change a thing, still, the expand icon is fixed in place and it isn't moving anywhere. so still, your argument invalid and i'm not going to change anything, what has been done, is done.

**Comment by yakov116** [comment]
@k0shk0sh agree will you, what is done is done 🤐

**Comment by k0shk0sh** [comment]
@yakov116 good boy :D

**Comment by cozyplanes** [comment]
@k0shk0sh r ya a father?  :joy:
