### ISSUE TITLE
Ability to see current labels in Issues

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#897]
**FastHub Version: 4.1.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---
---
---

Sometimes there are a long history of labels being marked and unmarked.

Can we see the current labels in a popup? 

You can put a button in the overflow button next to the issue number to open the popup.

**Comment by k0shk0sh** [comment]
long click on issue from outside or PR to see everything

**Comment by cozyplanes** [comment]
didnt knew that feature.
sorry for spamming(?) the issues

**Comment by k0shk0sh** [comment]
its alright, at least they are valid questions/issues.

**Comment by k0shk0sh** [comment]
this feature has been there for ages btw :p

**Comment by yakov116** [comment]
@k0shk0sh is this in the help lib?

**Comment by k0shk0sh** [comment]
@yakov116 what are you talking about

**Comment by yakov116** [comment]
@k0shk0sh when they load the app for the first time

**Comment by k0shk0sh** [comment]
@yakov116 what are you talking about? I didn't get anything

**Comment by yakov116** [comment]
@k0shk0sh When you load the app for the first time it shows you around the app what you can do......

Look here https://github.com/yakov116/My-Issues/issues/14#issuecomment-302968834

**Comment by k0shk0sh** [comment]
@yakov116 owwwh, you meant to show some sort of guides. Maybe ln future
