### ISSUE TITLE
[FR]Add "text only mode"

### ISSUE THREAD

**Issue by maple3142** [k0shk0sh/FastHub#898]
**FastHub Version: 4.1.0**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

When previewing `.md` `.svg` or others files, add a button can see the raw text with syntax highlight.

**Comment by k0shk0sh** [comment]
it will be in next version
