### ISSUE TITLE
App can't be open unless play store is opened first

### ISSUE THREAD

**Issue by k0shk0sh** [k0shk0sh/FastHub#900]
**FastHub Version: 4.1.0-debug**  
**APK Source: Unknown**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

 User in play store review rated FastHub 1star claiming that they can't open the app unless if the playstore is opened first. 

@AmyAckerRoot could you please elaborate on this? As it's quite impossible

**Comment by cozyplanes** [comment]
troll?

**Comment by k0shk0sh** [comment]
@cozyplanes not quite sure, I'm waiting for the person I tagged to elaborate on this.

**Comment by AmyAckerRoot** [comment]
Android Version: 6.0, without opening play store, when I open fasthub, it remains in the startup phase.

**Comment by k0shk0sh** [comment]
so you are disabling Google play service? then that's the issue. enable it and it will work perfectly.

**Comment by AmyAckerRoot** [comment]
I do not disable G play service. Version 4.0.3 doesn't have the problem.

**Comment by k0shk0sh** [comment]
@AmyAckerRoot well it has to do with google play services because it's the only thing that could cause the stuck at that screen. Other than that there shouldn't be a problem, and between 4.0.3 & 4.1.0 there is nothing changed but google play service library update.  Alternatively, you can go to release page in here, click on 4.0.3 and download the previous apk until I see what could be happening even tho I can't promise you anything as I can't produce it and nobody else reported such thing  :confused:

**Comment by AmyAckerRoot** [comment]
I accidentally found out the cause of the problem a few minutes ago. Beacuse my cellphone disable app secondary launch by default, fasthub can't launch app store secretly when I open fasthub. I am sorry for the inconvenience.  :sweat:

**Comment by k0shk0sh** [comment]
it's alright, what matters is that its fixed :) I hope you update your review on the playstore that would be really great ;),
