### ISSUE TITLE
Dark theme default

### ISSUE THREAD

**Issue by nblackburn** [k0shk0sh/FastHub#902]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Motorola  
- **Brand:** Motorola  
- **Model:** Moto G (3rd Gen)  
---

 Set the theme to prettify_dark on dark themes if the previous theme was the default.

**Comment by yakov116** [comment]
@nblackburn your talking about code style?

**Comment by nblackburn** [comment]
@yakov116 Yeah

**Comment by yakov116** [comment]
@nblackburn as @k0shk0sh labeled its a duplicate. We will not change any code styles by default.

**Comment by nblackburn** [comment]
@yakov116 Can you reference the duplicate?

**Comment by yakov116** [comment]
@nblackburn your right I was thinking of #871.

Thanks for your feedback

**Comment by k0shk0sh** [comment]
https://github.com/k0shk0sh/FastHub/issues/758
quick search showed up this ;)

**Comment by yakov116** [comment]
@k0shk0sh LOL i'm slow on the pickup 🤕

**Comment by nblackburn** [comment]
I don't think that is the same issue you know.

What i was hoping for is that if your code style is set to `prettify` and you then change the the UI theme to one of the darker ones then it would automatically change the code style to `pretty_dark` to accommodate.

**Comment by k0shk0sh** [comment]
it is the same, is to toggle between the themes it was such way, but then now its user preference and no longer in my hands :)

**Comment by nblackburn** [comment]
@k0shk0sh Ahh, i was looking at #871 (quoted by @yakov116) rather than the one you posted (which is relevant).

**Comment by k0shk0sh** [comment]
owwh, sorry I didn't see that reply that he made, the one I mentioned is what I referred too as duplicate :)

**Comment by nblackburn** [comment]
@k0shk0sh No worries, i didn't see yours either so we are both as guilty.
