### ISSUE TITLE
Teal customized accent displays as Green

### ISSUE THREAD

**Issue by TheWithz** [k0shk0sh/FastHub#903]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel C  
---

**Comment by yakov116** [comment]
@TheWithz Picture please? Also if possible please create issues using the app.

Thanks for your feedback

**Comment by TheWithz** [comment]
@yakov116 I am using the app. 

_Sent from my Pixel C using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

However I cannot post screenshots, please see #904

**Comment by yakov116** [comment]
@TheWithz What version are you on?

**Comment by TheWithz** [comment]
@yakov116 
FastHub Version: 4.1.0
Android Version: 7.1.2 (SDK: 25)
Device Information:
• Manufacturer: Google
• Model: Pixel C

**Comment by yakov116** [comment]
@TheWithz Let me check it out

**Comment by yakov116** [comment]
![](https://i.imgur.com/HJWSfDx.png)

**Comment by yakov116** [comment]
@TheWithz I answered your issue in #904 can you post a screen shot of this issue

**Comment by TheWithz** [comment]
@yakov116 
![](https://i.imgur.com/8EboPTt.png)

![](https://i.imgur.com/WAuB1X2.png)

**Comment by yakov116** [comment]
@TheWithz Thanks reproduced.
Side note: I am going to delete all non relevant info 

@Dreamersoul want to take a look at this?

**Comment by Dreamersoul** [comment]
i am currently busy but will look into it over the weekend :) thanks for reporting it @TheWithz

**Comment by Dreamersoul** [comment]
we can see that the theme engine is treating green and teal as the same if the theme is dark: 
https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/java/com/fastaccess/provider/theme/ThemeEngine.kt#L92
which means that this isnt a bug its a just a missing color from the theme's palette.
@k0shk0sh am i correct or am i missing something?

**Comment by yakov116** [comment]
@Dreamersoul it looks like you are correct!

**Comment by k0shk0sh** [comment]
@Dreamersoul yep, you definitely are 🤣
