### ISSUE TITLE
Screenshots in comments bring up link dialog

### ISSUE THREAD

**Issue by TheWithz** [k0shk0sh/FastHub#904]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel C  
---

 using the Image button brings up the Link dialog rather than a picture select.  EDIT: bad wording.

**Comment by yakov116** [comment]
@TheWithz well that is what it supposed to do! It uploads to imgur to preview the image click the eye in the right corner

**Comment by TheWithz** [comment]
oh. Sorry about that. User error :/

**Comment by yakov116** [comment]
@TheWithz No worries! I though something else happened 😄
