### ISSUE TITLE
Too much animations

### ISSUE THREAD

**Issue by paphonb** [k0shk0sh/FastHub#906]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia XZ  
---

Please add a way to reduce more such as circular reveal on the loading dialog and slide from right in settings.

**Comment by k0shk0sh** [comment]
Alright I have just done that & it will be in the next release.

P.S: its always good to report the issue here instead of rating fasthub low because you want something, the low rating will only slow development instead of making it fast. 

Thanks for your time on reporting this.

**Comment by k0shk0sh** [comment]
Owh yeah, and I hope you could evaluate your rating accordingly 😃
