### ISSUE TITLE
[4.1.0] Login bug, screen hangs even though authentication worked

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#907]
---

When you login using "Open in browser":

![](https://s26.postimg.org/7ci9l8rux/Screenshot_20170830-150152_01.png)

After logging into github, app resumes but is stuck at login screen:

![](https://s26.postimg.org/ba5janeo9/Screenshot_20170830-150214_01.png)

However, hitting back key to exit app and relaunching app, app is logged in:

![](https://s26.postimg.org/f7st021hl/Screenshot_20170830-150237_01.png)

So, authentication works but for some reason login screen hangs.

Also,
what is the point of having unauthorized user toast when you are not logged-in?
Obviously, login is needed.

![](https://s26.postimg.org/iz2dmdf61/Screenshot_20170830-150127_01.png)
It is slightly confusing as you did not login yet, and it makes it seem like it is trying to login with wrong credentials.

**Comment by yakov116** [comment]
@k0shk0sh I had this issue too when I used my emulator

**Comment by k0shk0sh** [comment]
I can't produce it & It seems like the user removed their device info for a reason. 

If it was an emulator, please use a valid device to test with.

**Comment by rancidfrog** [comment]
It is on device oneplus 5.
Webview based browser.

**Comment by k0shk0sh** [comment]
@rancidfrog webview based browser ? Didn't get that

**Comment by yakov116** [comment]
@rancidfrog Do u have any external browser installed on your device? Like chrome?

**Comment by cozyplanes** [comment]
i heard oauth is not avail. in webview based browser due to security reasons

**Comment by rancidfrog** [comment]
It works fine with OctoDroid. I am able to login. But, with Fasthub it hangs on login screen.
So, issue is there. Whether they chose to fix is up to them. Not many people use simple browsers, I guess.

**Comment by cozyplanes** [comment]
@k0shk0sh

**Comment by rancidfrog** [comment]
Not really a big issue though, as eventually you can login.
But, just makih devs aware that on certain browsers there can be a hang on login screen, however exiting app with back button and relaunching will login magically

**Comment by yakov116** [comment]
@rancidfrog I thought that was the issue. The issue is there but it's for such a small amount of people I don't think it's worth debugging. 

I don't mean to push you away but there are over 50,000 downloads that means that most people don't have this issue. To fix an issue that has to do with the user not having the standard browser is not something a dev should put time into.

**Comment by rancidfrog** [comment]
Yes, I understand.
I was just mentioning it so that you are aware. So if anyone else has the problem you know that they can still login they just exit and launch app again and it is logged in.

Even with other issue regarding splash it is a small issue where some users find annoying.
And I was just showing you some other solutions that other devs came up with, like transparent or blue background.
I know you will make your decision, but just pointing out that just in case, there is this little bug or annoying ...
Thank you for your time
