### ISSUE TITLE
[4.1.0] Adding images always inserts to end of file and not at cursor position, using toolbar

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#908]
When inserting image:

![](https://s26.postimg.org/b9n5rol55/Screenshot_20170830-153304_01_01.png)

It always adds image to the end, and not where the cursor was.

![](https://s26.postimg.org/ty57f0c21/Screenshot_20170830-153311_01.png)

**Comment by k0shk0sh** [comment]
was wondering why not using fasthub to attach images?

**Comment by rancidfrog** [comment]
I am? Fasthub toolbar - image button.

![](https://s26.postimg.org/eux9ziart/Screenshot_20170830-162646_01_01.png)

**Comment by k0shk0sh** [comment]
@rancidfrog  but as showing in the images posted here, you are uploading them somewhere and pasting the links. 
If you click select, you could select image from ur galary and let fasthub upload it to imgur and do everything for u.

**Comment by rancidfrog** [comment]
Habit.
Did not realize select is a button which does all that you mentioned.
Also, I resized image when uploading, otherwise it can be too big.
But, I did not test "select" from fasthub, yet.
Does it past link to cursor, though?

**Comment by yakov116** [comment]
@rancidfrog Try it and report back 😄

**Comment by k0shk0sh** [comment]
@rancidfrog nope it behaves the same
