### ISSUE TITLE
Enabling the Android Move To SD Card Feature?

### ISSUE THREAD

**Issue by AnonymerNiklasistanonym** [k0shk0sh/FastHub#909]
I didn't find an issue about this topic so I wanted to ask if it is possible to add the optional "Move to SD Card" feature.

I myself haven't yet tried to add it or even developed Android Apps yet but after looking at the following two websites it doesn't seem very difficult (from my point of view - I am just interested in adding this feature because I have only limited internal system space so enabling this feature would be very cool):
* https://code.tutsplus.com/tutorials/quick-tip-enabling-the-android-move-to-sd-card-feature--mobile-862
* https://developer.android.com/guide/topics/data/install-location.html

It seems like you only need to modify the android manifest by adding `android:installLocation="auto"` like in the following example from [the first website](https://code.tutsplus.com/tutorials/quick-tip-enabling-the-android-move-to-sd-card-feature--mobile-862):

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.mamlambo.article.phrasebook" android:versionCode="2" android:versionName="1.0.1"
android:installLocation="auto">
...
</manifest>
```

I really like the app and hope that I didn't wasted your time with something that obviously has reasons to not be activated or can't be activated because of some services or something other.
Also sorry for my probably not so good English. 

😄 

**FastHub Version:**   4.1.0
***Android Version:**  6.1.0*
***Device Information:**  ONE E1003*

**Comment by AnonymerNiklasistanonym** [comment]
This is probably the best explanation of the effects of adding `android:installLocation="auto"` from https://developer.android.com/guide/topics/data/install-location.html:
_"If you declare "auto", you indicate that your application may be installed on the external storage, but you don't have a preference of install location. The system will decide where to install your application based on several factors. The user can also move your application between the two locations.

When your application is installed on the external storage:

There is **no  effect on the application performance** so long as the external storage is mounted on the device.The .apk file is saved on the external storage, but **all private user data, databases, optimized .dexfiles, and extracted native code are saved on the internal device memory**.The unique container in which your application is stored is encrypted with a randomly generated key that can be decrypted only by the device that originally installed it. Thus, an application installed on an SD card works for only one device.The user can move your application to the internal storage through the system settings."_ 

Hope I could help.

**Comment by k0shk0sh** [comment]
Opps, this is fixed in my previous commit :)

**Comment by yakov116** [comment]
@k0shk0sh This does what?

**Comment by k0shk0sh** [comment]
@yakov116 make the app installable on the external sdcard.
