### ISSUE TITLE
Unable to select comments in PR

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#910]
**FastHub Version: 4.1.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

 After you implemented the lazy loading I've noticed that sometimes I cannot select comments. The scenario is non-stable and issue happens from time to time, however as per [Murphy's law](https://en.m.wikipedia.org/wiki/Murphy%27s_law) it happens exactly when you need to select text :disappointed:

Steps to repro:
- Open [this](https://github.com/AutoFixture/AutoFixture/pull/794) PR. 
- Quickly scroll down till you reach the end of the. 
- Try to select the latest comments (or simply each one) 

On my device sometimes selection doesn't appear - no matter how long I hold my finger over the comment. Issue happens for the whole comment - I cannot select it, but can select the other comments around. 

Likely it's somehow related to dynamic comments as previously it never happened. 

Let me know whether you are able to repro it.

**Comment by k0shk0sh** [comment]
I can't produce it, what I can suggest you to do, if the selection didn't happen the first one, lift your finger and do another selection and it will work. it's Android OS feature and I didn't write it so I could modify it :)

**Comment by zvirja** [comment]
No, it doesn't help. If I cannot select a comment, nothing helps. I can easily select the siblings and after I select something else, I still cannot select the comment. The only thing I can do is to open issue in browser and copy text from there.

Issue reproduces very often on my device - this is not something regular.

Try to use some issue with large comments history and select comments that are created dynamically. Not all the comments are affected.

Another thing I noticed. When I open some issue, I can select the initial comment. However after I scroll down so that comment bulks are lazily fetched and added, if I return to the initial comment - I am not able to select it more. It looks like something weird happens with control.

I'm able to reproduce issue for each time using [this](https://github.com/AutoFixture/AutoFixture/issues/703) issue as it has large history. When I scroll down a lot, I cannot select most of the previous comments..

**Comment by k0shk0sh** [comment]
> Issue reproduces very often after the update - this is not something usual and doesn't look like Android feature.

The selection feature is Android default implementation & nothing I can do about it, I can select any comment on the issue you linked to, would you want a video to believe me?  I believe that it might be broken for you somehow, but again, I'm asking you try what I mentioned. sometimes I have to do the same.

**Comment by k0shk0sh** [comment]
there is nothing changed in that area in 4.1.0 but the support Lib.

Its not about you know Android or do I, its about finding a solution for something that I can't produce, you are claiming something has changed from my side, but again i'm telling you that the comments layout is untouched and there is only one flag that enables that and its still there. there is no other implementation for the selection. 

I'll investigate on this, however I can't promise that I'll fix it because I never broke it ;)

**Comment by zvirja** [comment]
I'll try to test that later on another Samsung device to see whether that happens there as well.

Issue happens only after the next comments bulk is fetched. It could happen that issue was present earlier as well, but I never faced it because bulk size was greater..

**Comment by zvirja** [comment]
> yeah, I just encountered that 

Awesome! :relieved: 

Let's see whether you are able to find the root cause and whether it's something on app side.

**Comment by k0shk0sh** [comment]
not sure, it seems like something is taking away the focus from the textView ;)

**Comment by k0shk0sh** [comment]
so apparently, it was there from the beginning and I guess you never fell into the time it wasn't being selectable, anyway, setting `android:layout_width="wrap_content"` into the TextView fixed it 🤷‍♂️

**Comment by zvirja** [comment]
@k0shk0sh Thanks a lot for investigating and fixing that! It was a really annoying issue and I'm happy to know that it will not happen in the future more 😃
