### ISSUE TITLE
Add feature to scroll to the end

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#911]
**FastHub Version: 4.1.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

After you implemented lazy loading it become a nightmare to work with issues with large history. Previously I quickly scrolled and appeared at the end but now I only can slowly move through Ajax fetches.. 

Consider [this](https://github.com/AutoFixture/AutoFixture/issues/703) issue as a sample - it will take ages till you reach the last comment (e.g to post a reply). 

Could you please add a feature to quickly scroll to the end (e.g. via some button) or a setting to disable the lazy loading? I'd actually vote for the latter as most of time I work with the most recent comments (at the end) and current approach brings a lot of pain. :cry:

**Comment by k0shk0sh** [comment]
what do u mean by lazy loading? you mean the progress showing below on each page? it has always been there it just now that it shows progress in bottom. so I'm really unclear in what you are saying since it was there but no visuals but upper progress

**Comment by k0shk0sh** [comment]
owh yeah, now the difference is I'm loading 30 comments per page. previously was 100

**Comment by zvirja** [comment]
Oh, sorry that I haven't described that clearly.
Previously when you open issue or PR, all the comments were fetched from the server at once and rendered. That allowed you to use quick scroll gesture and you appeared at the end of the issue/PR.

On the 4.1.0 you implemented lazy comments fetch - when you scroll to the end of the previous bulk you fetch the next comments bulk. With such approach currently there is no a way to conveniently reach the latest comment - it's a pain.

I'm asking you rather to add a button to scroll to the end or a setting to fetch & render all the comments at once.

**Comment by k0shk0sh** [comment]
I'll bring back 100 (the maximum by GitHub api) pagination. 

in your other issue, you requested loading speed so I minimized the number of comments 🤦‍♂️

**Comment by zvirja** [comment]
> owh yeah, now the difference is I'm loading 30 comments per page.

I have a feeling that you fetch about 5 or 10 comments - it doesn't look like that all 30 comments are fetched. Probably, you fetch 30, but render only some of them..

**Comment by k0shk0sh** [comment]
No not really, sometimes I noticed GitHub will return random number of items and not really 30 🤦‍♂️  I just fixed the pagination to 100 by default

**Comment by k0shk0sh** [comment]
closed with c0be138eceeef3b8f95382c079202cdf1e6115e2
