### ISSUE TITLE
Unable to merge PRs in organization's repos

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#915]
**FastHub Version: 4.1.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

I am a member of organization and, therefore, have a write access to organization's repositories. However, when I open such PRs, I don't see a button to complete a PR (or close it). 

I never used this feature before, so am not sure whether I'm simple unable to find the button, or feature is not supported for such scenarios.. 

P.S. I've bought a Pro, so feature should be enabled if it's for Pro only.

**Comment by k0shk0sh** [comment]
it's not pro, its free except for different type of merge methods, default & free is merge. 

are you collaborator in the repo?

**Comment by k0shk0sh** [comment]
another question. did you look it up after clicking on pen icon, and it should be in the list there.

**Comment by zvirja** [comment]
I'm an admin there. You can navigate to my account and see the AutoFixture organization and my membership details. 
I'm able to complete PRs via UI.

**Comment by k0shk0sh** [comment]
my question is are you collaborator in the repo? or you on the repo?

**Comment by zvirja** [comment]
I'm still not sure about question. Repository belongs to the AutoFixture account, I'm logged in using my current account. Probably, the answer is that I'm a collaborator.

**Comment by k0shk0sh** [comment]
if the pen didn't show up then simply you aren't the owner or collaborator in the repo and that's what fasthub check, for both. nothing else can tell me ;)

**Comment by zvirja** [comment]
I'm a member of the AutoFixture account with "Owner" role, so I'm a co-owner of the repo. I'm able to merge via website, meaning I have permission to do that.

Could you please clarify what's wrong? Also could you show how the button looks like - probably I'm simply missing it..

**Comment by k0shk0sh** [comment]
does the pen icon show up in the toolbar?

**Comment by zvirja** [comment]
Just found the button - it's located in the menu.. Sorry for bothering you 😢

**Comment by zvirja** [comment]
Due to some reasons I expected a floating button on the right corner or at the end of comments :)

**Comment by k0shk0sh** [comment]
well, all editing related stuff will be under the pen icon for simplicity & consistency with the issue timeline
