### ISSUE TITLE
Show information about merge conflicts 

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#916]
**FastHub Version: 4.1.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

I have a PR with merge conflicts, so it cannot be completed. However, it isn't mentioned in UI somewhere. The only way to understand that is the missing merge option in menu. Consider [this](https://github.com/AutoFixture/AutoFixture/pull/711) PR as a sample - it only shows about successful AppVeyor checks.

Could you please add information whether PR can be merged?

Let me know if that's already there and I'm simply missing that..

**Comment by k0shk0sh** [comment]
what does the status header say?

**Comment by k0shk0sh** [comment]
Just showing all checks has passed 🤦‍♂️ 

<img width="465" alt="screen shot 2017-09-02 at 17 22 25" src="https://user-images.githubusercontent.com/960767/29996675-5a065aa0-9003-11e7-827a-d65f2069aa02.png">

**Comment by zvirja** [comment]
Sorry - was unable to upload a screenshot as upload from app doesn't work (error occurs).

Nothing at all is present in the header about merge, only in timeline..

Likely, we need to handle both cases when PR cannot be merged and when checks failed..

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/WeLoGbm.jpg)

**Comment by k0shk0sh** [comment]
uploading is working  :confused:

**Comment by k0shk0sh** [comment]
3 in 1 😅

**Comment by zvirja** [comment]
Hmm.. Image upload works from Samsung, but not from MiUi.. Will investigate and fire a separate issue.

**Comment by k0shk0sh** [comment]
MiUi what phone is this & is it custom rom?

**Comment by zvirja** [comment]
Hm.. This PR can be merged, but I don't see a message "This pull request can be merged" somewhere..


![](https://i.imgur.com/E98FZvc.jpg)

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/OQogyk5.png)
I actually was doing the status wrongly, I suppose to send the sha but were sending the ref.

**Comment by k0shk0sh** [comment]
later I'll be releasing new version with file commit(edit, delete & create) as well as directory & files commit history
