### ISSUE TITLE
Space between text and emoji is not being rendered

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#917]
**FastHub Version: 4.1.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

There is a pretty annoying issue with emoji rendering - the space char between text and smile is not being rendered. See a sample below:

Line with a space before smile: :wink:

Line without a space before smile::wink:

As you might notice, both lines are being rendered identically, while the first line should render a space indent before emoji. If you open this issue in browser you will see a difference. 

The issue is minor, however it's very annoying. I always place a space between char and emoji to have a visual distance and make them look better. However, with existing render it's impossible to understand whether space is present or not.

Could you please adjust the text rendering to respect the space char and render it?

**Comment by k0shk0sh** [comment]
there is something with the renderer and I can't seem to find it. will dig more once my hands are not busy
