### ISSUE TITLE
Doesn't load Readme on repositories 

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#922]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia Z5  
---

 this seems to happen rather often actually.  Usually with a "failure to load"  or a "could not find resource" toast message.

**Comment by yakov116** [comment]
@GeorgeWL can provide a link to the repo?


_Sent from my Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by GeorgeWL** [comment]
@yakov116 doesn't seem to be any specific repos.

More like a timeout issue, happens on lots of repos for me.

But just not every time.

**Comment by k0shk0sh** [comment]
if its a timeout then what could I do about it? if your connection isn't good or GitHub having some server problems (which they do sometimes when they do maintaince). 

you literally answered your question 🤣

**Comment by GeorgeWL** [comment]
wasn't sure if it was my side or if it was an api problem tbh.

guess my side.
