### ISSUE TITLE
Suggestion: Maybe a "Pretty Print" option in options menu of minified files 

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#923]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia Z5  
---

 just sounds like it could be a nice feature,  no clue how complex it would be to implement. 

Pretty Print is where it recognises the fact a file is minified then displays it as if it is not by doing a bit of magic to it.

**Comment by k0shk0sh** [comment]
well that will require some work on the highlightjs library which is written in js & I don't think I could comeup with something about it lol. its js /shrug

**Comment by k0shk0sh** [comment]
was about to create new label just for this issue (type: impossible) lok

**Comment by GeorgeWL** [comment]
I know js. but I'm no expert.  I'll look at it anyhow.

**Comment by yakov116** [comment]
@GeorgeWL  PR's are allways welcome
