### ISSUE TITLE
Unable too see code for dark theme

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#925]
**FastHub Version: 4.1.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

When you apply the last dark theme in the picker (BTW it's better to add names in UI, so we can refer to them more specifically), it's impossible to preview the `java` files:

![](https://i.imgur.com/hakoxhU.png)

I'm unable to recognize any text.. Likely, the colors or background should be adjusted..

**Comment by k0shk0sh** [comment]
#902 #752

**Comment by zvirja** [comment]
Sorry for a duplicate ;-)

**Comment by zvirja** [comment]
@k0shk0sh Could you also add theme names to the picker as I mentioned above?

**Comment by k0shk0sh** [comment]
they are in the picker? aren't they?

**Comment by zvirja** [comment]
Have I overlooked the name? I'm blind to see it..
![photo_2017-09-08_10-49-56](https://user-images.githubusercontent.com/1074182/30201442-7f5bfc5e-9483-11e7-8e0d-acb8c208fa55.jpg)
