### ISSUE TITLE
Load images

### ISSUE THREAD

**Issue by lologolo** [k0shk0sh/FastHub#926]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5  
---

<--Please submit your request in english.-->
 
Can you add the possibility to load images in the comments?

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/qtkPnLg.png)
huh? images load in comments & even gif does. so I'm not sure what is your question.

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/IILsp7n.png)

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/Ixq5VRl.png)

**Comment by lologolo** [comment]
excuse me I didn't see that the menu is scrollable. you can close  the issue.
