### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by lologolo** [k0shk0sh/FastHub#927]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5  
---

 Can you add the possibility to receive notifications by app? I only receive them by mail

**Comment by k0shk0sh** [comment]
could you please discover the app before opening an issue? also reading the Readme or playstore description is good to tell you what the app does. 

now to answer your question:
open menu drawer go settings and configure your notification settings from there, you only need to set the interval for the notification which by default is nothing.

**Comment by lologolo** [comment]
I know that is possible change the update interval, but anyhow I have never received a notification by app, so I think that is a bug

**Comment by k0shk0sh** [comment]
Well, if you open them up in email, they will be marked as read in github and therefor wont be receiving any in FastHub also you have to put the interval into consideration, meaning that the job will only run at the interval you put so it can never be received immediately unless if you specified it to 1 minute. 

therefore, its not a bug ;)

**Comment by lologolo** [comment]
for example now I have received this message by mail, I didn't read it , I have waited for more than 1 minutes and  the notification panel shows nothing

![](https://i.imgur.com/pyTI5q1.png)

![](https://i.imgur.com/Ddsu7We.png)

**Comment by k0shk0sh** [comment]
Right notification won't show u unread, it will show read only. first tap will show u unread.

with that said. it's a job schedulor meaning that you can't be 100% it will run in one minute. 

just give it time. also it will be helpful if u can tell if u have google play service & where u install the app

**Comment by lologolo** [comment]
i have this version: 
![](https://i.imgur.com/fHjAofT.png)

**Comment by k0shk0sh** [comment]
cool then everything should be fine :). just give it some time & don't open the mail at all.

**Comment by lologolo** [comment]
maybe I understand the problem : I have to check this buttons in web version settings

![](https://i.imgur.com/Z4OP3G1.png)
