### ISSUE TITLE
In depth search

### ISSUE THREAD

**Issue by lologolo** [k0shk0sh/FastHub#928]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5  
---

 Please can you add in deph search to find a word inside files?
I know that there is the option to search inside files, but you can't see the word where is precisely, so I suggest to make highlighted the find text
For example if I search "linear layout" and click on a file, appears that 
![](https://i.imgur.com/2klf3Z4.png)

**Comment by k0shk0sh** [comment]
this is going to be beyond java and I'm not interested on doing anything on that
