### ISSUE TITLE
App opens PDF files as text files

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#929]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A5000  
---

If in a GitHub repository there is a PDF file, the default FastHub editor downloads and handle it like a text file
Before opening the file it should check the type and if it's one of the types that the local device can handle, send an Intent to a PDF reader in this case

![](https://i.imgur.com/aD0kdch.png)

**Comment by AndreaCioccarelli** [comment]
Check this sample here: https://github.com/afollestad/aidanfollestad.com/blob/master/AidanFollestad_Resume.pdf

**Comment by k0shk0sh** [comment]
simple workaround, click menu and click download, in next version I won't allow you to open it. thanks :)
