### ISSUE TITLE
Clicking a notification does not open relevant page if app is already running

### ISSUE THREAD

**Issue by NotAFile** [k0shk0sh/FastHub#930]
**App Version: 2.1.0**

**OS Version: 23**

**Model: OnePlus-A0001**

Steps:
1. Open Issue1
1. Recieve notification for issue2
1. click issue2 notification
1. FastHub opens and shows issue1

**Comment by k0shk0sh** [comment]
2.1.0? fasthub is in 4.1.0 so I can't help you if you aren't in latest.

**Comment by NotAFile** [comment]
I am using the latest Version in F-Droid. Some googling reveals that you no longer support f-droid, which is very unfortunate. I will try using one of your releases instead.

**Comment by k0shk0sh** [comment]
@NotAFile yes please do so, you could install latest from there which has plenty of good stuff. U could imagine 2 versions ahead means what :)
