### ISSUE TITLE
Error while opening a repository 

### ISSUE THREAD

**Issue by nazavode** [k0shk0sh/FastHub#931]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Sony  
- **Brand:** Sony  
- **Model:** Xperia X  
---
Cannot open this repository:
 https://github.com/nazavode/cv

The application keeps saying that "An error occurred while communicating to the server". My guess is that the error is due to the fact that in that repository I have a git submodule.

**Comment by yakov116** [comment]
@nazavode can u add a file that is not part of a submodule?

**Comment by nazavode** [comment]
README and FILES tabs don't work, they immediately trigger the error and say "No data" while the rest of the tabs work fine.

**Comment by nazavode** [comment]
![](https://i.imgur.com/66p95JU.png)

**Comment by yakov116** [comment]
@nazavode I see that can add a regular file that is not part of the submodule?

**Comment by nazavode** [comment]
Added README.md, now the README tab works (while the error message keeps popping up). The FILES tab is still broken.

**Comment by k0shk0sh** [comment]
Type `symlink` isn't being handled by FastHub /shrug
