### ISSUE TITLE
Quick comment clears the input on fail

### ISSUE THREAD

**Issue by alashow** [k0shk0sh/FastHub#932]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Model:** Nexus 5X  
---

 I wrote a longish comment just now, like 10-15 lines and clicked 'Send' button. The app showed some toast like "No network" and cleared the input.. Boy, was I mad! (or sad)

**Comment by yakov116** [comment]
@alashow I agree with you!!!!!

**Comment by k0shk0sh** [comment]
sorry about that lol. it will fixed in next release :)
