### ISSUE TITLE
Issue preview displaying incorrectly

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#933]
**FastHub Version: 4.1.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

 I can't explain this, but just go here, long press the issues, and see the labels cut out.

https://github.com/devRant/devRant/issues 

See issues `#72`

**Comment by yakov116** [comment]
@cozyplanes I'm not sure what you are seeing 


![](https://i.imgur.com/0ZJ1b95.png)

**Comment by cozyplanes** [comment]
well, here, this is what it is showing 
![](https://i.imgur.com/Oc8Izrb.png)

**Comment by cozyplanes** [comment]
and i cannot scroll, just stuck there

maybe it is the issues only in my phone, but just reporting bcuz i am not sure

**Comment by cozyplanes** [comment]
:+1:
