### ISSUE TITLE
Close quick edit panel in comment view when 'Send' clicked

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#934]
**FastHub Version: 4.1.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

 So whenever i write some comments in the minimal view, I click the triangle to get access to the quick panel, or to open it in full screen. Whatever it does, when i click the send button, the quick panel is still there, opened.

I think it would be a nice touch to automatically close them after the user clicked the send button. Thanks.

**Comment by cozyplanes** [comment]
you mean no feature request? If then, ok @k0shk0sh

**Comment by k0shk0sh** [comment]
sorry :D . its done awhile ago and will be in next release

**Comment by cozyplanes** [comment]
Oh, no problem then. Thanks
