### ISSUE TITLE
OBJ appears when switching from markup preview

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#937]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

 When commenting, if you switch back and forth between markup edit and preview, sometimes [OBJ] appears, probably markup formatting not yet transformed to preview so it is in OBJ state?:

![](https://i.imgur.com/6RwoTCO.png)
  
In image above it should be a link, but it is  [OBJ], after switching to preview and back to edit

**Comment by k0shk0sh** [comment]
Its android Span, where it doesn't understand something it will show up as Obj usually on Images tho. I'll investigate that and try to produce it.

thanks

**Comment by rancidfrog** [comment]
It also happens on other markup formatting items I believe. 
But yes mostly on images.

**Comment by rancidfrog** [comment]
This issue happened to me again while commenting on another issue. To reproduce:
• Add image
• Select markdown preview
• Click arrow to submit￼

**Comment by k0shk0sh** [comment]
isn't once u submit the screen isn't showing anymore?

**Comment by rancidfrog** [comment]
I do not understand.
But, if you look at my previous comment above you can see in third bullet point there is an obj.
It happened when I added image and clicked  preview. OBJ appears and if I click submit it stays as in comment above (there is actual obj in comment: • Click arrow to submit￼

**Comment by k0shk0sh** [comment]
can't produce at all. following every step unmentioned. 

it seems like it's your phone problem. 🤷‍♂️
