### ISSUE TITLE
Markdown editor - no name completion

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#938]
**FastHub Version: 4.1.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

On previous versions when I typed @ symbol in full screen editor, the pop-up with name suggestions appeared. Currently it doesn't appear (e.g. when I write a comment) and that is very inconvenient. Could you please fix that?

Thank you 😊

**Comment by cozyplanes** [comment]
(life of a dev, needs to do what customer says)

**Comment by yakov116** [comment]
@k0shk0sh I think it's a nice idea if you want to tag more than one person. But your the boss
