### ISSUE TITLE
Folder skips when cancel

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#939]
**FastHub Version: 4.1.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

How to reproduce

Tested in fasthub, and other big and small repos

1. Go to file view
2. Open folder A
3. Open folder B inside A
4. Open folder C inside B
Now in the top, there will be A>B>C 
5. Press back button of PHONE 
6. It skips to folder A, not B.

When i opened more folders like

 A>B>C>D>E>F>G

And press back btn, it goes to F

**Comment by k0shk0sh** [comment]
I'm aware of that and its being there since the beginning. the preferred way is to use the tabs instead of back button.

**Comment by cozyplanes** [comment]
hmmm ok. really annoying though 😝

**Comment by cozyplanes** [comment]
so i will close for now
