### ISSUE TITLE
Combine issue activity and comments

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#94]
It would be cleaner to combine issue activity and comments in one list as GitHub web does.

**Comment by Rainer-Lang** [comment]
You mean without a ViewPager?

**Comment by HeinrichReimer** [comment]
Yes exactly! This behavior is very confusing given that all items from the two lists are actually events in the same logical timeline.
So for example a comment mentioning someone and the related "mentioned"-event should be linked visually.

**Comment by k0shk0sh** [comment]
this issue can be closed since #59 suggested this.
