### ISSUE TITLE
Jump through empty dirs

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#940]
**FastHub Version: 4.1.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

Any plans to support this?

![20170908_181330](https://user-images.githubusercontent.com/25971070/30204874-f402741e-94c1-11e7-9a2a-3bcddc3892a1.png)

**Comment by cozyplanes** [comment]
of what may i ask?

**Comment by k0shk0sh** [comment]
searching Empty show up this as second result 
https://github.com/k0shk0sh/FastHub/issues/254
