### ISSUE TITLE
Ext. browser / Chrome custom tabs

### ISSUE THREAD

**Issue by cozyplanes** [k0shk0sh/FastHub#941]
**FastHub Version: 4.1.0**  
**Android Version: 5.0.1 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G3 Cat.6  
---

 Allow users to change their prefs between opening links of files with big size in ext browser with intent or with chrome custom tabs

**Comment by k0shk0sh** [comment]
won't change, plus you got the option to open in browser from the chrome tabs.
