### ISSUE TITLE
Fdroid 

### ISSUE THREAD

**Issue by ralpheeee88** [k0shk0sh/FastHub#943]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** oneplus  
- **Model:** OnePlus One  
---

 Is this app on fdroid?

**Comment by k0shk0sh** [comment]
It was & its no longer there due to the complexity of maintaining multiple files.

**Comment by dedepete** [comment]
See #525 for more info.
