### ISSUE TITLE
Some PRs make FastHub crash when scrolling

### ISSUE THREAD

**Issue by nicolo-ribaudo** [k0shk0sh/FastHub#944]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

For example, https://github.com/babel/babel/pull/5421

**Comment by k0shk0sh** [comment]
I can't see logs right now, but I think it's due to the table in the row.
I'll fix it asap :)
