### ISSUE TITLE
Scrolling buggy in large files

### ISSUE THREAD

**Issue by J05HI** [k0shk0sh/FastHub#946]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8  
---

Scrolling laggs very much in large files.
Please improve it :)

**Comment by k0shk0sh** [comment]
I can't fix that unfortunately, what I did to at least reduce the lag is if I found the file is large I'll remove the syntax highlighting, besides that, it's Android webView and I can't do anything about it.

**Comment by k0shk0sh** [comment]
also it will be great if you could pass me the file url

**Comment by J05HI** [comment]
Maybe you could use something like this:
[https://clusterize.js.org](https://clusterize.js.org)

**Comment by k0shk0sh** [comment]
not so sure how this will help, but I'll give it a try definitely and get back to you on it later.

**Comment by J05HI** [comment]
Here an example:
[https://github.com/shashi007/google-drive-direct-remote-upload/blob/master/mimeTypes.php](https://github.com/shashi007/google-drive-direct-remote-upload/blob/master/mimeTypes.php)

**Comment by k0shk0sh** [comment]
@J05HI I'm using S8, opened that file and scrolling is pretty fine and smooth 😅😅. I'm confused now because you also use S8. 

Could you update your webview from playstore,?

**Comment by J05HI** [comment]
Okay, strange
I can't even scroll in it 😅
Everything is up to date

**Comment by k0shk0sh** [comment]
base on my tests before, this isn't even fall under the large file for my tests lol. which is strange :D

**Comment by k0shk0sh** [comment]
surprisly, opening that file in browser from FastHub (chrome tab) scrolling there lags alooot and can't even scroll, but from FastHub, scrolling is smooth 🤦‍♂️

**Comment by J05HI** [comment]
Okay I don't know why :(

**Comment by qw-in** [comment]
That example file completely freezes the app for me. Have to force quit. Cannot even use the back button

Galaxy S7

**Comment by k0shk0sh** [comment]
It works fine for me, maybe you should try and update webview from Google play?
