### ISSUE TITLE
Closed issues are not displayed 

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#947]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

Steps to reproduce:
1. Open this repo: [AutoFixture ](https://github.com/AutoFixture/AutoFixture)
2. Navigate to issues. You will see 373 closed.
3. Navigate to the `Closed` tab.

As result you'll see only 2 issues. If I use search, everything is displayed fine.

Thanks :flushed:

**Comment by k0shk0sh** [comment]
I guess I know what's going on, its due to the first pagination is fulled with PRs and only two issues are in the first page, therefore pagination wont work lol

**Comment by k0shk0sh** [comment]
:thanksgithubapi:

**Comment by zvirja** [comment]
Wow, so quick reply and guess - it's impressive :star2:

**Comment by k0shk0sh** [comment]
it happened i was in the tram :p 

GitHub API is sooo shitty that it returns PRs with the Issues API and therefore I have to filter them myself. so that is what's happening.

**Comment by zvirja** [comment]
@k0shk0sh BTW, just noticed that this issue wasn't fixed completely. Open the repository from the initial scenario and you will be unable to see all the closed issues. App version: 4.3.0.

**Comment by zvirja** [comment]
@k0shk0sh Unfortunately the issue still persists and I'm unable to see all the closed issues. The link to the repository is still the same :disappointed:

**Comment by k0shk0sh** [comment]
But the question is, it was fixed that time, why would it break this time? 🤔

**Comment by zvirja** [comment]
I don't know - probably it depends on number of opened PRs/Issues..

**Comment by k0shk0sh** [comment]
Found the issue and fixed it :)

**Comment by zvirja** [comment]
@k0shk0sh Wow, that's great! Thank you a lot for making this app better 🎖
