### ISSUE TITLE
Unable to close my own issue

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#948]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

Am trying to close my own issue ([link](https://github.com/prodot/ReCommended-Extension/issues/25)), but app says that the issue isn't editable by me (the red toast notification). When I open the issue in browser, I see the button to close the issue.

Do you need some additional info from me to investigate? I'm logged in with my personal account.

**Comment by k0shk0sh** [comment]
it's not the app who says that, so I'm unclear what is going on.

could u try again? its not like is possible to happen to 1 out of 50k.

**Comment by k0shk0sh** [comment]
I meant its not something that I show, its a response from GitHub. 

could you please also, like try and figure things out first then only open an issue? I'm sure you have been using Fasthub for awhile now and this never occurred to you, so it's unlikely fasthub issue.

**Comment by zvirja** [comment]
I've already tried for about 5 times - no luck. Just tried again - the same result. App asking for confirmation and later that red failure..

Any other ideas?

**Comment by k0shk0sh** [comment]
@zvirja nope, honestly :D . Give it some time and try again, GitHub might go down or something, it happened before here and I'm lazy to mark it as duplicate and close it. So I'm gonna let u figure this out and once it worked please close it :p. 
Good night

**Comment by zvirja** [comment]
Well, it's the first time I'm closing an issue in foreign repo via app. Will try to close via Browser to see how it goes..

**Comment by zvirja** [comment]
Well, it's the first time I'm closing an issue in foreign repo via app. Will try to close via Browser to see how it goes..

**Comment by k0shk0sh** [comment]
could u try n closs this? 😎

**Comment by zvirja** [comment]
Yep, everything works fine in browser - just closed. 

It seems issue is with app - just tried to reopen any own issue in this (FastHub) repo and got "Validation failed" error..

**Comment by zvirja** [comment]
This one works fine, but was unable to reopen [this](https://github.com/k0shk0sh/FastHub/issues/919) one.. Really weird..

**Comment by zvirja** [comment]
This one works fine, but was unable to reopen [this](https://github.com/k0shk0sh/FastHub/issues/919) one.. Really weird..

**Comment by k0shk0sh** [comment]
but you seemed able to close & reopen ?

**Comment by zvirja** [comment]
There ones which I can (like this), but there are a lot of different ones in your repo I cannot..

**Comment by zvirja** [comment]
There ones which I can (like this), but there are a lot of different ones in your repo I cannot..

**Comment by zvirja** [comment]
App started to send duplicates..

**Comment by k0shk0sh** [comment]
https://github.com/k0shk0sh/FastHub/issues/596 https://github.com/k0shk0sh/FastHub/issues/397

**Comment by k0shk0sh** [comment]
If you encountered that issue, please do give it few minutes and try again, it might be that github is doing some maintenance or shit that only god knows. *#GitHubShouldPayMeForAllThis* :D

**Comment by zvirja** [comment]
Thank you for the time you spend on this! :+1:

Will try tomorrow and will see whether I'm able to reopen the issue mentioned above (I still can't). If that's indeed GitHub issue, we'll need to report it to  them so they can fix this. It's very inconvenient if you cannot close/reopen half of your own issues via API.. :disappointed:

**Comment by zvirja** [comment]
No, I still cannot to reopen the issues mentioned above. :disappointed:
Could we register an issue for github specifying the API call I perform? I could also try to perform call via e.g. UI to see the reply.

One more question - do you have a  debug build somewhere with enabled logging? That would allow to see which exact API calls I perform..
