### ISSUE TITLE
Issue details clickable

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#95]
![screenshot_20170308-154837](https://cloud.githubusercontent.com/assets/5065698/23708622/d5ca97a6-0416-11e7-8402-16ac3a5e4bdd.png)
Issue details are clickable but don't provide any action.
The focus highlight also exceeds the view bounds as seen in the screenshot.
The actions should lead to the label/milestone/... the user clicked.

**Comment by HeinrichReimer** [comment]
And I suggest not to use the chat bubble for the issue status notes. I would rather display them on the same layer as the background to emphasize the issue comments if they'll be displayed in the same stream (#94)

**Comment by HeinrichReimer** [comment]
One side note: the text "Vor" in German should only be uppercase when it is a separate sentence (like for the issue comments) but not when used in the middle of a sentence (like in the issue activity)

**Comment by k0shk0sh** [comment]
Thats an Android bug tho lol as i'm using `DateUtils.getRelativeTimeSpanString` to display the date.
for #94 we will discuss about it there.

**Comment by HeinrichReimer** [comment]
So you made the items not clickable?

**Comment by k0shk0sh** [comment]
yup, only those who have commit reference via close, reference or merge shall be clickable the rest will not.

**Comment by HeinrichReimer** [comment]
OK thanks! Well it would be cool if you could also link to labels and milestones.
BTW is the hover background clipping issue fixed then too?

**Comment by k0shk0sh** [comment]
@HeinrichReimer now only the bubble is clickable however since there is an arrow at the end, you will notice the foreground drawable been drew on it, I guess there is not possible solution for it unless I created a different .9patch which has selection.

**Comment by HeinrichReimer** [comment]
It's possible without using a nine patch.
Check this: https://developer.android.com/training/material/shadows-clipping.html#Shadows

**Comment by HeinrichReimer** [comment]
Regarding the German uppercase issue:
As a quick fix you could just replace the first letter with its lowercase opponent.
I guess that would be right in many other languages too.
