### ISSUE TITLE
ARN

### ISSUE THREAD

**Issue by Dahnark** [k0shk0sh/FastHub#951]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

<--Please submit your request in english.-->

When I try to see this file I get an ARN

https://github.com/lapism/SearchView/commit/99c6bc7732e646c38ce23c7ab0e119707984ed7f

**Comment by yakov116** [comment]
@Dahnark ARN??

![](https://i.imgur.com/8ynikMC.png)

All good here

**Comment by Dahnark** [comment]
I think I shared a bad url, it is not the commit, it is the full SearchView.java file. I can't get it, ARN all times

**Comment by yakov116** [comment]
@Dahnark ARN?

**Comment by k0shk0sh** [comment]
I opened the full file and it works fine, I guess its ur phone that is low on battery or ur webview is not updated. anyway this is duplicated and hopefully will be solved soon.
