### ISSUE TITLE
Typo in german strings.xml: line 194

### ISSUE THREAD

**Issue by vaginessa** [k0shk0sh/FastHub#956]
**FastHub Version: 4.2.0**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S4  
---

<--Please submit your request in english.-->

In the german translation of strings.xml is a typo in line 194.
There is a ":" before the "&"

 wrong:
```
<string name="behavior">Verhalten :\& Aussehen</string>
```

fixed:
```
<string name="behavior">Verhalten \& Aussehen</string>
```

**Comment by yakov116** [comment]
@vaginessa Thanks i will fix it soon
