### ISSUE TITLE
code inside wiki

### ISSUE THREAD

**Issue by EX867** [k0shk0sh/FastHub#957]
**FastHub Version: 4.2.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note4  
---

> `<test> <y>`

works in here(editor), but in wiki, 
> `off <y> <x>`

this thing shows only
> `off`

this can be a bug...

**Comment by yakov116** [comment]
@EX867 link to repo?

**Comment by EX867** [comment]
https://github.com/EX867/PositionWriter/wiki/Commands
This is that file.

2017. 9. 11. 08:05에 "yakov116" <notifications@github.com>님이 작성:

**Comment by k0shk0sh** [comment]
could u make a simple wiki page that produce that? as I couldn't really get you and the wiki file is quite large to find what u mentioned & understand.

**Comment by EX867** [comment]
here is that :
https://github.com/EX867/PositionWriter/wiki/test

Github website and fasthub


2017. 9. 11. 14:27에 "Kosh Sergani" <notifications@github.com>님이 작성:

could u make a simple wiki page that produce that? as I couldn't really get
you and the wiki file is quite large to find what u mentioned & understand.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/k0shk0sh/FastHub/issues/957#issuecomment-328419166>,
or mute
the thread

**Comment by Jjagg** [comment]
Seems like code block content is not escaped and the stuff between angled brackets is parsed as an HTML tag. I came across a markdown document (not a wiki page) where all text after an unescaped `<S>` in a code block was rendered with strikethrough. 

Link: https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst
