### ISSUE TITLE
Issue not viewable by me

### ISSUE THREAD

**Issue by vadviktor** [k0shk0sh/FastHub#958]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

I am a member of an organisation and owner of a repo there. When I try to set labels on a newly created ticket, I get the toast message, that I can't view it. Clearly I can read and comment on it. If you need more info feel free to contact me.   @vadviktor

**Comment by k0shk0sh** [comment]
follow up with #952
