### ISSUE TITLE
Popover close bug 

### ISSUE THREAD

**Issue by J05HI** [k0shk0sh/FastHub#959]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8 
---

If you click outside of this, the element triggers the click.
Instead the popover should be closed.
![](https://i.imgur.com/f0NBRr1.jpg)

**Comment by yakov116** [comment]
@k0shk0sh maybe gray out the screen too.

**Comment by k0shk0sh** [comment]
@yakov116 it doesn't make sense.

could you please elaborate? when u touch outside the menu it should be closed and that's what is happening. so I'm unsure what you referring to!

**Comment by yakov116** [comment]
@k0shk0sh When you click the FAB you should not be able to click on any menu item. It should be grayed out.

**Comment by yakov116** [comment]
@k0shk0sh look at the picture in #390 you will see the way its grayed out.

**Comment by k0shk0sh** [comment]
I don't like it that way & the way currently implemented is unique. live with what you have.

**Comment by yakov116** [comment]
@J05HI SInce you can scroll or do anything else at this point we will not fix/correct it.

Thanks for your feedback
