### ISSUE TITLE
Pinned repositories list not updated in user menu after pinning

### ISSUE THREAD

**Issue by sm-g** [k0shk0sh/FastHub#960]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** P9  
---

Need to close/open app

**Comment by yakov116** [comment]
@sm-g did you try pull down refresh?

**Comment by sm-g** [comment]
Yes, not work. Also why this should be need?

11 сент. 2017 г. 4:46 ПП пользователь "yakov116" <notifications@github.com>
написал:

**Comment by yakov116** [comment]
@sm-g Just to double check your talking about in the menu bar? Or in the pinned repo menu itself?

**Comment by k0shk0sh** [comment]
simple solution, toggle the user menu and it will update.

**Comment by sm-g** [comment]
> Just to double check your talking about in the menu bar? Or in the pinned repo menu itself?

The menu near my username.

Strange thing is that I'm cannot reproduce this now.

**Comment by yakov116** [comment]
@sm-g That menu may take some time until it updates

**Comment by k0shk0sh** [comment]
not really, the secret to it to work is that you have toggle the user menu only then it will be refreshed

**Comment by yakov116** [comment]
@k0shk0sh I guess that is what you mean by 
>There are more stuff are not mentioned, find them out 😛

**Comment by k0shk0sh** [comment]
yep lol.
