### ISSUE TITLE
[FR]issue template

### ISSUE THREAD

**Issue by maple3142** [k0shk0sh/FastHub#962]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

same as title
Is that possible to load issue template of project when creating issue?

**Comment by k0shk0sh** [comment]
Its possible, however: 

1-  an API call is required. 
2- a search must be made to get the file.
3- once the file is found,  make another API to get its content. 
4- render it. 

Its too much to do for reporting an issue, as a user you'll be as well frustrated. so i'm sorry about that :D

**Comment by yakov116** [comment]
@maple3142 Thank you for your feedback!
