### ISSUE TITLE
Markdown viewed as a code doesn't have correct syntax highlighting

### ISSUE THREAD

**Issue by NinjaWolf064** [k0shk0sh/FastHub#963]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S8+  
---

When viewing a README.md for one of my repositories as code, the syntax highlighting wasn't for markdown.

**Comment by k0shk0sh** [comment]
url to file please!!

**Comment by yakov116** [comment]
@NinjaWolf064 I am closing the issue as you have not provided the link to the repo. Please feel free to post the link so we can reopen.

Thanks for your feedback
