### ISSUE TITLE
Missing forked repo

### ISSUE THREAD

**Issue by singh5** [k0shk0sh/FastHub#964]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** HMD Global  
- **Brand:** Nokia  
- **Model:** 6  
---

In my repositories I'm missing a private repo that I forked from a GitHub classroom organization.

**Comment by k0shk0sh** [comment]
please read the faq about organization in fasthub readme. you need to ask your org to Grant access to fasthub
