### ISSUE TITLE
Add a progress bar when sending a comment

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#966]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

Currently when you post a comment to an issue/PR visually nothing happens after you pressed the "Send" button (arrow). It's very inconvenient as you don't know whether you actually tapped the button or not. It's also possible to press the button again and as a result you will post a duplicated comment.

Could you please change the behavior so that when I press the "Send" button, you show the progress bar and don't allow to press the button again. Only after the message has been posted/failed, you allow to interact with the field again.

Thank you :blue_heart:

**Comment by yakov116** [comment]
@zvirja great idea. Think we should show a spinning circle. 

Thanks for your feedback

**Comment by zvirja** [comment]
@k0shk0sh Have you seem this? You haven't triaged it..
