### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by WildOrangutan** [k0shk0sh/FastHub#968]
Hey,

I've noticed an issue with scrolling, when Android's animations are turned off (Developer options -> Animation scale 0x). Basically what happens is that that header layout closes instantly and messes up with scrolling. 
This issue seems to be present only on"README" "tab".
I've attached gif video of the problem.

**FastHub Version:** 4.2.0 
**Device Information:**
- Xiaomi Redmi 3 @ API 25 (LineageOS 14.1)
- AVD @ API 26

![animationscroll](https://user-images.githubusercontent.com/5972966/30340749-e0bfe5aa-97f3-11e7-8f52-a19ae3d66de0.gif)

**Comment by k0shk0sh** [comment]
Really good explanation with details :). 

Thanks for reporting this, i'll try and fix it with weekend release :)

**Comment by k0shk0sh** [comment]
@TheAndroidMaster  any clue :D

**Comment by k0shk0sh** [comment]
Owh, so you are Peter who rated FastHub 1 star, I'm really glad that you listened to me when I said please report it in GitHub, sorry tho if I sounded harsh there, it just that you know, GitHub is meant for such things more than the review section. 

Salute for opening the issue here :)

**Comment by WildOrangutan** [comment]
Well yeah, 2 stars :) Sry about that, was feeling a bit frustrated at the end of the day :)
