### ISSUE TITLE
Make error toasts more user friendly.

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#97]
From an user point of view, getting toasts with texts like "timeout", "404", "connection timeout", and others I don't remember right now, are a bit annoying and not really useful.

I hope you create error messages that are more easy to understand for everyone.

Also, custom toasts are not so good imo. Either use the default Android toasts, or try to use more netural colors or colors that are actually related to the app, like the accent blue.

**Comment by k0shk0sh** [comment]
Tbh, I didn't bother much about these messages because I was like, developers who are going to use the app anyway, so they will definitely understand it lol. but you made your point tho. so hopefully it will make in 1.0.7

**Comment by xdk78** [comment]
"user friendly" 

> WE ARE DEVELOPERS WE LIKE LOGS 😄

**Comment by HeinrichReimer** [comment]
Well I think many of the toasts could be replaced by a `Snackbar`
