### ISSUE TITLE
Chinese characters garbled

### ISSUE THREAD

**Issue by ZengFanzai** [k0shk0sh/FastHub#970]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi 5  
---

<--Please submit your request in english.-->

My Chinese characters are garbled, what is your app support coding

**Comment by yakov116** [comment]
@ZengFanzai in what part of the app is garbled? Picture please.

**Comment by ZengFanzai** [comment]
these pictures in your app: 
![screenshot_2017-09-13-12-31-32-687_com fastaccess](https://user-images.githubusercontent.com/14274524/30359842-1e6e85f0-9880-11e7-8f41-fa4d9b93422e.png)
![screenshot_2017-09-13-12-31-37-045_com fastaccess](https://user-images.githubusercontent.com/14274524/30359836-16d24f34-9880-11e7-8882-9cde61a7b916.png)

this is my chorme explore:
![screenshot_2017-09-13-12-31-59-514_com android ch](https://user-images.githubusercontent.com/14274524/30359862-5002f8b2-9880-11e7-9809-fac8d9476e92.png)

**Comment by k0shk0sh** [comment]
link to file. 
it's utf-8

**Comment by ZengFanzai** [comment]
OK, thank

**Comment by k0shk0sh** [comment]
link to file that having the problem of you want it to be fixed!

**Comment by ZengFanzai** [comment]
I use utf-8 solve this problem

**Comment by ZengFanzai** [comment]
it's ok
