### ISSUE TITLE
Weird animation within settings view

### ISSUE THREAD

**Issue by TheZoker** [k0shk0sh/FastHub#971]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy S7  
---

First: Great app!

I disabled all animations, but within the settings view, there is still some weird animation opening a new fragment by sliding it from the right bottom. All other views open only by sliding from the right site.

**Comment by k0shk0sh** [comment]
could you tell me in which settings this happen? or where you exactly click?

**Comment by TheZoker** [comment]
![](https://i.imgur.com/XKgGDCI.png)

on any of these expect from the language chooser

**Comment by k0shk0sh** [comment]
owh, yeah, circle reveal for the activity launch :p

**Comment by k0shk0sh** [comment]
could you tell me what u click exactly? if I went to settings/customization/in app animation and toggle it I can't trigger any animation except for language selector which bottomSheet and this is how it behaves.

**Comment by TheZoker** [comment]
here is a video:
https://streamable.com/aevm2

I also opened an issue at the end, to show you the difference.
It's not a big animation, but rather a little one. 
The player supports a slow motion (just right click), there you can better see the animation

**Comment by k0shk0sh** [comment]
did you disable in app animation in customization settings? could you please take a screenshot of that screen?

**Comment by TheZoker** [comment]
![](https://i.imgur.com/BnzweJp.png)

**Comment by k0shk0sh** [comment]
please disable the in app animation as showing above to not see any animation.

**Comment by TheZoker** [comment]
Oh you're right. I thought I need to disable it, to disable it :smile:
