### ISSUE TITLE
Add option to customize homescreen

### ISSUE THREAD

**Issue by Kimi-Arthur** [k0shk0sh/FastHub#972]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** MI MAX  
---

For example, let homescreen show pinned repos or news from these repos.

**Comment by yakov116** [comment]
@Kimi-Arthur I have discussed this with @k0shk0sh some time ago. 

The app is designed to be like github. Just like github the first page is the feed so we will copy.

Thank you for your feedback.

(I will leave it open for @k0shk0sh's input)

**Comment by k0shk0sh** [comment]
I don't that this is a good idea tho, sorry but this won't be implemented :)
