### ISSUE TITLE
[FR] Load repo main when long pressing a feed item

### ISSUE THREAD

**Issue by yakov116** [k0shk0sh/FastHub#973]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** HTC  
- **Model:** Nexus 9  
---

Many times i need to access a repo that is in my feed, but i don't need the item that is in the feed.

Adding an option for long press would be nice

**Comment by k0shk0sh** [comment]
this closed with 4448032
