### ISSUE TITLE
Getting to a repository from PR or commit

### ISSUE THREAD

**Issue by alexejk** [k0shk0sh/FastHub#975]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

So far I haven't found a way to navigate easily to a repository that the PR belongs to.
I've opened a link to PR from my email and PR is up nicely, I review it and merge. However now I want to go to the repo to check other PRs or issues. Currently I don't see a way to do this from PR or feed for that matter.

**Comment by k0shk0sh** [comment]
you should you home up ( toolbar icon <-) to navigate. 

additionally, next release will provide long press to go repos from feeds.


also you got search, you can use it and find things you want

**Comment by alexejk** [comment]
Thanks, I just found the search (dumb me) and while editing the issue you responded. By the way - great app (responding through it) so keep it up!

**Comment by k0shk0sh** [comment]
thanks for your kind words :), don't hesitate to open any other issues :)
