### ISSUE TITLE
Screen crashes due to images

### ISSUE THREAD

**Issue by sudo-suhas** [k0shk0sh/FastHub#978]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** ZUK  
- **Brand:** ZUK  
- **Model:** Lenovo Z2 Plus  
---

If a post includes embedded images, the app crashes and goes back to 1st screen when I try to open the issue or PR.

**Comment by k0shk0sh** [comment]
could you be more specific like how would I trigger that?

**Comment by sudo-suhas** [comment]
Sure @k0shk0sh. If I try to open this for example - https://github.com/okonet/lint-staged/pull/287 and try to scroll down, the screen flashes, I see the fasthub logo and am back to my feeds.

**Comment by sudo-suhas** [comment]
Awesome app btw 😄

**Comment by sudo-suhas** [comment]
Issue may not be due to images. This crashes too - https://github.com/okonet/lint-staged/pull/286. Is the issue fixed already?

**Comment by k0shk0sh** [comment]
thanks for your ticket :), I was about to reply you but my phone ran out of battery.
yep, it's not due to image but rather to tha table rendering in the comment :)
