### ISSUE TITLE
Scrolling to the bottom of a pull request closes the app

### ISSUE THREAD

**Issue by browniebroke** [k0shk0sh/FastHub#979]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

I was browsing a pull request on one of my repo and while I scrolled to the bottom, the app closed and a was back to where I was before (Slack).

I tried browsing elsewhere and come back to it, then navigated to another PR and the app was closing and re-opening immediately.

It's on a private repo if that matters.

**Comment by browniebroke** [comment]
I managed to reproduce on a public repo

**Comment by browniebroke** [comment]
![20170916_124600](https://user-images.githubusercontent.com/861044/30512032-5d706886-9add-11e7-9721-ca46799aa3b6.gif)

**Comment by k0shk0sh** [comment]
yeah I'm aware of that, it's due to the table in the comment 😅, fixed it and tomorrow release will include the fix .
thanks

**Comment by browniebroke** [comment]
Great! Thanks.
