### ISSUE TITLE
Translation Contributors. 

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#98]
I think having an app translated to many languages will make it more attractive for users from all over the world.

I recommend you using [OneSky](https://www.oneskyapp.com/) for that :)

**Comment by k0shk0sh** [comment]
cool, I will look into it are you planning to translate FastHub to specific language since you suggest it :p.

**Comment by jahirfiquitiva** [comment]
@k0shk0sh 
yeah, I would translate it to Spanish

**Comment by k0shk0sh** [comment]
that would be awesome literally. 
I will buzz you once I created an account there. 
meantime. good night for me & have a great day for you.

**Comment by xdk78** [comment]
I would translate to Polish 😄

**Comment by k0shk0sh** [comment]
@xdk78 awesome. I will buzz you too 😁

**Comment by HeinrichReimer** [comment]
Germany here 🖐️🇩🇪

**Comment by k0shk0sh** [comment]
@HeinrichReimer nicee. tnx

**Comment by k0shk0sh** [comment]
Alright guys, here is the project link. 

http://fasthub.oneskyapp.com/

Thanks :)

**Comment by dromatick** [comment]
Hit me up for French 🥖

**Comment by k0shk0sh** [comment]
@dromatick I have added French to the list, you could start by following this link: http://fasthub.oneskyapp.com/

P.S: You guys going to be credited within the app & in contribution list. 

Thanks <3

**Comment by HeinrichReimer** [comment]
So I have posted some questions about the translation on onesky

**Comment by k0shk0sh** [comment]
@HeinrichReimer yup, got them. I have answered you  regard them.

**Comment by HeinrichReimer** [comment]
I don't quite like the inflationary use of "Click here..." phrases.
Instead of "Click here to star repo." it should probably be just "Star repo" (even without the dot). This is simpler and more direct to the user.

**Comment by HeinrichReimer** [comment]
And it should be pretty obvious to users that they have to click on things to fire some actions.

**Comment by k0shk0sh** [comment]
@HeinrichReimer makes sense, you could alter the text tho, even those in English, if you see something isn't good or does not make sense, you got my permission for it.

**Comment by HeinrichReimer** [comment]
Here are some basic guidelines: https://material.io/guidelines/style/writing.html#writing-capitalization-punctuation

**Comment by xdk78** [comment]
What about that @android:string/ok

**Comment by k0shk0sh** [comment]
@xdk78  good catch, shouldn't be translatable, i'll add this flag later, @android:stuff should remain as they are.

**Comment by HeinrichReimer** [comment]
I've read once that using `@android:` strings isn't really a good practice. Better translate it yourself to avoid situations where these Android strings are translated but the rest of the app isn't.

**Comment by k0shk0sh** [comment]
@HeinrichReimer make sense too. @xdk78 mission abort, mission abort. alter them to your specific language.

**Comment by xdk78** [comment]
@k0shk0sh what? In me language OK is OK

**Comment by kutsan** [comment]
I suggest you not to use external services. We have Git and all of us here GitHub user. Why we don't use GitHub itself for translation. Like this  [livae/AppHunt-translations](https://github.com/livae/AppHunt-translations) repository? If you use this method also you can add that repository to your project as git module. Every new translation will be easy to merge without download any file or copy paste.

**Comment by dikiaap** [comment]
Indonesia ready :indonesia:

**Comment by HeinrichReimer** [comment]
Good suggestion, @kutsan

**Comment by k0shk0sh** [comment]
this issue is no longer valid to be open, now you can do it through @FastHub-translations repo. which will be better option for most of you guys.

Thank you very much for your contribution.

**Comment by kutsan** [comment]
For future translators, please take a look https://github.com/k0shk0sh/FastHub-translations
