### ISSUE TITLE
App stuck when expand large diff

### ISSUE THREAD

**Issue by maple3142** [k0shk0sh/FastHub#980]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

When trying to expand large diff details the app will stuck and crash.

example: in [link](https://github.com/maple3142/vuejs-storage/commit/efefe374cd5c7a98782b1883434f8bc2db6f8000)
click "dist/vuejs-storage.js"

open that link in mobile github website will show (diff suppressed)

**Comment by k0shk0sh** [comment]
1298 lines that's definitely a lag. and simply I can't do much about it for now.

**Comment by maple3142** [comment]
@k0shk0sh Can make it just show **(diff suppressed)** instead?
Like github website

**Comment by k0shk0sh** [comment]
it does show it as GitHub.
could you give example of what you mean? pic will be good tho

**Comment by maple3142** [comment]
@k0shk0sh
![](https://i.imgur.com/lckkgLB.png)

**Comment by k0shk0sh** [comment]
alright, that make since :) 
thanks

**Comment by k0shk0sh** [comment]
I'll be showing toast message instead. ✌️
