### ISSUE TITLE
Sound notification can not be disabled

### ISSUE THREAD

**Issue by freMea** [k0shk0sh/FastHub#982]
**FastHub Version: 4.2.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone 2 (ZE551ML)  
---

Hi,

I have enabled notification but disabled sound but the sound keeps ringing at every new notification.

Regards

Fred

**Comment by k0shk0sh** [comment]
thanks, hopefully it'll make it in today's release :)

**Comment by k0shk0sh** [comment]
will be in today's release.
