### ISSUE TITLE
Organizations remains empty

### ISSUE THREAD

**Issue by Tularis** [k0shk0sh/FastHub#983]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HTC  
- **Brand:** htc  
- **Model:** One M9  
---

I am part of an organization, and I work on the code in that organization's repositories. However I can't find my organization, nor its repositories in this app.

**Comment by yakov116** [comment]
@Tularis Please please read read read search search search before opening an issue!

Why can't I see my Organizations either Private or Public ones?
Open up github.com/settings/applications and look for FastHub, open it then scroll to Organization access and click on Grant Button, alternatively login via Access Token which will ease this setup.

Thanks for your feedback

**Comment by Tularis** [comment]
Sorry, you can't search from within the app... Will search next time

**Comment by k0shk0sh** [comment]
yes you can
![](https://i.imgur.com/YfsBwed.png)

**Comment by yakov116** [comment]
@Tularis there was no need to even search. The text I posted is in the readme.
