### ISSUE TITLE
Files are not changing in a branch change

### ISSUE THREAD

**Issue by iamsubhranil** [k0shk0sh/FastHub#985]
**FastHub Version: 4.2.0**  
**Android Version: 5.1.1 (SDK: 22)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** HM 2LTE-IN  
---

I have three branches in my VirtualMachine repo. Two of them contains C code - `c` and `library`. When I'm changing the branches from c to library, the commits tab are changing, but the files are remaining on the c branch when I'm openning them with the built in text reader.
This issue is fully reproducible on my device.

**Comment by k0shk0sh** [comment]
So, you mean, you switched branch in commits and then head to files tab and its still in library? 
if that's the case then its working as intended. commits & branches are independent from each other.
