### ISSUE TITLE
Back button navigation issue

### ISSUE THREAD

**Issue by Demivan** [k0shk0sh/FastHub#987]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3010  
---

Sometimes when navigating through repo folder structure back button goes two folders back instead of one

**Comment by k0shk0sh** [comment]
use tabs instead of back button
