### ISSUE TITLE
Jump to the first unread post

### ISSUE THREAD

**Issue by wimstefan** [k0shk0sh/FastHub#988]
**FastHub Version: 4.2.0**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Redmi Note 4  
---

When I click on an issue with unread entries in my watchlist it opens the issue always on the first post. Could you add the possibility to jump to the first unread post? That would make reading long issues quite comfortable 😏

Great app!

**Comment by k0shk0sh** [comment]
in the near future

**Comment by wimstefan** [comment]
Thank you for the swift response and nice prospect.

And sorry for the duplicate ... I was searching through the issues (with FastHub 😉) for "jump to first unread" and didn't get any results 🤔

**Comment by k0shk0sh** [comment]
you need to be mor general, because that's so specific 😅
