### ISSUE TITLE
Fasthub offers to handle link clicks for Android that it doesn't support

### ISSUE THREAD

**Issue by mturley** [k0shk0sh/FastHub#989]
**FastHub Version: 4.2.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

I clicked this link in an email I was drafting: https://github.com/mturley/uxd-exercises/graphs/commit-activity and Android offered to "Open with FastHub" but then, FastHub gives me an error "no commit found for the ref commit-activity".

Here is a screenshot of the FastHub screen I arrive at: https://i.imgur.com/BgG1haT.png

**Comment by yakov116** [comment]
@k0shk0sh we should ignore /graphs

**Comment by yakov116** [comment]
@k0shk0sh we should ignore /graphs

**Comment by the-cybersapien** [comment]
@k0shk0sh is anyone already working on this?
I'd like to contribute :grimacing:

**Comment by k0shk0sh** [comment]
@the-cybersapien no one really, you could easily fix it in SchemeParser.java.

Thanks

**Comment by Styxxy** [comment]
I think this is similar to issue #1079 .

**Comment by k0shk0sh** [comment]
@Styxxy they are different issues, I'll look into them today personally.

**Comment by k0shk0sh** [comment]
@the-cybersapien have you started on this? If so please let me know so we don't work on the same thing :p

**Comment by the-cybersapien** [comment]
I've started working on it, Will send a PR later today 😄

**Comment by k0shk0sh** [comment]
@the-cybersapien awesome thanks 💪💪

**Comment by Styxxy** [comment]
@k0shk0sh Oh ok. They look very similar at least, with same error.

**Comment by the-cybersapien** [comment]
@k0shk0sh Hey,  I've been trying to fix this. But since Android's Pattern Matcher doesn't provide a choice to ignore a certain pattern, Fasthub will still try to open unsupported path unless each of the supported ones are entered manually. 

In the LinksParserActivity and SchemeParser, I've been trying to add a fix for the commits issue, but I can't seem to even get any logs in the Studio. Can anyone help me out here?

I've tried the app on the following:
1. OnePlus X - Android N.
2. Google Pixel Emulator Android O.

**Comment by k0shk0sh** [comment]
@the-cybersapien yep no way to do it, but if you look closely you'll find me ignoring some paths and opening them manually to the browser.

also what are you building? debug/release?

**Comment by the-cybersapien** [comment]
I'm building debug, I saw that happening in the release app I downloaded from the play store. 

I've been trying to get an idea as to how it is happening, but As of now, I haven't been able to figure it out.
I'd really appreciate some hints :sweat:

**Comment by k0shk0sh** [comment]
@the-cybersapien the way I did it is a hacky, I'll fallback to opening the browser if the url is 404. 

thanks for your help tho.
