### ISSUE TITLE
Pinned repositories

### ISSUE THREAD

**Issue by PixeLInc** [k0shk0sh/FastHub#991]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

Pinned repos aren't showing up, even though on the website I have one pinned? Sorry if this is already known lol (or I'm just dumb)

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/CQ7jlcE.png)
