### ISSUE TITLE
why minmum 3 char limit? 

### ISSUE THREAD

**Issue by eromoe** [k0shk0sh/FastHub#992]
**FastHub Version: 4.2.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** Xiaomi  
- **Brand:** Xiaomi  
- **Model:** Mi Note2  
---

it is normal to search by 2 chinese chars

**Comment by k0shk0sh** [comment]
because two is too mainstream :) . 
there is a limit in the search api and therefore you have to be specific on what you looking for, three characters are good.

**Comment by k0shk0sh** [comment]
next release will be able to search with even single character. 😏
