### ISSUE TITLE
Issue with wiki

### ISSUE THREAD

**Issue by jvalentik** [k0shk0sh/FastHub#993]
**FastHub Version: 4.2.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel XL  
---

Fasthub unable to display wiki neither on Enterprise nor personal account. End always with 404

**Comment by k0shk0sh** [comment]
links always good, for Enterprise or private repos it will not work. as I'm scrapping the HTML webpage and render it manually.

**Comment by Samyoul** [comment]
Yes I'm also having a problem with a private repo's wiki.

**Comment by k0shk0sh** [comment]
Private nor Enterprise will work,  sorry about that, buts its github limitation /shrug

**Comment by Samyoul** [comment]
do you want a link to the private wiki?

**Comment by k0shk0sh** [comment]
@Samyoul no need really, as it won't work, for private repos as we need some tokens & cookies required by GitHub and this only works in browsers 😀

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
