### ISSUE TITLE
Stay in the open, unable to access the app

### ISSUE THREAD

**Issue by nihaocun** [k0shk0sh/FastHub#995]
**FastHub Version:**    <>
**Android Version:**  
**Device Information:**  
- MANUFACTURER:   
- BRAND:   
- MODEL:   
---

**Comment by nihaocun** [comment]
![screenshot_2017-09-23-17-29-17](https://user-images.githubusercontent.com/25337480/30771948-24e03818-a085-11e7-9e5a-5543d6998e0a.png)

**Comment by k0shk0sh** [comment]
why I can't see any details of your phone and model?

please don't alter them.

besides that, search before posting issue.

**Comment by nihaocun** [comment]
@k0shk0sh 现在可以了
Now we can
