### ISSUE TITLE
Organization-wide Projects

### ISSUE THREAD

**Issue by cassidyjames** [k0shk0sh/FastHub#996]
**FastHub Version: 4.3.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

I see that you added repo-level projects, which is awesome! However, my organizations use several organization-level projects to manage our workflow, and I don't believe I can get to that from within the app. For example, the URLs are `github.com/orgs/${org-name}/projects` instead of `github.com/${org-name}/${repo-name}/projects`.

**Comment by k0shk0sh** [comment]
I'm aware of that and its ready, but forgot about it

**Comment by k0shk0sh** [comment]
sorry for the abandoned status 😅

**Comment by cassidyjames** [comment]
Ha no worries. Looking forward to the next release!
