### ISSUE TITLE
Loading animation black tint background

### ISSUE THREAD

**Issue by woeijiunn88** [k0shk0sh/FastHub#998]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ZenFone3  
---

Suggestion:
Remove background black color tint of loading screen, new loading animation may more visible / easy to view if the black color tint is removed.

**Comment by yakov116** [comment]
@woeijiunn88 can you please explain what exactly your talking about?

**Comment by woeijiunn88** [comment]
@yakov116 I'm talking about the new **blue bouncing ball loading animation screen** , and my suggestion is remove the black tint behind the bouncing ball loading animation screen, to improve the visibility of the bouncing ball.

That's what I think.:joy:

Hopefully can understand what I am talking haha:joy:

**Comment by k0shk0sh** [comment]
its a easy as doing, dialog.dimBackground = false or 0 can't remember 🤷‍♂️
