### ISSUE TITLE
Option to allow history based navigation with back button

### ISSUE THREAD

**Issue by crisidev** [k0shk0sh/FastHub#999]
**FastHub Version: 4.3.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** ONEPLUS A3003  
---

Hello,
I was wondering if it would be possible to honour the order of pages visited with with fasthub when hitting the hardware back button of my phone. Currently the application is not doing it and it is quite complex to navigate using only the soft controls on the app itself. I am not proposing this as a default behavior, but as a possibility in the settings.

Thanks for the awesome job.

**Comment by yakov116** [comment]
@crisidev please search before opening an issue. 

Thank you for your feedback!

_Sent from my Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by crisidev** [comment]
Well, I did and I did it again once you closed this one. @yakov116, do you mind to link the  issue I am duplicating so I can subscribe?

**Comment by k0shk0sh** [comment]
my internet is really shitty right now and can't search, I'll be lucky if this comment was even posted lol.

Anyway,

again, how Android navigation works is different from using browser, for example.

pressing hardware backbutton will bring you back to where you left.

pressing the toolbar back buttom arrow, will navigate you up base on the context. for example, if you were in an issue, pressing that icon will open up the repo associated to that issue. and so on.

**Comment by yakov116** [comment]
#568 #272 with just one search

**Comment by crisidev** [comment]
Thanks a lot for the explanation. I am with my mobile only and with the same internet situation as @k0shk0sh. I was unable to find the issues.
